### ISSUE TITLE
This device is using NextDNS with another configuration.

### ISSUE THREAD

**Issue by Jakethethird** [nextdns/nextdns#1]
I set up a first config, then registered to save it. Set the DNS in Ubuntu 19.04 and it worked fine. But too many lists chosen and blocking is too vigorous.

Looks good, so I decided to start again, making a new config and deleting the first one.

I set the DNS addresses for the new config (confirmed multiple times) in a new network manager profile. 

But now it does not record any queries in the Analytics page, doesn't block much and I get the message: 

"This device is using NextDNS with another configuration."

This is despite having no other config - original one was deleted.

Running https://browserleaks.com/ip, it tells me I am connected to your DNS servers, consistent with the message above.

Why won't my new config work? 

Thanks!

**Comment by rs** [comment]
Are you using the daemon from this repository? If not, please contact us thru the live chat on the nextdns site.
