### ISSUE TITLE
Device names in ASUS/Merlin

### ISSUE THREAD

**Issue by iJorgen** [nextdns/nextdns#100]
Today device-names seems to be picked from the DHCP-list of leases.

The first problem with this is that you can't give the device your own name since it seems to use some default built in name that the device reports.

The second problem is that if there are any duplicates, only the one device gets a proper name and the rest are just named with a "*". I have 10 Google Home mini, but only one shows up with a proper devicename and the rest nine just with a "*". Some other devices also just shows up with a "*" since they don't seems to report any name to DHCP.

It would be much better if names were picked up from the Network Map where I can give my devices friendly names, like "Google Home kitchen". We chatted about this issue before and the information is there to pull out from NVRAM if I remember correct when we tested around.

Could this be fixed? :-)

**Comment by rs** [comment]
There are multiple sources: dhcp, mdns and /etc/hosts. On metlin, /etc/hosts.dnsmasq is used, and should contain the custom hosts you set in the UI.

**Comment by iJorgen** [comment]
There is not such file on my AC86U, so maybe another architecture?! 
I can find all my custom names here:  /jffs/nvram# cat custom_clientlist

**Comment by rs** [comment]
Interesting. What version of Merlin? What is the format of this file?

**Comment by iJorgen** [comment]
I'm testing the new 384.16 alphas now, but was the same in 384.15.

Here is a sample of the 10 first entries and I "zeroed" my Mac-addresses:
<MyCloud>00:00:00:00:00:00>0>4>><TellStick>00:00:00:00:00:00>0>24>><HP-Computer>00:00:00:00:00:00>0>35>><AppleTV-4K>00:00:00:00:00:00>0>0>><AppleTV-HD>00:00:00:00:00:00>0>0>><Netatmo-Cam1>00:00:00:00:00:00>0>5>><Verisure>00:00:00:00:00:00>0>24>><GoogleMini-Bedroom>00:00:00:00:00:00>0>31>><GoogleMini-Kitchen>00:00:00:00:00:00>0>31>><GoogleMini-Bath>00:00:00:00:00:00>0>31>>

**Comment by dave14305** [comment]
I think the agnostic way to get the info is through “nvram get custom_clientlist”. I believe on the HND platforms (aarch64), it still returns the same data even though it is physically stored in jffs. On armv7 Merlin, it’s stored only in nvram.

**Comment by mrasquinho** [comment]
+1 for this enormous improvement.
First name to be reported - custom name. If it isn't available, then do the search from DHCP, mdns etc

**Comment by lunim** [comment]
I have the hosts.dnsmasq file, but it doesn't contain my custom names, I do see them through the `nvram get custom_clientlist` command.  It would be great if this could be used to client names.

**Comment by rs** [comment]
Please test it in master

**Comment by lunim** [comment]
@rs Are there instructions on how to install from master?

**Comment by rs** [comment]
Install Go and type go build at the root of the repo.

**Comment by lunim** [comment]
@rs I've compiled the latest from master and am running it on my router (verified version is dev) but the log on my.nextdns is not showing the custom names.  I ran `nvram get custom_clientlist` before starting nextdns to verify the clients are in the list.

I don't see any errors or warnings in the nextdns or router logs.

**Comment by maghuro** [comment]
I've compiled it to, removed .exe from compiled file, uploaded it to router and set permissions, but when running it gives errors and exits.
The nextdns file that's on router is 6784 KB and the one i compiled is 8839 KB.
Something wrong isn't right :)

**Comment by rs** [comment]
You need to cross compile by setting GOOS=linux GOARCH=armv5 envs

**Comment by lunim** [comment]
You need to set some cross compile variables:

```
SET GOOS=linux
SET GOARCH=arm
SET GOARM=7
```

Then run `go build`

**Comment by maghuro** [comment]
> You need to set some cross compile variables, this is what I set:
> 
> ```
> SET GOOS=linux
> SET GOARCH=arm
> SET GOARM=7
> ```
> 
> Then run `go build`

That did the trick. @rs didn't worked.
However, as @lunim said, no errors but only getting names from DHCP and mDNS

**Comment by maghuro** [comment]
@dave14305 any ideas?

**Comment by dave14305** [comment]
> @dave14305 any ideas?

Only to verify the matching of MAC to client IP. I am running John’s fork which does not include custom_clientlist, so I cant test for myself.

**Comment by rs** [comment]
Please test again with master.

**Comment by maghuro** [comment]
Is it preventing eventual blank custom names?
Will compile tomorrow, 5am here ☺️

**Comment by lunim** [comment]
@rs I see the discovery messages for Merlin in the log now, but the my.nextdns client names are still the DNS names.  I see the DNS discovery messages in the log after the Merlin messages.

**Comment by lunim** [comment]
@rs My suspicion is that the lookup code is first matching on IP and setting the name.  The MAC lookup will only set the name if the IP lookup failed: https://github.com/nextdns/nextdns/blob/5c1ef3cb2ef2c223b10e069f59b883edb5b73ec9/run.go#L475

**Comment by lunim** [comment]
I thinks it's possibly because the lookup uses IP first and matches DNS.  It only sets the MAC lookup if the DNS had no match:

https://github.com/nextdns/nextdns/blob/5c1ef3cb2ef2c223b10e069f59b883edb5b73ec9/run.go#L475

**Comment by rs** [comment]
Good point

**Comment by iJorgen** [comment]
A question... Will everyone be able to use this improvement using the install/upgrade script `sh -c "$(curl -sL https://nextdns.io/install)"` or do we all have to self-compile in the future?

**Comment by rs** [comment]
Once released it will be installable using the installer.

**Comment by maghuro** [comment]
Perfect! Totally working and Merlin names are the first ones to be catch!

Just one thing, on DHCP sometimes nextdns discovers devices with names "*" without quotes.
Maybe you can write a rule to skip those also?
Example:
"Apr 12 09:16:32 nextdns[31057]: Discovered(DHCP) xx:xx:xx:xx:xx:xx = *"

And then on Logs website, they are shown as "*" also!

**Comment by rs** [comment]
Will do, thanks for the heads up.

**Comment by maghuro** [comment]
Thanks!
As for now, everything working flawlessly. You can close the issue.

Thanks for your hard and quick work!

**Comment by maghuro** [comment]
In fact... Just one more thing:
On DHCP discovery, there isn't a rule between fetching first mac addresses or IPs. It's all scrambled.
So I suggest to fetch first all MAC addresses, as they are unique - and IP addresses may and can change! And just then fetch from IPs
`Apr 12 09:37:25 nextdns[17706]: Discovered(DHCP) IP = Device1
Apr 12 09:37:25 nextdns[17706]: Discovered(DHCP) MAC = Device2
Apr 12 09:37:25 nextdns[17706]: Discovered(DHCP) IP = Device3
Apr 12 09:37:25 nextdns[17706]: Discovered(DHCP) IP = Device4
Apr 12 09:37:25 nextdns[17706]: Discovered(DHCP) MAC = Device1`

**Comment by rs** [comment]
The MAC takes precedence now.

**Comment by maghuro** [comment]
I don't think so..
This is a log (stripped some lines) for my device a minutes ago, using last own builded release:

> Apr 12 09:37:25 nextdns[17706]: Discovered(DHCP) LanIP = QNAP
> Apr 12 09:37:25 nextdns[17706]: Discovered(DHCP) MAC = QNAP
> Apr 12 09:37:25 nextdns[17706]: Discovered(MDNS) IPv6 = QNAP

**Comment by rs** [comment]
The different sources (DHCP, MDNS, etc.) are kept separately. The order in which they are discovered does not matter. Check you logs tab, it should now always prefer the DHCP name over IP.

**Comment by lunim** [comment]
@rs the latest build works for me, the my.nextdns logs show the custom device names

**Comment by lunim** [comment]
@rs It appears to be unable to query for new names in the client list, my system log is filled with:

```
Apr 13 10:16:40 nextdns[4211]: Discovery: clientList: fork/exec /bin/nvram: cannot allocate memory
Apr 13 10:18:40 nextdns[4211]: Discovery: clientList: fork/exec /bin/nvram: cannot allocate memory
Apr 13 10:20:40 nextdns[4211]: Discovery: clientList: fork/exec /bin/nvram: cannot allocate memory
```

**Comment by rs** [comment]
I wonder if `nvram` isn't leaking memory on each call…
