### ISSUE TITLE
Edge Router Lite (EdgeOS) - log shows old DHCP names

### ISSUE THREAD

**Issue by Tuinslak** [nextdns/nextdns#107]
Seems that logs keep showing very very old names or names at all:

<img width="1097" alt="Screenshot 2020-03-19 at 23 38 29" src="https://user-images.githubusercontent.com/306680/77085067-c7259d80-6a3a-11ea-8f6e-99062b142697.png">

These don't match the DHCP names: 

IP/logs:
<img width="328" alt="Screenshot 2020-03-19 at 23 39 18" src="https://user-images.githubusercontent.com/306680/77085237-03f19480-6a3b-11ea-8c3d-db17d92ec66c.png">

DHCP:
<img width="811" alt="Screenshot 2020-03-19 at 23 39 48" src="https://user-images.githubusercontent.com/306680/77085270-0c49cf80-6a3b-11ea-8fac-2ae421851354.png">

IP/logs:
<img width="265" alt="Screenshot 2020-03-19 at 23 39 59" src="https://user-images.githubusercontent.com/306680/77085285-110e8380-6a3b-11ea-97c0-744d86dabdfc.png">

Static IP:
<img width="771" alt="Screenshot 2020-03-19 at 23 40 09" src="https://user-images.githubusercontent.com/306680/77085299-18359180-6a3b-11ea-977a-7f32c510085d.png">

**Comment by rs** [comment]
Did you override those names in the router or those are names reported by the client?

**Comment by Tuinslak** [comment]
These are reported by the client. 

It's showing the names the device used the first time it connected to the network (ie default windows installation name; which is later changed) or hostnames of the first device on the network using that IP (ie IP is reused by another machine, and it's still showing an old device name that no longer exists instead of the new hostname of the machine currently using that IP).

It's probably something weird with EdgeOS but I can't find it anywhere. No reference to it except through the logs.

**Comment by gbil** [comment]
I do not know the mechanism for nextdns to acquire the hostname but it is there in the /var/run/dhcpd.leases file, eg:
lease 192.168.2.191 {
  starts 3 2020/04/15 04:37:09;
  ends 4 2020/04/16 04:37:09;
#shared-network: LAN1
  cltt 3 2020/04/15 04:37:09;
  binding state active;
  next binding state free;
  hardware ethernet MAC-ADDRESS;
  uid "\001\374I-\213&@";
  client-hostname "amazon-3ab33ba10";
}

instead in the nextdns logs I see "Device #9PQR1"  

I assume the way to go would be that nextdns logs report the hostname and not the uid

**Comment by Tuinslak** [comment]
It was based on `/etc/hosts`. EdgeOS seems to not clear the hosts file and it commonly IP addresses with multiple hostnames (ie 1.2.3.4 hostname1, 1.2.3.4 hostname2, etc). 
Once it detects a new host or a changed hostname EdgeOS just adds a line.

NextDNS uses the first hostname that matches the IP it can find. So that's why it keeps on showing old hostnames. 

Ideally it should look for the last entry in the hosts file.

Clearing the hosts file solved the problem (but will surely reappear at some point).
