### ISSUE TITLE
EdgeOS - only about ~65% of traffic goes through DoH or DoT

### ISSUE THREAD

**Issue by Tuinslak** [nextdns/nextdns#108]
Looking at analytics for the last 30 mins it's showing:

One single host (both IPv4 and IPv6):

<img width="558" alt="Screenshot 2020-03-19 at 23 44 33" src="https://user-images.githubusercontent.com/306680/77085695-a90c6d00-6a3b-11ea-980b-fdae3516c011.png">

All hosts* are set to use DHCP DNS (which is gateway, and then uses NextDNS on EdgeOS).

<img width="572" alt="Screenshot 2020-03-19 at 23 46 29" src="https://user-images.githubusercontent.com/306680/77085853-e07b1980-6a3b-11ea-9b0c-378b9862bb32.png">

Any particular reason not everything is going through DoH? 

*) the only exception is Firefox on some devices, using DoH directly builtin.

**Comment by rs** [comment]
The cli will never send unencrypted traffic to NextDNS. Did you setup UDP IPs on your router in addition to the CLI daemon? It is possible that your router is not using the local CLI daemon for its own resolutions for instance.

**Comment by Tuinslak** [comment]
No specific UDP settings set up. 

It has forwarding DNS servers set up::

`yeri@sg-erl:~$ show dns forwarding nameservers 
-----------------------------------------------
   Nameservers configured for DNS forwarding
-----------------------------------------------
2a07:a8c0::34:e8d8 available via 'optionally configured'
2a07:a8c1::34:e8d8 available via 'optionally configured'
45.90.28.118 available via 'optionally configured'
45.90.30.15 available via 'optionally configured'

-----------------------------------------------
 Nameservers NOT configured for DNS forwarding
-----------------------------------------------
172.17.5.36 available via 'dhcp eth0'
172.17.5.68 available via 'dhcp eth0'`

But if I don't configure these, it seems to be using my ISP DNS servers for some % of the queries. How to check whether my router is using the local daemon?

**Comment by rs** [comment]
This is UDP. Basically, your router will send DNS queries to us using UDP. If you want to have your router going thru the CLI, set DNS fowarding to 127.0.0.1.

**Comment by Tuinslak** [comment]
Hmmm okay. That seems to work but then there's no more caching?

dig'ging google.be several times one after another shows a query time of ~250ms every single time? 


–
Kind regards
Yeri Tiete
yeri@tiete.be
+65 9225 0750


On 21 March 2020 at 09:34:16, Olivier Poitrey (notifications@github.com) wrote:

This is UDP. Basically, your router will send DNS queries to us using UDP. If you want to have your router going thru the CLI, set DNS fowarding to 127.0.0.1.

**Comment by rs** [comment]
That would be crazy latency. What do you get for `nextdns log`?

This setup wouldn’t change caching configuration anyway.

**Comment by Tuinslak** [comment]
dig from my mac to the NextDNS IPv4 address: https://pastebin.com/99AAk6JQ (seems to trace to Frankfurt and not a local Singapore server). 

dig from my mac to my gateway: https://pastebin.com/4cbvxvN9

–
Kind regards
Yeri Tiete
yeri@tiete.be
+65 9225 0750


On 22 March 2020 at 02:16:36, Olivier Poitrey (notifications@github.com) wrote:

That would be crazy latency. What do you get for nextdns log?

This setup wouldn’t change caching configuration anyway.

**Comment by Tuinslak** [comment]
Log:

``
yeri@sg-erl:~$ /config/nextdns/nextdns log
-- Logs begin at Sun 2020-03-22 11:54:15 +08, end at Sun 2020-03-22 12:25:02 +08. --
Mar 22 11:54:28 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-9
Mar 22 11:54:28 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-9
Mar 22 11:54:39 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-10
Mar 22 11:54:39 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-10
Mar 22 11:54:41 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-11
Mar 22 11:54:41 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-11
Mar 22 11:54:58 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-12
Mar 22 11:54:58 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-12
Mar 22 11:55:15 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-13
Mar 22 11:55:15 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-13
Mar 22 11:55:28 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-14
Mar 22 11:55:28 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-14
Mar 22 11:55:33 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-15
Mar 22 11:55:33 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-15
Mar 22 11:55:43 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-16
Mar 22 11:55:43 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-16
Mar 22 11:57:37 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-17
Mar 22 11:57:37 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-17
Mar 22 11:57:57 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-18
Mar 22 11:57:57 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-18
Mar 22 11:58:00 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-19
Mar 22 11:58:00 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-19
Mar 22 11:58:20 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-20
Mar 22 11:58:20 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-20
Mar 22 11:58:31 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-21
Mar 22 11:58:31 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-21
Mar 22 11:58:55 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-22
Mar 22 11:58:55 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-22
Mar 22 11:59:23 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-23
Mar 22 11:59:23 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-23
Mar 22 11:59:32 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-24
Mar 22 11:59:32 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-24
Mar 22 11:59:45 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-25
Mar 22 11:59:45 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-25
Mar 22 12:00:00 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-26
Mar 22 12:00:00 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-26
Mar 22 12:01:02 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-27
Mar 22 12:01:02 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-27
Mar 22 12:01:38 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-28
Mar 22 12:01:38 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-28
Mar 22 12:04:15 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-29
Mar 22 12:04:15 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-29
Mar 22 12:04:33 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-30
Mar 22 12:04:33 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-30
Mar 22 12:04:55 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-31
Mar 22 12:04:55 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-31
Mar 22 12:06:12 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-32
Mar 22 12:06:12 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-32
Mar 22 12:06:49 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue
Mar 22 12:06:49 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue
Mar 22 12:06:51 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-1
Mar 22 12:06:51 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-1
Mar 22 12:07:02 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-2
Mar 22 12:07:02 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-2
Mar 22 12:07:13 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-3
Mar 22 12:07:13 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-3
Mar 22 12:07:24 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-4
Mar 22 12:07:24 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-4
Mar 22 12:07:35 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-5
Mar 22 12:07:35 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-5
Mar 22 12:09:19 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-6
Mar 22 12:09:19 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-6
Mar 22 12:09:23 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-7
Mar 22 12:09:23 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-7
Mar 22 12:09:49 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-8
Mar 22 12:09:49 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-8
Mar 22 12:10:08 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-9
Mar 22 12:10:08 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-9
Mar 22 12:10:19 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-10
Mar 22 12:10:19 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-10
Mar 22 12:10:32 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-11
Mar 22 12:10:32 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-11
Mar 22 12:10:34 sg-erl nextdns[7579]: Connected [2401:c080:1400:40af:5400:2ff:fe99:8afa]:443 (con=4ms tls=108ms, TLS13)
Mar 22 12:10:54 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-12
Mar 22 12:10:54 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-12
Mar 22 12:11:00 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-13
Mar 22 12:11:00 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-13
Mar 22 12:11:26 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-14
Mar 22 12:11:26 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-14
Mar 22 12:11:48 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-15
Mar 22 12:11:48 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-15
Mar 22 12:12:12 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-16
Mar 22 12:12:12 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-16
Mar 22 12:12:16 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-17
Mar 22 12:12:16 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-17
Mar 22 12:13:24 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-18
Mar 22 12:13:24 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-18
Mar 22 12:14:23 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-19
Mar 22 12:14:23 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-19
Mar 22 12:14:26 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-20
Mar 22 12:14:26 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-20
Mar 22 12:15:08 sg-erl nextdns[7579]: Discovered(MDNS) 2404:e801:200e:334::1 = sg-erl
Mar 22 12:15:08 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.1 = sg-erl
Mar 22 12:15:09 sg-erl nextdns[7579]: Discovered(MDNS) fe80::7a8a:20ff:fe7f:4292 = sg-erl
Mar 22 12:15:13 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-21
Mar 22 12:15:13 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-21
Mar 22 12:15:17 sg-erl nextdns[7579]: Connected 66.42.58.195:443 (con=4ms tls=142ms, TLS13)
Mar 22 12:15:25 sg-erl nextdns[7579]: Endpoint failed: https://vultr-sin-1.edge.nextdns.io#66.42.58.195,2401:c080:1400:40af:5400:2ff:fe99:8afa: roundtrip: context deadline exceeded
Mar 22 12:15:25 sg-erl nextdns[7579]: Connected 45.90.28.0:443 (con=157ms tls=236ms, TLS13)
Mar 22 12:15:25 sg-erl nextdns[7579]: Switching endpoint: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::
Mar 22 12:15:30 sg-erl nextdns[7579]: Endpoint failed: https://vultr-sin-1.edge.nextdns.io#66.42.58.195,2401:c080:1400:40af:5400:2ff:fe99:8afa: roundtrip: context deadline exceeded
Mar 22 12:15:53 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue
Mar 22 12:15:53 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue
Mar 22 12:18:22 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-1
Mar 22 12:18:22 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-1
Mar 22 12:18:25 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-2
Mar 22 12:18:25 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-2
Mar 22 12:18:28 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-3
Mar 22 12:18:28 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-3
Mar 22 12:18:32 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-4
Mar 22 12:18:32 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-4
Mar 22 12:18:37 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-5
Mar 22 12:18:37 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-5
Mar 22 12:19:32 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-6
Mar 22 12:19:32 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-6
Mar 22 12:19:44 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-7
Mar 22 12:19:44 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-7
Mar 22 12:19:50 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-8
Mar 22 12:19:50 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-8
Mar 22 12:20:10 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-9
Mar 22 12:20:10 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-9
Mar 22 12:20:49 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-10
Mar 22 12:20:49 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-10
Mar 22 12:21:03 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-11
Mar 22 12:21:03 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-11
Mar 22 12:21:30 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue
Mar 22 12:21:30 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue
Mar 22 12:21:54 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-1
Mar 22 12:21:54 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-1
Mar 22 12:22:05 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-2
Mar 22 12:22:05 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-2
Mar 22 12:22:17 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue
Mar 22 12:22:17 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue
Mar 22 12:23:07 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-1
Mar 22 12:23:07 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-1
Mar 22 12:23:23 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-2
Mar 22 12:23:23 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-2
Mar 22 12:24:13 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue-3
Mar 22 12:24:13 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue-3
Mar 22 12:24:36 sg-erl nextdns[7579]: Discovered(MDNS) 10.60.111.149 = TieWo-Bridge-Hue
Mar 22 12:24:36 sg-erl nextdns[7579]: Discovered(MDNS) fe80::eeb5:faff:fe00:b2f2 = TieWo-Bridge-Hue
yeri@sg-erl:~$ 
``

**Comment by Tuinslak** [comment]
There was a anycast issue for Singapore, and EdgeOS dns server needs to be set to localhost (and not NextDNS public IPs)
