### ISSUE TITLE
cli app doesnt register into nextdns online account

### ISSUE THREAD

**Issue by FernandoMiguel** [nextdns/nextdns#11]
i cant see my log activity when using the cli app and my rules are not being applied

**Comment by rs** [comment]
Can't reproduce either, are you using the last master? How does you conf look like?

**Comment by FernandoMiguel** [comment]
i build it from master. 
if you cut a new release, i can use that too.

```ini
/etc$ cat nextdns.conf
listen :53
log-queries yes
report-client-info yes
forwarder company.com=10.0.2.1,10.0.16.2
```

**Comment by rs** [comment]
I don’t see the config parameter with your config ID.

**Comment by FernandoMiguel** [comment]
I completely missed it.
Was totally not clear to me from reading the docs until you mentioned it now

**Comment by FernandoMiguel** [comment]
by adding config it works.
i can see the logs showing up with device identification which is great.

although i still see 
`●This device is using NextDNS with another configuration.`
not sure if that is the expected behaviour

**Comment by rs** [comment]
What do you get on https://test.nextdns.io?

**Comment by FernandoMiguel** [comment]
```
{
	"status": "ok",
	"protocol": "DOH",
	"client": "62.172.34.243",
	"server": "vultr-london-1",
	"clientName": "unknown"
}
```

I even set the `Currently linked IP` to the office one

**Comment by rs** [comment]
Looks like your config id is still not in the config.

**Comment by FernandoMiguel** [comment]
upgrading now to 
`nextdns version 1.1.0`
let me retest

**Comment by FernandoMiguel** [comment]
```json
{
	"status": "ok",
	"protocol": "DOH",
	"client": "62.172.34.243",
	"server": "m247-lon-1",
	"clientName": "unknown"
}
```

```ini
$ cat /etc/nextdns.conf
listen :53
log-queries yes
report-client-info yes
config 96f736
forwarder company.com=10.0.2.1,10.0.1.8
```

**Comment by FernandoMiguel** [comment]
![image](https://user-images.githubusercontent.com/168366/68575586-450de280-0464-11ea-8936-5e08bdc1e757.png)
earlier it was doing something
