### ISSUE TITLE
Problem during installation on OpenWRT 19.07.1

### ISSUE THREAD

**Issue by cadusilva** [nextdns/nextdns#111]
Installation on OpenWRT 19.07.1 doesn't go as planned.

sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: openwrt
INFO: GOARCH: mipsle_softfloat
INFO: GOOS: linux
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
(...)
Installing nextdns (1.4.23-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.1/packages/mipsel_24kc/p                                                                                        ackages/nextdns_1.4.23-1_mipsel_24kc.ipk
Configuring nextdns.
Install the GUI? [Y|n]: Y
Installing luci-app-nextdns (git-20.081.71863-12f0dac-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.1/packages/mipsel_24kc/l                                                                                        uci/luci-app-nextdns_git-20.081.71863-12f0dac-1_all.ipk
Configuring luci-app-nextdns.
sh: /usr/bin/nextdns: not found
NextDNS Configuration ID: XXXXX
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: Y
Only use DNS servers located in jurisdictions with strong privacy laws.
This may increase latency.
sh: /usr/bin/nextdns: not found
Enable hardened privacy mode (may increase latency)? (y/n): n
Changes DNS settings of the host automatically when nextdns is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically configure host DNS on daemon startup? [Y|n]: Y
sh: /usr/bin/nextdns: not found
ERROR: install: exit 0
i) Install NextDNS
e) Exit
Choice (default=i): e

All the trouble is about this line: `sh: /usr/bin/nextdns: not found`. I downloaded the install script and changed `/usr/bin/nextdns` to `/usr/sbin/nextdns`, from the `whereis nextdns` command, and then things went smoothly once I knew where NextDNS is installed.

Without this edit, the installation is malformed and things doesn't work as expected or intended. The device names aren't sent correctly, for example. But the DNS resolution works.

In related news: the latest version isn't in OpenWRT repo, I downloaded the .tar.gz from Github and replaced the executable manually. But it doesn't work as smoothly as the one from the repo. When I run the install script without doing this, it asks if I want to upgrade but it just reinstalls the repo version.

**Comment by thuandt** [comment]
I think problem with install script is already fixed with this commit https://github.com/nextdns/nextdns/commit/3ce71109c5e6d27febebaa5b3020fdc074938010

FYI, Binary in github is too big ~7MB

**Comment by cadusilva** [comment]
Thank you, the install script is updated and things should be smooth from now on. I have a Mi Router 3G so there's plenty of space for the binary, I'm currently using it from Github and everything is fine.
