### ISSUE TITLE
dhcpcd overwrites /etc/resolv.conf

### ISSUE THREAD

**Issue by henrywallace** [nextdns/nextdns#119]
I'm using arch linux 5.5.13-arch2-1, with nextdns 1.4.35-1 and dhcpcd 8.1.6-1.

My problem is that dhcpcd overwrites my `/etc/resolv.conf` [1], after nextdns has activated, which means my DNS configuration isn't what I want to be.

More specifically, I have the following ordering of events.
- I have `nextdns.service` enabled, my computer boots, and network.target is activated.
- Upon `nextdns run`, it "activates", and overwrites `/etc/resolv.conf` to correctly use localhost server.
- I have `dhcpcd.service` enabled, and upon some network being activated, say I run `wpa_supplicant`, it too overwrites `/etc/resolv.conf` [1]. Now, I'm not using the dns server I want to, and instead just the default one at my interface ip.

This problem isn't unique to a first time start up race. I could also choose to restart, or change my network interface, and I don't think the `nextdns.service` would not observe the change, nor do anything about it.

One solution is to just add `nohook resolv.conf` to my `/etc/dhcpcd.conf` as suggested in [1]. Another solution would be to instruct `nextdns.service` to write to `/etc/resolv.conf.head` assuming dhcpcd is used, but that feels presumptuous. Another option would be to have `nextdns.service` watch `/etc/resolv.conf` and rewrite whenever it sees a change, but that feels aggressive. I've also heard things about `resolvconf` [2], but I don't have experience there.

For now, I'm just doing the first `nohook` method and it works well for me. But I thought I'd write this issue to bring attention to it being a problem. Maybe add README info, and let users decide themselves how to resolve it.

It also smells similar to this issue: https://github.com/nextdns/nextdns/issues/33.

[1] https://wiki.archlinux.org/index.php/Dhcpcd#/etc/resolv.conf
[2] https://wiki.archlinux.org/index.php/Openresolv

**Comment by eeeple** [comment]
Another idea that's more in line with systemd's service management could be to change /etc/systemd/system/nextdns.service to something like below by adding wpa_supplicant as a wanted service by the nextdns service:

```
[Unit]
Description=NextDNS DNS53 to DoH proxy.
ConditionFileIsExecutable=/usr/bin/nextdns
After=network.target wpa_supplicant.service
Before=nss-lookup.target
Wants=nss-lookup.target 

[Service]
StartLimitInterval=5
StartLimitBurst=10
Environment=SERVICE_RUN_MODE=1
ExecStart=/usr/bin/nextdns run
RestartSec=120
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target
```
But that would only works if wpa_supplicant is started at boot, which is definitely not the case for everyone.
