### ISSUE TITLE
QNAP (Soon) - Question

### ISSUE THREAD

**Issue by ChrisColotti** [nextdns/nextdns#120]
Noticed Synology is done and QNAP is still "Soon" is there any ETA for that client? :)

**Comment by rs** [comment]
I need those devices to add support.

**Comment by ChrisColotti** [comment]
too bad I had one I could have let you borrow but I sold it :/

**Comment by thealphabonanza** [comment]
Yes, 3 years and QNAP is still showing as SOON...
