### ISSUE TITLE
Closest endpoint to VPN

### ISSUE THREAD

**Issue by maghuro** [nextdns/nextdns#121]
When nextdns script gets the nearest endpoint (https://router.nextdns.io), on Merlin, it should get the nearest endpoint to the connection we're using now.
For example, in my case, I'm using a VPN on Netherlands on router and nextdns should get Amsterdam endpoint. However, when nextdns gets endpoint, it's assuming my real IP address in Portugal and gets the nearest endpoint (Spain, Madrid).
How can I force it to route the https://router.nextdns.io request through VPN?

**Comment by rs** [comment]
If the router request is performed over the VPN, the VPN IP will be used, and you then should get an IP close the VPN IP location.

**Comment by maghuro** [comment]
Correct! The problem is that router is needed to go through wan, only clients through vpn.
But if I knew router.nextdns.io IP range, I could redirect all traffic to that range through vpn.
The problem is that domain is pointing to Google hosting ranges.... Which are kind of shared ranges (masked, as cloudflare ones)

**Comment by rs** [comment]
We could add an option to disable the router so you would always use anycast.

**Comment by maghuro** [comment]
How can anycast help me? Not very familiar with it.

**Comment by maghuro** [comment]
But if you think that'll do it, that'd perfect and please, yes!

**Comment by maghuro** [comment]
I've been reading and now I think I now how anycast works and how it is used.
After you implement the option to rely on anycast, my question is - what is your anycast network IP, so I can route it through vpn?
Thanks!

**Comment by maghuro** [comment]
Just found them
AS34939
45.90.28-31.0/24

**Comment by rs** [comment]
45.90.28.0/22
2a07:a8c0::/29

**Comment by maghuro** [comment]
> 45.90.28.0/22
> 2a07:a8c0::/29

Just those?
29-31 range are not for anycast?

**Comment by rs** [comment]
They are included in the /22

**Comment by maghuro** [comment]
> They are included in the /22

Sorry, I read 24 instead of 22 :)

**Comment by maghuro** [comment]
> We could add an option to disable the router so you would always use anycast.

Any news, @rs?

**Comment by rs** [comment]
This issue will be closed when it's done.

**Comment by rs** [comment]
You can try the parameter `forwarder` with `https://dns.nextdns.io/<config>` to force anycast.

**Comment by maghuro** [comment]
> You can try the parameter `forwarder` with `https://dns.nextdns.io/<config>` to force anycast.

Where and how Olivier?

**Comment by rs** [comment]
`nextdns config set -forwarder https://dns.nextdns.io/confid` the restart the service

**Comment by maghuro** [comment]
Completely lost internet access after restart the service...

**Comment by rs** [comment]
Try nextdns `config set -forwarder https://dns.nextdns.io#45.90.28.0/confid`

**Comment by FernandoMiguel** [comment]
*config , not confid :D

**Comment by rs** [comment]
Replace “confid” by your configuration ID.

**Comment by maghuro** [comment]
Same result, @rs . Lost internet connection (maybe can't connect to DNS server?)
What is supposed to forward to do?

**Comment by rs** [comment]
Please upgrade to 1.5.0 and try again.

**Comment by maghuro** [comment]
The correct comand is
`nextdns config set -forwarder https://dns.nextdns.io/confid#45.90.28.0`
Yet, still thinking it's not using anycast.
I connected to a vpn in Brazil, and DNS server being used is in UK.

**Comment by rs** [comment]
Please contact us on our support chat.

**Comment by maghuro** [comment]
So are you planning to add the option to force use anycast?

**Comment by rs** [comment]
As discussed, it won't fix your issue. You need to route your DNS traffic over your VPN.
