### ISSUE TITLE
ASUS-Merlin: Forward local domain queries to upstream DNS

### ISSUE THREAD

**Issue by maghuro** [nextdns/nextdns#122]
As we talked in webchat, it is necessary to be "ON" for full compatibility with Handshake tld only.

Maybe, during installing, prompt the user if it wants handshake resolving, and if yes that the installer will activate this option.

Thanks!

**Comment by maghuro** [comment]
The command to do this is:
`nvram set dns_fwd_local=1`

**Comment by maghuro** [comment]
With that fix, may I now disable the forward local domain option? 
NextDNS app on router will handle it by itself?
@rs

**Comment by rs** [comment]
Yes it should

**Comment by maghuro** [comment]
Will you release a build soon? Or I must build it to test it?

**Comment by rs** [comment]
It's a pretty large change, so I would love to have as many people as possible testing it before I cut a release.

**Comment by maghuro** [comment]
> It's a pretty large change, so I would love to have as many people as possible testing it before I cut a release.

I built by myself and tested. Completely broke my Merlin router, lost access to internet. Had do manually remove it and install the official version again.
I sent you part of the logs on webchat. It seems it's trying to get files from my desktop instead of the app itself.

**Comment by rs** [comment]
I can't find the logs, can you send them again please? Please refer this issue.

**Comment by maghuro** [comment]
Done!
