### ISSUE TITLE
Client MAC address takes precedence over (changing) IP when using subrange based endpoints

### ISSUE THREAD

**Issue by johannrichard** [nextdns/nextdns#124]
I have a setup where I forward MAC *and* IP from dnsmasq to nextdns (See details at the end for version/system info). A certain IP subnet is using a different endpoint than the remaining networks. There are no endpoints linked to specific MAC addresses set-up. With these settings, I would expect that a client roaming between subnets is always sent to the correct endpoint, based on its current IP address.

That does not seem to be the case, though. It appears that whatever I configure, a "learned" MAC address takes precedence over a (changing) IP of the same client once this client has switched for the first time to the more specific endpoint because of the changing IP. This sticks, even if the client roams back to the original IP that's using the general config. 

The expected behaviour in this case would be, that the changing IP determines which config is used (Unless of course there *is* a MAC based config set).

## Example from config
```
[...]
config 10.22.50.0/24=foo
config bar
[...]
```
## How to reproduce

- Client A is on subnet 10.22.22.0/24, nextdns uses "bar" config
- Client A switches to subnet 10.22.50.0/24, nextdns now uses subnet specific "foo" config
- Client A changes back to subnet 10.22.22.0/24 yet nextdns still uses "foo" config

## Workaround 
If I turn off `add-mac` in the dnsmasq config, the following happens (which is the expected behaviour):

- Client A is on subnet 10.22.22.0/24, nextdns uses "bar" config
- Client A switches to subnet 10.22.50.0/24, nextdns now uses subnet specific "foo" config
- Client A changes back to subnet 10.22.22.0/24 and nextdns again uses "bar" config

To me, it thus appears that the "learned" MAC address for identifying the client is taking precedence over the changing IP of the same client, even if no MAC specific endpoint is defined.

Since removing `add-mac` works around the issue, I expect it is an error on nextdns side and not dnsmasq sending a wrong (cached) client IP when roaming between subnets.

### Environment
System: OPNSense (FreeBSD) 20.1
nextdns Version: 1.4.33

**Comment by johannrichard** [comment]
Digging a bit deeper: I think the problem stems from this piece of code:

https://github.com/nextdns/nextdns/blob/a5131a8611794dad2e3e2e24c490d4554fc93926/resolver/query.go#L54

Once the query is parsed, and if `EDNS0_MAC` and `EDNS0_SUBNET` both are present, the `q.PeerIP` would in fact contain the IP address of the client. However, just after parsing, you only test for localhost and the MAC. Whether the PeerIP was set via `EDNS0_SUBNET` does not matter. 

A possible solution would be to test for both an non-empty `q.MAC` and an empty `q.PeerIP` and only then fallback to (re)setting the `q.PeerIP`:

```go
	if err := q.parse(); err != nil {
		return q, err
	}

	if peerIP.IsLoopback() && q.PeerIP == nil && q.MAC != nil {
		// MAC was sent in the request with a localhost client, it means we have
		// a proxy like dnsmasq in front of us, not able to send the client IP
		// using ECS. Let's search the IP in the arp table.
		if ip := arp.SearchIP(q.MAC); ip != nil {
			q.PeerIP = ip
		}
	}

	return q, nil
```

**Comment by rs** [comment]
Do you mean `if peerIP.IsLoopback() || q.PeerIP`?

**Comment by rs** [comment]
Note that `q.PeerIP` should never be nil. In the case of dnsmasq without `EDNS0_SUBNET`, the PeerIP is going to the actual client IP (dnsmasq) which should be `127.0.0.1`.

**Comment by johannrichard** [comment]
Ah, missed that, you’re right. Then, since `q.PeerIP` is either set to the loopback or the `EDNS0` address, it‘s even simpler. 

The line in question should probably just be `if q.PeerIP.IsLoopback() && q.MAC != nil {`.

**Comment by johannrichard** [comment]
Ah, missed that one, thanks! In that case, we can simply test for `q.Peer` not being `127.0.0.1` instead of testing `peerIP`. 

```go
if q.PeerIP.IsLoopback() && q.MAC != nil {
```
