### ISSUE TITLE
Happy eyeball disable on endpoint transport

### ISSUE THREAD

**Issue by ciokan** [nextdns/nextdns#125]
https://github.com/nextdns/nextdns/blob/c706b9c295aa65b958b91ead6e1fd741adc83071/resolver/endpoint/transport.go#L30

Would have created a quick PR but I'm not sure if you really want this value to 0(zero) or it should be set to `-1`. Your (code) comment states an intention to disable it and I also see a custom dialer that does check for fastest reply so, as per docs, I think it should be a -1:

> FallbackDelay specifies the length of time to wait before spawning a RFC 6555 Fast Fallback connection. That is, this is the amount of time to wait for IPv6 to succeed before assuming that IPv6 is misconfigured and falling back to IPv4.
> If zero, a default delay of 300ms is used. A negative value disables Fast Fallback support.

**Comment by rs** [comment]
Good catch, thx
