### ISSUE TITLE
setup-router in the config seems to bind to any available IP

### ISSUE THREAD

**Issue by owah** [nextdns/nextdns#126]
Hi Team,

I am running "nextdns version 1.4.36" on a Debian host which has a direct Internet connection and the following config:

```
listen localhost:53
config REDACTED
use-hosts true
setup-router true
auto-activate false
log-queries false
report-client-info true
detect-captive-portals false
hardened-privacy true
bogus-priv true
timeout 5s
```

In my logs I have noticed some unknown devices and upon further inspection, the attached IPs seem not to originate from my own network(s). So I checked if I am an open resolver, and indeed my machine forwards DNS requests to nextDNS.

checking ss also shows that a wildcard is used to bind:

```
ss -l | grep domain
udp     UNCONN   0        0                                                   *:domain                                          *:*                             
tcp     LISTEN   0        4096                                                *:domain                                          *:* 
```

I at first thought that the listen directive is buggy, but upon reading the settings again, I noticed that listen is ignored when using the setup-router directive.

The question I now have is, if binding to an external IP (due to wildcards) in router mode is sane behavior? And how can listening to select interfaces be achieved (as listen can't be specified multiple times)?

**Comment by rs** [comment]
When setup-router is true, listen is ignored. I will add a warning if both are set.

**Comment by owah** [comment]
Thank you for adding this. I am still interested in discussing the issue of a wildcard listener, as in some scenarios such as mine, it can result in an open resolver.

**Comment by rs** [comment]
Disable `setup-router` if you want to listen on a specific IP. On a non-router firmware, this option does not do much.
