### ISSUE TITLE
RFE: Option to disable caching of NULL query response 

### ISSUE THREAD

**Issue by Fail-Safe** [nextdns/nextdns#131]
This is a request for consideration of an enhancement, not an issue.

Would you consider adding an option to disable caching of blocked records that are returned as NULL (0.0.0.0 or ::)? The behavior would effectively emulate the result of disabling negative caching.

This would provide for caching of “good” records locally, but would also allow for:
1. Quicker resolution of newly whitelisted domains. So cache would only need to be cleared on the locally affected client host(s) without also having to restart the NextDNS client (or waiting for the TTL to expire).
2. The NextDNS blocking counters to continue tracking against blocked domain queries. Admittedly this would have the unfortunate side-effect of skewing the good vs. bad query ratio/percentages. Personally, I would still opt for being able to more quickly resolve a newly whitelisted domain at the cost of skewed metrics as it helps me keep the peace with my family. 👍

**Comment by rs** [comment]
Yes, I was thinking about it. It won’t work with blockpages tho. We could send a signal in the DoH response as a header to signify it is blocked and disable caching. This would also save the hassle of parsing the DNS RR data.

**Comment by Fail-Safe** [comment]
Great point on the blockpages--I didn't consider that as I don't use that blocking method myself. It does sound like having a signal in the DoH response would afford benefits for both blocking styles.

I was also thinking about it more after I posted earlier this morning. What if instead of a boolean toggle for caching a blocked response, it was instead a value (in seconds) for `max-block-cache-ttl` or similar syntax? This could allow something like a zero second value to disable caching of any blocked response, but if someone preferred to have maybe a 10 or 30 second TTL of a blocked response they could specify that value instead.

Having a zero second TTL would probably fit a lot of home users with multiple family members like myself where being able to fairly quickly unblock a domain is preferential. But being able to specify an alternate TTL < 300sec (as is the current default) might be beneficial to other use-cases.

Would love to hear feedback from others, too. Maybe there are other angles I am not considering here.

**Comment by rs** [comment]
We will certainly go with a more global approach. On the DoH response, you will get a header with the last modified date of the config. This date will be used to set the max age of the cache, so any cache entries older than that will be considered stale.

This will fix the stats issue and avoid crazy devices from flooding us when blocked (that why we don’t set 0 TTL.

This will also work for when you blacklist a domain already in the cache.

**Comment by rs** [comment]
For devices, I'm thinking about adding the `max-ttl` of dnsmasq that would rewrite the TTL of all the responses to a low value, making all hosts depending on the cache of the router.

**Comment by Fail-Safe** [comment]
You work fast! Do you have an estimate of when the `X-Conf-Last-Modified` header will be supported on the server side? I'll be happy to pull the updates and test whenever it's ready.

Re: devices, are you referring to the iOS/Android client apps?

**Comment by rs** [comment]
I'm referring to all clients of the CLI when running on a router. Here is the `max-ttl` parameter: https://github.com/nextdns/nextdns/commit/06fba6f4096b32ec805e0a59b175aaba69e985ec. You can test a `-cache-size=10M -max-ttl=5s` and try changing blacklist. The change should quickly make it thru the clients of you LAN without having to flush their cache AND without losing the benefit of a DNS cache.

**Comment by rs** [comment]
> **[EDIT]** So unless my eyes are deceiving me, it appears this is already working. Is that correct?

Yes indeed :)

**Comment by Fail-Safe** [comment]
> I'm referring to all clients of the CLI when running on a router. Here is the `max-ttl` parameter: [06fba6f](https://github.com/nextdns/nextdns/commit/06fba6f4096b32ec805e0a59b175aaba69e985ec). You can test a `-cache-size=10M -max-ttl=5s` and try changing blacklist. The change should quickly make it thru the clients of you LAN without having to flush their cache AND without losing the benefit of a DNS cache.

I have set a`max-ttl 5s` in my nextdns.conf file and confirmed the setting with `nextdns config`. But client queries are still showing TTL > 5s for queries.

Config:
```lang-sh
[2.4.5-RELEASE][root@pfSense-n1.home.arpa]/root: nextdns config
auto-activate false
config xxxxxx
log-queries false
max-ttl 5s
hardened-privacy false
cache-size 10MB
cache-max-age 0s
timeout 5s
setup-router false
listen :53
report-client-info true
detect-captive-portals false
use-hosts true
bogus-priv true
```

Testing with "kraft.com" (no particular reason I chose it...) added to my blacklist:
```lang-sh
[2.4.5-RELEASE][root@pfSense-n1.home.arpa]/root: dig @127.0.0.1 kraft.com

; <<>> DiG 9.14.9 <<>> @127.0.0.1 kraft.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17085
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kraft.com.			IN	A

;; ANSWER SECTION:
kraft.com.		300	IN	A	0.0.0.0

;; Query time: 34 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Apr 10 09:28:45 EDT 2020
;; MSG SIZE  rcvd: 43

[2.4.5-RELEASE][root@pfSense-n1.home.arpa]/root: dig @127.0.0.1 kraft.com

; <<>> DiG 9.14.9 <<>> @127.0.0.1 kraft.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57750
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kraft.com.			IN	A

;; ANSWER SECTION:
kraft.com.		283	IN	A	0.0.0.0

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Apr 10 09:29:03 EDT 2020
;; MSG SIZE  rcvd: 43
```

**Comment by Fail-Safe** [comment]
> > **[EDIT]** So unless my eyes are deceiving me, it appears this is already working. Is that correct?
> 
> Yes indeed :)

When can I start paying for NextDNS service? This level of customer service is outstanding and worth every penny! 💯

**Comment by rs** [comment]
That’s odd, did you restart the service?

**Comment by Fail-Safe** [comment]
Yeah, restarted it a couple times and again just now for good measure. Same behavior. Checked with another domain that’s on my blacklist and I’m seeing 300s TTL on the initial query and then it decrements from there.

**Comment by rs** [comment]
Works on my machin™:

```
rs@router:~$ nextdns config
setup-router false
cache-size 100M
use-hosts true
timeout 5s
config 10.0.1.0/24=8xxx
config 10.0.2.0/24=7xxx
config 10.0.3.0/24=dxxx
config 9xxx
log-queries true
report-client-info true
hardened-privacy false
bogus-priv true
listen :53
max-ttl 5s
detect-captive-portals false
auto-activate true
cache-max-age 0s
rs@router:~$ dig kraft.com

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> kraft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19339
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;kraft.com.                     IN      A

;; ANSWER SECTION:
kraft.com.              5       IN      A       104.209.208.151

;; Query time: 20 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Apr 10 08:03:27 PDT 2020
;; MSG SIZE  rcvd: 54
```

I’ll try to reproduce. Thx for testing.

**Comment by Fail-Safe** [comment]
Found my issue--it's on me. So sorry for causing you to lose cycles trying to reproduce the issue.

At some point the NextDNS deamon died (???) and left a dangling NextDNS process running. I just realized after replacing the existing client binary with the newly built binary (with `max-ttl` support) it would appear to start, but was failing shortly after due to port 53 already being bound to the dangling NextDNS process. Once I found and killed the old client, the new one started and is working as expected after all. Working brilliantly, to be honest!

Sorry again for any lost time. I'm a father of three and off work today, so it took me a bit to get around to digging deeper.

**Comment by rs** [comment]
Don't worry, I did not spend any time trying to reproduce it yet. Thanks for the heads up. Enjoy your off time and take care.

**Comment by Fail-Safe** [comment]
FYI, since running this latest client code, it has stopped running twice randomly. Both times running `nextdns status` has indicated "stopped" but no errors logged. Trying to see if I can figure out a pattern around it. I will probably enable `log-queries` for the time being.

**Comment by Fail-Safe** [comment]
I went ahead and updated to your v1.5.0 release. On freebsd/amd64 the v1.5.0 binary is showing as 7852032 bytes and the dev build I was testing was 7839744 bytes.

Anyway, I will let you know if I see the same issue with the service stopping on the release version.

**Comment by Fail-Safe** [comment]
The service just stopped again. Logs show normal queries up until they just stop. No errors.

I bounced my pfSense box as a next step and will see if the client stops again.

**Comment by rs** [comment]
In the system logs, do you see a crash or something? Is the daemon still running when it stops working?

**Comment by Fail-Safe** [comment]
So far it is continuing to run post-reboot. Something odd must have been going on after the other issues I was having from earlier in the day.

Hopefully it was just an issue for me and nothing bigger. 👍
