### ISSUE TITLE
Losing internet connection will cause NextDNS client on Linux to hang

### ISSUE THREAD

**Issue by kennyluk** [nextdns/nextdns#132]
Running the client on Ubuntu 18, nextdns 1.4.36

If the internet connection was lost, the client will hang, or take an reasonable amount of time to recover. running 'systemctl restart nextdns' is the only way to fix it.

No log result. (is there a way to enable logging?)

**Comment by rs** [comment]
Use `log-queries`. What do you get for `sudo nextdns log`.

**Comment by kennyluk** [comment]
Ok thanks, this happens every ~48 hours, will report when it recurs.

**Comment by kunickiaj** [comment]
I'm seeing some similar behavior on a UniFi USG. Every day or two DNS just stops working. Will enable query logging. No names are being resolved after a certain point in time or event, but unclear what that event is. End up having to restart the service.

**Comment by rs** [comment]
For ubuntu, can you try disabling systemd-resolved and point your /etc/resolv.conf to 127.0.0.1 instead of 127.0.0.53?

**Comment by kunickiaj** [comment]
![image](https://user-images.githubusercontent.com/746474/80872396-85595b00-8c66-11ea-8086-03834105b13c.png)

Here's some of what I see -- drop of DNS queries hits zero until I run `nextdns restart`

From devices, queries timeout. This is EdgeOS (UniFi version) that does have dnsmasq enabled.

**Comment by rs** [comment]
@kunickiaj I think your problem is different from the one described in this ticket. Next time it happens, open https://test.nextdns.io and make sure the status is ok and client is nextdns-cli. If not, something is getting unconfigured. Check that your host is still using your router IP as DNS and that nextdns is still the process listening on port 53.

**Comment by kunickiaj** [comment]
Thanks, I will try that next time it does, but I don't think it'll yield anything as name resolution just seems to hang. I'm not sure if its dnsmasq related or nextdns-cli related yet (though didn't start having the issue until I started using nextdns-cli). Killing and restarting the process seems to resolve the issue for about a day or so. I'll see if I can generate any other trace information.

**Comment by cesarvspr** [comment]
Still facing this, very annoying, the restart command don't works always and that very long to the dns come back to live.

**Comment by agucova** [comment]
I've been having this problem for months (and I keep nextdns updated). I've made an alias to `sudo nextdns restart` and I now have muscle memory to trigger it whenever I change networks
