### ISSUE TITLE
Request: Supress Discovered log messages

### ISSUE THREAD

**Issue by lunim** [nextdns/nextdns#135]
I'm seeing quite a few log messages for the name discovery feature.  Would it be possible to lower these to debug or add a flag to suppress the output?

Thanks!

Reference: https://github.com/nextdns/nextdns/blob/06fba6f4096b32ec805e0a59b175aaba69e985ec/run.go#L451

**Comment by FernandoMiguel** [comment]
i personally love seeing that on reconnect without running in debug
