### ISSUE TITLE
cache and upstream

### ISSUE THREAD

**Issue by FernandoMiguel** [nextdns/nextdns#136]
have a couple questions about the cache feature
i set cache to 10m
but for each
`dig AAAA google.com -6`

i see in the logs it is going upstream, not hitting the cache?
```
INFO: 13:14:23 Query ::1 UDP AAAA google.com. (qry=51/res=67) 17ms HTTP/2.0
INFO: 13:14:24 Query ::1 UDP AAAA google.com. (qry=51/res=67) 4ms HTTP/2.0
INFO: 13:14:25 Query ::1 UDP AAAA google.com. (qry=51/res=67) 13ms HTTP/2.0
```

**Comment by rs** [comment]
Do you get anything cached? Make sure the process has been restarted after setting the option.

**Comment by FernandoMiguel** [comment]
restarting worked
