### ISSUE TITLE
forwarder priority/scope

### ISSUE THREAD

**Issue by FernandoMiguel** [nextdns/nextdns#143]
I have a list of forwarders.
some with bigger scope, some with a very limited one
```
forwarder vpn.office.com.=1.1.1.1
forwarder office.com.=10.0.2.1,10.0.6.2
```

if the VPN one is set after the APEX domain, it won't be used.
if the config file has the vpn one before the office one, it works.

**Comment by rs** [comment]
First match wins. What did you expect?

**Comment by FernandoMiguel** [comment]
Scope.
If something is more precise, it would take priority over something that is a root.
