### ISSUE TITLE
Asuswrt-Merlin I Call daemon from user scripts

### ISSUE THREAD

**Issue by maghuro** [nextdns/nextdns#144]
I came to this because I was trying to restart the daemon everytime VPN is connected/disconnected, and added the line `/jffs/nextdns/nextdns.init restart` to the openvpn-event user script file.
When nextdns.init start/restart is called from services-start script file, it'll pick the localhost:port correctly and daemon starts successfully. However if nextdns.init start/restart is called from another file, let's say openvpn-event, it fails to start/restart. 

Even if manually stopped, when called from any user script file other than services-start, it assumes an ipv6 internal IP and port 53 and simply fails.
Maybe because it is assuming local ipv6 inexistent address, don't know how and where to debug properly.

Log when called from services-start:
```
Apr 14 02:19:18 nextdns[26239]: Listening on TCP/127.0.0.1:5342
Apr 14 02:19:18 nextdns[26239]: Starting discovery resolver
Apr 14 02:19:18 nextdns[26239]: Listening on UDP/127.0.0.1:5342
```

Log when called from openvpn-event, for example.
```
Apr 14 02:18:01 nextdns[25047]: Listening on TCP/[::1]:53
Apr 14 02:18:01 nextdns[25047]: Listening on UDP/127.0.0.1:53
Apr 14 02:18:01 nextdns[25047]: Listening on TCP/127.0.0.1:53
Apr 14 02:18:01 nextdns[25047]: Listening on UDP/[::1]:53
Apr 14 02:18:01 nextdns[25047]: Startup failed: proxy: tcp: listen tcp [::1]:53: bind: cannot assign requested address
Apr 14 02:18:01 nextdns.init: Stopped
```

**Comment by rs** [comment]
Is this still an issue with the last revision? Please reopen if yes.

**Comment by maghuro** [comment]
The 1.5.3? Yes, it happens the same way
