### ISSUE TITLE
Turris Omnia support

### ISSUE THREAD

**Issue by eneroth** [nextdns/nextdns#149]
I would love support for Turris Omnia/TurrisOS

```sh
# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'

ERROR: Unsupported OS: Linux
INFO: OS:
INFO: GOARCH: armv7
INFO: GOOS: linux
ERROR: Cannot detect running environment.
```

```sh
# cat /etc/os-release

NAME="TurrisOS"
VERSION="4.0.5"
ID="turrisos"
ID_LIKE="lede openwrt"
PRETTY_NAME="TurrisOS 4.0.5"
VERSION_ID="4.0.5"
HOME_URL="https://www.turris.cz/"
BUG_URL="https://gitlab.labs.nic.cz/groups/turris/-/issues"
SUPPORT_URL="https://www.turris.cz/support/"
BUILD_ID="ab9d1bf"
LEDE_BOARD="mvebu/cortexa9"
LEDE_ARCH="arm_cortex-a9_vfpv3"
LEDE_TAINTS="busybox"
LEDE_DEVICE_MANUFACTURER="CZ.NIC"
LEDE_DEVICE_MANUFACTURER_URL="https://www.turris.cz"
LEDE_DEVICE_PRODUCT="Turris Omnia"
LEDE_DEVICE_REVISION="v0"
LEDE_RELEASE="TurrisOS 4.0.5 ab9d1bf"
```

**Comment by gnyman** [comment]
Yeah that would be nice. For now I just installed it manually by downloading the armv7 tar.gz.

`./nextdns install` worked, and after stopping `kresd` (`/etc/init.d/kresd stop`) it seems to run fine.

if you reboot though kresd will be back so you have to stop it again, I have on my todo to figure out a proper fix. For I have left it in as a backup, if nextdns would stop working, rebooting the router will fall back to kresd and I can then dig into what happened when I have time.

**Comment by rs** [comment]
Fixed by https://github.com/nextdns/nextdns/commit/acadb681cf863bdbcbec5a155ed02d8ec5359be2
