### ISSUE TITLE
OpenWRT dnsmasq rebind protection

### ISSUE THREAD

**Issue by martijnkruiten** [nextdns/nextdns#151]
By default the OpenWRT package does not change the rebind protection parameter of dnsmasq. Isn't it better to do so? All 0.0.0.0 responses are considered as potential rebind attacks.

**Comment by martijnkruiten** [comment]
So what I mean is that the clients will never get a 0.0.0.0 response, because dnsmasq rejects those.

**Comment by mkincaid** [comment]
Starting in dnsmasq 2.86, 0.0.0.0 is included in dnsmasq's localhost rebind exception:
https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=blobdiff;f=src/rfc1035.c;h=24ff00dbe0584c2e453e17dc4e34fcc16324e989;hp=9f4504ee79d3d730211ab5c897881da0da990bdc;hb=4558c26fcdbea59f40af8131d6790d7283d554f3;hpb=a92c6d77dcd475579c39bdff141f5eb128e2a048

Mentioning it here as in future OpenWrt versions when this change is merged, a more parsimonious fix might be to enable the localhost exception (if it isn't already -- I think maybe it is in the default openwrt config?) vs disabling rebind protection entirely.
