### ISSUE TITLE
Request: add ability to get cache performance metrics

### ISSUE THREAD

**Issue by jwelter1971** [nextdns/nextdns#154]
Would be nice to get cache performance metrics.  Hits, misses, # of cache entries, etc.

Also option to allow these cache metrics to be dumped to the log on a interval like hourly would be excellent.

**Comment by ciokan** [comment]
> Also option to allow these cache metrics to be dumped to the log on a interval like hourly would be excellent.
A sub command to dump would make more sense rather than dumping them on intervals which would introduce even more config flags (how often, what to dump etc)
