### ISSUE TITLE
Improve the Rewrites section

### ISSUE THREAD

**Issue by wuniversales** [nextdns/nextdns#157]
Please, Improve the Rewrites section!

I wish that all the subdomains of a domain could be added with an asterisk (*)

An example, suppose I have these domains set and point to ip 0.0.0.0

`one.test.example.com - 0.0.0.0`
`two.test.example.com - 0.0.0.0`
`three.test.example.com - 2.2.2.2`
`four.test.example.com - 0.0.0.0`

among many other subdomains ...

The case, all those who redirect to the same IP.
I wish I could do it like this

`*.test.example.com - 0.0.0.0`
`three.test.example.com - 2.2.2.2`

So all subdomains point to that ip (Except subdomain four.test.example.com).

Could you implement it?

Thank you very much

**Comment by Fail-Safe** [comment]
Assuming you are referring to the web console, you might consider posting your request here: https://www.reddit.com/r/nextdns/

**Comment by rs** [comment]
We are thinking about it. As @Fail-Safe said, this repo is not the right place to discuss non cli features.
