### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by tanji** [nextdns/nextdns#16]
NextDNS outputs DNS information to syslog, which is potentially disclosing information to other users on the system.
I could write a PR but there's no configuration file right now, and no option to use flags so I am not sure how you would want it.

**Comment by rs** [comment]
There is flags and configuration. The logs are output only if the log-query option is given. Perhaps you have an old version of the binary which did not have this l’option.

**Comment by tanji** [comment]
Yes I was on 1.05 from two weeks ago I didn't see that you had added so many features. Thanks!!
