### ISSUE TITLE
EdgeOS: setup-router should ensure all dnsmasq server params are removed

### ISSUE THREAD

**Issue by chronon** [nextdns/nextdns#166]
It wasn't documented or obvious (to me at least) that for `nextdns` to work after install I needed to remove any system name servers (System -> Name Server section in EdgeOS web UI). I had the NextDNS name servers added there, so my network resolved DNS correctly, but only a small percentage was using secure DNS. Removing the system name servers (and resetting NextDNS logs) resulted in 100% secure DNS as expected 👍.

One other note, it might be worth mentioning the `nextdns` executable is installed in `/config/nextdns/nextdns` and not in any known `$PATH` for the default EdgeOS shell.

**Comment by rs** [comment]
This is not a documentation issue, but an auto setup issue. The promise is that you have nothing to do manually to install nextdns. I'll have a look.

For the PATH, I will see if nextdns can install a symlink to himself in the path on startup.
