### ISSUE TITLE
curl: not found

### ISSUE THREAD

**Issue by jooeyw** [nextdns/nextdns#167]
Installed openwrt 19.07.2 on a linksys router. This command on the instructions page for openwrt did not work initially.

sh -c "$(curl -sL https://nextdns.io/install)" 

I kept receiving this error through SSH.

curl: not found 

I had to run these commands through SSH before the command worked.

opkg update
opkg install curl

Then, sh -c "$(curl -sL https://nextdns.io/install)" worked

Maybe add those 2 commands to the instructions to make it easier?

**Comment by thuandt** [comment]
then we can use `wget` instead?
