### ISSUE TITLE
Suggestion: Make "hosts" location (also) configurable

### ISSUE THREAD

**Issue by johannrichard** [nextdns/nextdns#170]
It would probably make sense to not only work towards supporting multiple known file locations, but also to support a location that can be configured in the config. This would allow more flexibility, for example for cases like OPNsense where both `dnsmasq` and `unbound` generate special hosts files that are filled with `dhcpd` hosts and manual host overrides. 

https://github.com/nextdns/nextdns/blob/0e0eb3fe80b47dc913a1e0528cf3b3dd2b06e0a7/hosts/hosts.go#L17-L23

PS: If nothing is speaking against it, I'd be happy to contribute some code if you could point me in the right direction how to integrate the config in `hosts/hosts.go` (or give some hints what other route to take for that).

**Comment by rs** [comment]
When auto-detection is possible, I favor it over yet another config. What is the path of those other hosts files you are describing?

**Comment by johannrichard** [comment]
On OPNsense, the host overrides defined in the `dnsmasq` plugin’s  config are stored under `/var/etc/dnsmasq-hosts`:

https://github.com/opnsense/core/blob/8bfd62c876ce932b06e7b1d6bd26f2a2967e5f42/src/etc/inc/plugins.inc.d/dnsmasq.inc#L285-L289

If that could be added, that would indeed cover this particular case. However, I realize it’s a specific workaround for another problem (see below).

Thinking about it: in the long run, a proper OPNsense plugin for `nextdns` which does the host override on its own would solve the real problem and hence remove the need for this workaround. After all, the main reason I’m currently running `dnsmasq` along `nextdns` is the lack of a systematic way to define (and use) these manual host overrides in `nextdns`. Copying that functionality from `dnsmasq` for a `nextdns` plugin would be trivial, I guess.

A properly defined location for such a `nextdns-hosts` file (bad choice, I know) would then probably still be needed to be read in. 

For the records and completeness’ sake: I was wrong about pfSense‘s `dnsmasq` which seems to store the hosts overrides in `/etc/hosts` which is covered by the current script. 

I was also wrong about `unbound` on OPNsense which uses its regular config format (with `local-data` and `local-data-ptr` entries) to store manual host overrides. This is currently not covered at all if I’m not mistaken and would probably require it’s own „module“ for discovery, similar to the Merlin one?
