### ISSUE TITLE
Feature request: Set a device name per IP/MAC

### ISSUE THREAD

**Issue by tubededentifrice** [nextdns/nextdns#172]
Probably something similar to the "config" option, to give devices a friendly name:

```
friendly-name 10.0.3.2/32=My Computer
friendly-name 00:1c:42:2e:60:4a=My iPhone
friendly-name 10.0.4.0/24=Kids network
friendly-name 10.0.4.2/32=Theo
```

**Comment by rs** [comment]
You can do that by adding your custom hostnames in `/etc/hosts`. We will also add a rename capability right into the UI (cc @romaincointepas).
