### ISSUE TITLE
macOS CLI client accepts connections from LAN

### ISSUE THREAD

**Issue by emilstahl** [nextdns/nextdns#175]
Hi

If you try to resolve a domain via the Mac's LAN IP from another device on the LAN, you get a popup to allow incoming connections. If you accept, it is possible for the other client to resolve domains.

Why does the DoH CLI client accept other than local connections?

**Comment by FernandoMiguel** [comment]
> Hi
> 
> If you try to resolve a domain via the Mac's LAN IP from another device on the LAN, you get a popup to allow incoming connections. If you accept, it is possible for the other client to resolve domains.
> 
> Why does the DoH CLI client accept other than local connections?

Are you binding to localhost or to a network card?

**Comment by emilstahl** [comment]
I did not select anything, config says:
`listen localhost:53`

**Comment by emilstahl** [comment]
Whoops, did not meant to close.

This request was made from another machine on my LAN, via the client on my Mac.

<img width="766" alt="nextdns" src="https://user-images.githubusercontent.com/3885790/79805299-188cb980-8366-11ea-9edf-df8e7766785b.png">
<img width="768" alt="nextdns2" src="https://user-images.githubusercontent.com/3885790/79805304-1b87aa00-8366-11ea-89a6-ce7a6db7b278.png">

**Comment by rs** [comment]
do you have `setup-router` set to `true`?

**Comment by emilstahl** [comment]
@rs Nope.

```
config xxxxx
cache-size 300MB
report-client-info true
setup-router false
log-queries false
detect-captive-portals false
auto-activate true
listen localhost:53
cache-max-age 0s
max-ttl 0s
timeout 5s
hardened-privacy false
bogus-priv true
use-hosts true
```

**Comment by rs** [comment]
```
lsof -nP -iTCP -sTCP:LISTEN | grep :53
```

**Comment by emilstahl** [comment]
@rs 
```
$ sudo lsof -nP -iTCP -sTCP:LISTEN | grep :53
nextdns    139     root   10u  IPv6 0x1f99e7ba3496dcb5      0t0  TCP [::1]:53 (LISTEN)
nextdns    139     root   12u  IPv4 0x1f99e7ba34967345      0t0  TCP 127.0.0.1:53 (LISTEN)
```

**Comment by emilstahl** [comment]
<img width="1001" alt="Screen Shot 2020-04-21 at 12 38 06" src="https://user-images.githubusercontent.com/3885790/79856731-03974100-83cd-11ea-9bd0-454948cf4fdf.png">

**Comment by emilstahl** [comment]
@rs `UDP *:53` 
```  
$ sudo lsof -nP  | grep :53 |grep nextdns
nextdns     139               root   10u     IPv6 0x1f99e7ba3496dcb5        0t0                 TCP [::1]:53 (LISTEN)
nextdns     139               root   11u     IPv6 0x1f99e7ba34679095        0t0                 UDP [::1]:53
nextdns     139               root   12u     IPv4 0x1f99e7ba34967345        0t0                 TCP 127.0.0.1:53 (LISTEN)
nextdns     139               root   13u     IPv4 0x1f99e7ba3467937d        0t0                 UDP *:53
```

**Comment by rs** [comment]
So it is only listening on localhost and your tcpdump show that you so not answer to dns queries from the other host. I’n not sure to understand the issue.

**Comment by emilstahl** [comment]
@rs It is listening to `UDP *:53`?

The tcpdump had src set, so it won't show the answers.

The issue should be clear, nextdns should not listen/respond to queries from LAN, when not in router mode?

Full tcpdump:
<img width="1245" alt="Screen Shot 2020-04-21 at 19 01 07" src="https://user-images.githubusercontent.com/3885790/79892201-7838a280-8402-11ea-9182-a20f8ebead69.png">

**Comment by rs** [comment]
Interesting, I can reproduce with 1.5.2 but not with master.

**Comment by emilstahl** [comment]
@rs Great. Let me know if you need additional info or more testing.
