### ISSUE TITLE
hosts file use doesn't work for remote clients

### ISSUE THREAD

**Issue by gbil** [nextdns/nextdns#176]
this is quite strange and probably happened after the latest release as it was working before 

what I've done:

in the router /etc/hosts file I have a custom entry for a domain eg. www.test.com to resolved to 192.168.2.50 

what happens:

when from a client I try to reach/resolve www.test.com I get a host not found error 

when from the router itself I do a nslookup/host of www.test.com I get back the correct answer 192.168.2.50 

eg. host www.test.com 127.0.0.1  returns 192.168.2.50 

in the config file I have 

use-hosts true
listen :53 

same thing happens with listen localhost:53

**Comment by rs** [comment]
Do you have a file name `/etc/hosts.dnsmasq`?

**Comment by gbil** [comment]
no

**Comment by rs** [comment]
The `host` command is using the libc which will lookup the host in `/etc/hosts` by itself before hitting the resolver. Do test properly, use `dig @localhost www.test.com`. You can turn on `log-queries` to see if the query is going thru.

**Comment by gbil** [comment]
dig from the router itself (running nextdns cli) works just fine but the issue remains
an extra message I saw from a mac client using  nslookup is :

Got recursion not available from 192.168.2.1, trying next server

**Comment by rs** [comment]
Please try master.

**Comment by gbil** [comment]
tested with the latest release and it works
by the way, you need to allow us to start paying for the service

**Comment by rs** [comment]
It's imminent :)

**Comment by gbil** [comment]
I'm afraid I need to reopen this because I still don't get the proper reply. Here is the strange part from a tcpdump
<img width="1503" alt="Screen Shot 2020-05-06 at 14 29 53" src="https://user-images.githubusercontent.com/32446126/81172531-1736d000-8fa7-11ea-9e78-1f5d1d23c809.png">

while the answer is in the reply, the reply code is no such name

**Comment by gbil** [comment]
@rs can you please have a look
