### ISSUE TITLE
Feature request: Persist settings on Analytics and Logs tabs

### ISSUE THREAD

**Issue by mbrinton01** [nextdns/nextdns#178]
On the Analytics tab it's possible to select a time period from a dropdown:
<img width="181" alt="analytics" src="https://user-images.githubusercontent.com/10635536/80112898-3ebd7f80-8547-11ea-8e3e-78183e97d3b7.png">

Each time the tab is loaded this setting is lost and resets to the default of 'Last 30 Days'. It should persist as the user changes tabs.

On the Logs tab it's possible to toggle the view to view Blocked Queries only:
<img width="185" alt="logs" src="https://user-images.githubusercontent.com/10635536/80113077-72000e80-8547-11ea-92b2-5d7ee0666434.png">

Each time the tab is loaded this setting is lost and resets to the default of disabled. It should persist as the user changes tabs.

**Comment by rs** [comment]
Thanks for your feedback. Closing as this repository is not about the UI.
