### ISSUE TITLE
Linux installer fails on update but works for initial install

### ISSUE THREAD

**Issue by ChrisColotti** [nextdns/nextdns#180]
Seems to run fine but then this:

```
Total download size: 3.0 M
Downloading packages:
nextdns_1.5.3_amd64.rpm        FAILED                                          
https://nextdns.io/repo/rpm/nextdns_1.5.3_amd64.rpm: [Errno 14] HTTPS Error 302 - Found0% [                                                                            ]  0.0 B/s |    0 B  --:--:-- ETA 
Trying other mirror.


Error downloading packages:
  nextdns-1.5.3-1.x86_64: [Errno 256] No more mirrors to try.

ERROR: upgrade: exit 0
```
You can remove and install fresh with no issue but this is the only OS I have had this issue with upgrades using the same script

**Comment by rs** [comment]
What is your distribution?

**Comment by scafroglia93** [comment]
@ChrisColotti 
You miss some info LoL in the past issue 

CentOS

**Comment by ChrisColotti** [comment]
Yes centOS on this one.  It’s odd b/c you can remove and install new fine but that’s the error on upgrade.

**Comment by jostyee** [comment]
same issue on Raspbian buster, too.

**Comment by rs** [comment]
Please confirm it's fixed

**Comment by ChrisColotti** [comment]
@rs still same error on CentOS

Error downloading packages:
  nextdns-1.5.4-1.x86_64: [Errno 256] No more mirrors to try.

**Comment by rs** [comment]
Does it solve it if you run this command and try again: `yum clean all`?

**Comment by ChrisColotti** [comment]
@rs  no same end result....very odd

'''Upgrade  1 Package

Total download size: 3.0 M
Downloading packages:
nextdns_1.5.4_amd64.rpm        FAILED                                          
https://nextdns.io/repo/rpm/nextdns_1.5.4_amd64.rpm: [Errno 14] HTTPS Error 302 - Found0% [                                                                            ]  0.0 B/s |    0 B  --:--:-- ETA 
Trying other mirror.


Error downloading packages:
  nextdns-1.5.4-1.x86_64: [Errno 256] No more mirrors to try.

ERROR: upgrade: exit 0
'''

**Comment by ChrisColotti** [comment]
so oddly, I did a sudo rum remove nextdns to re-install to get 1.5.6 and now te only version it will grab from the repo is 1.5.5 but says 1.5.6 is an upgrade, but still can't grab it.  I updated 2 macs and a Unifi USG just fine though...

**Comment by rs** [comment]
Last release got an error with bintray rollout. 1.5.5 is identical to 1.5.6 anyway. This will be fixed with next rev.

**Comment by ChrisColotti** [comment]
This is still an issue on CentOS 7 but not Ubuntu

```
Dependencies Resolved

====================================================================================================================================================================================================================================
 Package                                                Arch                                                  Version                                                  Repository                                              Size
====================================================================================================================================================================================================================================
Updating:
 nextdns                                                x86_64                                                1.6.3-1                                                  nextdns                                                3.0 M

Transaction Summary
====================================================================================================================================================================================================================================
Upgrade  1 Package

Total download size: 3.0 M
Downloading packages:
nextdns_1.6.3_amd64.rpm        FAILED                                          
https://nextdns.io/repo/rpm/nextdns_1.6.3_amd64.rpm: [Errno 14] HTTPS Error 302 - Found             0% [                                                                                          ]  0.0 B/s |    0 B  --:--:-- ETA 
Trying other mirror.


Error downloading packages:
  nextdns-1.6.3-1.x86_64: [Errno 256] No more mirrors to try.

ERROR: upgrade: exit 0
u) Upgrade NextDNS from 1.5.8 to 1.6.3
c) Configure NextDNS
r) Remove NextDNS
e) Exit
```

**Comment by ChrisColotti** [comment]
This still seems to be an issue on some linux distros I am still seeing it on CentOS....Always have to remove and re-install
