### ISSUE TITLE
Installer on OpenWRT unable to detect latest version.

### ISSUE THREAD

**Issue by mad-it** [nextdns/nextdns#182]
Trying to run an upgrade of NextDNS to get the new caching feature and I get the following:
![image](https://user-images.githubusercontent.com/1469047/80414178-ea145e80-88d0-11ea-91d0-7877d5d94508.png)

It looks like its unable to upgrade because it does not know what the next version is.

OpenWRT version is 19.07.2

PS: went through the bash script and reverse engineering all the commands, everything needed is present:

```bash
root@OpenWrt:~# curl -s "https://api.github.com/repos/nextdns/nextdns/releases/latest" |  grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed -e 's/^v//'
1.5.3
```

**Comment by rs** [comment]
This is "expected". We need to submit a new version to the openwrt repository, it is not automated. We only submit new major version after enough revision to make sure it's stable. We will submit a 1.5 soon.

**Comment by mad-it** [comment]
@rs Thanks for the quick response. Maybe it would be a good idea to add this to the Wiki as wel that releases of OpenWRT are not in sync with the normal releases to avoid confusion.

**Comment by rs** [comment]
Probably. I was hopping to find an easy way to automate it.
