### ISSUE TITLE
Exclude dns.nextdns.io from Analytics

### ISSUE THREAD

**Issue by csousougen** [nextdns/nextdns#184]
Hi, I was using DNS-over-TLS with hardcoded IPs (forward-addr: 45.xx.xx.x#xxx.dns1.nextdns.io) and my secure dns percentage was 100%.

After switching to DNS-over-HTTPS, the percentage started to drop. 
I believe the issue is that in DNS-over-HTTPS, the domain dns.nextdns.io has to be resolved using UDP.

Could you exclude this domain from Analytics in order to measure the real traffic?

**Comment by scafroglia93** [comment]
Write this inside the "metadata" repo
