### ISSUE TITLE
Too much logging in syslog

### ISSUE THREAD

**Issue by tz1** [nextdns/nextdns#188]
60% of the entries in my OpenWRT syslog are from NextDNS, and are at "err" severity for a successful connection?  I can find no option to quench this flood of messages.

A connect should be "info", not warn or err, and there should be a way to only log warnings or above or errors or above, and that should be the default setting.

Also "nextdns --help" just lists commands, but no information on any arguments they might take or what they do.

(addresses redacted)

Thu Apr 30 09:00:54 2020 daemon.err nextdns[2310]: INFO: 15:00:54 Connected  (con=35ms tls=122ms, TLS13)
Thu Apr 30 09:01:38 2020 daemon.err nextdns[2310]: INFO: 15:01:38 Connected (con=56ms tls=144ms, TLS13)
Thu Apr 30 09:02:55 2020 daemon.err nextdns[2310]: INFO: 15:02:55 Connected  (con=55ms tls=150ms, TLS13)
Thu Apr 30 09:03:55 2020 daemon.err nextdns[2310]: INFO: 15:03:55 Connected  (con=56ms tls=142ms, TLS13)
Thu Apr 30 09:04:55 2020 daemon.err nextdns[2310]: INFO: 15:04:55 Connected (con=55ms tls=143ms, TLS13)
Thu Apr 30 09:05:55 2020 daemon.err nextdns[2310]: INFO: 15:05:55 Connected (con=57ms tls=142ms, TLS13)
Thu Apr 30 09:06:56 2020 daemon.err nextdns[2310]: INFO: 15:06:56 Connected (con=55ms tls=143ms, TLS13)

**Comment by rs** [comment]
Logging is currently to stdout and not to syslog, so we can’t control the severity.

You can get help for sub-command with `nextdns subcommand -help`

**Comment by tz1** [comment]
OK, it is probably because it is started as a daemon/service, so that layer is probably redirecting stdout.  I will have to try to redirect it.

**Comment by tz1** [comment]
That was it.  The package has procd_set_param for both stdout and stderr set to 1 (but the messages appear to be coming out via stdout)

**Comment by BrianG61UK** [comment]
So what exactly do I have to do to stop /var/log/messages filling up with loads of nextdns stuff?
