### ISSUE TITLE
Command to list help for config options

### ISSUE THREAD

**Issue by patschi** [nextdns/nextdns#191]
While in the `config.go`  there are all arguments and descriptions available, I don't see an intended way getting the output of it. I was trying to figure out what kind of config options are available and to get a more detailed description about - in my opinion that's quite helpful to understand available options more.

Currently I mis-use an invalid parameter to get the output I was looking for:
````
$ nextdns config list x
Unrecognized parameter: x
  -auto-activate
        Run activate at startup and deactivate on exit.
  -bogus-priv
        Bogus private reverse lookups.

        All reverse lookups for private IP ranges (ie 192.168.x.x, etc.) are
        answered with "no such domain" rather than being forwarded upstream.
        The set of prefixes affected is the list given in RFC6303, for IPv4
        and IPv6. (default true)
```

It would be helpful to have something like `nextdns help`  or `nextdns config list help`.

**Comment by rs** [comment]
That’s a good point. The list is on nextdns run -help, but I agree it’s not obvious when coming from the `config` sub-command.
