### ISSUE TITLE
DD-WRT & Entware

### ISSUE THREAD

**Issue by peterpme** [nextdns/nextdns#194]
Hi there,

After talking to Olivier over Intercom, dd-wrt manual setup is pretty tricky especially because the amount of ram available is very low (need to plug in external USB stick for this to work)

After talking we decided that an Entware package that automatically handles all of this for you would be great (1 less installation step), so here I am creating the issue.

Thanks!

**Comment by ilshatms** [comment]
Hi there,

Is there support for entware?

**Comment by residentcode** [comment]
> Hi there,
> 
> Is there support for entware?

Check this out, tested ok.
https://forum.dd-wrt.com/phpBB2/viewtopic.php?t=320362
