### ISSUE TITLE
EdgeOS-NextDNS fails to start at boot or after IP change

### ISSUE THREAD

**Issue by josephasmith1** [nextdns/nextdns#197]
Trouble with latest version not starting at boot on 2.0 branch of EdgeOS on Edgerouter-x. #166  Could be part of this issue. Log says the port is not available. 

Latest version of EdgeOS NextDNS also has some memory management issues on Edgerouter-X  when IP changes or DHCP renew on ipv6. #132 

My thought here is that the hang and starting issues are related because NextDNS tries to start before the ip connection has been made, and that is causing the issue or possibly not including 127.0.0.1 & ::1 in the resolv.conf file that is replaced on EdgeOS has something to do with it since ISP DNS address are leaking when the NextDNS service fails to start.

**Comment by eproxus** [comment]
I've seen similar problems on the USG as well. It frequently stops responding and `/config/nextdns/nextds` status reports `stopped`. When running `start` it just returns, and then still reports it as `stopped`. In the logs I can see
```
May 15 19:52:40 USG nextdns[32051]: Starting discovery resolver
May 15 19:52:40 USG nextdns[32051]: Listening on UDP/127.0.0.1:5342
May 15 19:52:40 USG nextdns[32051]: Startup failed: proxy: tcp: listen tcp 127.0.0.1:5342: bind: address already in use
```
The only thing that works is to run `sudo killall nextdns` and then run `start` again.
