### ISSUE TITLE
Zorin OS 15 Compatibility

### ISSUE THREAD

**Issue by Darth-Falcon** [nextdns/nextdns#199]
I have been attempting to install the NextDNS client on my Linux machines. Both of them are Running Zorin OS 15, which is based on Ubuntu 18.04 LTS. When attempting the automated installer I get the following message:
```bash
sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'
ERROR: Unsupported OS: Linux
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
ERROR: Cannot detect running environment.
```

When attempting a manual install after doing sudo apt-get update and then attempting to apt install nextdns I get this message:
```bash
sudo apt install nextdns
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  folder-color-common gir1.2-camel-1.2 gir1.2-gee-0.8 libnemo-extension1
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,178 kB of archives.
After this operation, 7,967 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/nextdns/deb stable/main amd64 nextdns amd64 1.5.4
  403  Forbidden [IP: 13.249.94.206 443]
E: Failed to fetch https://d29vzk4ow07wi7.cloudfront.net/9f35e5ac39550cefa94a224b222cbf19d11a0b0e6e91c0b53f909a96acf525ed?response-content-disposition=attachment;filename="nextdns_1.5.4_amd64.deb"&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvOWYzNWU1YWMzOTU1MGNlZmE5NGEyMjRiMjIyY2JmMTlkMTFhMGIwZTZlOTFjMGI1M2Y5MDlhOTZhY2Y1MjVlZD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMm5leHRkbnNfMS41LjRfYW1kNjQuZGViJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTg4NzA4MjUxfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=G3lt~Zvxi4hUlnVM33ZZn79Z291eddH1eEJaiEwbjvDGWWHaJ4Y6kONuLxgeyVECqfE7uc9ZQ0tO9f58JlGb8~etv~NNy73iP8hawRj9OhO9dqSklZmtltqbmY7lNQgKNcueA6uCUhU2wIZ2jKOQ1BEFuBF8knXJGJuNygRPwNgxSdOObScQFSDAlzGjg0McVuDv0FGEIpupmH5J0y161U2JH1rYZqv0MU21LYfkH8DC76yJB19y6DFzIFiOShAc4z~brMQawVV0w-rMfB6ggOC9FAiRKBv7VNZxQDkSbrltLFVKk~ppTYl4ekiO3xmT8J~kref~KN-u824Aja8UdA__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA  403  Forbidden [IP: 13.249.94.206 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Running with --fix-missing was not able to resolve the issue either.

**Context**
 - Version 1.5.4: 
 - Platform Zorin OS 15:

**Comment by rs** [comment]
What do you get if you curl `https://dl.bintray.com/nextdns/deb/pool/main/m/nextdns_1.5.4_amd64.deb` from the same machine?

**Comment by Darth-Falcon** [comment]
Nothing happens. The terminal pauses for a moment, then goes back to normal. No output.

However, I was able to manually navigate to that page, download, and install the .deb file. I just ran though the configuration with no issues and now it is installed and I believe working system wide.

**Comment by Darth-Falcon** [comment]
As an update, I am unable to `apt  upgrade` NextDNS, so I cannot update the program automatically. I can follow the same technique I did in my previous comment, I can find the version in the error log and use the page https://dl.bintray.com/nextdns/deb/pool/main/m/nextdns_X.X.X_amd64.deb where X is the version, to download the newest deb file. Then using `sudo apt install ./<file>.deb` I can update the version. It's not the best solution but it works.

**Comment by rs** [comment]
Fixed by https://github.com/nextdns/nextdns/commit/acadb681cf863bdbcbec5a155ed02d8ec5359be2
