### ISSUE TITLE
Custom blocklist with wildcard support

### ISSUE THREAD

**Issue by mark4409** [nextdns/nextdns#200]
Hi, is there any chance of adding custom blocklist support to the client to supplement the blocklists already available on the servers? At the moment I'm using DNSCrypt-proxy (also Go-lang) on my router rather than your client simply due to this feature. I know you can add custom domains on your web interface, which is ok when you only have a handful of extra domains to block - but when you have a hundred, it's not a very efficient way to do it. Wildcard support would also allow for blocking keywords. This is especially useful with torrent sites that frequently get blocked and reappear again with a new tld. It would be far more efficient to be able to add `thepiratebay.*` or `*torrent*` to a custom blocklist.

In the shorter term, maybe a bulk add option could be added in the web interface?

**Comment by rs** [comment]
https://help.nextdns.io/en/articles/3941197-custom-blocklist-support

**Comment by mark4409** [comment]
Ok, I see why bulk upload of custom lists isn't possible, fair enough. I was really talking about client side though using the CLI client, and and using a custom wildcard blocklist within that in the same way that DNSCrypt does. It would be a useful feature - especially for those using the client on a router.  If you don't wish to implement this then it's no problem as you support DNSCrypt and I can continue using this functionality in their client. It's a shame though as I do like your clients ability to identify different clients on the network and send them off to different configurations.

**Comment by rs** [comment]
With the CLI you can do that with /etc/hosts, the cli will use it as an overlay.
