### ISSUE TITLE
Nextdns keeps discovering the same client repeatedly

### ISSUE THREAD

**Issue by jmehd** [nextdns/nextdns#202]
Nextdns keeps discovering the same client repeatedly. I have rebooted the router, as well as the device that's being discovered.

Excerpt of the System Log: [system log.txt](https://github.com/nextdns/nextdns/files/4589766/system.log.txt)

Top output: [top.txt](https://github.com/nextdns/nextdns/files/4589770/top.txt)

**Context**
 - Nextdns version 1.5.4 
 - Platform: Asus RT-AC86U with ASUS-Merlin Firmware Version: 384.17

**Comment by jmehd** [comment]
Update: I've had to revert the router firmware to a previous version (384.16) due to wireless instability on the 2.4GHz channel. The discovery issue still persists on the previous version of the router firmware.

Additionally, I've noticed when the router is rebooted, nextdns discovers the device using the name I've set in the router for it:
May  6 22:48:49 nextdns[5632]: Discovered(Merlin) 08:a6:bc:**:**:** = FireStick4_***b28d

However, a few seconds later, the log shows the discovery of the same device using MDNS:
May  6 22:49:20 nextdns[5632]: Discovered(MDNS) 192.168.1.126 = ***b28d
May  6 22:49:31 nextdns[5632]: Discovered(MDNS) 192.168.1.126 = ***-home-lan

**Comment by rs** [comment]
The log will show all the names discovered thru the different protocols, but some protocols will take precedence. The names discovered thru Merlin will take precedence on any other discovery method.

**Comment by jmehd** [comment]
Makes sense. However, the device still keeps being discovered as described in my original ticket.
