### ISSUE TITLE
NextDNS cannot get all the device names

### ISSUE THREAD

**Issue by Xtreme512** [nextdns/nextdns#204]
I'm using NextDNS on my OpenWrt device that is acting like an access point connected to my Mikrotik router, and I can't get device names to appear on the web site at all, or they appear wrong.

If I disable dnsmasq forwarding, even the OpenWrt access point loses its name on the web site log. So I need dnsmasq prior to NextDNS.
If I set NextDNS to listen on 127.0.0.1, I lose discovery services.
If I set NextDNS to listen on its APs IP 192.168.1.253:5342 with dnsmasq listening on localhost 127.0.0.1:53, I get the AP's name and I get several device names as well but only via mDNS and not all of them.

My guess is I need NextDNS to talk to my DHCP server which is in my router, but this is not possible AFAIK. Is there any other way I could try? Is there anyone who has the same config and suffers from the same situation?

 **- Version [NextDNS 1.4.23]: 
 - Platform [OpenWrt 19.07.2]:**

**Comment by Xtreme512** [comment]
I reseted the OpenWrt, installed the latest NextDNS CLI, set it to listen on 192.168.1.253:5342, set dnsmasq forwarder to it, then populated the /etc/hosts and it worked.

**Comment by marcov** [comment]
For me reporting client info on OpenWRT is still broken. I am using dnsmasq as local resolver, that forwards request to nextdns via localhost.

To make it work I have to force `enableDiscovery := true` here:

https://github.com/nextdns/nextdns/blob/cb5ed3a50078d674735d8c9c152b87f7db6f0c7d/run.go#L286-L290
