### ISSUE TITLE
Unable to use NextDNS client (installed on Ubuntu 18.04) as DNS for Unify SG

### ISSUE THREAD

**Issue by goodale** [nextdns/nextdns#208]
I've successfully installed the latest version of NextDNS on an Intel NUC running Ubuntu 18.04.  I updated the DNS on the Ubiquity Unify WAN to point to the NUC but once provisioning is complete nothing is able to resolve. 

details:
NextDNS Client running on 192.168.1.226
Unify Security gateway running on 192.168.1.1
WAN DNS set to 192.168.1.226

Am I missing something in this config?

**Comment by rs** [comment]
from a client, what do you get for `dig chaos @192.168.1.226 test.com`.

**Comment by goodale** [comment]
it was my error.  the bind address was already being used by systemd-resolve.   I discovered this by running nextdns status.

Once I stopped systemd-resolve i was able to start nextdns and everything worked.

Perhaps an enhancement of the installer is to automatically stop systemd-resolve and remove it from starting on boot.

**Comment by rs** [comment]
This is planned with the `setup-router` flag.
