### ISSUE TITLE
Should stop nextdns service or tell user to stop nextdns

### ISSUE THREAD

**Issue by AdityaTelange** [nextdns/nextdns#21]
https://github.com/nextdns/nextdns/blob/ecec00df87cd3fa1ecc729070105f154d975795a/.goreleaser/preremove.sh#L3

lead to 
https://github.com/nextdns/nextdns/issues/20

**Comment by rs** [comment]
Was fixed in yesterday’s release. Do you still experience this?

**Comment by AdityaTelange** [comment]
Sir, I faced it while it was updating .

**Comment by rs** [comment]
From a version with the issue, so it make sense. Does it still happen if you remove/reinstall the last version?

**Comment by AdityaTelange** [comment]
yes. that is what https://github.com/nextdns/nextdns/issues/20 address ,the 2nd part where i try to purge it !
