### ISSUE TITLE
hosts file use doesn't work for remote clients - part2

### ISSUE THREAD

**Issue by gbil** [nextdns/nextdns#211]
Re-opening from #176 

based on my capture the reply code is "no such name"

https://user-images.githubusercontent.com/32446126/81172531-1736d000-8fa7-11ea-9e78-1f5d1d23c809.png

**Context**
 - Version [e.g. 1.5.2]: 1.5.7
 - Platform [e.g. macOS, ASUS-Merlin]: edgeos

**Comment by JeanGionet** [comment]
I'm having the exact same issue on my OpenWRT install. Remote clients can't resolve whatever I have set in /etc/hosts
