### ISSUE TITLE
App does not launch OS X

### ISSUE THREAD

**Issue by alexjlennard** [nextdns/nextdns#213]
App does not launch on OS X Catalina 10.15.4

**Comment by lyrad87** [comment]
I'm on macOS Catalina 10.15.4 and the app is launching just fine. Do you have any more info that could help the guys to identify a problem? Or an error log? Use the `Console` app (Applications -> Utilities) and maybe it shows what may be going wrong.

**Comment by alexjlennard** [comment]
Looks like it was throwing 'address is loopback' error. After restarting the machine it seems to be working OK
