### ISSUE TITLE
(Windows) Backup dns addresses so we can restore on reset

### ISSUE THREAD

**Issue by ciokan** [nextdns/nextdns#216]
https://github.com/nextdns/nextdns/blob/a1627d6698b0764763e7c31721be1fd3dd7520a0/host/dns_windows.go#L52

This assumes the interfaces DNS addresses were on DHCP before which may not be the case. I think a backup needs to take place before activating this service so we can have a restore point when doing a reset. Do you want me to try with a PR or you're on it already?

**Comment by rs** [comment]
I thought about it, but it might be very hard to implement. If the computer crashes, the process is killed etc, there is a high risk of restoring a state that is not functional. I think 99% of the users will use DHCP, and for the 1%, they can disable auto-activate.
