### ISSUE TITLE
MacOS client leaking DNS queries

### ISSUE THREAD

**Issue by marktroberts** [nextdns/nextdns#222]
not sure is where to report this issue as it’s not directly related to the NextDNS cli code.  But i see intermittent dns quieres to 192.0.2.42 dropping on my firewall for the Mac i was testing the MacOS client on.  After disabling the packets stopped.  Seems like the vpn is not up constant and some DNS quieres are leaking out of the tunnel.

**Comment by specter78** [comment]
That is fallback behaviour. Happened with me too.

This was why I shifted to nextdns cli.

**Comment by marktroberts** [comment]
Not sure i would consider it fallback as the IP space is reserved for test networks.  So how would it be a fallback?

But yes, i agree that i could use cli, and i do use it on my linux box as a local lan, handing it out to clients using DHCP.  I wanted to use the mac client so the laptops would be covered when off network.  cli running on macos would not auto update via the app store, so i would need to setup patch management or write a cron job to auto update.

**Comment by rs** [comment]
It updates with homebrew on mac.

**Comment by FernandoMiguel** [comment]
> It updates with homebrew on mac.

It's still a manual step

But then again, even apple store requires manual intervention

**Comment by romaincointepas** [comment]
@marktroberts We're trying to figure this thing out right now. Did this happen by any chance after a battery died -> plugging in the laptop -> macOS showing the *restoring* thingy?

Also, are you seeing the issue right after restarting the mac (and before a battery dies event)?

**Comment by marktroberts** [comment]
It was on my son’s laptop.  it was way to frequent to be a dead batter situation.  more likely coming in and out of sleep.
