### ISSUE TITLE
Support resolution of dnsmasq dhcp client names with cache enabled

### ISSUE THREAD

**Issue by kunickiaj** [nextdns/nextdns#223]
When dnsmasq is used for dns and dhcp on many routers, local clients can be resolved. When enabling the caching feature of the nextdns cli, local dhcp client names are no longer resolvable.

For some static hosts, it's possible to add a manual entry in the NextDNS configuration to return local addresses, but that has its own limitations.

It would be great to pass through local queries to dnsmasq.

**Comment by rs** [comment]
This is planned. We don't need to pass them to dnsmasq, just use the same source to resolve them.

**Comment by kunickiaj** [comment]
Ah awesome. Do you happen to know off the top of your head where they’re sourced from usually? I may be able to submit a PR for it if that helps.
  

  
  
  

  
  
>

**Comment by rs** [comment]
It's either in the dhcp lease file or the hosts file. Don't bother, the code is mostly done already.
