### ISSUE TITLE
nextdns on edgerouter preventing ios devices from installing updates

### ISSUE THREAD

**Issue by tas50** [nextdns/nextdns#229]
I have the nextdns service 1.5.4 installed on an edgerouter and all hosts on my network are using the edgerouter's IP as their only DNS server. With this configuration iOS hosts are unable to search for iOS updates from Apple and while they find apps that need updates the apps will never start downloading. Switch the devices to LTE and everything works fine. I've checked the logs for sites being blocked and nothing is being blocked on these so it doesn't appear to be due to a Blocklist.

**Context**
 - Version:  1.5.4
 - Platform: edgerouter

**Comment by sdoyle1** [comment]
I think you are 4 versions behind have you tried updating

**Comment by tas50** [comment]
Oh yep I was way out of date. I just updated to 1.5.8 and it's still an issue.

**Comment by ThePowerOfDreams** [comment]
Restart your iOS device and try again.

**Comment by tas50** [comment]
Rebooted and iOS updates and app updates continue to fail w/o anything blocked in the logs.

**Comment by rs** [comment]
Please check your logs tab on my.nextdns.io to see if some apple domains aren't getting blocked.

**Comment by tas50** [comment]
@rs I've been using the logs to try to troubleshoot some of these problems. Here's the logs from when I try to check for updates on my phone:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/1015200/82517196-7af5e880-9ad1-11ea-8791-e8e5eb01c8ec.png">

**Comment by rs** [comment]
Focus on what's blocked (the checkbox)

**Comment by tas50** [comment]
Nothing has been blocked. I removed all block lists when I started troubleshooting this.

**Comment by Alex82719** [comment]
I have the same issue with 4G and the ios app .. all apple apps are not working (app store is not loading, also apple testflight and wheater app are not updating). I checked the logs several times and nothing is blocked.

**Comment by rs** [comment]
Can you guys please try to disable the ECS feature in the settings tab, restart your iPhone and try again?

**Comment by Alex82719** [comment]
You mean EDNS? Anonymized EDNS Client Subnet?

**Comment by rs** [comment]
Yes

**Comment by tas50** [comment]
@rs That fixed it!

**Comment by Alex82719** [comment]
Ok, disabled setting, closed all apps, restarted and opened app store. same issue. Checked my logs (only for may ipad), a lots of apple domains are resolved, nothing blocked. I have this with all my ios devices.

**Comment by Alex82719** [comment]
Just saw tas50 comment .. also checked my iphone, its not working. When I disable Vpn in the app its instantly working ...

**Comment by rs** [comment]
Can you please contact us on the support chat?

**Comment by Alex82719** [comment]
Ok, now I solved it .. I turned EDNS on again.. when I enable hardend privacy mode my resolver is from switzerland, app store is not working ... disable privacy mode, switch to frankfurt, germany and now my app store is working .. maybe a geo blocking? or is something wrong with the resolver? ..

**Comment by rs** [comment]
Apple is doing some strange things… Can you resolve the `iosapps.itunes.g.aaplimg.com` domain with and without the setting that fixed your issue @Alex82719 and @tas50 and give me the IPs?

It would also be useful if you could give me the result of this (with ECS on): 

https://dns.nextdns.io/<your conf id>?class=chaos&name=iosapps.itunes.g.aaplimg.com

Please send it to team@nextdns.io (it will contain your IP).

**Comment by Alex82719** [comment]
Sorry, I wasn‘t at home, so I can‘t do ping or something.

But today I tested it again and have no more issues. Maybe apple fixed it or it was resolved with our app update? From my side the issue can be closed. Thanks for your help, yearly pro subscription is ordered! :)
