### ISSUE TITLE
hosts file use doesn't work for remote clients - part3 - v1.6.3

### ISSUE THREAD

**Issue by gbil** [nextdns/nextdns#231]
I have to open this bug again as it still doesn't work with 1.6.3 

previous bug: https://github.com/nextdns/nextdns/issues/211 

**Context**
 - Version [e.g. 1.5.2]: 1.6.3
 - Platform [e.g. macOS, ASUS-Merlin]: EdgeOS

Still the same issue, together with the actual reply, the reply code: no such name is returned which breaks the resolution for multiple clients 
<img width="1297" alt="dns3" src="https://user-images.githubusercontent.com/32446126/82979476-cdfafe80-9fef-11ea-9992-e58a7e182661.png">

**Comment by rs** [comment]
With `nextdns discovered`, do you see the domain in the hosts section?

**Comment by gbil** [comment]
yes 

    "hosts": {
        "HOSTNAME.": [
            "192.168.2.50"
        ],

**Comment by rs** [comment]
You replaced it by a all caps domains it comes this way?

**Comment by gbil** [comment]
sorry just to be clear, the actual hostname is in the form xxx.xxx.xxx , I just replaced it here with HOSTNAME for privacy reasons

**Comment by tubededentifrice** [comment]
I think I'm getting the same behavior, basically the DNS server can't resolve it's own name.
In my config, I've:
`use-hosts false`

And `nextdns discovered` returns:

```
        "dns1.": [
            "127.0.1.1",
            "192.168.1.133",
            "192.168.1.220",
            "192.168.1.223",
            "192.168.1.226",
            "192.168.1.233",
            "192.168.1.243"
        ],
        "dns1.mydomain.com.": [
            "127.0.1.1"
        ],
        "dns2.": [
            "192.168.1.134",
            "192.168.1.221",
            "192.168.1.224",
            "192.168.1.227",
            "192.168.1.234",
            "192.168.1.244"
        ],
        "dns3.": [
            "192.168.1.135",
            "192.168.1.222",
            "192.168.1.225",
            "192.168.1.228",
            "192.168.1.235",
            "192.168.1.245"
        ],
```

In this case (taken from dns1), when I'm trying to resolve `dns1.mydomain.com` I'm getting a NXDOMAIN, even though it's properly configured at mydomain.com (no problem to resolve dns2.mydomain.com and dns3.mydomain.com) ; on dns2, I can resolve dns1.mydomain.com and dns3.mydomain.com, etc. (just to be clear, they are all using the same config).

To me, it looks like it's using the `hosts` file even though the config says otherwise (maybe to load the friendly names of other devices I'm pushing there), and something translates 127.0.0.1 to NXDOMAIN.
This is quite a new issue as before it was able to resolve itself properly.

**Comment by rs** [comment]
If use-hosts is false, the hosts file won't be used for resolution. The hosts file will still be used for discovery if you turned on report-client-info tho. Try turning use-hosts on if you want resolution to work.

**Comment by tubededentifrice** [comment]
Just to be clear, I don't want to have hosts file resolution. If hosts isn't the cause, then I don't know what's causing the behavior I described. The DNS domain I'm trying to resolve are actual domains and the records exists.

**Comment by tubededentifrice** [comment]
(hiding my comment, nextdns service was using wrong conf after updating)

**Comment by gbil** [comment]
> You replaced it by a all caps domains it comes this way?

the issue I reported though is still there

**Comment by neodc** [comment]
Any news on this ?

**Comment by gbil** [comment]
Still valid testing again master

**Comment by rs** [comment]
Please provide more info on the issue, with example hosts file and failing query.

**Comment by gbil** [comment]
> Please provide more info on the issue, with example hosts file and failing query.

not sure what more can I provide. I've provided even the network capture where it is shown that the result is returned but with a reply code: no such name

**Comment by rs** [comment]
What is the content of the hosts file and which query is performed?

**Comment by gbil** [comment]
here is with a dummy entry: test.test.com
hosts file content
`192.168.2.50    test.test.com`

result
`nslookup test.test.com
Server:		192.168.2.1
Address:	192.168.2.1#53

** server can't find test.test.com: NXDOMAIN`

capture
<img width="891" alt="test test com" src="https://user-images.githubusercontent.com/32446126/85035598-0b385380-b18c-11ea-9070-eca275d80c33.png">

actual issue, android devices fail to access the site . testing with mac on the other hand works

**Comment by rs** [comment]
Do you have `use-hosts` set to true in the config?

**Comment by gbil** [comment]
> Do you have `use-hosts` set to true in the config?

since day 1

use-hosts true

besides if that wasn't true, the reply wouldn't appear in the capture

**Comment by rs** [comment]
You would get a nxdomain just like your capture.

Is the cli listening on the port 53 directly or do you have something like dnsmasq in front of it?

**Comment by gbil** [comment]
Just the cli is listening on port 53. As this is on an edgerouter the nextdns sets the default dnsmasq on port 0 during activation

**Comment by neodc** [comment]
> You would get a nxdomain just like your capture.

The response has the nxdomain flag set but contain the correct info as can be seen the the Answers part of the capture, so everything is working except the nxdomain flag is incorrectly set.

**Comment by rs** [comment]
Oh I missed that. Next time, be clear about which part I should look at :)

**Comment by neodc** [comment]
Any update ? Do you have an idea of when it could be fix ?

**Comment by rs** [comment]
Can you please test master and validate it's fixed?

**Comment by gbil** [comment]
> Can you please test master and validate it's fixed?

YES it works now, just compiled and tested it and works fine

brilliant
