### ISSUE TITLE
EdgeOS missing post install step in docs - quick fix

### ISSUE THREAD

**Issue by zalberico** [nextdns/nextdns#232]
I tried to add this to the wiki, but I think editing is restricted. I also don't think I can submit a pull request since it's the wiki?

Anyway:
I put the answer here: https://www.reddit.com/r/nextdns/comments/grbasq/edgeos_configuration/

After installing on EdgeOS (the USG) it was super smooth and worked great, but you have to update your WAN settings in the Unifi controller to set the DNS servers to 127.0.0.1 or devices that don't have the NextDNS app installed don't work.

This was non-obvious for me and took a while to figure out, but would be a two second thing to include in the docs and would probably help a lot of people.

**Comment by gbil** [comment]
please note that what you mention is explicit configuration for USG not EdgeOS devices in general. on Edgerouters for example the nextdns script already sets the dns server properly in /etc/resolv.conf and nothing more is needed on the UI side

**Comment by DuncanKeyes** [comment]
I will say, I also had the issue for my edgerouter needing me to manually set the DNS IP in my DHCP pool to my router IP of 192.168.1.1 for it to work. Sounds like that is unintended though.

**Comment by gbil** [comment]
> I will say, I also had the issue for my edgerouter needing me to manually set the DNS IP in my DHCP pool to my router IP of 192.168.1.1 for it to work. Sounds like that is unintended though.

That is no the same issue actually. The first post refers to a change that needs to be made in the UI of USG in order for USG itself to use nextdns as the DNS resolver. What you mention is a change in the DHCP server of edgerouter in order for DHCP client to use the edgerouter as DNS resolver which in turns uses nextdns on 127.0.0.1 (localhost) as a DNS resolver.

**Comment by zalberico** [comment]
Thanks for the clarification - some indication that there another configuration step is likely required would be helpful. I’d be happy if it was there for each device, seems likely something others will hit?

**Comment by zalberico** [comment]
Could I get wiki write access? I’m happy to add it myself.

**Comment by rs** [comment]
Just for me to understand, you're saying the "auto-activate" does not currently work on USG? You want the USG itself to use the NextDNS daemon. Can you confirm that by default, you did not have to change anything for your LAN hosts to work?

If the activate does not work, we need to find how to fix it instead of adding a manual step in the wiki. I would be interested to know what's different about the USG here. Can you confirm that, without changing anything in the UI, the /etc/resolv.conf is pointing to 127.0.0.1 when NextDNS is started?

**Comment by zalberico** [comment]
I'm not sure I understand what you mean about auto activate, I'll try and confirm (specific steps of what I did are below). I'm guessing the WAN DNS setting in the UI is supposed to be related to `/etc/resolv.conf`? (My networking knowledge is pretty weak). I think after install the NextDNS was definitely doing something since the behavior did change, sites just wouldn't load.

 - SSH into USG
 - Run the curl command listed in the docs, follow the super simple install steps with defaults (this worked great)

Expectation:
 - I can now use the internet on all my networked devices with NextDNS handling DNS.

Reality:
 - My devices with the NextDNS app already installed (laptop, iPhone) worked, but all other devices failed to load any pages.

Fix:
 - I had to go into the USG cloud config UI and set `127.0.0.1` for the DNS server settings for the WAN. I use a Ubiquiti cloud key to manage this, but that's just so I don't have to manually plug into the USG (I don't think the cloud key causes this extra step).
 - This was non-obvious and I was lucky I found it mentioned on that random website I link  in  my reddit comment.

Misc:
 - Prior to setting `127.0.0.1` in these fields they were blank.

**Comment by rs** [comment]
Ok so if I understand correctly:
* This is not an USG but a CloudKey, which apparently runs a very different OS
* This is a bug with the setup-router which does not support this OS well
* Setting this parameter will most likely just point the dnsmasq (or whatever is running dns on this thing) to the running nextdns instance.

Can you please show the result of the following commands:
* `nextdns config`
* `netstat -lnpe | grep 53`

**Comment by zalberico** [comment]
To confirm I ran it on the **USG** itself.

I *think* the Cloud Key is probably irrelevant, but I just included it for clarity in case there are unknown unknowns I'm unaware of. I think the Cloudkey just lets me connect to the management UI without having to be on the network itself, but I think the UI is the same without it.

Command output below:
```
nextdns config
use-hosts true
setup-router true
auto-activate true
control /var/run/nextdns.sock
bogus-priv true
hardened-privacy false
timeout 5s
report-client-info true
cache-max-age 0s
max-ttl 0s
detect-captive-portals false
log-queries false
cache-size 0
listen localhost:53
config 346b3f
```

```
netstat -lnpe | grep 53
(No info could be read for "-p": geteuid()=1000 but you should be root.)
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      0          10985038    -               
tcp        0      0 127.0.0.1:5342          0.0.0.0:*               LISTEN      0          10951314    -               
tcp6       0      0 :::53                   :::*                    LISTEN      0          10985040    -               
udp        0      0 127.0.0.1:5342          0.0.0.0:*                           0          10951316    -               
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           0          10951320    -               
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           0          10951317    -               
udp        0      0 0.0.0.0:53              0.0.0.0:*                           0          10985037    -               
udp6       0      0 :::5353                 :::*                                0          10951322    -               
udp6       0      0 :::5353                 :::*                                0          10951319    -               
udp6       0      0 :::53                   :::*                                0          10985039    -               
unix  2      [ ACC ]     STREAM     LISTENING     10313053 -                   /tmp/ubnt.socket.statsd
```

Thanks for iterating on this with me.

**Comment by rs** [comment]
Please run the second command as root (with sudo or su first).

**Comment by zalberico** [comment]
```
sudo netstat -lnpe | grep 53
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      0          10985038    13966/dnsmasq   
tcp        0      0 127.0.0.1:5342          0.0.0.0:*               LISTEN      0          10951314    5423/nextdns    
tcp6       0      0 :::53                   :::*                    LISTEN      0          10985040    13966/dnsmasq   
udp        0      0 127.0.0.1:5342          0.0.0.0:*                           0          10951316    5423/nextdns    
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           0          10951320    5423/nextdns    
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           0          10951317    5423/nextdns    
udp        0      0 0.0.0.0:53              0.0.0.0:*                           0          10985037    13966/dnsmasq   
udp6       0      0 :::5353                 :::*                                0          10951322    5423/nextdns    
udp6       0      0 :::5353                 :::*                                0          10951319    5423/nextdns    
udp6       0      0 :::53                   :::*                                0          10985039    13966/dnsmasq   
raw6  294912      0 :::58                   :::*                    7           101        1330        753/zebra       
unix  2      [ ACC ]     STREAM     LISTENING     10313053 10098/ubnt-util     /tmp/ubnt.socket.statsd
unix  2      [ ACC ]     STREAM     LISTENING     417      753/zebra           /var/run/quagga/zserv.api
unix  2      [ ACC ]     STREAM     LISTENING     419      753/zebra           /var/run/quagga/zebra.vty
```

**Comment by rs** [comment]
`cat /etc/dnsmasq.d/nextdns.conf` while nextdns is running.

**Comment by zalberico** [comment]
```
cat /etc/dnsmasq.d/nextdns.conf
# Configuration generated by NextDNS
no-resolv
server=127.0.0.1#5342
add-mac
add-subnet=32,128
```

**Comment by rs** [comment]
There is something I'm missing. Everything should work out of the box, and setting 127.0.0.1 as WAN DNS like you do should just break all your devices that don't run a DNS server locally. On one of your LAN device, what do you get as DNS from DHCP?

**Comment by zalberico** [comment]
When I test on this site I get that NextDNS is handling DNS: https://www.dnsleaktest.com/results.html.

I get this result on a laptop with the NextDNS app turned off.

In case you haven't had a chance to look, this is the website where I found the original instruction to change the WAN DNS setting to point to localhost (which I think tells the controller to look at the USG to find the DNS server, which it then does find in the form of the NextDNS app? at least that was my guess).

I'm not sure how to check DNS from DHCP, is there some specific thing you want me to do?

Maybe this is related to using the cloud key controller somehow? It is a pretty common thing for people with USGs to use.

**Comment by rs** [comment]
Do you have a macOS or a linux (or any unix) running on that LAN?

**Comment by zalberico** [comment]
Yes - most of the devices are macOS (there’s one windows machine).

**Comment by rs** [comment]
On one of your mac, please execute: `ipconfig getoption "" domain_name_server`

**Comment by zalberico** [comment]
```
ipconfig getoption "" domain_name_server
192.168.1.1
```

**Comment by rs** [comment]
What do you get if you load https://test.nextdns.io in your browser?

**Comment by zalberico** [comment]
I redacted some of the potentially identifying details, but let me know if you need them for some reason.
```
{
	"status": "ok",
	"protocol": "DOH",
	"configuration": "fp1d6370b555e7e70f",
	"client": "<redacted>",
	"destIP": "104.238.181.28",
	"server": "vultr-sjc-1",
	"clientName": "nextdns-mac",
	"deviceName": "<redacted>",
	"deviceID": "<redacted>",
	"deviceModel": "Apple MacBookAir8,2"
}
```

**Comment by rs** [comment]
Please disable the nextdns mac app first.

**Comment by zalberico** [comment]
What are you looking for?

```
{
	"status": "ok",
	"protocol": "DOH",
	"configuration": "fp1d6370b555e7e70f",
	"client": "<redacted>",
	"destIP": "104.238.181.28",
	"server": "vultr-sjc-1",
	"clientName": "nextdns-cli",
	"deviceName": "<redacted>",
	"deviceID": "<redacted>",
	"deviceIP": "192.168.1.232",
	"deviceModel": "mac:f8:ff:c2"
}
```

**Comment by rs** [comment]
This is with setting 127.0.0.1 for WAN DNS on the cloud key or without?

**Comment by zalberico** [comment]
This is with it set (which is when the network works). I can break it and retest if you want.

**Comment by rs** [comment]
Yes please

**Comment by zalberico** [comment]
Roommates are using internet, but I should be able to test later tonight.

**Comment by zalberico** [comment]
Interesting, so have to removing the `127.0.0.1` address from the DNS fields in the WAN setting it still remains working now.
```
{
	"status": "ok",
	"protocol": "DOH",
	"configuration": "fp1d6370b555e7e70f",
	"client": "<redacted>",
	"destIP": "104.238.181.28",
	"server": "vultr-sjc-1",
	"clientName": "nextdns-cli",
	"deviceName": "<redacted>",
	"deviceID": "RK3TF",
	"deviceIP": "192.168.1.232",
	"deviceModel": "mac:f8:ff:c2"
}
```

This definitely was not the case when I initially set it up (where prior to saving the address in the DNS fields it would not resolve on devices without the app).

Maybe it setting the address forced it to update something?

I had tried multiple browsers, incognito, as well as restarting the USG prior to finding that website that suggested the address change, but none of those prior things worked.

**Comment by zalberico** [comment]
It appears to work now with or without that DNS address set, this site seems to claim that setting the address forces the USG to use only the NextDNS secure (as opposed to making two DNS queries, one to NextDNS and one maybe via the ISP?).

I've put the address back for now, but let me know if there's anything else I can do to help. I'm a happy pro user, and the service has been great so far.

**Comment by augoisms** [comment]
I am in the same boat with my USG. If I do not set my WAN DNS to `127.0.0.1` it does not work. If I keep refreshing https://test.nextdns.io I mostly get "unconfigured" but every now and then I'll get a status ok (protocol: DOH, clientName: nextdns-cli). Another refresh and it's back to unconfigured. 

Oddly, the UI at https://my.nextdns.io is saying that my resolver is Cloudflare. I had previously set my  WAN DNS to Cloudflare, but at this point I would expect it to either be NextDNS or my ISP. All Cloudflare addresses have been removed. It seems like there is something fighting again the default NextDNS configuration.

Likely a separate issue, but I'll mention briefly in case there are any clues... with the WAN DNS set to `127.0.0.1` everything will work fine for a few days and then stop suddenly. I will then issue a `stop` command and when I try to `start` I get permission errors. I cannot start, uninstall, install, etc. The only resolution is to restart the USG.

```
@USG3P:~$ nextdns start
Error: /config/scripts/post-config.d/nextdns.sh start: exit status 1: /config/scripts/post-config.d/nextdns.sh: line 29: /tmp/nextdns.pid: Permission denied
Error: proxy: tcp: listen tcp 127.0.0.1:5342: bind: address already in use
```

**Comment by ThePowerOfDreams** [comment]
> Oddly, the UI at https://my.nextdns.io is saying that my resolver is Cloudflare.

Which DNS servers are specified in the DHCP leases that are being handed out on your network?

**Comment by augoisms** [comment]
I get my router
```
$ ipconfig getoption "" domain_name_server
10.0.1.1
```

**Comment by ThePowerOfDreams** [comment]
Then your router is still configured to use Cloudflare, and is passing the requests from local machines on to them.

**Comment by augoisms** [comment]
I did some more digging and it appears that the USG is provisioned by default with Cloudflare's IP if you do not specify any DNS servers ([source](https://community.ui.com/questions/USG-DNS-problem/e7833719-9dd6-4530-a54c-9ee535df081a#answer/e84f60ef-e2df-46b7-9219-1c2597abd647)).

Without any DNS servers:
```
@USG3P:~$ sudo cat /etc/dnsmasq.conf
#
# autogenerated by vyatta-dns-forwarding.pl on Sat May 30 08:57:28 PDT 2020
#
log-facility=/var/log/dnsmasq.log
except-interface=eth0
cache-size=10000
ptr-record=1.1.0.10.in-addr.arpa,USG3P
all-servers
cname=unifi.localdomain,unifi
resolv-file=/etc/resolv.conf.dhclient-new-eth0
server=1.1.1.1
host-record=unifi,10.0.1.2
```
With DNS server set to `127.0.0.1`
```
@USG3P:~$ cat /etc/dnsmasq.conf
#
# autogenerated by vyatta-dns-forwarding.pl on Sat May 30 14:24:57 PDT 2020
#
log-facility=/var/log/dnsmasq.log
except-interface=eth0
cache-size=10000
ptr-record=1.1.0.10.in-addr.arpa,USG3P
all-servers
cname=unifi.localdomain,unifi
server=127.0.0.1
host-record=unifi,10.0.1.2
```

**Comment by zalberico** [comment]
After working for a couple days it broke again this morning (with no changes from me, the 127.0.0.1 setting was still in place).

https://test.nextdns.io/ fails to load (blank page) on devices that don't have the app. All other website fail to resolve.

I'm attaching Firefox network and console output while attempting to load the test page, but it doesn't look helpful.

<img width="1117" alt="network" src="https://user-images.githubusercontent.com/441466/83362726-5d821380-a348-11ea-9fb6-959524126b0b.png">
<img width="1119" alt="console" src="https://user-images.githubusercontent.com/441466/83362729-5fe46d80-a348-11ea-9ad9-bac0a8a5549d.png">

I think something is more broken here than I expected.

**Comment by rs** [comment]
Is the process still running? What do you get for `nextdns status`. What about `nextdns log`.

**Comment by zalberico** [comment]
I think so - before I saw your message I manually wired in to the switch via ethernet so I could change the settings in the USG UI directly.

The USG had a red bar at the top that said it was not connected to the internet, after removing my `127.0.0.1` config it refreshed the bar turned green and it had these in the DNS settings place:

<img width="955" alt="USG_DNS" src="https://user-images.githubusercontent.com/441466/83363028-e732e080-a34a-11ea-97f9-06b0e3cf043e.png">

I wish I had run your nextdns commands prior to removing the `127.0.0.1` setting, but running the status after said running (I'm guessing the log output will be irrelevant now)?

**Comment by rs** [comment]
The log is still relevant.

**Comment by zalberico** [comment]
Is there something in particular you're looking for?

I see a lot of this:
```
Query 192.168.1.10 UDP PTR lb._dns-sd._udp.0.1.168.192.in-addr.arpa. (qry=91/res=0) 1ms : not found
```

If I go back a few days I see this:
```
May 28 16:38:38 MerryMansionGateway nextdns[5423]: Query 192.168.1.150 UDP A www.youtube.com. (qry=66/res=0) 5001ms : doh resolve: context deadline exceeded
```

I don't want to paste all my DNS logs here since that kind of defeats the point of using NextDNS in the first place. Happy to help troubleshoot something specific.

**Comment by rs** [comment]
Filter out query logs. You can send then to team@nextdns.io. No problem if you aren’t confortable with it, it’s just in case something in it could help us understand the issue.

**Comment by zalberico** [comment]
Thanks - I did a `grep -v Query` which should hopefully just remove the query logs and scp'd the file down, I'll send it your way.

**Comment by slln** [comment]
There is something going on with the install script on Edgerouter (VyOS) as not being quite complete.
Most importantly the user still has to manually set NextDNS IPs in the (V)LAN DHCP server(s).
2nd (found on some other blogs/ forums) it helps a lot if in System>System name server, I set 127.0.0.1
3rd (maybe a bit overkill but would be nice to be added in the script questions) I believe NextDNS users prefer high degree of control and visibility on their network, thus I'm forcing all devices (especially IoT) that have hardcoded DNS settings to use NextDNS with a DNAT rule pointing back to the router IP.

**Comment by vijvis** [comment]
Looks to be working fine for me on USG 3P. 

1. I have added NextDNS IPv4 and IPv6 addresses in the controller UI under both WAN (IPv4 only) and LAN (IPv4 and IPv6) DNS Server settings.

2. The above, however, does not send the device name in the NextDNS portal logs / analytics. So I installed the CLI version as specified here straight on the USG - https://github.com/nextdns/nextdns/wiki/EdgeOS

I can now see the device name in the portal logs / analytics. 

This is from my Mac running Big Sur 11.1. It does not have the NextDNS app.

{
	"status": "ok",
	"protocol": "DOH",
	"configuration": "xxxxxxxxx",
	"client": "x.x.x.x",
	"destIP": "207.148.84.39",
	"server": "vultr-syd-1",
	"clientName": "nextdns-cli",
	"deviceName": "Vijays-Mac-mini",
	"deviceID": "3A82O",
	"deviceIP": "x.x.x.x",
	"deviceModel": "mac:60:f8:1d"
}

vijayv@USG3P:~$ cat /etc/dnsmasq.d/nextdns.conf
# Configuration generated by NextDNS
# DNS is handled by NextDNS
port=0
vijayv@USG3P:~$
