### ISSUE TITLE
Supported Docker Images for x86 and arm64

### ISSUE THREAD

**Issue by boostchicken** [nextdns/nextdns#239]
It would be excellent to just have a support docker image.  It would simply installation on many devices.

**Comment by rs** [comment]
Supporting docker while keeping all our features would not be easy at all. Here are a few issues from the top of my head:

* mDNS discovery can’t work from a docker as docker do not let you subscribe to multicast as far as I know
* DHCP lease discovery would not work as it we would not have access to the host filesysem
* /etc/hosts discovery and the use-hosts feature would not work as we would not have access to the host hosts file
* DNS discovery would not work because we could not learn the DNS learned by the host DHCP client
* Auto-activate would not work as we would not have access to the /etc/resolv.conf file
* The install would not work and you would have to deal with launching the docker on startup
* Captive portal detection would not work as we couldn’t detect the DHCP learned DNS

I’m sure I forget a few things. I don’t see what docker brings here as we are providing a single static binary with no dependencies. Docker is great to package complex software with many dependencies that need reproducible environment. In our case, our software adapts to its environment to auto setup itself. Isolating it from this environment will break most advanced features and force you do many things manually.

**Comment by ThePowerOfDreams** [comment]
Containerization is great, but if all you have is a hammer then everything looks like a nail.

**Comment by boostchicken** [comment]
For this discussion, I am going to assume you actually understand how Docker works since you're the Director of Engineering at Netflix.

"We don't plan on supporting Docker officially, it is not on our roadmap, Sorry!".  It's that easy man.

All the effort you put into your overgrown install.sh and platform-specific code baked into your binaries could have just been abstracted away into Docker mounts and a specific compose file for a platform.  In this way, I would have thought it would have been attractive to you.  Also, I am glad I dug into your software.  I have no interest in anything that makes changes to my environment would out at least documenting what it's doing.

There is no need to come up with a fluff response.  Running in Docker is plenty possible, so possible I already got it working, I was just asking for an official, supported service. _Once again, next time just say no._  I have always had a deep respect for the engineers at Netflix and always enjoyed my time talking to and learning from them at various industry events.  It's super disheartening to see their engineering leadership (YOU) straight up posting false, misleading information for the world to consume.

In case you don't know how Docker works and for the benefit of anyone that looks at this in the future and walk away believing mDNS discovery isn't possible in Docker, I have rebutted each of your arguments below.

mDNS discovery can’t work from a docker as docker do not let you subscribe to multicast as far as I know
**Solution**: Docker can do mDNS discovery just fine. You can use the whole host networking stack with the host networking mode.
https://docs.docker.com/network/host/
https://github.com/ianblenke/docker-avahi
https://github.com/flungo-docker/avahi

DHCP lease discovery would not work as it we would not have access to the host filesystem
**Solution**: You absolutely have access to the host filesystem, just mount whatever files you need using volumes. It looks like it's just these.
```	{"/var/run/dhcpd.leases", "isc-dhcpd"},
	{"/var/lib/dhcp/dhcpd.leases", "isc-dhcpd"},
	{"/var/dhcpd/var/db/dhcpd.leases", "isc-dhcpd"},
	{"/var/lib/misc/dnsmasq.leases", "dnsmasq"},
	{"/tmp/dnsmasq.leases", "dnsmasq"},
	{"/tmp/dhcp.leases", "dnsmasq"},
	{"/etc/dhcpd/dhcpd.conf.leases", "dnsmasq"},
	{"/var/run/dnsmasq-dhcp.leases", "dnsmasq"},
```

/etc/hosts discovery and the use-hosts feature would not work as we would not have access to the host hosts file
**Solution**: "By default, a container inherits the DNS settings of the Docker daemon, including the /etc/hosts and /etc/resolv.conf.You can override these settings on a per-container basis."
```
var hostsFiles = []string{
	"/etc/hosts.dnsmasq",
	"/tmp/hosts/dhcp.cfg01411c", // OpenWRT
	`C:\Windows\System32\Drivers\etc\hosts`,
	"/etc/hosts",
}```

Auto-activate would not work as we would not have access to the /etc/resolv.conf file
**Solution**: Mount it into the container and edit it. Yes, you have to use a privileged container, or you could just make a setup one that runs once-off like Bitwarden.  Also, you can still have an install process that runs outside of the docker container.

The install would not work and you would have to deal with launching the docker on startup
**Solution**: Docker containers can and usually do run on startup, it is up to the sysadmin to make sure this happens like starting your process on any other device. As for the installer, I went through the code.  Once again, just mounting files, or making the installer an external binary from the container.

Captive portal detection would not work as we couldn’t detect the DHCP learned DNS
**Solution**: Covered by the above.

**Comment by rs** [comment]
I thought that giving some context about why we are not considering Docker just now would be better than a simple "no". Apparently I was wrong. Note that I find your personal attacks inappropriate and unacceptable.

Regarding your argument about our install.sh that would be a lot simpler if we'd use Docker, it is ignoring that our main target is routers, that mostly run on non-x86 architectures with busybox based distributions and very limited memory and storage as well as non Linux installs like FreeBSD/pfSense etc. Requiring Docker installation would not make sense and would certainly not make things simpler.

Finally, running Docker in host network mode and mounting half your filesystem into it does not make much sense. All the solutions you listed would work, I never said it was impossible. All I'm saying is that it is adding complexity for unclear benefits.

Peace.

**Comment by boostchicken** [comment]
"It is ignoring that our main target is routers ....."

Is it _ignoring_, or just **not knowing** that? I guess as a new member of your community I should know everything about your business plan. 

I appreciate the context.  However, the context isn't it's too difficult or not possible.  The context is "Our main target is routers, since most routers do not use Docker, we do not have plans to support it at this time".  

Why didn't you just say that in the first place?  That is a totally valid reason and all the context in the world one would need on this subject.

Go ahead and close the feature request @rs .

**Comment by rs** [comment]
Again, I did not say we won't add support for Docker, so I will keep the issue open. It's just not on the top of the list right now. If Docker becomes a requirement in order to run on UDM, we might prioritize it for instance.

**Comment by boostchicken** [comment]
That is a whole different can of worms and I don't expect Ubiquiti is going to be supporting any install, docker, or otherwise anytime soon.  It's only possible through unsupported hacks.

**Comment by boostchicken** [comment]
@rs 
If you're interested in how it was actually done.  This works on the UDM/UDM Pro with DHCP lease discovery and mDNS.

https://github.com/boostchicken/udm-utilities/tree/master/nextdns

**Comment by rs** [comment]
I'd like to integrate such solution in the install script, and make it diverge as less as possible from a normal installation type. Ideally we would run the cli outside of docker so we don't have to fight the isolation for all features to work and have the `nextdns` command available in the path to control it. We could just use a docker as a helper to launch the service on startup.

I will need a UDM to make that happen, I might buy one soonish.

Also, I'm trying to find a contact a Ubiquiti so we could discuss a less hacky integration solution. If anyone has such contact, please tell me.

**Comment by boostchicken** [comment]
@rs hope you get there.  The main problem is the lack of support for running commands after a boot.  The main filesystem is squashfs. They use a ramfs overlay to allow changes that obviously only last for one boot.  This is pretty standard practice for embedded linux.

So unless they integrate your binary and service into their firmware you cannot modify the init process or install your binary. Also, they are making their own dnsfilter product. I doubt they are going to throw those plans away and include yours, but please prove me wrong :)

The dnsmasq conf files are regenerated often.  The one you would need to modify and monitor are
/etc/resolv.dnsmasq
/config/dnsmasq.lease -- You already added this one for the next release.
/run/dnsmasq.conf.d/dns.conf
```
# Generated automatically by ubios-udapi-server
#

# Configuration of DNS Forwarder
# Never forward plain names (without a dot or domain part)
domain-needed
# Never forward addresses in the non-routed address spaces.
bogus-priv
resolv-file=/etc/resolv.dnsmasq
all-servers
interface=br0
# Add resolution support to dnsfilter.
interface=dnsfilter
host-record=unifi,10.0.0.1
host-record=setup.ui.com,10.0.0.1
host-record=UDMP.domain,UDMP,10.0.0.1
```
These will be overwritten by the controller every time the device is provisioned

To recap, in order to run on the UDM/UDMP

1. Ubi supplies a post init method where you can start your binary
2. Your installer will be of little use here.  You just need to get a binary that monitors and modifies these files in real-time.  This means that there will be periods where NextDNS is not in use.
3. If they change anything you will have to adjust all of this.

So because of the above reasons, I don't think running on the main OS is a viable strategy here.  That is why I took the defensive approach using Docker and MacVLan. The advantages of having your own networking space, and their inability to interfere with the setup makes a lot of sense.  If that external device is a Pi, Docker container, whatever, doesn't really matter. Just install it somewhere and point your DHCP at it and write some IPTables rules.

**Comment by rs** [comment]
The install script would automate all the installation of nextdns, even if it is based on Docker. This install script is here to hide the complexity of each platform.

As I'm reading https://github.com/boostchicken/udm-utilities/tree/master/on-boot-script, there is something I'm not sure to understand. It seems to say that what you put in /etc/init.d/udm.sh or /etc/systemd will be persisted and ran on boot, does it mean /etc/ is writable and persisted across boot? If yes, what prevents me from putting a binary there directly?

**Comment by boostchicken** [comment]
@rs it is not.  Look closely.  It's running that command in a Docker container that is always started on the UDM.  They run their controller in Docker.  What that does is install a systemd service in the docker container that runs on boot.  That service ssh's back to the UDM and executes a shell script in /mnt/data that is persisted through reboots.

You cant persist anything that isn't in /mnt/data or /mnt/persistent.


So if you wanted to do a binary install on the UDM you would have to do the same on_boot hack I do unless they add real hooks into the init process.  Also, the controller re-writes resolv, host, and dnsmasq confs regularly.  So you can't just run a script once and change those.

For your edification here are all the mounts running on the UDM.  Obviously the podman stuff is specific to my box, but you get the picture.  It is a standard ramfs pivot_root overlay setup.

```
/dev/sda3 on /overlay/root_ro type squashfs (ro,relatime)
devtmpfs on /dev type devtmpfs (rw,relatime,size=1990208k,nr_inodes=497552,mode=755)
proc on /proc type proc (rw,relatime)
tmpfs on /overlay/rw type tmpfs (rw,relatime)
ram-overlay on / type overlay (rw,relatime,lowerdir=/,upperdir=/overlay/rw/upper,workdir=/overlay/rw/work)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=666)
tmpfs on /dev/shm type tmpfs (rw,relatime,mode=777)
tmpfs on /tmp type tmpfs (rw,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
none on /sys/fs/pstore type pstore (rw,relatime)
nodev on /sys/kernel/debug type debugfs (rw,relatime)
/dev/sda6 on /mnt/data type ext4 (rw,noatime,errors=panic,data=ordered)
/dev/sda4 on /mnt/persistent type ext4 (rw,noatime,errors=panic,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
/dev/sda6 on /mnt/data/podman/storage/overlay type ext4 (rw,noatime,errors=panic,data=ordered)
shm on /mnt/data/podman/storage/overlay-containers/cf2ddb9165d29b97a79fb73f923907e7085a17a5a83a4cac0556f04cd6a8e5a3/userdata/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=64000k)
overlay on /mnt/data/podman/storage/overlay/a5c52f84be4036781524342d46abd8c2b016fbf217fa98f5ceec3611876efabc/merged type overlay (rw,nodev,relatime,lowerdir=/var/lib/containers/storage/overlay/l/VYZRV3JW5E5PFATFDWYUGTKWHK,upperdir=/mnt/data/podman/storage/overlay/a5c52f84be4036781524342d46abd8c2b016fbf217fa98f5ceec3611876efabc/diff,workdir=/mnt/data/podman/storage/overlay/a5c52f84be4036781524342d46abd8c2b016fbf217fa98f5ceec3611876efabc/work)
shm on /mnt/data/podman/storage/overlay-containers/ea0bc4236c4d79fa2035568007ccc408f7b6be2983ac00e8b55332c24fc7a7df/userdata/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=64000k)
overlay on /mnt/data/podman/storage/overlay/eb1dfad3d39bf8e0cdca3fb241e87e9ebd4af52cbed420102eae1bae5dc8a529/merged type overlay (rw,nodev,relatime,lowerdir=/mnt/data/podman/storage/overlay/l/WIIZNKSC43KCX5FDLHWQZ4K26N:/mnt/data/podman/storage/overlay/l/AZNNJOBFOMMX5XK6ZAAHQOVDDE,upperdir=/mnt/data/podman/storage/overlay/eb1dfad3d39bf8e0cdca3fb241e87e9ebd4af52cbed420102eae1bae5dc8a529/diff,workdir=/mnt/data/podman/storage/overlay/eb1dfad3d39bf8e0cdca3fb241e87e9ebd4af52cbed420102eae1bae5dc8a529/work)
tmpfs on /run/netns type tmpfs (rw,nosuid,nodev,relatime,mode=755)
shm on /mnt/data/podman/storage/overlay-containers/f415a328304c7a1fe2f3a501a6a1bd4fccfe8f6865994202e34da997077e9daa/userdata/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=64000k)
nsfs on /run/netns/cni-d7657240-f861-795a-c02b-96340ab31090 type nsfs (rw)
overlay on /mnt/data/podman/storage/overlay/3671d03f468cacd2454e013af0920395b1a04dcb086402d988d24f5fc380fc70/merged type overlay (rw,nodev,relatime,lowerdir=/mnt/data/podman/storage/overlay/l/PC2R7VCWHNIKBNTYHYPFNEGFFH:/mnt/data/podman/storage/overlay/l/LZ23UT6UADD6CECZARGYYI7OVS:/mnt/data/podman/storage/overlay/l/ORM23YRG7EFNU2FMBG7GFK24QM,upperdir=/mnt/data/podman/storage/overlay/3671d03f468cacd2454e013af0920395b1a04dcb086402d988d24f5fc380fc70/diff,workdir=/mnt/data/podman/storage/overlay/3671d03f468cacd2454e013af0920395b1a04dcb086402d988d24f5fc380fc70/work)
```

**Comment by theshoehorn** [comment]
Any update on native support for a docker container? I have to have 2 full blown Linux servers running to connect to NextDNS (it's the easiest/lightest DoH client around), would be great to just pop them into my existing docker servers.
