### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by eallion** [nextdns/nextdns#242]
&lt;Describe the bug>

**Context**
 - Version [latest]: 
 - Platform [Openwrt]:

When I install, I got this error:

```
Collected errors:
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/helloworld/Packages.gz, wget returned 8.
```

**Comment by Fail-Safe** [comment]
* Which version of OpenWrt are you running?
* Are you attempting to install via this method? https://github.com/nextdns/nextdns/wiki/OpenWRT
