### ISSUE TITLE
command to remove "conditional config" from config file

### ISSUE THREAD

**Issue by osayb** [nextdns/nextdns#243]
is there note/help specifically stating how to remove conditional config?
I'm looking for ways to remove "00:1c:42:2e:60:4a=67890" line from the config file using Nextdns client.

**Comment by rs** [comment]
We need to add a `config del`, for now you have to edit the file manually.

**Comment by osayb** [comment]
OK, then I'll manually remove it.

**Comment by Lynxshd** [comment]
Sorry to ask a n00b quesiton but. Where is the config file on a pfsense box?

**Comment by PeterDaveHello** [comment]
Looks like the document(wiki) didn't mention the config path, and it can vary based on different environment, on Ubuntu, it's `/etc/nextdns.conf`. @rs is it something that you can mention on the document, or printed from the log? Thanks.

**Comment by rs** [comment]
The default config path is platform specific.

**Comment by PeterDaveHello** [comment]
Then print it somewhere will be really useful 👍

**Comment by rs** [comment]
In some cases it is not a file but the system's configuration API.

**Comment by PeterDaveHello** [comment]
Oh, wow, almost forgot that I saw the case somewhere ... then it's very hard for end-users to know, but need to guess, unless we're familiar with NextDNS cli inside 😅

Maybe just clearly let the user know that the config is stored via system's configuration API, or it's a file somewhere, no matter what?

**Comment by rs** [comment]
Most users don't care where the config is, they would just use the config set/del commands if needed.

**Comment by PeterDaveHello** [comment]
Oh yes, the implementation of del command would give me one less reason to know it!

**Comment by rs** [comment]
you have the `nextdns config edit` for that.

**Comment by PeterDaveHello** [comment]
Just trying to scripting the process, so that I can do the some thing on different places, the edit function will be limited in this case, currently that's what I'm manually do it.

**Comment by rs** [comment]
We could add a list counter-part that would save the config it gets from stdin.

**Comment by shiftoptk** [comment]
Delete command would be fantastic; the config edit command is not functional on my UDMP.

```
# nextdns config edit
Error: vi: exec: "vi": executable file not found in $PATH
Error: non zero exit code: 1: OCI runtime error
```

**Comment by rs** [comment]
Install vi or set your EDITOR env to your editor of choice.
