### ISSUE TITLE
can't connect after installing cli inside glinet

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/nextdns#244]
After the installation I can't connect the devices; it works only if the device is already connected to the / wifi network

**Context**
 - Version [e.g. 1.6.4]: 
 - Platform [openwrt]:

**Comment by Fail-Safe** [comment]
Couple clarifications, please:

* Does “glinet” = “GL.iNet” ?
* Are you saying when the NextDNS client is installed and running, you cannot get DHCP addresses assigned to client machines?
* Or DHCP works, but DNS resolution fails?
* Which OpenWrt version are you running?

It would help if you could post your NextDNS configuration with any sensitive details masked (configuration ID, any local domain names, etc).

**Comment by scafroglia93** [comment]
nextdns it's work but i think the dhcp have some issue

running openwrt 18.x.x inside glinet ar750s
