### ISSUE TITLE
SMTP connections not working

### ISSUE THREAD

**Issue by bhuguenin** [nextdns/nextdns#245]
After upgrading to 1.6.4, SMTP connections to smtp.fastmail.com are very very slow. Issue cleared up after removing CLI client

**Context**
 - Version 1.6.4
 - Platform MacOS 10.15.5

**Comment by scafroglia93** [comment]
have you checked the blocklists ?

**Comment by bhuguenin** [comment]
Nothing is being blocked and also, the computer is still behind a router with NextDNS DNS addresses (both IPv4/6) configured so everything is filtered either way. When the CLI is installed the SMTP connection take an extra 60 minutes while something evenutally times out and then mail is sent. Without the CLI mail is sent immediately via SMTP. This is repeatable. I can send SMTP logs separately if that would help. This started with CLI version 1.6.4

**Comment by SturdyErde** [comment]
Is every connection to that smtp server slow, or just the initial name resolution? Not a fix, but do you have caching enabled?

**Comment by bhuguenin** [comment]
Yes, every connection is slow and caching was enabled. Also, v1.7.0 didn’t fix the issue.

**Comment by bhuguenin** [comment]
Confirmed that this is still an issue in v1.7.1. IMAP connection works fine but SMTP has a 30 second delay and then eventually works but every time there is a delay. Caching is enabled.

**Comment by bhuguenin** [comment]
This is no longer an issue with the Big Sur DNS profile from apple.nextdns.io
