### ISSUE TITLE
Cache on OpenWRT makes nextdns stop resolving after a few hours

### ISSUE THREAD

**Issue by multiformeingegno** [nextdns/nextdns#246]
nextdns version 1.6.4
Router OpenWRT 19.07.3

This is a very weird behaviour that I’ve had on OpenWRT with all versions of nextdns since cache was introduced. I have experienced the same with the latest version 1.6.4.

When I install nextdns with cache option enabled (with the default 10Mb), after a few hours all clients are unable to navigate.
I then remove nextdns, reinstall it again without the cache option and everything works well.

**Comment by mad-it** [comment]
Can you enable `log queries` in your nextdns configuration? You can use `nextdns config set -log-queries=true`. After you enable this, restart nextdns using `nextdns restart`.

Can you post the log you see once everything stops working using `nextdns log` ?

I also had this same issue and in the end it looked like some dns queries were responding with an empty response. I would like to verify if this is also the behavior you are encountering.

**Comment by multiformeingegno** [comment]
@mad-it I had some time today so I tried to re-enable cache on nextDNS 1.7.0. Same behaviour. After approx. 2 hours since enabling caching, almost all the devices on the network could not navigate anymore. I enabled the logs, restarted nextdns and let it run for a bit. Nothing in the logs that suggested empty responses, but I could only see the queries of the few devices that could still navigate. For all the other devices that could not navigate, the logs would not even show the queries.

**Comment by multiformeingegno** [comment]
Also disabling cache from the config and restarting nextdns does not work to restore connectivity. I had to reinstall it

**Comment by nick-rigby** [comment]
@multiformeingegno are you using NextDNS in conjunction with DNSMasq? I've seen an issue that I thought was NextDNS related but ended up being DNSMasq being the culprit.

My current uptime is around 8 Days with no restart of either service.

**Comment by multiformeingegno** [comment]
@nick-rigby I haven’t changed anything from the default OpenWRT config. So it’s using the built in dnsmasq config. The CLI says that enabling cache disables dnsmasq, maybe it fails disabling it on openwrt?

**Comment by gwisl** [comment]
Make sure you have enough resources available for a 10MB cache. If it is a small home router it may be insufficient
