### ISSUE TITLE
Installing through Ansible

### ISSUE THREAD

**Issue by gam-phon** [nextdns/nextdns#247]
Can I automate installing Command-Line Client through Ansible? Can I install it without prompt maybe I can pass all parameters when calling the command so it will be automated and do not need any further actions.

**Comment by rs** [comment]
The installer will mostly only select the right binary to download and ask questions to generate the conf. If you know the architecture and the conf, you can do everything without the installeur. Just download the right binary, put it in the path and execute nextdns install with the right params

**Comment by gam-phon** [comment]
Thank you so much
