### ISSUE TITLE
Defaulting to India for users in Qatar instead of Bahrain/Singapore

### ISSUE THREAD

**Issue by MRizkBV** [nextdns/nextdns#248]
&lt;Describe the bug>

NextDNS TLS (on my GL-iNet Convexa-S via Stubby) defaults to NextDNS servers in India instead of Bahrain or Singapore. 

Ooredoo and Vodafone (the 2 ISPs in Qatar) have bad peering with Indian based hosting providers (with exception to AWS in India). We typically get 5 to 15 ms to Bahrain, and 85 to 120 ms to Singapore. Unfortunately, we get anywhere between 40 ms to 170 ms to India depending on the hosting provider and the route taken. In case of NextDNS, it takes a route to Singapore then goes to India which doubles the distance and more than triples the latency.

In a perfect world we would connect to NextDNS in Bahrain but it seems to be restricted to app use only (which is unfortunate).

**Context**
 - Version [e.g. 1.5.2]: NextDNS TLS via Stubby 
 - Platform [e.g. macOS, ASUS-Merlin]: GL-iNet Convexa-S running v3.104

**Comment by rs** [comment]
We will add more PoP in the area soon. Closing as this is not related to CLI.
