### ISSUE TITLE
Merge identical devices

### ISSUE THREAD

**Issue by pro-sumer** [nextdns/nextdns#252]
I use my iPhone X both at home via WiFi and on the road via cellular. NextDNS handles that phone as two different devices in logging/analytics (similar for my iPad):

* on WiFi (ASUS router running NextDNS CLI client): "iPhone X", "Apple, Inc"
* on cellular (NextDNS mobile iOS App): "iPhone X", "iPhone X"

Please make it possible to merge (identical) devices (based on MAC address, name, ...).

**Comment by maghuro** [comment]
+1
Plus, on mobile apps, autodisable it when it detects a particular wifi (home wifi), and enable it automatically when exiting defined wifi network :)

**Comment by pro-sumer** [comment]
@maghuro The iOS App can already exclude selected Wi-Fi networks ("_NextDNS will be automatically turned off when connected to those networks_")

**Comment by rs** [comment]
Added to our TODO.
Closing as it's not a cli specific feature.
