### ISSUE TITLE
can't install cli inside glinet b1300

### ISSUE THREAD

**Issue by difontane** [nextdns/nextdns#255]
Can't install Next DNS via script on my router
`root@GL-B1300:~# DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"
sh: .: line 948: can't open '/etc/os-release'
ERROR: Unsupported OS: Linux
ERROR: Unknown bin location for 
INFO: OS: 
INFO: GOARCH: armv7
INFO: GOOS: linux
INFO: NEXTDNS_BIN: 
INFO: LATEST_RELEASE: 1.6.4
ERROR: Cannot detect running environment.`

Installed Firmware 3.104/ OpenWrt Chaos Calmer 15.05.1 r48067

**Comment by Fail-Safe** [comment]
Can you confirm if /etc/os-release exists in your OS? Also, do you have the option to upgrade to a more recent OpenWrt release?

**Comment by difontane** [comment]
It's last firmware version and /etc/os-release not exists. It's firmware bug. Sorry )
