### ISSUE TITLE
Client fails to start on Windows (getTuntapComponentId)

### ISSUE THREAD

**Issue by AdamVig** [nextdns/nextdns#256]
When I start my computer, the Next DNS client automatically starts and shows this error dialog:
![image](https://user-images.githubusercontent.com/5354752/84540927-00794c80-acbc-11ea-98f0-7d93ecb3e235.png)

The text of the error is:
```
getTuntapComponentId: not found component id
```

When I click "OK", the window appears a second time. When I click "OK" on the second window, it goes away properly.

If I close the client and reopen it manually, then right click on the status bar icon and click "Enable", the same error dialog appears three times in a row.

The client seems to get stuck in the "Connecting..." status. The NextDNS dashboard shows that my computer is not using NextDNS.

**Context**
 - Version: 1.0.12
 - Platform: Windows 10 Pro Insiders build 19640.1

**Comment by rs** [comment]
We are aware. Next revision of the windows app will remove dependency on TAP driver. In the meantime, you can try to YugoDNS client, it's pretty good.

**Comment by candiesdoodle** [comment]
Hello, any ETA on this? Windows app is really broken at the moment because of the above error. Or any work arounds to use the app specifically

**Comment by Naxterra** [comment]
It is still happening on 2.0.3. At first install it gives the error, on second install it installs the app but then it floods event logs every five seconds with below message.
restart err: getTuntapComponentId: not found component id
