### ISSUE TITLE
Add support for runit init system

### ISSUE THREAD

**Issue by distefam** [nextdns/nextdns#258]
The Linux installers (at least the Arch one) requires a systemd service to work. For those of us who use Void, Artix, etc. please add support for other init systems like Runit.

**Comment by rs** [comment]
We support all this init systems: https://github.com/nextdns/nextdns/tree/master/host/service

Runit is not supported yet. Doesn’t Void support sysV type init?

**Comment by distefam** [comment]
I don't believe Void supports anything other than Runit as it was developed as a distro _around_ Runit. That said, I'm actually using Artix linux with Runit as an init system. For the time being, I ended up using DNSCrypt, which seems to get me most (if not all?) of the features that the NextDNS client offers.

**Comment by rs** [comment]
You miss most of the features of cli (device identification, cache auto flushing, dynamic configurations, geo steering, multi path fallback, etc.).

We will add runit support eventually. In the meantime, you can create an init script manually or help us add the feature if you can.

**Comment by distefam** [comment]
Thank you for the quick reply. I’ll see what I can do this coming week if I can find some time to write an Init script.

**Comment by Voltairine-de-Cleyre** [comment]
SysV support functions wonderfully. Runit would be great as antiX has a runit release in addition toa SysV release.

**Comment by quantizzed** [comment]
Hello,
another Void Linux user here, just wanted to confirm that `runit` support is much needed :pray:

**Comment by itsanubhavkini** [comment]
[This](https://github.com/itsanubhavkini/nextdns-voidlinux) works for me on voidlinux.
