### ISSUE TITLE
Merlin Asus - hangs on activating

### ISSUE THREAD

**Issue by maghuro** [nextdns/nextdns#259]
&lt;Describe the bug>

**Context**
 - Version [e.g. 1.5.2]: latest release
 - Platform [e.g. macOS, ASUS-Merlin]: Asus Merlin

On Asus Merlin, when booting the router, nextdns stucks in "Activating..." and it doesn't activate. However, when on ssh "nextdns status" says "running", but it isn't.

Logs:

```
May  5 06:05:24 nextdns[1623]: Starting NextDNS 1.6.4/linux on 127.0.0.1:5342
May  5 06:05:24 nextdns[1623]: Starting mDNS discovery
May  5 06:05:24 nextdns[1623]: Listening on TCP/127.0.0.1:5342
May  5 06:05:24 nextdns[1623]: Listening on UDP/127.0.0.1:5342
Jun 14 19:06:08 nextdns[1623]: Setting up router
Jun 14 19:06:24 nextdns[1623]: Activating
adminRT-AC86U/tmp/home/root
```

When doing "nextdns restart":

```
May  5 06:05:24 nextdns[1623]: Starting NextDNS 1.6.4/linux on 127.0.0.1:5342
May  5 06:05:24 nextdns[1623]: Starting mDNS discovery
May  5 06:05:24 nextdns[1623]: Listening on TCP/127.0.0.1:5342
May  5 06:05:24 nextdns[1623]: Listening on UDP/127.0.0.1:5342
Jun 14 19:06:08 nextdns[1623]: Setting up router
Jun 14 19:06:24 nextdns[1623]: Activating
Jun 14 19:10:48 nextdns[1623]: Received signal: terminated
Jun 14 19:10:48 nextdns[1623]: Stopping NextDNS 1.6.4/linux
Jun 14 19:10:48 nextdns[1623]: Restore router settings
Jun 14 19:10:48 nextdns[1623]: Deactivating
Jun 14 19:10:48 nextdns[1623]: NextDNS 1.6.4/linux stopped
Jun 14 19:10:49 nextdns[15057]: Starting NextDNS 1.6.4/linux on 127.0.0.1:5342
Jun 14 19:10:49 nextdns[15057]: Listening on TCP/127.0.0.1:5342
Jun 14 19:10:49 nextdns[15057]: Starting mDNS discovery
Jun 14 19:10:49 nextdns[15057]: Listening on UDP/127.0.0.1:5342
Jun 14 19:10:54 nextdns[15057]: Setting up router
Jun 14 19:10:54 nextdns[15057]: Activating
Jun 14 19:11:00 nextdns[15057]: Connected 45.90.28.0:443 (con=75ms tls=259ms, TLS13)
Jun 14 19:11:01 nextdns[15057]: Connected 188.208.143.11:443 (con=32ms tls=57ms, TLS13)
Jun 14 19:11:01 nextdns[15057]: Switching endpoint: https://ls-lis-1.edge.nextdns.io#188.208.143.11
```

**Comment by rs** [comment]
Before restart, what is the content of the /etc/resolv.conf file?

**Comment by maghuro** [comment]
> Before restart, what is the content of the /etc/resolv.conf file?

# This file is managed by nextdns.                                     
 2 #                                                                      
 3 # Run "nextdns deactivate" to restore previous configuration.          
 4                                                                        
 5 nameserver 127.0.0.1                                                   
 6

**Comment by maghuro** [comment]
However, I think the problem is related to /jffs/services-start

I think nextdns must be on the first line (after shebang) on this file, to be called before everything else.
However, it is placed in the first available line, so the other scripts are being called before, making it failing start because some other scripts have problems.

**Comment by rs** [comment]
Can you please try moving it to validate this assumption?

**Comment by maghuro** [comment]
> Can you please try moving it to validate this assumption?

I did it earlier, put it in the first place.
It worked and I rebooted a couple of times, and it worked.

But it's not a very scientific testing and conclusions 😊

**Comment by rs** [comment]
Reopened #116. I will close this one as it's dup.
