### ISSUE TITLE
Android - Split Horizon?

### ISSUE THREAD

**Issue by modularTaco** [nextdns/nextdns#260]
I'm using NextDNS client on my laptop (Fedora) and on my phone (Android).
In my home network there are running some services like NAS or home automation.
All of these services are reachable via their hostname and the domain "fritz.box" (as I use a Fritzbox as router), when resolved via the router.
On my laptop I was able to configure a split horizon to forward any dns query to nextdns, except the ones with the domain "fritz.box". After that, all of my local services were working fine.
But however I am not able to find a documentation on how to do the same on my android phone.
Is there any possibility to configure split horizon in NextDNS on Android? Or something similar to forward not all DNS queries to NextDNS, resolve some domains locally?
Otherwise I cannot use NextDNS on my mobile as I need to connect to my NAS from my mobile from time to time and do not want to stop and start the NextDNS VPN everytime.

**Comment by rs** [comment]
It's a planned feature on android. I'm closing this issue as this repository is for the cli client.
