### ISSUE TITLE
Zoom client and Block page certificate do not like each other

### ISSUE THREAD

**Issue by kurktchiev** [nextdns/nextdns#261]
With NextDNS installed, started and activated the Zoom client keeps throwing 
![image](https://user-images.githubusercontent.com/5804477/84761857-57d43100-afca-11ea-901d-db57b86b2ce9.png) it is impossible to tell Zoom to trust the cert and the popup comes on every so often (about 30secs to a min between popups)

**Context**
 - Version [e.g. 1.5.2]: 1.6.4
 - Platform [e.g. macOS, ASUS-Merlin]: OSX Catalina latest
 - Zoom: 5.1.0

**Comment by kurktchiev** [comment]
To followup, i have followed the instructions here https://help.nextdns.io/en/articles/4162250-how-to-install-and-trust-nextdns-root-ca and do have the root CA approved in the keychain. Either Zoom is doing something whacky and not using the chain or the way NextDNS is inserting itself is not playing nice with Zoom.

**Comment by rs** [comment]
Did you block zoom?

They might be pinning their cert.

**Comment by kurktchiev** [comment]
I am not directly blocking zoom unless one of the trackers picked up some new domain I guess that’s causing zoom issues


-B

**Comment by rs** [comment]
Can you please check in the logs, otherwise I don't see why zoom would complain.

**Comment by kurktchiev** [comment]
Ah... it does indeed seem that one of the lists added block for logfiles.zoom.us and I think thats tripping it up

**Comment by kurktchiev** [comment]
probably should close this as "user error" than a bug :)
