### ISSUE TITLE
install failed on manjaro kde

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/nextdns#262]
Cannot write config: open /etc/nextdns.conf: permission denied

**Context**
 - Version [e.g. 1.5.2]:  nextdns version 1.6.4
 - Platform [e.g. macOS, ASUS-Merlin]: manjaro KDE

**Comment by rs** [comment]
Did you get this error during install? If yes, can you please run the installer again with `DEBUG=1` at the beginning of the line and copy past the transcript?

**Comment by 3xploiton3** [comment]
problem solved

i try reinstall with script,
