### ISSUE TITLE
NextDNS for Mikrotik Routers

### ISSUE THREAD

**Issue by Xtreme512** [nextdns/nextdns#263]
We got DoH client for RouterOS finally and just asking if its possible for NextDNS engineers to create a package for Mikrotik in future?

**Comment by rs** [comment]
I don't believe Mikrotik let you create packages for their platform. Did I miss something?

**Comment by ipleten** [comment]
Would be cool to have that.

**Comment by rs** [comment]
Mikrotik has third party package support now? Any pointer?

**Comment by ipleten** [comment]
Yeah I googled a bit, and seems custom package development is impossible.

**Comment by rs** [comment]
Let's close this then
