### ISSUE TITLE
CLI does not broadcast itself as DNS server when ipv6 is disabled

### ISSUE THREAD

**Issue by mad-it** [nextdns/nextdns#264]
When IPv6 is disabled, dns resolution stop working on any client connected to the router. It seems that DHCP server is not broadcasting the IPv4 as a dns server.

**Context**
 - Version [e.g. 1.5.2]: latest
 - Platform [e.g. macOS, ASUS-Merlin]: OpenWRT

Reproduction:
1. Run nextdns CLI on an OpenWRT router with dnsmasq disabled for dns resolution(cache enabled does this automatically for you)
2. Disable IPv6 on a machine connected to the network
Linux:
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
```
3. Restart the network on the machine connected to the network
Linux:
```
systemctl restart network-manager.service
```

After network spins up you will notice that there is not DNS configured.

**Comment by anesiem** [comment]
I have it working with ipv6 disabled .. I don't think this is a bug.

**Comment by mad-it** [comment]
Might have been something in my local configuration. I will close this issue for now.
