### ISSUE TITLE
Not caching any records 1.7.0

### ISSUE THREAD

**Issue by adaptive** [nextdns/nextdns#267]
Queries your servers on every request, for test purposes the two requests are 10 seconds apart. I was expecting the first request around 16-22ms and the second returning from nextdns CLI cache at 0-1ms.

Cache Boost is on.

<img width="442" alt="Screen Shot 2020-06-25 at 4 23 26 PM" src="https://user-images.githubusercontent.com/17833/85749040-69bb7f80-b700-11ea-989f-2d1014a80cf8.png">

```
; <<>> DiG 9.10.6 <<>> a nextdns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11740
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;nextdns.com.			IN	A

;; ANSWER SECTION:
nextdns.com.		74654	IN	A	159.8.210.35

;; Query time: 22 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jun 25 16:18:56 WEST 2020
;; MSG SIZE  rcvd: 56


; <<>> DiG 9.10.6 <<>> a nextdns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33228
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;nextdns.com.			IN	A

;; ANSWER SECTION:
nextdns.com.		74497	IN	A	159.8.210.35

;; Query time: 15 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jun 25 16:21:33 WEST 2020
;; MSG SIZE  rcvd: 56
```

**Context**
 - Version 1.7.0
 - Platform macOS

**Comment by rs** [comment]
What is the output of `nextdns config`.

**Comment by adaptive** [comment]
`detect-captive-portals false
config c3e235
cache-size 0
max-ttl 0s
use-hosts true
timeout 5s
auto-activate true
control /var/run/nextdns.sock
log-queries false
report-client-info true
discovery-dns
listen localhost:53
cache-max-age 0s
bogus-priv true
hardened-privacy false
setup-router false`

**Comment by rs** [comment]
Please follow the following instructions to enable caching: https://github.com/nextdns/nextdns/wiki/Cache-Configuration

**Comment by adaptive** [comment]
@rs thanks
