### ISSUE TITLE
openwrt documentation

### ISSUE THREAD

**Issue by icf20** [nextdns/nextdns#268]
in the wiki the documentation assumes LUCI installed, is that a requirement? because the packages are separated nextdns vs luci-app-nextdns can be used on CLI mode ? or it needs LUCI

**Comment by rs** [comment]
The LUCI app is only needed if you want a configuration page in the UI, it is absolutely not required.

**Comment by rs** [comment]
The wiki goes for the simplest instruction. By installing the LUCI app, you get the cli as dep and you can finalize the installation from the UI.
