### ISSUE TITLE
flag/file.go: see module flagx/flagfile

### ISSUE THREAD

**Issue by dolmen** [nextdns/nextdns#27]
@rs I have seen file [flag/file.go](https://github.com/nextdns/nextdns/blob/master/flag/file.go) in this project and just wanted to advertise my own [`flagfile` module](https://pkg.go.dev/github.com/dolmen-go/flagx/flagfile/?tab=doc). It provides a [`File`](https://pkg.go.dev/github.com/dolmen-go/flagx/flagfile/?tab=doc#File) that uses a flexible interface [`Loader`](https://pkg.go.dev/github.com/dolmen-go/flagx/flagfile/?tab=doc#Loader) which you could use to implement your own file format on top of `File`.

**Comment by rs** [comment]
Thanks for the heads up. I want one to one parity with the arguments version. This mimics how dnsmasq config works by basically just treating each line as one argument with a value.
