### ISSUE TITLE
can you show me how to import certificates nextdns to mikrotik

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/nextdns#270]
i could not find in here

https://help.nextdns.io/en/articles/4162250-how-to-install-and-trust-nextdns-root-ca

**Comment by theovds** [comment]
Here is what I did:

- Use a Chromium based browser and browse to https://dns.nextdns.io/
- Open the certificate, and click on 'copy to file'
- Save as .p7b
- Copy file to Mikrotik
- On Mikrotik go to System > Certificates and select the p7b file

**Comment by rs** [comment]
Use curl CA bundle: https://curl.haxx.se/ca/cacert.pem

**Comment by 3xploiton3** [comment]
> Use curl CA bundle: https://curl.haxx.se/ca/cacert.pem

how import to mikrotik?

can u show me tutorial 1 by 1

**Comment by rs** [comment]
```
./tool fetch url=https://curl.haxx.se/ca/cacert.pem
./certificate import file-name=cacert.pem passphrase=""
```

**Comment by 3xploiton3** [comment]
> ```
> ./tool fetch url=https://curl.haxx.se/ca/cacert.pem
> ./certificate import file-name=cacert.pem passphrase=""
> ```

![image](https://user-images.githubusercontent.com/19517680/147356244-1d1e27f7-02f9-4c19-b6c8-1994e68467d1.png)
