### ISSUE TITLE
OpenWRT Package Upgrade 1.7.0 overwrites configuration back to default

### ISSUE THREAD

**Issue by nick-rigby** [nextdns/nextdns#271]
OpenWRT Package Upgrade 1.7.0 overwrites configuration back to default thus creating dns routing issues. Restored config from back-up with a "nextdns restart" resolves.

**Context**
 - Version [e.g. 1.5.2]: 1.7.0
 - Platform [e.g. macOS, ASUS-Merlin]: OpenWrt 19.07.3 r11063-85e04e9f46

**Comment by multiformeingegno** [comment]
Can confirm this happened to me as well upgrading from 1.6.4

**Comment by nick-rigby** [comment]
Just uprade to 1.8.1 and the issue is still present.
