### ISSUE TITLE
Comments on config file

### ISSUE THREAD

**Issue by maghuro** [nextdns/nextdns#273]
Please add the possibility to add coments on confi file.
I have so many conditional configs, and I'd love to add a comment in front of each one for organization purposes.

Even if I had comments now, they are stripped off.

**Comment by somedevreally** [comment]
its not perfect, but works
add #comment without space.
```
config 00:00:00:00:00:00=abcde#comment1
config 00:00:00:00:00:00=abcde#comment2
config 00:00:00:00:00:00=abcde#comment3
```
