### ISSUE TITLE
Enable DNS Rebinding Protection cannot install app from playstore

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/nextdns#274]
&lt;Describe the bug>

Enable DNS Rebinding Protection
cannot install application from playstore

**Context**
 - Version [e.g. 1.5.2]:  1.7
 - Platform [e.g. macOS, ASUS-Merlin]: Manjaro KDE

**Comment by goodness-from-me** [comment]
Check your logs - probably there is some Google domain banned.
If I am not mistaken, `android.clients.google.com`.

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/86614171-cc542b80-bfdc-11ea-8dd6-bb7da04f55dd.png)

**Comment by rs** [comment]
Issue not related to cli, closing.
