### ISSUE TITLE
Denylist doesn't work

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/nextdns#275]
**Context**
 - Version 1.0.12
 - Platform Windows 10 LTSC

![image](https://user-images.githubusercontent.com/19517680/86121538-5a717300-bb00-11ea-8bbc-f787a6281d66.png)

![image](https://user-images.githubusercontent.com/19517680/86121553-61988100-bb00-11ea-96f2-7643773e836e.png)

Denylist doesn't work

i still able to access 
internetdownloadmanager.com

**Comment by M0UL** [comment]
works fine for me.
i only have internetdownloadmanager.com added to the denylist

**Comment by goodness-from-me** [comment]
You probably have more than 1 DNS server set up.
Check it with [dnsleaktest.com](https://dnsleaktest.com) - it should show only dns servers by nextdns.

**Comment by Thuijoss** [comment]
Check that you aren't using navigation help in your browser settings. Most often, Chrome will additionally query the DNS server (8.8.8.8) in case of an error.

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/86615309-7c766400-bfde-11ea-928f-b888f1b042c7.png)
![image](https://user-images.githubusercontent.com/19517680/86615325-826c4500-bfde-11ea-8577-830f11913913.png)

now its worked,
or maybe i should restart PC for update NextDNS  ?

**Comment by rs** [comment]
Please do not open issues in this repository for issues not related with the cli client.

**Comment by 3xploiton3** [comment]
> Please do not open issues in this repository for issues not related with the cli client.

consider change title to 'nextdns-cli' or similar like that,
