### ISSUE TITLE
unbound on pfsense with nextdns cli

### ISSUE THREAD

**Issue by Hr46ph** [nextdns/nextdns#278]
I am running pfsense with dhcp and dns (unbound), clients register in dns. I'm running several vlans and setup firewall rules to specifically block/allow traffic. I have my own domain and use internal.mydomain.org for local clients.

Current unbound setup is straightforward and the nextdns setup is copy/pasted into the custom config to forward non-local queries to nextdns.

The issue is that nextdns logging shows only my public ip and no other clients. I'd like to change that to get full logging of clients and domains.

I tried setting up the nextdns cli but im confused how to configure this properly. I went over all the documentation and tried different things but I can't get it to work properly.

Obviously first issue is a port conflict so I reconfigured unbound to listen only on localhost 5353 and configured nextdns to listen on *:53 and forward my internal.mydomain.org to 127.0.0.1:5353.

Public queries work and clients show up in the logging, except the forwarder doesn't seem to work and I cant resolve local client hostnames.

```
max-ttl 0s
report-client-info true
cache-max-age 0s
detect-captive-portals false
hardened-privacy false
timeout 5s
listen *:53
config 12345
discovery-dns
use-hosts true
setup-router true
control /var/run/nextdns.sock
cache-size 0
bogus-priv true
auto-activate false
forwarder internal.mydomain.org.=127.0.0.1:5353
log-queries true
```
I tried different things:
change the listen to a LAN IP address
Change the forwarder (without ending dot)
tried *.internal.mydomain.org

I'm at a loss. Any ideas how to get this working properly?

Thanks.

**Comment by rs** [comment]
Try setting bogus-priv to false.

**Comment by Hr46ph** [comment]
Thanks, but not yet unfortunately. Long post but I want to be detailed. Something weird going on here.

When I run unbound on 53, everything works fine. Local domain queries are resolved for all clients and host overrides from unbound resolve fine. Queries not for the internal domain are sent to nextdns.io and end up in the logs.

I change unbound to listen on localhost 5353, I comment out the custom config (see first post) and enable nextdns on 127.0.0.1:53 and verify with netstat -an that things listen on the correct ports (** PS: nextdns seems to ignore 127.0.0.1 and uses *:53 instead**). I use it with the following config:
```
config 123abc
cache-size 0
bogus-priv false
setup-router true
auto-activate false
listen 127.0.0.1:53
timeout 5s
report-client-info true
log-queries false
cache-max-age 0s
max-ttl 0s
use-hosts true
control /var/run/nextdns.sock
detect-captive-portals false
hardened-privacy false
discovery-dns
forwarder internal.mydomain.org=127.0.0.1:5353
```
From a client in 192.168.1.0/24:
```
user123@ncc-1701-lnx ~ $ ping pfsense.internal.mydomain.org
ping: pfsense.internal.mydomain.org: Name or service not known

user123@ncc-1701-lnx ~ $ cat /etc/resolv.conf
# Generated by NetworkManager
search internal.mydomain.org
nameserver 192.168.1.1

user123@ncc-1701-lnx ~ $ nslookup
> server
Default server: 192.168.1.1
Address: 192.168.1.1#53                                <------------ nextdns
> pfsense.internal.mydomain.org
Server:         192.168.1.1
Address:        192.168.1.1#53

** server can't find pfsense.internal.mydomain.org: NXDOMAIN
 
user123@ncc-1701-lnx ~ $ dig pfsense.internal.mydomain.org
; <<>> DiG 9.11.20-RedHat-9.11.20-1.fc31 <<>> pfsense.internal.mydomain.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 29635
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pfsense.internal.mydomain.org. IN A

;; ANSWER SECTION:
pfsense.internal.mydomain.org. 0 IN A      10.1.1.1

;; Query time: 4 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)                 <------------ nextdns
;; WHEN: zo jul 12 10:27:57 CEST 2020
;; MSG SIZE  rcvd: 102

user123@ncc-1701-lnx ~ $
```
From pfsense console I can use ping all hosts, and nslookup or dig on localhost port 53 and 5353 and everything seems to work fine. nameserver 127.0.0.1 is in /etc/resolv.conf.

So, from a client, ping doesn't resolve, nslookup doesn't resolve, dig comes back with positive ansers. This is from multiple clients (windows and linux), one on wifi (192.168.1.0/24) and another wired (10.1.1.0/24). I've added temporary access rules on pfsense to allow any <-> any for any source, any dest, any proto and all ports on all networks.

So yeah, I'm kinda lost here. Any ideas?
Thanks!

**Comment by rs** [comment]
Two things:
* listen is ignored when setup-router is true
* dig shows the response is MXDOMAIN but with a valid answer, that’s a bug we need to understand, probably a cli bug.

**Comment by Hr46ph** [comment]
Is there anything I can do to help trace it?

**Comment by Hr46ph** [comment]
I backed up pfsense, factory defaults, with just basic lan/wan setup and allow all on lan. Setup dns resolver on 5353 localhost and nextdns as above but I get the same results so I think its reproducable. I just wanted to make sure its not something in my pfsense setup (which is quite complex) but it seems its not.

**Comment by rs** [comment]
The NXDOMAIN issue is fixed in master. It will be part of the next rev.
