### ISSUE TITLE
Functionality When Using Another DoH Provider

### ISSUE THREAD

**Issue by gaia** [nextdns/nextdns#280]
When using another DoH provider,

are blocklists active?
do queries count towards the free allowance?
which features are unavailable, obviously besides `hardened-privacy`?

**Comment by rs** [comment]
You mean using our client to connect to another provider? You will get none of our service features and obviously it will cost you nothing.

**Comment by Blason** [comment]
> You mean using our client to connect to another provider? You will get none of our service features and obviously it will cost you nothing.

Is that possible to use other DOH provider using nextdns client? I didnt see that option.

**Comment by rs** [comment]
Use the forwarder option with no domain, just DoH URL.

**Comment by Blason** [comment]
hmmm ok
