### ISSUE TITLE
config ID in settings menu can have hard to indentify or notice spaces

### ISSUE THREAD

**Issue by quarrel** [nextdns/nextdns#281]
![Capture](https://user-images.githubusercontent.com/306572/87291293-73d3df80-c542-11ea-8c76-99a24813a194.PNG)

When pasting the configuration ID in to the settings menu, it is easy to paste a following space, which doesn't get stripped. This then uses no configuration (which is shown in the my.nextdns.io dashboard) instead of the configuration that was pasted.

I assume there is no circumstance where this shouldn't be interpreted as the correct config. So just TrimSpace() it?

**Context**
 - Version: 1.0.12
 - Platform: Win10

**Comment by rs** [comment]
It's a known issue, it will be fixed. Closing as this issue is not related to this repository.
