### ISSUE TITLE
It would be good to have an API endpoint to manage

### ISSUE THREAD

**Issue by beastea** [nextdns/nextdns#282]
I have a big enough allowlists and also some overwrites there and I would like to have a chance to mange this in automated way:
- blocklists
- denylists
- allowlists
I wasn't been able to find any way to do that from outside of the web ui, but this would be 100% usefull.
Thanks in advance!

**Comment by rs** [comment]
Please see: https://help.nextdns.io/en/articles/3941197-custom-blocklist-support

**Comment by beastea** [comment]
Hi @rs,
Thank you very much for your response.
This request is actually completely different from what you linked to.
My question is about how I could manage the lists remotely. I do not want to click through the ui interface but would like to reproduce setup in let's say more then one configuration. This is absolutely not about custom blocklists but about automating to manage existing blocklists via api.
I hope I clear this out.

**Comment by rs** [comment]
We might add API support in the future.
