### ISSUE TITLE
DoH server connection error: SSL: handshake failed: unable to get certificate CRL (6) (mikrotik doh)

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/nextdns#283]
always getting error:
`DoH server connection error: SSL: handshake failed: unable to get certificate CRL (6)`

![image](https://user-images.githubusercontent.com/19517680/87398660-65d49c00-c5e0-11ea-9802-85bd042609ab.png)

**Comment by rs** [comment]
This repository is for the cli client, please contact support chat.
