### ISSUE TITLE
The `run` command does not pick up options from NextDNS configuration file

### ISSUE THREAD

**Issue by chazlever** [nextdns/nextdns#284]
The NextDNS CLI does not read options from the config file when started via the `run` command. The `run` command only respects options passed in on the command line. It seems reasonable to expect that the `run` command would pick up options from the configuration file and that those options could be overridden on the command line.

**Context**
 - Version [e.g. 1.5.2]: 1.7.0
 - Platform [e.g. macOS, ASUS-Merlin]: Debian

**Comment by rs** [comment]
You need to pass the path to the configuration file with the `-config` parameter for the `run` command to read it.
