### ISSUE TITLE
List commands and basic help in wiki pages

### ISSUE THREAD

**Issue by SturdyErde** [nextdns/nextdns#286]
The basic command introduction that is shown at the end of installation should be added to the wiki pages. For example, these are shown after installing on a Synology NAS. I looked for a way to add them for a community reference, but the wiki appears to be locked: 

### Managing
Start, stop, or restart the daemon
`nextdns start`
`nextdns stop`
`nextdns restart`

Configure the local host to point to NextDNS or not: 
`nextdns activate`
`nextdns deactivate`

Explore daemon logs:
`nextdns log`

For more commands, use:
`nextdns help`

Alertnatively:
### Full command list
install ...
uninstall ...
start ...
stop ...
restart ...
status ...
log ...
run ...
config ...
activate ...
deactivate ...
discovered ...
cache-stats ...
cache-keys ...
trace ...
version ...

**Comment by rs** [comment]
Done

**Comment by SturdyErde** [comment]
Thanks. Any way we can contribute to wikis?

**Comment by rs** [comment]
GH does not make this easy, it's either all open with no validation or all closed.
