### ISSUE TITLE
Current Version On EdgeOS sets DNS to localhost:53

### ISSUE THREAD

**Issue by gaia** [nextdns/nextdns#288]
installed current nextdns on current edgeOS (2.0.8), but it sets the listen to `localhost:53`

i uninstalled then reinstalled, stopped then started, deactivated then activated.

router is at 192.168.0.1 and clients are set to grab DNS from DHCP, but since nextdns is only listening on localhost, LAN clients get no DNS. running `nextdns config set -listen 0.0.0.0:53` fixes it, but i must be missing something. why is this extra step necessary?

**background**:
DHCP is set to advertise DNS at 192.168.0.1.
system nameserver was blank, setting it to 
![image](https://user-images.githubusercontent.com/87547/87881441-1f9b8600-c9ae-11ea-9c5c-883591dba7eb.png)
did not help. what should I enter here?

PS: i already had to stop and `systemctl disable dnsmasq systemd-resolved` because nextdns does not disable them, and won't run since the port is already bound. do i enable `dnsmasq` again? `systemd-resolved` must be off (would be good if the installer auto disabled it)

**Comment by rs** [comment]
Did you use the installer? If yes, can you run it again with DEBUG=1 at the beginning of the line and send me the transcript?

**Comment by gaia** [comment]
I did `sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'` 

now running `sh -c 'sh -c "$(curl -sL https://nextdns.io/install)" DEBUG=1'`

should I uninstall first? or a (C) reinstall is enough?

**Comment by rs** [comment]
Use `DEBUG=1 sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`

**Comment by gaia** [comment]
nothing was printed to the screen, debug file didn't get created, at least not in `/config/nextdns/` or the dir where I ran the install from

**Comment by rs** [comment]
It should set setup-router to true, then the listen parameter becomes ineffective.

**Comment by gaia** [comment]
thanks. I have `setup-router true`.

is it correct to disable dnsmasq?

**Comment by rs** [comment]
yes
