### ISSUE TITLE
Cannot connect NextDNS on command prompt in Window 10 

### ISSUE THREAD

**Issue by David-H-1** [nextdns/nextdns#289]
Here are my inputs and outputs:
C:\Program Files\NextDNS>nextdns run
nextdns.error(3): Cannot start control server: open \\.\pipe\nextdns-cli: Access is denied.
nextdns.info(1): Starting NextDNS 1.7.0/windows on localhost:53
nextdns.info(1): Listening on TCP/localhost:53
nextdns.info(1): Listening on UDP/localhost:53
nextdns.error(3): Startup failed: proxy: tcp: listen tcp 127.0.0.1:53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Error: proxy: tcp: listen tcp 127.0.0.1:53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

C:\Program Files\NextDNS>nextdns activate
Error: activate: localhost:53: no address found

How do I resolve this?

**Comment by David-H-1** [comment]
On Firefox because I use DNS over HTTPS it is working OK,
However on legacy Microsoft Edge it appears like this
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/60801469/87881800-2f858b00-c9eb-11ea-96c0-155073589cc3.png">
_Sensitive information has been redacted for privacy._

**Comment by rs** [comment]
You need to use the `start` sub-command, not `run`. Also, your command prompt must be admin.

**Comment by David-H-1** [comment]
> You need to use the `start` sub-command, not `run`. Also, your command prompt must be admin.

I AM the administrator

**Comment by David-H-1** [comment]
I used the start command but in Legacy Edge it still shows that I am not using NextDNS at all

**Comment by rs** [comment]
Your user need to be the administrator AND you need to open an admin command prompt.

**Comment by teohhanhui** [comment]
I have the same problem on Windows 10.

    > nextdns start
    > nextdns status
    running
    > nextdns activate
    Error: activate: localhost:53: no address found

This is what I had to do:

    > nextdns config set -listen 127.0.0.1:53

**Comment by 8227846265** [comment]
@teohhanhui - I had the same error upon installation Error: activate: localhost:53: no address found

Tried using your command
nextdns config set -listen 127.0.0.1:53

And it works! I can finally use NextDNS officially with my VPN to get encrypted DNS and VPN running system-wide!
