### ISSUE TITLE
Add First-Party Tracker List as Backup

### ISSUE THREAD

**Issue by sr093906** [nextdns/nextdns#29]
https://github.com/WaLLy3K/wally3k.github.io/commit/721e82a281070578cbb754cfd359e67609507921

**Comment by rs** [comment]
NextDNS already handle first party trackers. Read more about it here: https://medium.com/nextdns/nextdns-added-cname-uncloaking-support-becomes-the-first-cross-platform-solution-to-the-problem-e3f437f84342
