### ISSUE TITLE
Google Play Store doesn't work any more

### ISSUE THREAD

**Issue by David-H-1** [nextdns/nextdns#291]
When I am connected to the NextDNS via Android 10's DNS over TLS the Google Play Store does not work any more! All the apps are stuck at "download pending" stage, as shown in this picture![Screenshot_20200720_203808_com.android.vending.jpg](https://user-images.githubusercontent.com/60801469/88010211-e1b07600-cb03-11ea-83e4-69d50605e589.jpg)

Restarted Google Play Store-no use!
Cleared ALL the cache of Google Play Store and Google Play services - no use either!
Reboot the phone- still no use!
However when I stopped using NextDNS the download sometimes work again!

I checked my block logs and there is no Google Play related domains blocked. I nearly have all the filters enabled in the configuration except for GameIndustry, No Google and No Facebook

What the [bleep] should I do??? I am so frustrated!!!

**Comment by David-H-1** [comment]
Here are all the block logs during the time period when I cannot download any apps![Screenshot_20200720_204415_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/60801469/88010496-86cb4e80-cb04-11ea-9938-841911f0d668.jpg)![Screenshot_20200720_204411_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/60801469/88010498-87fc7b80-cb04-11ea-9ca2-c63b79b8e425.jpg)![Screenshot_20200720_204406_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/60801469/88010505-892da880-cb04-11ea-95cf-65599a880d21.jpg)

**Comment by David-H-1** [comment]
I find the possible problem
connectivitycheck.gstatic.com was blocked. It may prevent the Google Play Store from checking the Internet connectivity

**Comment by David-H-1** [comment]
It only happens when connecting via DNS over TLS, not through the official app

**Comment by David-H-1** [comment]
OK I figure it out it's a filter problem

**Comment by romaincointepas** [comment]
Could you share what the problem was?

**Comment by David-H-1** [comment]
It is the problem of the Energized Xtreme extension package. It is too aggressive that it blocks many domains of Facebook and Google and frequently breaks the websites and apps

**Comment by marcelloinfoweb** [comment]
I have the same problem
