### ISSUE TITLE
Netguard.me is wrongly blocked.

### ISSUE THREAD

**Issue by nihalanand697** [nextdns/nextdns#294]
www.netguard.me is blocked by Threat Intelligence Feed but is a genuine site of the famous Firewall for android named Netguard.
Kindly look into it.
:D

**Comment by Gamer4Life2020** [comment]
Then put it on your allow list, as they are not going look into everyone's request to unblock a site.
Especially on github, if they cared about doing do they would have a place on their site to do so/report.
No idea on the app don't use it. Though so far they are better then cloudflare and open dns as far of customizing goes and price it cheap.

**Comment by rs** [comment]
Please report this to https://github.com/nextdns/metadata.
