### ISSUE TITLE
Conflict with naming: whitelist or allowlist?

### ISSUE THREAD

**Issue by David-H-1** [nextdns/nextdns#295]
&lt;Describe the bug>

**Context**
 - Version [e.g. 1.5.2]: Newest
 - Platform [e.g. macOS, ASUS-Merlin]: ALL

![photo_2020-07-26_20-21-50](https://user-images.githubusercontent.com/60801469/88501064-e40a4880-cfb9-11ea-89b0-50f8d10321d9.jpg)

<img width="661" alt="Screenshot 2020-07-26 201839" src="https://user-images.githubusercontent.com/60801469/88501100-fab09f80-cfb9-11ea-8fa7-29a4d48a5e99.png">

So would you please change all references of "whitelist" to "allowlist"? It appears as "allowlist" in the menu but "whitelist" in the logs. What the heck?!

**Comment by rs** [comment]
This will be fixed in the UI. This repo is for the CLI client.
