### ISSUE TITLE
CLI on Pi reporting all device traffic as from network router

### ISSUE THREAD

**Issue by petebocken** [nextdns/nextdns#296]
I've installed CLI on a Raspberry Pi and setup the /etc/hosts file with all my device IPs and hostnames. I switched my Linksys Velop to only use the Pi for the DNS server. NextDNS logs and analytics is showing all traffic that is not already setup with the apps (Mac, iOS, Windows, etc) as my main parent Velop (main router) instead of designating each device on the network.

When I individually tested the Pi as the DNS sever on some devices manually, they recorded as a NextDNS device just fine, but I thought by adding my Pi as the DNS server on my router it would see each device name individually the traffic is from and read the hosts file on the Pi and record it correctly per device in NextDNS.

What am I doing wrong?

NextDNS CLI on the Pi's config:

log-queries false  
discovery-dns   
hardened-privacy false  
listen localhost:53  
report-client-info true  
use-hosts true  
timeout 5s  
auto-activate true  
control /var/run/nextdns.sock  
cache-max-age 0s  
max-ttl 5s  
config {redacted}  
cache-size 10MB  
detect-captive-portals false  
bogus-priv true  
setup-router true

**Comment by rs** [comment]
You need to change the DNS configured by DHCP on your router, not the DNS your router use as an upstream.

**Comment by petebocken** [comment]
I kind of understand you, but maybe this is a limitation on the Velop.

I have all my devices setup to use 192.168.10.1 (my parent Velop) as DNS (at least those that let me set it, some IoT devices may indeed be hard coded to use a different public DNS like Google). Then in my Velop setup under DHCP Server, I have static DNS set to my Pi’s IP.

So I figured that if a device is setup to use the Velop as DNS server and the Velop’s DNS server is setup for the Pi, then the device would use the Pi for DNS. I do believe it is working now, because in NextDNS logs I see entries for Roku, HDHomeRun and Tesla telemetry/log servers. But it’s all under one device “velop1” my main router, which is indeed what I named it in the Pi’s hosts file instead of reading my Pi’s host file and recording each device’s traffic in NextDND separately.

So I guess I could go around to all my devices and try to manually specify they use my Pi for DNS, although like I said most IoT devices don’t give you that option. Which is why I wanted to just have them grab the DNS server from my DHCP server (velop1).

Or do I need to setup my Pi as a DHCP server, disable DHCP server on the Velop, and this could possibly work without having to manually specify each devices DNS server?

**Comment by rs** [comment]
Can't you configure the dhcp server running on your router to use the IP of your pi as a DNS?

**Comment by petebocken** [comment]
Yes, that is what I am doing. However, it does appear to be some limitation or bug with Velop. Here is another person having the same issue when using Pi-hole. 

https://www.reddit.com/r/LinksysVelop/comments/hugo7x/dhcp_server_and_dns_handling/

I’ll reach out to Linksys, but I’m not hopeful. I’m guessing if I want better reporting, I’ll need to switch to a different router.
