### ISSUE TITLE
NextDNS Add-on for Home Assistant

### ISSUE THREAD

**Issue by domotiquefacile** [nextdns/nextdns#297]
I would like to replace Adguard Home by NextDNS but I would like to keep the feature to identify LAN clients (LAN hostname reporting) instead of grouping every LAN client behind my external IP address.
Adguard Home is running through Home Assistant and I have a Fritzbox router.

I don't see any solution except
A) modifying each client: install an app or manually configure the DNS
B) running the NextDNS CLI client on Home Assistant
C) somehow configure the Fritzbox router (which just got the DoT feature)

As A) is not really possible (some smart devices cannot be configured), and C) seems to be impossible, would you perhaps consider adding the NextDNS CLI to the Home Assistant add-on store ?
It would be really handy to just be able to install NextDNS through a click on the Home Assistant interface.

Thanks

**Comment by rs** [comment]
You can install it on the linux hosting home assistant, it should work out of the box.

-Olivier

**Comment by domotiquefacile** [comment]
Indeed, however as I am running Home Assistant through Hass.io:
- I am not sure what will happen in case of update or backup/restore ("Hass.io has its own operating system, a supervisor Docker container and the Home Assistant docker container")
- It would much easier for the average Home Assistant user to install through an add-on

**Comment by MatthewGreen** [comment]
Definitely upvoting for this as a feature request. Today I have the same config where for two VLANs in my home network, I use AdGuard as the Name Server. I am using AdGuard as a Home Assistant add-on (where Home Assistant is of the Hass.io build - same as @domotiquefacile). 

I use DoH on AdGuard with NextDNS as my upstream provider. Of course this method, while fine, introduces AdGuard as a SPOF in terms of the Name Server and an unnecessary middle person given the feature set of NextDNS. Finally, this method also takes away the per-device level logging. A nice to have of course.

**Comment by joergchm** [comment]
Would love to have NextDNS as an Add-on for Home Assistant!

**Comment by dsopkin** [comment]
Having a card for NextDNS would be really helpful to track analytics and logs. A binary sensor could be used to show if the local network is using NextDNS as the DNS resolver (or if it flipped back to another one). If you have multiple configs, being able to show those separately would be helpful. Finally, if you are using Home Assistant as your main DNS server, you can add a line to use the DNS-over-HTTPS or DNS-over-TLS functions as well.

**Comment by gammerboy** [comment]
If running hassio on rpi docker container for nextdns can be added using portainer. From what I've tried terafin/nextdns-proxy from docker hub works without much config, I just had to enter the config id to get it working. I have a diff setup so I just put my device to forward dns queries to the listening port otherwise I guess port mapping will have to be done.
Having a officially maintained docker container would be nice tho.

**Comment by cromulus** [comment]
Agreed on all fronts. It would also be very helpful to be able to disable/enable nextdns from home assistant.

**Comment by lbouriez** [comment]
It could be great to set the home ip through this addon. My domain DNS are in cloudflare and I need to unproxy the domain for NextDNS to work :/

**Comment by heytcass** [comment]
There seems to be an API tool written in Python already, which based on what I've seen for previous Home Assistant integrations seems to be step one. I'm not a Python developer by any stretch, so I can't write it myself, but here's the Github if someone else would like to use it as a jumping-off point.

[NextDNS-API](https://github.com/rhijjawi/NextDNS-API)

**Comment by billytkid** [comment]
Hi, I've made one here : https://github.com/billytkid/ha-addon-nextdns
Give it a go
