### ISSUE TITLE
Add request to whitelist option on block page

### ISSUE THREAD

**Issue by ChrisColotti** [nextdns/nextdns#299]
Having the block page is great.  Would be added benefit to add a "Request URL to be whitelisted" so someone can click it and generate an email notification to the account manage to look at it or just add to the whitelist with a click.  OpenDNS does this and it's very handy, but requires customization of the block page....also a good feature to have to brand the message.

**Comment by rs** [comment]
Please only use this repo for CLI related issues. We have this feature in our backlog BTW.
