### ISSUE TITLE
Delayed start

### ISSUE THREAD

**Issue by mfat** [nextdns/nextdns#301]
I use shadowsocks-libev client on my router and have installed NextDNS since it works way better that ss-tunnel that handles DNS resolution for shadowsocks.
However NextDNS needs to start AFTER the shadowsocks client, otherwise I'll have no internet. 
Can you please add a delayed start option?
Also which port does NextDNS run on? How can I redirect DNS requests manually to NextDNS? Thanks.

**Comment by Fail-Safe** [comment]
> NextDNS needs to start AFTER the shadowsocks client

What OS distro do you use? Could you just modify the NextDNS init.d file to start after shadowsocks?

> Also which port does NextDNS run on?

NextDNS communicates to the upstream servers via HTTPS over TCP 443. On the client (listening) side, it is standard DNS (UDP 53/TCP 53) by default.

> How can I redirect DNS requests manually to NextDNS?

Can you elaborate on your configuration? Are you asking how to have your client machines point to your NextDNS client?

**Comment by mfat** [comment]
I use it on the latest OpenWrt. I have a shadowsocks-libev client running on the router. It works as a transparent proxy. DNS is handled by NextDNS. It runs on its default port, I haven't changed the configuration. 
Every time I boot up the router, I don't have internet. I have to turn NextDNS off and back on. Then the problem is fixed.

**Comment by Fail-Safe** [comment]
In OpenWrt, NextDNS' init.d file is set to start just after `init.d/network` and stop just after `init.d/network`:
```
root@OpenWrt:~# cat /etc/init.d/nextdns
#!/bin/sh /etc/rc.common

USE_PROCD=1

# starts after network starts
START=21
# stops before networking stops
STOP=89
...
```

`Init.d/network` START=20 and STOP=90. You could modify the shadowsocks init.d file to have the start and stop mimic what NextDNS currently has (START=21, STOP=89), then modify NextDNS to START=22 and STOP=88.

This might fix your scenario, though you might have to modify these values after each time you upgrade these packages (or add these init.d files to your `/etc/sysupgrade.conf` so they survive upgrades).

Alternately, if you're comfortable with shell scripting, you could write an old-school loop in `/etc/rc.local` to keep checking the shadowsocks service state with a 1-2 second sleep in between. Then once the state of the service goes to "running", just issue a `nextdns restart` command and you should be set.

**Comment by Fail-Safe** [comment]
@mfat Did the above suggestions work out for you? If so, please consider marking this issue as closed.

**Comment by mfat** [comment]
I don't have access to the router for now. I will do ASAP. Thanks.
