### ISSUE TITLE
Nextdns blocking apt in WSL2

### ISSUE THREAD

**Issue by lminer** [nextdns/nextdns#302]
I'm running WSL2 on windows and have to disable nextdns to be able to sudo install or upgrade anything.

I'm getting the following error:
```
Err:1 https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/amd64  InRelease
  Temporary failure resolving 'nvidia.github.io'
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:4 https://download.docker.com/linux/ubuntu focal InRelease
  Temporary failure resolving 'download.docker.com'
Err:5 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
  Temporary failure resolving 'developer.download.nvidia.com'
```

**Comment by Mikaela** [comment]
I think this is more of a WSL issue, there are many reported at https://github.com/microsoft/WSL/issues?q=is%3Aissue+is%3Aopen+resolv.conf and as a workaround you can check /etc/resolv.conf instructions on how to manage the file manually and point it directly to some DNS server (while unencrypted though) and it should work.

https://github.com/microsoft/WSL/issues/994 may help in the future.

**Comment by TheRealEliteOwl** [comment]
> I'm running WSL2 on windows and have to disable nextdns to be able to sudo install or upgrade anything. 
> I'm getting the following error:
> ```
> Err:1 https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/amd64  InRelease
>   Temporary failure resolving 'nvidia.github.io'
> Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
>   Temporary failure resolving 'archive.ubuntu.com'
> Err:3 http://security.ubuntu.com/ubuntu focal-security InRelease
>   Temporary failure resolving 'security.ubuntu.com'
> Err:4 https://download.docker.com/linux/ubuntu focal InRelease
>   Temporary failure resolving 'download.docker.com'
> Err:5 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
>   Temporary failure resolving 'developer.download.nvidia.com'
> ```

Run: `cat /etc/resolv.conf`
Should look like this: 
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.XXX.XXX.XXX
```

If you have nameserver 172.XXX.XXX.XXX, this is probably your culprit as it's pointing towards your WSL Service Hyper-V Network Interface, which in my experience rarely forwards correctly. 
 
**This will fix Docker issues with WSL2 as well.**  
You can change this to your NextDNS config nameservers.

Probably not a factor, but make sure your sub-system environment is correctly set to WSL2. Ex. Ubuntu-18.04 is configured to WSL2.

**Comment by lminer** [comment]
@TheRealEliteOwl it does indeed look like that. Do I uncomment `generateReolvConf = false` and then stick in a dns nameserver of my choice?
