### ISSUE TITLE
DNS servers randomly alternating between NextDNS and my ISP's (Debian)

### ISSUE THREAD

**Issue by paps** [nextdns/nextdns#307]
Hi, thanks a lot for this great project.

I have a very simple setup on Debian Sid, nothing much installed, not even NetworkManager.

I've installed nextdns by doing the recommended `sh -c "$(curl -sL https://nextdns.io/install)"`

And here's what I get when I look at my dashboard, an alternating resolver (I'm not even refreshing the page):
![Peek 2020-08-26 00-20](https://user-images.githubusercontent.com/319424/91233942-97d63380-e732-11ea-963f-ed969b5efaf0.gif)

"Orange" is my ISP. I'm behind their provider router (ethernet) which obviously advertises their own DNS servers through DHCP (if that matters)

When I run `sudo systemctl restart nextdns` I see
```
Aug 26 00:28:11 paris nextdns[430529]: Activating
Aug 26 00:28:11 paris nextdns[430529]: Activate: NetworkManager resolver management: exit status 1
```
in the systemd logs which does not look too good, but then things start resolving (be it on orange or nextdns)

Any idea about what might cause this? Thanks

**Context**
 - Version 1.7.1 
 - Platform Debian Sid/unstable

**Comment by theeddie** [comment]
Just want to point out I have the same issue

**Comment by whitedragon551** [comment]
Also have the same issue, running this on the UDMP.

**Comment by paps** [comment]
So like I said in my original post, I didn't even have the NetworkManager running.

Turns out that
- installing `network-manager` (and `network-manager-gnome` but I guess this one is not needed)
- and changing `managed=false` to `managed=true` in `/etc/NetworkManager/NetworkManager.conf`
- and enabling and starting the `NetworkManager` service with:
   - `sudo systemctl enable NetworkManager`
   - `sudo systemctl start NetworkManager`

fixed my problem.

Seems like there are strong interactions between NetworkManager and NextDNS, I'm not sure exactly why or how. Anyway, that fixed it for me and I don't see anything wrong in having NetworkManager running on both desktop PCs I run

**Comment by paps** [comment]
Nevermind, I spoke too fast.

What I said above :point_up: is incorrect, it does not fix the problem

Anybody have a clue?

**Comment by rs** [comment]
Can you please try to disable auto activate `sudo nextdns config set -auto-activate=false; sudo nextdns restart` then set manually your DNS to 127.0.0.1 in /etc/resolv.conf to see if it resolves the issue?

**Comment by rs** [comment]
If it still does not work, you might be using a non supported DHCP client that overrides /etc/resolv.conf. Make sure you disable that.

**Comment by paps** [comment]
Alright thanks, I finally figured it out. Adding (or rather, uncommenting) the `prepend domain-name-servers 127.0.0.1;` line in `/etc/dhcp/dhclient.conf` solves the problem

This makes me believe that NextDNS does not work by default on Debian sid. Dhclient regularly overrides `resolv.conf` with parameters coming from the network.

> you might be using a non supported DHCP
I mean... I'm using all the defaults from Debian sid, I haven't touched anything. What do you think?
