### ISSUE TITLE
forwarder failover

### ISSUE THREAD

**Issue by rakheshster** [nextdns/nextdns#308]
Hi,

Not a request really but more of a question. If I specify two forwarders does the CLI round-robin between them or try the second one if the first is not reachable? I started using this CLI today and noticed that even though I have two forwarders specified if the first one is down the CLI doesn't seem to try the second one. 

Maybe it's just coincidence and it does round robin and I was unfortunate to hit the forwarder that was down each time ... 

Thanks.

**Comment by timkgh** [comment]
Similar to #305

**Comment by rakheshster** [comment]
> Similar to #305 

It's the opposite for me actually. :) The first entry was what went down each time and NextDNS couldn't resolve my home network as it couldn't contact that forwarder. If it did Round Robin like you suggested or there was an option to try the alternate forwarders if the first one is down that'd be great.
