### ISSUE TITLE
Mac OS client - Catalina - with VPN client

### ISSUE THREAD

**Issue by krioso** [nextdns/nextdns#31]
I have found that the VPN client overrides the NextDNS DNS setting unless you start NextDNS client after VPN established. Ideally, NextDNS client would detect the network change and reestablish. Can be overridden in a browser like Firefox, where a custom DNS-oer-https connection can be indicated, but doesn't work for other client-network comms.

**Comment by rs** [comment]
Are you talking about nextdns-cli on macOS or the NextDNS app on the app store?

**Comment by krioso** [comment]
App Store….haven’t tried CLI on Mac, only Linux.

I put the custom DNS in the VPN client and it seemed to work OK. However, it still feels like the NextDNS app might detect a network change and connect again.

**Comment by rs** [comment]
It's a good point, we'll test that out. Thx.

**Comment by krioso** [comment]
Thanks for your efforts! Using across Win, Linux, Mac , mobile. Impressed so far.

**Comment by NoSync** [comment]
Wouldn't call it solved - connecting to any VPN causes NextDNS to stop working. Detecting a network change and reconnecting would be nice. :-)

**Comment by romaincointepas** [comment]
> I have found that the VPN client overrides the NextDNS DNS setting unless you start NextDNS client after VPN established.

@krioso what VPN client were you using?

**Comment by NoSync** [comment]
(I'll also specify that I'm having the same issue with both macOS and Linux - maybe it's obvious, but more info never hurts)

**Comment by GauthierPLM** [comment]
I have this issue too when enabling VPN (ProtonVPN) or switching network (switching Wifi) when using the CLI on MacOS Catalina with Firefox.

It seems network changes are not properly detected on Mac, and the DNS fails to reconnect. Restarting the service via the CLI fixes the issue.

**Comment by rs** [comment]
Do you still have the issue with recent version of the CLI?

**Comment by krioso** [comment]
I still find there are times where I need to do a stop/start. The connection will be blocked but is immediately restored by doing this. I’ve just learned now what to look for. 

I sometimes find it with the GUI as well. When I have connection issues (I tend to jump IP and networks and shift around a lot) the disable / enable has become part of my standard troubleshooting go-to (or a stop/start with CLI).

**Comment by rs** [comment]
Closing as this issue relates to macOS GUI client.

**Comment by NoSync** [comment]
I still get this issue with the CLI client on macOS. When I connect to a VPN (in my case ExpressVPN and SurfShark) it overrides DNS resolution.
