### ISSUE TITLE
NextDNS 1.8.0 error

### ISSUE THREAD

**Issue by rakheshster** [nextdns/nextdns#310]
The `nextdns log` gives the following error after upgrading to version 1.8.0 on armv7 (Raspberry Pi 4B running Raspbian):

```
$ sudo nextdns log
Error: exec: "podman": executable file not found in $PATH
```

It seems to be working fine apart from this. 

I have another Pi running the same OS etc. and it is currently on NextDNS 1.7.1 and the log command works fine there. 

**Context**
 - Version: 1.8.0 
 - Platform: Linux 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

**Comment by rs** [comment]
Dup #309
