### ISSUE TITLE
Errors after upgrading

### ISSUE THREAD

**Issue by maghuro** [nextdns/nextdns#312]
![Screenshot_20200908-104109966](https://user-images.githubusercontent.com/1546139/92460412-dbfc1600-f1bf-11ea-8159-d42f4cceb60e.png)
![Screenshot_20200908-103447826](https://user-images.githubusercontent.com/1546139/92460417-ddc5d980-f1bf-11ea-9fb4-3a5a99f40606.png)

After upgrading for 1.8.1 I'm getting those errors.
Asus wrt Merlin

**Comment by baujahr** [comment]
Same thing here using a Unifi Security Gateway.
