### ISSUE TITLE
Ubuntu: after pkg upgrade, nextdns is enabled in systemd even if it was disabled before

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#314]
Ubuntu 18.04.5 LTS
I have nextdns installed but **disabled** (`sudo systemctl disable nextdns`)

If there is a package update in the repo and I install it, the systemd unit changes to enabled and nextdns starts automatically. It should instead preserve the previous disabled state.

**Context**
 - Version [e.g. 1.5.2]: Ubuntu 18.04.5 LTS
 - Platform [e.g. macOS, ASUS-Merlin]: 1.8.2

**Comment by rs** [comment]
Good point. That won’t be a trivial change tho.
