### ISSUE TITLE
UDM (Pro): Local name resolution fails

### ISSUE THREAD

**Issue by owine** [nextdns/nextdns#316]
Installed nextdns cli on my UDM Pro and it works as expected, but local name resolution does not function properly. I have not configured a separate forwarder for the local domain. Prior to using the nextdns CLI client, local name resolution worked as expected through the UDMP's resolver. Client names are reporting correctly to/from the CLI client.

I also have some log entries similar to the below when looking up local PTR records:

`Sep 08 09:23:14 UDM-ProFrontCloset nextdns[8466]: Query 10.17.89.25 UDP PTR lb._dns-sd._udp.0.89.17.10.in-addr.arpa. (qry=57/res=12) 0ms : not found`

**Context**
 - Version: 1.8.2
 - Platform: UbiOS - UDM Pro FW 1.8.0

**Comment by owine** [comment]
Thanks - I presume this will deliver in a 1.8.3 release? Would you like me to test in any way?

**Comment by rs** [comment]
Yes it will. If you know how to test it, that would be great yes.

Here is how you can test it:

```
# From the repository:
GOARCH=arm64 GOOS=linux go build
scp nextdns root@<IP of the UDM>

# On the UDM
nextdns stop
podman cp nextdns unifi-os:/usr/bin/nextdns
nextdns start
```

**Comment by owine** [comment]
In a couple of quick tests this is working as expected now. Local lookups plus PTR. Thanks!

**Comment by rs** [comment]
Thanks for checking.

**Comment by mbnn** [comment]
Will this be pushed today the 1.8.3? :) Thx

**Comment by rs** [comment]
Probably yes

**Comment by mbnn** [comment]
@rs could you pls push 1.8.3 out? :) Since this local name resolution fix is really important :)

**Comment by mbnn** [comment]
Thx :)

**Comment by Veldkornet** [comment]
I'm still getting this on 1.8.3, something special I need to do?

```
Sep 10 20:24:06 UDMP nextdns[9197]: Query 192.168.1.25 UDP PTR lb._dns-sd._udp.0.1.168.192.in-addr.arpa. (qry=60/res=12) 0ms : not found
Sep 10 20:24:23 UDMP nextdns[9197]: Query 192.168.1.28 UDP PTR 2.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
Sep 10 20:24:23 UDMP nextdns[9197]: Query 192.168.1.28 UDP PTR 2.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
Sep 10 20:24:23 UDMP nextdns[9197]: Query 192.168.1.28 UDP PTR 2.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
Sep 10 20:24:23 UDMP nextdns[9197]: Query 192.168.1.28 UDP PTR 2.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
Sep 10 20:24:23 UDMP nextdns[9197]: Query 192.168.1.28 UDP PTR 2.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
```

**Comment by rs** [comment]
Are you sure this IP as a reverse? What do you get for nslookup of this IP from the router?

**Comment by Veldkornet** [comment]
Hmm, I see the issue. 
The devices that are getting everything from DHCP are working correctly. The switches and AP's have manual configs, and these aren't working.

```
# nslookup 192.168.1.2
Server:         127.0.0.1
Address:        127.0.0.1:53

** server can't find 2.1.168.192.in-addr.arpa: NXDOMAIN
```

I suppose I could just add them as rewrites in NextDNS since there's only a few...

**Comment by rs** [comment]
The nslookup queries the udm resolver. If it’s not found there, it means this name is not exposed by udm with or without nextdns running.
