### ISSUE TITLE
Local name resolution not working right with UDM

### ISSUE THREAD

**Issue by mbnn** [nextdns/nextdns#317]
As discussed in https://github.com/nextdns/nextdns/issues/174

After configuring the new cli for UDM(Pro) and choosing Yes for router enable and so on local name resolution is not successful. this in the logs;

> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 14.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 12.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 36.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 9.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 10.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 1.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 5.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 60.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 12.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 37.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 14.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 10.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 1.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 30.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 31.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 5.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 9.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 36.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 30.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 60.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 3.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 12.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 14.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 37.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 10.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 1.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 3.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 5.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 9.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 31.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 36.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 30.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 60.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 9.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 12.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 14.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 37.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 1.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 10.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 3.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 5.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 12.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 31.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 36.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 30.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 9.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 60.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 10.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 14.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 37.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 1.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 30.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 3.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 5.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 31.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 36.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 37.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 60.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 3.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 31.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 4.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 4.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 4.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 4.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 4.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 19.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 17.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 19.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 17.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 17.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 19.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 19.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 17.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 19.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:06 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 17.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:07 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 22.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:07 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 22.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:07 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 22.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:07 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 22.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:07 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 22.1.168.192.in-addr.arpa. (qry=43/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 100.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 117.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 117.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 100.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 100.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 117.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 100.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 117.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 117.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 100.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 139.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 131.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 131.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 139.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 139.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 131.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 131.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 139.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 131.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 139.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 149.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 149.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 149.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 149.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:16 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 149.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:17 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 123.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:17 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 123.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:17 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 123.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:17 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 123.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:17 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 123.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:23 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 165.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:23 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 165.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:23 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 165.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:23 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 165.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:23 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 165.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 220.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 220.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 220.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 220.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 220.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 190.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 190.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 190.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 190.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:27 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 190.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:28 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 198.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:28 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 198.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:28 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 198.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:28 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 198.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:28 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 198.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:33 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 238.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:33 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 238.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:33 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 238.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:33 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 238.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found
> Sep 09 07:32:33 UniFiDreamMachinePro nextdns[19004]: Query 192.168.1.239 UDP PTR 238.1.168.192.in-addr.arpa. (qry=44/res=12) 0ms : not found

**Context**
 - Version: 1.8.2 NextDNS, 1.8.0 UDM Pro
 - Platform: UnifiOS

**Comment by rs** [comment]
Dup #316
