### ISSUE TITLE
UniFi-OS rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy

### ISSUE THREAD

**Issue by Veldkornet** [nextdns/nextdns#318]
When starting or activating NextDNS, the following can be seen in the NextDNS log:
`Error: setup resolv.conf: rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy`

**Context**
 - Version [e.g. 1.5.2]: 1.8.3 
 - Platform [e.g. macOS, ASUS-Merlin]: unifi-os

Using a UniFi UDMP on firmware 1.8.1 RC 3 and controller 6.0.19

**Comment by rs** [comment]
try disabling auto-activate

**Comment by Veldkornet** [comment]
Well if I run `nextdns deactivate` and then `nextdns activate`, I have the same issue. Is that the same thing?

I also checked the `/etc/resolv.conf` and all that's in it is the below, this this expected?
`nameserver 127.0.0.1`

I asked because I still ahve these messages in my log:
`nextdns[32503]: Query 192.168.1.25 UDP PTR lb._dns-sd._udp.0.1.168.192.in-addr.arpa. (qry=60/res=12) 0ms : not found`

**Comment by rs** [comment]
just do not activate it, it’s not needed on a router.

**Comment by rs** [comment]
Those errors are certainly due to the fact those PTR records do not exist.

**Comment by Veldkornet** [comment]
Hmm, I see, okay... I've configured it as below now (also disabled caching in an attempt to get the local resolution to work), is this correct? 

```
# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: LATEST_RELEASE: 1.8.3
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): c
NextDNS Configuration ID (default=xxxxxx): xxxxxx
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: y
Only use DNS servers located in jurisdictions with strong privacy laws.
This may increase latency.
Enable hardened privacy mode (may increase latency)? [y|N]: n
Make nextdns CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Note that enabling this feature will disable dnsmasq for DNS to avoid double
caching.
Enable caching? [Y|n]: n
Changes DNS settings of the host automatically when nextdns is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically setup local host DNS? [Y|n]: n
NextDNS installed and started using ubios init
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): e
```

So that clear up this issue then, it all seems to be working... except the local lookups as in #316, this still fails

**Comment by rs** [comment]
The caching should have no impact on this. You should not disable it.

**Comment by Veldkornet** [comment]
Cool, I've fixed that, thanks
