### ISSUE TITLE
ubuntu touch support

### ISSUE THREAD

**Issue by Fuseteam** [nextdns/nextdns#319]
i'm a user of the ubuntu touch mobile operating system. it would be nice if i could run this on there.
while most apps are confined, the devs have said the binary should work if it compiled for the arm architecture

**Comment by rs** [comment]
did you try it? what do you get?

**Comment by Fuseteam** [comment]
i have yet to find the time to compile it for arm, if someone has an arm binary i would be willing to test it with that

**Comment by rs** [comment]
It’s already compiled for all variations of arm. The installer will pick the right binary.

**Comment by Fuseteam** [comment]
wrth "installer" do you mean the pakage manager?

**Comment by rs** [comment]
This is the installer: `sh -c "$(curl -sL https://nextdns.io/install)"`

**Comment by Fuseteam** [comment]
ah right thanks

**Comment by Fuseteam** [comment]
for testing purposes i made the rootfs writable and the installer script completes without problems.
i am however unable to start nextdns, possibly due to some networkmanager issue

**Comment by rs** [comment]
What do you get for “nextdns log”

**Comment by Fuseteam** [comment]
i get `-- No entries --`

**Comment by Fuseteam** [comment]
it seems to work fine so far.
what are the hurdles you see to get this working with a readonly rootfs?

**Comment by Fuseteam** [comment]
Why the sudden mass closure?
