### ISSUE TITLE
Unable to use on Ubuntu 18.04, "doh resolve: context deadline exceeded"

### ISSUE THREAD

**Issue by mendhak** [nextdns/nextdns#32]
Ubuntu 18.04 and NextDNS v1.2.10, I installed using the README instructions.   After installing, 

    sudo nextdns install -report-client-info -config xxxxxx
    sudo nextdns activate

When I try to browse or ping, I get nothing.  The dig just times out. 

    $ dig +short @127.0.0.1 example.com
    ;; connection timed out; no servers could be reached

When I do a 

    sudo systemctl status nextdns

I see:

> Dec 07 18:54:52 xps13 systemd[1]: Started NextDNS DNS53 to DoH proxy..
Dec 07 18:54:52 xps13 nextdns[3720]: Starting NextDNS 1.2.10/linux on localhost:
Dec 07 18:54:52 xps13 nextdns[3720]: Starting mDNS resolver
Dec 07 18:55:02 xps13 nextdns[3720]: doh resolve: context deadline exceeded
Dec 07 18:55:02 xps13 nextdns[3720]: doh resolve: context deadline exceeded

However!  When I try (after deactivating the service so that port 53 doesn't conflict)

    sudo nextdns run

I am able to dig just fine.  

Any idea what's wrong, or how to find out if I'm missing something?

**Comment by CritiKILL** [comment]
I also have this exact error on Manjaro 18.1.3 KDE
Kernel 5.3.12-1
nextdns version 1.2.11
Additional images are from KDE System Logs

![bug](https://user-images.githubusercontent.com/27539137/70400236-b9de2900-19de-11ea-97b8-6763f91b4fec.jpg)
![bug2](https://user-images.githubusercontent.com/27539137/70400237-b9de2900-19de-11ea-8d21-0acadd6f4964.jpg)

**Comment by rs** [comment]
Fixed in v1.3.0.
