### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by r4nd0m123** [nextdns/nextdns#320]
Please consider adding something similar to rules found in YogaDNS. This feature would allow a user to pick which DNS server would resolve a given hostname.

https://yogadns.com/docs/#rules

**Comment by Fail-Safe** [comment]
Unless I am misunderstanding your question (I am not familiar with YogaDNS), NextDNS client already supports this today with split horizon configuration: https://github.com/nextdns/nextdns/wiki/Split-Horizon

**Comment by ignoramous** [comment]
Split horizon does leak DNS questions to upstream (NextDNS resolvers in this case) though, right?

**Comment by Fail-Safe** [comment]
@ignoramous No, for any domains I have specified in this split horizon configuration, I do not see the query forwarded to NextDNS.

**Comment by r4nd0m123** [comment]
Thanks.

I'm guessing this is only supported on Linux and macOS? Are there plans to incorporate this for other operating systems such as Windows and Android?

**Comment by Fail-Safe** [comment]
I have only used the client on Linux based OS and iOS/iPadOS, so I can’t comment authoritatively on Windows and Android. But I would suspect the configuration options in the Android client are much the same as the iOS client. If that holds true, you would be unable to configure split horizon on that client. AFAIK Windows has a config file as well, so this should be possible there.

I would ask, though, are you setting up a NextDNS client per device in your home/business? Do you have a scenario that precludes the setup of a single NextDNS client instance at your internet ingress/egress?

If the domains you are wishing to set up with split horizon are internal to your home/business, then having a single instance of the NextDNS client running on your router and serving DNS for all internal clients makes this a straightforward configuration.

On the other hand, if the domains you want to split horizon are domains you want handled in that fashion even outside your “home walls” then you might instead want to consider using NextDNS’ Rewrite feature in the Settings section of your NextDNS account. This requires that you 1) have a NextDNS account so you have a unique configuration ID and 2) are okay with the scenario @ignoramous referred to where NextDNS would see ALL DNS queries, even those intended for the rewritten domain entries.
