### ISSUE TITLE
NextDNS geo-location API for third-party DoH clients

### ISSUE THREAD

**Issue by ignoramous** [nextdns/nextdns#324]
Hi there,

I maintain a DoH client on Android, and I've had at least one user request that the client choose the nearest nextdns resolver than rely on `anycast`.

[I see that the cli relies on `router.nextdns.io`](https://github.com/nextdns/nextdns/blob/7106d9b4a265f93e32ff1b842e87e90cea7e480e/run.go#L414) and I'd have no qualms using it in our client provided the API doesn't one day change underneath from our noses (:

Can I expect `router.nextdns.io` to work forever with backwards compatibility?

Can I expect to be notified in case it had to break backwards compatibility?

Is there another API that I should use that's likely better?

Should we just not support this in our (third-party) client(s)?

Thanks.

**Comment by rs** [comment]
There is no guarantee as it is a private API.
