### ISSUE TITLE
NextDNS Blocks Zen Pinball Downloads

### ISSUE THREAD

**Issue by jputting** [nextdns/nextdns#325]
Hi,

I have the NextDNS app for macOS Catalina 10.15.6

I have installed the Zen Pinball 2 game  from the Apple App Store and when I try to download a new pinball table I get an error message stating "You must go online to continue".

This only happens when NextDNS is active, when I quit NextDNS everything works normally and I can download pinball tables.

I have tried removing all the filter lists,

I have also deactivated all the privacy and security options that I can find in my NextDNS configuration.

I have check all the logs and can find nothing at all which could cause this.

I have also added *.zenstudios.com to my "Allow List".

I have tried deleting my existing NextDNS  configuration.

But nothing I have tried solves this issue and NextDNS continues to block my Zen Pinball 2 from downloading pinball tables.

The quitting of the NextDNS app for macOS fixes this issue and when it has quit Zen Pinball 2 works normally and pinball tables can be downloaded.

I really would appreciate some help to solve this.

I have reached out to NextDNS via their Chat on their website and have been waiting and waiting and waiting and waiting for nearly 5 hours and still no response.

Their technical support is extremely poor or almost non existent.

**Context**
 - Version [e.g. 1.5.2]: 
 - Platform [e.g. macOS, ASUS-Merlin]:

**Comment by ThePowerOfDreams** [comment]
View the NextDNS logs to see what was blocked while you were playing the game. If logging is disabled, enable it during this troubleshooting.

**Comment by jputting** [comment]
Hi,

I have done exactly that many times and nothing at remotely related to this appears in the logs.

I can only download pinball tables when NextDNS has been quit when it's not active everything i works well.

So this is really a big mystery, it seems as though NextDNS mac app will not allow any type of connection needed to download the pinball tables.

The Zen Pinball 2 gives me an error message "You must go online to continue"

It's now over 6 hours of waiting and waiting and waiting and waiting for someone at NextDNS to start a chat to investigate this.

This is shockingly bad technical support, Delays of this length are inexcusable  and appallingly bad technical support will only damage the reputation of NextDNS.

Paying customers will cancel their NextDNS service and take their business to a company which provides prompt technical support.

**Comment by ThePowerOfDreams** [comment]
At least one of the items blocked while you are playing the game is the culprit, even if they seem to be totally unrelated.

**Comment by rs** [comment]
Please report this on https://github.com/nextdns/metadata. This repository is dedicated to the cli client.

**Comment by jputting** [comment]
Hi,

I have checked my NextDNS logs for the 10th time today after trying to download a pinball table.

I have extensively removed all filter lists, and disabled all the privacy and security options in every part of the NextDNS configuration.

My logs for "Blocked Queries" are blank because every security option and filter list is disabled and yet NextDNS app for macOS still will not let me download a pinball table.

I still keep getting the message from the Zen Pinball 2 "You must be online to continue".

I then check my NextDNS logs for blocked queries and absolutely nothing is in the "Blocked Queries".

I then disable/quit the NextDNS app for macOS and I can then instantly download a pinball table.

I don't how or why this occurring but this Zen Pinball 2 problem only occurs when NextDNS is active.

I have tried using a different NextDNS configuration, but NextDNS still blocks Zen Pinball 2 from downloading a pinball table.

**Comment by ThePowerOfDreams** [comment]
Is logging enabled in the settings page on the NextDNS website? If not, the logs will be empty. Ensure they are enabled and try again.

**Comment by jputting** [comment]
Hi,

Yes I am sure that logging is enabled as I can clearly see all the "allowed queries".

Once again there are no items in the "locked queries"  as I very thoroughly disabled every filter list and disabled all the privacy and security options that I could possibly find.

Yet NextDNS still somehow refuses to allow Zen Pinball 2 to download a pinball table.

Obviously NextDNS is blocking the type of connection that Zen Pinball 2 needs to establish and refuses to allow Zen Pinball to establish the needed network connection to permit the downloads to occur, thus causing the Zen Pinball 2 to believe its offline and then gives me the message that "You must go online to continue"

**Comment by ThePowerOfDreams** [comment]
It sounds like Zen Pinball is incorrectly determining that you are offline, instead of just trying to make the connection it needs to make without analyzing the situation (and incorrectly at that). You may wish to file a bug with the developer of that app instead.

**Comment by jputting** [comment]
Hi,

I do not believe that is the reason I am having trouble.

If that was the case Zen Pinball would continue to incorrectly determine that I was offline when NextDNS was quit/deactivated.


But Zen Pinball 2 can download pinball tables when NextDNS is not active.

This only occurs when NextDNS is activated.

**Comment by rs** [comment]
Try setting up nextdns with just the dns IPs and link IP instead of the mac client (or using cli). If it works that way, in means the game is interacting badly with the dummy VPN used by the mac client.

**Comment by ThePowerOfDreams** [comment]
Your hypothesis is incorrect; it is trying to evaluate your network setup and is incorrectly determining you're offline when NextDNS is active.

**Comment by jputting** [comment]
Hi,

I do believe that is what I was trying to say.

NextDNS is causing this game is to believe it is offline. 

The way NextDNS functions is interfering or blocking the game trying to establish or evaluate my network setup.

This should not be happening at all, I am now seriously about this potential for NextDNS to cause mac apps to believe they are offline.

How many mac apps have missed out on security updates because NextDNS has the potential to create the impression they are offline?
 
I am uninstalling this NextDNS as this has quite serious implications for macOS security.

**Comment by ThePowerOfDreams** [comment]
It is not an application's job to be determining the status of the network, but rather the operating system's networking layer.

You know not from whence you speak regarding neither networking nor security, sir.

**Comment by jputting** [comment]
Hi,

I don't really care about nitpicking the fine details.

If an installed app such as NextDNS is interfering with a macOS apps ability to establish a network connection, that is totally unacceptable.

The bottom line is that NextDNS client for macOS uses a dummy VPN, this has the potential to create security issues via causing macOS apps to believe they are offline.

I am not willing to argue this any further.

NextDNS for macOS has clearly demonstrated it can cause issues for other macOS apps.

NextDNS has interfered with a simple mac pinball game.

I shudder to think of the problems it could cause with security because of missed updates.

NextDNS is now forever banished from my mac.
