### ISSUE TITLE
Can NextDNS client be used with third party DOH server with authentication?

### ISSUE THREAD

**Issue by Blason** [nextdns/nextdns#327]
Hi Next DNS Team,

I have few queries pertaining to use NextDNS client to be used with third party DNS server which support DoH? Or Plain DNS Server?
If so is there any mechanism by which client can authenticate with server before serving request to avoid open dns?
Plus what mechanism you have used with URL authentication to authenticate clients with DNS server?

**Comment by rs** [comment]
This is not supported at the moment.
