### ISSUE TITLE
NextDNS CLI - VLANs

### ISSUE THREAD

**Issue by henrybelk** [nextdns/nextdns#328]
&lt;Describe the bug> Installed CLI on a VM of Raspbian to test with before I replace my PiHole on my network. Installed easily. Any device on the same /24 network as the VM can use CLI as their DNS without issue (reports analytics and logs correctly). If I try to use this VM from another VLAN for DNS, nothing is resolved. I have updated my FW policies to allow traffic to this new device. I can ping the new VM from the other VLANs and can see traffic for 53 from the VLANs to the new device, but nothing is resolved. I have the same setup working fine with PiHole (different VLANs going to PiHole on the same network as CLI). Tried with the option for Router-Setup being false and true with reboots and it didn't make a change.

CLI is on 10.10.10.0/24 network. Trying to use CLI as DNS from other VLANs (10.10.150.0/24, 10.10.50.0/24, etc). Any idea what I am missing?

**Context**
 - Version [e.g. 1.5.2]: 1.8.3
 - Platform [e.g. macOS, ASUS-Merlin]: Raspbian Buster

**Comment by rs** [comment]
Does it work if you force the query over tcp?

**Comment by henrybelk** [comment]
Not from a VLAN. From the same network as the CLI, I can.

**Comment by rs** [comment]
What do you get for `ss -lnpe|grep nextdns` from your rapsberry?

**Comment by henrybelk** [comment]
pi@raspberry:~ $ ss -lnpe|grep nextdns
u_str LISTEN 0      128                       /var/run/nextdns.sock 19359                                                 * 0                                    <-> ino:19362 dev:0/21 peers:
pi@raspberry:~ $

**Comment by henrybelk** [comment]
`pi@raspberry:~ $ ss -lnpe|grep nextdns
u_str LISTEN 0      128                       /var/run/nextdns.sock 19359                                                 * 0                                    <-> ino:19362 dev:0/21 peers:
pi@raspberry:~ $
`

**Comment by rs** [comment]
The output looks mangled, can you reset your term and try again?

**Comment by rs** [comment]
Oh, and please, execute this as root.

**Comment by henrybelk** [comment]
Tried posting with and without code brackets.

u_str LISTEN 0      128                       /var/run/nextdns.sock 19359                                                 * 0                                    users:(("nextdns",pid=567,fd=8)) <-> ino:19362 dev:0/21 peers:
u_dgr UNCONN 0      0                                             * 19358                                                 * 12236                                users:(("nextdns",pid=567,fd=7)) <->
udp   UNCONN 0      0                                             *:53                                                    *:*                                    users:(("nextdns",pid=567,fd=11)) ino:19731 sk:66 v6only:0 <->
tcp   LISTEN 0      128                                           *:53                                                    *:*                                    users:(("nextdns",pid=567,fd=10)) ino:19728 sk:6c v6only:0 <->

`u_str LISTEN 0      128                       /var/run/nextdns.sock 19359                                                 * 0                                    users:(("nextdns",pid=567,fd=8)) <-> ino:19362 dev:0/21 peers:
u_dgr UNCONN 0      0                                             * 19358                                                 * 12236                                users:(("nextdns",pid=567,fd=7)) <->
udp   UNCONN 0      0                                             *:53                                                    *:*                                    users:(("nextdns",pid=567,fd=11)) ino:19731 sk:66 v6only:0 <->
tcp   LISTEN 0      128                                           *:53                                                    *:*                                    users:(("nextdns",pid=567,fd=10)) ino:19728 sk:6c v6only:0 <->
`

**Comment by rs** [comment]
Can you capture a tcpdump of the port UDP/53 on the raspberry and try a query from the other VLAN?

**Comment by henrybelk** [comment]
So I did a TCPdump on the VM Raspberry Pi and couldn't see traffic on 53 coming from the other networks. Thought it might be something to do with the VM network configured in VMware Workstation, so this morning I rebuilt my production Raspberry Pi at home, installed/configured Unifi and NextDNS CLI. Once I got it up and running, I could see the traffic from the other VLANs. NextDNS CLI is working from all my networks now.

One question I have is the device names. Some are getting the name correctly, while most are coming up as 'Device #EJK6B'. Don't seem to be anything with the mac addresses. How do I figure out what they equate to and will it eventually get the correct device name?

Thanks

**Comment by rs** [comment]
Do you run the DHCP server on the same machin? If no, the cli won't be able to use DHCP names. You can fix that by either run DHCP on the same machin, or use `discovery-dns` with the IP of DNS running on the DHCP server (assuming this DNS is serving DHCP names for PTR queries on LAN IPs).
