### ISSUE TITLE
Ubuntu - need to manually activate after each reboot

### ISSUE THREAD

**Issue by mendhak** [nextdns/nextdns#33]
_Ubuntu 18.04, NextDNS 1.3.0_

Hello again, I'm not sure if this is an issue or advice is needed, 

Whenever I reboot,  NextDNS service is running but not used.  I notice in `/etc/resolv.conf` that the network manager has overwritten the file:

> \# Generated by NetworkManager
nameserver 127.0.0.53

I have to manually `sudo nextdns activate` to get NextDNS being used again and then the `/etc/resolv.conf` file shows 127.0.0.1 and my DNS requests go to NextDNS...   

Just like @krioso in #13 I did an uninstall reinstall following the README steps, I did it several times, but I'm always having the same result - I need to manually activate after each reboot. 

What I see when I run `sudo systemctl status nextdns` - I don't see the 'context deadline exceeded' error from #13 that's why I made this a separate issue

> Dec 11 11:49:34 xps13 nextdns[1705]: Endpoint failed: https://dns2.nextdns.io#45.90.30.0,2a07:a8c1::: roundtrip: dial tcp 45.90.30.0:443: connect: network is unreachable
Dec 11 11:49:34 xps13 nextdns[1705]: Switching endpoint: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::
Dec 11 11:49:34 xps13 nextdns[1705]: Endpoint provider failed: https://router.nextdns.io?stack=dual: Get https://216.239.32.21:443?stack=dual: dial tcp 216.239.36.21:443: connect: network is unreachable
Dec 11 11:49:34 xps13 nextdns[1705]: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::
Dec 11 11:49:34 xps13 nextdns[1705]: https://dns2.nextdns.io#45.90.30.0,2a07:a8c1::
Dec 11 11:49:34 xps13 nextdns[1705]: Endpoint failed: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::: roundtrip: dial tcp 45.90.28.0:443: connect: network is unreachable
Dec 11 11:49:34 xps13 nextdns[1705]: Endpoint failed: https://dns2.nextdns.io#45.90.30.0,2a07:a8c1::: roundtrip: dial tcp 45.90.30.0:443: connect: network is unreachable
Dec 11 11:49:39 xps13 nextdns[1705]: Server [2a07:a8c0::]:443 0ms
Dec 11 11:49:39 xps13 nextdns[1705]: Server 45.90.28.0:443 31ms
Dec 11 11:49:39 xps13 nextdns[1705]: Connected 45.90.28.0:443 con=31ms tls=93ms, TLS13)

**Comment by rs** [comment]
What do you get for `nextdns version` and `nextdns config`.

**Comment by mendhak** [comment]
Oh I'm sorry I didn't include the config earlier. 

`nextdns version`

>nextdns version 1.3.0


`nextdns config`

> listen localhost:53
config xxxxxx
log-queries false
report-client-info true
detect-captive-portals false
hardened-privacy false
bogus-priv true
timeout 5s
auto-activate false

I also tried an `apt purge nextdns` and then reinstall it with

    sudo nextdns install -report-client-info -config xxxxxx -auto-activate

(So `auto-activate` becomes `true` in the above config) - but that made no difference either.  After a reboot, the conf file is still being overwritten.  As before, the systemctl status for nextdns looks the same as first post.

**Comment by mendhak** [comment]
I also see 

```
mendhak@xps13:~$ cat /etc/NetworkManager/conf.d/nextdns.conf 
[main]
dns=none
```

So that should prevent anything overwriting `/etc/resolv.conf` is that right?  (I am not knowledgeable in this area)

**Comment by rs** [comment]
Can you send your `journalctl -b` just after a full boot?

**Comment by mendhak** [comment]
OK here you go, thanks for looking at it

[issue33-journalctlb.txt](https://github.com/nextdns/nextdns/files/3952571/issue33-journalctlb.txt)

**Comment by rs** [comment]
Please try 1.3.1

**Comment by mendhak** [comment]
You've done it!  I've rebooted multiple times now and nextdns is sticking in place.  Thanks for your help with both issues. 

So if I'm understanding it right, you had to do a `reload` instead of `try-restart`, and also set the dependency on `network.target` instead of `network-online.target` - I see some more commits after that but I guess that is to help with future troubleshooting and maintenance.  

In the meantime I had been using a workaround - I added `dns=none` under `[main]` in the `/etc/NetworkManager/Networkmanager.conf` file to get nextdns settings to persist.

**Comment by rs** [comment]
The main problem was the restart of NetworkManager instead of reload, which was disturbing the boot process. Other commits are to fix errors you always get at startup because the network is not yet reachable. Your log output should be cleaner now.
