### ISSUE TITLE
NextDns and PlayerUnknown’s Battlegrounds

### ISSUE THREAD

**Issue by ghost** [nextdns/nextdns#330]
If you try to connect to the game through nextdns, an error occurs in the game lobby. If you change dns, for example, to google, then there is no such error, the game is working properly. Error link http://s3.amazonaws.com/doc/2006-03-01/
https://www.youtube.com/watch?v=2yKSG3IMsQA

**Comment by multiformeingegno** [comment]
Do you see any blocked requests in the logs that could be related to the game?

**Comment by rs** [comment]
This is not a cli specific error. Please contact our support or open a ticket on https://github.com/nextdns/metadata if you found a wrongly blocked domain.
