### ISSUE TITLE
Fail position

### ISSUE THREAD

**Issue by onec526** [nextdns/nextdns#334]
![Screenshot_2020-09-28-08-44-01-608_com android chrome](https://user-images.githubusercontent.com/69666182/94380341-c1d2a980-0167-11eb-9972-8061ed728b8a.jpg)

![IMG_20200928_085655](https://user-images.githubusercontent.com/69666182/94380569-a4eaa600-0168-11eb-9ee6-2c2af9c9931e.jpg)

This website is taiwan news. Not porn.

news.ebc.net.tw

**Comment by rs** [comment]
Please report that to https://github.com/nextdns/metadata
