### ISSUE TITLE
Device Name Source Ingest Selection

### ISSUE THREAD

**Issue by deadskwerl** [nextdns/nextdns#335]
Hello, first day using NextDNS and it's really impressive!  

I'm using NextDNS CLI on my Synology NAS and I have everything working great with one exception, I'm getting duplicate devices in my logs and it's due to mDNS.  My LAN is all IPv4, but I have three devices that I cannot disable IPv6 on and I'm positive its because these devices are getting picked up via mDNS.  I see them as mDNS entries when I run "nextdns discovered."

Would it be possible to have the options to enable a device name ingest option?  

Something like this maybe?  

Ingest from DHCP, Host, and mDNS
>nextdns device-name dhcp host mdns 

Ingest from DHCP only
> nextdns device-name dhcp 

Ingest from DHCP and mDNS
> nextdns device-name dhcp mdns

**Comment by multiformeingegno** [comment]
+1 for this. I also see a few duplicate on my device list, and when I run nextdns discovered, it shows that all duplicates were picked up via mDNS

**Comment by rs** [comment]
You can only get duplicates if for some reason the device MAC is changing as they are all keyed on a hash of the MAC. Disabling mDNS would only change the name associated to the MAC, the UI always take the last one seen for a given MAC hash.

**Comment by multiformeingegno** [comment]
Strange, I am seeing this with a Windows Laptop and 2 iPhones. But on all of these devices I have disabled the Private Address / Random MAC Address features

**Comment by rs** [comment]
Are those devices talking to the cli directly, or is there something in between like a dnsmasq?

Do you have IPv6 local IPs on your network?

**Comment by rs** [comment]
Do you run VMs on your windows or have multiple NICs (wifi + eth for instance).

**Comment by multiformeingegno** [comment]
I'm pretty sure I don't have IPv6 local IPs on the network (I'm on OpenWRT, interface WAN6 is disabled and I don't see any leases under DHCPv6 Leases).

The 2 iPhones have the DNS for the wifi set to Automatic (so they pick up nextDNS's DNS from the router). The Windows laptop is a company one, and they use OpenDNS Umbrella, so most of the queries are TXT to debug.opendns.com, but some Windows queries leak anyway so I can see them in the logs. The company laptop has both wifi and ethernet, but it's always connected via wifi

**Comment by rs** [comment]
Can you please check the IP of each duplicates by hovering on the device name in the logs? Is the IP different? Is it always v4?

**Comment by multiformeingegno** [comment]
I only have 1 duplicate device at the moment as I reset the logs yesterday. I’ve checked and it’s IPv4 in both instances, but it has a different local IP (on a different subject). I know why tha5 is for that device. I have 2 wifi networks (Standard and Guest) on 2 separate subnets. I guess it connected briefly to the other wifi network and so it was assigned a new IP.
They might also be the case for the 2 other devices... I’ll check when I get them again in the logs. But is the behaviour expected? To have devices listed twice if they are assigned different IPs (but they have same MAC address)?

**Comment by rs** [comment]
This depend on the device/settings/os version. Since iOS14, by default the OS will use a diff private MAC for each SSID. Do you see a model detected for this device? If not, this is certainly a private MAC.

**Comment by multiformeingegno** [comment]
Yeah, you were right! The dropdown did not have any info on the model, and the Private Address toggle was enabled on that phone (weird! I had disabled it)

**Comment by deadskwerl** [comment]
Dang, I missed the conversation yesterday.  

When I run a "nextdns discovered" I see all of my DHCP names for the devices I have entered reservations for on my DHCP server.  There is no MAC address association that is displayed when I run this command.  Where I do see a MAC/IP association is in the mDNS entry.  

> 
    "dhcp": {
        ],
        "macbook.": [
            "192.168.1.101"
        ],
        "macbook.local.": [
            "192.168.1.101"
        ],
        "pixel-3a-v.": [
            "192.168.1.51"
        ],
        "pixel-3a-v.local.": [
            "192.168.1.51"
        ],
    },
    "mdns": {
        "2301b336-5eb7-48e8-b354-518651863931.local.": [
            "192.168.1.101"
        ],
        "v-macbook-pro.local.": [
            "192.168.1.101"
        ],
        "ffee71dc-c9d0-423e-a8a6-9627088a082d.local.": [
            "192.168.1.101"
        ],
        "android-2.local.": [
            "192.168.1.51",
            "fe80::a88c:295a:5:1234"
        ],
        "android.local.": [
            "192.168.1.51",
            "fe80::a88c:295a:5:1234"
        ],


So, in the output above I have a Pixel phone and a Macbook that are being picked up more than once in mDNS.  I have other duplicates in the GUI and that's why I think it would be nice to have a feature to control the IP/MAC -> Device Name binding.  Since more and more devices are coming out with IPv4/6 enabled by default.

**Comment by rs** [comment]
Having dups in mDNS or DHCP discovery will never create dups in the logs as it is only used for labelling. Devices are indexed by a hash of their MAC. So do have duplicates you need several different MACs for the same device.

You can fix IP->names in /etc/hosts yes.

**Comment by deadskwerl** [comment]
rs, ok - that makes sense now.  I misunderstood and thought that the MAC hashes were being done on NextCLI and then sent to the NextDNS GUI.

**Comment by rs** [comment]
This is the case
