### ISSUE TITLE
Too many entries (duplicates) in the log or...

### ISSUE THREAD

**Issue by crssi** [nextdns/nextdns#336]
...I might not understand what is happening.

Every member of the family have a laptop with YogaDNS set to NextDNS.

I have installed NextDNS DoH on Synology DSM per [instructions](https://github.com/nextdns/nextdns/wiki/Synology-DSM)
Then I have pointed clients to DNS on Synology over DNS settings on DHCP server.
The Router is also pointed to Synology DNS.

Can someone explain this situation?

See the picture:
![NextDNSdup](https://user-images.githubusercontent.com/17024151/94999580-b76e4080-05a9-11eb-8b7f-9d283bb3644d.PNG)

Thank you and cheers

**Comment by crssi** [comment]
Strangely YogaDNS does 2 queries each time
```
[10.03 21:15:06] cdn.cnn.com - process : server=NextDNS DNS, rule=NextDNS
[10.03 21:15:06] cdn.cnn.com - process : server=NextDNS DNS, rule=NextDNS
```
Maybe the YogaDNS has some 'problems'?

**Comment by rs** [comment]
I think it might be due to windows multi homed routing "feature". If you have several active interfaces, Windows will perform the same DNS query for each DNS of each interface. As YogaDNS capture all those queries, you get duplicates.

**Comment by rs** [comment]
Closing as it is not a cli bug.

**Comment by crssi** [comment]
Spot on. That was it.

Thank you ❤️
