### ISSUE TITLE
Apple TvOS14 profile adding not working

### ISSUE THREAD

**Issue by thewolfwood** [nextdns/nextdns#337]
Thanks for adding the profile option for ios14... works like a charm on my iPhones and iPads.
However, adding the profile via AppleTV4K is not working... I get an error "profile corrupted"
I re-created profile... re-published... no luck. When doing it with iphones... the profile is downloaded properly... so I guess the profile generated is not compatible with tvOS... Can you confirm? or maybe update the doc?

**Context**
 - Platform: Apple TvOS 14.0.1

**Comment by goodness-from-me** [comment]
Have you tried generating profile using [apple.nextdns.io](https://apple.nextdns.io)?

**Comment by romaincointepas** [comment]
@thewolfwood Can you try using the automatically generated `tinyurl.com` link that appears in the Install on tvOS section after clicking the Download button?

**Comment by thewolfwood** [comment]
Great... it worked using the tinyurl generated in the tvOS section... thanks Romain.
Maybe update the instructions to include those steps... it is not clear that there is a generated tinyurl after clicking download.

Thanks for the great addition to the already awesome service!

**Comment by haydenk** [comment]
One thing I noticed is that Apple TV says the status is inactive which made me think it wasn't working but if you add YouTube.com to your disallow list and try to go to YouTube on Apple TV, it will not work, so clearly it's working it just shows as inactive. It's not really a VPN, it just overrides the DNS values, iirc.

Use the profile created at apple.netxtdns.io and use the Apple Configurator to install it.
