### ISSUE TITLE
NextDNS CLI - External IPs

### ISSUE THREAD

**Issue by henrybelk** [nextdns/nextdns#338]
&lt;Describe the bug>
I have NextDNS CLI up and running on a Raspberry Pi. Working great and sending via DoH. Wanting to lock down my firewall at home and allow 53/443 to NextDNS ASN, but block any other DNS (53) request externally. Google Home uses hard-coded DNS. I've read that if they can't reach them, they will use DHCP supplied DNS servers. I'd like to try this instead of having to redirect queries at the FW.

I've created a policy to allow 53/443 to NextDNS ranges, but I don't see any traffic to those ranges. I see some traffic over 443 to a network owned by Anexia in Dallas (closest to me from ping.nextdns.io). Should these queries be going to NextDNS networks or do you have a range I can specify to allow DNS and DoH to that NextDNS uses?

AS34939:

- 45.90.28.0/24

- 45.90.29.0/24

- 45.90.30.0/24

**Context**
 - Version [e.g. 1.5.2]: 1.8.5
 - Platform [e.g. macOS, ASUS-Merlin]: Raspbian

**Comment by rs** [comment]
The CLI is using a router API to perform geo steering instead of anycast with anycast as fallback. This mean IPs are from different providers / ASNs etc. so unpredictable.

WIth the CLI, only 443 will be used. Blocking this port would block most web sites so it is not recommended anyway.
