### ISSUE TITLE
Unable to install on UDM (device or resource busy)

### ISSUE THREAD

**Issue by Zzgwalk** [nextdns/nextdns#339]
Somehow to install on a UDM
1.8.1 rc3
Controller: 6.0.24

Error message Error: setup resolv.conf: rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy

No joy after restarting as well

**Comment by Allram** [comment]
I used the command: 'nextdns stop' and then rebooted the UDMP, then it worked great for me :)

**Comment by Zzgwalk** [comment]
Just tried it but nope, also not working. The resolv.conf in /etc is just a symlink from /tmp/resolv.conf I assume that's why it is failing to replace the file.

**Comment by Ludacon** [comment]
I am also getting this error. I did very briefly after installing get the all good on the nextdns config website. It is now showing that im using cloudflare no matter if i remove nextdns or not. 

after seeing  Zzgwalk's comment about 

`The resolv.conf in /etc is just a symlink from /tmp/resolv.conf I assume that's why it is failing to replace the file.`

I copied the actual resolve.conf from /tmp to /etc and attempted to rerun, still no joy with various reboots.

**Comment by rs** [comment]
Please disable `auto-activate`, it is not necessary on a router and does not work on UDMP.

**Comment by Ludacon** [comment]
Hurm, i dont recall setting it, but i see its active, im still searching for the config file in the udm file structure, or a working command with nextdns config set to turn it off.

**Comment by rs** [comment]
`nextdns config set -auto-activate=false` then `nextdns restart`. The config file is located in `/data/nextdns.conf`.

**Comment by Ludacon** [comment]
thanks! Auto-Activate is now false, the dashboard still shows cloudflare but i see my network device queries in the logs. Actually looking through the logs it looks like its been working for a while now. 


I suspect the OP and myself were using the nextdns Activate command thinking that was necessary to get it working.

**Comment by rs** [comment]
The dashboard should’t show cloudflare tho.

**Comment by Ludacon** [comment]
After further diagnosing, it looks like its only in my main firefox install, so i suspect something with the browser there? test.nextdns.io shows everything properly configured. As do a handful of random devices i test (including 2 cell phones). I see regular dns queries going out so it IS working. But yea the cloudflare thing is weird.

**Comment by Ludacon** [comment]
![image](https://user-images.githubusercontent.com/1294187/98035689-e82ed900-1de6-11eb-9d18-7aa1cbf171c4.png)

**Comment by rs** [comment]
Did you disable DoH on firefox?

**Comment by Ludacon** [comment]
NOPE. TOTALLY forgot that was a thing. Many Many thanks @rs

**Comment by josdegroot** [comment]
I have upgraded today NextDNS on my UDP Pro to 1.9.6 and the service stopped working. Already tried al the things above but i'm not be able to activate the service again. 

Get the message: Activate: setup resolv.conf: rename /etc/resolv.conf.nextdns-tmp /etc/resolv.conf: dev

Uninstall --> install --> reboot etc etc... nothing work...

Is there a way to downgrade to a previous version?

`# nextdns log
Jan 12 16:04:27 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
Jan 12 16:04:27 ubnt nextdns[7550]: Starting NextDNS 1.9.6/linux on localhost:5553
Jan 12 16:04:27 ubnt nextdns[7550]: Starting mDNS discovery
Jan 12 16:04:27 ubnt nextdns[7550]: Listening on UDP/127.0.0.1:5553
Jan 12 16:04:27 ubnt nextdns[7550]: Listening on TCP/127.0.0.1:5553
Jan 12 16:04:27 ubnt ssh[7551]: Welcome to UbiOS
Jan 12 16:04:27 ubnt ssh[7551]: By logging in, accessing, or using the Ubiquiti product, you
Jan 12 16:04:27 ubnt ssh[7551]: acknowledge that you have read and understood the Ubiquiti
Jan 12 16:04:27 ubnt ssh[7551]: License Agreement and agree to be bound by its terms.
Jan 12 16:04:27 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
Jan 12 16:04:32 ubnt nextdns[7550]: Setting up router
Jan 12 16:04:33 ubnt nextdns[7550]: Activating
Jan 12 16:04:33 ubnt nextdns[7550]: Activate: setup resolv.conf: rename /etc/resolv.conf.nextdns-tmp /etc/resolv.conf: device or resource busy
Jan 12 16:04:46 ubnt systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Jan 12 16:04:46 ubnt nextdns[7550]: Received signal: terminated
Jan 12 16:04:46 ubnt nextdns[7550]: Stopping NextDNS 1.9.6/linux
Jan 12 16:04:46 ubnt nextdns[7550]: Restore router settings
Jan 12 16:04:46 ubnt nextdns[7550]: Deactivating
Jan 12 16:04:46 ubnt nextdns[7550]: Deactivate: restore resolv.conf: rename /etc/resolv.conf.nextdns-bak /etc/resolv.conf: device or resource busy
Jan 12 16:04:46 ubnt nextdns[7550]: NextDNS 1.9.6/linux stopped
`

**Comment by josdegroot** [comment]
Stil not working.... have updated to 1.10.1... but still get the message: Activate: setup resolv.conf: rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy

NextDNS is not working anymore...

**Comment by Morpilot** [comment]
I do have the same issue as well on UDM Pro running 1.9.2.3432

**Comment by rickross** [comment]
I have the same issue on UDM Pro running 1.10.0-8

**Comment by ArrEssJay** [comment]
I ran into this after mistakenly removing the local ssh public (`ssh-rsa <key data> root@ubntkey`) from `/root/.ssh/authorized_keys`

`ubnt ssh[23203]: Permission denied, please try again.` in the log was the hint

Replacing the removed key resolved this. In that case this isn't really a bug on the nextdns side as that key is needed for internal unifi processes. It _would_ be helpful if the purpose of that key was documented by Ubiquiti.

@rs Perhaps check a key with `root@ubntkey` exists in the `authorized_keys` file?

**Comment by dcramer** [comment]
Is the auto-activate issue still valid? The error still persists but I'm not sure its breaking NextDNS.

Maybe worth a note on https://github.com/nextdns/nextdns/wiki/UnifiOS ?
