### ISSUE TITLE
nameserver on resolve.conf keep 127.0.0.1 when listen on 127.0.3.1

### ISSUE THREAD

**Issue by nyancodeid** [nextdns/nextdns#34]
I try to run nextdns listen on 127.0.3.1:53 because 127.0.0.1:53 always been used. and the are dnscrypt-proxy run on 127.0.2.1 so i just make it 127.0.3.1 on nextdns and it's run. But when nextdns started always changes resolve.conf nameserver into 127.0.0.1. How to make it changes IP automatically same as configure file (127.0.3.1) when nextdns started or after PC being restarted? 

is there are any config parameter to make resolv.conf IP same config as listen parameter?

/etc/nextdns.conf
```
listen 127.0.3.1:53
config xxxxxx
log-queries false
report-client-info true
detect-captive-portals false
hardened-privacy false
bogus-priv true
timeout 5s
auto-activate true
```

/etc/resolve.conf
```
# This file is managed by nextdns.
#
# Run "nextdns deactivate" to restore previous configuration.

nameserver 127.0.0.1
```

NextDNS version 1.3.1
Linux Mint 19.1 Cinnamon 

Thanks.

**Comment by rs** [comment]
activate needs to be smarter and identify when the listen param would not include 127.0.0.1. Should be easy enough.

By curiosity, why would run both nextdns and dnscrypt-proxy on the same host?

**Comment by nyancodeid** [comment]
Exactly, that's what we need for now.

I want to separate the default DNS, dnscrypt-proxy and nextdns. They have their respective functions in certain cases.

**Comment by nyancodeid** [comment]
@rs Thanks for your hard work. Appreciate :100:
