### ISSUE TITLE
Limit bind to specific interfaces or IPs 

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#340]
This is an important feature on routers, I do not want nextdns to listen on the WAN interface or some VPN interfaces. For example, `dnsmasq` has a configuration to do so:
```
interface=switch0.10
interface=switch0.20
interface=switch0.30
```
And that's all it will listen on.

Yes, you can use firewall rules to lock it down if it listens on all interfaces, but that is added complexity.

Also confusing that on a router (ER-X) the default conf file has `listen localhost:53` but it listens on all interfaces. I understand that the listen option is not used when `setup-router true` but still confusing until paying close attention to `nextdns run --help`

**Comment by rs** [comment]
This is not exactly the requested feature but it let you specify several IPs to listen on.
