### ISSUE TITLE
Better interop with dnsmasq on a router with multiple VLANs and local domains

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#341]
On an ER-X router, I use `dnsmasq` for both DHCP and DNS. I also use static DHCP for most hosts on the LAN to set custom names. The LAN is actually 3 VLANs, each VLAN has its own local domain name (e.g. .domain1, .guest, .iot) and the same `dnsmasq` instance serves clients on all 3 VLANs returning correct (static DHCP) IP addresses and the correct domain for each VLAN.
This all works fine with `dnsmasq`, clients on any VLAN can resolve other hosts on the VLANs either by `shortname` or `shortname.domain`.

I was hoping to use `nextdns` as replacement for `dnsmasq` but still keep `dnsmasq` for DHCP so that I can get client reporting in the nextdns logs.

The default install disables the DNS part in dnsmasq by setting `port=0`. When that happens, the host names in the DHCP leases file `/run/dnsmasq-dhcp.leases` no longer have the custom static DHCP names that I want, but instead they have whatever the client reports or whatever dnsmasq may synthesize from MAC addresses, etc. This seems to be a limitation of dnsmasq if the DNS part doesn't run. Now `nextdns` cannot resolve hosts on my LAN by their custom names from static DHCP.

I figured that I'd just let dnsmasq run on some other port, say [5342](https://github.com/nextdns/nextdns/blob/master/router/edgeos/setup.go#L25) Now the short custom names show up in the leases file and nextdns can resolve them, but the FQDN names `shortname.domain` cannot be resolved because nextdns doesn't know about the VLAN domains.

I'm not sure what the correct way to set this up is, maybe dnsmasq needs to always run and use the nextdns setting `forwarder` for each VLAN domain. But it would be nice if the `setup-router` feature just worked out of the box without changing previous behavior that dnsmasq users are relying on.

**Comment by rs** [comment]
You can set the discovery-dns parameter to 127.0.0.1:5342, nextdns will ask dnsmasq for any requests resulting in a NXDOMAIN and return the result if dnsmasq returns a positive answer.

**Comment by timkgh** [comment]
I think I found a working config:
- in nextdns.conf set `setup-router false`, `discovery-dns 127.0.0.1:5342`, `listen 0.0.0.0:53` (see note below)
- move dnsmasq to listen on 127.0.0.1:5342
- do not use any upstream servers in dnsmasq

Be aware that `listen 0.0.0.0:53` will listen on ALL interfaces on the router, including WAN, VPN, etc. Make sure you have firewall rules in place for the interfaces where you do not want DNS. See issue #340

**Comment by Fail-Safe** [comment]
Indeed, the configuration you described does work well in this use-case. I run the same setup since @rs was kind enough to implement alternate port support for `discovery-dns` per https://github.com/nextdns/nextdns/issues/333.

**Comment by timkgh** [comment]
May I suggest a way to prioritize discovery and disable some of the discovery methods?
You could add a config options that is a priority list for discovery methods, e.g.

`discovery dns:127.0.0.1:5053,dns:192.168.5.1:53,hosts,dhcp,mdns`

Then the logic would go in order through the list until it can resolve a name/IP or not. PTR must also work.

A user can then implement dns discovery only against a local dnsmasq for example and disable the rest of the methods which in my use case are harmful:

`discovery dns:127.0.0.1:5053`

**Comment by timkgh** [comment]
@rs feasible to implement the suggestion above?

**Comment by rs** [comment]
It is yes. It’s not a small change tho.

**Comment by rs** [comment]
Also, I can’t remove older options otherwise it would break people who are using them.

**Comment by timkgh** [comment]
> Also, I can’t remove older options otherwise it would break people who are using them.

When a new version is installed and starts up, can it not update the config file to the new option?

**Comment by rs** [comment]
Yes, it means in addition to this feature, we need to implement a config migration system, and keep the support those old config forever.
