### ISSUE TITLE
Better Adblocking for South Korean Users (Blocklist add request)

### ISSUE THREAD

**Issue by parkleo121212** [nextdns/nextdns#342]
At this moment, NextDNS is only supporting "Youslist" as South Korea ad blocklist.
But, this list cannot cover all ad in South Korea, so i want to use list below.

https://list-kr.github.io/
https://github.com/List-KR/List-KR
https://github.com/List-KR/List-KR/blob/master/filter.txt

List-KR is ad blocklist for Adguard and, base on Youslist and updated frequently.(last update was on yesterday)
Thank you! 😉😊

**Comment by rs** [comment]
Please use https://github.com/nextdns/metadata for blocklist requests.
