### ISSUE TITLE
Issue #315 Redux: System logs flooded with failed PTR lookups for local LAN IPs

### ISSUE THREAD

**Issue by hazarjast** [nextdns/nextdns#344]
Same issue as #315 : system logs are flooded with failed PTR lookups for local LAN IPs. Aforementioned issue was closed stating these entries "will go away"; unfortunately they have not. At least in the FreeBSD implementation for pfSesnse this is problematic as the default 50 entries of the system log viewable to the user in the web GUI are flooded out with these superfluous entries. If option could be give under "nextdns config" to mute these that would be much preferred. Appreciate your consideration and review of this issue or replying/reopening the aforementioned, closed one.

Time | Process | PID | Message
-- | -- | -- | --
Oct 12 07:56:55 | nextdns | 7318 | Query 192.168.1.131 UDP PTR lb._dns-sd._udp.254.254.254.10.in-addr.arpa. (qry=61/res=12) 0ms : not found
Oct 12 07:56:55 | nextdns | 7318 | Query 192.168.1.131 UDP PTR lb._dns-sd._udp.0.1.168.192.in-addr.arpa. (qry=58/res=12) 0ms : not found
Oct 12 08:04:33 | nextdns | 7318 | Query 192.168.1.91 UDP PTR 0.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
  |   |   | ...(many repeating entries of the same)...
Oct 12 08:56:09 | nextdns | 7318 | Query 192.168.1.92 UDP PTR 0.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
Oct 12 09:00:00 | nextdns | 7318 | Received signal: terminated
Oct 12 09:00:00 | nextdns | 7318 | Stopping NextDNS 1.8.3/freebsd
Oct 12 09:00:00 | nextdns | 7318 | Restore router settings
Oct 12 09:00:00 | nextdns | 7318 | Deactivating
Oct 12 09:00:00 | nextdns | 85761 | Starting NextDNS 1.8.3/freebsd on :53
Oct 12 09:00:00 | nextdns | 85761 | Starting mDNS discovery
Oct 12 09:00:00 | nextdns | 85761 | Listening on UDP/:53
Oct 12 09:00:00 | nextdns | 85761 | Listening on TCP/:53
Oct 12 09:00:00 | nextdns | 7318 | NextDNS 1.8.3/freebsd stopped
Oct 12 09:00:00 | nextdns | 85761 | Connected 45.90.28.0:443 (con=51ms tls=160ms, TLS13)
Oct 12 09:00:01 | nextdns | 85761 | Connected 45.76.16.236:443 (con=49ms tls=54ms, TLS13)
Oct 12 09:00:01 | nextdns | 85761 | Switching endpoint: https://vultr-chi-1.edge.nextdns.io#45.76.16.236,2001:19f0:5c01:1ebc:5400:2ff:fece:28ed
Oct 12 09:00:05 | nextdns | 85761 | Setting up router
Oct 12 09:00:05 | nextdns | 85761 | Activating
Oct 12 09:04:39 | nextdns | 85761 | Query 192.168.1.91 UDP PTR 0.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
Oct 12 09:04:44 | nextdns | 85761 | Query 192.168.1.91 UDP PTR 0.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
Oct 12 09:06:06 | nextdns | 85761 | Query 192.168.1.92 UDP PTR 0.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
Oct 12 09:06:11 | nextdns | 85761 | Query 192.168.1.92 UDP PTR 0.1.168.192.in-addr.arpa. (qry=42/res=12) 0ms : not found
  |   |   | ...(many repeating entries of the same)...

**Comment by rs** [comment]
This is already fixed in latest version. Please upgrade.

**Comment by hazarjast** [comment]
Excellent. Thank you! For others' reference, this is resolved in version 1.8.6.
