### ISSUE TITLE
Intermittent Keyboard Input Lag

### ISSUE THREAD

**Issue by rsyring** [nextdns/nextdns#352]
Over the past 3-6 months or so, I have noticed that input from my keyboard has started to lag.  As I'm typing, the letters will stop showing up for a few seconds, sometimes it seems like as much as 5-10 seconds, and then everything I typed will quickly be output.  So, some kind of IO lag in typing.  

This becomes especially noticeable and repeatable when turning off my WIFI connection.

The problem goes away as soon I deactivate nextdns.  When my computer restarts, nextdns comes back, and eventually I notice the lag again and have to deactivate nextdns again.  Obviously, I could uninstall nextdns, but I keep hoping it will get fixed.  

**Context**

 - Version: 1.8.6
 - Platform: Ubuntu 20.04 running Cinnamon DE (my son has a similar problem using the Gnome DE)

**Comment by Fail-Safe** [comment]
Is any domain being blocked in your NextDNS logs as you are typing? Are there particular apps where this behavior appears?

**Comment by rsyring** [comment]
> Is any domain being blocked in your NextDNS logs as you are typing?

I can double check this the next time it happens.  However, it's most prominent when wifi is turned off.  So I wouldn't expect there to be any logs during that time period.

> Are there particular apps where this behavior appears?

It's most noticeable in VS Code and my terminal (Terminator/Bash).  However, I've also tested it in Mousepad with the same results.

Thanks for the reply.  Let me know if/what I can do to help troubleshoot.
