### ISSUE TITLE
discovery broken in 1.8.8

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#353]
Upgraded to 1.8.8, `discovery-dns` stopped working. Also `nextdns discovered` returns `null` so all discovery seems broken.

**Context**
 - Version [e.g. 1.5.2]: 1.8.8
 - Platform [e.g. macOS, ASUS-Merlin]: EdgeOS

**Comment by timkgh** [comment]
A bit more info on this:
* If nextdns is set to listen on specific addresses, e.g. `127.0.0.1:53` and I run `nextdns discovered` it returns `null`
* If it is configured to listen on `0.0.0.0:53` then `nextdns discovered` returns a blob of json with entries for dns, hosts, mdns. I also noticed that in this case it listens on mDNS port 5353 too.

Could you please clarify whether this is expected or a bug?

**Comment by rs** [comment]
This is expected and not new with 1.8.8. When listening on 127.0.0.1:53, it is assuming you are not running in a mode that is to serve other client (router mode) but just to serve local client DNS requests. In such case, there is no need to start discovery.

**Comment by timkgh** [comment]
But with the new feature in 1.8.8 I can have it listen on multiple interfaces, e.g.
```
listen 127.0.0.1:53
listen 192.168.1.1:53
listen 192.168.5.1:53
...
```
Because I want it to act as the DNS server on certain VLANs and still be able to resolve local names by doing dns discovery against dnsmasq that serves DHCP and knows about the local addresses. In this case discovery does not work, it returns `null`

**Comment by rs** [comment]
Ok, we should probably improve this detection. In the meantime, you can move the first listen to a later position, it should fix the issue.

**Comment by rs** [comment]
Forget my last comment, moving position won't work, you need to change the port. A fix should come soon.
