### ISSUE TITLE
Unifi-OS: Upgrade nextdns also upgrades Unifi apps

### ISSUE THREAD

**Issue by vbap** [nextdns/nextdns#354]
When upgrading nextdns (1.8.6-> 1.8.8) in Unifi-OS (UDM Pro) using the "Ugrade" option from the nextdns installer, I observed that several Unifi packages seemed to also be updated:
unifi-base-ucore
unifi-talk
unifi-access

```
Preparing to unpack .../1-libmariadbclient18_10.1.47-0+deb9u1_arm64.deb ...
Unpacking libmariadbclient18:arm64 (10.1.47-0+deb9u1) over (10.1.45-0+deb9u1) ...
Preparing to unpack .../2-openjdk-8-jre-headless_8u272-b10-0+deb9u1_arm64.deb ...
Unpacking openjdk-8-jre-headless:arm64 (8u272-b10-0+deb9u1) over (8u265-b01-0+deb9u1) ...
Preparing to unpack .../3-ulp-go_1.2.19+1583_arm64.deb ...
Unpacking ulp-go (1.2.19+1583) over (1.2.18+1543) ...
+ LX_USER=ulp-go
+ LX_GROUP=ulp-go
+ databases=(ulp-go ulp-go-syslog)
+ databaseUser=ulp-go
+ [[ upgrade = \p\u\r\g\e ]]
Preparing to unpack .../4-unifi-access_1.2.24+1710_arm64.deb ...
Unpacking unifi-access (1.2.24+1710) over (1.2.23+1698) ...
+ LX_USER=unifi-access
+ LX_GROUP=unifi-access
+ databases=(unifi-access)
+ databaseUser=unifi-access
+ [[ upgrade = \p\u\r\g\e ]]
Preparing to unpack .../5-unifi-talk_1.6.3_arm64.deb ...
Unpacking unifi-talk (1.6.3) over (1.6.0) ...
Preparing to unpack .../6-unifi-base-ucore_1.6.1_arm64.deb ...
Unpacking unifi-base-ucore (1.6.1) over (1.6.0) ...
Preparing to unpack .../7-nextdns_1.8.8_arm64.deb ...
Unpacking nextdns (1.8.8) over (1.8.6) ...
#-> ubnt-dpkg-cache unpack

```
I lost connectivity to the controller after the update, and had to restart it (podman restart unifi-os) to get it running again.
At this stage no damage appears to have been done - no firmware related to the apps I use (just Network & Protect controllers) appears to have taken place. NextDNS appears to be working OK.

**Context**
 - Version [e.g. 1.5.2]: 1.8.8
 - Platform [e.g. macOS, ASUS-Merlin]: Unifi-OS (UDM Pro on firmware 1.8.0)

**Comment by owine** [comment]
I have seen the same. Looks like there was an attempted fix previously https://github.com/nextdns/nextdns/commit/d975eb3418fb7c56851df0f7358b6a655bcb5c19 but still an issue.

**Comment by vbap** [comment]
I see it does a generic apt-get update, so all updated packages are downloaded (and unpacked) but the install is just done for nextdns. I'm no linux boffin so maybe this is OK but certainly after upgrading nextdns my UDMP lost some connectivity and needed a package restart to come good (and previously disable app like Unifi Talk was re-enabled).

**Comment by rs** [comment]
Do you know a way to just upgrade nextdns package without touching other packages?

**Comment by johannrichard** [comment]
A possible alternative if the package is already installed would be to use

`apt-get install --only-upgrade nextdns`

[apt-get](https://manpages.debian.org/buster/apt/apt-get.8.en.html):

```
--only-upgrade

Do not install new packages; when used in conjunction with install, only-upgrade will install upgrades for already installed packages only and ignore requests to install new packages. 

```

**Comment by maksd** [comment]
You could also only update the nextdns source:

`apt-get update -o Dir::Etc::sourcelist="sources.list.d/nextdns.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"`

Details: 
**-o Dir::Etc::sourcelist="sources.list.d/nextdns.list"** : override the default "/etc/apt/sources.list"
**-o Dir::Etc::sourceparts="-"** : Make sure to not update the other custom package locations
**-o APT::Get::List-Cleanup="0"** : Make sure to not screw up the state information "/var/lib/apt/lists/".

[apt-get(8)](https://manpages.debian.org/stretch/apt/apt-get.8.en.html)

**Comment by owine** [comment]
Appears to work as expected - this was upgrading to 1.9.0

```
The following packages will be upgraded:
  nextdns
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

And then running `nextdns upgrade` on 1.9.0 yields (before 1.9.1 has propogated)
```
nextdns is already the newest version (1.9.0).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
```

**Comment by rs** [comment]
Thx for confirming
