### ISSUE TITLE
Cannot listen on port other than 53 in FreeBSD iocage jail

### ISSUE THREAD

**Issue by k-obrien** [nextdns/nextdns#356]
Steps to reproduce:

1. Create brand new jail, configure to use DHCP or static IP; makes no difference
2. Confirm DNS within jail
`drill google.com @localhost`
3. Install nextdns cli
`sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`
4. Set the following configuration options (all others as default):
`-listen localhost:5553` # Have also tried 60, 5555, 5353
`-setup-router false` # Config defaults to generic; only tries to set resolver
`-auto-activate false` # Can't set resolver for ports outside of 53
5. Confirm original DNS still working:
`drill google.com`
6. Attempt to confirm nextdns working:
`drill google.com @localhost -p 5553`
Delay followed by `Error: error sending query: Could not send or receive, because of network error`
7. Reset (replace, not add) listen to localhost:53
8. Confirm nextdns working (spoiler: it works):
`drill google.com @localhost`

**Context**
 - Version [e.g. 1.5.2]: 1.8.8
 - Platform [e.g. macOS, ASUS-Merlin]: FreeBSD 11.3-RELEASE-p14 in an iocage jail

**Comment by rs** [comment]
Do you have setup-router set to true?

**Comment by k-obrien** [comment]
Originally, yes. Same issue.

**Comment by rs** [comment]
Set it to false, when true, it ignores the listen parameter.

**Comment by k-obrien** [comment]
> Set it to false, when true, it ignores the listen parameter.

Please read the ticket carefully; I've explained that I disabled it.

**Comment by rs** [comment]
How do you start the daemon in the iocage?

**Comment by k-obrien** [comment]
It gets installed by the install script and then I call `nextdns start`.

**Comment by rs** [comment]
Can you please show the logs (nextdns log).

**Comment by k-obrien** [comment]
### listen localhost:53
`Nov  1 21:40:39 dns nextdns[69102]: Starting NextDNS 1.8.8/freebsd on localhost:53`
`Nov  1 21:40:39 dns nextdns[69102]: Listening on TCP/127.0.0.1:53`
`Nov  1 21:40:39 dns nextdns[69102]: Listening on UDP/127.0.0.1:53`
`Nov  1 21:40:39 dns nextdns[69102]: Listening on TCP/[::1]:53`
`Nov  1 21:40:39 dns nextdns[69102]: Listening on UDP/[::1]:53`
`Nov  1 21:40:52 dns nextdns[69102]: Received signal: bad system call (ignored)`
`Nov  1 21:40:53 dns nextdns[69102]: Connected 45.121.209.148:443 (con=32ms tls=50ms, TLS13)`
`Nov  1 21:40:53 dns nextdns[69102]: Switching endpoint: https://gsl-mel-1.edge.nextdns.io#45.121.209.148,2401:3bc0:c:101:101:101:4d4:cb4b`
`Nov  1 21:40:56 dns nextdns[69102]: Connected 45.90.28.0:443 (con=3043ms tls=42ms, TLS13)`
### listen localhost:5553
`Nov  1 22:57:03 playground nextdns[71341]: Starting NextDNS 1.8.8/freebsd on localhost:5553`
`Nov  1 22:57:03 playground nextdns[71341]: Listening on TCP/127.0.0.1:5553`
`Nov  1 22:57:03 playground nextdns[71341]: Listening on TCP/[::1]:5553`
`Nov  1 22:57:03 playground nextdns[71341]: Listening on UDP/[::1]:5553`
`Nov  1 22:57:03 playground nextdns[71341]: Listening on UDP/127.0.0.1:5553`
### config
`control /var/run/nextdns.sock`
`log-queries false`
`discovery-dns`
`auto-activate false`
`listen localhost:53` or `listen localhost:5553`
`detect-captive-portals false`
`setup-router false`
`use-hosts false`
`config ******`
`cache-max-age 0s`
`max-ttl 5s`
`report-client-info false`
`hardened-privacy false`
`bogus-priv true`
`cache-size 0`
`timeout 5s`

**Comment by rs** [comment]
I think it’s not finding your config file in the jail.

**Comment by k-obrien** [comment]
How do you figure? The first lot of log output shows the service running on port 53, and the second shows it running on 5553, exactly matching the configuration posted at the bottom.

You'llnotice I listed the two ports on the same line of the config because it was the only thing that changed between the two runs.

**Comment by k-obrien** [comment]
The pertinent point here seems to be that the process outputs the following ONLY when listening on port 53:
```
Nov 1 21:40:52 dns nextdns[69102]: Received signal: bad system call (ignored)
Nov 1 21:40:53 dns nextdns[69102]: Connected 45.121.209.148:443 (con=32ms tls=50ms, TLS13)
Nov 1 21:40:53 dns nextdns[69102]: Switching endpoint: https://gsl-mel-1.edge.nextdns.io#45.121.209.148,2401:3bc0:c:101:101:101:4d4:cb4b
Nov 1 21:40:56 dns nextdns[69102]: Connected 45.90.28.0:443 (con=3043ms tls=42ms, TLS13)
```
This would suggest to me that the process is stalling somewhere. I'm attempting to trace this through but I've never written in golang before so any assistance would be greatly appreciated.

**Comment by k-obrien** [comment]
Confirmed working on v1.34.2.
