### ISSUE TITLE
Add --follow/-f flag to log command

### ISSUE THREAD

**Issue by loshz** [nextdns/nextdns#357]
It can be very useful to tail a log file, and while I can achieve the desired functionality using tools like `journalctl` independently, it would be relatively straightforward to add an extra flag to do this.

I think the steps would be as follows:
1. Update `ReadLog` to accept a "follow" (or similar) option and handle the printing itself: https://github.com/nextdns/nextdns/blob/master/host/log_linux.go#L14
2. Instead of calling `Output()` directly on the cmd, we would need to `Start()` the command manually and read/scan the cmd's `stdout`: https://github.com/nextdns/nextdns/blob/master/host/log_linux.go#L21
3. Pass additional flags to `journalctl` in order to stream output to `stdout`:
    - `-f` Follow the journal
    - `--no-pager` Do not pipe output into a pager
    - `--no-tail` Show all lines, even in follow mode

Here is a quick Go program to simulate the desired effect using `journalctl`:
```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"os/exec"
)

func main() {
	// create command
	cmd := exec.Command("journalctl", "-f", "--no-pager", "--no-tail", "-u", "nextdns")

	// create pipe to read from stdout
	stdout, _ := cmd.StdoutPipe()

	// start the Command
	if err := cmd.Start(); err != nil {
		log.Fatal(err)
	}

	// read from stdout
	reader := bufio.NewReader(stdout)
	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				break
			}
			log.Fatal(err)
		}

		fmt.Printf("%s", line)
	}

	// wait for command to finish or be cancelled
	cmd.Wait()
}
```

Tested using:
```
Linux 5.9.2-arch1-1
go1.15.3 linux/amd64
systemd 246 (246.6-1-arch)
```

If you think this would be a useful feature I'd be happy to PR it and add some further tests :)

**Comment by PeterDaveHello** [comment]
That's something very useful, would like to see the pull request be sent and accepted 🎉
