### ISSUE TITLE
NixOS Installation Instructions

### ISSUE THREAD

**Issue by pnelson** [nextdns/nextdns#360]
I packaged NextDNS for NixOS and with the release of NixOS 20.09 it has finally landed in stable channels. I thought maybe it would be nice to add to the wiki.

The NextDNS installer will not work due to the declarative nature of the paths. Upgrades are handled by the package manager.

Within `/etc/nixos/configuration.nix`:

1. Add `nextdns` to `environment.systemPackages`.
2. Configure the systemd service.
```
services.nextdns = {
  enable = true;
  arguments = [ "-config" "10.0.3.0/24=abcdef" "-cache-size" "10MB" ];
};
```
3. Run `nixos-rebuild switch` to install the package and enable the service.

**Comment by rs** [comment]
Added, thanks
