### ISSUE TITLE
Not selecting the nearest/fastest DNS-servers

### ISSUE THREAD

**Issue by iJorgen** [nextdns/nextdns#363]
Sweden is a long country and I'm much closer geographically to Copenhagen in Denmark.

These servers are picked by the NextDNS CLI:
- Primary server: Stockholm, distance 400 miles, latency 15-20 ms.
- Secondary server: Copenhagen, distance 20 miles, latency 2-3 ms.

■ anexia-cph        3 ms  (secondary)
  anexia-osl       10 ms
■ zepto-sto        18 ms  (primary)
  zepto-ams        19 ms
  zepto-fra        25 ms

Platform ASUS-Merlin, Version 1.8.8

**Comment by timkgh** [comment]
I think there should be an option to allow connecting to specific servers, or at least used as a strong hint.
https://github.com/nextdns/nextdns/issues/373

**Comment by rs** [comment]
The cli does not use anycast by default but the output of https://router.nextdns.io which is based on geo IP. What you see on http://ping.nextdns.io is not what cli is likely using.

If what the router is selecting is not good, please report it via http://nextdns.io/diag.

I’m closing as it is not planned to add the ability to select the pop you go to.

**Comment by timkgh** [comment]
Thanks for clarifying. I'm seeing the same thing, ping.nextdns.io gives a better choice (9ms latency) than router.nextdns.io (15ms latency). Consistent via ping from the cmd line also. Still very low absolute numbers, but the one nextdns cli picks is 66% "slower".

**Comment by iJorgen** [comment]
I used the diagnostics tool and sent a report about a week ago. Checking each day now with ping.nextdns.io to see if the routing is fixed, but still no luck...

**Comment by timkgh** [comment]
I cannot send a report using the tool at the end it tries to POST to localhost?

`Post unsuccessful: Post "http://localhost:8081/diagnostic": dial tcp 127.0.0.1:8081: connect: connection refused`

**Comment by iJorgen** [comment]
> 
> 
> I cannot send a report using the tool at the end it tries to POST to localhost?
> 
> `Post unsuccessful: Post "http://localhost:8081/diagnostic": dial tcp 127.0.0.1:8081: connect: connection refused`

I used it directly from the router using SSH and got a confirmation it was sent.

**Comment by rs** [comment]
@timkgh please try again.

**Comment by timkgh** [comment]
OK, it worked. Thanks for the fix.

**Comment by mbnn** [comment]
Noticed same thing, i live in the netherlands and one of two selections goes to france, while both AMS-IX nextdns servers are better and closer, ill send a diag report.

**Comment by Allram** [comment]
Sent a diagnostic now myself, run Nextdns on Ubiquiti UDMP.

I live near Oslo in Norway, and Zepto-osl is approx 2ms away and is choosen to be secondary, while zepto-sto (9ms) is the primary server.

**Comment by timkgh** [comment]
It's definitely making non-optimal choices. I sent a report, hopefully the routing choices are improved.

**Comment by iJorgen** [comment]
Are the reports we send handled manually by the NextDNS team or Ai to optimize the server selection? I submitted one a few weeks ago, but still not an optimal route for me. Any rough guess how long it will take from submitting to fixing? :-)

**Comment by rs** [comment]
Reports are handled by priorities and all anycast issues can't be easily fixed. Note that this repository is about the CLI client, if you are using the CLI client, you are not subject to anycast routing issues as the CLI is using a custom router that will route you by geographic location.

We will soon announce something for general DoH and DoT clients to get the same advantage.

**Comment by iJorgen** [comment]
> 
> 
> Reports are handled by priorities and all anycast issues can't be easily fixed. Note that this repository is about the CLI client, if you are using the CLI client, you are not subject to anycast routing issues as the CLI is using a custom router that will route you by geographic location.
> 
> We will soon announce something for general DoH and DoT clients to get the same advantage with other clients.

I am using the CLI client on ASUS Merlin, so guess it's the "custom router" that needs to be adjusted then. If the CLI client on my router did a simple test like https://ping.nextdns.io/ on startup it would easily find the fastest routers each time, but guess it's not that simple?! ;-)

**Comment by rs** [comment]
ping.nextdns.io gives you the top pop for your location (handled by the same router as for CLI) and ping them. The primary/secondary indicated show which pops are used for primary/secondary anycast. As CLI is not using anycast, what ping shows is irrelevant to you.

**Comment by timkgh** [comment]
https://ping.nextdns.io reports good primary and secondary selections but https://router.nextdns.io returns something else that is non-optimal, I'd rather use what ping.nextdns.io returns.

**Comment by rs** [comment]
Can you please show both outputs so we can debug?

**Comment by timkgh** [comment]
ping:
```
vultr-sjc     8 ms  (primary)
do-sfo       13 ms
anexia-lax   17 ms
zepto-lax    18 ms  (secondary)
vultr-lax    18 ms
```

router:
`[{"hostname":"ipv4-do-sfo-1.edge.nextdns.io","ip":"157.245.175.48"}]`

In ping, secondary doesn't look ideal (should be do-sfo, though maybe it just selects a different region for secondary), while in router it picked do-sfo which is not ideal either.

**Comment by rs** [comment]
They are all ideal TBH. 10ms difference is just nothing. SFO is used by router because geographically closer most likely.

**Comment by timkgh** [comment]
Every ms counts, in particular on web pages that can result in 10s if not 100s of DNS requests.

**Comment by ignoramous** [comment]
> Every ms counts, in particular on web pages that can result in 10s if not 100s of DNS requests.

I'd argue in that case, enable `cache boost` :)

**Comment by rs** [comment]
To add 10s on a page with 10ms incremental latency on DNS, the page would need to include assets from 1000 different domains, all **uncached** and all resolved **sequentially**. If you find this kind of page, I'd like to have a discussion with its author :)

**Comment by timkgh** [comment]
We can argue about the # of DNS requests and what humans perceive as slower, but still, the fact remains that the CLI makes a non-optimal choice.

**Comment by timkgh** [comment]
Another example from a different location:
ping:
```
  vultr-chi    11 ms
  vultr-dal    21 ms
  anexia-dal   23 ms
  vultr-atl    24 ms
  anexia-atl   25 ms
  zepto-mci    26 ms
■ zepto-iad    26 ms  (secondary)
  zepto-xrs    26 ms
  anexia-mnz   29 ms
  vultr-ewr    43 ms
■ vultr-lax    51 ms  (primary)
```

router:
`[{"hostname":"ipv4-zepto-mci-1.edge.nextdns.io","ip":"170.39.225.135"}]`

These choices don't make a lot of sense to me.

**Comment by romaincointepas** [comment]
@timkgh could you share your city (or closest metro) and ASN?

**Comment by timkgh** [comment]
Sent you an email.

**Comment by tympom** [comment]
For me it is constantly switching back and forth instead of sticking to the closest one...
