### ISSUE TITLE
EdgeOS v2.0.9 issues vs. v1.10.11

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#365]
I moved from EdgeOS v1.10.11 to v2.0.9-rc3 on an EdgeRouter ER-12 and noticed some issues:

1. `nextdns` is no longer in the `PATH`. I believe in v1 it used to be symlinked from `/usr/bin`, but not in v2.

2. EdgeOS v2 now uses `systemd` which nextdns seems to identify correctly. However `nextdns log` command is broken because the log goes to `/var/log/messages` not journald.
```
# /config/nextdns/nextdns log
-- No entries --

# journalctl -u nextdns
No journal files were found.
-- No entries --
```

**Context**
 - Version: 1.8.8
 - Platform: EdgeOS v2.0.9-rc3 (EdgeRouter ER-12)

**Comment by timkgh** [comment]
Another problem to add to the list:

3. It fails to start at boot. It tries but I suspect it comes up too early before the interfaces get IPs assigned so the listen fails. I have it configured to listen on specific IPs. This is the error in the log:
```
Nov  9 14:16:22 router nextdns[1119]: Startup failed: proxy: tcp: listen tcp 192.168.5.1:53: bind: cannot assign requested address
```
If I started after I ssh in to the router it comes up OK.

**Comment by timkgh** [comment]
4. `discovery-dns` just doesn't work on v2. This could be a general problem with nextdns 1.8.8 though because it doesn't seem to work on Linux server either (Ubuntu 18.04). I had this working in the past with 1.8.6, not sure what changed.
```
# /config/nextdns/nextdns discovered
...
"dns": {
"192.168.5.0": [],
"192.168.5.13": [],
...
"fe80::822a:a8ff:fe4b:381e": [],
...
"\u003cnil\u003e": [],
...
},
...
```

**Comment by sectary-want-holly** [comment]
> I moved from EdgeOS v1.10.11 to v2.0.9-rc3 on an EdgeRouter ER-12 and noticed some issues:
> 
> 1. `nextdns` is no longer in the `PATH`. I believe in v1 it used to be symlinked from `/usr/bin`, but not in v2.

I can replicate this in v2.0.8 (current STABLE).

> 2. EdgeOS v2 now uses `systemd` which nextdns seems to identify correctly. However `nextdns log` command is broken because the log goes to `/var/log/messages` not journald.

I cannot replicate this in v2.0.8.

**Comment by timkgh** [comment]
> > I moved from EdgeOS v1.10.11 to v2.0.9-rc3 on an EdgeRouter ER-12 and noticed some issues:
> > 
> > 1. `nextdns` is no longer in the `PATH`. I believe in v1 it used to be symlinked from `/usr/bin`, but not in v2.
> 
> I can replicate this in v2.0.8 (current STABLE).
> 
> > 1. EdgeOS v2 now uses `systemd` which nextdns seems to identify correctly. However `nextdns log` command is broken because the log goes to `/var/log/messages` not journald.
> 
> I cannot replicate this in v2.0.8.

Are you saying logs go to journald in v2.0.8 or that `nextdns log` works? 2.0.9rc3 is the first v2 version I'm using so I'm not sure what the proper behavior for logging on v2 should be, whether `/var/log/messges` is used or journald.

> > 1. `discovery-dns` just doesn't work on v2.
> 
> Works fine on v2.0.8 for me.
That was my experience on v1.10.11 too, not sure why it doesn't work on v2. Same running 1.8.8 on Linux though, so again something is broken somewhere.

> > It fails to start at boot.
> 
> I cannot replicate this on v2.0.8.

Are you listening on specific VLAN interfaces or on all interfaces? That might be the difference here. I have 3 VLANs and I want to listen on those only, not on WAN, VPN interfaces, etc.

**Comment by timkgh** [comment]
Ah `journald` is disabled by default in 2.0.9

**Comment by timkgh** [comment]
> discovery-dns just doesn't work on v2. This could be a general problem with nextdns 1.8.8 though because it doesn't seem to work on a Linux server either (Ubuntu 18.04). 

I believe this is the problem: https://github.com/nextdns/nextdns/issues/366

**Comment by timkgh** [comment]
EdgeOS v2.0.9 is semi-official, to be released to everyone next week:
https://community.ui.com/releases/EdgeMAX-EdgeRouter-Firmware-v2-0-9-v2-0-9/aa860fa1-8756-448b-a464-595d65ef6752

**Comment by timkgh** [comment]
> Another problem to add to the list:
> 
> 1. It fails to start at boot. It tries but I suspect it comes up too early before the interfaces get IPs assigned so the listen fails. I have it configured to listen on specific IPs (these IPs are statically assigned to interfaces, no DHCP is involved). This is the error in the log:
> 
> ```
> Nov  9 14:16:22 router nextdns[1119]: Startup failed: proxy: tcp: listen tcp 192.168.5.1:53: bind: cannot assign requested address
> ```
> 
> If I start it after I ssh in to the router it comes up OK, so it's not a config issue, it just starts too early, before all networking is set up.

For this issue, it may have to start after `vyatta-router.service` if the unit config for sshd on the router is any indication.
```
[Unit]
Description=OpenBSD Secure Shell server
Wants=vyatta-router.service
After=network.target auditd.service vyatta-router.service
```

The unit config for `nextdns` may also need to add `Restart=on-failure`, it only has `RestartSec=120`

**Comment by sectary-want-holly** [comment]
> > > 1. EdgeOS v2 now uses `systemd` which nextdns seems to identify correctly. However `nextdns log` command is broken because the log goes to `/var/log/messages` not journald.
> > 
> > 
> > I cannot replicate this in v2.0.8.
> 
> Are you saying logs go to journald in v2.0.8 or that `nextdns log` works?

They definitely go to /var/log/messages. I can see the logs initially, but it appears they disappear when <tt>messages</tt> is rotated.

> Are you listening on specific VLAN interfaces or on all interfaces? 

Not sure I understand the question?  By 'listening', what do you mean in the context of boot? Do I have an interface for WAN raised and listening for DHCP? Yes.

**Comment by sectary-want-holly** [comment]
I'll upgrade to 2.0.9 later this evening and see if I notice any of the issues you're raising.

**Comment by timkgh** [comment]
> Not sure I understand the question? By 'listening', what do you mean in the context of boot? Do I have an interface for WAN raised and listening for DHCP? Yes.

Sorry, I meant is your nextdns listening on specific interfaces? nextdns.conf looks like this for me when I see the issue:
```
listen 127.0.0.1:53
listen 192.168.x.1:53
listen 192.168.y.1:53
listen 192.168.z.1:53
```

**Comment by sectary-want-holly** [comment]
Ah. Then, no. I simply have: <tt>listen localhost:53</tt>

**Comment by timkgh** [comment]
> Ah. Then, no. I simply have: listen localhost:53. I drive everything through DNSMASQ first, then onto NextDNS Proxy.

I go the other way around, nextdns first and dnsmasq behind it via `discover-dns` to resolve local names. Does client name reporting work with your setup, can you see the names (not just IP or MAC) in analytics/logs in the NextDNS web interface? I've been struggling for a while to find a set up where everything works as expected.
See https://github.com/nextdns/nextdns/issues/341#issuecomment-706738980
This used to work in EdgeOS v1 but having a hard time with it in v2.

**Comment by sectary-want-holly** [comment]
Just upgraded to 2.0.9 GA. NextDNS *breaks* badly.  Upon bootup, the NextDNS service does not, and cannot, start. 

root@edgerouter:/config/nextdns# ./nextdns log
-- No entries --
root@edgerouter:/config/nextdns# ./nextdns stop
Error: systemctl stop nextdns.service: exit status 5: Failed to stop nextdns.service: Unit nextdns.service not loaded.
root@bos-edgerouter:/config/nextdns# ./nextdns start
Error: systemctl start nextdns.service: exit status 5: Failed to start nextdns.service: Unit nextdns.service not found.

Further, the log file is now *completely* broken. Nothing is outputted, nor captured in <tt>messages</tt>. This is going to cause a lot of issues when people upgrade to 2.0.9.

**Comment by sectary-want-holly** [comment]
To get my DNS service back, I had to uninstall NextDNS CLI and manually re-install.

**Comment by sectary-want-holly** [comment]
> Does client name reporting work with your setup, can you see the names

Yes. Works perfectly on 2.0.8.  Appears to also be working on 2.0.9.

**Comment by timkgh** [comment]
> > Does client name reporting work with your setup, can you see the names
> 
> Yes. Works perfectly on 2.0.8. Appears to also be working on 2.0.9.

Do you set `discovery-dns` to point to `dnsmasq` or it just picks up names from /etc/hosts, leases file, mDNS?

**Comment by timkgh** [comment]
Upgraded from EdgeOS 2.0.9-rc3 to 2.0.9, nextdns unit file and /etc/nextdns.conf were removed completely, had to re-install it again.

I also modified the unit file and it now starts after reboot:
```
[Unit]
Description=NextDNS DNS53 to DoH proxy.
ConditionFileIsExecutable=/config/nextdns/nextdns
After=network.target auditd.service vyatta-router.service
Before=nss-lookup.target
Wants=nss-lookup.target vyatta-router.service

[Service]
StartLimitInterval=5
StartLimitBurst=10
Environment=SERVICE_RUN_MODE=1
ExecStart=/config/nextdns/nextdns run
Restart=on-failure
RestartSec=60
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target
```

@rs This needs to be investigated for EdgeOS 2.0.9, there are some major issues on this platform.

**Comment by sectary-want-holly** [comment]
> > > Does client name reporting work with your setup, can you see the names
> > 
> > 
> > Yes. Works perfectly on 2.0.8. Appears to also be working on 2.0.9.
> 
> Do you set `discovery-dns` to point to `dnsmasq` or it just picks up names from /etc/hosts, leases file, mDNS?

The latter. I have PTR & A records all configured, so it grabs it from there I presume.

**Comment by sectary-want-holly** [comment]
@rs can you kindly acknowledge this issue as 2.0.9 is coming within days...

**Comment by rs** [comment]
I'll have a look at it ASAP.

**Comment by sectary-want-holly** [comment]
Much appreciated!

**Comment by timkgh** [comment]
It might be easiest to ignore `systemd` on this platform and do the same as for EdgeOS v1, use a `/config/scripts/post-config.d/` script to start it. Too many things will be wiped when the firmware is upgraded, but anything in `/config` survives.

**Comment by timkgh** [comment]
> > > > Does client name reporting work with your setup, can you see the names
> > > 
> > > 
> > > Yes. Works perfectly on 2.0.8. Appears to also be working on 2.0.9.
> > 
> > 
> > Do you set `discovery-dns` to point to `dnsmasq` or it just picks up names from /etc/hosts, leases file, mDNS?
> 
> The latter. I have PTR & A records all configured, so it grabs it from there I presume.

Not sure I understand the setup. Do you use `add-subnet` and/or `add-mac` in `dnsmasq`? Otherwise how can `nextdns` know which client the request comes from, it will look like all requests are made by the router.

**Comment by sectary-want-holly** [comment]
By default, NextDNS adds 'add-mac' to EdgeOS's dndmasq configuration file.

**Comment by timkgh** [comment]
I see. Do you use `setup-router true` in nextdns.conf? I never tried it. For my setup hosts, dhcp leases file, mDNS are not good enough, only dnsmasq has the full picture because of multiple VLANs and names in the lease file lacking the domains.

**Comment by sectary-want-holly** [comment]
> Do you use setup-router true in nextdns.conf

Yes.

**Comment by timkgh** [comment]
> I'll have a look at it ASAP.

@rs EdgeOS v2.0.9 is official.

**Comment by ralban** [comment]
Experiencing similar issues here.
My pre 2.x nextdns.conf saved in /config/nextdns seems to be ignored.
I can run sudo nextdns config commands to modify my post 2.x config, but I can't locate where the file is stored on the filesystem to transpose my MAC conditional configs in my pre 2.x conf.
This could be an ID10T on my part, happy to test or provide logs for troubleshooting.

**Comment by rs** [comment]
It's most likely in /etc/nextdns.conf

**Comment by timkgh** [comment]
> It's most likely in /etc/nextdns.conf

That's where it is. Note that it gets wiped every time you upgrade EdgeOS, so keep a backup on a computer if you customize the file. You will also have to re-install nextdns after a firmware upgrade as that gets wiped too.

**Comment by rs** [comment]
Is the /data partition saved over firmware upgrades?

**Comment by timkgh** [comment]
> Is the /data partition saved over firmware upgrades?

There is no `/data`, there is `/config` which is saved. With v1 firmware the script went in `/config/scripts/post-config.d` instead of using `systemd` and that was fine. Maybe easier to do the same for v2 instead of trying to fit it into systemd?
