### ISSUE TITLE
discovery-dns does not work against dnsmasq 2.79

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#366]
When setting `discovery-dns` to a `dnsmasq` v2.79 server, discovery always fails, dnsmasq returns `SERVFAIL` for all queries sent to it by nextdns.

It appears that nextdns needs to set the recursion desired bit. I did a wireshark on the queries it sends and the bit is not set.

From the dnsmasq changelog for 2.79:

> Always return a SERVFAIL answer to DNS queries without the
recursion desired bit set, UNLESS acting as an authoritative
DNS server. This avoids a potential route to cache snooping.

**Context**
 - Version: 1.8.8 
 - Platform: ALL

**Comment by rs** [comment]
The rd flag is not set on purpose as we are only interested by names dnsmasq is authoritative for in the context of discovery. What is the use-case of a discovery to a recursed domain?

**Comment by timkgh** [comment]
My use case is dnsmasq serving static DHCP and acting as the DNS server for local names for 3 VLANs (internal domains). For the static DHCP names/address mappings it can also respond to DNS queries for those names and reverse for IPs. I'm not sure why it is not authoritative for those names, maybe I'm missing some setting in dnsmasq if anyone knows.

I use nextdns as the DNS server on the router (listening on the interfaces of the 3 VLANs) but I also want it to resolve local names that dnsmasq knows about from the dhcp clients, hence I set it as discovery-dns.

I know that nextdns can look at the leases file directly but that is not good enough because the leases file does not include the domain names and I use 3 internal domain names on 3 VLANs. See https://github.com/nextdns/nextdns/issues/341

**Comment by timkgh** [comment]
It appears dnsmasq changed this again in 2.80 to allow local names without setting rd.

http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=29ae3083981ea82f535f77ea54bbd538f1224a9e

But what do we do meanwhile when we run on a distro or router firmware that offers dnsmasq 2.79 and it's hard or impossible to replace it?

**Comment by rs** [comment]
If it's a bug that only affects one version of dnsmasq, this problem will go away by itself pretty soon.

**Comment by timkgh** [comment]
> If it's a bug that only affects one version of dnsmasq, this problem will go away by itself pretty soon.

How? I don't expect that EdgeOS v2 will upgrade `dnsmasq` any time soon. Any distro that uses dnsmasq 2.79 will have this problem, e.g. Ubuntu 18.04 LTS which is still supported for another 2-3 years and they don't make version changes to the packages, just minor fixes.

**Comment by sectary-want-holly** [comment]
> If it's a bug that only affects one version of dnsmasq, this problem will go away by itself pretty soon.

It will not. It needs fixing.

**Comment by timkgh** [comment]
Thank you @rs. When can we get a new official build please?
