### ISSUE TITLE
Can I view nextdns account logs through the nextdns CLI without actually using it for DoH ?

### ISSUE THREAD

**Issue by rsyncnet** [nextdns/nextdns#367]
I do not need a DoH client - I have a properly working configuration just using the nextdns server addresses, etc.

HOWEVER, I do need to tail the logs of my nextdns account.

Currently I am using the https://my.nextdns.io/XXXXXXX/logs page and clicking the little spinny-arrow refresh button to make that page live refresh.

However, eventually it stops ... further, a web page is not a great interface - what I really want is to tail the logs in a terminal.

Can the nextdns CLI help in any way here ?  Can I use it to query and display the connection logs of my nextdns account ?

Or do I need to actually use it as my DoH client and send all my DNS through it in order to get logs ?

Thanks.

**Comment by rs** [comment]
No it can’t. The cli is just a DNS to DoH proxy with some advanced NextDNS specific features. It can’t access your account data or logs.
