### ISSUE TITLE
NextDNS unsuccesful installation on Untangle 16.0.1/Dnsmasq version 2.80

### ISSUE THREAD

**Issue by ghost** [nextdns/nextdns#369]
sh -c "$(curl -sL https://nextdns.io/install)" fails to properly install and run on Untangle v16 which runs Dnsmasq v2.80. Dnsmasq's port is not modified by the script and therefore NextDNS is halted upon run.

# nextdns log
-- Logs begin at Thu 2020-11-19 23:20:08 CST, end at Fri 2020-11-20 07:07:32 CST. --
Nov 20 07:02:29 gateway systemd[1]: Started NextDNS DNS53 to DoH proxy..
Nov 20 07:02:29 gateway nextdns[53325]: Starting NextDNS 1.8.8/linux on :53
Nov 20 07:02:29 gateway nextdns[53325]: Starting mDNS discovery
Nov 20 07:02:29 gateway nextdns[53325]: Listening on TCP/:53
Nov 20 07:02:29 gateway nextdns[53325]: Listening on UDP/:53
Nov 20 07:02:29 gateway nextdns[53325]: Error: proxy: tcp: listen tcp :53: bind: address already in use
Nov 20 07:02:29 gateway nextdns[53325]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
Nov 20 07:02:29 gateway systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
Nov 20 07:02:29 gateway systemd[1]: nextdns.service: Failed with result 'exit-code'.
Nov 20 07:02:57 gateway systemd[1]: Started NextDNS DNS53 to DoH proxy..
Nov 20 07:02:57 gateway nextdns[53687]: Starting NextDNS 1.8.8/linux on :53
Nov 20 07:02:57 gateway nextdns[53687]: Listening on TCP/:53
Nov 20 07:02:57 gateway nextdns[53687]: Error: proxy: tcp: listen tcp :53: bind: address already in use
Nov 20 07:02:57 gateway nextdns[53687]: Starting mDNS discovery
Nov 20 07:02:57 gateway nextdns[53687]: Listening on UDP/:53
Nov 20 07:02:57 gateway nextdns[53687]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
Nov 20 07:02:57 gateway systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
Nov 20 07:02:57 gateway systemd[1]: nextdns.service: Failed with result 'exit-code'.

**Comment by amit510** [comment]
any update on this issue? I am seeing similar issue when trying to install NextDNS on Untangle Firewall.
