### ISSUE TITLE
OS X/resolver support

### ISSUE THREAD

**Issue by kurktchiev** [nextdns/nextdns#371]
So I have a bunch of custom definitions in /etc/resolver/* on OS X but currently NextDNS ignores and actually overwrites these which more or less defeats the purpose of them :(

**Comment by rs** [comment]
Are you using the cli (from this repo), the app store app or the new DoH built-in support of Big Sur?

**Comment by kurktchiev** [comment]
CLI 
```
╭─ 15:57:34  hw-colo-west@default  ~ ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 1 ✘ 
╰─❯ nextdns version
nextdns version 1.8.8
```

**Comment by rs** [comment]
The cli is just setting the DNS server for the network interfaces to 127.0.0.1, it should not affect those rules. I actually didn't use this feature for years, and with or without nextdns enabled, it does not seem to work anymore. Are you sure this is still working under Big Sur?

What is your use-case?

**Comment by kurktchiev** [comment]
i thought the same with Big Sur and maybe they deprecated it but could not find anything on it. Either way thought whether through /etc/resolver/* or scutil --dns you can set resolvers and domains for those specific resolvers. My usecase is this: I connect to multiple VPNs and corporate FQDNs so I have the specific FQDNs using /etc/resolver to match the correct DNS server to use. Also, I am connecting to a slew of Kubernetes clusters whit different cluster FQDNs so depending on the FQDN of those I have dns server pointing to the k8s DNS so I can resolve things directly from my CLI.

**Comment by rs** [comment]
But when doing so, does it work without nextdns cli running?

Why not using the forwarder feature of nextdns cli?

**Comment by kurktchiev** [comment]
because i didn't know it could do the forwarder bit :). I will give it a try and see what happens
