### ISSUE TITLE
[Feature Request] Allow Conditional Forwarding

### ISSUE THREAD

**Issue by athornfam2** [nextdns/nextdns#374]
As an IT professional my family relies on my expertise at home. I finally found a service that's economical, easy to use, and has some stellar features. However, It kind of bums me out that I can't forward all of my WWW requests through my Windows DNS Servers that are geographically placed for my family.

Can you add these features:

* Roaming agents
* Tracking dns requests based on GEO-IP or LAN identifier
* Allow traffic forwarding through Windows Servers or supply Prosumers/small businesses with an OVA to run to split traffic requests
* Allow us to specify an external WAN address when setting up a new location
* Allow logging of all ip address based devices on a specified lan/lans under the WAN for that location

**Comment by rs** [comment]
Please describe your problem/request with more details, I don't understand.

**Comment by sectary-want-holly** [comment]
This FR makes absolutely no sense and appears to have been written by someone with limited competence.
