### ISSUE TITLE
Local DNS Forwarding

### ISSUE THREAD

**Issue by athornfam2** [nextdns/nextdns#375]
I'd like to request the ability to stand up a virtual appliance for local DNS forwarding. Hopefully, the picture helps with what I'm requesting.

https://files.readme.io/f7bc19a-dns_network.jpg

**Comment by rs** [comment]
You can implement this using the forwarder directive. More info here: https://github.com/nextdns/nextdns/wiki/Split-Horizon

**Comment by athornfam2** [comment]
So, I do have the NextDNS servers (45.90.28.102,45.90.30.102) on both of my primary DC's as forwarders. My devices are forwarding DNS requests to those DC's but those queries are not showing up in the analytics dashboard. Any reason why those requests wouldn't show?

**Comment by rs** [comment]
So you are not using the CLI? This repository is about the NextDNS CLI DNS proxy. You might want to try it to solve your issue.

See installation instructions here: https://github.com/nextdns/nextdns/wiki

**Comment by athornfam2** [comment]
If this is only for the DNS Client NextDNS provides where is a good place to put a support request in? I like the product and would like to use it I just either need to route all dns queries through an OVA for split traffic or directly through my DNS servers.

**Comment by rs** [comment]
For free and pro plan, we just launched a [community forum](https://help.nextdns.io/hc/en-us/community/topics). Company and education plans get email support.
