### ISSUE TITLE
ping.nextdns.io

### ISSUE THREAD

**Issue by FernandoMiguel** [nextdns/nextdns#377]
has ping.nextdns.io been limited?
it used to test all endpoints. 
was really useful to measure latency worldwide

**Comment by FernandoMiguel** [comment]
also, i cant see the chat anymore on the website

**Comment by rs** [comment]
Yes it does only return the top 10 closest PoPs now. We don’t want to make the live of attackers too easy.

**Comment by FernandoMiguel** [comment]
@rs make the longer list behind auth?
maybe a paid feature?
it is **really** useful

**Comment by rs** [comment]
Chat is gone, we are moving to a new community forum on https://help.nextdns.io
