### ISSUE TITLE
Cannot access CareerOneStop.org

### ISSUE THREAD

**Issue by yokoffing** [nextdns/nextdns#378]
I don't see a way to contact you guys anymore through the website, so I came here to Github.

If I use any of my browsers with my DoH setup, I cannot access https://www.careeronestop.org/. If I use my browsers with no DoH setup, I can access the website. Strange thing is: According to my logs, the domain isn't being blocked. So I'm not sure what's causing this.

**Comment by rs** [comment]
We just opened community support for free and pro plans: https://help.nextdns.io/hc/en-us/community/topics

For false positives and blocklists proposals: https://github.com/nextdns/metadata

**Comment by yokoffing** [comment]
Thank you.

I checked the site again this morning and now it's working on all my browsers. I've bookmarked these pages.

Not sure what was going on with NextDNS last night with that site.
