### ISSUE TITLE
Log exits with error

### ISSUE THREAD

**Issue by saneef** [nextdns/nextdns#380]
Using the latest nextdns, when trying to see the log it exists with error.

```bash
pi@raspberrypi:~ $ sudo nextdns status
running
pi@raspberrypi:~ $ sudo nextdns log
Error: exit status 1
```

**Context**
pi@raspberrypi:~ $ sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: raspbian
INFO: GOARCH: armv7
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: LATEST_RELEASE: 1.9.4

**Comment by rs** [comment]
what do you get for:

```
ls -l /var/log/messages
which journalctl
```

**Comment by saneef** [comment]
I get these:
```bash
$ ls -l /var/log/messages
-rw-r----- 1 root adm 169467 Dec  5 00:00 /var/log/messages
$ which journalctl
/usr/bin/journalctl
```

**Comment by iJorgen** [comment]
Same error-message here using the latest ASUS Merlin 386.1 beta 1.

**Comment by wii747** [comment]
Got the same error on my Pi

Linux raspberrypi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l

pi@raspberrypi:~ $ sh -c "$(curl -sL https://nextdns.io/install)"
INFO: OS: raspbian
INFO: GOARCH: armv7
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: LATEST_RELEASE: 1.9.4
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
OK

pi@raspberrypi:~ $ nextdns log
Error: exit status 1
pi@raspberrypi:~ $ sudo nextdns log
Error: exit status 1
pi@raspberrypi:~ $ ls -l /var/log/messages
-rw-r----- 1 root adm 148237 Dec  9 11:40 /var/log/messages
pi@raspberrypi:~ $ which journalctl
/usr/bin/journalctl

**Comment by raeokay** [comment]
Same issue on MX Linux. 

Not sure if related issue or if I should mention in a separate one, but running sudo nextdns activate also gives me a similar error: 

$ sudo nextdns activate
Error: NetworkManager resolver management: exit status 1
