### ISSUE TITLE
few basic questions for expert users

### ISSUE THREAD

**Issue by needhelpfulanswers-spectrumchat** [nextdns/nextdns#381]
**what recent tests analysis sources compares all main dns options to see how fast this one is?**
what app/tool can we use to test all dns and see which is fastest?

**do blocklists interfere with ublocklist if some are the same?**
does having dup blocklist basically waste cpu + ram? does it just waste a few second each site you go to?

**which are minimal blocklist to have for ads if you've already have default lists of ublocko ?**

**status keeps changing from** 

'All good! This device is using NextDNS with this configuration.'

to 

'This device is not using NextDNS.
This device is currently using ips as DNS resolver'

is that normal? whats wrong?

should do manually or?

windows 10

**for Native Tracking Protection BETA if you have windows 10 on, does it cause any problems like does it block updates?**

**steps to check if it's using DoH or DoT ?**

https://help.nextdns.io/hc/en-us/articles/360017665880-What-is-DNS-over-TLS-DoT-and-DNS-over-HTTPS-DoH-
https://help.nextdns.io/hc/en-us/articles/360017720899-Which-setup-type-to-use-

**it made ~700 queries within first couple of minutes, is that normal? seems to slow down tho**

**300k queries is nothing it has already used 1000+**
would be gone in 2 days or so
like each one of http://avatars3.githubusercontent.com/ counts as 1 query so looks like there's a ton just going to 1 site/page

are the blocklists adding to the queries?

**Comment by rs** [comment]
This repository is about the cli client. Please see https://community.nextdns.io/t/please-read-this-first/19 for where to find answers to your questions.

**Comment by needhelpfulanswers-spectrumchat** [comment]
delete
