### ISSUE TITLE
Log command not working on Win10 CLI client

### ISSUE THREAD

**Issue by chr-lei** [nextdns/nextdns#382]
Executing _nextdns log_ on the Windows CLI client does not display any logs (CLI or queries, if enabled). It returns the below error. Unclear if this is an broken on Windows because it doesn't implement the same logging infrastructure as Linux; or if this is a known non-implemented feature.

_C:\Program Files\NextDNS>nextdns log
%!s(<nil>)Error: not implemented_

**Context**
 - Version [e.g. 1.5.2]: 1.9.4
 - Platform [e.g. macOS, ASUS-Merlin]: Windows 10 x64

**Comment by rs** [comment]
The log command is not yet implemented on windows.
