### ISSUE TITLE
Update/Install no longer working on Mac

### ISSUE THREAD

**Issue by ChrisColotti** [nextdns/nextdns#383]
I tried to upgrade and it did nothing.  I then removed and tried to install the CLI and get:

ERROR: Installation failed: binary not installed in /usr/local/bin/nextdns
ERROR: install: exit 0

**Context**
 - Version: Latest
 - Platform: macOS Big Sur

Never had an issue on mac before updating or installing...

**Comment by rs** [comment]
I can't reproduce. Does it work if you uninstall then reinstall?

**Comment by ChrisColotti** [comment]
Same issue on removal and install.  I can no longer get it to even install clean..

More info used a different client there was some other text I could not see in the other client

'''INFO: Installing NextDNS...
==> Installing nextdns from nextdns/tap
==> Downloading https://github.com/nextdns/nextdns/releases/download/v1.9.4/nextdns_1.9.4_darwin_amd64.tar.gz
Already downloaded: /Users/ccolotti/Library/Caches/Homebrew/downloads/5f0809e52730f1df08ea1e1b689cbdef225f10ccf36b8527c4804649c4a32f34--nextdns_1.9.4_darwin_amd64.tar.gz
Error: Your CLT does not support macOS 11.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Error: An exception occurred within a child process:
  SystemExit: exit'''

**Comment by ChrisColotti** [comment]
the full removal and re-install seemed to fix homebrew

Closing for now
