### ISSUE TITLE
How to get support for best server

### ISSUE THREAD

**Issue by gbil** [nextdns/nextdns#384]
Before the chat shutdown I was troubleshooting an issue that not the proper server is selected for me but troubleshooting never finished 
Then I saw the diag process and I've used it already a few times but the behavior is still the same and I also mentioned in a thread in reddit that while support says that any diag report is checked, the customer has no information if that is really happening and what the status is 
Then I saw that this was fixed for others via a bug report here

So what is the best way to get support on such topics BUT also know the progress of the support request? 

**Context**
 - Version [e.g. 1.5.2]: 
 - Platform [e.g. macOS, ASUS-Merlin]:

**Comment by rs** [comment]
This repo is for cli. The diag is the right way to report network issues. Some issues takes longer than the others to get fixed.

**Comment by gbil** [comment]
So no real answer here, no real answer in reddit, help.nextdns.io no longer exists. I guess even though we pay we need to get support by..........  <- put any valid answer here

**Comment by rs** [comment]
We just fixed help.nextdns.io, we are still working on the help center, it is going to change dramatically in .

In a nutshell:
* For free and pro plans, the support is https://community.nextdns.io
* For business and education plans, there is an email support

See https://community.nextdns.io/t/please-read-this-first/19 for more info.

**Comment by gbil** [comment]
So you change your support model without offering anything similar to the previous one - direct chat - and we have to rely to a tool without any feedback whatsoever and on a forum, which by the way requires a separate registration 

If nothing else, make your support model CLEAR in the pricing offering, anything else it the least deceptive

**Comment by rs** [comment]
We will add clear support model in the pricing as soon as we settled it — should be very soon. As said, we are working on it. The current pricing does not include support, so we changed nothing in that regard.
