### ISSUE TITLE
Fresh Tomato Support

### ISSUE THREAD

**Issue by xtc0r** [nextdns/nextdns#386]
Hello,
I'm using a Netgear R7000 router and I'm wondering if there is any Fresh Tomato support on the horizon? The wiki says "soon".

**Comment by dougK44883** [comment]
Is it just needing development?  an installation script modification?  Is it FreshTomato's EOL 2.6 kernel?  Why wouldn't/doesn't NextDNS run on a FreshTomato installation?

**Comment by EaglePPP** [comment]
is there any news on this? it's been 2 years and still "soon"

**Comment by dougK44883** [comment]
Completely unclear whether the possibility even exists.  AsusWRT has it's roots from Tomato, in turn AsusWRT Merlin as well grew from Tomato, current fork FreshTomato.  
Has development changed to a degree FreshTomato won't run NextDNS, or does FreshTomato need just that much more to provide capability to run NextDNS?  
It's clearly an advanced issue, to even respond - give it up.
