### ISSUE TITLE
MacOS profile doesn't work with LuLu

### ISSUE THREAD

**Issue by dev9** [nextdns/nextdns#387]
The MacOS profile available at apple.nextdns.io doesn't work with the popular open-source MacOS firewall [LuLu](https://github.com/objective-see/LuLu). NextDNS remains disabled under Network Settings until LuLu is disabled and the NextDNS interface is manually made active by selecting the NextDNS interface, clicking on the additional settings button below, and making the interface active.

**Context**
 - Version latest config profile downloaded from apple.nextdns.io, latest LuLu 2.0.0, and latest MacOS Big Sur 11.0.1.

**Comment by rs** [comment]
This repository is for the CLI client. Please report other bugs on our [help center](https://help.nextdns.io/category/bugs).

**Comment by dev9** [comment]
Delete
