### ISSUE TITLE
report-client-info breaks Anonymized EDNS Client Subnet

### ISSUE THREAD

**Issue by mpeleshenko** [nextdns/nextdns#388]
I've noticed that when having Anonymized EDNS Client Subnet enabled, report-client-info enabled, and including the client subnet in the client DNS request, I was getting DNS results back with non-US IPs sometimes for a gateway.icloud.com. Removing the client subnet from the DNS request, I consistently got back DNS results with US IPs as expected. I am personally using unbound with the following settings to support forwarding to the nextdns-cli with the client IP so that I can then see proper client info in my.nextdns.io. This is similar to the dnsmasq integration detailed at https://github.com/nextdns/nextdns/wiki/DNSMasq-Integration, just without the MAC address info, so I don't get Device Model info, which is fine by me.
```
module-config: "subnetcache iterator"
send-client-subnet: 127.0.0.1
max-client-subnet-ipv6: 128
max-client-subnet-ipv4: 32
```

I've managed to reproduce the issue on my MacBook with the nextdns-cli client and using dig with and without client subnet. As far as I can tell the only difference is whether an `X-Device-Ip` header is included as per:
https://github.com/nextdns/nextdns/blob/83adb6e9a75fd5b4ded2a7d4783010c4c493fbd9/resolver/doh.go#L100-L102

**nextdns-cli command arguments**
```
run -listen :5342 -config <config_id> -discovery-dns 192.168.0.1 -report-client-info
```

**With client subnet**
```
$ dig @127.0.0.1 -p 5342 gateway.icloud.com +subnet=192.168.0.1/32

; <<>> DiG 9.16.7 <<>> @127.0.0.1 -p 5342 gateway.icloud.com +subnet=192.168.0.1/32
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20873
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
; CLIENT-SUBNET: 192.168.0.1/32/24
;; QUESTION SECTION:
;gateway.icloud.com.		IN	A

;; ANSWER SECTION:
gateway.icloud.com.	29	IN	A	17.248.151.101
gateway.icloud.com.	29	IN	A	17.248.151.108
gateway.icloud.com.	29	IN	A	17.248.151.43
gateway.icloud.com.	29	IN	A	17.248.151.12
gateway.icloud.com.	29	IN	A	17.248.151.11
gateway.icloud.com.	29	IN	A	17.248.151.44
gateway.icloud.com.	29	IN	A	17.248.151.72
gateway.icloud.com.	29	IN	A	17.248.151.70

;; Query time: 10 msec
;; SERVER: 127.0.0.1#5342(127.0.0.1)
;; WHEN: Sun Dec 13 18:19:34 EST 2020
;; MSG SIZE  rcvd: 187
```

**Without client subnet**
```
$ dig @127.0.0.1 -p 5342 gateway.icloud.com

; <<>> DiG 9.16.7 <<>> @127.0.0.1 -p 5342 gateway.icloud.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41581
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;gateway.icloud.com.		IN	A

;; ANSWER SECTION:
gateway.icloud.com.	30	IN	A	17.248.187.197
gateway.icloud.com.	30	IN	A	17.248.135.115
gateway.icloud.com.	30	IN	A	17.248.135.14
gateway.icloud.com.	30	IN	A	17.248.187.134
gateway.icloud.com.	30	IN	A	17.248.187.133
gateway.icloud.com.	30	IN	A	17.248.135.41
gateway.icloud.com.	30	IN	A	17.248.135.210
gateway.icloud.com.	30	IN	A	17.248.135.40

;; Query time: 9 msec
;; SERVER: 127.0.0.1#5342(127.0.0.1)
;; WHEN: Sun Dec 13 18:19:38 EST 2020
;; MSG SIZE  rcvd: 175
```

Comparing the two results, 17.248.151.101 resolves to an IP in South Africa while 17.248.187.197 resolves to an IP in the US. I used https://www.iplocation.net/ip-lookup for IP geolocation. I would expect to get the latter results always in both cases if Anonymized EDNS Client Subnet is enabled on my config.

**Context**
 - Version [e.g. 1.5.2]: 1.9.4
 - Platform [e.g. macOS, ASUS-Merlin]: OpenWRT

**Comment by rs** [comment]
The bug is not on CLI but is actually a edge case on the server code. We will soon deploy a fix. Thanks for the heads up.

**Comment by ignoramous** [comment]
Does this mean in this edge case NextDNS may have leaked client subnets? Or, is it the other way around (withheld / sent incorrect subnets to nameservers)?

**Comment by rs** [comment]
It leaked the private IP. Client supplied ECS is normally always stripped from the query but not in this particular case. It is not a big deal privacy-wise but for steering, some CDNs seem to think 192.168.0.1 is in South Africa... :)

**Comment by mpeleshenko** [comment]
Not sure if any fixes have been deployed, but I'm now sometimes getting another set of IPs from Germany when passing a subnet. This time, however, I consistently no longer see `CLIENT-SUBNET: 192.168.0.1/32/24` in the response, so something seems to have changed.

```
$ dig @127.0.0.1 -p 5342 gateway.icloud.com +subnet=192.168.0.1/32

; <<>> DiG 9.16.9 <<>> @127.0.0.1 -p 5342 gateway.icloud.com +subnet=192.168.0.1/32
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49809
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;gateway.icloud.com.		IN	A

;; ANSWER SECTION:
gateway.icloud.com.	30	IN	A	17.248.145.145
gateway.icloud.com.	30	IN	A	17.248.145.166
gateway.icloud.com.	30	IN	A	17.248.145.232
gateway.icloud.com.	30	IN	A	17.248.145.235
gateway.icloud.com.	30	IN	A	17.248.145.100
gateway.icloud.com.	30	IN	A	17.248.145.71
gateway.icloud.com.	30	IN	A	17.248.145.77
gateway.icloud.com.	30	IN	A	17.248.145.69

;; Query time: 29 msec
;; SERVER: 127.0.0.1#5342(127.0.0.1)
;; WHEN: Wed Dec 16 08:10:59 EST 2020
;; MSG SIZE  rcvd: 175
```

**Comment by rs** [comment]
Yes the fix is being progressively deployed on all servers.

**Comment by mpeleshenko** [comment]
I'm assuming that since I don't see `CLIENT-SUBNET` in the response, the fix is deployed on the server I'm using. From the logs I see it is `162.220.223.23`. If the fix is indeed deployed there, I would expect to get the US IPs consistently since I have Anonymized EDNS Client Subnet enabled as opposed to the German IPs I am now getting.

**Comment by rs** [comment]
What is the output of `dig +tcp chaos gateway.icloud.com`

**Comment by mpeleshenko** [comment]
See output below.
```
$ dig @127.0.0.1 -p 5342 +tcp chaos gateway.icloud.com +subnet=192.168.0.1/32
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.16.9 <<>> @127.0.0.1 -p 5342 +tcp chaos gateway.icloud.com +subnet=192.168.0.1/32
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22913
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 10

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;gateway.icloud.com.		CH	A

;; ANSWER SECTION:
gateway.icloud.com.	26	IN	A	17.248.145.198
gateway.icloud.com.	26	IN	A	17.248.145.139
gateway.icloud.com.	26	IN	A	17.248.145.202
gateway.icloud.com.	26	IN	A	17.248.145.234
gateway.icloud.com.	26	IN	A	17.248.145.199
gateway.icloud.com.	26	IN	A	17.248.145.76
gateway.icloud.com.	26	IN	A	17.248.145.73
gateway.icloud.com.	26	IN	A	17.248.145.134

;; ADDITIONAL SECTION:
proto.nextdns.io.	0	CH	TXT	"DOH"
conf.nextdns.io.	0	CH	TXT	"<conf>"
client.nextdns.io.	0	CH	TXT	"<WAN IP>"
device-name.nextdns.io.	0	CH	TXT	"OpenWrt"
device-id.nextdns.io.	0	CH	TXT	"BF4NI"
device-ip.nextdns.io.	0	CH	TXT	"192.168.0.1"
server.nextdns.io.	0	CH	TXT	"anexia-ewr-1"
client-name.nextdns.io.	0	CH	TXT	"nextdns-cli"
smart-ecs.nextdns.io.	0	CH	TXT	"not sent"

;; Query time: 25 msec
;; SERVER: 127.0.0.1#5342(127.0.0.1)
;; WHEN: Wed Dec 16 20:04:51 EST 2020
;; MSG SIZE  rcvd: 467
```

**Comment by mpeleshenko** [comment]
When I exclude the `+subnet`, I see my ISP subnet /24 under `smart-ecs.nextdns.io.`. Shouldn't I see the same subnet instead of `not sent` when I do pass `+subnet`?

**Comment by rs** [comment]
Found another edge case when ECS is sent by the client via DoH. Will be fixed soon.

**Comment by mpeleshenko** [comment]
@rs It's looking better now with `anexia-ewr-1` and `vultr-ewr-1` where `smart-ecs` is now populated even when passing `+subnet`. Will keep an eye on this for a few days.
