### ISSUE TITLE
Support DNS over QUIC

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#390]
Just like the competition :)
https://adguard.com/en/blog/dns-over-quic.html

**Comment by michaelb-ae** [comment]
i for it i have tested it in my network (adguard home) and their dns over quic as upstream, and i can say i see the difference (in my network configuration)

**Comment by rs** [comment]
We are still working on DoQ, it still has issues.

@michaelb-ae : if you feel the difference compare to DoH, it means you have a lossy path to your DNS server. If that's the case, you might want to fix that ;)

**Comment by michaelb-ae** [comment]
@rs thanks i have checked and i had a configuration issue thanks ^^, but i will continue with dns over tls / quic, because i prefer my DNS at transport layer than app layer (but it's a personal choice more than anything).

**Comment by rs** [comment]
Not sure what you mean, DNS is always at app layer.

**Comment by michaelb-ae** [comment]
@rs i have mistranslated my thought Doh and Dot have the encryption on different level and i prefer the encryption at lower level as possible

**Comment by devinus** [comment]
@rs DoH over HTTP/3 isn't DoQ, so I'm not sure if this issue should have been closed. DoQ has many advantages over DoH that AdGuard mentions in that article.

**Comment by rs** [comment]
In CLI we need the HTTP layer to transport client information when the option is enabled. Cons described by the AdGuard article are non-issues with CLI: we do not set a cookie jar, nor do we handle etags and aren't sending any fingerprintable information with HTTP. And as far as I know, all popular DoH client are doing the same, so all the DoH vs DoT bashing is a bit overrated if you ask me.

On the other side, HTTP/3 benefits from protocol negotiation with Alt-Svc/HTTPSSVC, so clients can upgrade from HTTP/2 or fallback in case Quic is blocked by the network or ISP/government. This makes it pretty hard to block, unlike DoQ or DoT which are using custom ports and have no clearly specified protocol negotiation yet.

**Comment by devinus** [comment]
> In CLI we need the HTTP layer to transport client information when the option is enabled. Cons described by the AdGuard article are non-issues with CLI: we do not set a cookie jar, nor do we handle etags and aren't sending any fingerprintable information with HTTP.

I should have read what this repository was before commenting. I thought this was the server itself and was concerned NextDNS (I'm actually a paying customer) wouldn't expose an actual DoH `quic://` endpoint.

**Comment by rs** [comment]
Our servers support DoQ already, [last draft](https://tools.ietf.org/html/draft-ietf-dprive-dnsoquic-02).

**Comment by chaojoy** [comment]
> 在 CLI 中，当启用该选项时，我们需要 HTTP 层来传输客户端信息。 AdGuard 文章描述的缺点与 CLI 无关：我们不设置 cookie jar，也不处理 etag，也不使用 HTTP 发送任何可指纹信息。 据我所知，所有流行的 DoH 客户端都在做同样的事情，所以如果你问我，所有对 DoH 与 DoT 的抨击都被高估了。
> 
> 另一方面，HTTP/3 受益于与 Alt-Svc/HTTPSSVC 的协议协商，因此客户端可以从 HTTP/2 升级或在 Quic 被网络或 ISP/政府阻止的情况下回退。 这使得它很难被阻止，不像 DoQ 或 DoT 使用自定义端口并且还没有明确指定的协议协商。

HTTP/3 or quic to some extent, in some highly censored countries ISP can reduce SNI exposure and blocking TLS handshake.
