### ISSUE TITLE
Public DNS

### ISSUE THREAD

**Issue by michaelb-ae** [nextdns/nextdns#392]
Hello, i want to ask a Public version of your DNS who will do two ting.
Fist : implement the Anonymised EDNS.
Second : propose the Google Safebrowsing and pedoporn blocking.

This have two purposes : 
1. if a user use your public dns over DoH or DoT, if he want a more filtered one, he will definitely try your services before event install pihole or adguard.
2. you will Attract more user since i haven't found any other who propose Edns anonymised.

**Comment by rs** [comment]
This repository is about the NextDNS CLI client. For general discussion about NextDNS product, please use https://help.nextdns.io/category/community.
