### ISSUE TITLE
Install script fails silently on fresh Ubuntu 20 Server install

### ISSUE THREAD

**Issue by spm1001** [nextdns/nextdns#394]
Possibly similar to [issue #110](https://github.com/nextdns/nextdns/issues/110), I’m getting silent fail of installation script version 1.9.4 on a clean Ubuntu 20 Server installation which I want to use for DNS for other devices on my network. 

I used the install script, which appeared to complete, but `nextdns status` showed `not installed` afterwards and `nextdns log` showed `nextdns[1370]: Error: proxy: tcp: listen tcp :53: bind: address already in use` followed by `nextdns.service: Failed with result 'exit-code' `

Netstat seemed to point to `systemd-resolved` as the occupier of port 53, (although I must admit I don’t understand the subtleties of a .53 loopback address, so this conclusion might have been false)
```
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      101        21907
      664/systemd-resolve 
udp        0      0 127.0.0.53:53           0.0.0.0:*                           101        21906
      664/systemd-resolve
```
Doing `sudo systemctl stop systemd-resolved` , `sudo systemctl disable systemd-resolved` then `sudo nextdns start` did fix the problem for me, as shown below, but seeing how thoughtfully you guys write software maybe there’s a more elegant solution?

(Thank you for a wonderful product btw.)

```
$ sudo nextdns start
$ nextdns status
running
$ sudo nextdns log
Dec 22 23:13:30 bunty systemd[1]: Started NextDNS DNS53 to DoH proxy..
Dec 22 23:13:30 bunty nextdns[2224]: Starting NextDNS 1.9.4/linux on :53
Dec 22 23:13:30 bunty nextdns[2224]: Listening on TCP/:53
Dec 22 23:13:30 bunty nextdns[2224]: Starting mDNS discovery
Dec 22 23:13:30 bunty nextdns[2224]: Listening on UDP/:53

$ sudo netstat -lnpe | grep 53
tcp6       0      0 :::53                   :::*                    LISTEN      0          33113
      2224/nextdns        
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           0          34910
      2224/nextdns        
udp6       0      0 :::53                   :::*                                0          33115
      2224/nextdns        
udp6       0      0 :::5353                 :::*                                0          34912
      2224/nextdns

$ nextdns config
config 86xxxx
cache-max-age 0s
max-ttl 5s
hardened-privacy false
setup-router true
control /var/run/nextdns.sock
cache-size 10MB
use-hosts true
timeout 5s
bogus-priv true
auto-activate true
listen localhost:53
log-queries false
report-client-info true
discovery-dns 
detect-captive-portals false
```

**Comment by hsmalley** [comment]
I've found using systemd-resolved configuration is a good workaround, although it does not solve the problem itself.

**Comment by rs** [comment]
I just tried to reproduce with a fresh install of 20.04, and I could not reproduce. Did you uninstall NetworkManager before installation or applied any change to the init system?

**Comment by rs** [comment]
Oh I see the you have setup-router set to `true`, is that intentional?

**Comment by spm1001** [comment]
Sorry for delay - yes setup-router `true` was intentional - it's a server that I want to use as a secondary resolver on the network. (Ultimately I want it to get the hostnames from primary/router, but I'm struggling with that bit)

If it helps it's an install of Ubuntu 20.04 Server only (no gui).

A better resolution I found from a commenter elsewhere was essentially to uncomment  `#DNSStubListener=yes` in `/etc/systemd/resolved.conf` and change it to `no`. Then do `sudo systemctl restart systemd-resolved.service` which in turn changes `/etc/resolv.conf` to remove its stub resolver line `nameserver 127.0.0.53`.

**Comment by dogsbody** [comment]
I hate "me too" comments but have just spent half an hour banging my head against this too :-p 
Brand new Ubuntu 20.04 server spun up on my network to act as a DNS53 to DoH proxy and couldn't get it to start at all until I trawled the logs and saw it was clashing with systemd-resolved
