### ISSUE TITLE
Alexa iOS ‘no internet connection’ 

### ISSUE THREAD

**Issue by sectary-want-holly** [nextdns/nextdns#396]
Platform: Alexa.app on iOS (14) using cellular connection. 

In the app, under ‘Communicate’ when using a NextDNS resolver the message ‘no Internet connection’ is displayed. 

This happens _only_ with cellular. If WiFi is used with a NextDNS resolver the issue doesn’t occur. If I change the resolver away from NextDNS when on cellular the app works as expected.  

How bizarre. Any ideas?

**Comment by rs** [comment]
Please use https://help.nextdns.io for such question. This repository is about NextDNS CLI client.

**Comment by sectary-want-holly** [comment]
Oh good point. Will do.
