### ISSUE TITLE
USG-8-XG Was Restarted

### ISSUE THREAD

**Issue by zcpnate** [nextdns/nextdns#397]
Running the nextdns client on Unifi USG-8-XG causes the gateway to crash and restart 1-3 times in a 24 hour period. No notable logs were able to be collected. Deactivating client resumes the stability of the gateway. Also: the service randomly stops and needs to be manually restarted when the client is active.

**Context**
 - Version [e.g. 1.5.2]: 
 - Platform [e.g. macOS, ASUS-Merlin]:

**Comment by rs** [comment]
Which version of the cli?

**Comment by zcpnate** [comment]
nextdns 1.9.4

**Comment by rs** [comment]
Anything interesting in system logs regarding the reason why the whole system would crash?

**Comment by zcpnate** [comment]
When USG reboots it clears the syslogs lol -- I setup rsyslog into graylog and saw nothing of note when crashes occurred. I could setup a console as well but haven't gotten around to it. My girlfriend was getting mad the wifi kept going down :D

**Comment by rs** [comment]
Sorry about that. I need more info to debug tho :)

**Comment by zcpnate** [comment]
No worries, I'll try to setup a console and get a log. In the past I've troubleshoot similar issues and it will show a kernel panic in the console with no real info.

Is there any way to enable logging on the nextdns client?
