### ISSUE TITLE
Wildcard local domain resolution

### ISSUE THREAD

**Issue by viggy96** [nextdns/nextdns#399]
Add the ability to resolve a wildcard domain to a local IP address. For example, I have a server with "domain.tld" that is on 192.168.1.10. That server has countless subdomains, like "foo.domain.tld" and "bar.domain.tld". Its tedious to have to add each and every single one to /etc/hosts to get them to resolve locally. DNSCrypt had something called "cloaking rules" that allowed for this (https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Cloaking). You could just put "*.domain.tld" in the file along with the local IP address, and all subdomains would be resolved to said address.

**Comment by rs** [comment]
The rewrite feature in the settings tab does just that.

**Comment by viggy96** [comment]
But I don't want it to be resolved by NextDNS's service. I want my router itself to resolve the domain, so that even if my Internet connection goes out, I can still resolve the domain, _locally_ within my LAN. Also, even if I did use the rewrite feature, when I'm outside my home, my "domain.tld" would still resolve to 192.168.1.10, instead of its public IP, which is not desirable.

**Comment by rs** [comment]
You can use dnscrypt then, or run a local auth DNS and configure a [split horizon](https://github.com/nextdns/nextdns/wiki/Split-Horizon).

Note that even with internet down, the CLI will continue serving those hosts from its cache until it is restarted, even if the cache become stale.
