### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by FernandoMiguel** [nextdns/nextdns#4]
is it possible to have a persistent config file in a well known location so that we don't have to always set the parameters via CLI?

**Comment by rs** [comment]
Yes

**Comment by FernandoMiguel** [comment]
is it implemented or should this be a feature request? :)

**Comment by rs** [comment]
It's not implemented yet, but should be easy to add. It would work similarly to dnsmasq, with one option per line without dashes, same options as the ones accepted by the command.
