### ISSUE TITLE
NextDNS freezes/extend login time on Windows 8.1 when using picture password.

### ISSUE THREAD

**Issue by nam108** [nextdns/nextdns#40]
Hello

I've noticed some strange thing.
On my device with Windows 8.1 (32bit), after installing the nextdns, after system restart, when the windows for login option appears which by default in my case is logging by image pattern, it takes for the login much more time then normal. It actually looks like some process is freezes after I made the pattern and it takes few seconds for the system to show the login messages that normally appears instantly. I can click other places and it's not totally freeze, just the process of logging seems to be stuck for some time.
Turning off automatic start-up or/and nextdns services strangely enough doesn't change anything.
Only uninstalling brings the situation to normal...

**Comment by rs** [comment]
Are you talking about our Windows app with a graphical user interface or about the command line version (current repo)?

**Comment by nam108** [comment]
> ?

Gui
