### ISSUE TITLE
High CPU usage on Ubiquiti UDMP

### ISSUE THREAD

**Issue by Allram** [nextdns/nextdns#400]
Running Nextdns CLI v1.9.4 on Ubiquiti UDMP (v1.8.5 FW),

It has been working great for a few months, then suddenly now it has startet to be "stable" at ~80% CPU usage.
I have tried to reinstall it by removing it and running this commands:

```
SSH's into the UDM PRO:
ssh root@192.xxx.x.x
enter password

Entered the UNI-OS Shell:
unifi-os shell

Removed the NextDNS Application:
apt-get remove nextdns

Successfully resinstalled the NextDNS app:
sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"' '
```

But it's still at ~80% CPU usage.

![High CPU](https://user-images.githubusercontent.com/5573149/104107447-82fed480-52bc-11eb-8f87-7cd0c8927464.PNG)

**Comment by rs** [comment]
What do you get for `nextdns config`?

**Comment by Allram** [comment]
This is the output for 'nextdns config':

```
max-ttl 5s
report-client-info true
detect-captive-portals false
timeout 5s
control /var/run/nextdns.sock
config 10.0.0.0/24=REMOVED
config 192.168.3.0/24=REMOVED
config 192.168.20.0/24=REMOVED
config 192.168.5.0/24=REMOVED
config REMOVED
config 192.168.2.0/24=REMOVED
cache-size 10MB
use-hosts true
listen localhost:53
log-queries false
bogus-priv true
hardened-privacy false
setup-router true
auto-activate false
cache-max-age 0s
discovery-dns
```

**Comment by Allram** [comment]
It seems to have been solved by running 'nextdns stop' and 'nextdns start' after install. Been stable for approx 1 day now with no visible CPU usage.

**Comment by Allram** [comment]
Marking issue as solved, as it has not occured since running 'nextdns stop' and 'nextdns start' and updating to v1.9.6
