### ISSUE TITLE
Arch Linux: Service stop timeout

### ISSUE THREAD

**Issue by ac130kz** [nextdns/nextdns#401]
I noticed a significant delay in my system's shutdown times as soon as I upgraded to the latest build from 1.8.3. I tried to imitate the stopping procedure which happens during the shutdown and got a timeout (the log below).

**Context**
 - Version: 1.9.4 
 - Platform: Arch Linux

```
● nextdns.service - NextDNS DNS53 to DoH proxy.
     Loaded: loaded (/etc/systemd/system/nextdns.service; enabled; vendor preset: disabled)
     Active: failed (Result: timeout) since Mon 2021-01-11 01:57:50 +06; 27s ago
    Process: 477 ExecStart=/usr/bin/nextdns run (code=killed, signal=KILL)
   Main PID: 477 (code=killed, signal=KILL)

Jan 11 01:56:20 hostname systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Jan 11 01:56:20 hostname nextdns[477]: Stopping NextDNS 1.9.4/linux
Jan 11 01:57:50 hostname systemd[1]: nextdns.service: State 'stop-sigterm' timed out. Killing.
Jan 11 01:57:50 hostname systemd[1]: nextdns.service: Killing process 477 (nextdns) with signal SIGKILL.
Jan 11 01:57:50 hostname systemd[1]: nextdns.service: Killing process 618 (nextdns) with signal SIGKILL.
Jan 11 01:57:50 hostname systemd[1]: nextdns.service: Killing process 622 (n/a) with signal SIGKILL.
Jan 11 01:57:50 hostname systemd[1]: nextdns.service: Killing process 4097 (n/a) with signal SIGKILL.
Jan 11 01:57:50 hostname systemd[1]: nextdns.service: Main process exited, code=killed, status=9/KILL
Jan 11 01:57:50 hostname systemd[1]: nextdns.service: Failed with result 'timeout'.
Jan 11 01:57:50 hostname systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
```

**Comment by rs** [comment]
cc @tanji

**Comment by ac130kz** [comment]
The issue persists on the latest version (1.9.6).

**Comment by tanji** [comment]
@rs did something change in the way we must stop NextDNS?
on linux, systemd will send a SIGKILL to all processes, which usually works out fine in most cases.

**Comment by rs** [comment]
A SIGKILL should just stop the process. Nothing has changed recently in that regard. Not sure what is going on here.

**Comment by ac130kz** [comment]
I managed to temporarily fix the problem by adding a short kill timeout and a control-group kill mode to the service file in `/etc/systemd/system/nextdns.service`:

```
[Service]
TimeoutStopSec=2
KillMode=control-group
```

**Comment by tanji** [comment]
@ac130kz `KillMode=control-group` is always the default in systemd.

**Comment by ac130kz** [comment]
@tanji didn't work without it, for some magic reason
