### ISSUE TITLE
NextDNS is no longer started after restarting UDM 

### ISSUE THREAD

**Issue by jsynowiec** [nextdns/nextdns#404]
After restarting UDM, nextdns reports as _not installed_, but it's running.
```
Welcome to UniFi Dream Machine!
# nextdns status
not installed
```
Running `nextdns` prints list of commands, but ends with the `Error: non zero exit code: 1: OCI runtime error` error message.

But according to logs, nextdns seems to start just fine. NextDNS settings also displays the **All good!** message.
```
# nextdns log
Jan 17 10:56:12 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
Jan 17 10:56:12 ubnt nextdns[68]: Starting NextDNS 1.9.6/linux on localhost:5553
Jan 17 10:56:12 ubnt nextdns[68]: Listening on TCP/127.0.0.1:5553
Jan 17 10:56:12 ubnt nextdns[68]: Listening on UDP/127.0.0.1:5553
```

After running `install` command status, `status` reports correctly.
```
# nextdns install
NextDNS installed and started using ubios init
# nextdns status
running
```

The issue is though, that if `nextdns install` is not executed, upon next restart of UDM, nextdns is not enabled and the nextdns command is no longer available. Website no longer reports **All good!** and informs that the regular DNS resolver is used. At this point, when I rerun the installer, it only asks to reconfigure or uninstall. Running reconfigure reenables NextDNS until next 2 restarts.

**Context**
 - Version: 1.9.6
 - Platform: UniFi UDM running 1.8.5 firmware

**Comment by jsynowiec** [comment]
Update: When SSH is left enabled the above issue doesn't happen. After going over the source code and reading other issues I think I understand how the _persistency_ between reboots was achieved and that it requires the SSH setting to be enabled (ensures that ssh daemon is running?)

**Comment by FlippityFloppityFloopy** [comment]
I have stumbled upon the same issue. Thank you for looking deeper into it. I'm not fond of leaving SSH on personally. So I will have to keep an eye on this constantly.

**Comment by Macqael** [comment]
@jsynowiec @FlippityFloppityFloopy The ssh module is opened on local only ? on internet and Lan to ? (because if it's only local we can let it activated but forbid connection with firewall to port 22 local and disable the rules when we have to connect on SSH) ?
Or I make a mistake in my thinking ?

**Comment by Macqael** [comment]
After some try, in my case I have forbidden port 22 on internet & internet 6 in, local & local 6 in and guest and guest 6 in.
and I disable the rules of dropping port 22 on Local when I have to connect to the UDM, like that SSH is unreachable and you have persistency enabled.
