### ISSUE TITLE
EdgeOS - router ignoring nextdns for its own lookups

### ISSUE THREAD

**Issue by mdav43** [nextdns/nextdns#405]
First - thanks for a great service. Now happily paying and its been flawless. Congrats!

_**[Issue is now solved for me, but thought i'd leave it here as a potenital bug?]**_

My issue: router (where i installed nextdns service following the simple guide) is ignoring the localhost instance of nextdns for its own requests. All clients on the network are using it, and I have put in place DNAT rules to block hardcoded dns lookups - looking at you google.

Note, I didn't edit any dns settings in the webUI of edgeOS. 

**Context**
 - nextdns version 1.9.6
 - Platform EdgeOS
  - Version:      v2.0.9
  - Build ID:     5346345
  - Build on:     10/28/20 16:47
  - HW model:     EdgeRouter X 5-Port

Dont know if this is helpful but output of following commands

```
user@edgerouterx:~$ cat /etc/resolv.conf
# This file is managed by nextdns.
#
# Run "nextdns deactivate" to restore previous configuration.

nameserver      172.17.5.36             #nameserver written by /opt/vyatta/sbin/vyatta_update_resolv.pl
nameserver      172.17.5.4              #nameserver written by /opt/vyatta/sbin/vyatta_update_resolv.pl
nameserver 127.0.0.1
```

I'm guessing its an issue with setting the router to get a DHCP assigned address from the internet modem... and it is
See [old issue in Ubiquit forums](https://community.ui.com/questions/DNS-setup-confusion-/5a5f093f-e507-4ba2-83c9-a80dd55d40d5). 

I corrected the issue by doing the following manually in EdgeOS:

```
-$ configure
-# set interfaces ethernet eth0 dhcp-options name-server no-update
-# commit ; save
-# exit
-$ renew dhcp interface eth0
```

Now the output of resolv.conf is:
```
user@edgerouterx:~$ cat /etc/resolv.conf
# This file is managed by nextdns.
#
# Run "nextdns deactivate" to restore previous configuration.

nameserver 127.0.0.1
```

Theres nothing like typing up an issue and then resolving it yourself! Not sure if you can edit the nextdns deactivate/active commands to show a warning if it detects othernameservers?

**Comment by supernovae** [comment]
Thanks for the great write up, this fixed the issue I was having

**Comment by ryanjoachim** [comment]
This resolved my issue with a fresh install of NextDNS as well!

I had custom DNS addresses set using the webUI prior to installing, and after installing and checking the resolv file it turns out the default Ubiquiti addresses were also still in there.
