### ISSUE TITLE
MacOS not upgrading again...

### ISSUE THREAD

**Issue by ChrisColotti** [nextdns/nextdns#406]
It just runs but does not upgrade.  Removal and re-install does not install the latest version still says it requires upgrade so it's a bit of a loop...

`INFO: LATEST_RELEASE: 1.9.6
u) Upgrade NextDNS from 1.9.4 to 1.9.6
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
NextDNS installed and started using launchd init
u) Upgrade NextDNS from 1.9.4 to 1.9.6
c) Configure NextDNS
r) Remove NextDNS
e) Exit`

MacOS 11.0.1 is the OS version...

Tried on two different laptops running same MacOS and CLI version 1.9.4 with same result as above.

**Comment by yyzguy** [comment]
Likely need to update Xcode command line tools for Big Sur.

**Comment by ChrisColotti** [comment]
@yyzguy had to do that the last time but there was actual errors to indicate it...can try again though good call..

**Comment by yyzguy** [comment]
I can tell you that mine successfully updated to 1.9.6, I don't recall what my previous version was.    I noticed you said MacOS 11.01.    Mine is 11.1   Also, I'm on Intel processor and have updated homebrew.    I'm not smart enough to know if those are required.

**Comment by ChrisColotti** [comment]
@yyzguy MacOS 11.0.1 is the latest but the fact it's the same result on two different machines is very odd...
