### ISSUE TITLE
Nextdns service not enabled for autostart after boot on OpenWRT by default

### ISSUE THREAD

**Issue by spm1001** [nextdns/nextdns#407]
Steps
1. Install luci-app-nextdns on clean install of OpenWRT 19.07.6 (though 19.07.5 and command line install also affected so reporting here)
2. Setup with configuration ID
3. Verify on my.nextdns.io that it’s working
4. Reboot router
5. NextDNS not running (my.nextdns.io shows ISP resolvers), and in luci System>Startup shows Nextdns service as Disabled

**Context**
 - Version: 1.9.6
 - Platform: Edgerouter Lite

**Comment by crssi** [comment]
This problem is real annoyance.

Is there any ETA for resolution?
Is there any workaround to set openwrt to reinit nextdns on bootup?

Thank you and cheers

**Comment by spm1001** [comment]
Sorry I should have said. 

Easy fix - go to System > Startup in browswr interface and in the initscripts tab click Disabled and change it to Enabled. 

Persists over reboot, and up to next service pack at least.

**Comment by crssi** [comment]
Fantastic @spm1001 

Tested now and verified. You really made my day. 😄 ❤️ 
Cheers
