### ISSUE TITLE
-hardened-privacy

### ISSUE THREAD

**Issue by RouterCFW** [nextdns/nextdns#408]
Hello I am using the latest version of Nextdns on asus merlin and for some reason I can’t enable hardened-privacy I have tried and tried but it doesn’t work I believe this is a bug since I tried other commands and they work fine

**Comment by scafroglia93** [comment]
it was removed; it's useless

**Comment by RouterCFW** [comment]
> it was removed; it's useless

It’s wasn’t removed from the router client it’s still an option

**Comment by scafroglia93** [comment]
Have you updated the cli version ?

**Comment by RouterCFW** [comment]
> Have you updated the cli version ?

Yes

**Comment by timkgh** [comment]
The help now says:
```
-hardened-privacy
    	Deprecated.
 ```
 
I would make plans to stop using it.
