### ISSUE TITLE
How to use command line

### ISSUE THREAD

**Issue by Thijxx** [nextdns/nextdns#409]
I try to change a setting using the command line. Specifically I try to turn of the set-router option.

These are all my attempts, the help function is not of any use and the wiki is without any example so I don't know how to actually use the options.

```
nextdns config set setup-router false
nextdns config set setup-router 0
nextdns config set setup-router
nextdns config set setup-router=false
nextdns config set setup-router=0
nextdns -config set setup-router=0
nextdns config set setup-router false
nextdns config set setup-router False
```

**Comment by rs** [comment]
`nextdns config set -option=value`
