### ISSUE TITLE
no feedback from 'nextdns start`

### ISSUE THREAD

**Issue by Thijxx** [nextdns/nextdns#410]
When I run `nextdns start` there is no feedback.
Then when I look at the status it says `not installed` so it definitely needs some feedback to tell me I try to start something and it's impossible.

**Comment by rs** [comment]
What do you get for `nextdns log`

**Comment by Thijxx** [comment]
I fixed it and now I cannot reproduce the state it was in. So maybe turn it into a Feature Request in stead of a bug. The problem was port 53 being used so it did not start but I don't know why it told me it was 'not installed'.

**Comment by Ahmedfaiz919** [comment]
Having same issue after installing it on Linux mint and status is not installed how did you fix it.

**Comment by Fuseteam** [comment]
@Ahmedfaiz919 what does `nextdns log` say?

**Comment by Ahmedfaiz919** [comment]
nextdns log
Jan 31 19:03:22 soulsurfer-ROG-Strix-G531GT-G531GT systemd[1]: Started NextDNS DNS53 to DoH proxy..
Jan 31 19:03:22 soulsurfer-ROG-Strix-G531GT-G531GT nextdns[3285]: Starting NextDNS 1.10.1/linux on :53
Jan 31 19:03:22 soulsurfer-ROG-Strix-G531GT-G531GT nextdns[3285]: Starting mDNS discovery
Jan 31 19:03:22 soulsurfer-ROG-Strix-G531GT-G531GT nextdns[3285]: Listening on TCP/:53
Jan 31 19:03:22 soulsurfer-ROG-Strix-G531GT-G531GT nextdns[3285]: Listening on UDP/:53
Jan 31 19:03:22 soulsurfer-ROG-Strix-G531GT-G531GT nextdns[3285]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
Jan 31 19:03:22 soulsurfer-ROG-Strix-G531GT-G531GT nextdns[3285]: Error: proxy: tcp: listen tcp :53: bind: address already in use
Jan 31 19:03:22 soulsurfer-ROG-Strix-G531GT-G531GT systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
Jan 31 19:03:22 soulsurfer-ROG-Strix-G531GT-G531GT systemd[1]: nextdns.service: Failed with result 'exit-code'.

**Comment by Thijxx** [comment]
> Having same issue after installing it on Linux mint and status is not installed how did you fix it.

I stopped and later removed the application using port 53, please note that in your case this may not be the best solution.

**Comment by Ahmedfaiz919** [comment]
I used the Timeshift to restore. and added the DNS servers manually through network settings.

**Comment by Ahmedfaiz919** [comment]
just reinstalled it today now all working fine with latest version on Linux mint.
