### ISSUE TITLE
Enhanced Parental Controls

### ISSUE THREAD

**Issue by dzg** [nextdns/nextdns#414]
First, thanks for this fantastically executed service. It's great.

I was wondering if you had any plans to expand parental controls, as mentioned at
https://help.nextdns.io/t/g9htq7x/extend-parental-control-functionality

I realize this is free, so I'm not complaining ... but would be great to know if this is something I should consider waiting around for ... or if I'm better off finding another solution.

Thank you!

**Comment by rs** [comment]
This repository is for issues related to the CLI. Please use our help.nextdns.io site for such questions.
