### ISSUE TITLE
NextDNS CLI not working on UDM Pro using version 1.9.0-10 (beta) and 1.8.6 (release)

### ISSUE THREAD

**Issue by RoyalClem** [nextdns/nextdns#418]
Trying to run NextDNS CLI on UDMP after installing version 1.9.0-10 (Beta) or 1.8.6 (Release) NextDNS will not run or activate using newest version of NextDNS CLI.

1.8.6 Release logs - https://community.ui.com/releases/UniFi-Dream-Machine-Firmware-1-8-6/10fa0a66-3391-4f23-a0f6-5a7db8862aa4

Current thinking is that it might be due to dnsmasq being upgraded to 2.83.

**Context**
 - Version [e.g. 1.5.2]: 1.10.1
 - Platform [e.g. macOS, ASUS-Merlin]: UDM Pro

Logs are below, let me know if you need any additional logs:

root@ubnt:/# nextdns log
Feb 09 10:10:54 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
Feb 09 10:10:54 ubnt nextdns[32106]: Starting NextDNS 1.10.1/linux on localhost:53
Feb 09 10:10:54 ubnt nextdns[32106]: Listening on TCP/127.0.0.1:53
Feb 09 10:10:54 ubnt nextdns[32106]: Listening on UDP/127.0.0.1:53
Feb 09 10:10:54 ubnt nextdns[32106]: Startup failed: proxy: tcp: listen tcp 127.0.0.1:53: bind: address already in use
Feb 09 10:10:54 ubnt nextdns[32106]: Error: proxy: tcp: listen tcp 127.0.0.1:53: bind: address already in use
Feb 09 10:10:54 ubnt systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 10:10:54 ubnt ssh[32107]: Warning: Permanently added '127.0.0.1' (RSA) to the list of known hosts.
Feb 09 10:10:55 ubnt ssh[32107]: Welcome to UbiOS
Feb 09 10:10:55 ubnt ssh[32107]: By logging in, accessing, or using the Ubiquiti product, you
Feb 09 10:10:55 ubnt ssh[32107]: acknowledge that you have read and understood the Ubiquiti
Feb 09 10:10:55 ubnt ssh[32107]: License Agreement and agree to be bound by its terms.
Feb 09 10:10:55 ubnt systemd[1]: nextdns.service: Failed with result 'exit-code'.
Feb 09 10:10:55 ubnt systemd[1]: Failed to start NextDNS DNS53 to DoH proxy..
Feb 09 10:11:43 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
Feb 09 10:11:43 ubnt nextdns[735]: Starting NextDNS 1.10.1/linux on localhost:5553
Feb 09 10:11:43 ubnt nextdns[735]: Listening on TCP/127.0.0.1:5553
Feb 09 10:11:43 ubnt nextdns[735]: Starting mDNS discovery
Feb 09 10:11:43 ubnt nextdns[735]: Listening on UDP/127.0.0.1:5553
Feb 09 10:11:44 ubnt ssh[736]: Welcome to UbiOS
Feb 09 10:11:44 ubnt ssh[736]: By logging in, accessing, or using the Ubiquiti product, you
Feb 09 10:11:44 ubnt ssh[736]: acknowledge that you have read and understood the Ubiquiti
Feb 09 10:11:44 ubnt ssh[736]: License Agreement and agree to be bound by its terms.
Feb 09 10:11:44 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
Feb 09 10:11:48 ubnt nextdns[735]: Setting up router
Feb 09 10:11:49 ubnt nextdns[735]: Activating
Feb 09 10:11:49 ubnt nextdns[735]: Activate: setup resolv.conf: rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy

root@ubnt:/# nextdns activate
Error: setup resolv.conf: rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy

root@ubnt:/# nextdns version 
nextdns version 1.10.1
root@ubnt:/#

**Comment by RoyalClem** [comment]
any more logs or anything so that I can get some help to get this working?

**Comment by rs** [comment]
Don’t use activate on UDM, it won’t work and it is not necessary on a router.

**Comment by RoyalClem** [comment]
So just to confirm - this is the correct config below, correct? 

Router config used to work on UDNP until newest update, and now I need to configure dns manual per network device or else it doesn't use NextDNS's DNS server. this is different compared to how it was before recent UDMP firmware update.

root@ubnt:/# nextdns config
log-queries false
report-client-info true
discovery-dns 
detect-captive-portals false
bogus-priv true
setup-router true
control /var/run/nextdns.sock
config mynextdnsid
cache-max-age 0s
timeout 5s
auto-activate true
listen localhost:53
hardened-privacy false
cache-size 10MB
max-ttl 5s
use-hosts true
root@ubnt:/#
