### ISSUE TITLE
Best way to install as service?

### ISSUE THREAD

**Issue by dzg** [nextdns/nextdns#419]
I installed as per https://github.com/nextdns/nextdns/wiki/MacOS ... but this then needs to be `start`ed manually each time.

What's the best way to install as a service/daemon/launch agent?

Does someone have a `.plist`?

Would be nice to include that in the above wiki page.

Thanks

**Comment by rs** [comment]
It should have to be started manually. It is installed as a launchd service. What do you get for `sudo nextdns status`?

**Comment by dzg** [comment]
```
$ sudo nextdns status
running
```

But there is nothing `nextdns` in `launchctl list`

Can't it be set to start automatically?

**Comment by rs** [comment]
It is set to run automatically.

**Comment by rs** [comment]
Please check `sudo launchctl list|grep nextdns`, if it is not listed or the status of nextdns is not running on reboot, please reopen.
