### ISSUE TITLE
Support for users of FreeBSD

### ISSUE THREAD

**Issue by grahamperrin** [nextdns/nextdns#42]
Might https://github.com/nextdns/nextdns/blob/master/README.md be updated for a FreeBSD audience?

**Comment by rs** [comment]
It will very soon all be replaced by a curl|sh script that do the right thing for your system.

**Comment by rs** [comment]
Fixed by v1.4.0

**Comment by grahamperrin** [comment]
👍 noted with thanks: 

* https://github.com/nextdns/nextdns/commit/54243b6943366304b3d7e38db3971b1ec3c2fd13#diff-04c6e90faac2675aa89e2176d2eec7d8R23 in `README.md` (sorry – overlooked when raising this issue – I guess that my eyes were drawn more to the installation section https://github.com/nextdns/nextdns/commit/54243b6943366304b3d7e38db3971b1ec3c2fd13#diff-04c6e90faac2675aa89e2176d2eec7d8R35 than the supported systems section)
* https://github.com/nextdns/nextdns/commit/4d48e52b8e572eb4c01232546136836ed1787c7b for the script
* https://github.com/nextdns/nextdns/wiki/FreeBSD and FreeBSD bug [242752 – New port: dns/nextdns NextDNS DNS53 to DNS over HTTPS proxy](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242752)

**Comment by grahamperrin** [comment]
Posted to Reddit: 

* [NextDNS CLI client – DNS over HTTPS (DoH) proxy – support for BSDs : freebsd](https://www.reddit.com/r/freebsd/comments/ejbob1/nextdns_cli_client_dns_over_https_doh_proxy/)
