### ISSUE TITLE
Hardened privacy please

### ISSUE THREAD

**Issue by RouterCFW** [nextdns/nextdns#421]
I thought I was the only one who wanted it back but a lot of people do I don’t see why it was removed i loved it that’s one of the only reasons I bought a Nextdns subscription 
https://cdn.discordapp.com/attachments/810548079748317194/810548115748552744/image0.png

**Comment by crssi** [comment]
What is "Hardened DNS mode"?

**Comment by RouterCFW** [comment]
> What is "Hardened DNS mode"?

It’s a mode which sends your dns traffic to strict privacy countries
