### ISSUE TITLE
IPv6 not going through NextDNS CLI on UDM

### ISSUE THREAD

**Issue by crwban** [nextdns/nextdns#422]
Not sure if this is a bug report, or a feature request, but anyway...

With IPv6 enabled on my UDM (Base, not Pro), devices on my network with IPv6 addresses end up querying Cloudflare's DNS servers as this is the fallback for the UDM (if you don't set any ipv6 dns servers yourself).

Looking at [router/ubios/setup.go](https://github.com/nextdns/nextdns/blob/master/router/ubios/setup.go), I can see that rules are only setup with iptables.

So, I wanted to ask if IPv6 is supposed to be supported in this way on the UDM, or whether the current implementation was intentionally IPv4 only? 

If it's the latter, I'm happy to try submitting a PR...

**Comment by trilantis** [comment]
Just set up the NextDNS client on my UDM-Pro and am running into the same issue. Ended up turning off IPv6 for now, since configuration is fairly limited on these devices.

**Comment by boosting1bar** [comment]
Same issue here on UDMP.  Hopefully this will be added with an update soon.

**Comment by mlapida** [comment]
+1

**Comment by ISSkiGeek** [comment]
+1

**Comment by mlapida** [comment]
[This solutions posted](https://help.nextdns.io/t/60htjnn?r=y4hzdnf) to the help section worked for me. Basically using the IPv6 version of the UDM IPv4 address will successfully resolve IPv6 traffic. You'll just need to add the converted IPv6 address to the DHCPv6/RDNSS settings for the local network.

**Comment by crwban** [comment]
The solution in that post doesn't seem to work for me - and I didn't think you could convert ipv4 addresses to ipv6 like that. As a test for this, 'ping6 <converted address>' doesn't work (for me).

What this _does_ do in my setup is stop things pointing to cloudflare by providing broken ipv6 dns info, which then forces everything through ipv4 dns resolution (as a fallback). @mlapida is ipv6 resolution definitely working for you? (something like 'dig -6 www.google.com' will tell you...)

**Comment by mlapida** [comment]
When I run `$ dig AAAA google.com @::ffff:10.0.0.1` it returns the IPv6. I'm seeing AAAA resolutions in my raw NextDNS logs, and when I load [IPv6 Test](https://ipv6-test.com) it reports back that DNS for IPv6 is working correctly. I also see IPv6 addresses registered to devices from the NextDNS CLI (`$ nextdns discovered`). I see no indication that it's falling back. 

The only thing that seems odd is the relatively high query time.

Full dig output:
```
$ dig AAAA google.com @::ffff:10.0.0.1

; <<>> DiG 9.10.6 <<>> AAAA google.com @::ffff:10.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13847
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	AAAA

;; ANSWER SECTION:
google.com.		5	IN	AAAA	2607:f8b0:4003:c05::64
google.com.		5	IN	AAAA	2607:f8b0:4003:c05::71
google.com.		5	IN	AAAA	2607:f8b0:4003:c05::8b
google.com.		5	IN	AAAA	2607:f8b0:4003:c05::66

;; Query time: 44 msec
;; SERVER: ::ffff:10.0.0.1#53(::ffff:10.0.0.1)
;; WHEN: Fri Feb 26 07:52:51 MST 2021
;; MSG SIZE  rcvd: 151
```

**Comment by crwban** [comment]
You're right, thanks! And I've now been able to replicate your results.

I think I'm intermittently having issues with the IPv6 address not propagating from ppp0 to br0 on my UDM which is breaking things for me... and am pretty sure these aren't related to nextdns.
