### ISSUE TITLE
NextDNS and Smart DNS (georestricted content)

### ISSUE THREAD

**Issue by sqwal** [nextdns/nextdns#423]
Hi,

Would there be a way to use another DNS for a specific device on my network, or for specific addresses, without having to cancel the use of NextDNS?

I'm using NextDNS on a Synology router, but some devices have a Smart DNS set instead of NextDNS, in order to access georestricted content. I'd like to know if there is a way for these devices to use the Smart DNS for some services (Netflix, BBC...), but to use NextDNS for everything else...

Or... an option to add a Smart DNS directly inside NextDNS, for using geo restricted content ;-)

**Comment by rs** [comment]
You can use split horizon to point the wanted domains to your smart dns: https://github.com/nextdns/nextdns/wiki/Split-Horizon
