### ISSUE TITLE
Supress Connected message in syslog

### ISSUE THREAD

**Issue by jkcapoeira** [nextdns/nextdns#425]
Hi,
i like NextDNS, and it is working also great on my OpenWRT router. However i noticed that there are a lot of Connected loggings in my syslog. Almost like every minute. 

It is coming from this code in Run.go at line 445
```
	OnConnect: func(ci *endpoint.ConnectInfo) {
			log.Infof("Connected %s (con=%dms tls=%dms, %s)",
				ci.ServerAddr,
				ci.ConnectTimes[ci.ServerAddr]/time.Millisecond,
				ci.TLSTime/time.Millisecond,
				ci.TLSVersion)
```
Is this standard or is it because of my nginx configuration or another setup i did wrong?
If it is by design, can we have an option to supress this?
Thanks.

**Comment by BrianG61UK** [comment]
I agree. There needs to be a way to disable this.
