### ISSUE TITLE
Why making UDM only capturing DNS traffic directed at the router?

### ISSUE THREAD

**Issue by sanyer** [nextdns/nextdns#426]
Hi @rs !
First of all, thanks for your service and huge effort in this repo. 

I have UDM Base and running nextdns 1.9.4 and so far it has been working flawlessly, easily survived a dozen of firmware upgrade and gave me zero issues.
Today I found out that there are a couple of new release and found 1.9.5 "Make UDM only capturing DNS traffic directed at the router"

Could you please provide more context behind this change? So far it has been quite useful to catch all DNS packets, mostly because of Google devices (Chromecast, Nest Hub etc) talking to their hardcoded DNS. I was using my own iptables rules before nextdns for capturing those and was quite happy to see nextdns following every request.

**Comment by rs** [comment]
It’s to make it consistent with other routers integration. Ideally, capture all DNS traffic should be a separate opt-in feature.

**Comment by sanyer** [comment]
Makes sense.
Do you have capturing all DNS traffic in plans? Or at least tracked as a feature-request? I can add one.

**Comment by rs** [comment]
It’s planned yes

**Comment by Belphemur** [comment]
@sanyer I've encountered the same problem.

You can already reenable the feature with the latest version, it just needs a couple of tweaks in the config of nextdns and the systemd service.

1. ssh into UDM
2. Stop nextdns `nextdns stop`
3. edit the file /data/nextdns.conf
4. set `setup-router false` & `listen localhost:5553`
5. run the `unifi-os shell` command
6. edit the systemd service with `systemctl edit nextdns`
7. Paste this content & save
```
[Service]
ExecStartPost=ssh -oStrictHostKeyChecking=no 127.0.0.1 iptables -t iptables -t nat -N NEXTDNS
ExecStartPost=ssh -oStrictHostKeyChecking=no 127.0.0.1 iptables -t nat -A NEXTDNS -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.1:5553
ExecStartPost=ssh -oStrictHostKeyChecking=no 127.0.0.1 iptables -t nat -A NEXTDNS -p tcp -m tcp --dport 53 -j DNAT --to-destination 127.0.0.1:5553
ExecStartPost=ssh -oStrictHostKeyChecking=no 127.0.0.1 iptables -t nat -I PREROUTING -j NEXTDNS
ExecStop=ssh -oStrictHostKeyChecking=no 127.0.0.1 iptables -t nat -D PREROUTING -j NEXTDNS
ExecStop=ssh -oStrictHostKeyChecking=no 127.0.0.1 iptables -t nat -F NEXTDNS
ExecStop=ssh -oStrictHostKeyChecking=no 127.0.0.1 iptables -t nat -X NEXTDNS
```
8. start nextdns `nextdns start`

Enjoy, now all the DNS traffic is redirected to nextdns

**Comment by sanyer** [comment]
@Belphemur yeah, that should do it for now. Thanks :-)

**Comment by Belphemur** [comment]
Yep it didn't. I've actually gone further ahead and installed: https://github.com/boostchicken/udm-utilities/tree/master/on-boot-script

With my own systemd service file to be run after nextdns

https://gist.github.com/Belphemur/f5f5afd19116ee17d4498f5ad87386a3

This way it survives reboot and firmware update

**Comment by magnuslsjoberg** [comment]
Please consider this request when upgrading your script to support Unifi 2.4.23
