### ISSUE TITLE
NextDNS function like YogaDNS

### ISSUE THREAD

**Issue by 8227846265** [nextdns/nextdns#431]
Hi, I would like to suggest to make NextDNS function like YogaDNS but for NextDNS specifically.

One of the biggest problem with the official Windows app is that it doesn't when a VPN app is installed and running.

It would be a very good customer experience to have the official app can run alongside the VPN of choice of the customer.

**Comment by rs** [comment]
This will be fixed by the next revision of Windows which comes with the support of DoH. Our apps is already updated to use this new feature.
