### ISSUE TITLE
'Error Unhandled "mismatch" case.'

### ISSUE THREAD

**Issue by dzg** [nextdns/nextdns#436]
config is set via MAC address on router, yet "Setup" in Web UI says 
`'Error Unhandled "mismatch" case.'`

![image](https://user-images.githubusercontent.com/466557/110881762-bbf3ff00-8295-11eb-802b-5e80e268d923.png)

**Context**
 - Version: 1.11.0
 - Platform: ASUS-Merlin

**Comment by rs** [comment]
What do you get for https://test.nextdns.io

**Comment by dzg** [comment]
> What do you get for https://test.nextdns.io
```
{
	"status": "ok",
	"protocol": "DOH",
	"client": "172.250.65.171",
	"destIP": "162.220.221.25",
	"anycast": false,
	"server": "anexia-lax-1",
	"clientName": "chromium-default"
}
```

**Comment by dzg** [comment]
Also my Roku ... which is setup via config/MAC address ... its activity is showing up in logs for the Router config, not the Roku config.

**Comment by rs** [comment]
Please try disabling DoH in chrome.

**Comment by rs** [comment]
Closing as it is not a CLI issue. If the problem persists, please open a thread on https://help.nextdns.io.
