### ISSUE TITLE
exclude wifi with cli?

### ISSUE THREAD

**Issue by kurktchiev** [nextdns/nextdns#439]
I am digging around the Wiki and cannot find a way for me to exclude running nextdns over my wifi when at home on my laptop where i have the CLI running as I am using some of the advanced features. Is it not possible or just not documented or?

**Comment by rs** [comment]
This is not supported by the CLI.

**Comment by thob** [comment]
It would be great if the CLI supports excluding several Wifis. I have it installed on several notebooks (for different peeps)  but only want it to run outside 2 Wifis.
