### ISSUE TITLE
Installer not compatible with VMware Photon OS

### ISSUE THREAD

**Issue by jrothlis** [nextdns/nextdns#442]
When trying to install NextDNS cli on Photon OS, I get the following:

root@photon [ ~ ]# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
ERROR: Unsupported OS: Linux
ERROR: Unknown bin location for 
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: 
INFO: LATEST_RELEASE: 1.11.0
ERROR: Cannot detect running environment.
root@photon [ ~ ]# 

I can force it to install using this command:

FORCE_OS=rhel sh -c "$(curl -sL https://nextdns.io/install)"

... but nextdns upgrade fails (and I haven't figured out how to make it work):

root@photon [ ~ ]# nextdns upgrade
ERROR: Unsupported OS: Linux
ERROR: Unknown bin location for 
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: 
INFO: LATEST_RELEASE: 1.11.0
ERROR: Cannot detect running environment.
Error: exit status 1
root@photon [ ~ ]# 

**Context**
 - Version: 1.10.1, 1.11.0
 - Platform: VMware Photon OS 4.0

Photon OS is an extremely lightweight Linux designed for VMs:
https://vmware.github.io/photon/

There is an additional problem (which I resolved by Googling) where systemctl has control of port 53 so NextDNS can't start. This is fixed like so:

sed -i -r 's/^#?DNSStubListener=.*/DNSStubListener=no/' /etc/systemd/resolved.conf
ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
systemctl restart systemd-resolved.service

**Comment by rs** [comment]
What’s the output of `cat /etc/os-release`?

**Comment by jrothlis** [comment]
root@photon [ ~ ]# cat /etc/os-release
NAME="VMware Photon OS"
VERSION="4.0"
ID=photon
VERSION_ID=4.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
root@photon [ ~ ]#

**Comment by rs** [comment]
Support for this distribution need to be added.

**Comment by jrothlis** [comment]
Happy to test, let me know what you need.

**Comment by jrothlis** [comment]
Still not fixed as of 1.33.2

root@dns01 [ ~ ]# nextdns upgrade
ERROR: Unsupported OS: Linux
ERROR: Unknown bin location for 
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: 
INFO: LATEST_RELEASE: 1.33.2
ERROR: Cannot detect running environment.
Error: exit status 1
root@dns01 [ ~ ]#

**Comment by Encryptz** [comment]
You can force it same way as when installing

FORCE_OS=rhel nextdns upgrade
