### ISSUE TITLE
Disable/block/drop IPV6 queries for IPV4 entries found in the hosts file

### ISSUE THREAD

**Issue by Groofster** [nextdns/nextdns#443]
Right now when a DNS query is done for an internal FQDN, nextdns forwards the IPV6 query to nextdns for all entries that are only available via the hosts file with IPV4 IP's only.

This has 2 implications:

1. the internal domain is forwarded and logged (leaked) to nextdns, no matter how hard you try to have all important FQDN's in the hosts file (or in a forwarder that does not do IPV6 either).
2. a query for such a FQDN will give a response with both the IPV4 IP in it, but also a NXDOMAIN response for the IPV6 query. This then results in a return value other then 0 making tools like fping/nslookup fail on this resolution.

See this response:

~# nslookup server.internaldomain.com        
Server:         10.x.x.x
Address:        10.x.x.x#53

Non-authoritative answer:
Name:   server.internaldomain.com
Address: 10.x.x.y
** server can't find server.internaldomain.com: NXDOMAIN

~# echo $?
1

Since a lot of people will be running IPV4 only in their internal network for a little bit longer, it would be nice to have a way of disabling/blocking/dropping this behaviour.

If there is anyone who has an idea how to fix this with the current configuration options, please let me know.

Running nextdns on a Debian server.

**Comment by ThePowerOfDreams** [comment]
I feel that this has important privacy and security implications and that @Groofster raises an important point.

**Comment by Groofster** [comment]
Having the possibility to add an empty forwarder for a domain, meaning no forwarding (so hosts file only) would be a simple and clean option. Something like:

forwarder mydomain.com=#
