### ISSUE TITLE
Periodically rotate HTTPS or TLS keys

### ISSUE THREAD

**Issue by malehumanperson** [nextdns/nextdns#447]
Can the NextDNS team please consider implementing an option in each OS’s NextDNS program and to the DNS resolver custom configuration script used in firewall routers—pfSense, OPNSense—that would specify an interval between rotating the encryption keys used to secure the TLS or HTTPS session by renegotiating the connection or another mechanism (can the keys be force rotated without renegotiating the connection?).

DNSCrypt has a feature to renegotiate the TLS keys after each DNS query on routers—which I feel is excessive. A more processor conservative implementation could set the minimum interval to an hour—with longer options as well; such as: 1, 2, 4, 8, 12, and 24 hour key renegotiation options. Instead of specifying a static temporal interval—the keys could also be renegotiated after a set number of DNS requests; such as: 50, 100, 250, or 500.

This feature would further enhance the security of encrypted DNS requests.

Thank you

**Comment by rs** [comment]
New keys are exchanged during TLS handshake. TLS resumption is used used so this does not happen on each new connection. Our servers rotate their TLS session keys every 24 hours and their certificate private key every 30 days.
