### ISSUE TITLE
Clickable Drilldown Report to Breakout Blocked DNS Requests

### ISSUE THREAD

**Issue by malehumanperson** [nextdns/nextdns#448]
Please consider enhancing the functionality of the Analytics Section->Blocked Reasons portion of the website by making each blocked reason clickable to expand a drilldown report listing each domain that was blocked, and the number of times it was blocked by each DNS filter. This would be very informative and helpful.

![2021-04-08 23_53_14-Analytics - Router-Firewall - NextDNS and 19 more pages - Profile 1 - Microsoft​](https://user-images.githubusercontent.com/48421304/114135635-befb0300-98c6-11eb-98ff-774561bf6a5c.png)

**Comment by rs** [comment]
Please use https://help.nextdns.io
