### ISSUE TITLE
Option to Block IPv6 DNS Requests

### ISSUE THREAD

**Issue by malehumanperson** [nextdns/nextdns#449]
Please consider implementing a feature to block IPv6 DNS requests for users that do not want IPv6 traffic on their network. Adding this feature would be a 'belt-and-suspenders' approach that NextDNS users can take when they can't—or don't want to—turn off IPv6 on each device connecting to their network, or block all IPv6 traffic at their firewall.

[Until one day in the future when the world runs out of IPv4 webhosting address space and some websites cannot be served over an IPv4 DNS address.]

Would implementing this feature as a toggle switch on the website break any websites that are currently only served over IPv6?

Thank you.

**Comment by rs** [comment]
Please use https://help.nextdns.io for such feature request. This repo is for the CLI client.
