### ISSUE TITLE
It's possible add uBlock filter list? 

### ISSUE THREAD

**Issue by peter9811** [nextdns/nextdns#450]
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt

I tried check it on https://adblock-tester.com/, but I don't get more that 60 points

**Comment by peter9811** [comment]
And maybe this too, please

http://sbc.io/hosts/hosts
http://sysctl.org/cameleon/hosts
https://gnuzilla.gnu.org/filters/blacklist.txt
https://openphish.com/feed.txt
https://raw.githubusercontent.com/Lerist/Go-Hosts/master/hosts-ad
https://raw.githubusercontent.com/bjornstar/hosts/master/hosts
https://raw.githubusercontent.com/vokins/yhosts/master/hosts.txt
https://raw.githubusercontent.com/yous/YousList/master/hosts.txt
https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
https://v.firebog.net/hosts/static/w3kbl.txt

**Comment by rs** [comment]
Please use https://github.com/nextdns/metadata for those types of requests.
