### ISSUE TITLE
Update command error.

### ISSUE THREAD

**Issue by cocoflan** [nextdns/nextdns#452]
Get this errors when doing apt update.

 Failed to fetch https://nextdns.io/repo/deb/dists/stable/InRelease 403 Forbidden [IP: 35.156.125.116 443]
E: The repository 'https://nextdns.io/repo/deb stable InRelease' is no longer signed.

N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details. 

How to fix this?

**Comment by konomith** [comment]
It seems that bintray (which nextdns uses for distributing the deb packages) is reaching [EOL](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), and they have a [scheduled](https://status.bintray.com/) interruption today (April 12th 6AM to 2PM Pacific Daylight Time.)

**Comment by cocoflan** [comment]
Ok Thx for the info.

**Comment by rs** [comment]
We're working on migrating to an in-house solution before the date.
