### ISSUE TITLE
Add IPv6 address to cert SANs

### ISSUE THREAD

**Issue by Mosney** [nextdns/nextdns#454]
I set NextDNS IPv6 address as AdGuardHome upstream via DoT/DoH, but found a question, its cert not contain those IPv6 address so that query will fail due to cert validate error. See https://github.com/AdguardTeam/AdGuardHome/discussions/2921#discussioncomment-572978

And another problem is NextDNS is hard to connect in China, authorities block DoT port  853 totally and interference DoH query too. That's why I have to touch NextDNS via IPv6 too. And I found some suggestions in social media, here is one: https://twitter.com/IceCode8964XI/status/1379413624247054338 So please consider do something.

**Comment by rs** [comment]
You can use `<random>.dns.nextdns.io` to workaround GFW. We do not plan to add IPs in our certs, as it is currently not supported by our CA.

Closing as this is not a ticket related to our CLI.

**Comment by Mosney** [comment]
@rs According my side multiple test, only DNS over HTTPS work for less than 1 minutes, then NextDNS's IP will go in blackhole cannot reach anymore, a period of time goes, it becomes available again, and so it repeats. You can see configuration `daaa2d` , I deploy this(https://dns.nextdns.io/daaa2d/) on my DNS upstream, you can see how many query blocked, most queries will not have a chance to reach NextDNS.

![image](https://user-images.githubusercontent.com/22477230/114728115-636ec080-9d71-11eb-9f46-69bb74b188e2.png)

**Comment by Mosney** [comment]
From now on, I'll test `<random>.dns.nextdns.io` on DoT/H, I'll be back in a week with the results.
