### ISSUE TITLE
NextDNS listening on :53 even when configured otherwise

### ISSUE THREAD

**Issue by DerekSeaman** [nextdns/nextdns#455]
On FreeBSD (OPNSense platform), I've configured NextDNS to listen only on localhost:5353. However, when running sockstat -l, NextDNS is still listening on port 53 and :5353.

USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     nextdns    20519 8  stream /var/run/nextdns.sock
root     nextdns    20519 9  udp4   *:5353                *:*
root     nextdns    20519 10 tcp46  *:53                  *:*
root     nextdns    20519 11 udp6   *:5353                *:*
root     nextdns    20519 12 udp46  *:53                  *:*
root     nextdns    20519 13 udp4   *:5353                *:*
root     nextdns    20519 14 udp6   *:5353                *:*
root     nextdns    20519 15 udp4   *:5353                *:*
root     nextdns    20519 16 udp6   *:5353                *:*
root     nextdns    20519 17 udp4   *:5353                *:*
root     nextdns    20519 18 udp6   *:5353                *:*

This is my config:
detect-captive-portals false
use-hosts true
auto-activate true
control /var/run/nextdns.sock
config xxxxxx
max-ttl 5s
listen localhost:5353
setup-router true
log-queries false
cache-max-age 0s
report-client-info true
hardened-privacy false
bogus-priv true
timeout 5s
cache-size 10MB
discovery-dns

When NextDNS is listening on 53, it is causing a port conflict with Unbound. I see no way to force NextDNS to only use the port(s) I specify. 

**Context**
 - Version [e.g. 1.5.2]: 1.11.0
 - Platform [e.g. macOS, ASUS-Merlin]: FreeBSD

**Comment by rs** [comment]
Set setup-router to false. This directive ignores listen value.
