### ISSUE TITLE
UDM-Pro Requests not always DNSoHTTPS

### ISSUE THREAD

**Issue by ChrisColotti** [nextdns/nextdns#456]
I am seeing some log entries with the same course IP of the UDM-Pro external IP but some are secure and others are not.  I am not sure why some would be and others would not be.

![image](https://user-images.githubusercontent.com/25350142/115020324-70ca9e80-9e88-11eb-9bf9-ef74726bdeea.png)

INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: LATEST_RELEASE: 1.11.0

All the other devices passing through the UDM are encrypted with the device name as well.  Any thoughts?

With the USG the WAN DNS used to be set to 12.0.0.1 but on the UDM that does not work, so it's been set to the NextDNS servers at the WAN network config all along which is the only config that works, but this odd inconsistency I can't figure out.

Although they look like they could be some docker containers, but those should be using the docker host's DNS but now I have to dig a little more.

**Comment by rs** [comment]
UDM does not let the cli change the local resolv.conf, so queries coming from the router itself aren’t encrypted.

**Comment by ChrisColotti** [comment]
@rs that makes sense but looking at the destinations it could very well be some of the containers I have...so I can dig a little more on that side too..

**Comment by ChrisColotti** [comment]
yeah looks like I needed to alter the docker compose files on a few to add a DNS option and now the docker host name is showing as the requester and it's encrypted.
