### ISSUE TITLE
Installation of CLI on UDM does not allow queries from Guest network

### ISSUE THREAD

**Issue by KilometerM** [nextdns/nextdns#457]
&lt;Describe the bug>

After installing the NextDNS CLI on my UDM by following the instructions here on Github, no DNS server can be reached from the Guest network when DHCP points DNS at the router itself (set to auto). 

After troubleshooting this issue, it appears this is because the Guest network on UDM by default only allows traffic directed to the router over ICMP, standard DNS ports, and DHCP ports. 

I was able to resolve this by adding a FW rule under GUEST LOCAL allowing traffic to the router over port 5553 TCP and UDP. Now queries reach the CLI and are resolved successfully.

This may be a known issue and unable to be resolved with the installation script, but if so, maybe it should be noted in the UDM instructions?

![image](https://user-images.githubusercontent.com/65037176/115057138-eb071d00-9ea0-11eb-832e-27bf277ce5d5.png)

**Context**
 - Version [e.g. 1.5.2]: 1.11.0
 - Platform [e.g. macOS, ASUS-Merlin]: UDM

**Comment by rs** [comment]
It should work with default settings. If you enable the `setup-router` option (done by default by the install script), a special iptables rule will be added to forward all traffic targeted private blocks to the local nextdns instance. This should capture all the DNS traffic targeted the UDM on port 53 and send it to nextdns CLI. This rule won't appear in the UI though.

Before changing the default setting, make sure it does not work by just rebooting the UDM.

**Comment by KilometerM** [comment]
Thanks for the response. I did reboot as my first troubleshooting effort before changing anything. To be clear, all of my corporate networks worked right away without any changes. Only the guest network was affected, because it appears default Guest network rules only allow ICMP and udp/tcp to 53 and 67/68. So the redirect to 5553 did not work on guest network until I added the rule referenced in the screenshot.

I have not changed anything in the nextdns default config set by the installer.

**Comment by rs** [comment]
Oh ok, make sense, I missed the "guest network" part.

**Comment by oviliz** [comment]
@KilometerM , do you have any Guest devices in the NextDNS's UI Logs?
I also have an UDM and can't see any of the Guest devices in the logs although my NextDNS config for the Guest IP range points to the correct ID.

**Comment by KilometerM** [comment]
Yes, I actually do see logs and the device name for the devices on my guest network. Sorry I’m not more help there. 

Did you have to make any changes like the ones I reference in this topic to get your guest network to function with the NextDNS CLI?

**Comment by adrianrudnik** [comment]
Just experienced the same. Guest wifi network routed through a guest network became unusable due to the DNS not being reachable/reacting. Added the mentioned routes for guest and guestv6 and had to reboot to get the correct routing.
