### ISSUE TITLE
V1.12.1 the log maybe little broken on Raspbian

### ISSUE THREAD

**Issue by cutmann** [nextdns/nextdns#466]
Hello,
since the upgrade the following spam the logs (true true true or in all other variants with true or  false)

nextdns log
Apr 19 23:20:48 systemd[1]: Started NextDNS DNS53 to DoH proxy..
Apr 19 23:20:48 nextdns[393]: Starting NextDNS 1.12.1/linux on :53
Apr 19 23:20:48 nextdns[393]: Starting mDNS discovery
Apr 19 23:20:48 nextdns[393]: Listening on TCP/:53
Apr 19 23:20:48 nextdns[393]: Listening on UDP/:53
Apr 19 23:20:52 nextdns[393]: Connected 45.90.28.0:443 (con=19ms tls=394ms, TCP, TLS13)
Apr 19 23:20:52 nextdns[393]: true true false
Apr 19 23:20:52 nextdns[393]: Connected 45.90.28.0:443 (con=15ms tls=35ms, TCP, TLS13)
Apr 19 23:20:52 nextdns[393]: Switching endpoint: https://dns.nextdns.io.#45.90.28.0,2a07:a8c0::
Apr 19 23:20:52 nextdns[393]: true true false
Apr 19 23:20:52 nextdns[393]: true true false
Apr 19 23:20:52 nextdns[393]: true true false
Apr 19 23:20:53 nextdns[393]: Setting up router
Apr 19 23:20:53 nextdns[393]: Activating
Apr 19 23:21:10 nextdns[393]: true true true
Apr 19 23:21:11 nextdns[393]: true true true
... always repeat the same ...
Apr 19 23:22:54 nextdns[393]: true true false
Apr 19 23:23:23 nextdns[393]: Connected 45.90.28.0:443 (con=17ms tls=58ms, TCP, TLS13)

i think is should be not normal

**Comment by cutmann** [comment]
with the latest version is the problem fixed. I see no more the spam in the log. Thanks for the fast solving.

**Comment by elkiehound** [comment]
Why do I keep getting these?  I am unsubscribed from thread.
