### ISSUE TITLE
OpenWRT install issue 18.06

### ISSUE THREAD

**Issue by kuwwoon** [nextdns/nextdns#47]
![Capture](https://user-images.githubusercontent.com/59504854/71765479-0b0a0b80-2efe-11ea-8909-584e92813765.PNG)
I tried to use the approach
https://github.com/nextdns/nextdns/wiki/OpenWRT

**Comment by rs** [comment]
What do you have in `/etc/os-release`?

**Comment by kuwwoon** [comment]
NAME="OpenWrt"                                                                                                          VERSION="18.06.5"                                                                                                       ID="openwrt"                                                                                                            ID_LIKE="lede openwrt"                                                                                                  PRETTY_NAME="OpenWrt 18.06.5"                                                                                           VERSION_ID="18.06.5"                                                                                                    HOME_URL="http://openwrt.org/"                                                                                          BUG_URL="http://bugs.openwrt.org/"                                                                                      SUPPORT_URL="http://forum.lede-project.org/"                                                                            BUILD_ID="r7897-9d401013fc"                                                                                             LEDE_BOARD="ramips/mt7620"                                                                                              LEDE_ARCH="mipsel_24kc"                                                                                                 LEDE_TAINTS=""                                                                                                          LEDE_DEVICE_MANUFACTURER="OpenWrt"                                                                                      LEDE_DEVICE_MANUFACTURER_URL="http://openwrt.org/"                                                                      LEDE_DEVICE_PRODUCT="Generic"                                                                                           LEDE_DEVICE_REVISION="v0"                                                                                               LEDE_RELEASE="OpenWrt 18.06.5 r7897-9d401013fc"

**Comment by rs** [comment]
Please test with:

`sh -c “$(curl -sL https://raw.githubusercontent.com/nextdns/nextdns/master/install.sh)”`

**Comment by kuwwoon** [comment]
It's been run, I do not see NextDNS as added Resolver in DNS Over HTTPS Proxy Settings. I supposed I would find it there.

**Comment by rs** [comment]
There is no UI for now
