### ISSUE TITLE
Does nextdns cli support QUIC?

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#470]
In the latest 1.12.5 version I see this in the log:

`... (con=10ms tls=11ms, TCP, TLS13)`

NextDNS servers seem to support DNS over QUIC. Is there a way to configure the cli to use it?

**Comment by rs** [comment]
HTTP/3 is currently only available on http3.dns.nextnds.io, cli will automatically get it when we enable it on dns.nextdns.io.

**Comment by jinkang23** [comment]
> HTTP/3 is currently only available on http3.dns.nextnds.io, cli will automatically get it when we enable it on dns.nextdns.io.

It's been almost a year since this reply. When will QUIC be enabled in the cli?

**Comment by Kamek437** [comment]
Bump.

> > HTTP/3 is currently only available on http3.dns.nextnds.io, cli will automatically get it when we enable it on dns.nextdns.io.
> 
> It's been almost a year since this reply. When will QUIC be enabled in the cli?

Bump?
