### ISSUE TITLE
OSX El capitan

### ISSUE THREAD

**Issue by cocoflan** [nextdns/nextdns#471]
Unhandled case where "resolver" is not present. when trying to run nextdns tool and browser.

**Comment by rs** [comment]
Please provide more context on how to reproduce the issue and on what the issue is exactly (expected vs reality).

**Comment by cocoflan** [comment]
Ok it is on a system of a friend, wil ask him to send me some more info soon.

Greetings

**Comment by rs** [comment]
Closing for now, please reopen when you have more context.
