### ISSUE TITLE
"E: Unable to locate package nextdns" on UDM 1.9.3

### ISSUE THREAD

**Issue by ghost** [nextdns/nextdns#477]
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: LATEST_RELEASE: 1.32.0

Unifi Dream Machine running 1.9.3

Is this just me or is there really an issue pulling repos right now?

INFO: Installing NextDNS...
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
Ign:1 https://dl.bintray.com/nextdns/deb stable InRelease
Ign:2 https://dl.bintray.com/nextdns/deb stable Release
Ign:3 https://dl.bintray.com/nextdns/deb stable/main all Packages
Ign:4 https://dl.bintray.com/nextdns/deb stable/main arm64 Packages
Ign:3 https://dl.bintray.com/nextdns/deb stable/main all Packages
Ign:4 https://dl.bintray.com/nextdns/deb stable/main arm64 Packages
Ign:3 https://dl.bintray.com/nextdns/deb stable/main all Packages
Ign:4 https://dl.bintray.com/nextdns/deb stable/main arm64 Packages
Ign:3 https://dl.bintray.com/nextdns/deb stable/main all Packages
Ign:4 https://dl.bintray.com/nextdns/deb stable/main arm64 Packages
Ign:3 https://dl.bintray.com/nextdns/deb stable/main all Packages
Ign:4 https://dl.bintray.com/nextdns/deb stable/main arm64 Packages
Ign:3 https://dl.bintray.com/nextdns/deb stable/main all Packages
Err:4 https://dl.bintray.com/nextdns/deb stable/main arm64 Packages
  403  Forbidden
Reading package lists...
W: The repository 'https://nextdns.io/repo/deb stable Release' does not have a Release file.
E: Failed to fetch https://dl.bintray.com/nextdns/deb/dists/stable/main/binary-arm64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error: non zero exit code: 100: OCI runtime error
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nextdns
Error: non zero exit code: 100: OCI runtime error

**Comment by rs** [comment]
Please uninstall and re-install.

**Comment by xzi** [comment]
This is a fresh install. Has something changed that I should try again though?

**Comment by rs** [comment]
Yes, I just fixed the install script, our repository location has changed.

**Comment by xzi** [comment]
Oh great. Thanks!

**Comment by xzi** [comment]
Now I'm getting this, but seems to be related to the other posted bug (a new installation)

```
WARNING: The following packages cannot be authenticated!
  nextdns
E: There were unauthenticated packages and -y was used without --allow-unauthenticated

```

**Comment by jdoss** [comment]
I am seeing this when I try to reinstall so I can update nextdns on my UDM Pro

```
# sh -c "$(curl -sL https://nextdns.io/install)"
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: LATEST_RELEASE: 1.32.0
i) Install NextDNS
e) Exit
Choice (default=i):
INFO: Installing NextDNS...
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
curl is already the newest version (7.52.1-5+deb9u13).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
Hit:1 https://repo.nextdns.io/deb stable InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
nextdns is already the newest version (1.32.0).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
ERROR: Installation failed: binary not installed in /data/nextdns
ERROR: install: exit 0
i) Install NextDNS
e) Exit```
