### ISSUE TITLE
W: The repository 'https://repo.nextdns.io/deb stable InRelease' is not signed.

### ISSUE THREAD

**Issue by pdiorio** [nextdns/nextdns#478]
The signing key for the repo might have changed, in which case you should resign the repository with the older key or flip properly to the new key. Considering hacking around this by modifying the script to allow-unauthenticated, but I would strongly prefer not to do that. Any other ideas / explanations or solutions?  Thanks

INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: LATEST_RELEASE: 1.32.0

INFO: Installing NextDNS...
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
Get:1 https://repo.nextdns.io/deb stable InRelease [9398 B]
Ign:1 https://repo.nextdns.io/deb stable InRelease
Fetched 9398 B in 0s (18.7 kB/s)
Reading package lists...
W: GPG error: https://repo.nextdns.io/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 467A7CCC8ACFA0B7
W: The repository 'https://repo.nextdns.io/deb stable InRelease' is not signed.
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 26 not upgraded.
Need to get 2934 kB of archives.
After this operation, 7930 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  nextdns
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Error: non zero exit code: 100: OCI runtime error

**Comment by vincentbernat** [comment]
Is it on a new installation or after a package upgrade? Package upgrades should have handled the change automatically. If this is a new installation, this is expected, I'll update the install script.

If it's an upgrade, could you provide the output of:

```
podman exec unifi-os cat /etc/apt/sources.list.d/nextdns.list
```

**Comment by pdiorio** [comment]
It was a new install, not an upgrade. Thanks for the update -- makes sense what needed to change
