### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by laracroftonline** [nextdns/nextdns#481]
Apr 29 21:58:04 nextdns[1431]: parse question: parsing/packing of this section has completed
Apr 29 21:58:05 nextdns[1431]: parse additional: Name: insufficient data for calculated length type

Merlin 386.2_2
nextdns-v1.32.0

**Comment by rs** [comment]
Seems like something is sending invalid DNS packets to this server on your LAN.

**Comment by laracroftonline** [comment]
Error got fixed after I restarted my modem and router.

**Comment by chessmck** [comment]
I have this same issue and it seems to go away after a router reboot, but returns in a few days.  Happens several times a day.  Other than generating the error message, I don't notice a system impact.

May 14 17:50:44 ERPoE-5 nextdns[6072]: parse question: parsing/packing of this section has completed
May 14 17:50:44 ERPoE-5 nextdns[6072]: parse question: parsing/packing of this section has completed
May 14 17:50:44 ERPoE-5 nextdns[6072]: parse additional: Name: insufficient data for calculated length type
May 14 17:50:59 ERPoE-5 nextdns[6072]: parse question: parsing/packing of this section has completed
May 14 17:50:59 ERPoE-5 nextdns[6072]: parse question: parsing/packing of this section has completed
May 14 17:50:59 ERPoE-5 nextdns[6072]: parse additional: Name: insufficient data for calculated length type
May 14 17:51:17 ERPoE-5 nextdns[6072]: parse question: parsing/packing of this section has completed
May 14 17:51:17 ERPoE-5 nextdns[6072]: parse additional: Name: insufficient data for calculated length type
May 14 17:51:17 ERPoE-5 nextdns[6072]: parse question: parsing/packing of this section has completed
