### ISSUE TITLE
Update wiki for SRM

### ISSUE THREAD

**Issue by xyzulu** [nextdns/nextdns#482]
This page: https://github.com/nextdns/nextdns/wiki/Synology-SRM
Please update to reflect the need to login to SRM/router using root@ and the admin password.

You can login as the admin user, but there is no sudo, so you'll be lost if you follow carefully the current directions you have here.

**Comment by iisworks** [comment]
Agreed, I just ran into the same issue and that solved it!

**Comment by rs** [comment]
Done
