### ISSUE TITLE
deb-repository broken 

### ISSUE THREAD

**Issue by wioxjk** [nextdns/nextdns#483]
root@x380:~# curl -i https://dl.bintray.com/nextdns/deb
HTTP/1.1 403 Forbidden
Server: nginx
Date: Mon, 03 May 2021 11:20:16 GMT
Content-Type: text/plain
Content-Length: 10
Connection: keep-alive
ETag: "5c408590-a"

Forbidden!

this keep systems using the .deb package to not work.

**Comment by rs** [comment]
Please uninstall and reinstall using our install script.

**Comment by wioxjk** [comment]
Why was this closed?
I installed with the manual install, and nextdns.io/repo/deb STILL redirects to bintray.


```
root@x380:~# curl -I https://nextdns.io/repo/deb
HTTP/2 301 
date: Mon, 03 May 2021 11:23:21 GMT
cache-control: max-age=3600
expires: Mon, 03 May 2021 12:23:21 GMT
location: https://dl.bintray.com/nextdns/deb
cf-request-id: 09d39103090000d88d3933e000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"max_age":604800,"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=Z4Ee2fzRfGIOVy3VGExvTZ6iKoJ95gEEMiYOGbt4MXWedoU4jtRZpclgHNAwNtBrB%2BEStgXclEYdBY%2BOussSh0sH0SbY6EPGwFnZ"}]}
nel: {"max_age":604800,"report_to":"cf-nel"}
strict-transport-security: max-age=15552000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 64991de4d8b0d88d-CPH
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400

```

**Comment by rs** [comment]
It's a known issue. If you uninstall then reinstall with the install script, the repository URL will be fixed.

**Comment by rsyring** [comment]
Uninstall & reinstall is a non-ideal solution for me.  I have multiple machines I'm managing through Ansible.  I would have appreciated a more thorough answer that included enough details that I could solve it without uninstall and reinstall.  What's the known issue, is it documented somewhere?  Could the correct repository URL just have been posted here?  Either would have saved me some digging.

**Comment by rs** [comment]
Our repo was hosted in bintray which EOL their service, so we had to migrate to our own.

**Comment by rs** [comment]
It was necessary during the migration. If you had upgraded before bintray was down, it would have updated the repository and gpg key automatically. Just changing the redirect would break the signature.
