### ISSUE TITLE
Error when trying to install NextDNS

### ISSUE THREAD

**Issue by Hostn4me** [nextdns/nextdns#484]
Hello,

When I try to install NextDNS, I get the following error(s):

_Err:3 https://dl.bintray.com/nextdns/deb stable InRelease                               
  403  Forbidden [IP: 3.124.41.190 443]
Reading package lists... Done                  
E: Failed to fetch https://nextdns.io/repo/deb/dists/stable/InRelease  403  Forbidden [IP: 3.124.41.190 443]
E: The repository 'https://nextdns.io/repo/deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details._

This started occurring yesterday. I am a paid subscriber and I have been using NextDNS for ~1.5 months.
Prior to yesterday I had no issues whatsoever and because I boot from live USBs quite often, I have installed
NextDNS almost on a daily basis.

I came across the following Issue: https://github.com/nextdns/nextdns/issues/452

I see the answer that was given before the Issue was closed.

Is there another mirror I can use in the meantime?
If so, how would I go about using it?

The Linux distro I am using is Ubuntu 18.05 x64 LTS.

Thanks in advance.

**Comment by rs** [comment]
Please uninstall and reinstall using the install script.
