### ISSUE TITLE
UDM-PRO at some update point lost all device name reporting

### ISSUE THREAD

**Issue by ChrisColotti** [nextdns/nextdns#485]
I was looking for something in the logs today and I noticed that all device name reporting stopped sometime back in mid April from devices using my UDM-Pro.  It was all reporting fine but for the last few weeks after some of the updates it's not logging any client device names just the single UDM external IP.  

Devices are configured for DHCP to use the UDM gateway as their DNS (it's always been that way) and the WAN interface is configured to use the NextDNS servers (also never been updated) but I am not sure why all device name reporting just stopped in the logs on or about April 15th/17th or so...

Can I provide any logs to help see what the issue may be but obviously makes it very hard to troubleshoot a device issue.

**Comment by ChrisColotti** [comment]
```
# nextdns config
max-ttl 5s
setup-router true
auto-activate false
listen localhost:53
log-queries false
cache-size 10MB
cache-max-age 0s
report-client-info true
hardened-privacy false
bogus-priv true
control /var/run/nextdns.sock
timeout 5s
use-hosts true
discovery-dns 
detect-captive-portals false
config 49ad3c
# 
```

**Comment by ChrisColotti** [comment]
The only things reporting device name have been devices with the client actually installed, but this was working for quite some time previously for sure.

**Comment by rs** [comment]
Do you have IPv6 configurrd on this UDM?

**Comment by ChrisColotti** [comment]
here is a good example how it was fine and just stopped for a device on the network at 7:22PM on april 18th...

![image](https://user-images.githubusercontent.com/25350142/116998275-f5505600-acab-11eb-80c7-8559ffa9742f.png)

@rs no IPv6 configured at all...

**Comment by rs** [comment]
Looks like you have some clients configured to go directly to nextdns using UDP. A former version of the CLI on UDM use to blindly capture those, it is no longer the case.

**Comment by ChrisColotti** [comment]
@rs why the change?  I have nothing configured specifically on any clients (except those that have a native client available like iOS) but that change seems to have also affected the DNSoHTTPS on these non native "app" based clients.  It was 100% compliant before on secure lookups from any device behind the UDM....(fireTV, appleTV, NAS, etc)....

So this has sort of limited the functionality that was there before not only for name reporting but also it appears for all devices to get secure lookups....maybe not 100% tied together, but....still....the effect is possibly related as now everything just appears as the UDM external IP.

I guess the real question is hoe can we get back the near 100% client naming along with the near 100% secure lookups?  this is a bit of a downer with that change..

**Comment by rs** [comment]
It was a mistake to capture all DNS UDP traffic going thru the UDM by default instead if just the traffic directed at the router. This fixed the wrong behavior. We may add a separate feature to capture all DNS traffic, but it should be a user choice.

May I ask what is the private network prefix used for the faulty install?

**Comment by ChrisColotti** [comment]
@rs understood on the feature, but seems maybe that is not the issue on this UDM

Working UDM network - 192.168.50.0/24
affected one:  192.168.100.0/24 (VLAN 100)

However, the working one has NO VLAN tags, the other difference is the UDM-Pro DOES have multiple VLAN's

So maybe that could be the issue we've uncovered....could have something to do with the CLI and VLAN tags?

**Comment by rs** [comment]
It could be that the new iptables rule with the more restrictive matching does not match in this case.

**Comment by rs** [comment]
Here is the change I suspect is the culprit: https://github.com/nextdns/nextdns/commit/8ee250abaa162395cb1dea14c4b5443308fe1c06

**Comment by ChrisColotti** [comment]
@rs that's interesting but can we fix it?  :) 

Do you think it's that change + VLAN's?  I have a segment without a VLAN Tag I could swap ports for a test machine and see, but the "majority" of all traffic is tagged...the only untagged segment is the management one very few machines on it.

**Comment by rs** [comment]
Try to execute this to see if it fixes the issue: 

`iptables -t nat -I PREROUTING 1 ! -d 127.0.0.0/8 -j NEXTDNS`

**Comment by ChrisColotti** [comment]
@rs does not appear to have made any change difference...I also did test a machine on the untagged network segment with the same result

**Comment by rs** [comment]
What is the `nextdns config`?

**Comment by ChrisColotti** [comment]
```
# nextdns config
max-ttl 5s
report-client-info true
auto-activate false
log-queries false
cache-size 10MB
cache-max-age 0s
discovery-dns 
setup-router true
listen localhost:53
control /var/run/nextdns.sock
config 49ad3c
timeout 5s
detect-captive-portals false
hardened-privacy false
bogus-priv true
use-hosts true
```

**Comment by ChrisColotti** [comment]
Pretty OOB config nothing custom.

**Comment by rs** [comment]
Unencrypted queries aren’t coming from the CLI. Can you identify the hosts which are making those queries and check their DNS config to ensure it is setup to query the router’s IP?

**Comment by ChrisColotti** [comment]
@rs yes I did that that are all getting DNS from DHCP which on the UDM and on all networks is by default the UDM's GW IP of that network...so yes all clients are 100% getting the same DNS config via DHCP

![image](https://user-images.githubusercontent.com/25350142/117003481-e8833080-acb2-11eb-8406-030f98a68301.png)

![image](https://user-images.githubusercontent.com/25350142/117003533-f638b600-acb2-11eb-8fa1-74767b77f543.png)

the sudden change on 4/18 is for sure suspect...

**Comment by rs** [comment]
Can you please enable query log and check if you see the unencrypted queries there?

Could you also please revert to the last working rev of the cli to validate it is a cli regression ?

**Comment by ChrisColotti** [comment]
@rs sure what's the command to enable the query log?  

I am not sure how far back I need to go it was prior to the releases being rev'd up to 1.32 and how would I grab the previous UDM installs to test.  Would have to do that after the logging

**Comment by ChrisColotti** [comment]
ummm you suppose maybe this could be an indicator?  there is nothing in the logs past the exit code

```
# nextdns log
May 04 07:09:21 ubnt systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
May 04 07:09:21 ubnt nextdns[17085]: Received signal: terminated
May 04 07:09:21 ubnt nextdns[17085]: Stopping NextDNS 1.32.0/linux
May 04 07:09:21 ubnt nextdns[17085]: Restore router settings
May 04 07:09:21 ubnt nextdns[17085]: Restore router settings: exit status 1
May 04 07:09:21 ubnt nextdns[17085]: NextDNS 1.32.0/linux stopped
May 04 07:09:21 ubnt systemd[1]: nextdns.service: Succeeded.
May 04 07:09:21 ubnt systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
May 04 07:09:22 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
May 04 07:09:22 ubnt nextdns[5450]: Starting NextDNS 1.32.1/linux on localhost:5553
May 04 07:09:22 ubnt nextdns[5450]: Listening on TCP/127.0.0.1:5553
May 04 07:09:22 ubnt nextdns[5450]: Starting mDNS discovery
May 04 07:09:22 ubnt nextdns[5450]: Listening on UDP/127.0.0.1:5553
May 04 07:09:22 ubnt ssh[5451]: Welcome to UbiOS
May 04 07:09:22 ubnt ssh[5451]: By logging in, accessing, or using the Ubiquiti product, you
May 04 07:09:22 ubnt ssh[5451]: acknowledge that you have read and understood the Ubiquiti
May 04 07:09:22 ubnt ssh[5451]: License Agreement and agree to be bound by its terms.
May 04 07:09:22 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 04 07:09:27 ubnt nextdns[5450]: Setting up router
May 04 07:09:27 ubnt nextdns[5450]: Setting up router: exit status 1
May 04 07:09:30 ubnt systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
May 04 07:09:30 ubnt nextdns[5450]: Received signal: terminated
May 04 07:09:30 ubnt nextdns[5450]: Stopping NextDNS 1.32.1/linux
May 04 07:09:30 ubnt nextdns[5450]: Restore router settings
May 04 07:09:30 ubnt nextdns[5450]: Restore router settings: exit status 1
May 04 07:09:30 ubnt nextdns[5450]: NextDNS 1.32.1/linux stopped
May 04 07:09:30 ubnt systemd[1]: nextdns.service: Succeeded.
May 04 07:09:30 ubnt systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
May 04 07:09:31 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
May 04 07:09:31 ubnt nextdns[5733]: Starting NextDNS 1.32.1/linux on localhost:5553
May 04 07:09:31 ubnt nextdns[5733]: Starting mDNS discovery
May 04 07:09:31 ubnt nextdns[5733]: Listening on UDP/127.0.0.1:5553
May 04 07:09:31 ubnt nextdns[5733]: Listening on TCP/127.0.0.1:5553
May 04 07:09:31 ubnt ssh[5734]: Welcome to UbiOS
May 04 07:09:31 ubnt ssh[5734]: By logging in, accessing, or using the Ubiquiti product, you
May 04 07:09:31 ubnt ssh[5734]: acknowledge that you have read and understood the Ubiquiti
May 04 07:09:31 ubnt ssh[5734]: License Agreement and agree to be bound by its terms.
May 04 07:09:31 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 04 07:09:36 ubnt nextdns[5733]: Setting up router
May 04 07:09:36 ubnt nextdns[5733]: Setting up router: exit status 1
May 04 07:26:51 ubnt nextdns[5733]: Received signal: terminated
May 04 07:26:51 ubnt nextdns[5733]: Stopping NextDNS 1.32.1/linux
May 04 07:26:51 ubnt nextdns[5733]: Restore router settings
May 04 07:26:51 ubnt systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
May 04 07:26:51 ubnt nextdns[5733]: Restore router settings: exit status 1
May 04 07:26:51 ubnt nextdns[5733]: NextDNS 1.32.1/linux stopped
May 04 07:26:51 ubnt systemd[1]: nextdns.service: Succeeded.
May 04 07:26:51 ubnt systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
May 04 07:27:26 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
May 04 07:27:26 ubnt nextdns[25834]: Starting NextDNS 1.32.1/linux on localhost:5553
May 04 07:27:26 ubnt nextdns[25834]: Listening on TCP/127.0.0.1:5553
May 04 07:27:26 ubnt nextdns[25834]: Starting mDNS discovery
May 04 07:27:26 ubnt nextdns[25834]: Listening on UDP/127.0.0.1:5553
May 04 07:27:26 ubnt ssh[25835]: Welcome to UbiOS
May 04 07:27:26 ubnt ssh[25835]: By logging in, accessing, or using the Ubiquiti product, you
May 04 07:27:26 ubnt ssh[25835]: acknowledge that you have read and understood the Ubiquiti
May 04 07:27:26 ubnt ssh[25835]: License Agreement and agree to be bound by its terms.
May 04 07:27:26 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 04 07:27:31 ubnt nextdns[25834]: Setting up router
May 04 07:27:31 ubnt nextdns[25834]: Setting up router: exit status 1
May 04 07:27:39 ubnt systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
May 04 07:27:39 ubnt nextdns[25834]: Received signal: terminated
May 04 07:27:39 ubnt nextdns[25834]: Stopping NextDNS 1.32.1/linux
May 04 07:27:39 ubnt nextdns[25834]: Restore router settings
May 04 07:27:39 ubnt nextdns[25834]: Restore router settings: exit status 1
May 04 07:27:39 ubnt nextdns[25834]: NextDNS 1.32.1/linux stopped
May 04 07:27:39 ubnt systemd[1]: nextdns.service: Succeeded.
May 04 07:27:39 ubnt systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
May 04 07:27:40 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
May 04 07:27:40 ubnt nextdns[26233]: Starting NextDNS 1.32.1/linux on localhost:5553
May 04 07:27:40 ubnt nextdns[26233]: Listening on TCP/127.0.0.1:5553
May 04 07:27:40 ubnt nextdns[26233]: Starting mDNS discovery
May 04 07:27:40 ubnt nextdns[26233]: Listening on UDP/127.0.0.1:5553
May 04 07:27:40 ubnt ssh[26234]: Welcome to UbiOS
May 04 07:27:40 ubnt ssh[26234]: By logging in, accessing, or using the Ubiquiti product, you
May 04 07:27:40 ubnt ssh[26234]: acknowledge that you have read and understood the Ubiquiti
May 04 07:27:40 ubnt ssh[26234]: License Agreement and agree to be bound by its terms.
May 04 07:27:40 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 04 07:27:45 ubnt nextdns[26233]: Setting up router
May 04 07:27:45 ubnt nextdns[26233]: Setting up router: exit status 1
```

and that is after log queries was enabled...

**Comment by ChrisColotti** [comment]
vs the other UDM there is all kinds of log information:

```
May 04 08:19:38 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=25ms tls=34ms, TCP, TLS13)
May 04 08:22:02 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=20ms tls=31ms, TCP, TLS13)
May 04 08:23:53 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=25ms tls=29ms, TCP, TLS13)
May 04 08:24:50 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=22ms tls=24ms, TCP, TLS13)
May 04 08:25:58 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=25ms tls=29ms, TCP, TLS13)
May 04 08:27:31 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=19ms tls=28ms, TCP, TLS13)
May 04 08:28:59 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=21ms tls=33ms, TCP, TLS13)
May 04 08:29:45 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=22ms tls=25ms, TCP, TLS13)
May 04 08:30:30 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=25ms tls=27ms, TCP, TLS13)
May 04 08:34:31 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=20ms tls=31ms, TCP, TLS13)
May 04 08:35:38 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=24ms tls=24ms, TCP, TLS13)
May 04 08:38:35 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=19ms tls=29ms, TCP, TLS13)
May 04 08:40:43 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=29ms tls=29ms, TCP, TLS13)
May 04 08:42:43 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=24ms tls=29ms, TCP, TLS13)
May 04 08:44:09 ubnt nextdns[5975]: Connected 45.90.28.0:443 (con=22ms tls=28ms, TCP, TLS13)
```

so seems there is a service related issue on this one?   How do we just completely remove all things nextdns related or will I really have to do a reset and config restore?

**Comment by rs** [comment]
Try `nextdns uninstall` followed by `nextdns install`. I suspect a bad systemd service file.

**Comment by ChrisColotti** [comment]
@rs isnt that the same as uninstalling and re-0installing with the script although now the install script is failing after nextdns uninstall

```
ERROR: Installation failed: binary not installed in /data/nextdns
ERROR: install: exit 0
i) Install NextDNS
e) Exit
```

**Comment by rs** [comment]
It’s not. Try a full uninstall / install with the script then.

**Comment by ChrisColotti** [comment]
Yeah don’t that 3-4 times already with the script but now it’s not installing.   This has to be related to all that mess trying to get the release issues cleaned up on this unit.

**Comment by ChrisColotti** [comment]
@rs no joy...

```
# sh -c "$(curl -sL https://nextdns.io/install)"
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: LATEST_RELEASE: 1.32.1
i) Install NextDNS
e) Exit
Choice (default=i): 
INFO: Installing NextDNS...
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
curl is already the newest version (7.52.1-5+deb9u13).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Hit:1 https://repo.nextdns.io/deb stable InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
nextdns is already the newest version (1.32.1).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
ERROR: Installation failed: binary not installed in /data/nextdns
ERROR: install: exit 0
i) Install NextDNS
e) Exit
Choice (default=i): 
```

**Comment by ChrisColotti** [comment]
@rs well the beauty of UBNT is the easy restore function....reset to factory and restored the entire network config and now it's working again....seriously must have traced back to that messed up release.
