### ISSUE TITLE
mDNS resolver on Raspbian

### ISSUE THREAD

**Issue by ajp2k13** [nextdns/nextdns#49]
With recent versions of the NextDNS linux client on Raspbian I get the following error when starting the client:

Cannot start mDNS resolver: mdns browse: write udp6 [::]:5353->224.0.0.251:5353: sendto: network is unreachable

My config is:

setup-router false
listen :53
detect-captive-portals false
use-hosts true
bogus-priv true
timeout 5s
auto-activate false
config XXXXXX
log-queries false
report-client-info true
hardened-privacy false

**Comment by rs** [comment]
Which version?

**Comment by ajp2k13** [comment]
Latest, although that error appeared a few versions ago... not sure which one exaclty.
