### ISSUE TITLE
NextDNS on DDWRT

### ISSUE THREAD

**Issue by s-ahuja** [nextdns/nextdns#492]
https://github.com/nextdns/nextdns/wiki/DDWRT - when will this be completely available.

**Comment by Mile-Lile** [comment]
@rs 
I tested 1.37.4 on ddwrt and can confirm that it is working... maybe this ticket can be closed and wiki edited... or if there is another member that can confirm...

**Comment by rs** [comment]
The installer works out of the box or did you have to perform manual tasks?

**Comment by Mile-Lile** [comment]
works, out of the box... I had jffs allready enabled and prepared
(cleaned)...
