### ISSUE TITLE
Cant upgrade on my Pi

### ISSUE THREAD

**Issue by bryshaw** [nextdns/nextdns#493]
&lt;Describe the bug> Not sure why i cant upgrade. Tried uninstall then install and still. I get this:
INFO: Upgrading NextDNS...
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                                       
Err:1 https://dl.bintray.com/nextdns/deb stable InRelease                                          
  403  Forbidden [IP: 52.42.217.145 443]
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease                          
Reading package lists... Done                              
E: Failed to fetch https://nextdns.io/repo/deb/dists/stable/InRelease  403  Forbidden [IP: 52.42.217.145 443]
E: The repository 'https://nextdns.io/repo/deb stable InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
ERROR: upgrade: exit 0

**Context**
 - Version [e.g. 1.5.2]: 
 - Platform [e.g. macOS, ASUS-Merlin]:rpi

**Comment by rs** [comment]
Please uninstall then reinstall.

**Comment by bryshaw** [comment]
I already tried that.

**Comment by bryshaw** [comment]
I also state that I did that already in my post as well.

**Comment by bryshaw** [comment]
@rs i already tried that. I state that in the post as well.

**Comment by rs** [comment]
How did you uninstall?

**Comment by bryshaw** [comment]
sudo Nextdns uninstall

**Comment by bryshaw** [comment]
Did I uninstall it correctly?

**Comment by rs** [comment]
You need to use the install script and select uninstall.

**Comment by bryshaw** [comment]
Okay I will try that.

**Comment by bryshaw** [comment]
So I did that with uninstall. And now when I run the install script nothing happens. No output or anything in terminal.

**Comment by bryshaw** [comment]
I’ve flashed the SD card and I’m trying again from scratch.

**Comment by bryshaw** [comment]
Working after flash. Thank you.
