### ISSUE TITLE
Non-interactive version check and upgrade

### ISSUE THREAD

**Issue by mihakralj** [nextdns/nextdns#494]
the command `sudo nextdns upgrade` should allow non-interactive check of the installed and available version, allowing quiet (non-interactive) upgrade with a command-line switch.

Ideally, the `nextdns version` should show both installed and available version and `nextdns upgrade` should allow silent upgrade.

**Comment by rs** [comment]
The upgrade is already non-interactive. Please explain the use case.

**Comment by mihakralj** [comment]
I distinctly remember how `nextdns upgrade` required keyboard confirmation (y) or else it didn't continue.
But it seems that this changed recently?

```
root@fw1:/usr/local/sbin # nextdns version
nextdns version 1.32.0

root@fw1:/usr/local/sbin # nextdns upgrade
INFO: OS: opnsense
INFO: GOARCH: amd64
INFO: GOOS: freebsd
INFO: NEXTDNS_BIN: /usr/local/sbin/nextdns
INFO: LATEST_RELEASE: 1.32.2
INFO: Upgrading NextDNS...
Terminated
root@fw1:/usr/local/sbin # Terminated
Terminated

root@fw1:/usr/local/sbin # nextdns version
nextdns version 1.32.2
```

Here is the use case: allowing user in firewall UI to interact with NextDNS CLI:
- get currently-installed NextDNS CLI version (ideally CLI should output the version in JSON)
- get the latest available version of NextDNS (ideally JSON, with a link to changelog)
- have an ability to display an 'upgrade' button in UI - and to trigger the unattended install (which should return the pass/fail status of the upgrade
- bonus: downgrade command (to reverse the changes, in case the upgrade is buggy)

As long as all actions can be passed through a command line, and results can be parsed, we are good!
([here is a link to PR](https://github.com/mimugmail/opn-repo/pull/53) of some work-in-progress and below are few screenshots of UI wrapper for NextDNS on OPNsense): 

![image](https://user-images.githubusercontent.com/31756078/119090348-5e301180-b9c0-11eb-8276-02c2898bb4c0.png)

**Comment by rs** [comment]
It’s better to handle upgrade through the package manager of the OS and let it handle upgrades. We already have a freebsd port, I guess it should be easy to get this port added to opnsense.

**Comment by mihakralj** [comment]
Agreed, OPNsense is already pulling standard ports from upstream repo and Nextdns is there, but...

The ports version shows no version at all - just that it is Dev version. Wiki claims that BSD  ports is coming - is the process done and is ports version current?

**Comment by rs** [comment]
Yes it is: https://cgit.freebsd.org/ports/tree/dns/nextdns/Makefile

**Comment by mihakralj** [comment]
Awesome, one issue less! 😊

**Comment by rs** [comment]
I updated the freebsd wifi to reflect the port status.

**Comment by mihakralj** [comment]
Awesome. Nextdns is awesome. ❤️
