### ISSUE TITLE
Cannot install on Ubuntu 19.10

### ISSUE THREAD

**Issue by FSM45** [nextdns/nextdns#495]
sh -c "$(curl -sL https://nextdns.io/install)"
INFO: OS: ubuntu
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: LATEST_RELEASE: 1.32.2
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
Hit:1 http://mirror.dhakacom.com/ubuntu-archive groovy InRelease
Hit:2 http://mirror.dhakacom.com/ubuntu-archive groovy-updates InRelease                                      
Hit:3 http://mirror.dhakacom.com/ubuntu-archive groovy-backports InRelease                                             
Hit:4 http://mirror.dhakacom.com/ubuntu-archive groovy-security InRelease                                              
Hit:5 http://packages.microsoft.com/repos/edge stable InRelease                                                        
Hit:6 http://ppa.launchpad.net/hamishmb/myppa/ubuntu groovy InRelease                                                  
Hit:7 http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04  InRelease                         
Hit:8 http://ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu groovy InRelease                                         
Hit:9 http://archive.canonical.com/ubuntu groovy InRelease                                                             
Get:10 https://mega.nz/linux/MEGAsync/xUbuntu_20.04 ./ InRelease [2,441 B]                                             
Hit:11 http://ppa.launchpad.net/mjasnik/ppa/ubuntu groovy InRelease                                                    
Hit:12 https://debrepo.freedownloadmanager.org bionic InRelease                                                      
Hit:13 https://repo.nextdns.io/deb stable InRelease                                                                  
Hit:14 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu groovy InRelease                  
Get:15 https://repo.protonvpn.com/debian unstable InRelease [2,521 B]    
Hit:16 http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu groovy InRelease
Fetched 4,962 B in 3s (1,834 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/3,238 kB of archives.
After this operation, 8,503 kB of additional disk space will be used.
Selecting previously unselected package nextdns.
(Reading database ... 197239 files and directories currently installed.)
Preparing to unpack .../nextdns_1.32.2_amd64.deb ...
Unpacking nextdns (1.32.2) ...
Setting up nextdns (1.32.2) ...
NextDNS installed and started using systemd init
NextDNS Configuration ID (default=cbe135): cbe135
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: Y
Accept DNS request from other network hosts.
Setup as a router? [Y|n]: n
Make nextdns CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Enable caching? [Y|n]: Y
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on you LAN hosts without having to wait for their cache to expire.
Enable instant refresh? [Y|n]: Y
Changes DNS settings of the host automatically when nextdns is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically setup local host DNS? [Y|n]: Y
NextDNS installed and started using systemd init

Congratulations! NextDNS is now installed.

To upgrade/uninstall, run this command again and select the approriate option.

You can use the nextdns command to control the daemon.
Here is a few important commands to know:

# Start, stop, restart the daemon:
nextdns start
nextdns stop
nextdns restart

# Configure the local host to point to NextDNS or not:
nextdns activate
nextdns deactivate

# Explore daemon logs:
nextdns log

# For more commands, use:
nextdns help
fs1@fs1-Dell-System-Vostro-3450:~$ nextdns status
not installed
fs1@fs1-Dell-System-Vostro-3450:~$ systemctl is-active nextdns
failed

                                                           I've also tried this instruction but it didn't work.
" After some research "systemd-r" enter in conflict with next-dns to solve the problem edit the file

/etc/systemd/resolved.conf
and change the line

DNSStubListener=yes
to

DNSStubListener=no
after that kill the pid of "systemd-r", use this command to show the pid

sudo lsof -i -P -n | grep ":53 (LISTEN)"
and restart next-dns with

next-dns install
and that's all :) "

I also use Nextdns on my windows 10 laptop and it works fine there. Really nice service and effectiveness. If I run "nextdns log" this is what I get:
~$ nextdns log
May 22 13:51:15 fs1-Dell-System-Vostro-3450 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 22 13:51:18 fs1-Dell-System-Vostro-3450 nextdns[1119]: Starting NextDNS 1.32.2/linux on :53
May 22 13:51:18 fs1-Dell-System-Vostro-3450 nextdns[1119]: Listening on TCP/:53
May 22 13:51:18 fs1-Dell-System-Vostro-3450 nextdns[1119]: Starting mDNS discovery
May 22 13:51:18 fs1-Dell-System-Vostro-3450 nextdns[1119]: Listening on UDP/:53
May 22 13:51:18 fs1-Dell-System-Vostro-3450 nextdns[1119]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
May 22 13:51:18 fs1-Dell-System-Vostro-3450 nextdns[1119]: Error: proxy: tcp: listen tcp :53: bind: address already in use
May 22 13:51:18 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 22 13:51:18 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Failed with result 'exit-code'.
May 22 13:54:20 fs1-Dell-System-Vostro-3450 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 22 13:54:20 fs1-Dell-System-Vostro-3450 nextdns[18473]: Starting NextDNS 1.32.2/linux on :53
May 22 13:54:20 fs1-Dell-System-Vostro-3450 nextdns[18473]: Starting mDNS discovery
May 22 13:54:20 fs1-Dell-System-Vostro-3450 nextdns[18473]: Listening on TCP/:53
May 22 13:54:20 fs1-Dell-System-Vostro-3450 nextdns[18473]: Listening on UDP/:53
May 22 13:54:20 fs1-Dell-System-Vostro-3450 nextdns[18473]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
May 22 13:54:20 fs1-Dell-System-Vostro-3450 nextdns[18473]: Error: proxy: tcp: listen tcp :53: bind: address already in use
May 22 13:54:20 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 22 13:54:20 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Failed with result 'exit-code'.
May 22 14:00:56 fs1-Dell-System-Vostro-3450 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 22 14:00:56 fs1-Dell-System-Vostro-3450 nextdns[40762]: Starting NextDNS 1.32.2/linux on :53
May 22 14:00:56 fs1-Dell-System-Vostro-3450 nextdns[40762]: Starting mDNS discovery
May 22 14:00:56 fs1-Dell-System-Vostro-3450 nextdns[40762]: Listening on TCP/:53
May 22 14:00:56 fs1-Dell-System-Vostro-3450 nextdns[40762]: Error: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:00:56 fs1-Dell-System-Vostro-3450 nextdns[40762]: Listening on UDP/:53
May 22 14:00:56 fs1-Dell-System-Vostro-3450 nextdns[40762]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:00:56 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 22 14:00:56 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Failed with result 'exit-code'.
May 22 14:02:06 fs1-Dell-System-Vostro-3450 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 22 14:02:06 fs1-Dell-System-Vostro-3450 nextdns[45273]: Starting NextDNS 1.32.2/linux on :53
May 22 14:02:06 fs1-Dell-System-Vostro-3450 nextdns[45273]: Listening on TCP/:53
May 22 14:02:06 fs1-Dell-System-Vostro-3450 nextdns[45273]: Starting mDNS discovery
May 22 14:02:06 fs1-Dell-System-Vostro-3450 nextdns[45273]: Listening on UDP/:53
May 22 14:02:06 fs1-Dell-System-Vostro-3450 nextdns[45273]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:02:06 fs1-Dell-System-Vostro-3450 nextdns[45273]: Error: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:02:06 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 22 14:02:06 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Failed with result 'exit-code'.
May 22 14:06:08 fs1-Dell-System-Vostro-3450 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 22 14:06:08 fs1-Dell-System-Vostro-3450 nextdns[59192]: Starting NextDNS 1.32.2/linux on :53
May 22 14:06:08 fs1-Dell-System-Vostro-3450 nextdns[59192]: Listening on TCP/:53
May 22 14:06:08 fs1-Dell-System-Vostro-3450 nextdns[59192]: Listening on UDP/:53
May 22 14:06:08 fs1-Dell-System-Vostro-3450 nextdns[59192]: Starting mDNS discovery
May 22 14:06:08 fs1-Dell-System-Vostro-3450 nextdns[59192]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:06:08 fs1-Dell-System-Vostro-3450 nextdns[59192]: Error: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:06:08 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 22 14:06:08 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Failed with result 'exit-code'.
May 22 14:06:39 fs1-Dell-System-Vostro-3450 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 22 14:06:39 fs1-Dell-System-Vostro-3450 nextdns[61372]: Starting NextDNS 1.32.2/linux on :53
May 22 14:06:39 fs1-Dell-System-Vostro-3450 nextdns[61372]: Listening on TCP/:53
May 22 14:06:39 fs1-Dell-System-Vostro-3450 nextdns[61372]: Starting mDNS discovery
May 22 14:06:39 fs1-Dell-System-Vostro-3450 nextdns[61372]: Listening on UDP/:53
May 22 14:06:39 fs1-Dell-System-Vostro-3450 nextdns[61372]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:06:39 fs1-Dell-System-Vostro-3450 nextdns[61372]: Error: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:06:39 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 22 14:06:39 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Failed with result 'exit-code'.
May 22 14:07:05 fs1-Dell-System-Vostro-3450 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 22 14:07:05 fs1-Dell-System-Vostro-3450 nextdns[62389]: Starting NextDNS 1.32.2/linux on :53
May 22 14:07:05 fs1-Dell-System-Vostro-3450 nextdns[62389]: Starting mDNS discovery
May 22 14:07:05 fs1-Dell-System-Vostro-3450 nextdns[62389]: Listening on TCP/:53
May 22 14:07:05 fs1-Dell-System-Vostro-3450 nextdns[62389]: Listening on UDP/:53
May 22 14:07:05 fs1-Dell-System-Vostro-3450 nextdns[62389]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:07:05 fs1-Dell-System-Vostro-3450 nextdns[62389]: Error: proxy: tcp: listen tcp :53: bind: address already in use
May 22 14:07:05 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 22 14:07:05 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Failed with result 'exit-code'.
May 22 14:08:22 fs1-Dell-System-Vostro-3450 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 22 14:08:22 fs1-Dell-System-Vostro-3450 nextdns[66396]: Starting NextDNS 1.32.2/linux on :53
May 22 14:08:22 fs1-Dell-System-Vostro-3450 nextdns[66396]: Starting mDNS discovery
May 22 14:08:22 fs1-Dell-System-Vostro-3450 nextdns[66396]: Listening on UDP/:53
May 22 14:08:22 fs1-Dell-System-Vostro-3450 nextdns[66396]: Listening on TCP/:53
May 22 14:08:22 fs1-Dell-System-Vostro-3450 nextdns[66396]: Error: proxy: udp: listen udp :53: bind: address already in use
May 22 14:08:22 fs1-Dell-System-Vostro-3450 nextdns[66396]: Startup failed: proxy: udp: listen udp :53: bind: address already in use
May 22 14:08:22 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 22 14:08:22 fs1-Dell-System-Vostro-3450 systemd[1]: nextdns.service: Failed with result 'exit-code'.

**Comment by rtanx** [comment]
have you done deal with it? I'm facing same issue, it's seems like tcp :53 already in use by systemd, cek `sudo lsof -i -P -n | grep LISTEN`

**Comment by PeterDaveHello** [comment]
Do you have result of the command: `sudo netstat -lnup | grep ':53'`?
