### ISSUE TITLE
Bulk disable/enable blocklists

### ISSUE THREAD

**Issue by mihakralj** [nextdns/nextdns#496]
When troubleshooting a malfunctioning website, the most common step is to stop blocklists from filtering requests and see if there was some over-aggressive filter causing problems.

**Current process (that I use)**: capture the active list of selected blocklists, remove all blocklists, troubleshoot, then add the captured list of blocklists back. (all of that can be done through a few API calls)

**Desired process**: a single enable/disable switch that controls if blocklists are active (not selected, ACTIVE); if that switch is set to 'disable', any blocklist on the privacy page plus any domains on denylist would stop filtering the requests. Having the switch accessible through an API, as well as through web UI

**Bonus**: flipping the switch for a pre-defined time (in minutes), so the domain filtering can be suspended for a time interval.

**Comment by rs** [comment]
Please use https://help.nextdns.io for feature request about our service. This repository is only about NextDNS CLI.
