### ISSUE TITLE
FreeBSD NextDNS CLI: no listener on IPv6 ports

### ISSUE THREAD

**Issue by mihakralj** [nextdns/nextdns#501]
- there is no response to IPv6 queries like `dig -6 xxx` while the same query on IPv4 works: `dig -4 xxx`
- `sudo sockstat | grep :53` shows the following (notice the absence of tcp6/udp6

```
[admin@fw ~]$ sudo sockstat | grep :53
root     nextdns    19750 7  tcp4   127.0.0.1:53          *:*
root     nextdns    19750 8  udp4   127.0.0.1:53          *:*
```

The equivalent Unbound configuration:

```
[admin@fw ~]$ sudo sockstat | grep :53
unbound  unbound    1179  3  udp6   *:53                  *:*
unbound  unbound    1179  4  tcp6   *:53                  *:*
unbound  unbound    1179  5  udp4   *:53                  *:*
unbound  unbound    1179  6  tcp4   *:53                  *:*
unbound  unbound    1179  7  udp6   *:53                  *:*
unbound  unbound    1179  8  tcp6   *:53                  *:*
unbound  unbound    1179  9  udp4   *:53                  *:*
unbound  unbound    1179  10 tcp4   *:53                  *:*
```

The same behavior exists when nextdns.config includes `setup-router true` as well as when it includes:
```
setup-router false
listen 127.0.0.1:53
listen [::1]:53

**Context**
 - Version: FreeBSD x64, 1.32.2
 - Platform: OPNsense 21.7.a_426

**Comment by mihakralj** [comment]
Additionally:
even when nextdns.conf includes only IPv6 addresses, the nextdns CLI still listens on IPv4:
nextdns.conf:
```
listen [::1]:53
listen  2001:xxx:xxx:1::1:53
setup-router false
```
the response from sockstat:
```
[admin@fw ~]$ sudo sockstat | grep :53
root     nextdns    59917 7  tcp4   127.0.0.1:53          *:*
```

**Comment by tris** [comment]
I was seeing very similar behavior on OPNsense 23.1.11 / FreeBSD 13.1 / nextdns 1.39.4.

I was rather blindly following [Derek Seaman's guide](https://www.derekseaman.com/2021/04/how-to-nextdns-opnsense-firewall.html) at first, listening on individual addresses, but that doesn't feel nice with v6.

I was eventually able to debug it by running nextdns in the foreground, with `log-queries true` while trying several combinations of `listen` directives.  The only combination that worked for me was a _single_ `listen [::]:53` and nothing else.  This is what the output should say:

```
root@gw:~ # nextdns run -config-file /usr/local/etc/nextdns.conf
INFO:  12:04:09 Starting NextDNS 1.39.4/freebsd on [::]:53
INFO:  12:04:09 Starting mDNS discovery
INFO:  12:04:09 Listening on TCP/[::]:53
INFO:  12:04:09 Listening on UDP/[::]:53
...
```

```
root@gw:~ # sockstat -ln | grep ':53 '
0        nextdns    3215  8  tcp46  *:53                  *:*
0        nextdns    3215  11 udp46  *:53                  *:*
```

Hope this helps someone. :)

**Comment by mihakralj** [comment]
so, how does the conf file look then?
```
...
listen :53
listen [::]:53
...
```
Is that right?

**Comment by tris** [comment]
No, just a single `listen` directive:

```
root@gw:~ # grep listen /usr/local/etc/nextdns.conf
listen [::]:53
```
