### ISSUE TITLE
Cannot upgrade

### ISSUE THREAD

**Issue by travisboss** [nextdns/nextdns#502]
&lt;Describe the bug>

```
Err:1 https://dl.bintray.com/nextdns/deb stable InRelease
  403  Forbidden [IP: 52.42.38.157 443]
Hit:3 https://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
E: Failed to fetch https://nextdns.io/repo/deb/dists/stable/InRelease  403  Forbidden [IP: 52.42.38.157 443]
```

**Context**
 - Version [e.g. 1.5.2]: 1.11.0
 - Platform [e.g. macOS, ASUS-Merlin]: Raspberry Pi OS

Using dietpi which is a trimmed down version of RPI OS and have been for a long time, but everytime I try to do a `nextdns upgrade` I get the error shown above that the IP is forbidden.

**Comment by rs** [comment]
This is a known issue. Please uninstall and reinstall using the install script.

**Comment by fpgnl** [comment]
Try Manual install.:

[https://github.com/nextdns/nextdns/wiki/Debian-Based-Distribution#manual-install]
