### ISSUE TITLE
UDMP + Nextdns loosing connection many times a day

### ISSUE THREAD

**Issue by Allram** [nextdns/nextdns#503]
&lt; Loosing connection with Nextdns installed on UDMP multiple times a day.

**Context**
 - Version [e.g. 1.5.2]: 1.32.2
 - Platform [e.g. macOS, ASUS-Merlin]: UDMP

This is the report, i can't even finish this one.. :

# sh -c 'sh -c "$(curl -s https://nextdns.io/diag)"'

Welcome to NextDNS network diagnostic tool.

This tool will download a small binary to capture latency and routing information
regarding the connectivity of your network with NextDNS. In order to perform a
traceroute, root permission is required. You may therefore be asked to provide
your password for sudo.

The source code of this tool is available at https://github.com/nextdns/diag

Do you want to continue? (press enter to accept)
Testing IPv6 connectivity
  available: false
Fetching https://test.nextdns.io
  status: ok
  client: 79.***.***.***
  protocol: UDP
  dest IP: 45.90.30.189
  server: anexia-osl-1
Fetching PoP name for ultra low latency primary IPv4 (ipv4.dns1.nextdns.io)
  anexia-osl: 3.389ms
Fetching PoP name for ultra low latency secondary IPv4 (ipv4.dns2.nextdns.io)
  zepto-osl: 10.261ms
Fetching PoP name for anycast primary IPv4 (45.90.28.0)
  zepto-sto: 10.669ms
Fetching PoP name for anycast secondary IPv4 (45.90.30.0)
  anexia-osl: 3.589ms
Pinging PoPs
  anexia-osl: 3.4ms
  zepto-osl: 9.858ms
  zepto-sto: 10.76ms
  estnoc-cph: 10ms
  hetzner-hel: 16.289ms
  anexia-cph: 21.919ms
  anexia-sto: 26.255ms
  vultr-ams: 28.934ms
  tavu-hel: 28ms
  zepto-ams: 34.331ms
Traceroute for ultra low latency primary IPv4 (188.172.223.3)
    1 79.160.116.154    3ms   3ms   5ms
    2 213.167.114.141    3ms   3ms   3ms
    3 212.112.170.194    3ms   3ms   3ms
    4 146.247.201.227    3ms   3ms   3ms
    5 146.247.160.45    3ms   3ms   3ms
    6    94.16.99.32    3ms   3ms   3ms
    7  188.172.223.3    3ms   3ms   3ms
Traceroute for ultra low latency secondary IPv4 (37.120.149.148)
    1 79.160.116.154    3ms   3ms   3ms
    2 213.167.114.217    3ms   3ms   3ms
    3    62.140.27.1   20ms   8ms   7ms
    4    4.69.201.77   16ms  17ms  17ms
    5  212.162.27.82   10ms   9ms  10ms
    6 37.120.128.247   10ms  10ms  10ms
    7  45.11.107.148   10ms  10ms   9ms
    8 37.120.149.148    9ms   9ms   9ms
Traceroute for anycast primary IPv4 (45.90.28.0)
    1 79.160.116.154    9ms   5ms   4ms
    2 213.167.114.219    3ms   9ms   4ms
    3  62.115.54.185    9ms   5ms   7ms

**Comment by rs** [comment]
What do you get for `nextdns version`?

**Comment by Allram** [comment]
Nextdns version 1.32.2

**Comment by Allram** [comment]
This is the output of log:
I don't know how much it means, but isn't it weird that is changed from a endpoint with con=9ms and tls=8ms to a endpoint with con=3ms and tls=174ms? or does the tls= not matter that much in terms of connection?

# nextdns log
May 31 14:01:39 ubnt nextdns[6451]: Connected 45.90.28.0:443 (con=10ms tls=87ms, TCP, TLS13)
May 31 14:08:58 ubnt nextdns[6451]: Connected 45.90.28.0:443 (con=10ms tls=19ms, TCP, TLS13)
May 31 14:17:25 ubnt nextdns[6451]: Connected 45.90.28.0:443 (con=10ms tls=15ms, TCP, TLS13)
May 31 14:27:36 ubnt nextdns[6451]: Connected 45.90.28.0:443 (con=10ms tls=15ms, TCP, TLS13)
May 31 14:31:57 ubnt nextdns[6451]: Connected 45.90.28.0:443 (con=10ms tls=16ms, TCP, TLS13)
May 31 14:37:43 ubnt nextdns[6451]: Connected 45.90.28.0:443 (con=10ms tls=17ms, TCP, TLS13)
May 31 17:02:30 ubnt nextdns[6451]: Connected 45.90.28.0:443 (con=10ms tls=15ms, TCP, TLS13)
May 31 18:06:30 ubnt nextdns[6451]: Received signal: terminated
May 31 18:06:30 ubnt systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
May 31 18:06:30 ubnt nextdns[6451]: Stopping NextDNS 1.32.2/linux
May 31 18:06:30 ubnt nextdns[6451]: Restore router settings
May 31 18:06:31 ubnt nextdns[6451]: NextDNS 1.32.2/linux stopped
May 31 18:06:31 ubnt systemd[1]: nextdns.service: Succeeded.
May 31 18:06:31 ubnt systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
May 31 18:06:31 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
May 31 18:06:31 ubnt nextdns[818]: Starting NextDNS 1.32.2/linux on localhost:5553
May 31 18:06:31 ubnt nextdns[818]: Listening on TCP/127.0.0.1:5553
May 31 18:06:31 ubnt nextdns[818]: Listening on UDP/127.0.0.1:5553
May 31 18:06:31 ubnt nextdns[818]: Starting mDNS discovery
May 31 18:06:31 ubnt ssh[819]: Welcome to UbiOS
May 31 18:06:31 ubnt ssh[819]: By logging in, accessing, or using the Ubiquiti product, you
May 31 18:06:31 ubnt ssh[819]: acknowledge that you have read and understood the Ubiquiti
May 31 18:06:31 ubnt ssh[819]: License Agreement and agree to be bound by its terms.
May 31 18:06:31 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 31 18:06:36 ubnt nextdns[818]: Setting up router
May 31 18:06:37 ubnt nextdns[818]: Connected 188.172.223.3:443 (con=9ms tls=8ms, TCP, TLS13)
May 31 18:06:37 ubnt nextdns[818]: Switching endpoint: https://dns.nextdns.io.#37.120.149.148,2a0d:5642:117:101:5054:ff:fe0f:6c8e,188.172.223.3,2a00:11c0:68:657::3
May 31 18:06:37 ubnt nextdns[818]: Connected 45.90.30.0:443 (con=3ms tls=174ms, TCP, TLS13)

**Comment by rs** [comment]
It is normal for DoH to re-establish the TCP/TLS connection regularly. Do you experience actual issues?

**Comment by Allram** [comment]
Yes, the DNS stops answering multiple times a day.

Somedays it works itself out and works after a few minutes. Other days i have to cli login and restart the nextdns service to get it working again.
