### ISSUE TITLE
NextDNS with Smart DNS for some content

### ISSUE THREAD

**Issue by sqwal** [nextdns/nextdns#508]
Hi,

I'm using a SmartDNS to bypass some georestrictions on some of my devices. This SmartDNS is set up permanently (DNS address).
I'd like to be able to use NextDNS for ALL my local network devices, but keep using the SmartDNS service only for some content.

Is there a way I could use Split Horizon for that matter? Do you have any idea?

To be more precise, I'm trying to unlock BBC iPlayer (I don't live in the UK). I tried adding the line `-forwarder bbc.co.uk=1.2.3.4,1.2.3.5` (1.2.3.4 being my Smart DNS address) to my config, but it's not working, so I guess it's not the domain used by BBC to check the location.

Do you have any idea?

Thanks!!

**Comment by chentag** [comment]
For BBC, you have to add a lot url in the file. I've setup a dnsmasq + sniproxy for that.
> www.bbc.com
> www.bbc.co
> www.bbci.co.uk
> www.bbci.co
> vod-dash-uk-live.akamaized.net
> vod-thumb-uk-live.akamaized.net
> vod-dash-uk-live.bbcfmt.hs.llnwd.net
> vod-thumb-uk-live.bbcfmt.hs.llnwd.net

**Comment by mbk87** [comment]
Now works like a charm :-)
