### ISSUE TITLE
Duplicate clients in log

### ISSUE THREAD

**Issue by anaschaudhary33** [nextdns/nextdns#512]
I have installed nextdns cli on my raspberry pi 4 and using it as a dns server. But I am seeing duplicate clients in log.

I have tried the following,
Setup static lease on the router to prevent ip change. Entered host file entries for custom name. But even the custom names appears twice or thrice in logs, all of them have same ip.

I there any way to remove these duplicates? 
![Screenshot_20210605-111620__01__01](https://user-images.githubusercontent.com/70742968/120881699-bb4ada80-c5f0-11eb-984a-b36dd456ed3d.jpg)

**Context**
 - Version [1.32.3]: 
 - Platform [linux, Raspberry Pi]:

**Comment by vijvis** [comment]
I see the same issue as well. Require an option to remove duplicates - automatic or manual.

**Comment by lm913** [comment]
I have the same issue (Asus Merlin router)
