### ISSUE TITLE
Error when installing: invalid boolean value "Invalid" for -report-client-info: parse error

### ISSUE THREAD

**Issue by kamalhm** [nextdns/nextdns#514]
&lt;Describe the bug>

When I tried to install nextdns on my router, after this step it shows this in the console

>Report device name? [Y|n]: Y
Make nextdns CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Note that enabling this feature will disable dnsmasq for DNS to avoid double
caching.
Enable caching? (y/n): y
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on you LAN hosts without having to wait for their cache to expire.
Enable instant refresh? (y/n): y
**invalid boolean value "Invalid" for -report-client-info: parse error**

**Context**
 - Version [e.g. 1.5.2]: 1.32.3
 - Platform [e.g. macOS, ASUS-Merlin]: Asus-Merlin firmware on ASUS RT AC66U_B1

**Comment by rs** [comment]
Does it work if you just “enter” to the report client info question?

**Comment by kamalhm** [comment]
I tried reinstalling, and I use all uppercase "Y" and it somehow worked, not sure why
