### ISSUE TITLE
Update breaks support for MacOS 10.10 Yosemite

### ISSUE THREAD

**Issue by BergiusR** [nextdns/nextdns#515]
Was unfortunate to have to re-install NextDNS on my old Yosemite machine. Apparently an update over the last few month (can't be sure at which version it started), broke compatibility with Yosemite. I get the following error:

> dyld: Symbol not found: _clock_gettime
>   Referenced from: /usr/local/bin/nextdns
>   Expected in: flat namespace

Clock_gettime is only available in ElCapitan and above. Now I'm stuck: obviously the machine is too old to upgrade MacOS and I cannot figure out how to install back an older version (tried with brew and a direct link to an older Homebrew-tap version, but no dice).

Could somebody point me to the last working version that did not require clock_gettime and how to re-install it on my machine?
I try not to update anything because of such issues, but maybe it would also be good to tell brew that these latest versions can't be installed on Yosemite machines? Just so to be safe.

Thanks

**Context**
 - Version 1.32.3: 
 - Platform MacOS 10.10 Yosemite:

**Comment by rs** [comment]
Go dropped support for Yosemite with version 1.12. Only a very early version of the CLI would use such an old version of Go. As an alternative, you can compile the binary from source with a version of Go pre-dating Go 1.12.

**Comment by BergiusR** [comment]
Thanks, I managed to reinstall an old version using the ruby scripts in the homebrew-tap in the end. Didn't have to go that far back: 1.11.0 works perfectly (1.12.5 didn't, and I didn't try in between).

I've now pinned it also just to be sure.
