### ISSUE TITLE
My google image search cannot be displayed normally

### ISSUE THREAD

**Issue by Gi0laby** [nextdns/nextdns#516]
![F54C2DA8-A6C9-48C2-BBB4-E3F85F5DC839](https://user-images.githubusercontent.com/51205600/121225809-7c50a980-c8bc-11eb-8fe4-14907ab402f5.png)

After using the nextDNS service, my google image search cannot be displayed normally, even if no block list is added.
When I stop using the nextDNS service, everything is back to normal

**Comment by rs** [comment]
Please report this to https://help.nextdns.io. This repository is about the CLI client.
