### ISSUE TITLE
restart err: getTuntapComponentId: not found component id error

### ISSUE THREAD

**Issue by Naxterra** [nextdns/nextdns#517]
It is happening on 2.0.3. At first install it gives the error, on second install it installs the app but then it floods event logs every five seconds with below message.
restart err: getTuntapComponentId: not found component id

![image](https://user-images.githubusercontent.com/41871948/121393599-cbe0b500-c950-11eb-8573-7c95124e99e4.png)

**Comment by rs** [comment]
Wrong repo -> https://github.com/nextdns/windows. This should have been fixed by 2.1.0.
