### ISSUE TITLE
Nextdns just breaks all the dns system when using nextdns + nordvpn on ubuntu 

### ISSUE THREAD

**Issue by cesarvspr** [nextdns/nextdns#519]
Not a single method of dns resolving after nextdns is installed. I tried everything. 

Not even the nordvpn dns setting can override the nextdns. 

What I tried and not worked: 

Nmcli dns setting for google. 
Nordvpn dns pointing to google.
Systemd resolving.

Tried all this with nextdns running and not running. Nothing works.

Actually I have a lot of work past due and a computer with no internet connection cuz it can't solve the dns.

Obs: everything is fine with ISP connection, I use other computers on this network. 

This sucks a lot.

Idk what to do. 

**Context**
 - Version [1.32.2]: 
 - Platform [ubuntu 20.04.2 LTS]:
![IMG_20210612_111314.jpg](https://user-images.githubusercontent.com/37849741/121780642-46871b80-cb6f-11eb-923b-b37e65fae913.jpg)

**Comment by ThePowerOfDreams** [comment]
> Actually I have a lot of work past due and a computer with no internet connection cuz it can't solve the dns.

Uninstall NextDNS, reboot, then try again when you actually have time to experiment.

**Comment by cesarvspr** [comment]
> > Actually I have a lot of work past due and a computer with no internet connection cuz it can't solve the dns.
> 
> Uninstall NextDNS, reboot, then try again when you actually have time to experiment.

Just uninstalling NextDNS doesnt work. But uninstalling nextdns and nordvpn works! Thank you so much!

**Comment by scafroglia93** [comment]
I don't think all the issues you report are issues to be reputed to nextdns; if you are unable to configure two services, forget it

I use nextdns with azirevpn and I don't have any kind of problem maybe, it would be necessary to check if that vpn toilet you have chosen is to be configured correctly

Also, I think that spending on the subscription of a precarious service like nordvpn is completely useless but, the money is yours for which.

Paying a vpn that bases its service on an indefinite number of servers rented at random makes no sense

**Comment by cesarvspr** [comment]
> Also, I think that spending on the subscription of a precarious service like nordvpn is completely useless but, the money is >yours for which.
>
>Paying a vpn that bases its service on an indefinite number of servers rented at random makes no sense

Thank you for you answer, I was angry when I wrote the post so you may be right about this being the wrong place for this kind of issue. But I'll leave it for someone with the same problem in the future. 

Can you explain a little bit more about why nordvpn isn't good?

**Comment by scafroglia93** [comment]
> > Also, I think that spending on the subscription of a precarious service like nordvpn is completely useless but, the money is >yours for which.
> >
> >Paying a vpn that bases its service on an indefinite number of servers rented at random makes no sense
> 
> Thank you for you answer, I was angry when I wrote the post so you may be right about this being the wrong place for this kind of issue. But I'll leave it for someone with the same problem in the future. 
> 
> Can you explain a little bit more about why nordvpn isn't good? 


Please PM me on telegram @scafroglia93

**Comment by DonRichards** [comment]
I have the same issue with my office VPN from time to time. When I connect to the office VPN it's not an issue. The issue happens when I disconnect. I'm running Ubuntu 21.04 with openvpn client. The problem only goes away when I stop Nextdns service so I doubt the issue is with Nordvpn. 

```shell
$ sudo systemctl stop nextdns
```

**Comment by DonRichards** [comment]
@cesarvspr Did you turn off the service before you uninstalled it? From my experience VPN services stay active after uninstalled if they aren't first disabled. I ask because from what I'm seeing, the act of disabling the service forces the OS to reinitialize the DNS cahce. 

To flush cache after 
```shell
$ sudo systemd-resolve --flush-caches
```

**Comment by cesarvspr** [comment]
Manually changing the dns also worked for me. Never had the problem again after uninstalling nextdns

**Comment by a-bianucci** [comment]
There is a setting in the app about Privacy Mode - I have disabled that (enabled the box) and magically I have now went about 12h without an issue. Maybe worth an attempt.
