### ISSUE TITLE
How to specify QUIC protocol in forwarder config?

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#520]
If I want to forward certain domains to a different DNS server and want to force nextdns cli to use QUIC, how do I specify it in the `forwarder` config?

**Comment by rs** [comment]
https://github.com/nextdns/nextdns/wiki/Split-Horizon

**Comment by timkgh** [comment]
Does this mean that QUIC will be negotiated automatically if supported by the server or is there a way to force QUIC?
