### ISSUE TITLE
Max inflight requests

### ISSUE THREAD

**Issue by maghuro** [nextdns/nextdns#522]
**Context**
 - CLI Version: 1.33.0 
 - Platform: Asus Merlin

After upgrading to last version, I can't initiate nextdns, it throws the error I attach.

`adminRT-AC86U/tmp/home/root nextdns start
Error: /jffs/nextdns/nextdns.init start: exit status 1: strconv.ParseUint: parsing "12977912": value out of range
nextdns.init: Unable to start`

The only new value I find on nextdns settings file is the max-inflight-requests which is 12977912

I haven't changed any settings, just upgraded.

**Comment by frankebobdk** [comment]
Same here!
