### ISSUE TITLE
NEXTDNS CLI UDM PRO UNIFI

### ISSUE THREAD

**Issue by Gimanuel** [nextdns/nextdns#523]
**Context**
 - CLI Version: 1.33.1
 - Platform: UDM PRO

Hello,

I've upgrade from 1.32.2 to 1.33.1 and impossible to configure it.

I've always this argument during the processing :

NextDNS Configuration ID: Setting up nextdns (1.33.1) ...
strconv.ParseUint: parsing "274878543944": value out of range
#-> ubnt-dpkg-cache configure
<-# ubnt-dpkg-cache configure
strconv.ParseUint: parsing "274878543944": value out of range

How to fix it?

Thank you very much for the support !

**Comment by joelberger76** [comment]
I'm having the same issue on Asus Merlin, both with 1.33 and 1.33.1.

Asus RT-AX88U
Asus Merlin 386.2_6

**Comment by rs** [comment]
Fixed by 1.33.2.
