### ISSUE TITLE
USG not working - 1.33.1

### ISSUE THREAD

**Issue by frankebobdk** [nextdns/nextdns#525]
CLI Version: 1.33.1
    Platform: Ubiquiti (edgeos)

Hello,

I've upgrade from 1.33.0 to 1.33.1 and the service won't start. 

If I try to restart it, I get the following error: 

**Error: /config/scripts/post-config.d/nextdns.sh stop: exit status 1:**

**Comment by rs** [comment]
what do you get for `nextdns config`?

**Comment by frankebobdk** [comment]
Nextdns config: 

bogus-priv true
timeout 5s
max-inflight-requests 256
config 63a246
cache-max-age 0s
max-ttl 0s
detect-captive-portals false
hardened-privacy false
setup-router true
auto-activate false
control /var/run/nextdns.sock
log-queries false
discovery-dns 
cache-size 0
report-client-info true
listen localhost:53
use-hosts true

and 

Nextdns log: 

Jun 20 00:45:23 UnifiSecurityGateway nextdns[18351]: Starting NextDNS 1.33.1/linux on 127.0.0.1:5342
Jun 20 00:45:23 UnifiSecurityGateway nextdns[18351]: Listening on TCP/127.0.0.1:5342
Jun 20 00:45:23 UnifiSecurityGateway nextdns[18351]: Starting mDNS discovery
Jun 20 00:45:23 UnifiSecurityGateway nextdns[18351]: Listening on UDP/127.0.0.1:5342
Jun 20 00:45:28 UnifiSecurityGateway nextdns[18351]: Setting up router

And after the service is trying to setting up the router, nothing happens.

**Comment by timkgh** [comment]
1.33.1 seems completely busted on Ubuntu 20.04 amd64 too, it doesn't respond to any requests.
https://github.com/nextdns/nextdns/issues/524#issuecomment-864473889

The releases would benefit from better testing, in particular when versions are automatically pushed to repos/PPAs. There have been a few bad ones recently.

**Comment by rs** [comment]
Fixed in 1.33.2, sorry about that.
