### ISSUE TITLE
Nextdns on Synology DSM 7.0

### ISSUE THREAD

**Issue by LiFeTecX** [nextdns/nextdns#529]
i am verly new to this but i am unable to install Nextdns CLI on my synoloy with DMS 7.0 i am able to SSH into my synology trying to run sh -c "$(curl -sL https://nextdns.io/install)" but nothing happens.

**Comment by mbnn** [comment]
Running DSM 7 here as well, did you sudo -s before running that command? Works fine here.

**Comment by LiFeTecX** [comment]
Thank you very much that was the sollution. like i sayed i am verly new to this ;)

**Comment by LiFeTecX** [comment]
New problem, when nextdns CLI is installed my synology DHCP server stops working. uninstall nextdns and the DHCP server starts again. 

i need the DHCP server on the synology to work in order to see what clients are connecting to.

**Comment by mbnn** [comment]
+

> New problem, when nextdns CLI is installed my synology DHCP server stops working. uninstall nextdns and the DHCP server starts again.
> 
> i need the DHCP server on the synology to work in order to see what clients are connecting to.

If you only use the DHCP of Syno for that, well, you dont need it for that :)
You can simply use your router's DHCP by editing the nextdns config: https://github.com/nextdns/nextdns/wiki/Split-Horizon

So for example if your router DHCP is 192.168.1.1 you can simply do:
```
sudo nextdns config set -forwarder localdomain.lan=192.168.1.1
sudo nextdns restart
```

**Comment by noob101x** [comment]
> > New problem, when nextdns CLI is installed my synology DHCP server stops working. uninstall nextdns and the DHCP server starts again.
> > i need the DHCP server on the synology to work in order to see what clients are connecting to.
> 
> I have the same issue, Synology DHCP server fails when NextDNS client is installed. I really need to use the Synology DHCP as NextDNS client is not getting DNS names from my router, that is currently handling DHCP. This is with all manner of settings enabled, including the above split-horizon. Router is a Netgear Orbi PRO.

Could you share how you configure the DHCP server on the NAS? I am in a similar situation (installed NextDNS CLI on my Synology NAS, DSM 7.0) but failed to establish DHCP server after that. I am not familiar with network setting so I thought there might be something wrong with my settings.

Have you found a solution to make it work (showing device names)?

**Comment by zerodayz1** [comment]
There is nothing special to configure on the Syno for DHCP. I'm sure you have configured it correctly, as there aren't a great deal of settings to make. 
This is due to the bug that needs fixing with NextDNS and it breaking Syno DHCP. 
You can test your setup by enabling DHCP on the Syno, Enabling NextDNS on the Syno, then check you are _not_ getting a DHCP address assigned (ipconfig /release > ipconfig /renew). Then stop the NextDNS service on Syno, try to get a DHCP address again, it should start working. If this is the case, come back here and we should re-open the case to get it resolved. I could really do with using DCHP from my syno too.

**Comment by noob101x** [comment]
For some reasons my configuration is not working for NextDNS . 

Here is the screenshot of my DHCP settings, and my router IP is 192.168.1.1. Although my devices are connected to the network but log (from NextDNS) didn't pick up any activities. Currently I have several profiles on nextdns (Base, Kids and etc..) but not sure if it is necessary to 'link' the profile to the configuration.

![dhcp settings](https://user-images.githubusercontent.com/93782214/141695390-af45c13b-bf0a-481a-a77a-74cce4ff86ab.PNG)

**Comment by zerodayz1** [comment]
I thought we established that NextDNS and Syno DHCP do not work together at present. You will need to _**disable**_ DHCP on Syno and use your router for now. Just add the primary DNS in the DHCP config to that of your Syno running NextDNS CLI and the secondary to the NextDNS server that you are given on the first config page of NextDNS. (For failover)
Check you are getting a DHCP address on a client and check the primary/secondary DNS settings are correct. Run a few queries and check the NextDNS CLI to ensure things are working.
Of course, check that NextDNS CLI is working correctly first, just by manually configuring a client to point at the Syno.

**Comment by sim-san** [comment]
> There is nothing special to configure on the Syno for DHCP. I'm sure you have configured it correctly, as there aren't a great deal of settings to make. 
> This is due to the bug that needs fixing with NextDNS and it breaking Syno DHCP. 
> You can test your setup by enabling DHCP on the Syno, Enabling NextDNS on the Syno, then check you are _not_ getting a DHCP address assigned (ipconfig /release > ipconfig /renew). Then stop the NextDNS service on Syno, try to get a DHCP address again, it should start working. If this is the case, come back here and we should re-open the case to get it resolved. I could really do with using DCHP from my syno too. 
> 

Is this Bug fixed ?

**Comment by zerodayz1** [comment]
This issue is not directly related to the DHCP issue. Might be an idea to open a new issue if it's still occurring.
I would like to see it fixed also.
