### ISSUE TITLE
Nextdns cli not taking 'listen' option in account

### ISSUE THREAD

**Issue by kovaxur** [nextdns/nextdns#53]
Hi,
I installed the nextdns cli on my Centos7 box, I tried to change the listen address/port in the configuration file, but it looks like, that the server/proxy only wants to listen on 0.0.0.0:53.

nextdns version 1.4.19

/etc/nextdns.conf

report-client-info true
detect-captive-portals false
bogus-priv true
use-hosts false
timeout 5s
auto-activate true
listen 127.0.0.1:10053
config XXX
log-queries true
hardened-privacy true
setup-router true

After executing "service nextdns restart", in the log files i see:

Jan 11 20:47:35 XXX systemd[1]: Started NextDNS DNS53 to DoH proxy..
Jan 11 20:47:35 XXX nextdns[12115]: Starting NextDNS 1.4.19/linux on :53
Jan 11 20:47:35 XXX nextdns[12115]: Listening on TCP/:53
Jan 11 20:47:35 XXX nextdns[12115]: Starting discovery resolver
Jan 11 20:47:35 XXX nextdns[12115]: Listening on UDP/:53

I would expect, that it would listen on port 10053 instead of 53.
Thanks

**Comment by kovaxur** [comment]
Okay, found the issue, so when I use the "setup-router" option, then the listen option is not used.

Just saw, that someone else had the same problem, maybe it would be helpful for troubleshooting, if there was a log line telling the user, that although they set the listen address, but it's not used.

Cheers :)

**Comment by rs** [comment]
Yes, I will add that.

**Comment by cesarvspr** [comment]
Did you something more to connect?
