### ISSUE TITLE
Unsupported OS when using new Rocky Linux

### ISSUE THREAD

**Issue by theshoehorn** [nextdns/nextdns#530]
Trying to install NextDNS using the "sh -c "$(curl -sL https://nextdns.io/install)"" script on newly forked Rocky Linux (RHEL fork) produces the below error:

ERROR: Unsupported OS: Linux
ERROR: Unknown bin location for 
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: 
INFO: LATEST_RELEASE: 1.33.2

**Comment by rs** [comment]
Please try again

**Comment by rs** [comment]
Fixed by https://github.com/nextdns/nextdns/commit/acadb681cf863bdbcbec5a155ed02d8ec5359be2

**Comment by theshoehorn** [comment]
Looks good now, thanks!!!
