### ISSUE TITLE
Asuswrt Merlin update

### ISSUE THREAD

**Issue by maghuro** [nextdns/nextdns#531]
Can't update on Merlin asuswrt

![Screenshot_2021-06-26-16-15-42-484_com server auditor ssh client](https://user-images.githubusercontent.com/1546139/123517600-d497f180-d699-11eb-83c8-334a5ffc4626.jpg)

**Comment by rs** [comment]
Should be fixed soon

**Comment by maghuro** [comment]
Error persists
