### ISSUE TITLE
Please don't add "exit 0" to dnsmasq.postconf on AsusWRT Merlin

### ISSUE THREAD

**Issue by jackyaz** [nextdns/nextdns#538]
It is not very considerate to other script developers.

**Comment by rs** [comment]
Installing nextdns will disable dnsmasq's DNS part, so any other scripts would likely conflict.

**Comment by jackyaz** [comment]
In YazFi's case, NextDNS' behaviour prevents DHCP configuration from being added

**Comment by jackyaz** [comment]
If you don't want to fix it, I'll code in a check for NextDNS and wipe out the exit line, no problem

**Comment by ThePowerOfDreams** [comment]
Send a PR instead of taking your ball and going home.

**Comment by jackyaz** [comment]
No PR needed, I've patched my script to remove the issue introduced by NextDNS
