### ISSUE TITLE
LAN dns server

### ISSUE THREAD

**Issue by Pantyhose-X** [nextdns/nextdns#539]
I hope that the Android version can create a LAN dns server
LAN dns server to NextDNS
LAN dns192.168.1.100>NextDNS>
My phone runs 24 hours

**Comment by rs** [comment]
You can probably run the CLI on a rooted android with some effort. This is not a good idea to run your LAN DNS on a phone tho. We won't support such setup.

**Comment by Pantyhose-X** [comment]
> You can probably run the CLI on a rooted android with some effort. This is not a good idea to run your LAN DNS on a phone tho. We won't support such setup.

Can be run in adb mode, no root required
