### ISSUE TITLE
Custom blacklist/whitelist grouping

### ISSUE THREAD

**Issue by fantom-x** [nextdns/nextdns#54]
When using the web interface, the domains in blacklist/whitelist are presented as a flat list. It would be more convenient to be able to group them so that it is easier to tell which domain is for what purpose there.

**Comment by rs** [comment]
This repository is dedicated to the NextDNS CLI client. Please use our subreddit [/r/nextdns](https://www.reddit.com/r/nextdns) to discuss feature requests on NextDNS.
