### ISSUE TITLE
UDM upgrade error

### ISSUE THREAD

**Issue by mojo333** [nextdns/nextdns#540]
Trying to upgrade nextdns via the CLI.

 - CLI Version: 1.33.2
 - Platform: Unifi UDM PRO
 - UDM Pro Version: 1.10.0-15.3686
 - Unifi Network Application Version: 6.3.51

Running the command `nextdns upgrade` results in an error when trying to update the package lists.

```
# nextdns upgrade
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.34.2
INFO: Upgrading NextDNS...
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Hit:5 http://deb.debian.org/debian stretch Release
Hit:6 https://deb.nodesource.com/node_8.x stretch InRelease
Err:7 https://apt.artifacts.ui.com stretch InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Err:8 https://apt-beta.artifacts.ui.com stretch InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Fetched 343 kB in 1s (263 kB/s)
Reading package lists...
E: Failed to fetch https://apt.artifacts.ui.com/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Failed to fetch https://apt-beta.artifacts.ui.com/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error: exit status 100
Error: non zero exit code: 1: OCI runtime error

```

**Comment by vincentbernat** [comment]
This seems unrelated to NextDNS. You should remove these `artifacts.ui.com` repository to fix this error.

**Comment by mojo333** [comment]
@vincentbernat the output I provided is all from the `nextdns upgrade` command i.e. part of nextdns' upgrade process, not from any commands I issued.

Saying that I then tried upgrading via `sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'` and picking upgrade. That worked just fine so not sure why the `nextdns upgrade` command didn't work.

**Comment by rs** [comment]
It’s an issue with how UDM work. The nextdns upgrade launches the upgrade from within the container instead of outside. Please use the other method with curl for now.
