### ISSUE TITLE
NextDNS CLI run command reduce stdout logging

### ISSUE THREAD

**Issue by adhodgson1** [nextdns/nextdns#541]
I'm running the CLI now via my own Docker image which runs using the nextdns run command with relevant arguments. I'm not specifying log arguments at all however the container dumps lots of info messages out via stdout, for example:
INFO: 21:35:27 Connected [2001:19f0:7401:85d3:5400:2ff:fec8:749f]:443 (con=1ms tls=3ms, TCP, TLS13)
INFO: 21:36:21 Connected [2a00:11c0:8:4::9]:443 (con=0ms tls=2ms, TCP, TLS13)
INFO: 21:37:30 Connected 37.252.230.153:443 (con=0ms tls=3ms, TCP, TLS13)
INFO: 21:38:58 Connected 37.252.230.153:443 (con=1ms tls=2ms, TCP, TLS13)
It would be good to explore options for reducing this, for example being able to set  log type that will be sent to stdout, I would say these messages are more DEBUG than INFO.

**Comment by agneevX** [comment]
Do you have `log-queries` set to `false` in your config file?

**Comment by adhodgson1** [comment]
I am using the run command so don’t have a config file. However my belief was log-queries was set to false by default. Also I’m not logging queries, its just the endpoint changes that are being logged.
