### ISSUE TITLE
EdgeRouter nextdns cli stopped

### ISSUE THREAD

**Issue by fototeddy** [nextdns/nextdns#544]
**Context**
 - CLI Version: 1.32.3
 - Platform: EdgeOS v2.0.9-hotfix.1

I have NextDNS Cli running on my EdgeRouter. NextDNS is stopping after some days and status says "Stopped" Log does not give any hint why it hast stopped and I have to restart it manually. 
Is there anyway top restart NextDNS automatically or find out WHY it is stopping after some days?

**Comment by rs** [comment]
Please use the last revision
