### ISSUE TITLE
nextdns service on Unifi USG fails sometimes with cerificate signed by unknown authority

### ISSUE THREAD

**Issue by deverton** [nextdns/nextdns#546]
**Context**
 - CLI Version: 1.34.2
 - Platform: Unifi USG3P

Sometimes the `nextdns` just stops working with the below error:

```
Jul 15 14:23:11 USG nextdns[4210]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07:a8c1::}: exchange: roundtrip: x509: certificate signed by unknown authority
```

If I `curl` the endpoint with certificate chain verification disabled I get:

```
admin@USG:~$ curl -vk https://dns.nextdns.io
* About to connect() to dns.nextdns.io port 443 (#0)
*   Trying 119.252.95.133...
* connected
* Connected to dns.nextdns.io (119.252.95.133) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=dns.nextdns.io
*        start date: 2021-05-20 23:00:04 GMT
*        expire date: 2021-08-18 23:00:04 GMT
*        issuer: C=US; O=Let's Encrypt; CN=E1
*        SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
```

It appears that the certificate chain served up by NextDNS isn't in the CA certificate trust store of the Unifi USG.

**Comment by deverton** [comment]
Doing this https://github.com/nextdns/nextdns/issues/500#issuecomment-853140837 seems to fix it but I thought that wasn't needed in newer versions.

**Comment by deverton** [comment]
Even after updating the CA certificates the issue still occurs intermittently:

```
Jul 15 20:26:27 USG nextdns[4210]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07:a8c1::}: exchange: roundtrip: x509: certificate signed by unknown authority
```

**Comment by smhex** [comment]
Same here on my USG4 Pro. Symptoms came up today...I had to disable the service

**Comment by shjryan** [comment]
Experiencing the same or similar issue on my USG3P. Reinstalled CA certificates and the issue still occurs intermittently. 

```
Jul 18 11:20:48 nextdns[12679]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07:a8c1::}: exchange: roundtrip: x509: certificate signed by unknown authority
Jul 18 11:21:08 nextdns[12679]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io}: exchange: roundtrip: dial tcp: lookup dns.nextdns.io on 127.0.0.1:53: read udp 127.0.0.1:60122->127.0.0.1:53: i/o timeout
Jul 18 11:21:08 nextdns[12679]: Query 10.0.10.10 UDP 65 media-sea1-1.cdn.whatsapp.net. (qry=47/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
... a lot of context deadline exceeded messages
```
Haven't been able to find any solution.

**Comment by vincentbernat** [comment]
In case the issue is not intermittent, could you do:

```
curl -v https://dns.nextdns.io --resolve dns.nextdns.io:443:45.90.28.0
curl -v https://dns.nextdns.io --resolve dns.nextdns.io:443:2a07:a8c0::
curl -v https://dns.nextdns.io --resolve dns.nextdns.io:443:45.90.30.0
curl -v https://dns.nextdns.io --resolve dns.nextdns.io:443:2a07:a8c1::
```

And check if each of them succeed. Notably, the output should say:

```
*  subjectAltName: host "dns.nextdns.io" matched cert's "dns.nextdns.io"
*  issuer: C=US; O=Let's Encrypt; CN=E1
*  SSL certificate verify ok.
```

Adapt the IP addresses with the ones you get on the error.

**Comment by deverton** [comment]
Just ran those `curl` commands and they all executed fine. However I can still see recent incidents in the `nextdns logs` output

```
Jul 19 09:09:34 USG nextdns[4210]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07:a8c1::}: exchange: roundtrip: x509: certificate signed by unknown authority
Jul 19 09:09:54 USG nextdns[4210]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io}: exchange: roundtrip: dial tcp: lookup dns.nextdns.io on 127.0.0.1:53: read udp 127.0.0.1:59435->127.0.0.1:53: i/o timeout
Jul 19 09:09:54 USG nextdns[4210]: Query 127.0.0.1 UDP A dns.nextdns.io. (qry=32/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Jul 19 09:09:54 USG nextdns[4210]: Query 127.0.0.1 UDP AAAA dns.nextdns.io. (qry=32/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Jul 19 09:09:54 USG nextdns[4210]: Query 127.0.0.1 UDP A dns.nextdns.io. (qry=32/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Jul 19 09:09:54 USG nextdns[4210]: Query 127.0.0.1 UDP AAAA dns.nextdns.io. (qry=32/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
```

**Comment by vincentbernat** [comment]
Could it be related to your ISP trying to intercept some web pages to display some messages? In your case, the issue being intermittent, this is a bit difficult to debug. I will add more details to this error to better understand the issue.

**Comment by deverton** [comment]
It's a possibility but it only seems to affect calls to `nextdns` and only from the USG. I've got Firefox configured to use DoH (bypassing the USG DNS server) and I've not noticed any issues there.

I'm trying to catch a failure in real time with the following script running on the USG but so far nothing.

```sh
#!/bin/sh

# baseline
curl -v https://dns.nextdns.io --resolve dns.nextdns.io:443:45.90.28.0 2>&1 | grep -A 7 "SSL connection" > output.1

while true; do
        curl -v https://dns.nextdns.io --resolve dns.nextdns.io:443:45.90.28.0 2>&1 | grep -A 7 "SSL connection" > output.2
        if ! diff -q output.1 output.2; then
                break
        fi
        echo -n "."
        sleep 30
done

echo "done"
```

**Comment by vincentbernat** [comment]
Maybe you'll get better luck with tcpdump:

```
tcpdump -pni outputinterface -w /tmp/nextdns.pcap host 45.90.28.0 and port 443
```

However, the file may get too big. In this case, you could be smarter with a script like this:

```sh
tcpdump -pni outputinterface -w /tmp/nextdns.pcap -W 3 -C 10 host 45.90.28.0 and port 443 &
pid=$!
while true; do
   nextdns log | grep -F "certificate signed by unknown authority" && break
   sleep 10
done
kill $pid
```

This will use only 3×10MB, you can tune down.

Alternatively, if you have a regular workstation that can stays up until the problem happens, you can just get tcpdump over SSH:

```sh
ssh yourUSG tcpdump -pni outputinterface -w - -U host 45.90.28.0 and port 443 > usg.pcap
```

Once you have a pcap, Wireshark could easily spot the failed handshake.

**Comment by deverton** [comment]
Oh right, `tcpdump`. That's a much better idea :) I'll try that and see what I can get.

**Comment by vincentbernat** [comment]
Alternatively, you can try the snapshot in #550. It just adds more logging when such an error happens. It should point us in the right direction. There is a short blob explaining how to install it: https://snapshot.nextdns.io/pr-550/index.html

**Comment by smhex** [comment]
Hi, tried snapshot #550. Installation went fine - startup log shows the error again:

```
Jul 19 09:12:38 USG-PRO-4 nextdns[4535]: Starting NextDNS v0.0.0-SNAPSHOT-1747a8e/linux on :53
Jul 19 09:12:38 USG-PRO-4 nextdns[4535]: Listening on TCP/:53
Jul 19 09:12:38 USG-PRO-4 nextdns[4535]: Starting mDNS discovery
Jul 19 09:12:38 USG-PRO-4 nextdns[4535]: Listening on UDP/:53
Jul 19 09:12:41 USG-PRO-4 nextdns[4535]: Query 192.168.XX.XX UDP 65 weather-edge.apple.com. (qry=40/res=12) 1255ms : doh resolve: x509: certificate signed by unknown authority
Jul 19 09:12:41 USG-PRO-4 nextdns[4535]: Query 192.168.XX.XX UDP 65 weather-data.apple.com. (qry=40/res=12) 1268ms : doh resolve: x509: certificate signed by unknown authority
Jul 19 09:12:41 USG-PRO-4 nextdns[4535]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07:a8c1::}: exchange: roundtrip: x509: certificate signed by unknown authority (subject=CN=ISRG Root X2,O=Internet Security Research Group,C=US, issuer=CN=ISRG Root X1,O=Internet Security Research Group,C=US)
Jul 19 09:12:43 USG-PRO-4 nextdns[4535]: Setting up router
```

Output of curl shows
```
curl -v https://dns.nextdns.io --resolve dns.nextdns.io:443:45.90.28.0
* Added dns.nextdns.io:443:45.90.28.0 to DNS cache
* About to connect() to dns.nextdns.io port 443 (#0)
*   Trying 45.90.28.0...
* connected
* Connected to dns.nextdns.io (45.90.28.0) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html
```

Hope that helps

**Comment by vincentbernat** [comment]
@smhex  OK, in your case, it's your system certificate which is too old.  https://github.com/nextdns/nextdns/issues/500#issuecomment-853140837 should have fixed that. Alternatively, you can try the following snapshot: https://github.com/nextdns/nextdns/pull/548

**Comment by smhex** [comment]
Thanks @vincentbernat, I did an update of the root certificates in the meantime and it worked. Nevertheless, I will observe the logs. I am still wondering why it happened yesterday for the first time...

**Comment by vincentbernat** [comment]
❦ 19 July 2021 02:50 -07, smhex:

> Thanks @vincentbernat, I did an update of the root certificates in the
> meantime and it worked. Nevertheless, I will observe the logs. I am
> still wondering why it happened yesterday for the first time...

Let's Encrypt is now signing its certificates with a newer root
certificate which was not included on "old" hardware. So, when
certificates get renewed from now, you get the new root certificate.

See here:
https://community.letsencrypt.org/t/certbot-users-preparing-for-the-isrg-root-transition-january-11-2021/138059.

So, it may also explain why this is intermittent for some people:
depending on which node you connect to, the node may have renewed its
certificate after July 1st and gets the problem or not. And the
bootstrap is done on an anycast node, so it depends on your location.

**Comment by smhex** [comment]
Thank you for your explanation @vincentbernat 👍

**Comment by deverton** [comment]
I updated the `ca-certificates` bundle on the USG to include the new root for Let's Encrypt shortly after raising this issue but still had problems. However, since I've been trying to capture some packets I haven't seen the issue again. It does seem like it might have been something else now. I'll keep monitoring.

**Comment by deverton** [comment]
I have been unable to reproduce this over the past few days which makes me think there was something in the network path at issue. I'd say this can be closed for now.

**Comment by sodabrew** [comment]
I had to manually fetch the new Let's Encrypt roots onto my USG:

```
admin@ubnt:/config/nextdns$ ./nextdns version
nextdns version 1.32.2

admin@ubnt:/config/nextdns$ ./nextdns upgrade
ERROR: Cannot get latest version:
INFO: OS: edgeos
INFO: GOARCH: mips64_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /config/nextdns/nextdns
INFO: INSTALL_RELEASE:
ERROR: Cannot detect running environment.
Error: exit status 1

admin@ubnt:/etc/ssl/certs$ sudo curl -O https://letsencrypt.org/certs/isrg-root-x2.pem
admin@ubnt:/etc/ssl/certs$ sudo curl -O https://letsencrypt.org/certs/isrgrootx1.pem

admin@ubnt:/config/nextdns$ ./nextdns upgrade
INFO: OS: edgeos
INFO: GOARCH: mips64_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /config/nextdns/nextdns
INFO: INSTALL_RELEASE: 1.34.2
INFO: Upgrading NextDNS...
NextDNS installed and started using edgeos init

admin@ubnt:/config/nextdns$ ./nextdns version
nextdns version 1.34.2
```

The NextDNS service was crashing due to the certificate failures, resulting in "THE INTERNET IS DOWN!" to be shouted across the house. Need to work on a PR to adjust the volume of these alerts. The steps above reduce the volume in terms of number of failures. But also would be nice to turn down the volume in dB of the shouting.

**Comment by ycUygB1** [comment]
The USG is a buggy piece of equipment that will soon be discontinued.  I would not blame any problem you are experiencing on NextDNS.  Try using an EdgeRouter and see if you have the same problem.

**Comment by deverton** [comment]
Well, to be fair I've not seen this issue since so I'll close this.
