### ISSUE TITLE
Deactivate command doesn't work

### ISSUE THREAD

**Issue by bclnr** [nextdns/nextdns#553]
**Context**
 - CLI Version: 1.34.2
 - Platform: Ubuntu 21.04

Executing `sudo nextdns deactivate` doesn't work.
After executing this, my "setup" page shows I still use NextDNS.
Also no deactivation appears in "nextdns log".

**Comment by vishalvshekkar** [comment]
I noticed the same.

Running nextdns-cli on a raspberry pi on my home network.

Executing `sudo nextdns deactivate` does nothing.
- The blocked pages continue to be blocked.
- The blocked domains appear on the NextDNS logs.
- The setup page shows that I'm using the NextDNS config which was supposed to be deactivated.

Not sure what this command is supposed to achieve.
