### ISSUE TITLE
add support for gentoo linux

### ISSUE THREAD

**Issue by formula-spectre** [nextdns/nextdns#564]
in a nutshell, `go build`, then `./nextdns start` says system not supported. the installer also says the following:
```
ERROR: Unsupported OS: GNU/Linux ID=gentoo
ERROR: Unknown bin location for 
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: 
INFO: INSTALL_RELEASE: 1.36.0
ERROR: Cannot detect running environment.
```

**Comment by rs** [comment]
openrc is supported: https://github.com/nextdns/nextdns/blob/master/host/service/openrc/service.go

**Comment by formula-spectre** [comment]
yeah openrc is supported, but nextdns dies since gentoo it's not "supported", even though openrc is

**Comment by rs** [comment]
The installer does not support gentoo yet. Please try installing the binary manually in `/usr/bin` and call `nextdns install` to see if it would work.

**Comment by formula-spectre** [comment]
I tried to execute the bin in the git folder (after a `go build`, via `./nextdns install`) but it still says `system not supported`

**Comment by LordRishav** [comment]
+1 would want to see this too

**Comment by ran-dall** [comment]
@rs I'm putting an ebuild to address this and to contribute into the Gentoo's Guru overlay; however the amount Go dependencies are killing me due to having to explicitly declare every dependency of every dependency of every dependency. Would it be possible to vendor the dependencies? 

Ref: https://devmanual.gentoo.org/eclass-reference/go-module.eclass/index.html

I'd also be happy to share what I have so far.

FWIW I've been told that a simple `bin` isn't gonna cut it because there's several things are aren't up to Gentoo standards. However, I've made patches to address everything that has been brought to my attention.

**Comment by rs** [comment]
Can't the build system use go module or the content of go.sum?

The dep inflation is due to the quic/http3 package. You can ignore most of the dep if you don't compile with the `http3` tag.

Here is the dep graph without http3:
```
github.com/nextdns/nextdns github.com/Microsoft/go-winio@v0.5.0
github.com/nextdns/nextdns github.com/cespare/xxhash@v1.1.0
github.com/nextdns/nextdns github.com/denisbrodbeck/machineid@v1.0.1
github.com/nextdns/nextdns github.com/hashicorp/golang-lru@v0.5.4
github.com/nextdns/nextdns github.com/vishvananda/netlink@v1.1.0
github.com/nextdns/nextdns github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f
github.com/nextdns/nextdns golang.org/x/net@v0.0.0-20210813160813-60bc85c4be6d
github.com/nextdns/nextdns golang.org/x/sys@v0.0.0-20210823070655-63515b42dcdf
github.com/Microsoft/go-winio@v0.5.0 github.com/pkg/errors@v0.9.1
github.com/Microsoft/go-winio@v0.5.0 github.com/sirupsen/logrus@v1.7.0
github.com/Microsoft/go-winio@v0.5.0 golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c
github.com/cespare/xxhash@v1.1.0 github.com/OneOfOne/xxhash@v1.2.2
github.com/cespare/xxhash@v1.1.0 github.com/spaolacci/murmur3@v0.0.0-20180118202830-f09979ecbc72
github.com/vishvananda/netlink@v1.1.0 github.com/vishvananda/netns@v0.0.0-20191106174202-0a2b9b5464df
github.com/vishvananda/netlink@v1.1.0 golang.org/x/sys@v0.0.0-20190606203320-7fc4e5ec1444
github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f golang.org/x/sys@v0.0.0-20200217220822-9197077df867
golang.org/x/net@v0.0.0-20210813160813-60bc85c4be6d golang.org/x/sys@v0.0.0-20210423082822-04245dca01da
golang.org/x/net@v0.0.0-20210813160813-60bc85c4be6d golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1
golang.org/x/net@v0.0.0-20210813160813-60bc85c4be6d golang.org/x/text@v0.3.6
github.com/sirupsen/logrus@v1.7.0 github.com/davecgh/go-spew@v1.1.1
github.com/sirupsen/logrus@v1.7.0 github.com/pmezard/go-difflib@v1.0.0
github.com/sirupsen/logrus@v1.7.0 github.com/stretchr/testify@v1.2.2
github.com/sirupsen/logrus@v1.7.0 golang.org/x/sys@v0.0.0-20191026070338-33540a1f6037
golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1 golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68
golang.org/x/text@v0.3.6 golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e
```

**Comment by ran-dall** [comment]
> Can't the build system use go module...

I wish. It would be much easier than the way it currently is set up.

> ...or the content of go.sum?

Not that I know of.

> The dep inflation is due to the quic/http3 package. You can ignore most of the dep if you don't compile with the http3 tag.

I don't think it matters. Basically, it wants to have every dependency of every package listed recursively, unless, it's in a 'vendor' file...this is per the eclass, or at least my understanding of it.

Here's an example of what I'm talking about...

```
go: github.com/Microsoft/go-winio@v0.5.0 requires
        github.com/pkg/errors@v0.9.1: reading file:///var/tmp/portage/net-dns/nextdns-1.37.3/temp/go-proxy/github.com/pkg/errors/@v/v0.9.1.mod: no such file or directory
``` 

I don't know why it tries to look for mods like that. To fix it, I have to manually the `/go.mod` to all the dependencies...which is where the pain point is.

**Comment by rs** [comment]
in master most deps are removed as a result of removing the http3 support (waiting for a better library). It should make your life easier.

**Comment by vincentbernat** [comment]
❦ 15 November 2021 15:46 -08, Randall:

> @rs I'm putting an ebuild to address this and to contribute into the
> Gentoo's Guru overlay; however the amount Go dependencies are killing
> me due to having to explicitly declare every dependency of every
> dependency of every dependency. Would it be possible to vendor the
> dependencies?

Maybe as a compromise, dependencies could be vendored in a specific
release tarball instead of the Git tree? Would it work for you?
Something like nextdns-vendored-1.40.1.tar.gz (containing both NextDNS
sources and vendored sources).

**Comment by ran-dall** [comment]
@rs I don't think it matters because it starts to look down the dep tree, I think as long as there are packages with dependencies, it will climb down. So far, I've seen it go down 3-4 levels deep. I don't think there's a way to make it aware of the `http3` build flag.

@vincentbernat Maybe. That's not a bad suggestion. However, I'm pretty Gentoo would be against it though, since it's really working around eclass as opposed to using it.

**Comment by ran-dall** [comment]
@rs FWIW I made a branch on my overlay to work on this: https://github.com/ran-dall/portage-overlay/tree/add-nextdns. What I have so far is in there.

**Comment by ran-dall** [comment]
I had some time today to address the go modules issue, so I did, and updated the branch. It installs just fine now. 

However there are other issues we'd need to address...

- For consideration as an official ebuild, Gentoo would require us to install both the systemd unit and openrc init.d file. That bring us up an issue with the installer function.
- Gentoo would 'prefer' (not sure how hard of a requirement it is) we don't require users to run any install or upgrade commands. Things should work out of the box, and upgrades should be handled to Portage.

In the ebuild's directory, there's a `/files` directory, where I've started some solutions to address this. I have both the systemd unit and the openrc init.d file. The ebuild already deploys them. I've also made a preliminary patch that patches out the install and upgrade function (which I've removed entirely in the current ebuild). However, this brings us to the problem that the installed binary doesn't run as trying to `start` displays the `system not supported` error. So this is probably not the best way to handle this.

So I'm open to suggestions...

**Comment by rs** [comment]
Here is the detection code for gentoo (openrc): https://github.com/nextdns/nextdns/blob/3ffa7c849fc1cae5734f47d4977b71a2984ec7d4/host/service/openrc/service.go#L21

Is there something there that would fail in your environment?

**Comment by ran-dall** [comment]
@rs Thanks for getting back to me. I found the issue. I'm not installing `/etc/nextdns.conf`. Is there a way you can provide me a default I can deploy with the ebuild with the install by Portage?

**Comment by rs** [comment]
just type `nextdns config`, it will output the default config.

**Comment by ran-dall** [comment]
It gives me `system not supported` when I try `nextdns config`.

**Comment by dlrudie** [comment]
@rs Sure, but in that case I want to dig a little deeper to handle systemd-resolved automatically. If you don't stop the systemd-resolved service beforehand nextdns will appear to have installed and started correctly, but when checking nextdns log it will say that it failed to start because port 53 is already in use.

Note: I didn't look at how the installer handles Ubuntu or other systemd-based installations to see if there's already something in place to account for systemd-resolved.

**Comment by x0rzavi** [comment]
Hi, I've made an ebuild for gentoo here, https://github.com/x0rzavi/x0rzavi-overlay/blob/main/net-dns/nextdns/nextdns-1.37.11.ebuild
Although it works perfectly in my case, it needs more testing and work to make it Gentoo's ebuild policy conformant. I'll try to keep the package updated.

**Comment by ran-dall** [comment]
> Although it works perfectly in my case, it needs more testing and work to make it Gentoo's ebuild policy conformant. 

FWIW there isn't a way to make this Gentoo compliant, There was a discussion (last year, if I'm not mistaken) on IRC, and there's a lot in the package that Gentoo doesn't agree with or support. At the end of it all, we decided against merging this in any official overlay channel; hence, I decided to no longer move forward with the ebuild.
