### ISSUE TITLE
Quad9 support / partnership

### ISSUE THREAD

**Issue by BirdInFire** [nextdns/nextdns#566]
Actually Quad9 is per test, the best at blocking bad website etc.
Can you add a way in security (disabled by default (or not your call)),

To do something like this.
When enabled every call of your client (with cache shared of course) is done by your server to Quad9.
If the response is NXdomain (and your own resolution do not generate NX domain) you cache It and block it to the client.

Its a way to add even more security without really forward any request, since these request are cached on your dns, and are done independently than the client.

Hope to see that soon.

**Comment by rs** [comment]
We have something even better cooking, stay tuned.

I'm closing this ticket as it is not related to CLI.

**Comment by BirdInFire** [comment]
@rs is the https://headwayapp.co/nextdns-changelog always where you announce something ?
And have you an idea if you will announce that soon (I do not ask a precise date but at least a month or a year) ? I ask because I search a way to replace quad9 (slower in my region), so it's to see if I wait your announce of simply search something else during the time you announce.

**Comment by rs** [comment]
We do no longer use this changelog. Twitter is the best way to get news. It's almost ready, so you won't have to wait long.

**Comment by scottbeamer** [comment]
What does this even mean?

**Comment by ignoramous** [comment]
> What does this even mean?

OP wants NextDNS to also block whatever Quad9 blocks by querying it just-in-time for users who opt-in to do so.
