### ISSUE TITLE
update from 1.10.1 to 1.36.0 doesn't work

### ISSUE THREAD

**Issue by goodale** [nextdns/nextdns#567]
**Context**
 - CLI Version:   1.10.1 to 1.36.0
 - Platform: Ubuntu 20.04 LTS

&lt;Describe the bug>

Running the provided install/upgrade script results in the error below:
 sudo sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'

[sudo] password for XXX: 
INFO: OS: ubuntu
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.36.0
**u) Upgrade NextDNS from 1.10.1 to 1.36.0**
c) Configure NextDNS
r) Remove NextDNS
e) Exit
**Choice (default=u): u**
INFO: Upgrading NextDNS...
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]  
Get:4 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1175 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [853 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [24.6 kB]
Hit:5 https://dl.ubnt.com/unifi/debian stable InRelease                         
Fetched 2381 kB in 1s (2786 kB/s)              
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**nextdns is already the newest version (1.10.1).**

**Comment by rfyiamcool** [comment]
😅

**Comment by rs** [comment]
Please try to uninstall then reinstall.
