### ISSUE TITLE
Add a way to avoid less secure server on cli

### ISSUE THREAD

**Issue by BirdInFire** [nextdns/nextdns#569]
I have done some test with https://www.grc.com/dns/dns.htm

and I have found some of your serveur (or a least your partner server to be more exact) done very bad in spoofability test, and I hope to see a settings to make the cli-client avoir them and only use the more secure one (even if it add latency).

**Comment by rs** [comment]
Please show the output you see. You are probably not testing our servers as none of them should show this vulnerability. There is no such thing as "partner servers", they are all operated by us.

**Comment by BirdInFire** [comment]
@rs no problem let me some time (I have to relaunch the test upload that asap)

**Comment by BirdInFire** [comment]
So I have launched the test, in time I will explain how I have had this result,

Unifi dream machine pro, use the dynamic donc on my domain and add it to link my ipv4, add the ipv4 to the "internet" zone.
after that I connect on it with ssd and add my config on the NextDNS file an restart the service.

The first result is good the two other not brillant, and after there is a list of ip not well tested.

there is screenshot on Swiss transfer (valid 7 day, downloadable 20 time) : 
https://www.swisstransfer.com/d/41cde814-8bf1-45bd-ae47-858074d85d8c

**Comment by BirdInFire** [comment]
But if I use the profile directly on my computer or phone (apple) this problem don't appear, it's why I have posted here since it happen only with cli (not tested on android or windows)

**Comment by rs** [comment]
Can you please try to reproduce again?

**Comment by BirdInFire** [comment]
@rs it's fixed the bad one don't appear now thanks !
