### ISSUE TITLE
install script hangs (never exits from install)

### ISSUE THREAD

**Issue by dave14305** [nextdns/nextdns#57]
Installer script never returns from final install action:
/jffs/nextdns/nextdns install -config=a12345 -report-client-info=true -hardened-privacy=false -setup-router=true -auto-activate=true

Service runs but doesn’t seem to daemonize, as if running in foreground.

**Comment by rs** [comment]
Merlin?

**Comment by dave14305** [comment]
Yes, John’s fork.

**Comment by rs** [comment]
Is it a regression with the last rev or it never worked?

**Comment by dave14305** [comment]
Regression. Worked fine this morning.

**Comment by dave14305** [comment]
NextDNS 1.4.20/linux Was last version I ran cleanly.

**Comment by rs** [comment]
Do you get the same issue on Merlin (non fork)?

**Comment by dave14305** [comment]
I can’t test that since it would require reflashing the router.

**Comment by dave14305** [comment]
Downloaded 1.4.21 manually and it installs OK.

**Comment by brainsik** [comment]
This is happening for me as well on EdgeOS after upgrading just now to 1.4.23. All was fine on 1.4.19.

**Comment by Sc0th** [comment]
+1 happening on Debian (k8s pod)

**Comment by rs** [comment]
Fix is on its way.

**Comment by rs** [comment]
Please confirm v1.4.24 is fixing the issue.

**Comment by dave14305** [comment]
> Fix is on its way.

Works!

**Comment by Sc0th** [comment]
Much better, thank you!
