### ISSUE TITLE
v1.37.1 update broke the stable repo

### ISSUE THREAD

**Issue by valynor** [nextdns/nextdns#571]
Can't update to 1.37.1, Linux Mint updater has been throwing this error for the last ~20min: 

Failed to fetch https://repo.nextdns.io/deb/dists/stable/main/binary-i386/Packages.gz  File has unexpected size (422 != 426). Mirror sync in progress? [IP: 2606:4700:20::681a:94 443]
Hashes of expected file:
 - Filesize:426 [weak]
 - SHA512:7bc899c897b7e6da1b2ce4913c0055342a21820a4d52e983769e4c71b1d200531b4a0c3f432d999444a3f0bff44419147c9cfe0cc760d064ded201d90581d715
 - SHA256:4a0ee0d49a934fa8954e649991cfe80db3f6538ef03f2d2a661d2208f7134647
 - SHA1:108b3131d90758f848911c99d8f422c75540f92a [weak]
 - MD5Sum:e560b1328be6dc7b59e34976e9c733ac [weak]
Release file created at: Tue, 07 Sep 2021 21:16:41 +0000
Failed to fetch https://repo.nextdns.io/deb/dists/stable/main/binary-amd64/Packages.gz  Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by rs** [comment]
The new revision was being built. Does it still happen?

**Comment by valynor** [comment]
Yes:

Failed to fetch https://repo.nextdns.io/deb/dists/stable/main/binary-i386/Packages.gz  File has unexpected size (422 != 426). Mirror sync in progress? [IP: 2606:4700:20::ac43:482e 443]
Hashes of expected file:
 - Filesize:426 [weak]
 - SHA512:7bc899c897b7e6da1b2ce4913c0055342a21820a4d52e983769e4c71b1d200531b4a0c3f432d999444a3f0bff44419147c9cfe0cc760d064ded201d90581d715
 - SHA256:4a0ee0d49a934fa8954e649991cfe80db3f6538ef03f2d2a661d2208f7134647
 - SHA1:108b3131d90758f848911c99d8f422c75540f92a [weak]
 - MD5Sum:e560b1328be6dc7b59e34976e9c733ac [weak]
Release file created at: Tue, 07 Sep 2021 21:16:41 +0000
Failed to fetch https://repo.nextdns.io/deb/dists/stable/main/binary-amd64/Packages.gz  Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by mbk87** [comment]
Now works like a charm :-)

**Comment by valynor** [comment]
Still broken for me, slightly different error message: 

Failed to fetch https://repo.nextdns.io/deb/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (426 != 423). Mirror sync in progress? [IP: 2606:4700:20::681a:194 443]
Hashes of expected file:
 - Filesize:423 [weak]
 - SHA512:03744ffd20b7236a9e6e8da667708cf41d35d6508750bebee0a00db8f925226d0042e7879d1b33c07401fa5a07cb9d3f96a1a4dfb28584105c9c3a62cf098dba
 - SHA256:768764286c65344460e8cff175772a9d3e5939ec7e523c88cf9e5f5c4dee4c38
 - SHA1:6e6683da9b3e7cc2221206874b25856e508c08eb [weak]
 - MD5Sum:fd71f29459d492e4538b5c13f19f5407 [weak]
Release file created at: Tue, 07 Sep 2021 21:16:41 +0000
Failed to fetch https://repo.nextdns.io/deb/dists/stable/main/binary-i386/Packages.gz  Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by valynor** [comment]
Works again.
