### ISSUE TITLE
Use the specified server node and specified account

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/nextdns#572]
doh: `https://ipv4-zepto-tyo-1.edge.nextdns.io/fb896a?name=www.google.com`

dot: `tls://fb896a.ipv4-zepto-tyo-1.edge.nextdns.io/`

🤔

Sometimes the results of the system's automatic matching are not so good, but the manual selection will be much better.

**Comment by rs** [comment]
This repository is dedicated to the CLI client. For other types of issues please use https://help.nextdns.io.
