### ISSUE TITLE
Update from 1.36.0 to 1.37.1 not working on OpenWRT 21.02.0

### ISSUE THREAD

**Issue by jjpinom** [nextdns/nextdns#573]
**Context**
 - CLI Version: 1.36.0
 - Platform: OpenWrt 21.02.0, r16279-5cc0535800 on WRT3200ACM Router

On OpenWrt 19.07.8 package repository, the current NextDNS CLI version is 1.37.1.

I updated to OpenWrt 21.02.0 and got the CLI version 1.36.0

I tried to update the package using LuCI update tool but the most recent version is 1.36.0, and hence the update is not available.

I then tried to update using the CLI and got the folowing:

root@jpRouter:~# nextdns version
nextdns version 1.36.0
root@jpRouter:~# nextdns upgrade
INFO: OS: openwrt
INFO: GOARCH: armv7
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/sbin/nextdns
INFO: INSTALL_RELEASE: 1.37.1
INFO: Upgrading NextDNS...
Downloading https://downloads.openwrt.org/releases/21.02.0/targets/mvebu/cortexa9/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/releases/21.02.0/targets/mvebu/cortexa9/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9_vfpv3-d16/telephony/Packages.sig
Signature check passed.
root@jpRouter:~# nextdns restart
root@jpRouter:~# nextdns version
nextdns version 1.36.0

**Comment by rs** [comment]
Please try again tomorrow, it might take some time for the new revision to be pushed on their repos.

**Comment by jjpinom** [comment]
Ready. Update completed!
