### ISSUE TITLE
Load allow/block-list from cli

### ISSUE THREAD

**Issue by BirdInFire** [nextdns/nextdns#578]
Actually i have a custom made blocklist but this list is a nightmare to maintain because it's updated every day by a script who check every day if a website is up or down and if a website disappear after some time he remove it by himself.

This request come to add to the request : https://github.com/nextdns/nextdns/issues/430

it's to add a way to actually load a file (json or simple domain list) with a cli command in the previous feature request.

Note i ask this manual feature since maintain a personal allow/deny list with hundred of domain in it totally manually from an interface is really a pain.

**Comment by BirdInFire** [comment]
Note on why i ask this : 
If you allow the previous request but do not add a restriction on the speed in adding entry and add a way to load a json file (or any file) with a list, you will risque some noob-dev, to create their own script to do this load list, and if some of them do an error (infinite loop etc) you will risk to have some DDOS coming from VPS well known very difficult to block.

But if you allow this way to maintain our allow/block list, it prevent these accidental DDOS of command, but also let you actually check the syntax of the file (if json) even before pushing it, so even if a defective script on our side do an error the Nextdns-CLi will protect your server API from overload.

**Comment by rs** [comment]
This is not aligned with our product.
