### ISSUE TITLE
Client Feature Requests

### ISSUE THREAD

**Issue by Sc0th** [nextdns/nextdns#58]
Please can the option be added to configure log location and also set a custom device name to be sent from the Linux client?

**Comment by rs** [comment]
Do you have a use case in mind for the custom log location?

**Comment by Sc0th** [comment]
I run an exclusively dockerized environment, it would be helpful for me to be able to stipulate so I don't have to expose too much outside of the pod something like having --logs=/logs/shared/nextdns.log would be super useful.

**Comment by rs** [comment]
If you use `run`, all logs are sent to stderr, which let you redirect them whenever you want.
