### ISSUE TITLE
No Option To Exclude WiFi Networks in iOS 15 or iPadOS 15

### ISSUE THREAD

**Issue by argiedoubleya** [nextdns/nextdns#581]
**Context**
 - Version: 2.0.1(29) 
 - Platform: iOS

&lt;Describe the bug>

On a fresh install of iOS 15 there is no option given in the settings to exclude certain WiFi networks. Is this a known bug and will it be fixed with an update?

**Comment by rs** [comment]
This is a bug in iOS. Apple said they will fix it in a future revision.

Closing as this is not related to CLI.
