### ISSUE TITLE
Dynamic DNS on cli

### ISSUE THREAD

**Issue by BirdInFire** [nextdns/nextdns#583]
Hello,

Actually we can use a dynamic DNS on a domain,
But the problem with this method is that there is a public domain who have the ip of many network we don't want to expose their public ip.

If possible i prefer a method who doesn't rely of a weak combination of "user/password", why not the cli generate a key we have to past in the interfaces ? like that we authenticate the cli, and it's protected by the 2FA of the control panel.

Again i ask a automated method to update old network (who don't support ipv6 at all without having to expose our public ip (because it can lead to bad guy who will DDOS these ip for ransom)).

Thanks

**Comment by rs** [comment]
The CLI does not need dynamic DNS and there is no user/password involved. You just need to set it up a configuration ID you created on my.nextdns.io, which is somewhat what you are describing as a “key”.

**Comment by BirdInFire** [comment]
> The CLI does not need dynamic DNS and there is no user/password involved. You just need to set it up a configuration ID you created on my.nextdns.io, which is somewhat what you are describing as a “key”.
@rs 
hum yes but just closing this does not resolve the problem your way to do DDNS actually require a public domain linked to all our router who don't have IPV6 (thanks our isp of these router), so we can be targetted more easily cli is the easiest way (since it's already installed on our router) but if you have another idea just change the name not close it .....

**Comment by rs** [comment]
DDNS is not a CLI feature. Of you want to discuss this feature, please use https://help.nextdns.io. This repository is dedicated to NextDNS CLI client.

**Comment by BirdInFire** [comment]
@rs I ASK a feature to UPDATE the ip from CLI, because your DDNS disclose our IP on a domain.
I ASK YOU to find a way to do that in cli, and it's me who have to do the job ?
Or ask on HELP when i ask a FEATURE FOR CLI ???????

SERIOUSLY ????????

**Comment by BirdInFire** [comment]
i will stop to even try and go to competitor i'm bored to have at best a customer level, when we want to do some more advanced thing and/or being sended again and again on a help forum where idea are just forgotten.

**Comment by rs** [comment]
You don't need the CLI to update the link IP. On the setup page, click on "Show advanced options" under link IP, you will get the link IP API URL. You can just call "curl <the url>" to link your IP. Call this from a crontab for instance.

**Comment by crssi** [comment]
> i will stop to even try and go to competitor i'm bored to have at best a customer level, when we want to do some more advanced thing and/or being sended again and again on a help forum where idea are just forgotten.

@BirdInFire who the competitor is?

Cheers
