### ISSUE TITLE
High CPU on EdgeOS

### ISSUE THREAD

**Issue by nbrewster** [nextdns/nextdns#586]
**Context**
 - CLI Version: nextdns version 1.37.2
 - Platform: EdgeRouter ER-X-SFP / EdgeOSv2.0.9-hotfix.2

NextDNS starts consuming all the CPU on my EdgeRouter, at least once a day.

Example: top output
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                         
 3889 root      20   0  670268  87888   5148 R 272.4 34.7  49:20.80 nextdns         
```

Config:
```
cache-size 0
cache-max-age 0s
bogus-priv true
timeout 5s
listen localhost:53
control /var/run/nextdns.sock
use-hosts true
max-inflight-requests 256
detect-captive-portals false
hardened-privacy false
log-queries false
max-ttl 0s
report-client-info true
discovery-dns 
setup-router true
config ****
auto-activate false
````

Trace here: https://gist.github.com/nbrewster/fd250ddc3cad791073756ddb2007bba5

**Comment by rs** [comment]
Please try reducing the max-inflight-requests by half.

**Comment by nbrewster** [comment]
Thanks you, done - I will report back.

**Comment by rs** [comment]
Can you please try to reproduce without client identification enabled?

**Comment by dk90103** [comment]
Just set: "report-client-info false"

Will test and report back

**Comment by dk90103** [comment]
Still the same problem after setting "report-client-info false""
Config:
listen localhost:53
bogus-priv true
config XXXXXX
timeout 5s
max-inflight-requests 128
auto-activate false
control /var/run/nextdns.sock
log-queries false
cache-size 10MB
cache-max-age 0s
detect-captive-portals false
max-ttl 5s
report-client-info false
discovery-dns
hardened-privacy false
use-hosts true
setup-router true

Top output:
![image](https://user-images.githubusercontent.com/48084282/134494491-83f9661b-99ab-45e1-a9ae-69254d579c60.png)

**Comment by nbrewster** [comment]
Same problem (though it took a few days) with "max-inflight-requests 128". I will try "report-client-info false" next (but it seems that didn't help @dk90103).

**Comment by dk90103** [comment]
@nbrewster I currently had to un-install nextdns in my Edgemax because I hit this CPU bug after a few hours of run-time. But I am happy to try out anything that @rs suggests.

**Comment by anastyalien** [comment]
Could this be a backend issue? I understand this is a CLI discussion but my old router also goes insane when I use nextdns via dnscrypt-proxy2 package from Entware. Of course this could be a firmware/entware issue but weird that it happens only with nextdns and seeing similar complaints here on CLI and different hardware/firmware.
After a while, nextdns makes dnscrypt-proxy service hang and router goes into 100% CPU usage with all DNS requests failing either until I reboot my router or manually restart dnscrypt-proxy service. This seems to only happen with nextdns and no other doh/dnscrypt provider. Happens even when I use my personal clientID instead of the default public "nextdns" one from dnscrypt relays list.
No setting in dnscrypt-proxy.toml affects this behavior and dnscrypt main log also has no errors, only dnscrypt domain resolve log gets flooded with "network error" errors and response times of 5000ms+ despite having no connection issues to nextdns servers when looking at traceroutes and diag.exe.

**Comment by nbrewster** [comment]
Since setting `max-inflight-requests 128` and `report-client-info false`, I have not seen a recurrence of the problem on my router. Of course, I also no longer see client names in the logs (everything shows as the public IP of my router), which is not acceptable for my use case. @rs any other suggestions?

**Comment by andrew-susanto** [comment]
Recently had this problem with EdgeRouter X v2.0.9-hotfix.2 and nextdns CLI 1.37.2, the cpu jumps more than 200%.  When this happens, it's stop responding to dns queries, try to restart nextdns via CLI got no response, hang the ssh, try create another ssh session, the nextdns service status is stopped, try to start again and the dns works again. I think disabling report-client-info and log-queries help this issue. 

This is the log from /var/log/messages arround the time it happens.
[log.txt](https://github.com/nextdns/nextdns/files/7313431/log.txt)

**Comment by rs** [comment]
do you reproduce with older revision?

**Comment by andrew-susanto** [comment]
I'm trying with older version 1.36.0. Will report back if i can reproduce the problem.

I think to set installation version, we can use NEXTDNS_VERSION environment variable
Run this command first before sh the installation script. 
`export NEXTDNS_VERSION=1.36.0`

To install the older version, i first remove nextdns via CLI, then reinstall it.

**Comment by andrew-susanto** [comment]
Update for version 1.36.0. Still get high cpu usage after running about 2 hours 30 minutes. DNS is not responding when that happens. I managed to get the dns work again with nextdns restart command.
![image](https://user-images.githubusercontent.com/28893391/136638766-6d08b30b-280a-4a74-bc01-b03aba22fa29.png)

**Comment by andrew-susanto** [comment]
Have been running nextdns cli 1.35.0 over almost 36 hours and haven't seen this issue occured again. The CPU usage is pretty low and not see any spike caused by nextdns. The router gives reply on dns request in all of those time. I also configured prtg since i installed 1.35.0 to monitor the cpu usage (empty cpu load in graph caused by my prtg server goes to sleep). I hope nextdns team can figure out what's happened. 

![image](https://user-images.githubusercontent.com/28893391/136694805-d13262ab-61ef-473a-a79e-648149bdb0b5.png)

**Comment by ralban** [comment]
I've continued to run 1.37.2, and have not observed this symptom since October 9th.
Perhaps this symptom is not in the CLI client.  Maybe it is something cloud side that becomes evident in the CLI on EdgeOS b/c it is a lower-powered device with a higher volume of requests served. The symptom might not be noticeable on single smartphone (faster proc) with only 1 device querying it.

In my case, I might have ~65 clients/8 configs. Not sure if others experiencing this symptom have similar device and query volumes.

**Comment by rs** [comment]
Please try with this verison: NEXTDNS_VERSION=master/SNAPSHOT-ff4185e sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'

**Comment by ralban** [comment]
I experienced my crash symptom overnight on the pre-release snapshot. I'm trying to pull logs, but might have lost them as loss DNS disconnected by logging server. I'm installed 1.35 and will continue to monitor.

**Comment by ralban** [comment]
@jrm523, thanks for the suggestion. I've not done a hardware reset recently. I've been running the 1.3.5 version for 3 days without incident. Will continue to observe this release and future releases before I commit to that kind of downtime.

**Comment by markangus2b** [comment]
I can also confirm this issue persists on v1.37.3 on my Edgerouter X v2.0.9-hotfix.2.



> Reproduced on 1.37.3 (with report-client-info true). I'm reverting back to 1.35 for now.

Could you share how you reverted back to 1.35?

**Comment by nbrewster** [comment]
> Could you share how you reverted back to 1.35?

`export NEXTDNS_VERSION=1.35.0; sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`

You may want to back up `/config/nextdns/nextdns.conf` first and restore it again after.

**Comment by jzelinskie** [comment]
Looking at the commits, I'm not sure how downgrading to 1.35.0 would make any difference.
Did reverting actually help?

**Comment by nbrewster** [comment]
> Looking at the commits, I'm not sure how downgrading to 1.35.0 would make any difference. Did reverting actually help?

Yes , it helps for me. On 1.35.0, even with `report-client-info true`, I have not had a recurrence of the problem. Here is my 1.35.0 config:

```
max-ttl 0s
report-client-info true
detect-captive-portals false
use-hosts true
config ***
cache-size 0
bogus-priv true
timeout 5s
setup-router true
listen localhost:53
discovery-dns 
max-inflight-requests 128
control /var/run/nextdns.sock
log-queries false
cache-max-age 0s
hardened-privacy false
auto-activate false
```

**Comment by jzelinskie** [comment]
Yep! Since downgrading, I've also not had issues.

**Comment by thomase1234** [comment]
Same here. Downgraded on Oct27 and no issues since the downgrade.

**Comment by jeamland** [comment]
I'm also seeing this (EdgeRouter X) and have just done the downgrade thing.

**Comment by jrm523** [comment]
I have been on a honeymoon but struggled with this as well before and after my trip. I noticed the problem occurs on both hotfix 1 and hotfix 2 edgerouter firmware. However, it seemed to happen more frequently on hotfix 2 firmware. Today I have downgraded to 1.35 as all of you have suggested and am hoping that resolves my issues. Thanks @nbrewster for posting the config on how to downgrade.

**Comment by ybkshaw** [comment]
After trying the fix @nbrewster suggested NextDNS-cli on my EdgeRouter-X has been totally stable. My log still has sparse "context deadline exceeded" errors but significantly less than previously seen and all users on the network report stability has resumed.

**Comment by jaYINGLING** [comment]
I'm also using nextdns 1.37.0 with ER-X and was experiencing DNS drops about twice a day. I just downgraded to 1.35.0 and will comment again if I experience more of the same issue.

**Comment by rs** [comment]
@jaYINGLING please try with 1.37.4 not 1.37.0.

**Comment by jaYINGLING** [comment]
@rs Okay, I'll give that a try and report back.

**Comment by jaYINGLING** [comment]
@rs still having the issue on 1.37.4

**Comment by ybkshaw** [comment]
Reporting in that 1.3.5.0 has remained stable and uptime hasn't been effected since my previous comment.

**Comment by Hugo-LA** [comment]
@rs I confirm, version 1.37.4 also failed me.

**Comment by vincentbernat** [comment]
Could you try with the snapshot in #618? It switches back to Go 1.16 instead of Go 1.17 which was one of the main change between 1.35 and 1.36. Comment back in #618 if it works or not. Thanks!

**Comment by andrew-susanto** [comment]
Currently trying pr-618/SNAPSHOT-9483d8b, will report back.  

Installation command:
```NEXTDNS_VERSION=pr-618/SNAPSHOT-9483d8b sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'```

**Comment by dk90103** [comment]
Do we know which minor version of 1.17 that is used ? There are some additional fixes in 1.17.3
go1.17 (released 2021-08-16)
Go 1.17 is a major release of Go. Read the Go 1.17 Release Notes for more information.

Minor revisions
go1.17.1 (released 2021-09-09) includes a security fix to the archive/zip package, as well as bug fixes to the compiler, linker, the go command, and to the crypto/rand, embed, go/types, html/template, and net/http packages. See the Go 1.17.1 milestone on our issue tracker for details.

go1.17.2 (released 2021-10-07) includes a security fix to the linker and misc/wasm directory, as well as bug fixes to the compiler, the runtime, the go command, and to the time and text/template packages. See the Go 1.17.2 milestone on our issue tracker for details.

go1.17.3 (released 2021-11-04) includes security fixes to the archive/zip and debug/macho packages, as well as bug fixes to the compiler, linker, runtime, the go command, the misc/wasm directory, and to the net/http and syscall packages. See the Go 1.17.3 milestone on our issue tracker for details.

**Comment by vincentbernat** [comment]
1.17.3 was used for 1.37.4.

**Comment by shivv3r** [comment]
Same issue on Mi Wifi Mini with latest OpenWRT. Still not fixed.

**Comment by ahuj9** [comment]
Same issue on ERX with latest OpenWRT/nextdns opkg

**Comment by BrianG61UK** [comment]
nextdns 1.37.7 is working well on my EdgeRouter X without caching or client identification by using dnsmasq for caching.

My nextdns.conf:
```
auto-activate false
control /var/run/nextdns.sock
config ******
max-ttl 0s
report-client-info false
max-inflight-requests 256
discovery-dns
mdns disabled
hardened-privacy false
setup-router false
listen 127.0.0.1:53053
cache-size 0
cache-max-age 0s
detect-captive-portals false
bogus-priv true
log-queries false
use-hosts false
timeout 5s
```

dnsmasq is configured similar to:
```
    dns {
        forwarding {
            cache-size 1000
            listen-on switch0.10
            listen-on switch0.20
            options no-resolv
            options query-port=53054
            options server=127.0.0.1#53053
            options bogus-priv
            options domain-needed
            options stop-dns-rebind
        }
    }
```

**Comment by BrianG61UK** [comment]
@anastyalien said:
> but my old router also goes insane when I use nextdns via dnscrypt-proxy2 package from Entware.

Yes, I found the same when using DoH via dnscrypt-proxy2 on my EdgeRouter X. No dns and dnscrypt-proxy2 using 100++% CPU after a few hours.

There was no such problem with dnscrypt-proxy2 when using dnscrypt (rather than DoH) to talk to openDNS.

**Comment by rs** [comment]
It is probably due to the cipher suite negociate with TLS and the lack of acceleration on this hardware. We attempted several optimizations to reduce TLS handshake frequency, but it is apparently not always enough.

Cc @vincentbernat

**Comment by BrianG61UK** [comment]
> It is probably due to the cipher suite negociate with TLS and the lack of acceleration on this hardware.
> We attempted several optimizations to reduce TLS handshake frequency, but it is apparently not always enough.
> 
> Cc @vincentbernat

How would that turn nextdns (and it seems, also dnscrypt-proxy2) into dead CPU eating processes?

**Comment by BrianG61UK** [comment]
@rs said:
> It is probably due to the cipher suite negociate with TLS and the lack of acceleration on this hardware.
> We attempted several optimizations to reduce TLS handshake frequency, but it is apparently not always enough.
> 
> Cc @vincentbernat

How would that turn nextdns cli (and it seems, also dnscrypt-proxy2) into useless CPU eating processes?

**Comment by rs** [comment]
My theory is that handshake get so slow that jt times out and retry in loop. I can’t reproduce this issue on the same hardware so it is hard to understand what is happening.

**Comment by BrianG61UK** [comment]
People are saying nextdns cli v1.35 does not have this problem. Has something changed since then?
Also why does nextdns cli 1.37.7 seem to work well as I have chosen to configure it on my EdgeRouter X shown [here](https://github.com/nextdns/nextdns/issues/586#issuecomment-1005751167)

**Comment by jeamland** [comment]
> My theory is that handshake get so slow that jt times out and retry in loop. I can’t reproduce this issue on the same hardware so it is hard to understand what is happening.

Are you able to introduce some synthetic network delay and/or packet loss into your test environment?

**Comment by BrianG61UK** [comment]
Does this only occur on mipsle based EdgeRouters?
Has anyone seen this problem on the mips64 based EdgeRouters?

**Comment by BrianG61UK** [comment]
> People are saying nextdns cli v1.35 does not have this problem.
If that's right and v1.35 is the most recent version without this problem, then that represents the last version released before updating the go compiler to v1.17. Could there be a bug in 1.17 with mipsle code?

**Comment by vincentbernat** [comment]
1.37.7 is using Go 1.16. See https://github.com/nextdns/nextdns/pull/618. It has been confirmed by several people this was solving the problem for them on ER-X. Maybe you can try the snapshot in https://github.com/nextdns/nextdns/pull/620. This is using the exact same version Go version than for 1.35.

**Comment by ybkshaw** [comment]
I updated the latest version on my EdgeRouter ER-X and it's been stable and happy for a couple of weeks now.

**Comment by nbrewster** [comment]
I have also been running 1.37.7 for a couple of weeks with no issues - even with `report-client-info true`.

**Comment by BrianG61UK** [comment]
Yes. 1,37.7 and 1.37.10 seem good on my ER-X too.

**Comment by j-jacobi** [comment]
I noticed this issue on 1.37.11 (not on EdgeOS) after a few hours:
```
INFO: OS: openwrt
INFO: GOARCH: mips_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/sbin/nextdns
INFO: INSTALL_RELEASE: 1.37.11
```

For the moment I downgraded to 1.37.10 and didn't notice the issue 🤞 

<details>

<summary>
How to downgrade to custom version 1.37.10 on OperWRT:
</summary>

1. First uninstall `luci-app-nextdns` if installed and then `nextdns` (Your configuration file will not be removed)
`opkg remove luci-app-nextdns`
`opkg remove nextdns`
2. Download and install the old version
`wget https://github.com/nextdns/nextdns/releases/download/v1.37.10/nextdns_1.37.10_linux_mips_softfloat.tar.gz -O nextdns.tar.gz`
` tar xvzf nextdns.tar.gz`
`./nextdns install`
3. (Optional/hacky): Install `luci-app-nextdns`, this will reinstall the new version of `nextdns` so I manually replaced it with:
`rm /usr/sbin/nextdns && mv ./nextdns /user/sbin/nextdns`

</details>
