### ISSUE TITLE
NextDNS CLI randomly stops on Ubiquiti EdgeRouter-X

### ISSUE THREAD

**Issue by jrm523** [nextdns/nextdns#587]
Occasionally, the CLI client randomly stops on my EdgeRouter-X. The last time it happened, I saw a similar issue posted and upgraded the CLI client. However, it happened again today. I noticed that the logs show a flurry of "context deadline exceeded" and then the following logs were shown before the CLI service quit working..

`
Oct  3 12:10:06 edge nextdns[27400]: Received signal: broken pipe (ignored)
`
`
Oct  3 12:10:06 edge nextdns[27400]: Endpoint failed: https://dns.nextdns.io#45.32.219.28,2001:19f0:5401:1d93:5400:2ff:fece:25e9,162.250.7.137,2605:380:57:613::5: roundtrip: context deadline exceeded
`
`
Oct  3 12:10:06 edge nextdns[27400]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io}: exchange: roundtrip: dial tcp: lookup dns.nextdns.io on 127.0.0.1:53: read udp 127.0.0.1:51407->127.0.0.1:53: i/o timeout
`
`
Oct  3 12:10:06 edge nextdns[27400]: Endpoint failed: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::: roundtrip: context deadline exceeded
`
`
Oct  3 12:10:06 edge nextdns[27400]: Endpoint failed: https://dns2.nextdns.io#45.90.30.0,2a07:a8c1::: roundtrip: context deadline exceeded
`
`
Oct  3 12:10:06 edge nextdns[27400]: Switching endpoint: https://dns.nextdns.io#45.32.219.28,2001:19f0:5401:1d93:5400:2ff:fece:25e9,162.250.7.137,2605:380:57:613::5
`

 - CLI Version: 1.37.2 
 - Platform: Ubiquiti EdgeRouter-X v2.0.9 hf1

Please let me know if you need any other information. Thanks for the great service.

**Comment by rs** [comment]
@jrm523 this line is suspect: `Oct 3 12:10:06 edge nextdns[27400]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io}: exchange: roundtrip: dial tcp: lookup dns.nextdns.io on 127.0.0.1:53: read udp 127.0.0.1:51407->127.0.0.1:53: i/o timeout`

Seem like the CLI is trying to connect on itself and fails. I wonder is there isn't a circular dependency at play here. What do you get for `nextdns config`?

**Comment by jzelinskie** [comment]
For the past 3 days, I have not seen the bug manifested.

**Comment by jrm523** [comment]
> NEXTDNS_VERSION=master/SNAPSHOT-ff4185e sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'

@rs Apologies for the late response. I'm about to get married next week and it has been hectic to say the least. I applied the snapshot and will let you know via a new issues if I am still having issues. I am very optimistic per @jzelinskie updates. Thank you very much for taking the time to address this issue.

**Comment by jzelinskie** [comment]
It actually happened twice today randomly, so I feel like there might be something server-side triggering it.
My logs are typically crowded with many "doh resolve: context deadline exceed", but when I filter them out I see some interesting failures to connect to the backend:

```
Oct 20 04:19:40 ubnt nextdns[29477]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07:a
8c1::}: exchange: roundtrip: write tcp 69.169.4.201:47556->45.90.30.0:443: write: broken pipe
Oct 20 04:19:40 ubnt nextdns[29477]: Received signal: broken pipe (ignored)
Oct 20 04:20:04 ubnt nextdns[29477]: Query 192.168.2.80 UDP A edgeapi.slack.com. (qry=35/res=12) cache fallback HTTP/2.0: doh resolve: EOF
Oct 20 04:20:04 ubnt nextdns[29477]: Query 192.168.2.68 UDP A mail.google.com. (qry=33/res=12) cache fallback HTTP/2.0: doh resolve: EOF
Oct 20 04:20:09 ubnt nextdns[29477]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07:a8c1::}: exchange: roundtrip: write tcp 69.169.4.201:47758->45.90.30.0:443: write: broken pipe
Oct 20 04:20:12 ubnt nextdns[29477]: Received signal: broken pipe (ignored)
Oct 20 04:20:28 ubnt nextdns[29477]: Query 192.168.2.68 UDP A www.google.com. (qry=32/res=12) cache fallback HTTP/2.0: doh resolve: EOF
Oct 20 04:20:41 ubnt nextdns[29477]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07:a8c1::}: exchange: roundtrip: write tcp 69.169.4.201:47988->45.90.30.0:443: write: broken pipe
Oct 20 04:20:42 ubnt nextdns[29477]: Received signal: broken pipe (ignored)
Oct 20 04:21:03 ubnt nextdns[29477]: Query 192.168.2.80 UDP A securetoken.googleapis.com. (qry=44/res=12) cache fallback HTTP/2.0: doh resolve: EOF
```

**Comment by jzelinskie** [comment]
@rs This is while it's not broken:

```
  anexia-ewr        2 ms  (anycast2, ultralow1)
■ vultr-ewr         2 ms  (anycast1, ultralow2)
  zepto-iad         7 ms
  axcelx-bos        8 ms
  hetzner-iad       8 ms
  zepto-xrs         8 ms
  smarthost-bos     8 ms
  anexia-mnz        8 ms
  router-pit       16 ms
  teraswitch-pit   16 ms
```

**Comment by ybkshaw** [comment]
FYI for anyone still troubleshooting this, it appears the this issue was closed as a duplicate, discussion is still ongoing here: https://github.com/nextdns/nextdns/issues/586
