### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by itsnotsaved** [nextdns/nextdns#588]
I read this article https://help.nextdns.io/t/q6hmv0s/translations and sent email to support@nextdns.io with title "[Localization] Add new language" but it seems no action for that request, already 1 month+
@rs @romaincointepas can you please review and process it? check it for more details however i requested to add sinhala (si) language.

**Comment by rs** [comment]
Please only use this repository for CLI related issues.

**Comment by itsnotsaved** [comment]
Sorry, I know that but 2 months ago, i sent request through crowdin and then 1 month ago, as mentioned above sent email to support@nextdns.io but it seems no one care about them.
Furthermore, https://crowdin.com/project/nextdns translation guide link also broken
