### ISSUE TITLE
Wrong DHCP lease file(s) being found on EdgeOS

### ISSUE THREAD

**Issue by brainsik** [nextdns/nextdns#59]
* nextdns version 1.4.24
* EdgeOS (EdgeRouter X v1.10.10)

It looks like NextDNS has a list of possible DHCP leas file locations and uses the first one it finds. Unfortunately, this strategy doesn't work on my EdgeOS router as 3 of these files exist, but only one of them is the correct file to use. It's a roll of the map ordering as to whether I get the correct file read.

In this case, one of the files is an empty one that is `touch`ed by the dnsmasq init script on start (`/var/run/dnsmasq-dhcp.leases`), one is the DHCP lease file for the WAN interface (`/var/run/dhclient_*.leases`), and one is the actual lease file I want read (`/var/run/dhcpd.leases`).

Perhaps we can have an option in the `nextdns.conf` to specify which file to load?

**Comment by rs** [comment]
Are all the "wrong" ones empty? We could check for that.

**Comment by brainsik** [comment]
Unfortunately, not. The lease file for the WAN interface contains the lease for the dynamically assigned IP from the ISP.

**Comment by rs** [comment]
The one for the dhclient does not make sense actually, I will remove it.

**Comment by AJolly** [comment]
Both files are valid on edgeos - depending if you are using dhcpd or dnsmasq.  https://help.ui.com/hc/en-us/articles/115002673188-EdgeRouter-DHCP-Server-Using-Dnsmasq
(The reason to switch is to better support dynamic hostname resolution)
