### ISSUE TITLE
EdgeRouter Issues (Continuation from Support Chat)

### ISSUE THREAD

**Issue by gaia** [nextdns/nextdns#591]
**Context**
 - CLI Version: 1.37.2
 - Platform: EdgeRouter Lite running v2.0.9-hotfix.2

please see https://help.nextdns.io/messages/k9h83k for the issue and all the steps already tried.

**Comment by rs** [comment]
Can you please describe the issue in the ticket?

**Comment by gaia** [comment]
Thanks @rs. uninstalled, installed then re-conf accepting all defaults.

on the router side:

a) what do I set for the LAN's DHCP:
![image](https://user-images.githubusercontent.com/87547/137411050-8917d0cb-b5c5-49c9-943d-341dac75c5b9.png)

b) for the system name server?
![image](https://user-images.githubusercontent.com/87547/137411114-9119a723-7ea2-41e3-8caa-831ec3b0ba43.png)

c) I'd like to use caching at router level, and I have it blank under DNS config
![image](https://user-images.githubusercontent.com/87547/137411165-f1e7519c-dd18-4100-aaf2-8421da067daa.png)

thanks again

**Comment by gaia** [comment]
ok thanks for the explanation!

now what do I do next time DNS stops working (when I say stops working, I can't even use `dig` when I SSH into the router itself.

**Comment by rs** [comment]
The snapshot provided above is trying to fix your issue. It will be released soon even if you don't test it, but you will still need to upgrade the CLI to fix the issue.

**Comment by gaia** [comment]
I installed the snapshot given AND upgraded the cli. I wrote

"as for the fix, it worked for a while, i am not sure if i got any errors, i didnt' have time to check. it stopped working " in https://github.com/nextdns/nextdns/issues/591#issuecomment-944668857

**Comment by gaia** [comment]
[nextdns.log](https://github.com/nextdns/nextdns/files/7585884/nextdns.log)

pls see attached. using v1.37.3. restarting fixes it.
