### ISSUE TITLE
UDMP SE 2.3.10 + CLI does not persist upgrade

### ISSUE THREAD

**Issue by janthony6** [nextdns/nextdns#593]
CLI works on the latest firmware 2.3.10. However when you upgrade firmware, it wipes out nextdns and it has to be manually reinstalled. There is a good post here on reddit that shows that packages can persist upgrades. Maybe should be added to the installer?

https://www.reddit.com/r/Ubiquiti/comments/q7qk3m/udm_se_persisted_debian_packages_installation/

Happy to help test.

**Comment by janthony6** [comment]
did you ever get your SE in?

**Comment by rs** [comment]
Yes, I need to find time to work on it.

**Comment by mazzy89** [comment]
@janthony6 I'm not sure if this help but at the moment I'm running fine NextDNS on the UDM PRO Se that persist over the reboot.

Just download the binary of NextDNS, place it in the `/mnt/data/netxtdns` folder along with the `config` file. then create systemd unit that makes a symlink of the nextdata bin placed in the `/mnt/data/netxtdns` folder. in this way no matter what you will have nextdns always running after any updates.

**Comment by janthony6** [comment]
installed 2.3.12 today and nextdns was still on the router - no need to reinstall with the latest firmware.
