### ISSUE TITLE
Add support for EndeavourOS (Arch Linux)

### ISSUE THREAD

**Issue by ghost** [nextdns/nextdns#594]
Running the command `sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'` from the wiki returns the following error on [EndeavourOS](https://endeavouros.com/):

```

ERROR: Unsupported OS: GNU/Linux ID=endeavouros ID_LIKE=arch BUILD_ID=2021.08.27

ERROR: Unknown bin location for

INFO: OS:

INFO: GOARCH: amd64

INFO: GOOS: linux

INFO: NEXTDNS_BIN:

INFO: INSTALL_RELEASE: 1.37.2`

ERROR: Cannot detect running environment.

```

A workaround is to install `nextdns` from the AUR as per [the wiki's suggestions](https://github.com/nextdns/nextdns/wiki/Arch-Linux-Based-Distributions#installing-from-aur), although I'd prefer if EndeavourOS was officially supported. EndeavourOS is a very popular Arch based distro; currently the 2nd most popular distro on [DistroWatch](https://distrowatch.com/table.php?distribution=endeavour) at the time of writing this. The curl command from the wiki works fine on Arch and Manjaro so I don't think it'll be too difficult to add support for it.

Cheers.

**Comment by jps2003** [comment]
If it helps, here's the output of `cat /etc/os-release`:

```
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID=endeavouros
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://endeavouros.com/wiki/"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://github.com/endeavouros-team"
LOGO=endeavouros
```
