### ISSUE TITLE
Windows NextDNS CLI: no IPv6 listener

### ISSUE THREAD

**Issue by stijnpieters** [nextdns/nextdns#601]
**Context**
 - CLI Version: 1.37.2
 - Platform: Windows

Same issue as in https://github.com/nextdns/nextdns/issues/501, except for Windows. 

No listener for IPv6. This causes tools like nslookup to fall over because default adapter settings prefer name resolution over IPv6.
temp workaround was disabling IPv6 name resolution.

**Comment by Gorson84** [comment]
What's the status on this? I still see most of my IPV6 traffic bypassing the NextDNS CLI
