### ISSUE TITLE
Ship nextdns client with CA certpool 

### ISSUE THREAD

**Issue by Mile-Lile** [nextdns/nextdns#604]
Can you ship CLI client with CA bundle so that routers that doesn't have CA bundle can have nextdns DoH... can this be done at all?
[https://github.com/certifi/gocertifi](url)

**Comment by rs** [comment]
This has drawbacks but it is something we are considering.

Cc @vincentbernat

**Comment by Mile-Lile** [comment]
Thx Olivier!

**Comment by vincentbernat** [comment]
In #548, the two options are  available:
- just use embedded certificates
- use embedded certificates in addition to the system ones

The second option has no drawback (but does not save memory). I can do it again with the current authority.

**Comment by rs** [comment]
Let’s do the latter

**Comment by vincentbernat** [comment]
This is done in #606.

**Comment by Mile-Lile** [comment]
![Screenshot_select-area_20211107173829](https://user-images.githubusercontent.com/12752816/140653774-97cd32b5-ac49-416e-9899-a325e99e6848.png)

I tested this snapshot on ddwrt and all I can say thank you very much. This is working like a charm... very good job vincent!!! Thx
