### ISSUE TITLE
Add support for DeepinOS - manually installed nextdns CLI - tested working

### ISSUE THREAD

**Issue by Mile-Lile** [nextdns/nextdns#605]
Can you add installer support for DeepinOS. It is very popular linux distro, you can check it on distrowatch. It is based on Debian so I used .deb file and deb manager and successfully installed it.  Unfortunately I cannot upgrade it. I get error: Cannot detect running environment.

```
mile-lile@toshiba-laptop:~$ nextdns upgrade
ERROR: Unsupported OS: GNU/Linux VERSION_ID=20.2.4 ID=Deepin
ERROR: Unknown bin location for 
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: 
INFO: INSTALL_RELEASE: 1.37.3
ERROR: Cannot detect running environment.
Error: exit status 1
```

Here are some tests:

```
mile-lile@toshiba-laptop:~$ uname -a
Linux toshiba-laptop 5.13.13-amd64-desktop #1 SMP Tue Aug 31 18:01:11 CST 2021 x86_64 GNU/Linux
```

```
mile-lile@toshiba-laptop:~$ systemctl status nextdns.service
● nextdns.service - NextDNS DNS53 to DoH proxy.
   Loaded: loaded (/etc/systemd/system/nextdns.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-11-05 20:22:04 CET; 28min ago
 Main PID: 17547 (nextdns)
    Tasks: 8 (limit: 4486)
   Memory: 7.1M
   CGroup: /system.slice/nextdns.service
           └─17547 /usr/bin/nextdns run
```
```
mile-lile@toshiba-laptop:~$ dig whoami.akamai.net

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> whoami.akamai.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5862
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;whoami.akamai.net.             IN      A

;; ANSWER SECTION:
whoami.akamai.net.      5       IN      A       217.146.8.49

;; Query time: 16 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Nov 05 20:48:58 CET 2021
;; MSG SIZE  rcvd: 62
```

```
mile-lile@toshiba-laptop:~$ sh -c 'sh -c "$(curl -s https://nextdns.io/diag)"'

Welcome to NextDNS network diagnostic tool.

This tool will download a small binary to capture latency and routing information
regarding the connectivity of your network with NextDNS. In order to perform a
traceroute, root permission is required. You may therefore be asked to provide
your password for sudo.

The source code of this tool is available at https://github.com/nextdns/diag

Do you want to continue? (press enter to accept)
[sudo] password for mile-lile: 
Verification successful
Testing IPv6 connectivity
  available: false
Fetching https://test.nextdns.io
  status: ok
  client: 109.198.5.204
  protocol: DOH
  dest IP: 217.146.8.49
  server: anexia-beg-1
Fetching PoP name for ultra low latency primary IPv4 (ipv4.dns1.nextdns.io)
  anexia-beg: 34.575ms
Fetching PoP name for ultra low latency secondary IPv4 (ipv4.dns2.nextdns.io)
  edis-beg: 18.163ms
Fetching PoP name for anycast primary IPv4 (45.90.28.0)
  zepto-fra: 31.385ms
Fetching PoP name for anycast secondary IPv4 (45.90.30.0)
  anexia-vie: 33.013ms
Pinging PoPs
  edis-beg: 18.015ms
  anexia-beg: 18.013ms
  zepto-sof: 23.147ms
  edis-zag: 23.074ms
  edis-bud: 23.177ms
  anexia-bud: 32.868ms
  edis-skp: 40.667ms
  albahost-tia: 40.601ms
  anexia-sof: 40.723ms
  albahost-prn: 52.312ms
Traceroute for ultra low latency primary IPv4 (217.146.8.49)
    1    192.168.2.1    4ms  21ms   9ms
    2    192.168.1.1    1ms   1ms   1ms
    3     10.65.96.1   23ms  25ms   9ms
    4 91.185.116.104   16ms  15ms  21ms
    5  91.185.118.98   26ms  18ms  15ms
    6  91.185.118.60   30ms  16ms  19ms
    7 212.200.93.133   11ms  11ms  12ms
    8  212.200.7.178   12ms  12ms  21ms
    9   212.200.7.65    9ms   9ms  12ms
   10 178.222.125.186   15ms  15ms  13ms
   11    94.16.12.32   10ms  15ms  12ms
   12   217.146.8.49   21ms  16ms  19ms
Traceroute for ultra low latency secondary IPv4 (194.71.126.128)
    1    192.168.2.1    1ms   1ms   3ms
    2    192.168.1.1    1ms   1ms   1ms
    3     10.65.96.1   31ms  56ms  10ms
    4 91.185.116.104   16ms  18ms  11ms
    5  91.185.118.98   16ms  53ms  34ms
    6  91.185.118.60   12ms  14ms  14ms
    7    185.1.27.77   15ms  10ms  20ms
    8 212.103.51.177   37ms  33ms  44ms
    9 212.103.51.221   12ms  15ms  14ms
   10 194.71.126.128   11ms  11ms  21ms
Traceroute for anycast primary IPv4 (45.90.28.0)
    1    192.168.2.1    1ms   *     1ms
    2    192.168.1.1    1ms   1ms   1ms
    3     10.65.96.1   14ms  17ms   8ms
    4 91.185.116.104   15ms  10ms  13ms
    5  91.185.118.98    9ms  11ms  10ms
    6  91.185.118.60   11ms  13ms  14ms
    7 212.200.93.133   18ms  25ms  11ms
    8  212.200.7.178   10ms  20ms  12ms
    9   212.200.5.36   31ms  31ms  31ms
   10  80.81.192.231   32ms  34ms  30ms
   11     45.90.28.0   35ms  27ms  32ms
Traceroute for anycast secondary IPv4 (45.90.30.0)
    1    192.168.2.1    1ms   1ms   1ms
    2    192.168.1.1    1ms   1ms   1ms
    3     10.65.96.1   10ms  11ms   9ms
    4 91.185.116.104   13ms  11ms   9ms
    5  91.185.118.98   25ms  10ms  16ms
    6  91.185.118.60   11ms  13ms  11ms
    7 212.200.93.133   11ms  34ms  12ms
    8  212.200.7.178   11ms   9ms  11ms
    9   212.200.5.32   17ms  22ms  36ms
   10   193.203.0.19   30ms  39ms  35ms
   11 144.208.208.135   29ms  29ms  32ms
   12     45.90.30.0   34ms  31ms  33ms
Do you want to send this report? [Y/n]: n
```

```
mile-lile@toshiba-laptop:~$ curl -v https://dns.nextdns.io/info

*   Trying 217.146.8.49...
* TCP_NODELAY set
* Expire in 149950 ms for 3 (transfer 0x148ce20)
* Expire in 200 ms for 4 (transfer 0x148ce20)
* Connected to dns.nextdns.io (217.146.8.49) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=dns.nextdns.io
*  start date: Sep 11 00:00:00 2021 GMT
*  expire date: Dec 10 23:59:59 2021 GMT
*  subjectAltName: host "dns.nextdns.io" matched cert's "dns.nextdns.io"
*  issuer: C=AT; O=ZeroSSL; CN=ZeroSSL ECC Domain Secure Site CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x148ce20)
> GET /info HTTP/2
> Host: dns.nextdns.io
> User-Agent: curl/7.64.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< access-control-allow-origin: *
< content-type: application/json
< strict-transport-security: max-age=63072000; includeSubDomains; preload
< timing-allow-origin: *
< content-length: 80
< date: Fri, 05 Nov 2021 19:56:30 GMT
< 
* Connection #0 to host dns.nextdns.io left intact
{"locationName": "🇷🇸 Belgrade, Serbia", "pop": "anexia-beg", "rtt": 12866}mile-lile@toshiba-laptop:~$ 
```

**Comment by Mile-Lile** [comment]
It is working basically
![Screenshot_select-area_20211105205810](https://user-images.githubusercontent.com/12752816/140573355-4f335272-1821-4e1f-88e0-709b0fba427a.png)

**Comment by rs** [comment]
What is the content of /etc/os-release on this distribution?

**Comment by Mile-Lile** [comment]
![Screenshot_select-area_20211105213124](https://user-images.githubusercontent.com/12752816/140574845-edaed298-18e6-45a0-9a4a-2481ccf42680.png)

**Comment by rs** [comment]
Please test the install script.

**Comment by Mile-Lile** [comment]
Working like a charm:) Thank you very much! Sorry for laye response...


`mile-lile@toshiba-laptop:~$ sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: Deepin
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.3
u) Upgrade NextDNS from v0.0.0-SNAPSHOT-f594d23 to 1.37.3
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
Hit:1 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://community-packages.deepin.com/deepin apricot InRelease                                         
Hit:3 https://community-packages.deepin.com/printer eagle InRelease                                          
Hit:4 https://home-store-img.uniontech.com/appstore deepin InRelease     
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nextdns is already the newest version (0.0.0~SNAPSHOT-f594d23).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
u) Upgrade NextDNS from v0.0.0-SNAPSHOT-f594d23 to 1.37.3
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): r
INFO: Uninstalling NextDNS...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  nextdns
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 8,552 kB disk space will be freed.
(Reading database ... 213051 files and directories currently installed.)
Removing nextdns (0.0.0~SNAPSHOT-f594d23) ...
Error: systemctl disable nextdns.service: exit status 1: Failed to disable unit: Unit file nextdns.service does not exist.

i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
Hit:1 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://community-packages.deepin.com/deepin apricot InRelease                                         
Hit:3 https://community-packages.deepin.com/printer eagle InRelease                                          
Get:4 https://repo.nextdns.io/deb stable InRelease [9,398 B]                                                 
Hit:5 https://home-store-img.uniontech.com/appstore deepin InRelease                                 
Get:6 https://repo.nextdns.io/deb stable/main amd64 Packages [424 B]
Get:7 https://repo.nextdns.io/deb stable/main i386 Packages [423 B]
Fetched 10.2 kB in 2s (5,458 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,331 kB of archives.
After this operation, 8,589 kB of additional disk space will be used.
Get:1 https://repo.nextdns.io/deb stable/main amd64 nextdns amd64 1.37.3 [3,331 kB]
Fetched 3,331 kB in 2s (2,005 kB/s)
Selecting previously unselected package nextdns.
(Reading database ... 213051 files and directories currently installed.)
Preparing to unpack .../nextdns_1.37.3_amd64.deb ...
Unpacking nextdns (1.37.3) ...
Setting up nextdns (1.37.3) ...
NextDNS installed and started using systemd init
NextDNS Configuration ID (default=192.168.2.0/24=39d5fc
14:2d:27:07:70:4b=39d5fc
39d5fc): 
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: y
Accept DNS request from other network hosts.
Setup as a router? (y/n): n
Make nextdns CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Enable caching? (y/n): y
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on you LAN hosts without having to wait for their cache to expire.
Enable instant refresh? [Y|n]: y
Changes DNS settings of the host automatically when nextdns is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically setup local host DNS? [Y|n]: y
NextDNS installed and started using systemd init

Congratulations! NextDNS is now installed.

To upgrade/uninstall, run this command again and select the approriate option.

You can use the nextdns command to control the daemon.
Here is a few important commands to know:

# Start, stop, restart the daemon:
nextdns start
nextdns stop
nextdns restart

# Configure the local host to point to NextDNS or not:
nextdns activate
nextdns deactivate

# Explore daemon logs:
nextdns log

# For more commands, use:
nextdns help

mile-lile@toshiba-laptop:~$ `
