### ISSUE TITLE
Report client info without mDNS

### ISSUE THREAD

**Issue by yvbeek** [nextdns/nextdns#607]
On my pfSense firewall I have nextdns running and everything is working great, except for one thing. When the `report-client-info` is turned on, nextdns will start a listener on port 5353 for mDNS. Unfortunately this conflicts with the Avahi daemon package that already runs on that port.

I'd like to keep reporting the client info based on the DHCP and hosts file, but I don't need the mDNS part for that. The Avahi daemon is more important to me, because otherwise I'll run into issues with casting to my Chromecast etc.

Unfortunately it doesn't seem to be possible to disable the mDNS functionality? The only way seems to be to disable `report-client-info` but then I lose all the client info in my logs. Even though it could just use the DHCP and hosts file info to resolve the host names.

My configuration is:
```
hardened-privacy false
use-hosts true
max-inflight-requests 256
config 192.168.40.0/24=SNIPPED2
config SNIPPED1
detect-captive-portals false
setup-router false
listen localhost:53
listen 192.168.10.1:53
listen 192.168.20.1:53
listen 192.168.30.1:53
listen 192.168.40.1:53
discovery-dns 127.0.0.1:5300
timeout 5s
auto-activate true
cache-size 10MB
log-queries false
cache-max-age 24h0m0s
max-ttl 5s
report-client-info true
bogus-priv true
control /var/run/nextdns.sock
```

Would it be possible to add an option to disable the mDNS functionality?

**Edit:** here is [someone that is running into the same issue](https://www.reddit.com/r/nextdns/comments/p8hepr/prevent_nextdns_from_listening_on_port_5353/). It would be great if `report-client-info` wouldn't necessarily turn on the mDNS functionality:

**Comment by yvbeek** [comment]
@rs This is a fairly big issue for people that want to runt the NextDNS daemon on a pfSense or OPNSense install. 

Perhaps the option could be `discovery-mdns true/false`. The if-statement on [run.go:287](https://github.com/nextdns/nextdns/blob/master/run.go#L287) could then check if that option is set to true (which should probably be the default).

**Comment by rs** [comment]
Yes I’m ok to add this option.

**Comment by yvbeek** [comment]
@rs Thank you for implementing this! I was about to work on a PR this weekend 🙂

**Comment by rs** [comment]
Oh too bad, I missed an opportunity then :)
