### ISSUE TITLE
Service only runs for 0 seconds on macOS Catalina 10.15.2

### ISSUE THREAD

**Issue by pro-sumer** [nextdns/nextdns#61]
Since I need to disable NextDNS on my company network (please allow an option to exclude Wi-Fi networks in the macOS App, as you do in the iOS App) I'm trying to use this cli client with the `forwarder` option.

However, I can't get NextDNS 1.4.25 to run on macOS Catalina 10.15.2:

```
Jan 14 13:40:00 mbp nextdns[16251]: Starting NextDNS 1.4.25/darwin on localhost:53
Jan 14 13:40:00 mbp nextdns[16251]: Listening on TCP/[::1]:53
Jan 14 13:40:00 mbp nextdns[16251]: Listening on UDP/[::1]:53
Jan 14 13:40:00 mbp nextdns[16251]: Listening on TCP/127.0.0.1:53
Jan 14 13:40:00 mbp nextdns[16251]: Listening on UDP/127.0.0.1:53
Jan 14 13:40:00 mbp com.apple.xpc.launchd[1] (nextdns[16251]): Service exited with abnormal code: 1
Jan 14 13:40:00 mbp com.apple.xpc.launchd[1] (nextdns): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 14 13:40:10 mbp nextdns[16254]: Starting NextDNS 1.4.25/darwin on localhost:53
Jan 14 13:40:10 mbp nextdns[16254]: Listening on TCP/[::1]:53
Jan 14 13:40:10 mbp nextdns[16254]: Listening on TCP/127.0.0.1:53
Jan 14 13:40:10 mbp nextdns[16254]: Listening on UDP/[::1]:53
Jan 14 13:40:10 mbp nextdns[16254]: Listening on UDP/127.0.0.1:53
Jan 14 13:40:10 mbp com.apple.xpc.launchd[1] (nextdns[16254]): Service exited with abnormal code: 1
Jan 14 13:40:10 mbp com.apple.xpc.launchd[1] (nextdns): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 14 13:40:20 mbp nextdns[16259]: Starting NextDNS 1.4.25/darwin on localhost:53
Jan 14 13:40:20 mbp nextdns[16259]: Listening on TCP/[::1]:53
Jan 14 13:40:20 mbp nextdns[16259]: Listening on TCP/127.0.0.1:53
Jan 14 13:40:20 mbp nextdns[16259]: Listening on UDP/127.0.0.1:53
Jan 14 13:40:20 mbp nextdns[16259]: Listening on UDP/[::1]:53
Jan 14 13:40:20 mbp com.apple.xpc.launchd[1] (nextdns[16259]): Service exited with abnormal code: 1
Jan 14 13:40:20 mbp com.apple.xpc.launchd[1] (nextdns): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by rs** [comment]
What do you get for l `nextdns log`.

**Comment by rs** [comment]
Please create another ticket for wifi exclusion feature request.

**Comment by pro-sumer** [comment]
> What do you get for l `nextdns log`.

The log I [posted above](https://github.com/nextdns/nextdns/issues/61#issue-549543851).

> Please create another ticket for wifi exclusion feature request.

That request is for the macOS App, not this CLI client. There's no GitHub repo for that?

**Comment by rs** [comment]
No there is not. The wifi exclusion is planned already for the mac app BTW.

Could you please run `sudo nextdns run -listen :53` and paste here what you get? Also, what do you get for `nextdns config`

**Comment by pro-sumer** [comment]
I got this:

```
INFO: 16:13:42 Starting NextDNS 1.4.25/darwin on :53
INFO: 16:13:42 Listening on TCP/:53
INFO: 16:13:42 Listening on UDP/:53
```

But more importantly, I also got this pop-up:

![firewall](https://user-images.githubusercontent.com/44335102/72356320-5d5edf80-36e9-11ea-9ce8-a8715a399112.png)

After tapping "Allow" the NextDNS client seems to work!

The NextDNS setup page now shows "This device is using NextDNS with this configuration."

**Comment by rs** [comment]
That is not the solution tho. What do you get for `nextdns config`.

**Comment by pro-sumer** [comment]
Config:

```
forwarder MYCOMPANY.com.=IP-ADDRESS
detect-captive-portals true
setup-router false
auto-activate true
timeout 5s
listen localhost:53
config MYCONFIG
log-queries false
report-client-info true
hardened-privacy false
bogus-priv true
use-hosts true
```

I'm surprised about the `.` after `.com`. Should that be there?

**Comment by pro-sumer** [comment]
> I'm surprised about the `.` after `.com`. Should that be there?

Looks like that's a bug. I'll submit a separate issue for that.

**Comment by rs** [comment]
Can you try `sudo nextdns run -config /etc/nextdns.conf`

**Comment by rs** [comment]
The dot is fine. It’s a fqdn.

**Comment by pro-sumer** [comment]
```
❯ sudo nextdns run -config-file /etc/nextdns.conf
INFO: 16:48:46 Starting NextDNS 1.4.25/darwin on localhost:53
INFO: 16:48:46 Listening on TCP/[::1]:53
INFO: 16:48:46 Listening on TCP/127.0.0.1:53
INFO: 16:48:46 Listening on UDP/[::1]:53
INFO: 16:48:46 Listening on UDP/127.0.0.1:53
INFO: 16:48:51 Activating
INFO: 16:48:51 Connected 45.90.28.0:443 (con=4ms tls=151ms, TLS13)
INFO: 16:48:51 Connected IPv4-ADDRESS:443 (con=5ms tls=7ms, TLS13)
INFO: 16:48:51 Switching endpoint: https://SUBDOMAIN.edge.nextdns.io#IPv4-ADDRESS,IPv6-ADDRESS
```

**Comment by rs** [comment]
Still does not start thru launchd?

**Comment by pro-sumer** [comment]
> Still does not start thru launchd?

It does start via `sudo nextdns start`:

`This device is using NextDNS with this configuration.`

However, I still see this appearing in the log:

```
Jan 14 17:10:17 mbp com.apple.xpc.launchd[1] (nextdns[34026]): Service exited with abnormal code: 1
Jan 14 17:10:17 mbp com.apple.xpc.launchd[1] (nextdns): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

`nslookup` seems to work (and it is using `127.0.0.1#53`).

**Comment by pro-sumer** [comment]
I enabled logging (`stdout` and `stderr`) in the property list and got this:

```
Error: proxy: tcp: listen tcp 127.0.0.1:53: bind: address already in use
Error: proxy: tcp: listen tcp [::1]:53: bind: address already in use
Error: proxy: udp: listen udp 127.0.0.1:53: bind: address already in use
Error: proxy: udp: listen udp [::1]:53: bind: address already in use
```

(each of the lines occurring multiple times; I used `sort -u` to clean the log a bit)

Does that help?

**Comment by rs** [comment]
You probably have something already listening on the same port or nextdns launched twice in launchd.

**Comment by pro-sumer** [comment]
Have not seen this error for two days now.

**Comment by rs** [comment]
You had probably the service running twice. Closing this ticket, please reopen if it bite you again.

**Comment by pro-sumer** [comment]
Currently having it again, even after a reboot...
