### ISSUE TITLE
Custom categories

### ISSUE THREAD

**Issue by jacogreyling** [nextdns/nextdns#611]
Hi,

I really like the Parental Controls. However the customisation thereof is a little limited. I would like to create a custom category where I can selectively add apps/games/social media etc. to my category. This will allow me to switch on/off the category with a single mouse click. At the moment I have to enable/disable 10+ apps every time I want to allow my kids screen time. Custom categories will help a lot in speeding this process up.

Thanks!

**Comment by rs** [comment]
Same as other issue, please use help.nextdns.io.
