### ISSUE TITLE
Finer grained recreation times

### ISSUE THREAD

**Issue by jacogreyling** [nextdns/nextdns#612]
Hi,

One of the reasons why I bought NextDNS is because of its parental controls. However, I would like the flexibility to set **multiple** windows per day for recreation time. This is very common (at least in my house hold) where you might want to allow screen time to certain apps say between 1 - 2pm (lunch time) and then again after 6pm. Also at the moment you can't select a time frame to midnight. The 'latest' you can go to is 23:30 :( More flexible windows will be a great addition and 'complete' the solution for me.

Thanks!

**Comment by rs** [comment]
Please use help.nextdns.io for feature requests. This repository is for CLI client only.
