### ISSUE TITLE
Exclude certain source CIDRs from NextDNS

### ISSUE THREAD

**Issue by jacogreyling** [nextdns/nextdns#613]
Hi,

I'm using an Ubiquiti Dream Machine as my router. In addition I use [split-vpn](https://github.com/peacey/split-vpn) to provide VPN services to certain networks (e.g. 192.168.3.0/24). The problem is when I enable NextDNS `sudo nextdns start` it adds an iptables rule which intercepts ALL local DNS queries.

```
DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 to:127.0.0.1:5553
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 to:127.0.0.1:5553
```

This is a problem since it's also incepting DNS queries for my Open VPN network and hence causing a DNS leak.

What I've done to fix this is to override the iptables rules like so:

```
DNAT       udp  -- !192.168.3.0/24       0.0.0.0/0            udp dpt:53 to:127.0.0.1:5553
DNAT       tcp  -- !192.168.3.0/24       0.0.0.0/0            tcp dpt:53 to:127.0.0.1:5553
```
This seems to work and I'm not getting any DNS leaks anymore.

So the feature request is to add this as a config option to 'bypass' NextDNS from certain source networks / IP's. Similar to how you can specify different config ID's per network.

**Comment by jacogreyling** [comment]
Dev team, just checking to see if anyone has some thoughts around this task (is it viable)? Happy to work with the team if you need assistance.

**Comment by svenvg93** [comment]
+1

**Comment by jacogreyling** [comment]
Bump

**Comment by svenvg93** [comment]
@rs Is there away we can get this to work. Would like exclude some Guest Networks from NextDNS.

**Comment by BrianG61UK** [comment]
> Hi,
> 
> I'm using an Ubiquiti Dream Machine as my router. In addition I use [split-vpn](https://github.com/peacey/split-vpn) to provide VPN services to certain networks (e.g. 192.168.3.0/24). The problem is when I enable NextDNS `sudo nextdns start` it adds an iptables rule which intercepts ALL local DNS queries.
> 
> ```
> DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 to:127.0.0.1:5553
> DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 to:127.0.0.1:5553
> ```
> 
> This is a problem since it's also incepting DNS queries for my Open VPN network and hence causing a DNS leak.
> 
> What I've done to fix this is to override the iptables rules like so:
> 
> ```
> DNAT       udp  -- !192.168.3.0/24       0.0.0.0/0            udp dpt:53 to:127.0.0.1:5553
> DNAT       tcp  -- !192.168.3.0/24       0.0.0.0/0            tcp dpt:53 to:127.0.0.1:5553
> ```
> 
> This seems to work and I'm not getting any DNS leaks anymore.
> 
> So the feature request is to add this as a config option to 'bypass' NextDNS from certain source networks / IP's. Similar to how you can specify different config ID's per network.

Surely the nextdns cli won't do this if you configure it with:
auto-activate=false
and
setup-router=false

**Comment by ijuliank** [comment]
they doesnt seem to be taking issues serious again
