### ISSUE TITLE
Unable to update from 1.37.3 to 1.37.4 on MacOS Montery 12.0.1

### ISSUE THREAD

**Issue by bondskin** [nextdns/nextdns#616]
**Context**
 - CLI Version: nextdns version 1.37.3
 - Platform: MacOS Montery 12.0.1 (Intel chip)

I am unable to update to the latest version 1.37.4

mike@Air13-8 ~ % nextdns upgrade
INFO: OS: darwin
INFO: GOARCH: amd64
INFO: GOOS: darwin
INFO: NEXTDNS_BIN: /usr/local/bin/nextdns
**INFO: INSTALL_RELEASE: 1.37.4**
INFO: Upgrading NextDNS...
NextDNS installed and started using launchd init
mike@Air13-8 ~ % sudo nextdns stop
mike@Air13-8 ~ % sudo nextdns start
**mike@Air13-8 ~ % nextdns version  
nextdns version 1.37.3**

**Comment by Undutchable62** [comment]
The same over here!

**Comment by bondskin** [comment]
still not able to upgrade
```
mike@Air13-4 ~ % nextdns upgrade
INFO: OS: darwin
INFO: GOARCH: amd64
INFO: GOOS: darwin
INFO: NEXTDNS_BIN: /usr/local/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.5
INFO: Upgrading NextDNS...
NextDNS installed and started using launchd init
mike@Air13-4 ~ % nextdns version     
nextdns version 1.37.3
```
