### ISSUE TITLE
Stuck on "Installing NextDNS"

### ISSUE THREAD

**Issue by multiformeingegno** [nextdns/nextdns#619]
Latest version of Raspberry OS Lite. Fresh install:

_sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'_

INFO: OS: raspbian
INFO: GOARCH: armv7
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.4
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...

It remains stuck here.

**Comment by Mile-Lile** [comment]
what message you get when you try debug

`DEBUG=1 sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`

**Comment by multiformeingegno** [comment]
Nothing much..

```
DEBUG=1 sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: raspbian
INFO: GOARCH: armv7
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.7
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
DEBUG: Using deb install type

```
