### ISSUE TITLE
Use Homebrew on macOS to install/update/uninstall NextDNS

### ISSUE THREAD

**Issue by pro-sumer** [nextdns/nextdns#62]
Somehow I keep forgetting this command:

`sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`

Please use the [Homebrew](https://brew.sh) package manager on macOS, so that I can use simple(r) commands:

- `brew install nextdns`
- `brew upgrade nextdns`
- `brew uninstall nextdns`

**Comment by pro-sumer** [comment]
Oops, it's apparently already possible?

```❯ brew install nextdns
==> Installing nextdns from nextdns/tap
==> Downloading https://github.com/nextdns/nextdns/releases/download/v1.4.25/nextdns_1.4.25_darwin_amd64.tar.gz
==> Caveats
To install NextDNS, run the following command:
sudo nextdns install --config <your_conf_id>
Then setup your DNS manually to 127.0.0.1 or by running:
sudo nextdns activate
==> Summary
🍺  /usr/local/Cellar/nextdns/1.4.25: 5 files, 8.0MB, built in 5 seconds```

So maybe change this request in: "please add Homebrew to installation instructions (for macOS)".

**Comment by rs** [comment]
It is already there, in the manual install section. https://github.com/nextdns/nextdns/wiki/MacOS#manual-install

**Comment by moltar** [comment]
Interesting that search does not bring it up:

```
❯ brew search nextdns
No formula or cask found for "nextdns".
```

**Comment by moltar** [comment]
Never mind saw the instructions. Need to add a cask.

**Comment by DaveEveritt** [comment]
First time user, and I prefer the Homebrew `uninstall` option. But Homebrew doesn't seem to have a cask (Monterey):

```
> brew search nextdns
==> Formulae
getdns
```

So I'll get it from the App Store? I presume I can uninstall from the Launchpad by clicking->holding-.hitting'X'?
