### ISSUE TITLE
wrong GOARCH detected

### ISSUE THREAD

**Issue by Mile-Lile** [nextdns/nextdns#621]
**Context**
 - CLI Version: 1.37.4
 - Platform: ddwrt

During installation wrong GOARCH is detected.... armv5 instead of armv7. Probably falls back to lowest one, but can you adjust detection a little bit... I think it is problem that I have "l" at the end. armv7l instead armv7?
![Screenshot_deepin-terminal_20211128080618](https://user-images.githubusercontent.com/12752816/143733269-59da2286-3773-4d79-87fd-74b4d7ff9418.png)

![Screenshot_select-area_20211128080315](https://user-images.githubusercontent.com/12752816/143733271-513bcb5b-27ca-4ed7-8491-3ceb3205fdbf.png)

**Comment by vincentbernat** [comment]
That's expected. If you don't have "vfp" in the features, it fallbacks to arm5.  vfp is SIMD (fpa is hardware floating point, maybe we should check that instead). You can override by prepending the install command by `env FORCE_GOARCH=armv7`. That's not recommended because your kernel will have to emulate the floating point operations.

**Comment by Mile-Lile** [comment]
doesn't work that way... for every directive I get "illegal instruction"...
![Screenshot_select-area_20211128134353](https://user-images.githubusercontent.com/12752816/143768381-75d5ad7b-8cbf-41fe-b19e-a26a448e3d4c.png)

**Comment by vincentbernat** [comment]
From [Go documentation](https://go.dev/doc/install/source):
- GOARM=5: use software floating point; when CPU doesn't have VFP co-processor
- GOARM=6: use VFPv1 only; default if cross compiling; usually ARM11 or better cores (VFPv2 or better is also supported)
- GOARM=7: use VFPv3; usually Cortex-A cores

**Comment by Mile-Lile** [comment]
![Screenshot_select-area_20211128143020](https://user-images.githubusercontent.com/12752816/143769926-d7d469cd-7fa4-4685-906d-b7279b8ab9db.png)


[BCM4708](https://www.broadcom.com/products/wireless/wireless-lan-infrastructure/bcm4707-4708-4709) has Cortex™-A9 dual-core so, I suppose it should sopprt VFPv3...but, don't know how ddwt kernwl is builded, with which features... I will talk to ddwrt dev to find out, but I think it will be dead end because I read on the google that there are some licencing (GPL) problem with this VFP on linux...
