### ISSUE TITLE
Windows now reports NextDNS-Client as virus (Trojan:Win32/Bearfoos.A!ml)

### ISSUE THREAD

**Issue by gschafra** [nextdns/nextdns#622]
**Context**
 - CLI Version: v1.37.4
 - Platform: amd64

![image](https://user-images.githubusercontent.com/3999582/143836405-a605c410-db0c-4486-8fd8-d90be919eeee.png)

**Comment by rs** [comment]
You can safely create an exception.

**Comment by gschafra** [comment]
Sorry, event if I put the executable and the parent path to the whitelist, when installing the client as service using `-install` it fails with an error.

**Comment by s4parke** [comment]
I submitted a review request to Microsoft Security Intelligence for nextdns.exe (nextdns-v1.37.7) and flagged it as a false detection in Microsoft Defender 365. Hopefully it will be reviewed within 48 hours!

![MDE-submission-nextdns](https://user-images.githubusercontent.com/656510/144946012-12731aef-9867-4996-9210-4d9b18e8195f.png)

Additionally I added a comment/upvote to the file in VirusTotal.

[https://www.virustotal.com/gui/file/1e569b9f419fe61b8fd6bb7e3e54ac38f8e6fe90a6f069a202bc7e42fc0c5cde/community](https://www.virustotal.com/gui/file/1e...sha256...de/community)
`sha256: 1e569b9f419fe61b8fd6bb7e3e54ac38f8e6fe90a6f069a202bc7e42fc0c5cde`

**Comment by rs** [comment]
Thank you

**Comment by s4parke** [comment]
This now appears to be resolved (Windows 10 Security intelligence version 1.353.2226.0). **nextdns.exe** persisted after unwhitelisting, updating defs (see below), full scan in Defender, and reboot.

**MSI analyst comments:**
> The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to `c:\Program Files\Windows Defender`
2. Run `MpCmdRun.exe -removedefinitions -dynamicsignatures`
3. Run `MpCmdRun.exe -SignatureUpdate`

If it happens again, create an encrypted .zip file with the executable (password: `infected`) and submit for review at https://www.microsoft.com/en-us/wdsi/filesubmission 

![2021-12-07 09_44_44-Submission](https://user-images.githubusercontent.com/656510/145058588-4f6c9257-4276-4246-bd6b-bab4a5de4384.png)

**Comment by ItzLevvie** [comment]
cc @rs: This should probably be closed now as I'm not able to reproduce anymore with Security Intelligence version 1.355.2086.1 (Microsoft Internal Only):
![image](https://user-images.githubusercontent.com/11600822/148437276-1a8b5180-6ddb-4b08-a2ac-d0f4e5e454e3.png)
![image](https://user-images.githubusercontent.com/11600822/148436893-0c835da8-039e-4c6f-8ad3-38101cc7cc41.png)
![image](https://user-images.githubusercontent.com/11600822/148436795-3b2c47a8-0608-4b60-b536-51535736439a.png)

If you're still able to reproduce then please follow https://github.com/nextdns/nextdns/issues/622#issuecomment-988037350.

**Comment by rs** [comment]
Thx

**Comment by pdevelopement** [comment]
Be careful! It is MALWARE DEFINITELY!!!
