### ISSUE TITLE
Query Transformation or Rewrite

### ISSUE THREAD

**Issue by jimmystewpot** [nextdns/nextdns#625]
Hello,

NextDNS has some great features, thank you for putting together such a useful set of services and tools.

I have recently been experimenting with a beta IPv6 service with a local smaller ISP. This has lead me to find some interesting edge case behaviors which could be nice additions to next dns. The current behavior is that it will simply forward the request on to the upstream or answer the query if it is cached. The tool supports rewrites of domains, it would also be useful to do a similar rewrite on query types. 

An example of the default behavior
```
# host google.com
google.com has address 172.217.167.78
google.com has IPv6 address 2404:6800:4006:80a::200e
```
With query type rewrite (drop AAAA)

```
# host google.com
google.com has address 172.217.167.78
```

With query type rewrite (drop A)
```
# host google.com
google.com has IPv6 address 2404:6800:4006:80a::200e
```

The value that this feature provides is to allow users to bypass a broken IPv4 or IPv6 implementations if required. At this point in time I don't see any use cases beyond A and AAAA queries.

This type of feature could be implemented centrally similar to how your existing hostname rewrites function or it could be done via the cli tool. If you feel that this feature could be useful and that it is suited to the cli tool I could potentially do the implementation and do a pull request etc back to your code. I would need some guidance on what you felt would be the best configuration key names to use so that there is no confusion between host rewrites and whatever this feature could be called.

To give some additional context. The current work around is to use a nextdns cli forwarder to a local powerdns recursor running Lua code. If the query is of type AAAA the query is not forwarded. The type A queries are then forwarded back to the upstream nextdns servers giving the final security/privacy overlay.

**Comment by rs** [comment]
If you set the A in the rewrites it will replace AAAA and do something similar. The A will become static though.

If we were to implement selective dropping of record type, that would be on my.nextdns.io, not on CLI. Please reopen this issue as an idea on help.nextdns.io as this repository is only for CLI.

**Comment by jimmystewpot** [comment]
Thank you for your response .I will open the request via help. I wasn't sure if this would be a local cli implementation or central so thank you for the clarity.
