### ISSUE TITLE
macOS: Use reverse domain name for launchd property list file

### ISSUE THREAD

**Issue by pro-sumer** [nextdns/nextdns#63]
The launchd property list file in `/Library/LaunchDaemons` is called `nextdns.plist`. All other files in this folder use a reverse domain name to make sure their filename/label is unique. Also, Apple uses `com.example.sleep` in their [example](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html).

Please use `io.nextdns.plist` or `io.nextdns.client.plist` instead of `nextdns.plist`.

**Comment by rs** [comment]
Decided against doing this one. Would make the code more complex for little value.
