### ISSUE TITLE
"system not supported" on OpenBSD

### ISSUE THREAD

**Issue by robdejonge** [nextdns/nextdns#630]
**Context**
 - CLI Version: 1.37.4
 - Platform: OpenBSD 7.0

&lt;Describe the bug>

```
% doas sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'

INFO: OS: openbsd
INFO: GOARCH: arm64
INFO: GOOS: openbsd
INFO: NEXTDNS_BIN: /usr/local/sbin/nextdns
INFO: INSTALL_RELEASE: 1.37.4
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i):
INFO: Installing NextDNS...
DEBUG: Using bin install type
DEBUG: Installing 1.37.4 binary for openbsd/arm64 to /usr/local/sbin/nextdns
DEBUG: Downloading https://github.com/nextdns/nextdns/releases/download/v1.37.4/nextdns_1.37.4_openbsd_arm64.tar.gz
DEBUG: Start configure
DEBUG: Get configuration ID
NextDNS Configuration ID: xxx
DEBUG: Add arg -config=xxx
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: y
DEBUG: Add arg -report-client-info=true
Accept DNS request from other network hosts.
Setup as a router? (y/n): y
DEBUG: Add arg -setup-router=true
Make nextdns CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Enable caching? [Y|n]: n
Changes DNS settings of the host automatically when nextdns is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically setup local host DNS? [Y|n]: n
DEBUG: Add arg -auto-activate=false

Congratulations! NextDNS is now installed.

To upgrade/uninstall, run this command again and select the approriate option.

You can use the nextdns command to control the daemon.
Here is a few important commands to know:

# Start, stop, restart the daemon:
nextdns start
nextdns stop
nextdns restart

# Configure the local host to point to NextDNS or not:
nextdns activate
nextdns deactivate

# Explore daemon logs:
nextdns log

# For more commands, use:
nextdns help

% doas nextdns start
doas: nextdns: command not found


% doas rcctl start nextdns
rcctl: service nextdns does not exist

% ls -l $(which nextdns)
-rwxr-xr-x  1 root  wheel  0 Nov 25 12:21 /usr/local/sbin/nextdns

```

No service is installed (as is the norm on OpenBSD) and an empty script/binary is created, which obviously does nothing. 

I've also tried running the command in a root shell, to no avail. 
I've also tried running it without `doas` and it asks me for a password a few times, but results in the same.

**Comment by robdejonge** [comment]
Gave installing another try today to see if I could get this to work, and got the same result. However, a binary does get created in my home directory which also has the name `nextdns`. I have not noticed this getting created on previous tries, but can't with 100% certainty say it did not. 

However, upon trying to run it with almost any of the commands possible, I get the message "system not supported" in my terminal window. 

```
~ % ./nextdns start
system not supported
~ % ./nextdns status
system not supported
~ % ./nextdns config
system not supported
```

Running the same using `doas` gets the same result.

**Comment by robdejonge** [comment]
Moving the binary from `~/nextdns` to `/usr/local/sbin/nextdns` also makes no difference.

**Comment by mitoca** [comment]
Just wondering if NextDNS team can comment. Is OpenBSD support is something that is on the roadmap?

**Comment by robdejonge** [comment]
@mitoca Given their reputation of never commenting, responding or acknowledging anything whatsoever, I would not hold your breath. I've given up.

**Comment by robdejonge** [comment]
Gasp!!! Took only a year and nine months to … I mean shall we be generous and call this a response? 

I’ve long moved to Control D; just as good, reply within a day and engage with their community!
