### ISSUE TITLE
Linked IP not being set

### ISSUE THREAD

**Issue by Altycoder** [nextdns/nextdns#631]
- CLI Version: 1.37.7
 - Platform: Arch Linux (LTS Kernel)

I have the client set up on my Arch server, linked to a config profile and I can see from the logs and analytics pages that it's working.  All of my queries are listed and encrypted.

However the linked IP on the setup page hasn't been populated / linked, I'm assuming that the client should be designed to do that?

I realise that the client captures all DNS traffic and routes it over DoH and that the linked IP is to associate unencrypted ipv4 traffic with a client profile, but I would have thought that the client would link the IP address as well?

**Comment by rs** [comment]
Link IP is only useful for IPv4 unencrypted DNS. In your case linked IP is useless.
