### ISSUE TITLE
"too many open files" when WAN goes down then comes up.

### ISSUE THREAD

**Issue by gaia** [nextdns/nextdns#632]
**Context**
 - CLI Version: v1.37.7
 - Platform: EdgeOS

if the WAN link goes down, when it comes back upo nextdns has to be restarted because the log only shows

`oh resolve: dial tcp 1.1.1.1:443: socket: too many open files`

**Comment by BrianG61UK** [comment]
Could you share more detail like your nextdns.conf and exact router model?
Nextdns has been working well for me on my Edgerouter X, except that /var/log/messages does fill up with an alarming amount of stuff, especially when the connection comes back up.
