### ISSUE TITLE
Conditional config with multiple external forwarder and nextdns config

### ISSUE THREAD

**Issue by BirdInFire** [nextdns/nextdns#633]
Hello, 
I actually have created two Network on UDM pro ans created two VLAN for two type of IOT (IOT and NOT), i would like to use multiple forwarder (since i use NEXTDNS only on my own vlan only, and external provider for other but it seem if i config one "forwarder" all my network are pushed on the forwarder and ignore other forwarder / nextdns config.

Is this a normal behavior or is it a bug (can you cange my title into [BUG] or [Feature request], to match if it's a bug or not).

**Comment by BirdInFire** [comment]
Note if it's a feature request : 
What's i ask (exemple configuration)

192.168.1.0/24=NEXTDNSID
192.168.2.0/24=https://first.dns.com/dns-query
192.168.3.0/24=https://other.dns.com/dns-query

**Comment by rs** [comment]
Forwarder are only supported for domaines, not source IPs.
