### ISSUE TITLE
Very high CPU/RAM usage on OpenWRT 21.02.1 Mi Router Mini 

### ISSUE THREAD

**Issue by shivv3r** [nextdns/nextdns#634]
**Context**
Since 21.02 I'm having this issue " Unable to execute opkg install command: SyntaxError: Unexpected end of JSON input " when installing NextDNS package on my Xiaomi Wifi Mini Router, any idea how to fix it?

I saw now that the NextDNS was installed anyway, but when I start it the network doesn't work properly, very slow and losing the connection.

 - CLI Version: 1.37.7 but same issue on few previous versions
 - Platform: OpenWRT 21.02.1

Describe the bug
NextDNS on OpenWRT takes 543% of memory and 50% of CPU

Tue Dec 14 00:10:36 2021 daemon.warn nextdns[28407]: Endpoint failed: https://dns.nextdns.io#116.203.147.209,2a01:4f8:c0c:fa3f::1: roundtrip: context deadline exceeded

Tue Dec 14 00:10:41 2021 daemon.warn nextdns[28407]: Endpoint failed: https://dns.nextdns.io#217.146.22.163,2a00:11c0:e:ffff:1::d: roundtrip: context deadline exceeded

Tue Dec 14 00:10:46 2021 daemon.warn nextdns[28407]: Endpoint failed: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::: roundtrip: context deadline exceeded

Tue Dec 14 00:10:52 2021 daemon.warn nextdns[28407]: Endpoint failed: https://dns2.nextdns.io#45.90.30.0,2a07:a8c1::: roundtrip: context deadline exceeded

**Comment by nikojaro** [comment]
I have the same problem

**Comment by dotamidplayer** [comment]
use the snapshot version [f535f8c](https://github.com/nextdns/nextdns/commit/f535f8ccc12bff49f648c76cdcb57464d38c1b36) no high cpu/ram usages so far
![DCED1D57-66F4-479C-B6F2-0B829438C9C0](https://user-images.githubusercontent.com/48650357/148707961-10a8f01e-81a2-4970-9f66-c86412bfb158.jpeg)
![049F90D2-86DB-428B-8C62-1D40EFD6689D](https://user-images.githubusercontent.com/48650357/148707964-aa28fad9-f9ee-445d-90cf-d689bc7b50f1.jpeg)

**Comment by UrbanPotato** [comment]
this is still an issue even on the latest release
did this not get merged in ?
