### ISSUE TITLE
Will not update or install on UDMPro

### ISSUE THREAD

**Issue by lynnsorenson** [nextdns/nextdns#635]
**Context**
 - CLI Version: Will not install
 - Platform: UbiOS

I had NextDNS installed and running on my UDMPro, after I updated to its latest official firmware 1.11.0 (was on 1.10.4 if not mistaken) I also proceeded to update NextDNS to latest (1.37.7), but upgrade failed, so I uninstalled and rebooted the machine, after which I tried a clean install but it still will not work, the following is the result in debug mode:

`# sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: INSTALL_RELEASE: 1.37.7
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
DEBUG: Using ubios install type
no such directory for freezer.state
Error: `/usr/bin/runc pause 279a3c753bcd8129552f338ca419c858858bf45232acb660f7a2c674296551f1` failed: exit status 1
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
curl is already the newest version (7.52.1-5+deb9u16).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
Reading package lists...
W: Unable to read /etc/apt/-/ - DirectoryExists (2: No such file or directory)
W: Unable to read /etc/apt/sources.list.d/nextdns.list - RealFileExists (2: No such file or directory)
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nextdns
Error: non zero exit code: 100: OCI runtime error
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i): e
#`

I realize a similar issue was discussed #563 but it did not seem to be resolved.

**Comment by clayton006** [comment]
Having the same issue. I had nextdns installed but it would not activate or run. Unable to uninstall and now install. I'm on version 1.11.0 of my UDM pro

**Comment by jinie** [comment]
Same issue on both my UDM Base and UDM Pro. UnifiOS 1.11 on both. Was working on 1.10.x

After upgrading, I tried reinstalling NextDNS which failed. I then uninstalled NextDNS and attempted to reinstall it, but it fails to add the apt source to /etc/apt/sources.list.d, so it never installs.

**Comment by lynnsorenson** [comment]
It's working again, thank you.

**Comment by timrettop** [comment]
Looks like its been updated on nextdns.io/install, I just updated from 1.37.4 to 1.37.7 successfully. 
Thanks!
