### ISSUE TITLE
NextDNS blocks WeChat login page

### ISSUE THREAD

**Issue by maXity** [nextdns/nextdns#636]
Hello,

I cannot open the WeChat login verification page while my iPhone is set to NextDNS.

The blocked domains appear to be minorshort.weixin.qq.com and shminorshort.weixin.qq.com (see below).

![image](https://user-images.githubusercontent.com/23332112/147407988-e8cc1bfa-002c-4d19-b38b-3fc280209dd5.png)

I know how to whitelist them, but I would argue this should not be blocked in the first place.

**Comment by rs** [comment]
Please report this under the https://github.com/nextdns/metadata repository. This repository is for the CLI client.
