### ISSUE TITLE
macOS: code sign executable (& property lists?)

### ISSUE THREAD

**Issue by pro-sumer** [nextdns/nextdns#64]
Apparently the macOS executable is not code signed:

```
❯ codesign -dv --verbose=4 /usr/local/Cellar/nextdns/1.4.25/bin/nextdns
/usr/local/Cellar/nextdns/1.4.25/bin/nextdns: code object is not signed at all
```

Can you please code sign the executable (and property lists) so that we know we can trust them?

See https://developer.apple.com/support/code-signing

**Comment by pro-sumer** [comment]
You might even want to "notarize" it?

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by rs** [comment]
Not easy to automate so it may not happen soon. Also, the code is open source so easier to trust.

**Comment by specter78** [comment]
https://github.com/mitchellh/gon

This can help automate notarization.
