### ISSUE TITLE
configuration ID no passthrough on Void Linux

### ISSUE THREAD

**Issue by ghost** [nextdns/nextdns#641]
**Context**
 - CLI Version: 1.37.7
 - Platform: Void Linux

After following the instructions on wiki. The page shows `This device is using NextDNS with no configuration.`

`/etc/nextdns.conf`

```
log-queries false
mdns all
auto-activate true
max-inflight-requests 256
setup-router false
listen localhost:53
cache-size 10MB
max-ttl 5s
report-client-info true
discovery-dns 
bogus-priv true
control /var/run/nextdns.sock
config <id>
cache-max-age 0s
use-hosts true
detect-captive-portals false
hardened-privacy false
timeout 5s
```

**Comment by Mile-Lile** [comment]
You probably forget to enter one, when NEXTDNS CLI asked you during setup...

add it manually with:

`sudo nextdns config set -config abcdef` where abcdef is your ID

then

`sudo nextdns restart`

**Comment by wuzhe** [comment]
> You probably forget to enter one, when NEXTDNS CLI asked you during setup...
> 
> add it manually with:
> 
> `sudo nextdns config set -config abcdef` where abcdef is your ID
> 
> then
> 
> `sudo nextdns restart`

This doesn't fix the issue

**Comment by 0xJes** [comment]
Same problem here, using Void linux, cli ver: 1.37.7

My config is:
```
log-queries false
max-ttl 5s
mdns all
bogus-priv true
timeout 5s
max-inflight-requests 256
setup-router false
listen localhost:53
config xxxxxx
report-client-info true
detect-captive-portals false
use-hosts true
hardened-privacy false
auto-activate true
control /var/run/nextdns.sock
cache-size 10MB
cache-max-age 0s
discovery-dns
```

**Comment by RunningDroid** [comment]
Can you give the output of `pgrep -a nextdns`?
I think I experienced this when nextdns replaced my `/etc/sv/nextdns/run` with one that dropped the `-config-file /etc/nextdns.conf` argument.

**Comment by 0xJes** [comment]
> Can you give the output of `pgrep -a nextdns`? I think I experienced this when nextdns replaced my `/etc/sv/nextdns/run` with one that dropped the `-config-file /etc/nextdns.conf` argument.

```
jes ) pgrep -a nextdns
2329 /usr/bin/nextdns run
```

**Comment by mustarde** [comment]
Can confirm the problem is still there
