### ISSUE TITLE
unable to set endpoint ID using MAC address for guest network device

### ISSUE THREAD

**Issue by GvXV3toYUNbmP** [nextdns/nextdns#643]
**Context**
 - CLI Version: 1.37.7
 - Platform:Asuswrt merlin

&lt;Describe the bug>
unable to set nextdns endpoint ID using Mac address if device is in guest network.  Using IP address/sub works fine.

**Comment by rs** [comment]
Please make sure the mac is first in the list of “config”. Order matter (first match wins).

**Comment by GvXV3toYUNbmP** [comment]
Thanks it works
