### ISSUE TITLE
Why are queries to *.openthread.thread.home.arpa being forwarded?

### ISSUE THREAD

**Issue by mojo333** [nextdns/nextdns#646]
Got a new Apple TV which contains their new Thread platform and I can see in the logs thousands of entries for *.openthread.thread.home.arpa e.g. livingroom.openthread.thread.home.arpa etc - "home.arpa" shouldn't be forwarded according to https://datatracker.ietf.org/doc/html/rfc8375 ?

This might be happening but looking in **proxy\util.go** is the issue with a full stop at the end of "arpa" which is causing this?

```
func ptrIP(ptr string) net.IP {
	if !strings.HasSuffix(ptr, ".arpa.") {
		return nil
	}
```

**Comment by rs** [comment]
This condition is only for PTR parsing. There is currently no filter on which domains are forwarded. Those domains won't go further but this gives you the opportunity to rewrite domains, even local ones.
