### ISSUE TITLE
nextdns not resolving RFC1918 hostnames

### ISSUE THREAD

**Issue by GlenHertz** [nextdns/nextdns#647]
**Context**
 - CLI Version: 1.37.7
 - Platform: x64

I installed nextdns on the command line with these settings:
```
config XXXXXX
auto-activate true
bogus-priv true
timeout 5s
report-client-info true
discovery-dns 127.0.0.1:5555
mdns all
use-hosts false
max-inflight-requests 256
log-queries false
cache-max-age 0s
detect-captive-portals false
max-ttl 5s
hardened-privacy false
setup-router false
listen localhost:53
listen 10.4.0.1:53
listen 10.10.0.1:53
listen 10.19.0.1:53
listen 10.46.0.1:53
listen 10.50.0.1:53
listen 10.99.0.1:53
listen 10.107.0.1:53
listen 10.108.0.1:53
listen 172.16.0.1:53
listen 192.168.1.1:53
listen 192.168.86.1:53
control /var/run/nextdns.sock
cache-size 10MB
```

I'm using opnsense and guessing a bit how to install it.
1. I changed the unbound address to listen to 5555
2. I changed the nextdns setting to `discovery-dns 127.0.0.1:5555` (see above) while also setting in unbound `Register DHCP leases` and `Register DHCP static mappings` so NextDNS can find the host names of the devices on the network -- this seems to work. 

Everything seems to work except `ping a_local_host` returns `127.0.0.1` instead of `192.168.1.33`.  All my local hostnames are sinkholed.  What setting should I change?

**Comment by BrianG61UK** [comment]
I'm a little confused by your language, but I think you should try with `bogus-priv false`

**Comment by GlenHertz** [comment]
I tried that but it didn't fix the issue.  The issue is hosts on my subnet don't get resolved correctly (only external hosts do).  If I go to my `printer` I get back the IP of `127.0.0.1`.  I'm trying a basic setup starting with a working Unbound config to resolve hostnames on my internal subnet and supply local device names to NextDNS.  If something is confusing then please ask a question to clarify.
