### ISSUE TITLE
Device name do not show up in logs

### ISSUE THREAD

**Issue by aasiddiq** [nextdns/nextdns#648]
**Context**
 - CLI Version: 1.37.7
 - Platform: Raspbian 11 (bullseye)

I am using nextdns with the below configuration on a raspberry pi and using the IP as my DNS in the router. I see the device names like `Device #xxxx`. When I added the IP in `discovery-dns` it started showing up correct names for some time but later today when I checked they had all gone back the generic format.

Below is the conf file.
```
log-queries false
max-ttl 5s
bogus-priv true
listen localhost:53
config <removed>
cache-max-age 0s
report-client-info true
mdns all
hardened-privacy false
max-inflight-requests 256
setup-router true
control /var/run/nextdns.sock
detect-captive-portals false
timeout 5s
auto-activate true
cache-size 10MB
discovery-dns 192.168.1.1 
use-hosts true

```

**Comment by rs** [comment]
Please show a few log entries (the right part with host details) for device with failed names.

**Comment by rs** [comment]
What do you get for `dig -x 192.168.1.102 @192.168.1.1`?

**Comment by rs** [comment]
You have setup your router as discovery-dns to get names, but your router does not seem to know this device, so the CLI is unable to report its name.

**Comment by aasiddiq** [comment]
@rs So I tried the same command for a device it is able to identify and they both seem to give similar result from `dig`, is this something still at my router's configuration or something else might be issue?
.27 is for the iPhone .46 is another device which my router shows the name.
![image](https://user-images.githubusercontent.com/9424117/150473790-6f02621e-2c86-4adf-8c38-b1285fa5c4af.png)

![image](https://user-images.githubusercontent.com/9424117/150474031-2c7689d2-08af-42d5-a9ed-909dacfb5a75.png)

![150474378-ad955e4f-ea8e-4394-86e9-2bc799caca51](https://user-images.githubusercontent.com/9424117/150474510-c75fc077-616a-4d53-8b1b-500103372a4f.png)

**Comment by rs** [comment]
Your router knows the name from DHCP but does not seem to expose it over DNS.

**Comment by aasiddiq** [comment]
Is that a capability in the router? Or something can be configured at the nextdns side?

**Comment by rs** [comment]
It's in the router. Some router may not have this capability though.
