### ISSUE TITLE
Little Snitch 5 on macOS fails to display hostnames on alert dialogs when nextdns CLI is installed/activated

### ISSUE THREAD

**Issue by sneak** [nextdns/nextdns#650]
**Context**
 - CLI Version: nextdns version 1.37.7
 - Platform: macOS 12.1 (21C52)

When nextdns CLI is installed via `sudo nextdns install` and `sudo nextdns activate`, Little Snitch 5 alert popups no longer show hostnames, just IP addresses.  This makes it difficult to determine the purpose of the connection and makes it harder to identify the rule.  I'm not sure if this is a bug in Little Snitch or in NextDNS, but it doesn't happen (the hostnames are displayed correctly) when NextDNS CLI isn't installed/activated.

**Comment by ignoramous** [comment]
NextDNS likely hides the DNS queries from LittleSnitch. It isn't a bug... in fact, it might be a result of both these software working as intended.

**Comment by kubat** [comment]
I am also seeing this bug with

- CLI Version: nextdns version 1.37.11
- Platform: macOS 12.5 (21G72
- Little Snitch: 5.4.2 (nightly) (6260)

Little Snitch is able to see the domain from DPI (clicking the (i) icon in the modal).
