### ISSUE TITLE
NextDNS CLI not working on UDM

### ISSUE THREAD

**Issue by onegun15** [nextdns/nextdns#651]
I installed successfully the nextdns CLI on my UDM Base but it does not show me as connected when I go to nextdns. I have changed the DNS IP in my network settings as well and checked the status using nextdns status and it came back as running.

**Comment by chr-lei** [comment]
Not a NextDNS staffer but I run the CLI on my UDM and have worked through some issues myself. 3 easy ?s:
1. Are your devices using the UDM's IP address for their DNS? The CLI will capture DNS traffic bound for the UDM IPs and forward to NextDNS.
2. Are there any errors in `nextdns log`?
3. If you run `iptables -t nat -L PREROUTING` on your UDM, do you see an entry for NextDNS? Should look like this:
`NEXTDNS    all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL`

**Comment by onegun15** [comment]
> Not a NextDNS staffer but I run the CLI on my UDM and have worked through some issues myself. 3 easy ?s:
> 
> 1. Are your devices using the UDM's IP address for their DNS? The CLI will capture DNS traffic bound for the UDM IPs and forward to NextDNS.
> 2. Are there any errors in `nextdns log`?
> 3. If you run `iptables -t nat -L PREROUTING` on your UDM, do you see an entry for NextDNS? Should look like this:
>    `NEXTDNS    all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL`

Thanks for the response and help! 

1.My devices are using the IP address listed on the NextDNS page I have an account on. Is that not the correct way to do it? Should I change their DNS to the UDM IP? 

2.I have not seen any out of the ordinary errors in the log.

3. I do not run iptables on my UDM. Is this something you would recommend?

**Comment by makitsune** [comment]
I started having problems recently with new Unifi updates. I'm using a linked ip in nextdns for the time being.

After running the installer and running `nextdns` it prints `Error: non zero exit code: 1: OCI runtime error` at the bottom which I'm not sure is new or not.

My `nextdns log` returns this:
```
Feb 09 19:03:28 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
Feb 09 19:03:28 ubnt nextdns[14699]: Starting NextDNS 1.37.7/linux on localhost:5553
Feb 09 19:03:28 ubnt nextdns[14699]: Starting mDNS discovery
Feb 09 19:03:28 ubnt nextdns[14699]: Listening on TCP/127.0.0.1:5553
Feb 09 19:03:28 ubnt nextdns[14699]: Listening on UDP/127.0.0.1:5553
Feb 09 19:03:28 ubnt ssh[14700]: Welcome to UbiOS
Feb 09 19:03:28 ubnt ssh[14700]: By logging in, accessing, or using the Ubiquiti product, you
Feb 09 19:03:28 ubnt ssh[14700]: acknowledge that you have read and understood the Ubiquiti
Feb 09 19:03:28 ubnt ssh[14700]: License Agreement and agree to be bound by its terms.
Feb 09 19:03:28 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
Feb 09 19:03:33 ubnt nextdns[14699]: Setting up router
Feb 09 19:03:33 ubnt nextdns[14699]: Setting up router: exit status 1:
Feb 09 19:03:33 ubnt nextdns[14699]: Activating
Feb 09 19:03:33 ubnt nextdns[14699]: Activate: setup resolv.conf: rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy
Feb 09 19:03:40 ubnt nextdns[14699]: Received signal: terminated
Feb 09 19:03:40 ubnt nextdns[14699]: Stopping NextDNS 1.37.7/linux
Feb 09 19:03:40 ubnt systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Feb 09 19:03:40 ubnt nextdns[14699]: Restore router settings
Feb 09 19:03:40 ubnt nextdns[14699]: Restore router settings: exit status 1:
Feb 09 19:03:40 ubnt nextdns[14699]: Deactivating
Feb 09 19:03:40 ubnt nextdns[14699]: NextDNS 1.37.7/linux stopped
Feb 09 19:03:40 ubnt systemd[1]: nextdns.service: Succeeded.
Feb 09 19:03:40 ubnt systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
Feb 09 19:03:40 ubnt systemd[1]: nextdns.service: Consumed 280ms CPU time.
Feb 09 19:03:41 ubnt systemd[1]: Starting NextDNS DNS53 to DoH proxy....
Feb 09 19:03:41 ubnt nextdns[15050]: Starting NextDNS 1.37.7/linux on localhost:5553
Feb 09 19:03:41 ubnt nextdns[15050]: Listening on TCP/127.0.0.1:5553
Feb 09 19:03:41 ubnt nextdns[15050]: Listening on UDP/127.0.0.1:5553
Feb 09 19:03:41 ubnt nextdns[15050]: Starting mDNS discovery
Feb 09 19:03:41 ubnt ssh[15051]: Welcome to UbiOS
Feb 09 19:03:41 ubnt ssh[15051]: By logging in, accessing, or using the Ubiquiti product, you
Feb 09 19:03:41 ubnt ssh[15051]: acknowledge that you have read and understood the Ubiquiti
Feb 09 19:03:41 ubnt ssh[15051]: License Agreement and agree to be bound by its terms.
Feb 09 19:03:41 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
Feb 09 19:03:46 ubnt nextdns[15050]: Setting up router
Feb 09 19:03:46 ubnt nextdns[15050]: Setting up router: exit status 1:
Feb 09 19:03:46 ubnt nextdns[15050]: Activating
Feb 09 19:03:46 ubnt nextdns[15050]: Activate: setup resolv.conf: rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy
```

My `/etc/resolv.conf` which is symlinked to `/tmp/resolve.conf` is:
```
# Generated automatically by ubios-udapi-server
nameserver 127.0.0.1
```
