### ISSUE TITLE
NextDNS stop working after UDM (UniFi OS) update

### ISSUE THREAD

**Issue by o42o** [nextdns/nextdns#661]
- CLI Version: 1.37.7
 - Platform: UniFi OS Version 1.11.4

My UDM updated last night automatically to 1.11.4. This morning, the CLI was not working. The logs on my.nextdns.io stop at the time of the update.

When I connected through SSH on my UDM, nextdns command did not work
`# nextdns activate`
`-sh: nextdns: not found`

I add to run the following command
`sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`

Remove NextDNS and install it after. The configuration was still there after the remove/install process.

Do you need any log to investigate?

**Comment by BlvckWolv** [comment]
I got the same issue also. Currently on 1.37.7 attempting to update to 1.37.8, but it keeps failing. 
![nextdns](https://user-images.githubusercontent.com/83855479/156975753-36700f44-cce2-4a1a-9366-0795fb5bded0.PNG)
