### ISSUE TITLE
1.37.8 won't install

### ISSUE THREAD

**Issue by janthony6** [nextdns/nextdns#662]
`
**W: GPG error: https://repo.nextdns.io/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 467A7CCC8ACFA0B7
W: The repository 'https://repo.nextdns.io/deb stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nextdns is already the newest version (1.37.7).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.`

**Comment by rs** [comment]
Try again please.

**Comment by janthony6** [comment]
this didn't work again:

Reading package lists... Done
W: GPG error: https://repo.nextdns.io/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 467A7CCC8ACFA0B7
W: The repository 'https://repo.nextdns.io/deb stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by janthony6** [comment]
`cat /etc/os-release`
root@UDMPROSE:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

`cat /etc/apt/sources.lists/nextdns.list`
cat: /etc/apt/sources.lists/nextdns.list: No such file or directory


md5sum: /usr/share/keyrings/nextdns.gpg: No such file or directory

UDM-SE firmware 2.3.15

**Comment by vincentbernat** [comment]
Then can you do:
- `podman exec unifi-os cat /etc/apt/sources.lists/nextdns.list`
- `podman exec unifi-os md5sum /usr/share/keyrings/nextdns.gpg`
- `podman exec unifi-os cat /etc/os-release`

**Comment by janthony6** [comment]
UDM-SE doesn't use podman.

**Comment by janthony6** [comment]
its under sources.list.d

root@UDMPROSE:~# cat /etc/apt/sources.list.d/nextdns.list
deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main

**Comment by vincentbernat** [comment]
You can get `nextdns.gpg` [here](https://repo.nextdns.io/nextdns.gpg). Did you install from a snapshot? It is a bit unexpected you have `nextdns.list`, but not `nextdns.gpg`.

**Comment by janthony6** [comment]
maybe its an issue with 1.37.7 persisting upgrades now. I tried installing gpg and then installing again. it still doesn't work but throws no errors. I removed nextdns and tried installing again - still doesn't work - instead it reinstalls 1.37.7.

**Comment by vincentbernat** [comment]
The version is published on GitHub but the repository build [failed](https://github.com/nextdns/nextdns/actions/runs/1943360284). A new version is currently [building](https://github.com/nextdns/nextdns/actions/runs/1947379373).

**Comment by janthony6** [comment]
okay. I just tried again with 1.37.9 and it failed too. haven't seen this before where it takes a while after publish to install when the installer finds it.

**Comment by vincentbernat** [comment]
The repository build did not succeed either. Hopefully, we will fix this soon.

**Comment by janthony6** [comment]
> You can get `nextdns.gpg` [here](https://repo.nextdns.io/nextdns.gpg). Did you install from a snapshot? It is a bit unexpected you have `nextdns.list`, but not `nextdns.gpg`.

Hi,

Just to note - anytime the UDMSE updates, this file is deleted and needs to be replaced in keyrings otherwise nextdns will no longer install/update on the router.
