### ISSUE TITLE
Manjaro Linux ERROR: Unsupported OS: Linux

### ISSUE THREAD

**Issue by IanQS** [nextdns/nextdns#67]
Running

```
sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"' 
```

I get 

```
ERROR: Unsupported OS: Linux
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
ERROR: Cannot detect running environement.
```

Even though I'm running Arch Linux. Not really sure what the recommended thing to do is. I also tried running 

`DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"` but got the same error. Not really much to go off of so I wasn't sure if I should email the devs as recommended on the [Troubleshooting](https://github.com/nextdns/nextdns/wiki/Linux-Arch#troubleshooting) section

**Comment by rs** [comment]
What do you get for uname -o?

**Comment by IanQS** [comment]
```
uname -o
GNU/Linux
```

**Comment by PoorPocketsMcNewHold** [comment]
Sorry to necro this closed issue, 
but do know that you can also manually install it from the AUR as well, instead of the automatic script.
Instructions available here : https://github.com/nextdns/nextdns/wiki/Linux-Arch
