### ISSUE TITLE
IPV6 support for CLI (UniFi)

### ISSUE THREAD

**Issue by mbnn** [nextdns/nextdns#671]
Hello there,

I was wondering and I cannot find it anywhere in the documentation, does the CLI for the UniFiOS support IPV6 by default or do you need to enable something manually? There isn't much to find about this topic in the wiki.

I would like to have both IPV4 and IPV6 active if possible 😀  Thanks.

**Comment by quantumpacket** [comment]
If I'm not mistaken it appears it does automatically setup IPv6 when configured as shown here: https://github.com/nextdns/nextdns/blob/master/router/ubios/setup.go#L86-L88
