### ISSUE TITLE
Add all TLDs to block list

### ISSUE THREAD

**Issue by bcardarella** [nextdns/nextdns#677]
I'd like to use NextDNS to lock out every DNS request but then selectively opt into the domains that are allowed via the Allowlist. From what I understand the only way to do this is use the Security/Block TLDs feature. However, there are hundreds of TLDs and clicking each one by one isn't practical.

Can we get a way to disallow all TLDs or just a simple`*` wildcard for the Blocklist?

**Comment by rs** [comment]
This repository is about the CLI client. For feature requests on the NextDNS service, please use https://help.nextdns.io.
