### ISSUE TITLE
Nextdns doesn't installs on Linux Mint 20.03

### ISSUE THREAD

**Issue by LONEWALKER01** [nextdns/nextdns#679]
**Context**
 - CLI Version: 1.37.11
 - Platform: Linux Mint 20.3 x86_64

&lt;Describe the bug>
It just doesn't install for some reason. I tried editing the /etc/nextdns.conf file too, to check whether there was some sort of error, but I couldn't find anything. Below is the screenshot. 
![image](https://user-images.githubusercontent.com/86109244/162279910-8da700c7-b33c-490f-8a47-b6c60f058103.png)

**Comment by RPMozley** [comment]
Try `nextdns restart`
Saw this recently after an issue connecting to our printer. 
Status showed as not installed but it definitely was, after restart command it was back to showing running.
