### ISSUE TITLE
Windows app does not get config updates

### ISSUE THREAD

**Issue by ldormoy** [nextdns/nextdns#68]
Hi,

Thanks for this awesome service!

I'm using nextdns on Windows10 and I noticed that the client does not get configuration updates.

For instance if I add a domain to the whitelist, it won't resolve properly until I restart the nextdns application on my laptop. Then it works fine.

I can confirm that it's a client issue, as I successfully use the same configuration on my Galaxy S8 Android smartphone.

client version: 1.0.12
Windows version: 10.0.19041.21

**Comment by rs** [comment]
Windows has a DNS cache. You need either flush windows cache or wait for the cache to expire.

**Comment by ldormoy** [comment]
Thanks! `ipconfig /flushdns` indeed does the trick
