### ISSUE TITLE
DOH and DOT Not stable again

### ISSUE THREAD

**Issue by kiro102000** [nextdns/nextdns#680]
**Context**
 - CLI Version: DOH3, yoga using the NextDNS config, DOT on android phone
 - Platform: chrome on windows and android, yoga for windows, DOT on Android phone

&lt; keeps telling me that "This device is using NextDNS with no configuration.
Make sure you use the DNS-over-HTTPS endpoint shown below."
also
"This device is using NextDNS with no configuration.
Make sure you use the DNS-over-TLS endpoint shown below."

**Comment by kiro102000** [comment]
issue back again 2day

**Comment by rs** [comment]
See other issue.
