### ISSUE TITLE
Conditional configuration not working

### ISSUE THREAD

**Issue by mad-it** [nextdns/nextdns#681]
**Context**
 - CLI Version: 1.37.11
 - Platform: UnifyOS (UDM-base) 1.11.0

I have the following nextdns config:
```
use-hosts true
control /var/run/nextdns.sock
cache-size 10MB
discovery-dns 
hardened-privacy false
auto-activate false
max-ttl 5s
report-client-info true
mdns all
detect-captive-portals false
setup-router true
bogus-priv true
timeout 5s
max-inflight-requests 256
listen localhost:53
config 192.168.2.0/24=yyyyy
config xxxxxx
log-queries false
cache-max-age 0s
```

I am in the 192.168.2.0/24 vlan and nextdns is not forwarding requests to the configured `yyyyy`.

This is from logs from a machine in that specific vlan.

```
wlo1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.134  netmask 255.255.255.0  broadcast 192.168.2.255

curl -L test.nextdns.io
{
	"status": "ok",
	"protocol": "DOH",
	"profile": "<redacted>",
	"client": "<redacted>",
	"srcIP": "<redacted>",
	"destIP": "95.179.134.211",
	"anycast": false,
	"server": "vultr-ams-1",
	"clientName": "nextdns-cli",
	"deviceName": "<redacted>",
	"deviceID": "97D3D"
}
```

When I go to the UI on the machine I am on it says I am currently on the "default configuration" and not the configuration for the specified VLAN.

**Comment by Moareulf** [comment]
I noticed this issue as well, have debugged and found a logic issue with the matching code. It always matches the default configuration.

**Comment by Moareulf** [comment]
I have raised a pull request for this, hopefully the maintainer accept. First ever pull request I've done for a public repo so hopefully I've got it right.
