### ISSUE TITLE
Voicemail not working with Nextdns enabled

### ISSUE THREAD

**Issue by CloneVince** [nextdns/nextdns#682]
**Context**
 - CLI Version: Nextdns app from AppStore / Profile generated by Nextdns
 - Platform: iOS 15

&lt;Describe the bug>
With iOS 15 we ça choose with DNS we use.
As I choose DNS with AppStore App or with the generated profile, I can't get my voicemail.
I tried lots of settings, without success.
As I choose Auto for DNS => airplane mode enable => airplane mode disable, I get instant my voicemail.
If i'm using my home VPN which is using Nextdns on my RT2600ac, no problem.

For information, my provide is Orange (France) but same thing with Free or others.

Thanks for your help
(in meantime, I use Orange DNS)

**Comment by rs** [comment]
It's a know issue with Orange and encrypted DNS in general (not specific to NextDNS). We are working with them trying to find the issue. This is unrelated to the CLI so I'm closing this issue.
