### ISSUE TITLE
Win: - NO Tap adapter simple mode installation?

### ISSUE THREAD

**Issue by Owyn** [nextdns/nextdns#688]
I just wanted a simple dns local service (like the dnsproxy I'm currently using) but it installed some weird tap adapter instead (and also DNSunleak while I didn't ask for it),
I'm also sharing internet connection through my PC and my notebooks and phones and with dnsproxy (and 127.0.0.1 specified in ipv4 properties as the dnsserver) they use it to make DNS requests but with this weird TAP adapter thingy - they do not use it and continue using default dns address from my ISP connection

so, an option to install in classic dns service mode on windows without any tap adapters would be nice.

**Comment by rs** [comment]
This issue is for the windows repository and is fixed in the v3 branch.
