### ISSUE TITLE
NextDNS Mac App using native dns-over-https?

### ISSUE THREAD

**Issue by shapiro125** [nextdns/nextdns#689]
Hello – not sure if this is the right place, but I was just wondering if there's anything on the roadmap to convert the NextDNS mac app away from the VPN implementation and to native DNS-over-HTTPS like the iOS app? My computer sometimes stumbles over enabling the VPN properly on startup, but the encrypted DNS feature on iOS has been rock solid. Thanks!

**Comment by thalamus** [comment]
You're best off just using the profile generator rather than the app. 

Profiles use the native implementation: https://apple.nextdns.io

**Comment by rs** [comment]
There are still problematic bugs with Apple’s DNS profile on MacOS that prevents us from migrating to it. Closing as this repository is for the CLI. Please use help.nextdns.io for such discussion.
