### ISSUE TITLE
Faulty uninstaller: leaves autorun & win tap driver behind

### ISSUE THREAD

**Issue by Owyn** [nextdns/nextdns#690]
**Context**
 - CLI Version: NextDNSSetup-2.2.1.exe
 - Platform: Win10

&lt;Describe the bug>
Installed, Uninstalled - it left its autorun & windows network tap driver behind in the system even after the restart

**Comment by rs** [comment]
This is not the right repository for windows app. It is also a known issue that will be fixed with next revision (we are moving away from TAP).
