### ISSUE TITLE
Error Starting NextDNS USG DM Pro

### ISSUE THREAD

**Issue by ampnh603** [nextdns/nextdns#691]
Greetings, Attempting to setup/install NextDNS on my DM Pro and I'm getting the below error when I attempt to start/configure the service.

**# nextdns start**
Error: systemctl start nextdns.service: exit status 1: Job for nextdns.service failed because the control process exited with error code.
See "systemctl status nextdns.service" and "journalctl -xe" for details.

Error: non zero exit code: 1: OCI runtime error

**# nextdns version**
nextdns version 1.37.11

**# nextdns log**
May 03 14:42:30 ubnt nextdns[14545]: Starting NextDNS 1.37.11/linux on localhost:53
May 03 14:42:30 ubnt nextdns[14545]: Listening on TCP/127.0.0.1:53
May 03 14:42:30 ubnt nextdns[14545]: Listening on UDP/127.0.0.1:53
May 03 14:42:30 ubnt nextdns[14545]: Startup failed: proxy: tcp: listen tcp 127.0.0.1:53: bind: address already in use
May 03 14:42:30 ubnt nextdns[14545]: Error: proxy: tcp: listen tcp 127.0.0.1:53: bind: address already in use
May 03 14:42:30 ubnt systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 03 14:42:30 ubnt ssh[14546]: Welcome to UbiOS
May 03 14:42:30 ubnt ssh[14546]: By logging in, accessing, or using the Ubiquiti product, you
May 03 14:42:30 ubnt ssh[14546]: acknowledge that you have read and understood the Ubiquiti
May 03 14:42:30 ubnt ssh[14546]: License Agreement and agree to be bound by its terms.
May 03 14:42:30 ubnt systemd[1]: nextdns.service: Failed with result 'exit-code'.
May 03 14:42:30 ubnt systemd[1]: Failed to start NextDNS DNS53 to DoH proxy..
May 03 14:42:30 ubnt systemd[1]: nextdns.service: Consumed 43ms CPU time.

**Comment by seanbarr1988** [comment]
Is there any update on this error?   experiencing the same issue and had to uninstall. now I can no longer install nextdns.

**Comment by rs** [comment]
Does this still happen with the last revision?
