### ISSUE TITLE
OpenWrt client broken after attended sysupgrade

### ISSUE THREAD

**Issue by ozgunawesome** [nextdns/nextdns#693]
**Context**
 - CLI Version: 1.37.11-1
 - Platform: OpenWrt 21.04.3 any platform

&lt;Describe the bug>

OpenWrt has an “attended sysupgrade” mechanism that builds a custom firmware upgrade file on a remote build server, with all opkg packages preinstalled and the configuration files preserved across the reflash.

If the router is upgraded via this mechanism, the Nextdns init.d script located at `/etc/init.d/nextdns` will not be preserved and the system is left with a non functioning Nextdns client, which can only be fixed by manually removing and reinstalling the package.

This is not desirable and sometimes not even possible because the preinstalled packages get baked into the read only part of the firmware, but when reinstalled, it will get installed into the overlay file system, which may not always have enough space on low flash memory devices.

**Comment by viniribeirossa** [comment]
I solved this problem like this

In CLI
`nextdns install`
`nextdns restart`
after reinstall .ipk the nextdns
