### ISSUE TITLE
Bullshit customer support

### ISSUE THREAD

**Issue by ETJAKEOC** [nextdns/nextdns#696]
**Context**
 - CLI Version: 1.37.11
 - Platform: OpenWRT

&lt;Describe the bug>

First things first, the fact that I have to create a second seperate account on your help website to get any assistance is absurd, I refuse to make a second fucking account just to get help. Secondly, and the ACTUAL issue, your program simply refuses to do its basic job. Ask it to read the hosts file and forward it to all other devices on the network, nope, go fuck myself, why would an option in a program ever do what it says it does? Simple, because programmers are a fucking joke and don't have any place on this fucking planet.

Fix your fucking program or I'm not renewing my subscription.

**Comment by rs** [comment]
Thanks for your kind perspective.
