### ISSUE TITLE
windows command line breaks NLA

### ISSUE THREAD

**Issue by ben71fl** [nextdns/nextdns#697]
Windows 10 - installing the CLI version with minimal parameters the computer will report its 'offline' after an hour or so until a reboot. While the device still works apps like Office365 / OneDrive will report 'no connection' and web pages wont auto-refresh etc. Installing the GUI app works fine (using TAP adapter it seems). Unfortunately we can't seem to do things like internal dns bypass and such with the gui app.

Windows 11 does not have this issue with the same config

 - CLI Version: 1.37
 - Platform: Windows x64

Device reports 'offline' and apps that use Network Location Awareness (365 / gsuite etc) all stop functioning.

**Comment by rs** [comment]
Please check the beta channel of the windows client.

**Comment by ben71fl** [comment]
We did that and had similar issue. I was able to sort out on Windows 10 by removing IPv6 in the registry, and then the install works. Cant just uncheck IPv6 I had to disable it with the regkey
