### ISSUE TITLE
UDMP SE (and other EA routers): install script working?

### ISSUE THREAD

**Issue by pcm1ke** [nextdns/nextdns#704]
Can nextdns please confirm that the current install script correctly installs nextdns on the UDMP SE (and would likely also do the same on other EA routers like the UDW)? Is there anything special that needs to be done or taken into account? Does it persist firmware upgrades or do you have to do something special?

Thank you

**Comment by rs** [comment]
UDM series including SE is supported.

**Comment by pcm1ke** [comment]
@rs any idea if that includes the EA udw? It debuted in the newer 2.X firmware (similar to SE). Can you give more insight as to what “supported” means? Does nextdns break on each firmware update and need special care or no?

**Comment by rs** [comment]
Supported means no special care (install and forget). 2.X firmware of the SE is supported but I can’t tell if EA works. Let us know if it does.

**Comment by pcm1ke** [comment]
@rs Sorry to bother you again.. is there a post or wiki or something somewhere that explains all the changes that NextDNS makes to a udm se when installed? The wiki is so scant on details and I'd really like to understand what is modified before I do this. I'm concerned that installing NextDNS will break the local dns functionality that I now enjoy; will it break? Thanks again

**Comment by rs** [comment]
Why don’t you test it? You can easily uninstall it if it doesn’t fulfill your requirements.
