### ISSUE TITLE
CLI client chooses distant DOH server

### ISSUE THREAD

**Issue by ely105** [nextdns/nextdns#705]
In my office location in Santa Clara, CA the CLI client is choosing Dallas as the Low Latency POP(40ms) instead of many more local and <10ms.  The algorithm seems to choose unwisely.  I saw a similar Issue posted to allow for setting the POP, but the author declines to do this.  How can we nudge the client to choose better?  For some reason it ignores the anycast servers but doesn't seem to know I am located in the Bay Area.  Maybe the IP is geolocated incorrectly.  Again, it would be helpful if the author would allow some form of override and/or manually setting geo location so that it can choose better.

Diagnostic here:
https://nextdns.io/diag/e30d3800-fe17-11ec-bf23-09ff0d59f5bd

Ping.nextdns.io results
<img width="296" alt="Screen Shot 2022-07-07 at 1 47 53 PM" src="https://user-images.githubusercontent.com/76797105/177868689-7d405025-bc6c-4d80-9603-bcc783d4395a.png">

**Comment by ely105** [comment]
@rs I am using nextDNS on the DOH client.  but for any system behind this public IP it resolves to DAL.  What am I missing?

**Comment by rs** [comment]
Are you using the CLI client at the location that steers you to DAL?

**Comment by ely105** [comment]
@rs yes, the client is at the location here in Santa Clara.  And any client that I run ping.nextdns on seems to find DAL closest. What is the method used to determine where to look for POPs?  It seems to me it thinks my pub ip is not in Silicon Valley.

**Comment by ely105** [comment]
@rs Is there a particular IP Database you use?  It seems like only 1 or 2 have mine listed in Louisiana.  Maybe I can work with them to correct.

**Comment by rs** [comment]
A mix of ip-api and maxmind.
