### ISSUE TITLE
REAL IP INSTEAD OF THE IPv4 ENDPOINT

### ISSUE THREAD

**Issue by dnses** [nextdns/nextdns#708]
**Context**
 - CLI Version: 1.37.11
 - Platform: MacOS Mojave 10.14.3 
 
when using a proxyclient that uses KEXT kernel extension, NextDnsCLI shows the real IP instead of the endpoints. Some times it shows the end points as shown in the first picture and then switches to the assigned IP address after subsequent queries as shown in the second picture but it's stable on windows when used with yoga dns client.
![20220710_021500](https://user-images.githubusercontent.com/106841996/178133677-17b33718-0b8c-4107-89d8-e8c736d56a09.jpg)
. Attached is a picture

**Comment by rs** [comment]
This is expected with ultralow. How is this an issue?

**Comment by rs** [comment]
Please explain what is your concern.

**Comment by dnses** [comment]
> Please explain what is your concern.

The problem is that: when using YogaDns (which supports DNSCrypt protocol) on WindowsOS, my network analytical tool shows the endpoints 45.90.28.0 or 45.90.30.0, but one at a time as it uses the fastest which is great but does not reveal the assigned TCP/IPs except when I check using browserleaks.com in the browsers and the assigned IP is consistent on there when I track the locations of my Proxies using the browsers on WindowsOS. The location of my proxy is Pennsylvania (PA) and the assigned IP 74.118.141.85 is also in PA and consistent which is very great.

On the contrary, On my MacBook, It shows the assigned IPs using the same analytical tool on MacOS instead of the endpoints. Also, it changes between 74.118.141.85 (a Pittsburgh IP) and 23.83.133.96 (Scottsdale,AZ IP) on my MacOS with NextDNS CLI. This is not normal. It's not supposed to show the assigned IPs in the tool except when checked on the browser like it does on Windows. Something is not right.

So, the question is this: can I make use of DNSCrypt or Unbound using my nextdns Account on MacOS? I'm asking because it wasn't recommended. And I can't make use of a configuration profile because I do not want to upgrade my MacOS to BigSur or Higher. I want to stick to MacOS Mojave 10.14.3 as most applications/software on MacOS are yet to be compatible with the higher versions.

**Comment by rs** [comment]
This is the normal behavior with ultralow, that is how it works and this should not be a concern. If it is, please explain how.

**Comment by dnses** [comment]
Okay, how do I disable ultralow? I want my assigned IP to be a constant not a variable.

**Comment by dnses** [comment]
So, the question is this: can I make use of DNSCrypt or Unbound using my nextdns Account on MacOS? Will I be able to disable Ultralow on those platforms?

**Comment by rs** [comment]
How the timezone of your DNS resolver could affect your anonymity?

**Comment by dnses** [comment]
Please, does nextdns support wireformat and JSON?

**Comment by rs** [comment]
Yes

**Comment by dnses** [comment]
Hi, please help. Is there a way I can prepend anycast and my profile ID to the QUIC endpoints?
