### ISSUE TITLE
Unable to install on Elementary OS 5.1

### ISSUE THREAD

**Issue by geocfu** [nextdns/nextdns#71]
ERROR: Unsupported OS: Linux
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
ERROR: Cannot detect running environement.

**Comment by agucova** [comment]
I have the same problem with ZorinOS, it seems that Ubuntu/Debian distros are not being recognized. 

Perhaps the installation script could have more permissive OS recognition or a force install flag for OS families (idk, -f ubuntu)

**Comment by agucova** [comment]
Checking the script, it's using /etc/os-release to identify the Linux distro, but ElementaryOS and ZorinOS are not mapped as Ubuntu. I've forced the install by manually setting `OS = ubuntu` in the bash script.

**Comment by agucova** [comment]
Following my (very probably not supported) journey to install NextDNS, I found this problem:

```
Err:1 https://dl.bintray.com/nextdns/deb stable/main amd64 nextdns amd64 1.4.25
403  Forbidden [IP: 13.35.112.91 443]

E: Failed to fetch https://d29vzk4ow07wi7.cloudfront.net/REDACTED?response-content-disposition=attachment;filename="nextdns_1.4.25_amd64.deb"&Policy=REDACTED&Signature=REDACTED&Key-Pair-Id=REDACTED  
403  Forbidden [IP: 13.35.112.91 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: install: exit 0
```

I'm guessing this has to do with bintray/cloudfront checking the User Agent before delivering the file, since at least Zorin OS changes this to authenticate with its servers.

Is there any chance that User-Agent verification could be disabled?

**Comment by rs** [comment]
Just tried to fetch a package with curl and got no issue. Do you have a way to reproduce this?

**Comment by geocfu** [comment]
From my side, i changed distro, so its a no from me. But propably @agucova can test this.
