### ISSUE TITLE
OPNsense: typing "nextdns log" returns "Error: exit status 2"

### ISSUE THREAD

**Issue by SampoHau** [nextdns/nextdns#724]
Not sure if opnSense is supposed to be supported or not, but it does seem to work apart from typing "nextdns log" command. It returns "Error: exit status 2", but the client keeps running.

 - CLI Version: 1.37.11
 - Platform: OPNsense 22.7.2 (FreeBSD 13.1-RELEASE-p1) (and all previous versions since I've used NextDNS CLI)

**Comment by bryanwieg** [comment]
the issue is that the location of the nextdns log is not in the expected place on opnsense. I don't have it in front of me, but you can still cat the log manually even though the nextdns bin cannot find it. You just have to find it.

**Comment by SampoHau** [comment]
Thanks for the idea @bryanwieg!

What I ended up doing is the following: # cat /var/log/system/latest.log | grep nextdns. This is a good enough workaround for occasional log viewing. I'm still leaving the issue open, though, since I think this should be fixed. :)
