### ISSUE TITLE
apple tv apple config profile doesn't work

### ISSUE THREAD

**Issue by ijuliank** [nextdns/nextdns#730]
https://help.nextdns.io/t/h7hnakp/the-apple-config-dns-profile-generator-doesnt-work

please have a look on this, it worked before with a apple.nextdns.io config

**Comment by ijuliank** [comment]
hi @rs may i ask why you closed it? is it fixed?

**Comment by rs** [comment]
This repository is about the CLI.

**Comment by ijuliank** [comment]
@rs wich can i place it in?

**Comment by rs** [comment]
help is the right place.

**Comment by ijuliank** [comment]
@rs ok thnks anyways, i hope someon can/will have a solution soon then,
it worked before
