### ISSUE TITLE
Enhanced log management

### ISSUE THREAD

**Issue by mbierman** [nextdns/nextdns#732]
Similar to https://github.com/nextdns/nextdns/issues/537, I have devices that sometimes (but not always?) fail to discover the DeviceID despite having the same mac address (Private mac address is disabled.) 

This makes the nextDNS logs fairly unusable. It would be amazing if a "clean up" feature was added so that:

1. Devices IDs (names) could be edited (renamed when the entire name doesn't come through properly) 
2. Merged when the same device appears more than once, the data could be merged into a single entity. This would allow users to manually fix when auto-discovery fails for whatever reason.

**Comment by rs** [comment]
This repository is about the CLI client. For feature requests on the NextDNS service, please use https://help.nextdns.io.

**Comment by mbierman** [comment]
No problem filing over there... but kind of disappointing that something from Sep is only being reviewed now.
