### ISSUE TITLE
Clone configurations

### ISSUE THREAD

**Issue by mbierman** [nextdns/nextdns#738]
It would be very helpful if it was easy to clone a configuration. 

**Use cases:** 
1. Testing. Be able to start with an exact copy and make changes without blowing anything up AND have a test environment before deploying changes.
2. Make a copy of a profile as a starting point for a different group of devices.

**Comment by kan3nas** [comment]
+1

**Comment by rs** [comment]
This repository is about the CLI client. For nextdns service feature request, please use https://help.nextdns.io.
