### ISSUE TITLE
Support for Clear Linux

### ISSUE THREAD

**Issue by chickenlol** [nextdns/nextdns#74]
Is it possible for Clear Linux (https://clearlinux.org/) to be supported by this client?

$ sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
ERROR: Unsupported OS: Linux
INFO: OS: 
INFO: GOARCH: amd64
INFO: GOOS: linux
ERROR: Cannot detect running environement.

**Comment by eeeple** [comment]
Considering the script relies on `uname -r` to detect the Linux flavor, and considering Clear Linux prints out `Linux`, it might not be that easy to support Clear Linux.

**Comment by msfjarvis** [comment]
This was fixed by https://github.com/nextdns/nextdns/pull/91 but this issue wasn't linked to it so this must be closed manually
