### ISSUE TITLE
/var/run/nextdns.sock not created on pfsense 22.05 (freebsd)

### ISSUE THREAD

**Issue by rcork** [nextdns/nextdns#743]
**Context**
 - CLI Version: 1.37.11
 - Platform: pfsense 22.05 FreeBSD 12.3-STABLE

I've installed nextdns CLI 1.37 on pfsense 22.05. With the default configuration it is set to create the nextdns.sock file in the /var/run directory. However, when listing the directory contents of /var/run, the file is not created. This leads to issues trying to run commands like cache-stats or cache-keys because the file does not exist. 

If i change my config to 
`control /tmp/nextdns.sock`
then the file is created successfully.  However there is still an issue with running cache-stats or cache-keys because it's still looking for the socket file in /var/run. (I'll create a separate issue for that).

**Comment by sectary-want-holly** [comment]
I cannot replicate this. 

```
grep 'control' /usr/local/etc/nextdns.conf
control /var/run/nextdns.sock
```

```
*** Welcome to Netgate pfSense Plus 22.05-RELEASE (amd64) on pfSense ***
# pwd
/var/run
# ls -lah *next*
-rw-------  1 root  wheel     5B Oct  8 18:22 nextdns.pid
srwxr-xr-x  1 root  wheel     0B Oct  8 18:05 nextdns.sock
```

`[22.05-RELEASE]: nextdns cache-stats
{
    "hit": 82198,
    "miss": 93093
}`

**Comment by rcork** [comment]
I'm not the only one. There are several posts over on the NextDNS Community site from other users having the same problem. 

https://help.nextdns.io/t/g9h7bws/nextdns-sock-not-created-by-cli-1-37-11-freebsd
https://help.nextdns.io/t/y4hgc1c/varrunnextdns-sock-connect-no-such-file-or-directory

**Comment by sectary-want-holly** [comment]
*shrug*

Can't replicate. Works fine.

**Comment by rcork** [comment]
Except it doesn't for some of us. Any way to turn on debug logging that would show why the socket file does not get created?

**Comment by sectary-want-holly** [comment]
Use DTrace. If dev can't replicate this, it's hard to fix...
