### ISSUE TITLE
cache-stats and cache-keys commands hardcoded to use /var/run/nextdns.sock

### ISSUE THREAD

**Issue by rcork** [nextdns/nextdns#744]
**Context**
 - CLI Version: 1.37.11
 - Platform: pfsense 22.05 FreeBSD 12.3-STABLE

&lt;Describe the bug>

I've modified my configuration file to specify that nextdns.sock should be created under /tmp directory. I have verified the file is created succesfully as /tmp/nextdns.sock.

When i attempt to run nextdns cache-stats or nextdns cache-keys, i get the following error

`Error: dial unix /var/run/nextdns.sock: connect: no such file or directory`

It appears that this path is hardcoded and not respecting the directory set in the configuration file.

**Comment by sectary-want-holly** [comment]
I think you have a stuck process...
