### ISSUE TITLE
Running `nextdns install` while the nextdns runit service is already installed overwrites existing directory

### ISSUE THREAD

**Issue by RunningDroid** [nextdns/nextdns#746]
**Context**
 - CLI Version: 1.39.4
 - Platform: Void Linux

&lt;Describe the bug>
If I enable and start the service `sudo ln -s /etc/sv/nextdns /var/service`, then `stat` the service dir:
```
$ stat /etc/sv/nextdns
  File: /etc/sv/nextdns
  Size: 4         	Blocks: 1          IO Block: 131072 directory
Device: 0,25	Inode: 262362      Links: 3
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-04-14 01:16:57.071433283 -0400
Modify: 2023-04-14 01:16:50.799395975 -0400
Change: 2023-04-14 01:16:50.799395975 -0400
 Birth: 2023-04-14 01:16:48.363381489 -0400
```
then run the install (which exits with an error)
```
$ sudo nextdns install -debug
NextDNS installed and started using runit init
Error: sv up nextdns: exit status 1:
```
and run `stat` again the dir has been rewritten:
```
$ stat /etc/sv/nextdns
  File: /etc/sv/nextdns
  Size: 4         	Blocks: 1          IO Block: 131072 directory
Device: 0,25	Inode: 268349      Links: 3
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-04-14 01:18:20.820931308 -0400
Modify: 2023-04-14 01:18:23.254945784 -0400
Change: 2023-04-14 01:18:23.254945784 -0400
 Birth: 2023-04-14 01:18:20.820931308 -0400
```
This can cause odd behavior from runit if the service is running, presumably because the files for managing the service are kept inside the dir providing the service.

Edit: I noticed it was the service dir being overwritten, not (just?) the symlink
Edit2: change the command from `nextdns config wizard` to `nextdns install` (which is probably run by `nextdns config wizard`), update version number, correct stat'd path to match the directory that's deleted then re-created.

**Comment by RunningDroid** [comment]
What's with the mass closing of issues as "not planned"? Is the repo getting archived?
![Screenshot 2023-09-09 at 23-30-28 nextdns_nextdns NextDNS CLI client (DoH Proxy)](https://github.com/nextdns/nextdns/assets/486393/db8799d0-e15f-4bd7-bc55-1d2b3d149378)

**Comment by rs** [comment]
Most of those issues are either old, edge cases, not reproducible or feature requests not planned. Instead of keeping them open in case more people repro or +1 (which led to many opened issues), I’ll let people reopen when necessary.
