### ISSUE TITLE
parental control section the pornography false positive

### ISSUE THREAD

**Issue by hulores** [nextdns/nextdns#748]
in the parental control section the pornography filter shows false errors for domain cb01.uno cb01.school cb1.online etc. i have try add to white list cb01.* but not allowed, could I know from which filter this domain is taken in order to report the false positive to the maintainer of the list? because I'm tired of adding all domains to the white list every day.

**Comment by hulores** [comment]
![image](https://user-images.githubusercontent.com/101432826/201536781-01e5f98d-aaa3-44cf-8a7e-7cc6eba08999.png)
This option break all site, another example is `transmissionbt.com`

**Comment by rs** [comment]
We are pushing change that should progressively fix those issues
