### ISSUE TITLE
Parental Controls Not Working for apps with Recreation Time:TikTok, Facebook, Snapchat, Instagram, Messenger

### ISSUE THREAD

**Issue by crougher** [nextdns/nextdns#749]
**Context**
 - CLI Version:  Im using iPhone Settings/ General VPN,DNS & DEvice Management / Restrictions and Proxies/ DNS
 - Platform: iphone12, iOS v. 16.1

&lt;Describe the bug>

I have enabled "Parental Control" with Recreation Time for my kid iphone and all of the blocked apps are not working as desire.
Howewver issue is that they are blocked also outside of Recreation Time:
- example: block time Mon- Fri from 7pm - 11:30pm
- I would expect to only see apps block during this time frame, however over weekends or dudring weekdays before 7pm apps are being blocked as well.

I did test: test.nextdns.io - and profile is activated.

I do not want to use denylist, as blocked apps should be only blocked during specific time.
Can you please advice?

//Jarek

**Comment by rs** [comment]
Please use https://help.nextdns.io to report product issues. This repository is about the CLI client.
