### ISSUE TITLE
OpenWRT install error: tar invalid magic, short read

### ISSUE THREAD

**Issue by OJFord** [nextdns/nextdns#75]
Fails to install:
```
# DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"
INFO: OS: openwrt
INFO: GOARCH: mips
INFO: GOOS: linux
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i):
INFO: Installing NextDNS...
DEBUG: Using bin install type
DEBUG: Installing  binary for linux/mips to /usr/bin/nextdns
tar: invalid magic
tar: short read
ERROR: install: exit 0
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i):
```

**Comment by rs** [comment]
What do you get for `df -h`?

**Comment by zefrs** [comment]
Seems i'm getting the same issue...

df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 3.0M      3.0M         0 100% /rom
tmpfs                    29.3M      1.4M     28.0M   5% /tmp
/dev/mtdblock8           11.6M      2.2M      9.5M  19% /overlay
overlayfs:/overlay       11.6M      2.2M      9.5M  19% /
tmpfs                   512.0K         0    512.0K   0% /dev

**Comment by rs** [comment]
That's probably too short on your overlay device to store the nextdns binary. Hopefully, Go (the language we are using) is currently working on improving produced binary size. There is good signs that we will be able to [reduce the binary size substantially](https://twitter.com/bradfitz/status/1256348714198654976) very soon.

**Comment by rs** [comment]
I'm going to close this for now.

**Comment by OJFord** [comment]
Uh, here you go. 😄
