### ISSUE TITLE
bogus-priv true returning SERVFAIL instead of NXDOMAIN causing pfSense DHCP leases page to hang

### ISSUE THREAD

**Issue by elarsson1** [nextdns/nextdns#750]
I have NextDNS CLI installed on my pfSense firewall, with Unbound resolver configured on an alternate port and discovery-dns and local forwarder configuration for my split-DNS domain pointing at that local Unbound instance. 

When activating NextDNS for answering local queries from pfSense itself, I noticed that the DHCP Leases page in the admin interface was hanging. I ultimately determined that this was being caused by retries on reverse DNS lookups of local IPs that were failing with a SERVFAIL response. If bogus-priv is set to false, then those reverse lookups that are not answered by local Unbound are forwarded up to NextDNS upstream but they now return an NXDOMAIN response as expected. 

The only other changes I've made from defaults that may be somewhat unique is that I've disabled mdns support as NextDNS's mdns client conflicts with the local Avahi instance I use for mdns reflection between subnets. I've also disabled use-hosts as that was returning duplicate A record responses when local unbound and hosts file both contain an entry (pfSense puts all local host overrides both in the /etc/hosts file and in the local Unbound config as local-data entries). use-hosts was also not allowing AAAA queries for entries in /etc/hosts to fall through to DNS upstream or local Unbound via the forwarder entry. (I have unbound set up with "typetransparent" zone type to enable exactly this behavior).

**NextDNS version: 1.37.11**

Redacted config:

```
hardened-privacy false
bogus-priv false
use-hosts false
max-inflight-requests 256
setup-router false
forwarder redacted-domain.com.=127.0.0.1:5555
log-queries false
discovery-dns 127.0.0.1:5555
mdns disabled
control /var/run/nextdns.sock
config 10.70.6.0/23=GUEST-CONFIG-ID
config MAIN-CONFIG-ID
max-ttl 5s
report-client-info true
timeout 5s
auto-activate true
listen 0.0.0.0:53
cache-size 10MB
cache-max-age 0s
detect-captive-portals false
```

Demonstrating the issue:

With bogus-priv set to false:

```
: dig @127.0.0.1 -x 10.10.10.10

; <<>> DiG 9.16.26 <<>> @127.0.0.1 -x 10.10.10.10
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 36858
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;10.10.10.10.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
10.in-addr.arpa.	5	IN	SOA	prisoner.iana.org. hostmaster.root-servers.org. 1 604800 60 604800 604800

;; Query time: 5 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Oct 30 18:09:54 EDT 2022
;; MSG SIZE  rcvd: 130
```

bogus-priv set to true

```
: dig @127.0.0.1 -x 10.10.10.10

; <<>> DiG 9.16.26 <<>> @127.0.0.1 -x 10.10.10.10
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 44584
;; flags: qr; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Oct 30 18:10:50 EDT 2022
;; MSG SIZE  rcvd: 12
```

**Comment by rcork** [comment]
I just ran into this issue on my pfsense instance and unfortunately, losing access to the DHCP leases page is a non-starter for me. I've cancelled my NextDNS membership and will wait to see if this issue is fixed.

**Comment by brainsik** [comment]
Unfortunately, this hasn't fixed the issue I'm seeing with `getaddrinfo()` hanging on pfSense when `bogus-priv true` is set.

@elarsson1 Did this patch (v1.38.0) fix things for you?

## bogus-priv true

`getaddrinfo()` hangs for 15s:

```
$ /usr/bin/time python3.8 -c 'import socket; socket.gethostbyaddr("10.19.47.50")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.herror: [Errno 2] Host name lookup failure
       15.18 real         0.14 user         0.01 sys
```

```
$ dig -x 10.19.47.50

; <<>> DiG 9.16.26 <<>> -x 10.19.47.50
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50706
;; flags: qr; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jan 05 16:28:57 PST 2023
;; MSG SIZE  rcvd: 12
```

## bogus-priv false

`getaddrinfo()` quickly fails:

```
$ /usr/bin/time python3.8 -c 'import socket; socket.gethostbyaddr("10.19.47.50")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.herror: [Errno 1] Unknown host
        0.16 real         0.11 user         0.04 sys
```

```
$ dig -x 10.19.47.50

; <<>> DiG 9.16.26 <<>> -x 10.19.47.50
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 47985
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;50.47.19.10.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
10.in-addr.arpa.	5	IN	SOA	prisoner.iana.org. hostmaster.root-servers.org. 1 604800 60 604800 604800

;; Query time: 15 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jan 05 16:30:40 PST 2023
;; MSG SIZE  rcvd: 130
```

**Comment by elarsson1** [comment]
I am continuing to see the same timeout behavior on the latest release of nextdns cli

**Comment by brainsik** [comment]
@rs Can we re-open this or would you prefer I make a new issue with a different title?
