### ISSUE TITLE
 NO_PUBKEY 467A7CCC8ACFA0B7

### ISSUE THREAD

**Issue by janthony6** [nextdns/nextdns#755]
**Context**
 - CLI Version:  1.38.0
 - Platform: UDMSE

When trying to upgrade I get this error:
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 467A7CCC8ACFA0B7

**Comment by rs** [comment]
@vincentbernat ^

**Comment by janthony6** [comment]
okay I fixed it. same issue it's been having where nextdns.gpg is missing from usr/share/keyrings. I replaced it and it upgraded fine. on reboot or upgrade the file doesn't persist.

**Comment by vincentbernat** [comment]
@janthony6 would you be able to test the install script again? Use the "install" action to ensure the updated sources.list is installed. Reboot and try to upgrade. The error should not be here (my hope is that moving the file to `/etc` instead of `/usr/share` will make it persistent)

**Comment by janthony6** [comment]
yes - what is the command to run that?
