### ISSUE TITLE
Asuswrt-Merlin: support /etc/hosts.dnsmasq

### ISSUE THREAD

**Issue by pro-sumer** [nextdns/nextdns#76]
On Asuswrt-Merlin you seem to support `/etc/hosts` to resolve local domain names :)

Example of line in `/etc/hosts`:

    192.168.1.1 router

Please support `/etc/hosts.dnsmasq` as well.

Example of line in `/etc/hosts.dnsmasq`:

    192.168.1.100 mac

**Comment by rs** [comment]
Fixed by 06c9adb1760d6632838ae992e65f6c0dadfb14e1
