### ISSUE TITLE
Cannot install NextDNS on Asus Merlin

### ISSUE THREAD

**Issue by melboone** [nextdns/nextdns#760]
Hi All,

I'm running Asus Merlin, Firmware version 3.0.0.4.388_21099, and when I try to install NextDNS with `sh -c "$(curl -sL https://nextdns.io/install)"` it fails.

```
administrator@ZenWiFi_XT8-4930:/tmp/home/root# sh -c "$(curl -sL https://nextdns.io/install)"
sh: xargs: not found
ERROR: Unsupported OS:
ERROR: Unknown bin location for
INFO: OS:
INFO: GOARCH: armv7
INFO: GOOS: linux
INFO: NEXTDNS_BIN:
INFO: INSTALL_RELEASE: 1.38.0
ERROR: Cannot detect running environment.
```

**Comment by vincentbernat** [comment]
Can you copy/paste the result of `cat /etc/os-release`?

**Comment by damian123** [comment]
I have a similar problem:

XXXX@RT-AX92U-2CE0:/tmp/home/root# DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"
sh: xargs: not found
ERROR: Unsupported OS:  
ERROR: Unknown bin location for 
INFO: OS: 
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: 
INFO: INSTALL_RELEASE: 1.39.4
ERROR: Cannot detect running environment.

@rs @vincentbernat
