### ISSUE TITLE
TP-Link

### ISSUE THREAD

**Issue by DjDany** [nextdns/nextdns#764]
Hi
i cant use for tp-link ax73,why,you can help me ?

**Comment by KenKilty** [comment]
@DjDany  from the documentation for that device it appears you need to set a static IP to input custom DNS entries to use the public IP's for NextDNS listed below in the my.nextdns.com portal. I don't see any means to run a DoH proxy on this router. I used to have a tp-link router before I moved to Eero. Eero doesn't support DoH proxy either, most consumer routers won't let you run executables.

![image](https://user-images.githubusercontent.com/7634904/215161455-c5b50f50-9284-42d7-821d-3a0d59f6f28e.png)
