### ISSUE TITLE
nextdns-v1.38.0 false-positive for antivirus clients

### ISSUE THREAD

**Issue by patschi** [nextdns/nextdns#767]
**Context**
 - CLI Version: nextdns-v1.38.0
 - Platform: windows amd64

**Describe the bug:**

I'm running still a quite old nextdns-v1.5.x release so I decided to update to the latest one, however my antivirus solution Carbon Black is detecting it as malware:

![image](https://user-images.githubusercontent.com/2029878/204891020-d3dd8f48-0722-4bea-a457-b12584f782d3.png)

Also virustotal is showing several suspected hits:
https://www.virustotal.com/gui/file/74d8dedfdec716081f667d6994e09661a87b6bc124fe109a5af6c5

**Comment by rs** [comment]
It is probably because the binary is not signed.

**Comment by patschi** [comment]
No, that's not relevant to be classified as malware and its hash being listed as suspicious. Also the old binary is unsigned and been working fine for more than 2 years now.

**Comment by rs** [comment]
We had this problem regularly. It goes away as people mark it as false positive. It is unclear what triggers their algorithm.
