### ISSUE TITLE
Asuswrt-Merlin: NextDNS does not start after router reboot

### ISSUE THREAD

**Issue by pro-sumer** [nextdns/nextdns#77]
On Asuswrt-Merlin NextDNS does not start after a reboot, because the router does not have the correct system time yet, and thus your certificates are not valid "yet". The NTP server I use requires me to use a domain name instead of an IP address, but since NextDNS does not run, I cannot access this server... So I end up in a Catch-22 :(

How can I get out of this, while still using NextDNS and that particular NTP server?

**Comment by rs** [comment]
What version do you run. The last version should wait for time to be set by ntp before setting up the router to go thru it.

**Comment by pro-sumer** [comment]
- ASUSWRT-Merlin RT-AC86U 384.15_alpha2-g42112679cc Mon Jan 27 03:50:13 UTC 2020
- nextdns version 1.4.25

**Comment by dave14305** [comment]
The issue may have been that the automatic WAN DNS via DHCP is disabled during nextdns startup. This user had no manual WAN DNS servers setup so the router had no valid DNS servers to resolve the ntp server name. So ntp won’t be synced.

The Merlin GUI won’t let you disable automatic WAN DNS, but that’s what nextdns does via nvram commands. Normally it should revert the changes if stopped gracefully, but it can lead to problems if the nvram changes aren’t properly reverted.

**Comment by dave14305** [comment]
Do you need to stop nextdns via the /jffs/scripts/services-stop so that it shuts down gracefully on a router reboot?

**Comment by rs** [comment]
Not necessarily, the process will restore settings on exit. It is true that this won’t happen if the router lose poser for instance. We should probably for some nvram settings at startup while waiting for ntp.

**Comment by dave14305** [comment]
Perhaps you should not be disabling wan_dnsenable_x during launch. It merely switches from WAN DHCP DNS to manual WAN DHCP DNS. It doesn't disable external DNS for dnsmasq. It just switches between ISP DHCP servers and manual servers. You really want to remove the servers-file= line from /etc/dnsmasq.conf via /jffs/dnsmasq.postconf so all that remains is the server parameter to point to 127.0.0.1:5342. Easier to do what you want with dnsmasq.postconf than with dnsmasq.conf.add.

**Comment by rs** [comment]
You have a good point.

**Comment by dave14305** [comment]
This is how I would write a dnsmasq.postconf to modify dnsmasq.conf for NextDNS, but only if it is running, so dnsmasq can work normally if NextDNS fails to start. But you have assume there is already content in the dnsmasq.postconf script (e.g. Diversion commands). The pc_delete and pc_append are just alias to sed commands from helper.sh.
```
#!/bin/sh

CONFIG="$1"
. /usr/sbin/helper.sh

if [ -f /tmp/nextdns.pid ] && [ -d "/proc/$(sed -n '1p' /tmp/nextdns.pid)" ]; then
	pc_delete "servers-file" "$CONFIG"				# disconnect dnsmasq from WAN DNS settings
	pc_append "server=127.0.0.1#5342" "$CONFIG"		# point dnsmasq to NextDNS listener IP:port
	pc_delete "stop-dns-rebind" "$CONFIG"			# disable dns rebind if enabled
	pc_delete "trust-anchor=" "$CONFIG"				# disable DNSSEC
	pc_delete "dnssec" "$CONFIG"					# disable DNSSEC
fi
```

**Comment by rs** [comment]
appending the `server` is not enough, we need to make sure we are the only server. I'm also not sure how to deal with existing .postconf or .add. Most likely, existing content won't be compatible with nextdns.

**Comment by dave14305** [comment]
Removing any servers-file= or resolv-file= lines from dnsmasq.conf would be enough to ensure nextdns is the only upstream for dnsmasq. In my opinion, it’s cleaner than modifying resolv.dnsmasq on-the-fly since that can be undone by the firmware if someone restarts dnsmasq manually or through a GUI change on the router. dnsmasq.postconf will run every time dnsmasq is started, so you can be sure dnsmasq points only to your listener.

It’s just a suggestion since the Merlin platform is so extensible with the custom scripts and configuration options. The Merlin community has a lot of experience integrating dnsmasq with other upstreams on the router (e.g. Stubby, Unbound, dnscrypt-proxy).

**Comment by lunim** [comment]
@rs I'm seeing this issue with the latest version 1.5.  I haven't made any configuration changes to NTP or WAN DNS, I'm running a pretty close to default Merlin installation.

**Comment by rs** [comment]
Do you see something in the logs?

**Comment by lunim** [comment]
I've cleared the logs since then, but the issue was as described in the ticket.  The system date was May 2018 and the router server failed due to certificate validation error.  When I manually SSHed in and started the service it was fine.

**Comment by rs** [comment]
Can you please try to remove the `unset TZ` line from the `/jffs/nextdns/nextdns.init` and restart to see if it fixes it?

**Comment by lunim** [comment]
Okay, it looks like it was successful this time, I see a few messages with the old date, but it seems to have updated shortly after:

```
May  5 05:05:23 nextdns[1745]: Endpoint provider failed: https://router.nextdns.                                                                                                                           io?stack=dual: Get "https://216.239.32.21:443?stack=dual": x509: certificate has                                                                                                                            expired or is not yet valid: current time 2018-05-05T05:05:22Z is before 2020-0                                                                                                                           3-13T01:20:19Z
May  5 05:05:23 nextdns[1745]: Endpoint failed: https://dns1.nextdns.io#45.90.28                                                                                                                           .0,2a07:a8c0::: roundtrip: x509: certificate has expired or is not yet valid: cu                                                                                                                           rrent time 2018-05-05T05:05:23Z is before 2020-04-05T00:28:16Z
May  5 05:05:23 nextdns[1745]: Endpoint failed: https://dns2.nextdns.io#45.90.30                                                                                                                           .0,2a07:a8c1::: roundtrip: x509: certificate has expired or is not yet valid: cu                                                                                                                           rrent time 2018-05-05T05:05:23Z is before 2020-04-05T00:28:16Z
May  5 05:05:23 nextdns[1745]: Switching endpoint: 45.90.28.0:53
Apr 10 22:37:46 nextdns[1745]: Connected 66.42.72.30:443 (con=5ms tls=40ms, TLS1                                                                                                                           3)
Apr 10 22:37:46 nextdns[1745]: Switching endpoint: https://vultr-sea-1.edge.next                                                                                                                           dns.io#66.42.72.30,2001:19f0:8001:1b16:5400:2ff:fe99:8d17
```

**Comment by rs** [comment]
Can you confirm it worked because you removed the `unset TZ`?

**Comment by lunim** [comment]
I re-added the unset TZ and rebooted, it successfully started with roughly the same log.  I'm not sure why it failed the previous time.  I guess I can comment again if I see it happen.

```
May  4 22:05:22 nextdns[1746]: Endpoint provider failed: https://router.nextdns.io?stack=dual: Get "https://216.239.32.21:443?stack=dual": x509: certificate has expired or is not yet valid: current time 2018-05-04T22:05:21-07:00 is before 2020-03-13T01:20:19Z
May  4 22:05:22 nextdns[1746]: Endpoint failed: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::: roundtrip: x509: certificate has expired or is not yet valid: current time 2018-05-04T22:05:22-07:00 is before 2020-04-05T00:28:16Z
May  4 22:05:22 nextdns[1746]: Endpoint failed: https://dns2.nextdns.io#45.90.30.0,2a07:a8c1::: roundtrip: x509: certificate has expired or is not yet valid: current time 2018-05-04T22:05:22-07:00 is before 2020-04-05T00:28:16Z
May  4 22:05:22 nextdns[1746]: Switching endpoint: 45.90.28.0:53
May  4 22:05:22 custom_script: Running /jffs/scripts/service-event (args: start ntpd)
May  4 22:05:22 ntpd: Started ntpd
Apr 10 16:06:14 ntpd: Initial clock set
Apr 10 16:06:14 miniupnpd[2135]: HTTP listening on port 52153
Apr 10 16:06:14 miniupnpd[2135]: Listening for NAT-PMP/PCP traffic on port 5351
Apr 10 16:06:14 rc_service: ntpd_synced 2118:notify_rc restart_diskmon
Apr 10 16:06:14 custom_script: Running /jffs/scripts/service-event (args: restart diskmon)
Apr 10 16:06:14 disk_monitor: Finish
Apr 10 16:06:14 kernel: Archer TCP Pure ACK Enabled
Apr 10 16:06:14 disk_monitor: be idle
Apr 10 16:06:14 dhcp_client: bound .../255.255.240.0 via ... for 1800 seconds.
Apr 10 16:06:16 WAN_Connection: WAN was restored.
Apr 10 16:06:18 nextdns[1746]: Connected 66.42.72.30:443 (con=6ms tls=40ms, TLS13)
Apr 10 16:06:18 nextdns[1746]: Switching endpoint: https://vultr-sea-1.edge.nextdns.io#66.42.72.30,2001:19f0:8001:1b16:5400:2ff:fe99:8d17
```
