### ISSUE TITLE
[docs bug] pfSense wiki link is misleading, should match the website

### ISSUE THREAD

**Issue by carterkozak** [nextdns/nextdns#773]
**Context**
The `pfSense` link on [the wiki](https://github.com/nextdns/nextdns/wiki) points to the [installer](https://github.com/nextdns/nextdns/wiki/Installer) documentation. Unfortunately the installer doesn't succeed out of the box due to port collisions with the default DNS resolver, once resolved prevents the dhcp leases page from loading (which is likely reasonable enough, but worth documenting).

The website documentation describes how to add options to the default Unbound DNS resolver in a way that works easily out of the box. This should probably be suggested by default in the wiki as well, until the installer executes successfully (or additional docs are provided describing workarounds).

I would propose making the following change to match the `my.nextdns.io` router documentation:
https://gist.github.com/carterkozak/639be7598a7ac9a3bd94479ec3b96995

**Comment by rs** [comment]
Done, thx
