### ISSUE TITLE
UniFi OS - Dream Machines 2.4.23 supported?

### ISSUE THREAD

**Issue by bondskin** [nextdns/nextdns#774]
Hi,

does the Unifi OS installation also works on UniFi OS - Dream Machines 2.4.x on an UnifiOS (UDM) device?

thx
Mike

**Comment by mad-it** [comment]
From what I remember, UDM-SE is supported which runs 2.x. So in theory it should work however I did not try it out yet on my UDM-B.

**Comment by cpressland** [comment]
Just my 2¢ that everything has been working fine since upgrading my UDMP to 2.4.23. Obviously I had to reinstall post upgrade, but nothing else to report.

**Comment by timrettop** [comment]
After upgrading to 2.4.23 on my UDM Base, I reinstalled the script and the installation seemed fine, however after rebooting my UDM, nextdns service doesn't seem to start or start correctly. 
Running nextdns restart on CLI first time reports: 
```Error: systemctl restart nextdns.service: signal: killed:```
Then nextdns restart a second time it completes successfully and my.nextdns.io reports green working.

**Comment by timrettop** [comment]
I suspect this line in /etc/systemd/system/nextdns.service 
```After=unifi.service 
Before=nss-lookup.target
Wants=nss-lookup.target```

There isn't a unifi service or nss-lookup target as far as I can tell.  I replaced unifi.service with udm-boot.service (probably could be something else standard) and commented out the Before and Wants lines, and reboot now works as does nextdns restart

**Comment by rs** [comment]
The `nss-lookup.target` is a systemd synchronisation target, it will exist on all systems.

For `unifi.service` I'm surprised. What do you get for `systemctl status unifi.service`?

**Comment by jfroy** [comment]
I just did the upgrade and `unifi.service` is running and active. `nss-lookup.target` exists but is inactive.

```
● nss-lookup.target - Host and Network Name Lookups
   Loaded: loaded (/lib/systemd/system/nss-lookup.target; static; vendor preset: enabled)
   Active: inactive (dead)
```

**Comment by mojo333** [comment]
> `nss-lookup.target` exists but is inactive.

Just had a quick look at nsslookup.target state on my UDMPro v2.4.23 - this is what I see:

```
root@UDMP:~# systemctl status nss-lookup.target
● nss-lookup.target - Host and Network Name Lookups
   Loaded: loaded (/lib/systemd/system/nss-lookup.target; static; vendor preset: enabled)
   Active: active since Thu 2022-12-15 17:21:15 GMT; 15h ago
     Docs: man:systemd.special(7)

Dec 15 17:21:15 UDMP systemd[1]: Reached target Host and Network Name Lookups.
```

Saying that, I still have the issue that NextDNS doesn't start on reboot.

**Comment by sra** [comment]
I've updated to this version of UnifiOS on a UDP Pro and Network 7.3.76 and while the install seems to work, the status never indicates DNS is routed through NextDNS anymore.

**Comment by jinkang23** [comment]
Updated UDMP to 2.4.23 and nextdns CLI installed fine.. and appears to be working.. however, `nextdns log` command fails..

```sh
root@udmp:/# nextdns status
running
root@udmp:/# nextdns log
Error: exit status 1
```

**Comment by mojo333** [comment]
> Saying that, I still have the issue that NextDNS doesn't start on reboot.

Quoting my own response, it looks like NextDNS does start on boot - it just takes several minutes. I did a reboot and then got distracted by something else and when I came back ~5 minutes later NextDNS was up and running.

Maybe `After=unifi.service` needs to be another service which starts more quickly?

**Comment by rs** [comment]
It has to be after unifi as this service is installing iptables rules and would overwrite nextdns’.

**Comment by timrettop** [comment]
> > Saying that, I still have the issue that NextDNS doesn't start on reboot.
> 
> Quoting my own response, it looks like NextDNS does start on boot - it just takes several minutes. I did a reboot and then got distracted by something else and when I came back ~5 minutes later NextDNS was up and running.
> 
> Maybe `After=unifi.service` needs to be another service which starts more quickly?

I noticed the same.  It took about 5 minutes for the unifi service to be active, but nextdns was running afterwards successfully.

**Comment by timrettop** [comment]
> Updated UDMP to 2.4.23 and nextdns CLI installed fine.. and appears to be working.. however, `nextdns log` command fails..
> 
> ```shell
> root@udmp:/# nextdns status
> running
> root@udmp:/# nextdns log
> Error: exit status 1
> ```

```nextdns log``` worked for me after waiting a few minutes after boot and checking the nextdns status.

**Comment by timrettop** [comment]
> Seeing strange behavior on version 2.4.27 (released yesterday).
> 
> ```
> root@UDM-Pro:~# nextdns status
> not installed
> root@UDM-Pro:~# nextdns status
> running
> ```

I get the same thing during boot (status reports not installed) until the service starts (for me it seems to be about 2 minutes after boot).  Seems like its not properly reporting its status.
