### ISSUE TITLE
UniFi OS - use dnsmasq for non-containarized version

### ISSUE THREAD

**Issue by sanyer** [nextdns/nextdns#776]
According to this https://github.com/nextdns/nextdns/issues/556#issuecomment-986196304, it is possible to use nextdns on ubios without iptables and with dnsmasq. I tried config in this config and only problem was the fact that nextdns wasn't discovering any devices names, instead they were all sent to my.nextdns.io as `Device #MAC`

This will send device's request through the nextdns, removing the previous limitation.

**Comment by rs** [comment]
Chaining two dns proxies this way is inefficient and hides information the cli need for device identification.

**Comment by sanyer** [comment]
So, ubiquiti has different approach to how dnsmasq is used?
AFAIK, dnsmasq is the method used for every other nextdns implementation.

**Comment by rs** [comment]
dnsmasq is disabled on other routers when nextdns is running. We are contemplating using the iptables in most cases instead so we don't mess with the router's configuration. What is the issue with iptables?

**Comment by sanyer** [comment]
No no, no issues. Just curiosity. I just wanted to check again on the limitation of UnifiOS not sending own requests through nextdns client.

**Comment by rs** [comment]
@sanyer are you planning to sending an updated PR for this?

**Comment by sanyer** [comment]
Hey @rs ,
What do you mean by "updated"?
As far as I remember I didn't send any PRs for this.
I can look into it, though. 

Wouldn't it be possible to put back that iptables code?
