### ISSUE TITLE
void linux: parse /etc/nextdns.conf by default

### ISSUE THREAD

**Issue by sbromberger** [nextdns/nextdns#778]
Currently configurations are stored in `/etc/nextdns.conf` but this file is not parsed by default during `nextdns run` without an explicit `-config-file` flag. The runit service that gets installed does not pass this flag, so nextdns always starts with the default settings which may not be what the user wants.

Could nextdns be configured so that `/etc/nextdns.conf` is a last-resort check for configurations?

**Comment by rs** [comment]
What do you get for `/etc/sv/nextdns/run`?

**Comment by sbromberger** [comment]
sorry for the delay - I've been out of country.

`/etc/sv/nextdns/run` has
```
#!/bin/sh
exec /usr/bin/nextdns run
```
