### ISSUE TITLE
EdgeOS Nextdns CLI stop working

### ISSUE THREAD

**Issue by jakafahrial** [nextdns/nextdns#780]
![SCR-20230110-s2i](https://user-images.githubusercontent.com/45447531/211567760-c709957b-6af7-48d4-860e-5312cfe66ac3.png)
**Context**
 - CLI Version: 1.38.0
 - Platform: edgeos

I just realised last night, "nextdns cli" stopped working as it route to anycast DNS. 
- I managed to stop and restart -> no luck
- Refresh (remove and add profile) -> no luck
- Directly add customised nextdns over Chrome browser -> ok, works 

A few event on attached screenshot.

QQ: 
1. Is there any config changes on nextdns or service down that we dont know?
2. From the log event, is that normal behaviour? couple times connected to the same address for less than 10minutes
3. diag result: https://nextdns.io/diag/a5150a80-90ea-11ed-91f8-e5aeb9f0fab3

**Comment by rs** [comment]
Can you please:
1. Upgrade to the last version of the CLI
2. Execute `nextdns config set -debug=true`
3. Restart the service with `nextdns restart`
4. Perform a few queries
5. Post the logs

**Comment by jakafahrial** [comment]
Hi @rs - thanks for the responses

The log:
![image](https://user-images.githubusercontent.com/45447531/215252157-ebf4df54-7334-4c82-a705-e7dcbdd1e88a.png)

Diag result: https://nextdns.io/diag/5226d850-9eda-11ed-9922-2f3a2506ed4b

**Comment by rs** [comment]
It doesn’t seem like you enabled debug mode. What do you get for `nextdns config`
