### ISSUE TITLE
NextDNS CLI 1.39.0 Ignores -Listen parameter on install

### ISSUE THREAD

**Issue by Raymoz101** [nextdns/nextdns#788]
Was doing a reboot of my Firewalla Gold and had to reinstall NextDNS.
Noticed no devices were using NextDNS.

Troubleshooting eventually pointed to NextDNS ignoring my install parameters and instead listening on "localhost:53"

Install script is as follows (Source: https://help.firewalla.com/hc/en-us/community/posts/7469669689619-NextDNS-CLI-on-Firewalla-revisited-working-DHCP-host-resolution-in-NextDNS-logs-):
```
sudo wget -qO /usr/share/keyrings/nextdns.gpg https://repo.nextdns.io/nextdns.gpg
echo "deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main" | sudo tee /etc/apt/sources.list.d/nextdns.list
sudo apt update
sudo apt install nextdns

sudo nextdns install -config 10.0.101.1/24=XXXXX -config 10.0.102.1/24=XXXXX -config 10.0.100.1/24=XXXXX -config XXXXXX -report-client-info -cache-size=10MB -max-ttl=5s -discovery-dns 10.99.0.1 -listen 10.99.0.1:5555

# Add dnsmasq integration to enable client reporting in NextDNS logs: https://github.com/nextdns/nextdns/wiki/DNSMasq-Integration
cat > /home/pi/.firewalla/config/dnsmasq/mynextdns.conf << EOF
server=10.99.0.1#5555
add-mac
add-subnet=32,128
EOF
```
Output = "NextDNS installed and started using systemd init"
However, "nextdns config" command shows:
```
pi@Firewalla:~/.firewalla/config/post_main.d (Firewalla) $ nextdns config
control /var/run/nextdns.sock
report-client-info false
discovery-dns
mdns all
setup-router false
auto-activate true
max-inflight-requests 256
listen localhost:53
cache-size 0
max-ttl 0s
bogus-priv true
use-hosts true
timeout 5s
cache-max-age 0s
detect-captive-portals false
log-queries false
hardened-privacy false
```

and 
"sudo netstat -tulpn | grep LISTEN" command shows:
```
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      198373/nextdns
```

NOTE: You can see it is also ignoring other parameters such as "Report client info"

Any advice to test or resolve this issue would be hugely appreciated! Have spent hours this morning testing to confirm, this is the cause.
If there is a better way to configure the listen ports, let me know! :)

**Comment by rs** [comment]
Please upgrade to 1.39.1 and confirm it is fixed.

**Comment by Raymoz101** [comment]
> Please upgrade to 1.39.1 and confirm it is fixed.

Perfection!!
Thank you for such a quick response. 

Love the verbose confirmation on install now, then I confirmed all the profiles and arguments are listed correctly with "NextDNS config" command. 

Back up and running!
