### ISSUE TITLE
v 1.39.1 stopped capturing ads

### ISSUE THREAD

**Issue by thob** [nextdns/nextdns#790]
this is what I get on the CLI
![image](https://user-images.githubusercontent.com/755337/214886414-89d8133c-3ccb-42f7-b579-d30cc09da9ab.png)

and (some) ads aren't captured anymore, it seems

**Comment by rs** [comment]
What OS is it running on?
How did you upgrade?
What do you get for `cat /etc/nextdns.conf`?

**Comment by cirrusflyer** [comment]
I'm seeing this exact behavior.

**Comment by cirrusflyer** [comment]
completely broken and lost my config.  I have a backup, but may not be current.

**Comment by thob** [comment]
> What OS is it running on?
> How did you upgrade?
> What do you get for `cat /etc/nextdns.conf`?

I used nextdns upgrade, I’m on PopOS latest. Seems there’s a new version out.

**Comment by rs** [comment]
Found the issue, it will be fixed in 1.39.4. Please give it a few hours to make sure all it is fully tested before upgrading.

**Comment by thob** [comment]
getting 
`Failed to fetch https://repo.nextdns.io/deb/dists/stable/main/binary-amd64/Packages.gz `
when trying to upgrade

**Comment by thob** [comment]
worked now. thanks

**Comment by thob** [comment]
I think during all this hassle something got lost. nextdns is running but it doesn't capture anything. For config I get

debug false
control /var/run/nextdns.sock
discovery-dns 
max-inflight-requests 256
listen localhost:53
log-queries false
max-ttl 0s
bogus-priv true
report-client-info false
mdns all
detect-captive-portals false
use-hosts true
cache-size 0
cache-max-age 0s
hardened-privacy false
timeout 5s
setup-router false
auto-activate true

**Comment by rs** [comment]
Your config is missing a profile. Use `nextdns config set -profile=xxxxx` or run the wizard again with `nextdns config wizard`

**Comment by thob** [comment]
Hmm, it's picking up stuff again, thanks! But the log tells me that the device name is picked up but it doesn't show in the GUI log

**Comment by thob** [comment]
OK, got it working. It seems I lost a few settings (like -report-client-info). Maybe I should run the wizard.

**Comment by thob** [comment]
And now I got an entry for

config xxxxx
profile XXXX

Do I need both?

**Comment by rs** [comment]
How did you edit the file? Only profile should remain.

**Comment by thob** [comment]
First I added it via CLI directly, and then I ran the wizard…

**Comment by rs** [comment]
What do you get for `nextdns version`?

**Comment by thob** [comment]
1.39.4
