### ISSUE TITLE
Some Index files failed to download 1.39.4

### ISSUE THREAD

**Issue by janthony6** [nextdns/nextdns#792]
Latest release on UDM

<img width="977" alt="image" src="https://user-images.githubusercontent.com/41707668/214925783-c5c065ff-dd8f-404a-97f7-ee0cc35b5acf.png">

**Comment by owine** [comment]
Perhaps the release workflow would benefit from an action to purge Cloudflare cache.

**Comment by rs** [comment]
Please try again, it should work.

**Comment by janthony6** [comment]
Just tried and it happened again on a UDM-SE

**Comment by rs** [comment]
Tested on UDM-SE with 1.39.4 and it does not longer wipe the configuration. Are you sure you tried this version?

**Comment by SherlockHomie** [comment]
Just updated and these errors are now gone, thanks!

![Screenshot from 2023-01-26 10-09-45](https://user-images.githubusercontent.com/4062922/214939694-a7bfa370-6df3-4b94-8a4d-7125645deec0.png)
e!
![Screenshot from 2023-01-26 10-09-30](https://user-images.githubusercontent.com/4062922/214939698-02d16b60-4509-4d81-baa7-991211312c3e.png)
![Screenshot from 2023-01-26 10-09-02](https://user-images.githubusercontent.com/4062922/214939700-375acddf-c546-4b3b-b141-fb24ac910578.png)

**Comment by janthony6** [comment]
Tried upgrade again and it failed with errors again. I’ll try what I did last time, uninstall and reinstall and see if that works. It just takes forever too. When you select I for install it says INFO: Installing NextDNS and hangs forever.
