### ISSUE TITLE
no tracker capturing again after recent hassle w/ 1.39.

### ISSUE THREAD

**Issue by thob** [nextdns/nextdns#796]
[I'm sure if I can reopen a close bug report hence I link to it: #790
](https://github.com/nextdns/nextdns/issues/790)

In a nutshell. it's running. The config looks okay to me. but it's not capturing anything. I posted additional info to the original ticket

**Comment by rs** [comment]
What do you get for `nextdns config` and `curl -L https://test.nextdns.io`

**Comment by rs** [comment]
Answered in the other issue
