### ISSUE TITLE
synology: log bug

### ISSUE THREAD

**Issue by grrrrreg** [nextdns/nextdns#80]
Also witnessed live with @rs on my Synology
```
admin@jumbo:/$ nextdns log
Error: exit status 2
```

**Comment by grrrrreg** [comment]
FWIW install via the shell script went perfectly fine.

**Comment by rs** [comment]
Please try with sudo

**Comment by 1player** [comment]
Still fails when running as root

```
root@Cupboard:~# id
uid=0(root) gid=0(root) groups=0(root),2(daemon),19(log)
root@Cupboard:~# nextdns log
Error: exit status 1
```

**Comment by vandijks** [comment]
Not only the log fails to run also "nextdns discovered"

I get an: 

Error: dial unix /var/run/nextdns.sock: connect: permission denied
