### ISSUE TITLE
iCloud Private Relay bypasses "Enforce Safesearch"

### ISSUE THREAD

**Issue by TorsteinVin** [nextdns/nextdns#801]
**Context**
 - CLI Version: 1.39.4
 - Platform: Asus-merlin 388.1

When using Safari 16.2 on macOS 13.2 Ventura with iCloud Private Relay enabled, NextDNS' "Enforce Safesearch" is rendered useless and bypassed by Safari, leaving the web unfiltered from adult content. This happens despite "Block bypass methods" option enabled. 

Firefox is unaffected by iCloud Private Rely, and NextDNS' "Enfore safesearch" still works. The only way to have "Enforce Safesearch" working in Safari is by disabling iCloud Private Relay.

Due to privacy concerns I would like my family to be able to continue using Private Relay together with NextDNS and allow parental controls to work and protect my family from adult content etc.

Does anyone else experience this or have any solutions? Can perhaps NextDNS' engineers look into this?

**Comment by rs** [comment]
This issue is due to the way Apple Private Relay works and can’t be solved on our side.

**Comment by TorsteinVin** [comment]
According to "NextDNS" user on your forums, you and Apple have been in talks about a solution, but that was for ios15 and macos 12. any news on that front? 😊

NextDNS keeps filtering and blocking DNS-queries while private relay is activated, so it seems to work for some things?  Should I not be using both iCloud private relay and NextDNS at the same time at this point? And are you still working with Apple on this?

https://help.nextdns.io/t/p8hkfyw
"We worked with Apple on this and agreed on a better solution, but they could not implement it on time for the release. We hope the correct behavior will be implemented in the next dot release."

<img width="694" alt="Skjermbilde 2023-02-05 kl  17 49 32" src="https://user-images.githubusercontent.com/77975542/216832680-870f4cf6-b572-473f-93ee-9225980ff634.png">

**Comment by rs** [comment]
The solution with Apple is that blocking works, but any rewrite won’t. It’s safe for threat protection or ad-blocking, but won’t work for things like safe browsing or blockpage that rewrite the dns response instead of blocking it. Apple won’t move on that apparently. We can’t recommend using private relay for that reason.

**Comment by TorsteinVin** [comment]
**By "safe browsing" you mean "safe search", right? Will it work for your other security-features such as Google Safebrowsing**
- Cryptojacking protection
- DNS Rebinding Protection
- DNS Rebinding Protection
- Typosquatting Protection
- Domain Generation Algorithms (DGAs) Protection
- Block Newly Registered Domains (NRDs), Block Dynamic DNS Hostnames,
- Block Parked Domains
- Block Top-Level Domains (TLDs)?

**And what about under Privacy:**
- Block Top-Level Domains (TLDs)

**And performance-improvements such as**
- Anonymized EDNS Client Subnet
- Cache Boost
- CNAME Flattening

Will these work under iCloud Private Relay? If these work, then I feel safe using Private Relay together with NextDNS, but if not, I'd have to consider giving up Private Relay, which is a shame, since it provides excellent privacy protection from my ISP.

**Comment by rs** [comment]
Yes for all except the one that rewrite dns queries or responses like the last 3 ones.
