### ISSUE TITLE
UDM 2.4.27 / status not reported correctly

### ISSUE THREAD

**Issue by bondskin** [nextdns/nextdns#803]
**Context**
 - CLI Version: 1.39.4
 - Platform: UDM 2.4.27

Status of NextDNS keep changing, although it is running actually
Re-installation did not help.

> root@Skynet:# nextdns status
> running
> root@Skynet:# nextdns status
> running
> root@Skynet:# nextdns status
> not installed
> 

log:

> Feb 10 14:48:55 Skynet systemd[1]: Started NextDNS DNS53 to DoH proxy..
> Feb 10 14:48:55 Skynet nextdns[25344]: Starting NextDNS 1.39.4/linux on localhost:53
> Feb 10 14:48:55 Skynet nextdns[25344]: Listening on TCP/[::1]:53
> Feb 10 14:48:55 Skynet nextdns[25344]: Listening on UDP/127.0.0.1:53
> Feb 10 14:48:55 Skynet nextdns[25344]: Listening on TCP/127.0.0.1:53
> Feb 10 14:48:55 Skynet nextdns[25344]: Listening on UDP/[::1]:53
> Feb 10 14:48:55 Skynet nextdns[25344]: Startup failed: proxy: udp: listen udp 127.0.0.1:53: bind: address already in use
> Feb 10 14:48:55 Skynet nextdns[25344]: Error: proxy: udp: listen udp 127.0.0.1:53: bind: address already in use
> Feb 10 14:48:55 Skynet systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
> Feb 10 14:48:55 Skynet systemd[1]: nextdns.service: Failed with result 'exit-code'.
> Feb 10 14:48:55 Skynet systemd[1]: nextdns.service: Consumed 9ms CPU time.
> Feb 10 14:49:16 Skynet systemd[1]: Started NextDNS DNS53 to DoH proxy..
> Feb 10 14:49:16 Skynet nextdns[26120]: Starting NextDNS 1.39.4/linux on localhost:5553, [2003:c9:xxxx:af00::1]:5553
> Feb 10 14:49:16 Skynet nextdns[26120]: Starting mDNS discovery
> Feb 10 14:49:16 Skynet nextdns[26120]: Listening on TCP/[2003:c9:xxxx:af00::1]:5553
> Feb 10 14:49:16 Skynet nextdns[26120]: Listening on UDP/[::1]:5553
> Feb 10 14:49:16 Skynet nextdns[26120]: Listening on TCP/127.0.0.1:5553
> Feb 10 14:49:16 Skynet nextdns[26120]: Listening on TCP/[::1]:5553
> Feb 10 14:49:16 Skynet nextdns[26120]: Listening on UDP/[2003:c9:xxxx:af00::1]:5553
> Feb 10 14:49:16 Skynet nextdns[26120]: Listening on UDP/127.0.0.1:5553
> Feb 10 14:49:21 Skynet nextdns[26120]: Setting up router
> Feb 10 14:49:22 Skynet nextdns[26120]: Connected 45.90.30.0:443 (con=11ms tls=50ms, TCP, TLS13)
> Feb 10 14:49:22 Skynet nextdns[26120]: Connected 199.247.16.158:443 (con=11ms tls=38ms, TCP, TLS13)
> Feb 10 14:49:22 Skynet nextdns[26120]: Switching endpoint

**Comment by phaelium** [comment]
My install did this on 1.12.38 as well, so I don’t think it’s related to the 2.4 firmware…?

**Comment by Perkinje** [comment]
Same problem, also on 1.39.4 and 2.4.27

**Comment by GY8VSdYYzvL8-K6T** [comment]
Yes, firmware 2.X changed the OS completely. Its unknown if NextDNS can run on it going forward because firmwre 2.X does not include any containers. You may need to use UDM on-boot utilities and install Podman separate to get NextDNS working.

**Comment by rs** [comment]
2.x is supported

**Comment by bondskin** [comment]
> Yes, firmware 2.X changed the OS. They removed container support. NextDNS needs to update its plugin to make it work correctly.

I needed to re-install NextDNS once I moved from 1.x to UniFi OS 2.4.
No issue here with UnifiOS 2.5 and no re-installation was necessary.

**Comment by sarangrao** [comment]
Can confirm I get the same issue. Until a day ago it was working as expected. UDM-Pro updated last night.
Uninstalled nextdns and reinstalled. Restarted UDM Pro. I still get the message from my desktop
"This device is using NextDNS with no profile."

**Comment by bondskin** [comment]
Hi @sarangrao , this sounds like a different issue to me

**Comment by sarangrao** [comment]
I get the same error as you when I run the status. To add to it, after the update I can't get it working.

**Comment by nader-eloshaiker** [comment]
Has this issue been acknowledged by NextDNS, I have had to disable IPv6 to continue using their service.
