### ISSUE TITLE
EdgeOS CLI - nextdns log = Error: exit status 1

### ISSUE THREAD

**Issue by RobbieTT** [nextdns/nextdns#805]
The `nextdns log` command returns an error `exit status 1`.
 - CLI Version: 1.39.4
 - Platform: EdgeOS (ER-4 running v2.0.9-hotfix.6)

Not sure when this bug started but it worked fine for several months so this may be linked with an update somewhere.  Looking in more detail the `nextdns log` command appears to be a grep from `/var/log/messages` and on inspection there are no nextdns entries in this log (apologies if I have misunderstood this).  I can view NextDNS logs via the my.nextdns.io logs webpage though.

My nextdns config:

```
@router:~$ nextdns config
mdns all
detect-captive-portals false
debug false
listen 10.0.1.1:53
listen 10.0.2.1:53
listen 10.0.3.1:53
listen 172.16.1.1:53
control /var/run/nextdns.sock
report-client-info true
hardened-privacy false
use-hosts true
max-inflight-requests 256
setup-router false
profile xxxxxx
cache-max-age 0s
max-ttl 5s
bogus-priv true
timeout 3s
auto-activate true
log-queries true
cache-size 10MB
discovery-dns 127.0.0.1:3553
@router:~$ 
```

Regards.

**Comment by goofball222** [comment]
- CLI Version: 1.39.4
- Platform: EdgeOS (ERL running v2.0.9-hotfix.6)

Also seeing this same thing on the above config, first crash/failure happened early AM on 2023-02-15 for me, after having run without issue since 2023-01-23 when it was started post-upgrade.

nextdns-cli was stable for months prior to this latest update. It was upgraded to 1.39.4 via ```sudo nextdns upgrade```.

**Comment by RobbieTT** [comment]
Not planned?  I presumed this was just a bug, or is the EdgeOS version of nextdns being depreciated?

(I appreciate that EdgeOS is more towards the sunset of its lifespan.)

☕️

**Comment by rs** [comment]
Logging management will be changed so this sort of bug on different platforms will just go away.

**Comment by RobbieTT** [comment]
Perfect & thanks for the details.  👍

☕️
