### ISSUE TITLE
NextDNS-CLI stops resolving when failover to WAN 2 on Edgerouter 4

### ISSUE THREAD

**Issue by argiedoubleya** [nextdns/nextdns#809]
**Context**
 - CLI Version: 1.39.4
 - Platform: EdgeOS

I have a dual WAN setup on an Edgerouter 4. After failing over to WAN 2 there is no DNS resolution, it does not return after failing back to WAN 1. Nextdns-cli cannot be restarted either and gives and Exit code 1 when I try to restart it. The only way to get it to work again is to reboot the router. 

How do I get this to work?

**Comment by jimmystewpot** [comment]
what does `nextdns status` command show when it's in the state where it is failing to do DNS resolutions?

**Comment by vjasonacc** [comment]
> what does nextdns status command show when it's in the state where it is failing to do DNS resolutions?

when wan1 is down, i ssh into OPNSense, it shows that it's`running`

P.S I am having the same issues on my OPNSense router. My issues is exactly the same as OP, but we our different hardware, see [this](https://github.com/nextdns/nextdns/issues/809#issuecomment-1655898094) for more info.

**Comment by piersdd** [comment]
I also have this issue on EdgeRouter 4, which requires a NextDNS restart

```bash
Welcome to EdgeOS
vbash-4.1$ sudo /config/nextdns/nextdns restart
```

Have just adjusted my config, adding a `transition-script`. Not sure yet if it reliably works;

```
load-balance {
    group G {
        exclude-local-dns disable
        flush-on-active enable
        gateway-update-interval 20
        interface eth0.849 {
            failover-only
            failover-priority 10
        }
        interface eth3 {
            weight 40
        }
        interface pppoe0 {
            weight 80
        }
        lb-local enable
        lb-local-metric-change disable
        sticky {
            dest-addr enable
        }
        transition-script /config/scripts/wan_failover.sh
    }
}```

```
vbash-4.1$ cat /config/scripts/wan_failover.sh
#!/bin/sh
/config/nextdns/nextdns restart```
