### ISSUE TITLE
UDM SE - intermittent performance - inconsistent status reporting

### ISSUE THREAD

**Issue by strattao** [nextdns/nextdns#817]
**Context**
 - CLI Version: 1.39.4
 - Platform: UDM SE 3.0.18

Every day I wake up and see that NextDNS is not working. I confirm this by logging in to my.nextdns.io and it says "This device is not using NextDNS"
When I ssh into my UDM and check "nextdns status", sometimes it will say "running" and sometimes it will say "not installed"

I re-run the installation script and then I don't appear to have issues for the rest of the day. I assume something is getting stomped on during an update, but I'm not sure how to troubleshoot.

After I have run the installation script, I can log into my.nextdns.io and see that everything is "All good!", but checking the "nextdns status" on my UDM SE will sometimes say "running" and sometimes say "not installed" even though things appear to be working at that time.

If I run nextdns status repeatedly, it is not consistent:
root@Dream-Machine-Special-Edition:~# nextdns status
running
root@Dream-Machine-Special-Edition:~# nextdns status
running
root@Dream-Machine-Special-Edition:~# nextdns status
not installed
root@Dream-Machine-Special-Edition:~# nextdns status
running
root@Dream-Machine-Special-Edition:~# nextdns status
not installed
root@Dream-Machine-Special-Edition:~# nextdns status
running
root@Dream-Machine-Special-Edition:~# nextdns status
running
root@Dream-Machine-Special-Edition:~# nextdns status
not installed

What steps can I do to troubleshoot to figure out what is going on and what might be getting stomped on each day?

**Comment by jimmystewpot** [comment]
can you do the following commands and paste the output
`systemctl status nextdns`
also
`journalctl -u nextdns.service`

I am running the same versions you are reporting issues without any problems, just trying to see if there is something else that might be wrong.

**Comment by strattao** [comment]
root@Dream-Machine-Special-Edition:~# systemctl status nextdns
● nextdns.service - NextDNS DNS53 to DoH proxy.
     Loaded: loaded (/etc/systemd/system/nextdns.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-03-27 15:06:23 EDT; 1 day 1h ago
   Main PID: 301902 (nextdns)
      Tasks: 11 (limit: 4725)
     Memory: 50.6M
        CPU: 1min 30.772s
     CGroup: /system.slice/nextdns.service
             └─301902 /usr/bin/nextdns run

Mar 28 15:19:35 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=6ms tls=11ms, TCP, TLS13)
Mar 28 15:37:55 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=11ms tls=10ms, TCP, TLS13)
Mar 28 15:51:10 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=7ms tls=9ms, TCP, TLS13)
Mar 28 15:54:11 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=6ms tls=11ms, TCP, TLS13)
Mar 28 16:00:15 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=7ms tls=9ms, TCP, TLS13)
Mar 28 16:10:04 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=7ms tls=11ms, TCP, TLS13)
Mar 28 16:21:40 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=11ms tls=12ms, TCP, TLS13)
Mar 28 16:32:12 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=13ms tls=10ms, TCP, TLS13)
Mar 28 16:42:30 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=7ms tls=5ms, TCP, TLS13)
Mar 28 16:47:47 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=9ms tls=10ms, TCP, TLS13)


root@Dream-Machine-Special-Edition:~# journalctl -u nextdns.service
-- Journal begins at Tue 2023-03-28 13:54:26 EDT, ends at Tue 2023-03-28 16:49:53 EDT. --
Mar 28 14:01:41 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=11ms tls=12ms, TCP, TLS13)
Mar 28 14:09:17 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=9ms tls=12ms, TCP, TLS13)
Mar 28 14:18:39 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=9ms tls=8ms, TCP, TLS13)
Mar 28 14:25:02 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=14ms tls=6ms, TCP, TLS13)
Mar 28 14:29:45 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=7ms tls=11ms, TCP, TLS13)
Mar 28 14:49:14 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=7ms tls=11ms, TCP, TLS13)
Mar 28 14:54:21 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=6ms tls=10ms, TCP, TLS13)
Mar 28 15:10:20 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=3ms tls=10ms, TCP, TLS13)
Mar 28 15:19:35 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=6ms tls=11ms, TCP, TLS13)
Mar 28 15:37:55 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=11ms tls=10ms, TCP, TLS13)
Mar 28 15:51:10 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=7ms tls=9ms, TCP, TLS13)
Mar 28 15:54:11 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=6ms tls=11ms, TCP, TLS13)
Mar 28 16:00:15 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=7ms tls=9ms, TCP, TLS13)
Mar 28 16:10:04 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=7ms tls=11ms, TCP, TLS13)
Mar 28 16:21:40 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=11ms tls=12ms, TCP, TLS13)
Mar 28 16:32:12 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=13ms tls=10ms, TCP, TLS13)
Mar 28 16:42:30 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=7ms tls=5ms, TCP, TLS13)
Mar 28 16:47:47 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=9ms tls=10ms, TCP, TLS13)


And yet, my network is not using nextdns. The rules are not applied, I can access sites I have blocked, etc. When I browse to https://my.nextdns.io it says this device is not using NextDNS. 
![Image 3-28-23 at 4 48 PM](https://user-images.githubusercontent.com/10549774/228365110-5a18a56f-4944-41ff-bc33-2c9150110b9e.jpg)

It's at this step that I run the install script again. And here is the output of those two commands:

root@Dream-Machine-Special-Edition:~# systemctl status nextdns
● nextdns.service - NextDNS DNS53 to DoH proxy.
     Loaded: loaded (/etc/systemd/system/nextdns.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-03-28 16:54:51 EDT; 7s ago
   Main PID: 2749554 (nextdns)
      Tasks: 11 (limit: 4725)
     Memory: 11.3M
        CPU: 282ms
     CGroup: /system.slice/nextdns.service
             └─2749554 /usr/bin/nextdns run

Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Starting NextDNS 1.39.4/linux on localhost:5553
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Listening on TCP/[::1]:5553
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Starting mDNS discovery
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Listening on TCP/127.0.0.1:5553
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Listening on UDP/127.0.0.1:5553
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Listening on UDP/[::1]:5553
Mar 28 16:54:56 Dream-Machine-Special-Edition nextdns[2749554]: Setting up router
Mar 28 16:54:56 Dream-Machine-Special-Edition nextdns[2749554]: Connected 45.90.30.0:443 (con=5ms tls=43ms, TCP, TLS13)
Mar 28 16:54:56 Dream-Machine-Special-Edition nextdns[2749554]: Connected 5.161.43.197:443 (con=8ms tls=31ms, TCP, TLS13)
Mar 28 16:54:56 Dream-Machine-Special-Edition nextdns[2749554]: Switching endpoint: https://dns.nextdns.io#170.39.224.134,5.161.43.197,2a0e:6902:2002:12b:5054:


root@Dream-Machine-Special-Edition:~# journalctl -u nextdns.service
-- Journal begins at Tue 2023-03-28 13:54:26 EDT, ends at Tue 2023-03-28 16:57:59 EDT. --
Mar 28 14:01:41 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=11ms tls=12ms, TCP, TLS13)
Mar 28 14:09:17 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=9ms tls=12ms, TCP, TLS13)
Mar 28 14:18:39 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=9ms tls=8ms, TCP, TLS13)
Mar 28 14:25:02 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=14ms tls=6ms, TCP, TLS13)
Mar 28 14:29:45 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=7ms tls=11ms, TCP, TLS13)
Mar 28 14:49:14 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=7ms tls=11ms, TCP, TLS13)
Mar 28 14:54:21 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=6ms tls=10ms, TCP, TLS13)
Mar 28 15:10:20 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=3ms tls=10ms, TCP, TLS13)
Mar 28 15:19:35 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=6ms tls=11ms, TCP, TLS13)
Mar 28 15:37:55 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=11ms tls=10ms, TCP, TLS13)
Mar 28 15:51:10 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=7ms tls=9ms, TCP, TLS13)
Mar 28 15:54:11 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=6ms tls=11ms, TCP, TLS13)
Mar 28 16:00:15 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=7ms tls=9ms, TCP, TLS13)
Mar 28 16:10:04 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=7ms tls=11ms, TCP, TLS13)
Mar 28 16:21:40 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=11ms tls=12ms, TCP, TLS13)
Mar 28 16:32:12 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=13ms tls=10ms, TCP, TLS13)
Mar 28 16:42:30 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=7ms tls=5ms, TCP, TLS13)
Mar 28 16:47:47 Dream-Machine-Special-Edition nextdns[301902]: Connected 5.161.43.197:443 (con=9ms tls=10ms, TCP, TLS13)
Mar 28 16:51:28 Dream-Machine-Special-Edition nextdns[301902]: Connected 170.39.224.134:443 (con=4ms tls=10ms, TCP, TLS13)
Mar 28 16:54:49 Dream-Machine-Special-Edition systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Mar 28 16:54:49 Dream-Machine-Special-Edition nextdns[301902]: Received signal: terminated
Mar 28 16:54:49 Dream-Machine-Special-Edition nextdns[301902]: Stopping NextDNS 1.39.4/linux
Mar 28 16:54:49 Dream-Machine-Special-Edition nextdns[301902]: Restore router settings
Mar 28 16:54:49 Dream-Machine-Special-Edition nextdns[301902]: NextDNS 1.39.4/linux stopped
Mar 28 16:54:49 Dream-Machine-Special-Edition systemd[1]: nextdns.service: Succeeded.
Mar 28 16:54:49 Dream-Machine-Special-Edition systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
Mar 28 16:54:49 Dream-Machine-Special-Edition systemd[1]: nextdns.service: Consumed 1min 31.075s CPU time.
Mar 28 16:54:51 Dream-Machine-Special-Edition systemd[1]: Started NextDNS DNS53 to DoH proxy..
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Starting NextDNS 1.39.4/linux on localhost:5553
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Listening on TCP/[::1]:5553
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Starting mDNS discovery
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Listening on TCP/127.0.0.1:5553
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Listening on UDP/127.0.0.1:5553
Mar 28 16:54:51 Dream-Machine-Special-Edition nextdns[2749554]: Listening on UDP/[::1]:5553
Mar 28 16:54:56 Dream-Machine-Special-Edition nextdns[2749554]: Setting up router
Mar 28 16:54:56 Dream-Machine-Special-Edition nextdns[2749554]: Connected 45.90.30.0:443 (con=5ms tls=43ms, TCP, TLS13)
Mar 28 16:54:56 Dream-Machine-Special-Edition nextdns[2749554]: Connected 5.161.43.197:443 (con=8ms tls=31ms, TCP, TLS13)
Mar 28 16:54:56 Dream-Machine-Special-Edition nextdns[2749554]: Switching endpoint: https://dns.nextdns.io#170.39.224.134,5.161.43.197,2a0e:6902:2002:12b:5054:


And now everything is happy!
![Image 3-28-23 at 4 58 PM](https://user-images.githubusercontent.com/10549774/228365414-88aee4a5-8286-4d34-bdab-59c5be1c079f.jpg)

So, since you are running without any problems, that tells me it must be something with my UDM SE configuration...

**Comment by jimmystewpot** [comment]
Are you a dual stack network, i.e. IPv4 and IPv6 on the same network interfaces?

**Comment by strattao** [comment]
Not dual stack networked, and yes I am connected on the same interface/wifi as the UDM.
As I have been troubleshooting this, I have disabled ipv6 on my network. I only have br0 on my UDM SE, no br1 or above.

**Comment by jimmystewpot** [comment]
Do you have dual internet connections or vpn?

**Comment by strattao** [comment]
I do not have a dual internet connection, and am not currently using a vpn. I will sometimes enable the vpn on the UDM SE when I know I’ll be away from home and want to get onto my network remotely.

**Comment by jimmystewpot** [comment]
Thanks, I am trying to reproduce errors with my second device.. so far unsuccessfully

**Comment by johanns** [comment]
Experiencing the same issue with DreamMachine Pro and 3.0.20. 

```
root@UDMPro:~# nextdns status
running
root@UDMPro:~# nextdns status
running
root@UDMPro:~# nextdns status
running
root@UDMPro:~# nextdns status
running
root@UDMPro:~# nextdns status
running
root@UDMPro:~# nextdns status
running
root@UDMPro:~# nextdns status
running
root@UDMPro:~# nextdns status
not installed
root@UDMPro:~# nextdns status
```

```
● nextdns.service - NextDNS DNS53 to DoH proxy.
     Loaded: loaded (/etc/systemd/system/nextdns.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-04-21 09:24:55 PDT; 42min ago
   Main PID: 3006656 (nextdns)
      Tasks: 11 (limit: 4725)
     Memory: 43.1M
        CPU: 14.446s
     CGroup: /system.slice/nextdns.service
             └─3006656 /usr/bin/nextdns run

Apr 21 09:24:55 UDMPro nextdns[3006656]: Starting mDNS discovery
Apr 21 09:24:55 UDMPro nextdns[3006656]: Listening on TCP/[::1]:5553
Apr 21 09:24:55 UDMPro nextdns[3006656]: Listening on UDP/127.0.0.1:5553
Apr 21 09:24:55 UDMPro nextdns[3006656]: Listening on TCP/127.0.0.1:5553
Apr 21 09:24:55 UDMPro nextdns[3006656]: Listening on UDP/[::1]:5553
Apr 21 09:25:00 UDMPro nextdns[3006656]: Setting up router
Apr 21 09:25:00 UDMPro nextdns[3006656]: Activating
Apr 21 09:25:41 UDMPro nextdns[3006656]: Connected 45.90.28.0:443 (con=14ms tls=64ms, TCP, TLS13)
Apr 21 09:25:41 UDMPro nextdns[3006656]: Connected 104.238.181.28:443 (con=11ms tls=37ms, TCP, TLS13)
Apr 21 09:25:41 UDMPro nextdns[3006656]: Switching endpoint: https://dns.nextdns.io#104.238.181.28,209.209.57.165,2001:19f0:ac01:170:5400:2ff:fec8:72>
root@UDMPro:~# journalctl -u nextdns.service
-- Journal begins at Thu 2023-04-20 22:59:30 PDT, ends at Fri 2023-04-21 10:07:52 PDT. --
Apr 21 09:24:55 UDMPro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Apr 21 09:24:55 UDMPro nextdns[3006656]: Starting NextDNS 1.39.4/linux on localhost:5553
Apr 21 09:24:55 UDMPro nextdns[3006656]: Starting mDNS discovery
Apr 21 09:24:55 UDMPro nextdns[3006656]: Listening on TCP/[::1]:5553
Apr 21 09:24:55 UDMPro nextdns[3006656]: Listening on UDP/127.0.0.1:5553
Apr 21 09:24:55 UDMPro nextdns[3006656]: Listening on TCP/127.0.0.1:5553
Apr 21 09:24:55 UDMPro nextdns[3006656]: Listening on UDP/[::1]:5553
Apr 21 09:25:00 UDMPro nextdns[3006656]: Setting up router
Apr 21 09:25:00 UDMPro nextdns[3006656]: Activating
Apr 21 09:25:41 UDMPro nextdns[3006656]: Connected 45.90.28.0:443 (con=14ms tls=64ms, TCP, TLS13)
Apr 21 09:25:41 UDMPro nextdns[3006656]: Connected 104.238.181.28:443 (con=11ms tls=37ms, TCP, TLS13)
Apr 21 09:25:41 UDMPro nextdns[3006656]: Switching endpoint: https://dns.nextdns.io#104.238.181.28,209.209.57.165,2001:19f0:ac01:170:5400:2ff:fec8:72>
```

I have (4) `br` interfaces:

```
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.254  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::ac8b:a9ff:fe2c:5a3e  prefixlen 64  scopeid 0x20<link>
        ether ae:8b:a9:2c:5a:3e  txqueuelen 1000  (Ethernet)
        RX packets 517692  bytes 185133823 (176.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2175348  bytes 2780066227 (2.5 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.120.254  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::d086:69ff:feae:6e4  prefixlen 64  scopeid 0x20<link>
        inet6 <SNIP>18c4::1  prefixlen 64  scopeid 0x0<global>
        ether ac:8b:a9:2c:5a:47  txqueuelen 1000  (Ethernet)
        RX packets 5867002  bytes 6622030469 (6.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8923455  bytes 8571730043 (7.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.130.254  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::4474:5eff:fec6:3951  prefixlen 64  scopeid 0x20<link>
        ether ac:8b:a9:2c:5a:47  txqueuelen 1000  (Ethernet)
        RX packets 311183  bytes 45958573 (43.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 475934  bytes 176642031 (168.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.140.254  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::400f:8bff:fe00:7379  prefixlen 64  scopeid 0x20<link>
        ether ac:8b:a9:2c:5a:47  txqueuelen 1000  (Ethernet)
        RX packets 36057  bytes 7714302 (7.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 44868  bytes 20457865 (19.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by johanns** [comment]
Update: Disabling IPv6 on `br2` resolved the issue. I noticed in `/ubios/setup.go` that assumption is that global IPv6 is always attached to `br0` -- perhaps this can be a prompt or post install config option.

https://github.com/nextdns/nextdns/blob/36bec555dc4df42cfdf079e21ea17dbe0d096191/router/ubios/setup.go#L24
