### ISSUE TITLE
[Bug] NextDNS doesn't support Adguard DNS blocklists with wildcards

### ISSUE THREAD

**Issue by jakecharlie** [nextdns/nextdns#818]
Hello, I noticed that NextDNS has a bug related to some domains on the AdguardDNS list because NextDNS does not  support AdguardDNS list blocklists with wildcards yet.

I went to test blocking two Amazon telemetry domains used on the Echo Show and Fire TV.

You can see in their list here: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

Domain blocked:

||device-metrics-*.amazon.com^
||device-metrics-us*.amazon.com^

You can see that instead of them blocking [device-metrics-us.amazon.com](http://device-metrics-us.amazon.com/) and [device-metrics-us-2.amazon.com](http://device-metrics-us-2.amazon.com/) probably to save space in the list and make it smaller or to cover possible new tracking domains of the same company, they (Adguard team) block some domains in a single line and put an asterisk * on the domain itself.

I went to test it in the linux terminal and realized that this type of approach works when using their own DNS (https://adguard-dns.io/en/public-dns.html), but testing NextDNS with  the AdguardDNS list, these domains are not being blocked.

They use this type of approach in 244 domains, such as:
||sock*-goguardian.pusher.com^
||analytics*.clickdimensions.com^
||dualstack.adbert-web-lbs-*.elb.amazonaws.com^

Please, see this particularity of the AdguardDNS list, because if not, many domains that should be blocked, will not be using NextDNS with adguard dns list.

**TERMINAL LINUX (USING ADGUARD DNS):**
acer@acer:~$ nslookup [device-metrics-us.amazon.com](http://device-metrics-us.amazon.com/)
Server: 127.0.0.53
Address: 127.0.0.53#53

Non-authoritative answer:
Name: [device-metrics-us.amazon.com](http://device-metrics-us.amazon.com/)
Address: 0.0.0.0
Name: [device-metrics-us.amazon.com](http://device-metrics-us.amazon.com/)
Address: ::

acer@acer:~$ nslookup [device-metrics-us-2.amazon.com](http://device-metrics-us-2.amazon.com/)
Server: 127.0.0.53
Address: 127.0.0.53#53

Non-authoritative answer:
Name: [device-metrics-us-2.amazon.com](http://device-metrics-us-2.amazon.com/)
Address: 0.0.0.0
Name: [device-metrics-us-2.amazon.com](http://device-metrics-us-2.amazon.com/)
Address: ::

**TERMINAL LINUX (USING NEXTDNS WITH ADGUARD DNS LIST ENABLED):**
acer@acer:~$ nslookup [device-metrics-us.amazon.com](http://device-metrics-us.amazon.com/)
Server: 127.0.0.53
Address: 127.0.0.53#53

Non-authoritative answer:
Name: [device-metrics-us.amazon.com](http://device-metrics-us.amazon.com/)
Address: 52.1.172.87
Name: [device-metrics-us.amazon.com](http://device-metrics-us.amazon.com/)
Address: 3.208.140.212
Name: [device-metrics-us.amazon.com](http://device-metrics-us.amazon.com/)
Address: 44.197.43.221

acer@acer:~$ nslookup [device-metrics-us-2.amazon.com](http://device-metrics-us-2.amazon.com/)
Server: 127.0.0.53
Address: 127.0.0.53#53

Non-authoritative answer:
Name: [device-metrics-us-2.amazon.com](http://device-metrics-us-2.amazon.com/)
Address: 54.157.203.98
Name: [device-metrics-us-2.amazon.com](http://device-metrics-us-2.amazon.com/)
Address: 54.205.24.65
Name: [device-metrics-us-2.amazon.com](http://device-metrics-us-2.amazon.com/)
Address: 54.166.21.152

I reached out to the Adguard DNS team asking what the NextDNS team should know to facilitate the implementation of wildcard domains: https://github.com/AdguardTeam/AdGuardDNS/issues/550

https://adguard-dns.io/kb/general/dns-filtering-syntax/

https://adguard.com/kb/general/ad-filtering/create-own-filters/

**Please add support to Adguard DNS blocklists with wildcards**

**Comment by damian-w** [comment]
+1 - would love to see this supported.

**Comment by trollybusman** [comment]
In the mean time, just use Control D: https://freedns.controld.com/x-adguard

Works great.
