### ISSUE TITLE
0x20 Bit Support

### ISSUE THREAD

**Issue by Veldkornet** [nextdns/nextdns#82]
In pfSense, I had enabled “_[0x20 Bit](https://tools.ietf.org/html/draft-vixie-dnsext-dns0x20-00) Support_“ under advanced options.
`Use 0x-20 encoded random bits in the DNS query to foil spoofing attempts.`
Initially, this works, but after a while you start getting the following error:

`SSL_handshake syscall: Connection reset by peer`

The only way I can fix it is to restart Unbound, then it will work again... for a while.

This seems to work fine with 1.1.1.1 and 9.9.9.9, but NextDNS doesn’t seem to be happy with it. Additionally, if it’s enabled, in the NextDNS dashboard it doesn’t see you as “Using NextDNS”, and says you’re using an “Unknown” DNS server and the little traffic light is grey instead of green.

I had pfSense setup as follows:
	

- **DNS Resolver:**
```
[x] Enable DNSSEC Support
[x] Enable Forwarding Mode
[x] Use SSL/TLS for outgoing DNS Queries to Forwarding Servers
```
		     
-  **DNS Resolver - Advanced Settings:**
```
[x] Query Name Minimization
[x] Prefetch Support
[x] Prefetch DNS Key Support
[x] Harden DNSSEC Data
[x] Experimental Bit 0x20 Support
```
	
- **General Setup:**
```
45.90.28.0	<device-name>-<id> .dns1.nextdns.io
45.90.30.0	<device-name>-<id> .dns2.nextdns.io
```

**Comment by rs** [comment]
I don't see how 0x20 Bit entropy could generate this error. We had a bug in the connection tester tho, which can explain "Unknown" resolver. We will deploy a fix ASAP.

If you use DoT or DoH, 0x20 Bit entropy is unnecessary. Also, it's better to disable DNSSEC validation at client level if you are using blocklists.

Any reason for not using nextdns cli (this project) instead of unbound?

**Comment by Veldkornet** [comment]
Ah oki, I’ve changed the DNSSEC settings.

Understood that the 0x20 is probably not necessary, but as I had it on for a while with the other DNS providers without any problems, I couldn’t figure out why it was going wrong.

No reason in particular, it works fine via the GUI and was quick to do, so I’ve not looked into the CLI yet :)

**Comment by rs** [comment]
Apparently, the issue you are describing happened [with other providers](https://forum.opnsense.org/index.php?topic=7811.0) too. Not sure if it is fixed now and how they fixed it.

**Comment by rs** [comment]
I'm gonna close this issue as it is not related to this project, and the status page bug with 0x20 has been fixed.
