### ISSUE TITLE
NextDNS no more as of Unifi OS 3.1.6 

### ISSUE THREAD

**Issue by Ricks88** [nextdns/nextdns#820]
![offline1](https://user-images.githubusercontent.com/91467918/227164877-c522c5b9-af3f-404d-b3b5-e584c0c81305.jpg)
**Context**
 - CLI Version: 1.39.4
 - Platform: Unifi OS 3.1.6

&lt;Describe the bug>
Network Offline in UDR
All the info @ 
https://community.ui.com/questions/Network-application-not-available/b6645d3c-c5c9-458a-8109-0ebdc6b769fd#answer/3ccf21d2-a20e-492c-a16f-46a1e68630eb

**Comment by tfs** [comment]
I second that - https://community.ui.com/questions/Application-unavailable/55e4e3a0-5b77-4ff0-aa4f-96167747799d#answer/3c3c19a7-081c-4fd2-96e0-ca87bde4ef1c

Currently I know of at least 3 persons that are affected in the (preview) channel of the new Unifi OS 3.1.6.

UI has no detailed information - they consider installing nextdns as a modification that is not supported. Only solution proposal from UI is "reset device, restore from backup, don't install nextdns".

**Comment by tfs** [comment]
I am still looking, but I have not found any logs with messages in regard to this.
Somewhat puzzleing -> the router and internal network as well as wan connection works.

Definitely not working is the network application as shown in the above screenshot - it pronounces itself offline.

**Comment by tfs** [comment]
Fixed by a new UniFi Network Application 7.4.149 - Admin Website is working again.

**Comment by mojo333** [comment]
Great news
