### ISSUE TITLE
error during upgrade

### ISSUE THREAD

**Issue by Mile-Lile** [nextdns/nextdns#824]
**Context**
 - CLI Version: 1.39.4
 - Platform: DD-WRT

While upgrading from cli I get error: **Error: Get "https://nextdns.io/install": x509: certificate signed by unknown authority**

![Screenshot_deepin-terminal_20230416075504](https://user-images.githubusercontent.com/12752816/232274534-0750a935-b2d0-4c72-b8de-332c10bf8d37.png)

**Comment by rs** [comment]
Fixed
