### ISSUE TITLE
apt update giving errors

### ISSUE THREAD

**Issue by pythonmobile** [nextdns/nextdns#825]
Failed to fetch https://repo.nextdns.io/deb/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 467A7CCC8ACFA0B7 NextDNS <team@nextdns.io>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Context**
 - CLI Version: nextdns version 1.39.4
 - Platform: Ubuntu 20.04LTS

apt update has started giving this error. What is the correct way of fixing this?

**Comment by drzero42** [comment]
@pythonmobile The key used for signing has expired. The admins of the packages repo need to create a fresh set of private and public key, and then everybody using the repo need to grab this new public key. After that, things work again.

**Comment by rs** [comment]
Fixed

**Comment by slimshizn** [comment]
People coming back at a later date, the answer is here https://github.com/nextdns/nextdns/issues/828#issuecomment-1520272702
