### ISSUE TITLE
repo not signed

### ISSUE THREAD

**Issue by goodale** [nextdns/nextdns#826]
I'm trying to install NextDNS on a Unifi DMP per instructions at https://github.com/nextdns/nextdns/wiki/UnifiOS

The following error occurs:

Err:6 https://repo.nextdns.io/deb stable InRelease
  The following signatures were invalid: EXPKEYSIG 467A7CCC8ACFA0B7 NextDNS <team@nextdns.io>
Reading package lists... Done
W: GPG error: https://repo.nextdns.io/deb stable InRelease: The following signatures were invalid: EXPKEYSIG 467A7CCC8ACFA0B7 NextDNS <team@nextdns.io>
E: The repository 'https://repo.nextdns.io/deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
i) Install NextDNS
e) Exit

**Comment by hagezi** [comment]
https://github.com/nextdns/nextdns/issues/824
https://github.com/nextdns/nextdns/issues/825

ping @romaincointepas @rs

**Comment by rs** [comment]
Fixed

**Comment by crcastle** [comment]
For those that bump into this and don't know how to fix the issue now that NextDNS has updated the keys, all I had to do was run the below command to get the new public key and put it in the correct place. Note that this is **specifically for Debian or apt-based installs**.

```
sudo wget -qO /usr/share/keyrings/nextdns.gpg https://repo.nextdns.io/nextdns.gpg
```

This is the first command in NextDNS's [Manual Debian Install Instructions](https://github.com/nextdns/nextdns/wiki/Debian-Based-Distribution#manual-install).
