### ISSUE TITLE
Signatures invalid: Error: https://repo.nextdns.io/deb stable InRelease

### ISSUE THREAD

**Issue by ngmisl** [nextdns/nextdns#828]
- Platform: Debian

Error: https://repo.nextdns.io/deb stable InRelease
  The following signatures were invalid: EXPKEYSIG 467A7CCC8ACFA0B7 NextDNS <team@nextdns.io>

**Comment by hagezi** [comment]
Manual fix:

```
sudo wget -qO /etc/apt/keyrings/nextdns.gpg https://repo.nextdns.io/nextdns.gpg
sudo curl -sfL https://repo.nextdns.io/nextdns.gpg -o /etc/apt/keyrings/nextdns.gpg
sudo chmod 0644 /etc/apt/keyrings/nextdns.gpg
sudo apt update
```

**Comment by ngmisl** [comment]
@hagezi 

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.nextdns.io/deb stable InRelease: The following signatures were invalid: EXPKEYSIG 467A7CCC8ACFA0B7 NextDNS <team@nextdns.io>
W: Failed to fetch https://repo.nextdns.io/deb/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 467A7CCC8ACFA0B7 NextDNS <team@nextdns.io>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by hagezi** [comment]
@ngmisl 
Did the exchange of the key work?

Please show the content of the file `/etc/apt/sources.list.d/nextdns.list`

**Comment by ngmisl** [comment]
@hagezi 

`deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main`

**Comment by hagezi** [comment]
@ngmisl 

The key is in a different directory for you, in the commands above you must replace `/etc/apt/keyrings/nextdns.gpg` in 3 places with `/usr/share/keyrings/nextdns.gpg`

Then it should work.

**Comment by ngmisl** [comment]
worked, thanks!

**Comment by hagezi** [comment]
Great!

**Comment by DonRichards** [comment]
To sum up the solution, edit `/etc/apt/sources.list.d/nextdns.list` and set it to **/usr/share/keyrings/**
```list
deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main
```

Then run these commands
```shell
sudo wget -qO /usr/share/keyrings/nextdns.gpg https://repo.nextdns.io/nextdns.gpg
# OR
sudo curl -sfL https://repo.nextdns.io/nextdns.gpg -o /usr/share/keyrings/nextdns.gpg

# THEN  
sudo chmod 0644 /etc/apt/keyrings/nextdns.gpg
sudo apt update
```
This worked for me. Just thought a little clarity will help the next person. And it's either curl or wget but both isn't needed I assume.

**Comment by smithbill17** [comment]
This worked for me also, but to clarify your clarification, I think the chmod bit is meant to say:

`sudo chmod 0644 /user/share/keyrings/nextdns.gpg`

😁

**Comment by volcan96** [comment]
@smithbill17 @DonRichards I think the command should be:
sudo chmod 0644 /usr/share/keyrings/nextdns.gpg

there's an e in "usr" in previous command

**Comment by bonnebulle** [comment]
I do this way...
```sudo curl -sfL https://repo.nextdns.io/nextdns.gpg -o nextdns.gpg```
```sudo apt-key add - < nextdns.gpg```
(others doesnt works)
