### ISSUE TITLE
Unifi OS UDM SE update .3.1.11 appears to uninstall nextdns client

### ISSUE THREAD

**Issue by sdjernes** [nextdns/nextdns#844]
**Context**
 - CLI Version: 1.39.4
 - Platform: UnifiOS 3.1.11

&lt;Describe the bug>
When the UDM SE upgrades from 3.1.9 to 3.1.11, the nextdns client seems to be uninstalled from the router and needs to be reinstalled.  All config settings seem to be saved as it has my ID when it goes to configure the client.

This is what it detects during the install:
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.39.4

**Comment by ravens** [comment]
Same here on UDM base.

**Comment by bondskin** [comment]
normal behaviour since UnifiOS >= 2.0 as it does not come with pod manager

With every new Unifi firmware, you need to install NextDNS again (config data is retained, though)

**Comment by ravens** [comment]
I think this is more the persistence strategy that needs to be changed. 
I noticed systemctl scripts persist across those updates in 2.x/3.x, perhaps the install part of the nextdns binary should generate a minimal entry capable of reinstalling the binary by itself.

**Comment by damienbutt** [comment]
On UDM-Pro 3.1.12, the install script no longer works. 

```
root@UDM-PRO:~# sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'
ERROR: Cannot get latest version:
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE:
ERROR: Cannot detect running environment.
```

I was able to get back up and running using `wget` on the `arm64.deb` and using `sudo dpkg -i` though.

**Comment by ravens** [comment]
On my, with 3.1.12, UDM Base, the install script works however - it could reinstall the env.

**Comment by bondskin** [comment]
Hi @damienbutt ,
Would you please share the full dpkg command?

I am still on 3.1.11 (UDM Base) and it worked with the script at least up to this version 

Thx
Mike

**Comment by damienbutt** [comment]
> Hi @damienbutt ,
> Would you please share the full dpkg command?
> 
> I am still on 3.1.11 (UDM Base) and it worked with the script at least up to this version 
> 
> Thx
> Mike

Hi Mike,

`sudo dpkg -i [name_of_package]_arm64.deb`

Can’t remember the name of package of top of my head but it’s the name of the package yoy download using `wget` from the GitHub releases page.

Thanks,
D

**Comment by ravens** [comment]
So it looks like nextdns install failed during the first minutes after the boot, and then start to work again:
```
root@Nuke:~# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
ERROR: Cannot get latest version:
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE:
ERROR: Cannot detect running environment.
root@Nuke:~# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.39.4
i) Install NextDNS
e) Exit
Choice (default=i):
```

**Comment by sanyer** [comment]
I'm experiencing the same on UDM Base 3.1.13
Both install script and nextdns upgrade result in this:

```
root@dream-machine:~# nextdns upgrade
ERROR: Cannot get latest version:
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE:
ERROR: Cannot detect running environment.
Error: exit status 1
```

**Comment by bondskin** [comment]
@sanyer :
Did you try 
https://github.com/nextdns/nextdns/wiki/UnifiOS

> sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'

**Comment by beelzetron** [comment]
> With every new Unifi firmware, you need to install NextDNS again (config data is retained, though)

Conditional forwarders configuration is not retained, I have to add it back after nextdns reinstallation.

**Comment by sanyer** [comment]
@bondskin yeah, I did try.
I just downloaded .deb and installed manually.

**Comment by rs** [comment]
I could not reproduce this. Keep in mind that it can take several minutes for the UDM to be fully started and the cli is started relatively late in the startup process, giving the impression it is no longer installed.
