### ISSUE TITLE
NextDNS support ended?

### ISSUE THREAD

**Issue by Ricks88** [nextdns/nextdns#849]
Seems nothing is happening here anymore, can we say it is dead?
Any replacement tool?

**Comment by ijuliank** [comment]
Adguard home, for cli replacement.. Or devices just the adguard app

**Comment by maghuro** [comment]
I'm very very sad, because I've been member since day one. I loved the service, the innovation, the support team.
But unfortunately I had to switch to ControlD.

I mean, NextDNS is working, but in autopilot. No innovation, not a single word from both Romain nor Oliver.

They also started DNS0, fantastic in Europe. First week of party, and then... Auto pilot.
I dunno what's happening, unfortunately.

I switched to ControlD. Maybe in a future, I switch back. When the two guys I saw as kings return.

Farewell... :(

**Comment by ijuliank** [comment]
> I'm very very sad, because I've been member since day one. I loved the service, the innovation, the support team. But unfortunately I had to switch to ControlD.
> 
> I mean, NextDNS is working, but in autopilot. No innovation, not a single word from both Romain nor Oliver.
> 
> They also started DNS0, fantastic in Europe. First week of party, and then... Auto pilot. I dunno what's happening, unfortunately.
> 
> I switched to ControlD. Maybe in a future, I switch back. When the two guys I saw as kings return.
> 
> Farewell... :(

why not adguard?

**Comment by maghuro** [comment]
> > I'm very very sad, because I've been member since day one. I loved the service, the innovation, the support team. But unfortunately I had to switch to ControlD.
> > 
> > I mean, NextDNS is working, but in autopilot. No innovation, not a single word from both Romain nor Oliver.
> > 
> > They also started DNS0, fantastic in Europe. First week of party, and then... Auto pilot. I dunno what's happening, unfortunately.
> > 
> > I switched to ControlD. Maybe in a future, I switch back. When the two guys I saw as kings return.
> > 
> > Farewell... :(
> 
> why not adguard?

I really don't know :)

Maybe I'll give it a try some day

**Comment by ijuliank** [comment]
> > > I'm very very sad, because I've been member since day one. I loved the service, the innovation, the support team. But unfortunately I had to switch to ControlD.
> > > I mean, NextDNS is working, but in autopilot. No innovation, not a single word from both Romain nor Oliver.
> > > They also started DNS0, fantastic in Europe. First week of party, and then... Auto pilot. I dunno what's happening, unfortunately.
> > > I switched to ControlD. Maybe in a future, I switch back. When the two guys I saw as kings return.
> > > Farewell... :(
> > 
> > 
> > why not adguard?
> 
> I really don't know :)
> 
> Maybe I'll give it a try some day

weird response overall but ok

**Comment by maghuro** [comment]
> > > > I'm very very sad, because I've been member since day one. I loved the service, the innovation, the support team. But unfortunately I had to switch to ControlD.
> > > > I mean, NextDNS is working, but in autopilot. No innovation, not a single word from both Romain nor Oliver.
> > > > They also started DNS0, fantastic in Europe. First week of party, and then... Auto pilot. I dunno what's happening, unfortunately.
> > > > I switched to ControlD. Maybe in a future, I switch back. When the two guys I saw as kings return.
> > > > Farewell... :(
> > > 
> > > 
> > > why not adguard?
> > 
> > I really don't know :)
> > 
> > Maybe I'll give it a try some day
> 
> weird response overall but ok

Weird answer?? Why? Because I choose ControlD over adguard? 🙄
