### ISSUE TITLE
Device name from docker

### ISSUE THREAD

**Issue by Sc0th** [nextdns/nextdns#85]
Hi,

When running the client in a k8s pod (using docker) the device name shown in analytics come through as entries such as 'Device #94UE2' which makes it tricky to ascertain where a request came from (especially as I am unable to figure out how that name is derived) would it be possible to allow provision of a custom string to clear this up?

Thanks!

**Comment by rs** [comment]
You can put names for each IPs in /etc/hosts inside the docker.

**Comment by Sc0th** [comment]
Unfortunately that will not work with k8s due to the way host names are assigned - even if it did it's kind of going against the principals of docker by creating a unique system, ideally it needs to be set as part of config so it can be sent into the pod via a variable. Is this something you would look into? I would expect as k8s becomes more widespread I will not be that last to ask....

**Comment by theshoehorn** [comment]
Great to know on the hosts file. Would be cool to see an option in the web GUI where we could assign names to the unknown device IDs too!

**Comment by rs** [comment]
We will implement renaming in the UI. Closing this, as it won't happen in the cli.

**Comment by FudiHub** [comment]
Any information on when we could expect device renaming in the UI?

**Comment by FudiHub** [comment]
> We will implement renaming in the UI. Closing this, as it won't happen in the cli.

Any information on when we could expect device renaming in the UI?
