### ISSUE TITLE
Issue with NextDNS CLI on UDM Pro SE - Devices not fully identified

### ISSUE THREAD

**Issue by GraafIvar** [nextdns/nextdns#851]
**Context**
 - CLI Version: 1.39.4
 - Platform: UnifiOS 
 - UnifiOS Version: UDM SE v3.1.15
 - Device Unifi Dream Machine Special Edition

I have recently installed NextDNS CLI on my new router, the UDM Pro SE. While using the CLI, I noticed that not all devices are fully identifiable in the logs. For example, my iPhone cannot be identified with its device name. I have checked if this issue is related to the different VLANs configured on the network. Interestingly, only a select few devices distributed across the different VLANs show their identity, including the device name, but not all devices.

Previously, when I initially installed the CLI last Thursday, all devices were properly identified. However, due to a bug, NextDNS was removed, and after reinstalling it, some devices are no longer being identified. I suspect this might be a bug in the NextDNS CLI. 

I have tried to troubleshoot the issue by reconfiguring VLAN settings and reinstalling the NextDNS CLI, but the problem persists. in addition, as a test I have adjusted the configuration, for each VLAN I have individually set the “listen localhost” to each IP address of the router, example “listen 10.0.0.1”. device names were then given here, but not the right ones, it looked like randomly generated names. in the end I undid the test and installed NextDNS all over again, now the names of all devices are still not passed.

**Comment by GraafIvar** [comment]
Addition:

In the logs on my.nextdns.io, I have noticed that certain devices, such as the Hue Bridge, virtual machines, and some IoT devices, correctly transmit their device names. However, the logs show that the solar panel inverter is displaying two different incorrect names. Moreover, my iPhone is still being identified by its external IP address without showing the device name or local IP address.

**Comment by rs** [comment]
By any chance, didn’t you setup a DNS profile on your iOS device? That would explain the external IP. If that’s the case, you can set the name during profile creation.

**Comment by GraafIvar** [comment]
> By any chance, didn’t you setup a DNS profile on your iOS device? That would explain the external IP. If that’s the case, you can set the name during profile creation.


nope, I have not installed a profile, and the app is disabled by default on the WiFi network. By the way, I also see that other Apple devices may also have this, no name is reported in the device list. and in the logs I only see the IP address, the other devices also have no profile and do not have the app

**Comment by rs** [comment]
And those devices have a proper name in the UDM’s UI?

**Comment by GraafIvar** [comment]
now that you mention it, the list is now bigger and my iPhone is now in there, but there is nothing in the logs under the device. To be on the safe side, I had completely deleted the logs so that the list was updated. so i think now i see the new list with my iphone
________________________________
Van: Olivier Poitrey ***@***.***>
Verzonden: Friday, July 28, 2023 8:42:07 AM
Aan: nextdns/nextdns ***@***.***>
CC: Ivar de Graaf ***@***.***>; Author ***@***.***>
Onderwerp: Re: [nextdns/nextdns] Issue with NextDNS CLI on UDM Pro SE - Devices not fully identified (Issue #851)


And those devices have a proper name in the UDM’s UI?

**Comment by GraafIvar** [comment]
![IMG_4485](https://github.com/nextdns/nextdns/assets/67483861/b866d203-85f1-4e33-9caa-a7f7b672086a)
![IMG_4484](https://github.com/nextdns/nextdns/assets/67483861/0b94f55a-27c0-4b3d-b472-45671197d4d0)

**Comment by bunker195** [comment]
Thanks for letting me know.

Bummer it won’t be fixed, though.

**Comment by rs** [comment]
It’s more closed as « non reproducible ». If you get more info on how to repro, feel free to reopen.

**Comment by bunker195** [comment]
I can reproduce it for you in a matter of a few hours and send video

I don’t know much about posting to GitHub, but if it will help I’m willing.

I have found that if I issue nextDNS restart everything goes back to working normally  using names for devices for a few hours.
