### ISSUE TITLE
UDM-Pro and NextDNS Configuration Issue

### ISSUE THREAD

**Issue by BlackJoker90** [nextdns/nextdns#853]
**Context**
 - CLI Version: 1.39.4
 - Platform: UDM Network 7.4.162

&lt;Describe the bug>
Despite a clean reinstall of the CLI version and restarting the service on the UDM-Pro, I'm unable to establish a successful connection. To navigate around this, I have manually entered the NextDNS IPs in the UDM-Pro, which although has provided a temporary fix, isn't an ideal solution in my view.

I'm curious to know if anyone else is currently encountering the same problem and has possibly found a solution. Any insights or advice regarding this issue would be greatly appreciated!

This is how my config looks like and the status says running

`root@UDM-Pro:~# nextdns config
log-queries false
mdns all
detect-captive-portals false
setup-router true
auto-activate true
debug false
control /var/run/nextdns.sock
max-ttl 5s
listen localhost:53
profile XXXXXX
report-client-info true
discovery-dns
bogus-priv true
max-inflight-requests 256
cache-size 10MB
cache-max-age 0s
hardened-privacy false
use-hosts true
timeout 5s
`

**Comment by tc60045** [comment]
Latest firmware from Ubiquiti blew away a well-performing NextDNS install on UDM-Pro (UDM Pro 3.1.15; Official channel; this installs Network 7.4.162).

Re-install of Nextdns is failing in two places in the shell script:
- first failing in get_release(), with 'cannot get latest version'
- then failing early in main(), with 'cannot detect running environment'

Here is rather sparse debug:

> root@Foo-UDM-Pro:~# sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'
ERROR: Cannot get latest version: 
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 
ERROR: Cannot detect running environment.

**Comment by BlackJoker90** [comment]
It is indeed a comfort to know that I am not alone in facing this challenge, and that there are others who share my perspective and have encountered similar difficulties. What we need now is a solution for the problem.

**Comment by tc60045** [comment]
@BlackJoker90, here is hoping this makes your day:
1. Go to https://github.com/nextdns/nextdns/releases/tag/v1.39.4
2. Find the release that corresponds to the underlying hardware of your Ubiquiti device.  For my UDM-Pro, that is linux-arm64
3. Download the .deb to your Mac / PC.  Again, here is mine: https://github.com/nextdns/nextdns/releases/download/v1.39.4/nextdns_1.39.4_linux_arm64.deb
4. make your UDM ssh-able 
5. scp the .deb file from #3 to root@router:/root/name_of_file.deb
6. ssh into your UDM, confirm the .deb is there
7. sudo dpkg -i the full name of the .deb
8. Mine installed like a champ

**Comment by tc60045** [comment]
Why not just wget or curl the file in 3 above directly to the UDM?   I couldn't get that to work, frankly.  I believe the file was getting truncated, as it repeatedly threw errors when trying to install via dpkg, so I decided to try local download + scp, and it worked.

**Comment by BlackJoker90** [comment]
@tc60045 Thank you for your detailed instructions. I was able to follow your steps and successfully install the software on my UDM device. Your contribution to the community is greatly appreciated. Keep up the good work! Now everything is working again :)

**Comment by rs** [comment]
Can someone with the issue confirm this version does not have any of the `curl`, `wget` or `openssl` commands in the path? Showing the output of this would be helpful:

```
which curl wget openssl
echo $PATH
```

**Comment by tc60045** [comment]
@rs - here you go.  Never placed any of those in $path, personally.  

root@TC-UDM-Pro:~# which curl wget openssl
/usr/bin/curl
/usr/bin/wget
/usr/bin/openssl
root@TC-UDM-Pro:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@TC-UDM-Pro:~#

**Comment by tc60045** [comment]
> Nevermind, just realized I was meant to re-run `sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`

@altShiftDev -- when you install the package with sudo, it is installed but it is a little confusing:
- if you then type: nextdns status you get "not installed" (!!!!!!)
- but if you then type: sudo nextdns status you get "running"

I did not need to reinstall or run the script -- didn't try it, actually -- just because I happened to think, "OK, I'll try sudo and see what status comes back"

I mention this so Olivier @rs will see this and think about whether to mod the docs to emphasize sudo or change the perms to let nextdns report out status for non-sudo users.  Neither of those is easy.  And to let others understand what to expect after the work-around installation.

**Comment by rs** [comment]
Isn’t root the default and only user when connecting over ssh?

**Comment by tc60045** [comment]
> Isn’t root the default and only user when connecting over ssh?

Default, yes; only, I am not sure, but here's output substantiating the above:

root@TC-UDM-Pro: nextdns status
not installed
root@TC-UDM-Pro: sudo nextdns status
running

**Comment by rs** [comment]
The script is also installing via dpkg. I can’t repro this issue on a UDM SE.

**Comment by jimmystewpot** [comment]
Since the bump in UDM Pro's OS the ipset names have changed from `UBIOS6ADDRv6_br0` to `UBIOS6NETv6_br0` this change means that the UDM Pros ip6table won't match the address range to dst nat it to the correct nextdns service. Once this was added nextdns started working for me again.

**Comment by rs** [comment]
Should be fixed by [5e0087b](https://github.com/nextdns/nextdns/commit/5e0087b970af3c31c2a062a77146c59c99f38d17). Please reopen if not.
