### ISSUE TITLE
CLI shows wifi extender name even though static leases are set

### ISSUE THREAD

**Issue by LoneWolff7** [nextdns/nextdns#855]
Hostnames for devices connected to WiFi extender not showing up 
 - CLI Version: 1.39.4 
 - Platform: OpenWrt

All the devices connected to my WiFi extender don’t get device names in the log and shows up as coming from the extender itself. Even though I’ve setup static leases for them in main router. 

If I disable mdns, it keeps interchanging from WiFi extender to actual device name every few seconds on the test.nextdns.io website. 

My CLI config: 

nextdns config
profile xx:xx:xx:xx:xx:xx=config1
profile xx:xx:xx:xx:xx:xx=config1
profile xx:xx:xx:xx:xx:xx=config1
profile xx:xx:xx:xx:xx:xx=config1
profile xx:xx:xx:xx:xx:xx=config1
profile xx:xx:xx:xx:xx:xx=config1
profile xx:xx:xx:xx:xx:xx=config1
profile xx:xx:xx:xx:xx:xx=config1
profile xx:xx:xx:xx:xx:xx=config1
profile config2
log-queries false
cache-max-age 0s
bogus-priv true
auto-activate false
control /var/run/nextdns.sock
report-client-info true
mdns disabled
detect-captive-portals false
use-hosts true
max-inflight-requests 256
setup-router false
cache-size 10MB
discovery-dns 192.168.1.1
timeout 5s
listen 192.168.1.1:5342
listen localhost:53
max-ttl 5s
hardened-privacy false
debug false

**Comment by rs** [comment]
You would have to setup the extenders in bridge mode of the individual clients behind it to be visible.

**Comment by LoneWolff7** [comment]
> You would have to setup the extenders in bridge mode of the individual clients behind it to be visible.

Hey @rs
