### ISSUE TITLE
enhance forwarder to pass client info in URL

### ISSUE THREAD

**Issue by coltonshipley** [nextdns/nextdns#856]
So I'm using the nextdns cli on a UDM Pro, I have a forwader setup to go to an instance of adguard home. 

The forwarder is setup to go to https://dns.domain.tld/dns-query

Could you please add clientid to the end of the url? I think nextdnsCLI only passes it in a header. 

ReportClientInfo is set to true. I would hope like to be able to forward to https://dns.domain.tld/dns-query/client or something like that.

**Comment by rs** [comment]
The format of those info are only relevant to NextDNS. That would not work.

**Comment by coltonshipley** [comment]
All that would be needed would be the client name that you already grab for your stuff.

so like https://dns.domain.tld/dns-query/bobs-iphone-12-pro-max
