### ISSUE TITLE
Don't exclusively bind the mDNS broadcast listen port

### ISSUE THREAD

**Issue by brokeh** [nextdns/nextdns#859]
I'd like to make use of the `report-client-info` setting to include my internal client hostnames in logs where my pfSense router is the DNS resolver for my network, however, enabling that option exclusively binds to port UDP/5353 for the mDNS listener which then breaks my Avahi mDNS forwarder which wants to bind to the same port.

This should be done by setting the `SO_REUSEADDR` option before binding to the socket. See https://linux.die.net/man/3/setsockopt#:~:text=a%20Boolean%20option.-,SO_REUSEADDR,-Specifies%20that%20the

I think the relevant place to set this would be the `net.ListenMulticastUDP` in https://github.com/nextdns/nextdns/blob/16105833448871fa8f82ca147814bdb06255f021/discovery/mdns.go#L78-L85 but from what I can tell from [the documentation](https://pkg.go.dev/net#ListenMulticastUDP) it is not possible to set socket options when using this method.

**Comment by rs** [comment]
It does not seem to be easily doable with Go. I'm not sure it would work correctly anyway.
