### ISSUE TITLE
NextDNS randomly erroring on unifyOS (UDM pro)

### ISSUE THREAD

**Issue by Material-Design** [nextdns/nextdns#861]
UDM pro: v3.1.16
NextDNS CLI: 1.39.4

DNS settings within GUI on UDM are set to ‘auto’ before NextDNS install.

On a clean install of unifyOS using the NextDNS installer command in sudo, the installation runs fine and installs successfully. All functions work as expected.

Installed using: 
 `sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`

Status shows NextDNS running.

However, at some undetermined point where no restarts have occurred nor any GUI / CLI changes have happened. NextDNS begins to misbehave only with UDM’s own traffic.

All other clients routing traffic through UDM seem unaffected and resolve DNS queries with NextDNS without issue.

Within SSH, the ping command fails:

```
root@xxxxxx:~# ping google.com
ping: google.com: Temporary failure in name resolution
```

However, I'm still able to ping outbound IPs just fine.

```
root@xxxxxx:~# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=61 time=6.01 ms
```

Checking the status of NextDNS states it is running.

```
root@xxxxxx:~# nextdns status
running
```

NextDNS log shows no stand-out errors apart from a lot of 'use of closed network connection' logs:

```
Sep 04 12:52:33 xxxxxx nextdns[32774]: Query 192.168.2.219 TCP 65 accounts.google.com. (qry=37/res=87) 21ms HTTP/2.0: write tcp 127.0.0.1:5553->192.168.2.219:15391: use of closed network connection
Sep 04 12:52:58 xxxxxx nextdns[32774]: Query 192.168.2.219 TCP 65 www.gstatic.com. (qry=33/res=90) 25ms HTTP/2.0: write tcp 127.0.0.1:5553->192.168.2.219:15419: use of closed network connection
Sep 04 12:53:22 xxxxxx nextdns[32774]: Query 192.168.2.219 TCP 65 xxxxxx-ats.iot.us-west-2.amazonaws.com. (qry=64/res=142) 10ms HTTP/2.0: write tcp 127.0.0.1:5553->192.168.2.219:15453: use of closed network connection
```

NextDNS config:

```root@xxxxxx:~# nextdns config
setup-router true
auto-activate true
max-inflight-requests 256
cache-max-age 0s
report-client-info true
discovery-dns
mdns all
use-hosts true
profile xxxxxx
cache-size 10MB
log-queries false
max-ttl 5s
detect-captive-portals false
bogus-priv true
timeout 5s
debug false
hardened-privacy false
listen localhost:53
control /var/run/nextdns.sock
```

A restart does not fix this and the only way I have found to make it work as expected is to uninstall, restart then reinstall NextDNS CLI. This however does not last longer than a day before breaking again.

Symptoms of this issue include not being able to access UDM remotely, UDM thinking there is no internet due to ping failures and speed tests within UDM failing.

**Comment by mikeburgh** [comment]
I had something similar after testing controld and finding it did not remove it self correctly.. temp solution I used till I figured out if was controld not being properly uninstalled was to change /etc/resolv.conf to use 8.8.8.8 for it's nameserver

**Comment by o42o** [comment]
To make sure that NextDNS is used in all cases, I set the V4 IP addresses in the DNS settings rather than on `auto`. This way, if NextDNS stops working properly, NextDNS will still receive all requests.

I've also linked the IP address with NextDNS so that it can work properly.

**Comment by rs** [comment]
Please tell us if you can repro with 1.40.1

**Comment by Material-Design** [comment]
> I had something similar after testing controld and finding it did not remove it self correctly.. temp solution I used till I figured out if was controld not being properly uninstalled was to change /etc/resolv.conf to use 8.8.8.8 for it's nameserver

Yes, this workaround works for me too.

**Comment by Material-Design** [comment]
> Please tell us if you can repro with 1.40.1

Just done that now, will let you know in a few days if it errors out. Thanks.

**Comment by charlestephen** [comment]
Can confirm this also happens on the older USG-Pro4 with the same and started around the same time.

**Comment by Material-Design** [comment]
> Please tell us if you can repro with 1.40.1

Been repo on 1.40.1 for the last two weeks and can confirm no random DNS errors as discussed above. Can anyone else confirm?

**Comment by oneguynick** [comment]
I have not seen the issues on my side either since the upgrade.
