### ISSUE TITLE
NextDNS no longer working as of 1.40.1 on UnifiOS

### ISSUE THREAD

**Issue by muness** [nextdns/nextdns#865]
**Context**
 - CLI Version: 1.40.1
 - Platform: UniFi OS 3.1.16 running on UDM Pro

I updated to 1.40.1 using the install shell command. Now when I check my DNS server at https://my.nextdns.io/ it no longer shows up as using NextDNS. `nextdns log` shows that it is running:

```
Sep 15 20:18:45 217UDMPro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Sep 15 20:18:45 217UDMPro nextdns[4087071]: Starting NextDNS 1.40.1/linux on localhost:5342
Sep 15 20:18:45 217UDMPro nextdns[4087071]: Listening on TCP/[::1]:5342
Sep 15 20:18:45 217UDMPro nextdns[4087071]: Listening on UDP/127.0.0.1:5342
Sep 15 20:18:45 217UDMPro nextdns[4087071]: Listening on TCP/127.0.0.1:5342
Sep 15 20:18:45 217UDMPro nextdns[4087071]: Listening on UDP/[::1]:5342
Sep 15 20:18:45 217UDMPro nextdns[4087071]: Starting mDNS discovery
Sep 15 20:18:50 217UDMPro nextdns[4087071]: Setting up router
Sep 15 20:18:53 217UDMPro nextdns[4087071]: Connected 45.90.28.0:443 (con=22ms tls=56ms, TCP, TLS13)
Sep 15 20:18:53 217UDMPro nextdns[4087071]: Connected 74.118.138.167:443 (con=35ms tls=53ms, TCP, TLS13)
Sep 15 20:18:53 217UDMPro nextdns[4087071]: Switching endpoint: https://dns.nextdns.io#23.83.133.96,74.118.138.167
```

I stripped down my config to only specify the basics, (i.e. just my profile), restarted, and that didn't help:
```
control /var/run/nextdns.sock
cache-max-age 0s
max-ttl 5s
report-client-info true
use-hosts true
timeout 5s
debug false
profile <my default profile id>
hardened-privacy false
bogus-priv true
detect-captive-portals false
setup-router true
auto-activate true
listen localhost:53
log-queries false
cache-size 10MB
discovery-dns
mdns all
max-inflight-requests 256
```

I've tried uninstalling / reinstalling multiple times, all to no avail. Any ideas of what I can do to debug this further?

**Comment by rs** [comment]
what do you get for `cat /run/dnsmasq.conf.d/nextdns.conf`

**Comment by muness** [comment]
BTW, I I installed 1.39.4 and it's working again:
```
curl -OL https://github.com/nextdns/nextdns/releases/download/v1.39.4/nextdns_1.39.4_linux_arm64.deb
cp nextdns_1.39.4_linux_arm64.deb /persistent/dpkg/bullseye/packages/
apt install /persistent/dpkg/bullseye/packages/nextdns_1.39.4_linux_arm64.deb
nextdns stop
nextdns start
```

**Comment by muness** [comment]
> what do you get for `cat /run/dnsmasq.conf.d/nextdns.conf`

I upgraded back to 1.40.1 and this is what I get when I run `cat /run/dnsmasq.conf.d/nextdns.conf`

```
# Configuration generated by NextDNS
no-resolv
server=127.0.0.1#5342
add-mac
add-subnet=32,128
max-cache-ttl=0
```

**Comment by rs** [comment]
What do you get for `curl -L https://test.nextdns.io` from the router?

**Comment by muness** [comment]
> What do you get for `curl -L https://test.nextdns.io` from the router?

From the UDM Pro router:
```
{
        "status": "ok",
        "protocol": "DOH",
        "profile": "fp1abf30d134af826f",
        "client": "24.165.105.56",
        "srcIP": "24.165.105.56",
        "destIP": "74.118.138.167",
        "anycast": false,
        "server": "teraswitch-pit-1",
        "clientName": "nextdns-cli",
        "deviceName": "217UDMPro",
        "deviceID": "73FB7",
        "deviceIP": "127.0.0.1"
}
```

From a device on the network (my Windows PC and an Ubuntu VM):
```
# curl -L https://test.nextdns.io
{
        "status": "unconfigured",
        "resolver": "104.207.143.71",
        "srcIP": "24.165.105.56",
        "server": "vultr-chi-1"
}
```

**Comment by rs** [comment]
Did you enable the DNS filter feature of the UDM?

**Comment by muness** [comment]
> Did you enable the DNS filter feature of the UDM?

Thank you, disabling that worked. I didn't realize that the Content filtering worked at the DNS level as Unifi describe it that way.

In case anyone else has this issue: I had [Content filtering](https://help.ui.com/hc/en-us/articles/12568927589143-UniFi-Gateway-Content-Filtering) turned on for my networks as a backstop for when NextDNS stopped working (this happened sporadically and after UnifiOS updates). This didn't conflict with previous versions but must no longer work as of 1.40 with the move away from iptables.
