### ISSUE TITLE
Conditional Profiles for Interfaces

### ISSUE THREAD

**Issue by jimvajda** [nextdns/nextdns#866]
Conditional profiles only apply to ipv4 traffic, so all ipv6 traffic gets the default profile. This is a problem for dual-stack networks, because a host's ipv4 traffic may get assigned a different profile than its ipv6 traffic.

To address this, conditional profiles could be assigned by ipv6 prefix, or a by incoming interface to catch both ipv4/v6 in a single profile rule. Assigning profiles by interface would also catch prefix changes from DHCP-PD.

**Comment by rs** [comment]
What make you think it does only apply to ipv4?

**Comment by jimvajda** [comment]
Thanks for the fast response! My assumption was based on the config options only showing ipv4. Is this incorrect?

**Comment by jimvajda** [comment]
So I tested an ipv6 prefix and it looks like it works, I guess I should have done that first. I would still prefer to have universal rules based on incoming interface. The use case is for networks with DHCP-PD prefixes from an ISP which can change routinely.

**Comment by rs** [comment]
Added to the master, please test and validate it is working: https://snapshot.nextdns.io/master/index.html

**Comment by jimvajda** [comment]
Thank you for addressing this so quickly!

On my UDM-Pro, I installed the snapshot, removed the existing IP-based profile rules from the config, and added these lines (profiles removed). Now all DNS is going to the default profile unfortunately. No DNS traffic appears to be going to the interface assigned profiles.

profile br2=xxxxxx
profile br3=yyyyyy
profile br4=zzzzzz
profile aaaaaa

**Comment by rs** [comment]
Can you please enable query log and post some logs that should match one of those rules?

**Comment by jimvajda** [comment]
Sep 16 18:29:28 home-udmp nextdns[3854238]: Query 192.168.3.11 UDP A cloudservices.roku.com. eecbxx (qry=73/res=91) 23ms HTTP/2.0
Sep 16 18:29:28 home-udmp nextdns[3854238]: Query 1234:1234:1234:1802:1478:e194:e992:9354 UDP A cloudservices.roku.com. eecbxx (qry=85/res=91) 25ms HTTP/2.0
Sep 16 18:29:28 home-udmp nextdns[3854238]: Query 1234:1234:1234:1802:1478:e194:e992:9354 UDP A scribe.logs.roku.com. eecbxx (qry=83/res=89) 22ms HTTP/2.0
Sep 16 18:29:28 home-udmp nextdns[3854238]: Query 192.168.1.12 UDP A p2p2-usa.aqara.com. eecbxx (qry=69/res=63) 243ms HTTP/2.0
Sep 16 18:29:28 home-udmp nextdns[3854238]: Query 192.168.1.12 UDP A p2p3-usa.aqara.com. eecbxx (qry=69/res=63) 244ms HTTP/2.0

Each of these three addresses use a different incoming interface, so they should show different profiles.
