### ISSUE TITLE
listen tcp 127.0.0.1:53: bind: address already in use

### ISSUE THREAD

**Issue by chocobopie** [nextdns/nextdns#868]
Im trying to install NextDns CLI on my ASUS RT-AX82 Merlin firmware, when i try to Nextdns run it shows this error. Do i need to disable or delete dnsmasq to get Nextdns to work ?
 
![image](https://github.com/nextdns/nextdns/assets/26004529/bb731e29-d173-4171-a741-35a407e259bd)

![image](https://github.com/nextdns/nextdns/assets/26004529/ee3e0a18-2149-4da8-beff-1efd6e168405)

**Comment by rs** [comment]
Do you have `setup-router` correctly set to `true`?

**Comment by chocobopie** [comment]
> Do you have `setup-router` correctly set to `true`?

Yes i do

![image](https://github.com/nextdns/nextdns/assets/26004529/82914919-0030-41a8-97c2-1bb1e15ef3b6)

**Comment by chocobopie** [comment]
Just factory reset to install NextDns CLI and still doesnt work

**Comment by clemente3905** [comment]
I have the exact same issue on a Synology NAS on which dnsmasq is listening on port 53. Any solution?
Is it safe to disable dnsmasq? How do I do it eventually?

**Comment by RouterCFW** [comment]
It appears to be a problem with the NextDNS and ControlD router apps. I encountered this issue with NextDNS, and the solution is to stop NextDNS, wait for DNSmasq to start, and then restart NextDNS.
