### ISSUE TITLE
Automatic whitelist/blacklist asterisk prefix breaking added rules

### ISSUE THREAD

**Issue by RejZoRSheep** [nextdns/nextdns#87]
I've noticed that placing any address to whitelist or blacklist automatically prepends asterisk with a dot.

For example, if you add "google.com" it'll add entry as "*.google.com" and matches all subdomains with it, like "maps.google.com". Which is fine.

Problem happens when you enter a full precise domain, like "maps.google.com". It seems to prepend asterisk with a dot anyway for some reason, making it look like "*.maps.google.com". Which ultimately means such rule will never match with anything because the address is https://maps.google.com, having no dot before maps in the actual address. Is this just a cosmetic thing in the frontend (what user sees) and the matching engine still correctly whitelists or blacklists maps.google.com or does it get missed because of it?

**Comment by rs** [comment]
The `*.` is in grey to show that the domain itself as well as all its sub-domains are whitelisted. So in you example `maps.google.com` will be whitelisted as well as `anything.maps.google.com`.

**Comment by rs** [comment]
Closing this, as this repo is for the nextdns cli client, not general service questions. Please contact support or open a topic on our reddit for further discussion on this topic.
