### ISSUE TITLE
add force dns server in openwrt

### ISSUE THREAD

**Issue by vijayrajah** [nextdns/nextdns#870]
**Context**

I'm running nextdns on openwrt on x86

here is myconfig
```
# nextdns config
listen localhost:53
profile xxxxx
cache-max-age 0s
discovery-dns
detect-captive-portals false
timeout 5s
log-queries false
cache-size 100MB
mdns all
bogus-priv true
use-hosts true
debug false
control /var/run/nextdns.sock
max-ttl 0s
report-client-info true
hardened-privacy false
max-inflight-requests 256
setup-router true
auto-activate false

```

All works well, but DHCP( Bootp) wasn't giving out DNS server via BOOTP (option 6)

I had to force it from LUCI.. network >> interfaces >> edit br-lan >> DHCP Server >> Advanced >> DHCP-Options

and add
`6,192.168.50.1` (50.1 is my router's IP)

![image](https://github.com/nextdns/nextdns/assets/4451012/87a944e1-456d-416f-b903-2945c3f8fa6d)

This will add a config entry in `/etc/config/dhcp` under  `config dhcp 'lan'` 
```
config dhcp 'lan'
        option interface 'lan'
        option start '100'
        option limit '150'
        option leasetime '12h'
        option dhcpv4 'server'
        option force '1'
        list dhcp_option '6,192.168.50.1'

```

can we make the https://github.com/nextdns/nextdns/blob/7da8f4c0657f1f23f16fa8258fd8108bf8ee8a76/router/openwrt/setup.go#L52 to automatically add this line?

**Comment by rs** [comment]
I'm surprise this is not the default on OpenWRT. When this is not set, what DNS is advertised?

**Comment by vijayrajah** [comment]
> I'm surprised this is not the default on OpenWRT. When this is not set, what DNS is advertised?

I did a tcpdump, I did not see any DHCP option 6 (DNS) in response. so my android clients used 8.8.8.8. (that's how I found it & I saw lot of ads on my mobile :) )

i'm running rc version 
`OpenWrt 23.05.0-rc3 r23389-5deed175a5 / LuCI openwrt-23.05 branch git-23.219.80063-bece581`

maybe something changed ?

**Comment by pandrani** [comment]
I observed the same behaviour as the OP. It seems to only occur for me when caching is turned on. For some reason that stops the DNS from being sent by the OpenWRT router in the DHCP handshake. Really weird!
