### ISSUE TITLE
buggy upgrade script

### ISSUE THREAD

**Issue by goodale** [nextdns/nextdns#874]
Upgrade script doesn't work.   It recognizes there's a new version but selecting 'u' to upgrade just eventually says you are already running the latest version (a minor version back) and asks if you want to upgrade again.   If the reason is that the repo pkg is out of date then the script should also update the repo package, etc.

/etc/apt/sources.list.d$ sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: ubuntu
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.40.1
u) Upgrade NextDNS from 1.39.4 to 1.40.1
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease                                                                                                                                                
Hit:3 https://artifacts.elastic.co/packages/7.x/apt stable InRelease                                                                                                                                            
Hit:4 https://download.newrelic.com/infrastructure_agent/linux/apt focal InRelease                                                                                                                              
Get:5 https://deb.nodesource.com/node_16.x focal InRelease [4,583 B]                                                                                                                                     
Hit:6 http://us.archive.ubuntu.com/ubuntu focal InRelease                                                                                           
Hit:7 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease                                               
Hit:8 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease                           
Hit:10 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease                        
Hit:9 https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu focal InRelease                                               
Hit:12 https://packages.gitlab.com/runner/gitlab-runner/ubuntu focal InRelease
Hit:11 https://packagecloud.io/ookla/speedtest-cli/ubuntu focal InRelease
Fetched 4,583 B in 2s (2,872 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nextdns is already the newest version (1.39.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
u) Upgrade NextDNS from 1.39.4 to 1.40.1
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u):

**Comment by rs** [comment]
Does it still happen?

**Comment by mvicari** [comment]
This is happening to me also:

```
root@Dream-Router:~# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.43.4
u) Upgrade NextDNS from 1.43.3 to 1.43.4
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
Hit:1 https://security.debian.org/debian-security bullseye-security InRelease
Hit:2 https://deb.debian.org/debian bullseye InRelease
Hit:3 https://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://deb.debian.org/debian bullseye-backports InRelease
Hit:5 https://repo.nextdns.io/deb stable InRelease
Hit:6 https://apt.artifacts.ui.com bullseye InRelease
Hit:7 https://apt-release-candidate.artifacts.ui.com bullseye InRelease
Hit:8 https://apt-beta.artifacts.ui.com bullseye InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nextdns is already the newest version (1.43.3).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
u) Upgrade NextDNS from 1.43.3 to 1.43.4
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u):
```

**Comment by rs** [comment]
It always happens for some time after a new version. Try again, it should be fine now.
