### ISSUE TITLE
ECH (Encrypted Client Hello) Support

### ISSUE THREAD

**Issue by Medi223** [nextdns/nextdns#878]
Hello, this is a request to enable/add support for ECH in NextDNS CLI. Firefox recently added ECH in version 118 when using a DoH connection by default. After enabling **network.dns.echconfig.enabled** in about:config these two [test](https://tls-ech.dev/) [sites](https://www.cloudflare.com/en-au/ssl/encrypted-sni/#results) indicate ECH works with NextDNS.

I see no method or indication to enable ECH via NextDNS CLI for a system-wide implementation, nor an option to enable it via my.nextdns.io at present. Thanks in advance, and apologies if I've simply missed something and ECH is already working.

**Comment by rs** [comment]
You want ECH for the dns.nextdns.io domain when connecting with DoH or you mean something else?

**Comment by Medi223** [comment]
I want NextDNS CLI to use ECH+DoH for all domains my device connects with. ECH seems to only work through Firefox, which can be detected via the third-party services mentioned above or **[this](https://defo.ie/ech-check.php)** and **[this](https://crypto.cloudflare.com/cdn-cgi/trace)**. Using just NextDNS CLI as my system resolver does not enable ECH as far as I'm aware. Reference image: https://i.imgur.com/d5CATFr.png

**Comment by rs** [comment]
ECH has to be supported by the client (Firefox in your case) and the web server you are trying to reach. DNS is used in the process but the resolver (NextDNS here) does not have to support ECH specifically other than by being a DNSSEC aware resolver. This is all already in place so there is nothing more to do on NextDNS side to enable ECH. ECH adoption on web servers will be progressive and out of our control.

**Comment by rs** [comment]
BTW, the issue you are reporting is related to this https://bugzilla.mozilla.org/show_bug.cgi?id=1500289

**Comment by Medi223** [comment]
Necroing to mention Firefox 129.0 now supports using the OS DNS resolver with ECH (https://www.mozilla.org/en-US/firefox/129.0/releasenotes/)

> - HTTPS DNS records can now be resolved with the operating system's DNS resolver on specific platforms (Windows 11, Linux, Android 10+). Previously this required [DNS over HTTPS](https://support.mozilla.org/kb/firefox-dns-over-https) to be enabled. This capability allows the use of HTTP/3 without needing to use the [Alt-Svc](https://developer.mozilla.org/docs/Web/HTTP/Headers/Alt-Svc) header, upgrades requests to HTTPS when the DNS record is present, and enables wider use of [ECH](https://support.mozilla.org/kb/faq-encrypted-client-hello).
> - Added support for DNS lookup of [HTTPS Resource Records (RR)](https://datatracker.ietf.org/doc/rfc9460/) with the native DNS resolver, increasing HTTPS coverage and facilitating the use of [Encrypted Client Hello (ECH)](https://datatracker.ietf.org/doc/draft-ietf-tls-esni/) if present in HTTPS RR.
