### ISSUE TITLE
Add OpenNIC / Namecoin / Emercoin TLD (Optional configurable function)

### ISSUE THREAD

**Issue by wuniversales** [nextdns/nextdns#88]

**Comment by IceCodeNew** [comment]
May I ask why this issue is closed? I can't find a PR, or any changelog refers to an implementation of OpenNIC support.

**Comment by rs** [comment]
This is a feature request for the nextdns service. This repository is about the cli client. Please discuss nextdns feature request on reddit (r/nextdns). Note that Handshake is already implemented
