### ISSUE TITLE
DoH3 protocol on Adguard iOS

### ISSUE THREAD

**Issue by Domsicols** [nextdns/nextdns#880]
**Context**
 - CLI Version:78.148.214.88
 - Platform:iOS

&lt;Describe the bug>Adguard for iOS recently announced that they now support HTTP/3 but upon testing with the use of DoH3 using the Nextdns, There is a Constant drop of internet. And I can confirm that Doh3 protocol is working since whenever I check for the test page for NextDNS , it says DoH3. Any work around with this?![image](https://github.com/nextdns/nextdns/assets/104392824/4688dc31-ad62-4da2-88dd-6d5bebef4818)

**Comment by rs** [comment]
Did you use doh3.dns.nextdns.io hostname?

**Comment by Domsicols** [comment]
> Did you use doh3.dns.nextdns.io hostname?

Yes, I am using h3://doh3.dns.nextdns.io/xxxx. I have also raised this to the adguard first but seems they cant find any problem on their end thats why it may be possible that it is on NextDNS.
