### ISSUE TITLE
VyOS init script is out of date

### ISSUE THREAD

**Issue by patrickli** [nextdns/nextdns#885]
**Context**
 - CLI Version: 1.41.0
 - Platform: VyOS 1.3+

VyOS is similar to EdgeOS in terms of the configuration interface, but they differ quite a lot in the underlaying components. For example VyOS uses `systemd` and the hook scripts locations are different (https://docs.vyos.io/en/equuleus/automation/command-scripting.html).

I think we should separate the two and create a proper configuration for VyOS.

**Comment by rs** [comment]
Would you be willing to contribute by submitting a pull request?

**Comment by rs** [comment]
Thanks @Giggum for the attempt. Could you make it a draft PR so we can easily discuss on the code itself?

**Comment by Giggum** [comment]
Draft PR is here https://github.com/nextdns/nextdns/pull/920

I will look at your suggestion.
