### ISSUE TITLE
Support for Unifi Gateway Lite

### ISSUE THREAD

**Issue by jdloft** [nextdns/nextdns#889]
New UI Gateway dropped and the CLI doesn't seem to detect it as a Unifi device. Looks like the client currently looks for the `/data/unifi` path ([relevant line](https://github.com/nextdns/nextdns/blob/master/router/ubios/setup.go#L21)) but on my device I have:
```
# ls /data/
dpi-tracer/  udapi-config/  ui-db/  uxgpro-setup/  wifiman/
```

However, the CLI does install correctly, but conflicts with the `dnsmasq` on port 53 from `ubios-udapi-server`. Are there any plans to support this device?

Update: Looks like I only needed to create the dir `/data/unifi` and everything worked.

**Comment by itislp** [comment]
I too am looking for this type of support. I was able to successfully install on the UXG-Lite running latest firmware but get an error "stuck in a failed state" upon status check.

Do you know if your workaround will persist across firmware updates? Thanks for posting this info, I am going to give it a try today to see if I can get it working as well.

**Comment by nxion** [comment]
@rs That command returns
```
3.1.15
```

**Comment by ralban** [comment]
+1 for UXG-Lite support.
3.1.16 was just released.

**Comment by bwestrek** [comment]
For me it works also by creating first the folder /data/unifi and running the install script. So it looks like in the script needs small adjustment that it creates the folder /data/unifi first then the rest of the script.

**Comment by rs** [comment]
Please try this snapshot to confirm it works as expected: 

```
NEXTDNS_VERSION=pr-899/SNAPSHOT-efee3d1 sh -c 'sh -c "$(curl -sL https://raw.githubusercontent.com/nextdns/nextdns/f106407bc9a8ee0c6f1c2917bedb246a8b16013b/install.sh)"'
```

**Comment by ralban** [comment]
I uninstalled my previous instance and installed this snapshot.  It installed in the folder I was in when I ran the script (/data) and picked-up on my previous nextdns.conf. Should it be in a child folder (/data/nextdns)?
It did not survive when I went from 3.1.15 to 3.1.16 with the previous stable build. I am already on 3.1.16 so I won't be able to test survivability until they release the next upgrade.
![image](https://github.com/nextdns/nextdns/assets/52607152/74a4db91-d7a9-40fa-b2a2-c15db30564a4)

**Comment by rs** [comment]
It should install the binary via the deb package with the config in the /data directory. Isn’t it what happened?

**Comment by wprivera** [comment]
Unifi UXG Pro UniFi OS v3.2.7
Initial install does not work. Traffic by device name is not listed in the NextDNS logs. I manually created the /data/unifi folders, and re-ran the install script. Still does not work.  Any update on a fix?

**Comment by wprivera** [comment]
The poster "RS" is Olivier Poitrey. He is the Co-Founder of NextDNS. He is actively working on a fix. Maybe follow him, for when he posts an update. He posted the following in "Add support for UXG series of Unifi product #899"

> You did not test the snapshot. Please make sure to copy the whole command:
> 
> ```
> NEXTDNS_VERSION=pr-899/SNAPSHOT-efee3d1 sh -c 'sh -c "$(curl -sL https://raw.githubusercontent.com/nextdns/nextdns/f106407bc9a8ee0c6f1c2917bedb246a8b16013b/install.sh)"'
> ```

It did not work for me, but that is what he instructed. It is an unreleased test version. I'm sure he'll post an update soon.

**Comment by modxmv** [comment]
I ran the test snapshot and it appears to be working

`root@UXG-Lite:/# NEXTDNS_VERSION=pr-899/SNAPSHOT-efee3d1 sh -c 'sh -c "$(curl -sL https://raw.githubusercontent.com/nextdns/nextdns/f106407bc9a8ee0c6f1c2917bedb246a8b16013b/install.sh)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: pr-899/SNAPSHOT-efee3d1
u) Upgrade NextDNS from 1.41.0 to pr-899/SNAPSHOT-efee3d1
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
NextDNS installed and started using ubios init
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c):
NextDNS Profile ID: 36f557
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: y
Make NextDNS CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Note that enabling this feature will disable dnsmasq for DNS to avoid double
caching.
Enable caching? (y/n): y
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on your LAN hosts without having to wait for their cache to expire.
Enable instant refresh? (y/n): y
NextDNS installed and started using ubios init
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): e
root@UXG-Lite:/#
root@UXG-Lite:/#
root@UXG-Lite:/# nextdns status
running
root@UXG-Lite:/#
`
![image](https://github.com/nextdns/nextdns/assets/29495359/aecb66fd-e06b-49d7-9913-be88d36dbffd)
