### ISSUE TITLE
Option to flush DNS Cache

### ISSUE THREAD

**Issue by spignelon** [nextdns/nextdns#890]
It often happens that we have to unblock blocked domain or block an unblocked domain, mainly due to issues with hosts blocklists under privacy or allowlist/denylist.

The ability to flush DNS cache by using a command like `nextdns flush` would enable an easy propagation of newly changed settings without needing to reboot the PC

**Comment by rs** [comment]
The cache is already automatically flushed when the profile is changed.

**Comment by spignelon** [comment]
> The cache is already automatically flushed when the profile is changed.

Thank you, closing the issue
