### ISSUE TITLE
Installation on DDWRT if curl not found?

### ISSUE THREAD

**Issue by coolandsmartrr** [nextdns/nextdns#892]
**Context**
 - CLI Version: 
 - Platform: DD-WRT v3.0-r44715 std (11/03/20)

&lt;Describe the bug>
I'm follwing the installation steps [here](https://github.com/nextdns/nextdns/wiki/DDWRT). While I've followed the prior steps, it looks like `curl` is not installed on my distro:

```
BusyBox v1.32.0 (2020-11-03 08:53:55 +03) built-in shell (ash)

root@TP-LINK_XXXX_5G:~# sh -c "$(curl -sL https://nextdns.io/install)"
-sh: curl: not found
```

How should I run the installer? What should I do in this case?

**Comment by Mile-Lile** [comment]
you have very old build from 2020... update ddwrt... verify if you have wget-ssl installed... if not try with:

`sh -c "$(wget http://nextdns.io/install)"`

note: download of binaries wont be encrypted

or you need unit with bigger flashsize... curl and wget-ssl are not included in routers with 4MB flashsize... not sure if 8MB unit have it...

**Comment by Mile-Lile** [comment]
and this really is not nextdns bug...

**Comment by coolandsmartrr** [comment]
@Mile-Lile Thank you for your response. I understand that this was not a NextDNS bug and more of an issue with my environment, but I wasn't sure where to ask for help.
