### ISSUE TITLE
REQUEST: set subnet to have none NEXTDNS routing. exclude or profile = none

### ISSUE THREAD

**Issue by Dejmacro** [nextdns/nextdns#894]
In Conditional config setup It appears we can set differing NDNS profiles for a subnet or for all other subs, but what if i do not want to route DNS for a subnet through NEXTDNS at all? . 

IS it supported to have certain subnets excluded from NEXTDNS CLi?

**Comment by rs** [comment]
This can’t be controlled by the CLI itself but by how you configure your network/hosts.
