### ISSUE TITLE
Wrong ultralow for past 2 years

### ISSUE THREAD

**Issue by bubobih** [nextdns/nextdns#897]
- CLI Version: Latest
 - Platform: Asus merlin

Hello im using nextdns almost 2years on many places and i always get ultralow in middle of the list... i want to say that most closest nodes are never ultralow. For example zepto is 6ms and he is 6ms for a year or more but he never give ultralow. like he is here usualy only to be shown on the list and not usable... im using asus merlin nextdns script but i use on my work on opnsense you script with same result. 
![BCIcjz3](https://github.com/nextdns/nextdns/assets/21065487/982701ef-57f8-48fc-bce0-bf36795ad15a)

**Comment by rs** [comment]
Are you un Serbia?

**Comment by bubobih** [comment]
> Are you un Serbia?

Bosnia mtel

**Comment by rs** [comment]
It’s going for the closest geographically. It does not always translate to the lowest latency but 10ms difference is nothing.

**Comment by rs** [comment]
Unfortunately we can't make such exception as it would impact all users of your country/ISP. Again, 10ms is imperceptible, especially for DNS queries which are heavily cached. It should not impact your browsing speed.

**Comment by bubobih** [comment]
> Unfortunately we can't make such exception as it would impact all users of your country/ISP. Again, 10ms is imperceptible, especially for DNS queries which are heavily cached. It should not impact your browsing speed.

I understand one more question about this. Why all nodes are open for (ultralow) and my router will decide by ping. I mean your script should decide that. Im confused because from whole list only 2 are open and one anycast

**Comment by rs** [comment]
Ultralow steering is based on DNS steering, it is not based on ping.
