### ISSUE TITLE
UniFi native(-ish) DNSCrypt handling?

### ISSUE THREAD

**Issue by austin-meadows** [nextdns/nextdns#898]
Hey all,

UniFi routers such as the [Dream Machine SE](https://community.ui.com/releases/UniFi-OS-Dream-Machine-SE-3-2-7/6e5c8f0a-ab9e-45c6-acba-af2211dd5fa6) / [Dream Machine Pro](https://community.ui.com/releases/UniFi-OS-Dream-Machines-3-2-7/251dfc1e-f4dd-4264-a080-3be9d8b9e02b) have recently had a release allowing native DNS encryption (called "DNS Shield" by them).

Unfortunately, their implementation does not allow you to specify your own URL, so when selecting NextDNS (or one like it), you'll use NextDNS but without a profile.

I dug a little bit on the box via SSH, and it seems their implementation of DNS encryption is using [`dnscrypt-proxy`](https://github.com/DNSCrypt/dnscrypt-proxy). CLI commands and etc are available for this library.

I'm unsure exactly how the implementation for [NextDNS on Unifi](https://github.com/nextdns/nextdns/wiki/UnifiOS) works, but would it be possible to update NextDNS's installer to leverage the library available to us on the router? Or would this even make sense / be worth it, given the implementation? I would imagine this could simplify things and maybe have less overhead, but maybe the current implementation is not too much different in that regard haha.

I might could look into this myself but my skills in this regard are limited. I did try to specify my own HTTPS profile, but it seems `dnscrypt`'s configuration is generated by some UniFi service at `/run/dnscrypt-proxy.toml`. I have tried manually restarting the Linux service for DNSCrypt and specifying a modified configuration, but to no effect. I am very likely doing something wrong, but that is beyond the scope of the NextDNS script.

Thanks! :)

**Comment by rs** [comment]
You would lose most of the advanced features of CLI like LAN device info, dynamic profiles etc.

**Comment by supernovae** [comment]
Could we at least have the basic network association and rules apply? i don't need many of the advanced cli features :)

**Comment by rs** [comment]
That can’t work without the cli or a specific implementation in ubios which we have no control on.
