### ISSUE TITLE
UniFi UXG Pro Device Firmware Version 3.1.16 Failure Bug

### ISSUE THREAD

**Issue by macflyhub** [nextdns/nextdns#900]
Since the Ubiquiti UniFi UXG Device Firmware update to 3.1.16 there is a bug causing a failure with NextDNS on the UniFi UXG router.
(Note: this is not the same issue as UniFi OS 3.1.16 nor the UDM 3.1.16 which is not UXG device firmware version 3.1.16 - that issue was related to Content Filtering and not the DNS Shield with DM)
This updated happened around the 29th of Dec 2023 due to auto updates across multiple UniFi/UXG sites causing all of them to loose their NextDNS (Paid) protection. This was only noticed when people started to complain about being able to visit bad websites and seeing tons of adverts as it was using generic NextDNS not account allocated NextDNS connection.
Also it appears 3.1.16 came out around the 17th Dec 2023. https://community.ui.com/releases/UniFi-NeXt-Generation-Gateways-3-1-16/dba1a228-e24b-479f-919f-e37d9be9756d
The NextDNS log and analytics had not updated on the web overview page, confirming that it wasn't working.
Changing ISP IP also does not update anything. This bug might just be related to the IP linking.
Many people who have this installed may not even realise or those that have static IP's might not notice.

I have tried rebooting and reinstalling NextDNS on the UXG and that goes through without a failure but fails to actually work.

nextdns status = shows "running"

Update:
Even though I can't get the code to work. If I manually update the IP on the NextDNS website, the logs then show it is connected which means the DNS is passing over but there is just no IP update when the IP changes.

**Comment by macflyhub** [comment]
Also tried with this code update: https://github.com/nextdns/nextdns/issues/889
Here is the log and there is zero updates on the nextdns log showing its not communicating.

Linux UXGPro 4.19.152-ui-alpine #4.19.152 SMP Mon Dec 4 11:09:15 CST 2023 aarch6                                                                                                                                                                                                                                             4

Firmware version: v3.1.16

  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2023
 |   |  |   |  \  ||  \   |  |   Ubiquiti Inc.
 |______|___|  /__||__/   |__|
            |_/                  https://www.ui.com

      Welcome to UniFi NeXt-Gen Gateway Pro!

********************************* NOTICE **********************************
* By logging in to, accessing, or using any Ubiquiti product, you are     *
* signifying that you have read our Terms of Service (ToS) and End User   *
* License Agreement (EULA), understand their terms, and agree to be       *
* fully bound to them. The use of CLI (Command Line Interface) can        *
* potentially harm Ubiquiti devices and result in lost access to them and *
* their data. By proceeding, you acknowledge that the use of CLI to       *
* modify device(s) outside of their normal operational scope, or in any   *
* manner inconsistent with the ToS or EULA, will permanently and          *
* irrevocably void any applicable warranty.                               *
***************************************************************************
Last login: Fri Dec  1 13:02:48 2023 from 192.168.1.211
root@UXGPro:~# sh -c 'sh -c "$(curl -sL https://raw.githubusercontent.com/nextdn                                                                                                                                                                                                                                             s/nextdns/f106407bc9a8ee0c6f1c2917bedb246a8b16013b/install.sh)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.41.0
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
Reading package lists... Done
Building dependency tree... Done
apt-transport-https is already the newest version (2.2.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Get:1 https://security.debian.org/debian-security bullseye-security InRelease [4                                                                                                                                                                                                                                             8.4 kB]
Get:2 https://deb.debian.org/debian bullseye InRelease [116 kB]
Get:3 https://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 https://deb.debian.org/debian bullseye-backports InRelease [49.0 kB]
Get:5 https://security.debian.org/debian-security bullseye-security/main arm64 P                                                                                                                                                                                                                                             ackages [258 kB]
Get:6 https://deb.debian.org/debian bullseye/main arm64 Packages [7951 kB]
Get:7 https://deb.debian.org/debian bullseye/contrib arm64 Packages [40.8 kB]
Get:8 https://deb.debian.org/debian bullseye/non-free arm64 Packages [72.2 kB]
Get:9 https://deb.debian.org/debian bullseye-updates/main arm64 Packages [16.3 k                                                                                                                                                                                                                                             B]
Get:10 https://deb.debian.org/debian bullseye-backports/main arm64 Packages [398                                                                                                                                                                                                                                              kB]
Get:11 https://repo.nextdns.io/deb stable InRelease [8490 B]
Get:12 https://repo.nextdns.io/deb stable/main arm64 Packages [425 B]
Fetched 9004 kB in 3s (3418 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
Need to get 2964 kB of archives.
After this operation, 7143 kB of additional disk space will be used.
Get:1 https://repo.nextdns.io/deb stable/main arm64 nextdns arm64 1.41.0 [2964 k                                                                                                                                                                                                                                             B]
Fetched 2964 kB in 3s (921 kB/s)
Selecting previously unselected package nextdns.
(Reading database ... 24170 files and directories currently installed.)
Preparing to unpack .../nextdns_1.41.0_arm64.deb ...
Unpacking nextdns (1.41.0) ...
Setting up nextdns (1.41.0) ...
NextDNS installed and started using systemd init
NextDNS Profile ID (default=[removed]):
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: Y
Accept DNS request from other network hosts.
Setup as a router? [Y|n]: Y
Make NextDNS CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Enable caching? [Y|n]: Y
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on your LAN hosts without having to wait for their cache to expire.
Enable instant refresh? [Y|n]: Y
Changes DNS settings of the host automatically when NextDNS is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically setup local host DNS? [Y|n]: Y
NextDNS installed and started using systemd init
Error: systemctl start nextdns.service: signal: killed:

Congratulations! NextDNS is now installed.

To upgrade/uninstall, run this command again and select the appropriate option.

You can use the NextDNS command to control the daemon.
Here are a few important commands to know:

# Start, stop, restart the daemon:
nextdns start
nextdns stop
nextdns restart

# Configure the local host to point to NextDNS or not:
nextdns activate
nextdns deactivate

# Explore daemon logs:
nextdns log

# For more commands, use:
nextdns help

root@UXGPro:~# nextdns status
running
root@UXGPro:~# nextdns log
Dec 31 17:53:45 UXGPro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Dec 31 17:53:45 UXGPro nextdns[2896630]: Starting NextDNS 1.41.0/linux on :53
Dec 31 17:53:45 UXGPro nextdns[2896630]: Starting mDNS discovery
Dec 31 17:53:45 UXGPro nextdns[2896630]: Listening on TCP/:53
Dec 31 17:53:45 UXGPro nextdns[2896630]: Listening on UDP/:53
Dec 31 17:53:50 UXGPro nextdns[2896630]: Setting up generic router
Dec 31 17:53:50 UXGPro nextdns[2896630]: Activating
Dec 31 17:54:08 UXGPro nextdns[2896630]: Received signal: terminated
Dec 31 17:54:08 UXGPro nextdns[2896630]: Stopping NextDNS 1.41.0/linux
Dec 31 17:54:08 UXGPro systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: State 'stop-sigterm' timed out. Killing.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896630 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896632 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896633 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896635 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896639 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896640 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896641 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Main process exited, code=killed, status=9/KILL
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Failed with result 'timeout'.
Dec 31 17:55:38 UXGPro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Dec 31 17:55:38 UXGPro nextdns[2898432]: Starting NextDNS 1.41.0/linux on :53
Dec 31 17:55:38 UXGPro nextdns[2898432]: Listening on TCP/:53
Dec 31 17:55:38 UXGPro nextdns[2898432]: Starting mDNS discovery
Dec 31 17:55:38 UXGPro nextdns[2898432]: Listening on UDP/:53
Dec 31 17:55:43 UXGPro nextdns[2898432]: Setting up generic router
Dec 31 17:55:43 UXGPro nextdns[2898432]: Activating
root@UXGPro:~# nextdns start
root@UXGPro:~# nextdns restart

Error: systemctl restart nextdns.service: signal: killed:
root@UXGPro:~#
root@UXGPro:~# nextdns status
Error: unknown status:
root@UXGPro:~# nextdns start
Error: systemctl start nextdns.service: signal: killed:
root@UXGPro:~# nextdns status
running
root@UXGPro:~# nextdns activate
root@UXGPro:~# nextdns status
running
root@UXGPro:~# sh -c 'sh -c "$(curl -sL https://raw.githubusercontent.com/nextdns/nextdns/f106407bc9a8ee0c6f1c2917bedb246a8b16013b/install.sh)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.41.0
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): r
INFO: Uninstalling NextDNS...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  nextdns
0 upgraded, 0 newly installed, 1 to remove and 20 not upgraded.
After this operation, 7143 kB disk space will be freed.
(Reading database ... 24171 files and directories currently installed.)
Removing nextdns (1.41.0) ...
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.2.4).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Hit:1 https://security.debian.org/debian-security bullseye-security InRelease
Hit:2 https://deb.debian.org/debian bullseye InRelease
Hit:3 https://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://deb.debian.org/debian bullseye-backports InRelease
Hit:5 https://repo.nextdns.io/deb stable InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
Need to get 0 B/2964 kB of archives.
After this operation, 7143 kB of additional disk space will be used.
Selecting previously unselected package nextdns.
(Reading database ... 24170 files and directories currently installed.)
Preparing to unpack .../nextdns_1.41.0_arm64.deb ...
Unpacking nextdns (1.41.0) ...
Setting up nextdns (1.41.0) ...
NextDNS installed and started using systemd init
NextDNS Profile ID (default=[Removed]):
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: Y
Accept DNS request from other network hosts.
Setup as a router? [Y|n]: Y
Make NextDNS CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Enable caching? [Y|n]: Y
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on your LAN hosts without having to wait for their cache to expire.
Enable instant refresh? [Y|n]: Y
Changes DNS settings of the host automatically when NextDNS is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically setup local host DNS? [Y|n]: Y
NextDNS installed and started using systemd init
Error: systemctl start nextdns.service: signal: killed:

Congratulations! NextDNS is now installed.

To upgrade/uninstall, run this command again and select the appropriate option.

You can use the NextDNS command to control the daemon.
Here are a few important commands to know:

# Start, stop, restart the daemon:
nextdns start
nextdns stop
nextdns restart

# Configure the local host to point to NextDNS or not:
nextdns activate
nextdns deactivate

# Explore daemon logs:
nextdns log

# For more commands, use:
nextdns help

root@UXGPro:~# nextdns status
stopped
root@UXGPro:~# nextdns start
root@UXGPro:~# nextdns status
running
root@UXGPro:~# nextdns log
Dec 31 17:53:45 UXGPro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Dec 31 17:53:45 UXGPro nextdns[2896630]: Starting NextDNS 1.41.0/linux on :53
Dec 31 17:53:45 UXGPro nextdns[2896630]: Starting mDNS discovery
Dec 31 17:53:45 UXGPro nextdns[2896630]: Listening on TCP/:53
Dec 31 17:53:45 UXGPro nextdns[2896630]: Listening on UDP/:53
Dec 31 17:53:50 UXGPro nextdns[2896630]: Setting up generic router
Dec 31 17:53:50 UXGPro nextdns[2896630]: Activating
Dec 31 17:54:08 UXGPro nextdns[2896630]: Received signal: terminated
Dec 31 17:54:08 UXGPro nextdns[2896630]: Stopping NextDNS 1.41.0/linux
Dec 31 17:54:08 UXGPro systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: State 'stop-sigterm' timed out. Killing.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896630 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896632 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896633 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896635 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896639 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896640 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Killing process 2896641 (nextdns) with signal SIGKILL.
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Main process exited, code=killed, status=9/KILL
Dec 31 17:55:38 UXGPro systemd[1]: nextdns.service: Failed with result 'timeout'.
Dec 31 17:55:38 UXGPro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Dec 31 17:55:38 UXGPro nextdns[2898432]: Starting NextDNS 1.41.0/linux on :53
Dec 31 17:55:38 UXGPro nextdns[2898432]: Listening on TCP/:53
Dec 31 17:55:38 UXGPro nextdns[2898432]: Starting mDNS discovery
Dec 31 17:55:38 UXGPro nextdns[2898432]: Listening on UDP/:53
Dec 31 17:55:43 UXGPro nextdns[2898432]: Setting up generic router
Dec 31 17:55:43 UXGPro nextdns[2898432]: Activating
Dec 31 17:57:38 UXGPro nextdns[2898432]: Received signal: terminated
Dec 31 17:57:38 UXGPro systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Dec 31 17:57:38 UXGPro nextdns[2898432]: Stopping NextDNS 1.41.0/linux
Dec 31 17:59:08 UXGPro systemd[1]: nextdns.service: State 'stop-sigterm' timed out. Killing.
Dec 31 17:59:08 UXGPro systemd[1]: nextdns.service: Killing process 2898432 (nextdns) with signal SIGKILL.
Dec 31 17:59:08 UXGPro systemd[1]: nextdns.service: Killing process 2898434 (nextdns) with signal SIGKILL.
Dec 31 17:59:08 UXGPro systemd[1]: nextdns.service: Main process exited, code=killed, status=9/KILL
Dec 31 17:59:08 UXGPro systemd[1]: nextdns.service: Failed with result 'timeout'.
Dec 31 17:59:08 UXGPro systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
Dec 31 17:59:08 UXGPro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Dec 31 17:59:08 UXGPro nextdns[2901004]: Starting NextDNS 1.41.0/linux on :53
Dec 31 17:59:08 UXGPro nextdns[2901004]: Listening on TCP/:53
Dec 31 17:59:08 UXGPro nextdns[2901004]: Starting mDNS discovery
Dec 31 17:59:08 UXGPro nextdns[2901004]: Listening on UDP/:53
Dec 31 17:59:13 UXGPro nextdns[2901004]: Setting up generic router
Dec 31 17:59:13 UXGPro nextdns[2901004]: Activating
Dec 31 18:03:37 UXGPro systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Dec 31 18:03:37 UXGPro nextdns[2901004]: Received signal: terminated
Dec 31 18:03:37 UXGPro nextdns[2901004]: Stopping NextDNS 1.41.0/linux
Dec 31 18:05:08 UXGPro systemd[1]: nextdns.service: State 'stop-sigterm' timed out. Killing.
Dec 31 18:05:08 UXGPro systemd[1]: nextdns.service: Killing process 2901004 (nextdns) with signal SIGKILL.
Dec 31 18:05:08 UXGPro systemd[1]: nextdns.service: Killing process 2901005 (nextdns) with signal SIGKILL.
Dec 31 18:05:08 UXGPro systemd[1]: nextdns.service: Killing process 2901006 (n/a) with signal SIGKILL.
Dec 31 18:05:08 UXGPro systemd[1]: nextdns.service: Killing process 2901007 (nextdns) with signal SIGKILL.
Dec 31 18:05:08 UXGPro systemd[1]: nextdns.service: Killing process 2901010 (nextdns) with signal SIGKILL.
Dec 31 18:05:08 UXGPro systemd[1]: nextdns.service: Killing process 2901014 (n/a) with signal SIGKILL.
Dec 31 18:05:08 UXGPro systemd[1]: nextdns.service: Main process exited, code=killed, status=9/KILL
Dec 31 18:05:08 UXGPro systemd[1]: nextdns.service: Failed with result 'timeout'.
Dec 31 18:05:08 UXGPro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Dec 31 18:05:08 UXGPro nextdns[2906659]: Starting NextDNS 1.41.0/linux on :53
Dec 31 18:05:08 UXGPro nextdns[2906659]: Starting mDNS discovery
Dec 31 18:05:08 UXGPro nextdns[2906659]: Listening on TCP/:53
Dec 31 18:05:08 UXGPro nextdns[2906659]: Listening on UDP/:53
Dec 31 18:05:13 UXGPro nextdns[2906659]: Setting up generic router
Dec 31 18:05:13 UXGPro nextdns[2906659]: Activating
Dec 31 18:05:24 UXGPro nextdns[2906659]: Received signal: terminated
Dec 31 18:05:24 UXGPro systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Dec 31 18:05:24 UXGPro nextdns[2906659]: Stopping NextDNS 1.41.0/linux
Dec 31 18:06:54 UXGPro systemd[1]: nextdns.service: State 'stop-sigterm' timed out. Killing.
Dec 31 18:06:54 UXGPro systemd[1]: nextdns.service: Killing process 2906659 (nextdns) with signal SIGKILL.
Dec 31 18:06:54 UXGPro systemd[1]: nextdns.service: Killing process 2906662 (nextdns) with signal SIGKILL.
Dec 31 18:06:54 UXGPro systemd[1]: nextdns.service: Killing process 2906669 (nextdns) with signal SIGKILL.
Dec 31 18:06:54 UXGPro systemd[1]: nextdns.service: Killing process 2906671 (nextdns) with signal SIGKILL.
Dec 31 18:06:54 UXGPro systemd[1]: nextdns.service: Main process exited, code=killed, status=9/KILL
Dec 31 18:06:54 UXGPro systemd[1]: nextdns.service: Failed with result 'timeout'.
Dec 31 18:06:54 UXGPro systemd[1]: Started NextDNS DNS53 to DoH proxy..
Dec 31 18:06:54 UXGPro nextdns[2908054]: Starting NextDNS 1.41.0/linux on :53
Dec 31 18:06:54 UXGPro nextdns[2908054]: Starting mDNS discovery
Dec 31 18:06:54 UXGPro nextdns[2908054]: Listening on TCP/:53
Dec 31 18:06:54 UXGPro nextdns[2908054]: Listening on UDP/:53
Dec 31 18:06:59 UXGPro nextdns[2908054]: Setting up generic router
Dec 31 18:06:59 UXGPro nextdns[2908054]: Activating
root@UXGPro:~#

**Comment by rs** [comment]
You did not copied the whole command for the test version. Your need the env variable before the command otherwise it is ineffective.

**Comment by macflyhub** [comment]
Tried that and it threw an error.
Lost all internet and gave permission denied for everything.
Tried all kinds of things. 
Hours later.. had to flash back to factory and push setup.
Then tried again and it worked eventually but what a nightmare..
-
`root@UXG-Pro:~# NEXTDNS_VERSION=pr-899/SNAPSHOT-efee3d1 sh -c 'sh -c "$(curl -sL                                                                            https://raw.githubusercontent.com/nextdns/nextdns/f106407bc9a8ee0c6f1c2917bedb2                                                                           46a8b16013b/install.sh)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: pr-899/SNAPSHOT-efee3d1
u) Upgrade NextDNS from 1.41.0 to pr-899/SNAPSHOT-efee3d1
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
NextDNS installed and started using ubios init

[Did not work at this point - so went to Configure and then it all went down hill]

c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): c
NextDNS Profile ID (default=[Redacted]):
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: Y
Accept DNS request from other network hosts.
Setup as a router? [Y|n]: Y
Make NextDNS CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Enable caching? [Y|n]: Y
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on your LAN hosts without having to wait for their cache to expire.
Enable instant refresh? [Y|n]: Y
Changes DNS settings of the host automatically when NextDNS is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically setup local host DNS? [Y|n]: Y
NextDNS installed and started using ubios init
Error: systemctl start nextdns.service: signal: killed:
ERROR: configure: exit 0
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): r
INFO: Uninstalling NextDNS...
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

**Comment by rs** [comment]
Should be fixed with latest version. Please reopen if not.
