### ISSUE TITLE
Identify Client Correctly

### ISSUE THREAD

**Issue by vdias** [nextdns/nextdns#904]
Permit the CLI to resolve all clients locally.

My router DHCP assign a DNS entry to all devices, why can't the NextDNS cli resolve them to populate logs?

Adguard Home does that quite well...

**Comment by rs** [comment]
This is definitely a feature of the CLI. If it does not work in your setup, we will need more info.

**Comment by Fail-Safe** [comment]
@vdias What are your setting values for the following?

`discovery-dns`
`mdns`
`report-client-info`
`use-hosts`
