### ISSUE TITLE
Conditional config and device name reporting stops working

### ISSUE THREAD

**Issue by LoneWolff7** [nextdns/nextdns#905]
**Context** Conditional profiles and device names stops working randomly 
 - CLI Version: 1.41.0
 - Platform: OpenWRT 23.05.2

&lt;Describe the bug>
Conditional profiles and device name reporting stops working randomly after sometime, starts working after a router reboot but breaks once again after sometime.

I have populated /etc/hosts manually but the issue persists. I have also turned off MAC randomization on all my devices.

Here’s my NextDNS config
root@OpenWrt:~# nextdns config
profile xx:xx:xx:xx:xx:xx=abcdef
profile xx:xx:xx:xx:xx:xx=abcdef
profile xx:xx:xx:xx:xx:xx=abcdef
profile 123456
log-queries false
report-client-info true
mdns all
detect-captive-portals false
bogus-priv true
listen localhost:53
forwarder .lan.=192.168.1.1:5342
cache-size 10MB
discovery-dns 192.168.1.1:5342
hardened-privacy false
setup-router true
auto-activate true
control /var/run/nextdns.sock
max-ttl 5s
use-hosts true
max-inflight-requests 256
debug false
cache-max-age 0s
timeout 5s

root@OpenWrt:~# nextdns version
nextdns version 1.41.0

**Comment by Fail-Safe** [comment]
@LoneWolff7 Is it safe to assume `192.168.1.1:5342` is dnsmasq on your OpenWrt box?

When you run the command `nextdns discovered`, do you see all your devices, including their proper (expected) host names and IP addresses? There should be multiple groupings in the output including `dhcp`, `dns`, `hosts`, and `mdns`.

**Comment by LoneWolff7** [comment]
@Fail-Safe I’ve solved the issue by setting `setup-router=false` and `listen=192.168.1.1:53`, it’s working very reliably now. It simply doesn’t work with setup-router set to true for some reason.
