### ISSUE TITLE
NextDNS Latency Discrepancy: Salvador vs. Rio de Janeiro

### ISSUE THREAD

**Issue by viniribeirossa** [nextdns/nextdns#907]
**Context**
 - CLI Version: 1.41.0
 - Platform: OpenWrt 23.02

I live in Salvador, Bahia, BR, and NextDNS has a server in my city (**edgeuno-ssa**). However, my traffic is routed through Rio de Janeiro, BR, via the server (**edgeuno-rio**), whereas if it were routed through the server in my city, I would have **4ms** latency, but with Rio de Janeiro, I have **35ms**.

```
  edgeuno-ssa           4 ms
  edgeuno-ssa (IPv6)    9 ms
  anexia-rio           28 ms  (ultralow1)
  anexia-rio (IPv6)    28 ms  (ultralow1)
  anexia-sao           33 ms
  vultr-sao (IPv6)     33 ms
  edgeuno-sao (IPv6)   33 ms
  zepto-sao (IPv6)     33 ms  (anycast1)
  edgeuno-sao          34 ms
  anexia-sao (IPv6)    34 ms  (anycast2)
  zepto-sao            34 ms  (anycast1)
  vultr-sao            35 ms  (anycast2)
■ edgeuno-rio          35 ms  (ultralow2)
  edgeuno-rio (IPv6)   36 ms  (ultralow2)
  edgeuno-bsb (IPv6)   38 ms
  edgeuno-bsb          38 ms
  edgeuno-cwb          39 ms
  edgeuno-cwb (IPv6)   43 ms
  edgeuno-for (IPv6)   48 ms
  edgeuno-for          48 ms
```

**Comment by eboermans** [comment]
@nextdns I have a similar router.nextdns problem here in Melbourne Australia:
https://nextdns.io/diag/7f4926e0-bf30-11ee-a065-fd6a42fe65b7

**Comment by eboermans** [comment]
MyRouter-123456.dns.nextdns.io resolves the server IPs of too distant servers 
How do I add MyRouter-123456. to:
ipv6.dns2.nextdns.io
ipv4.dns2.nextdns.io
ipv6.dns1.nextdns.io
ipv4.dns1.nextdns.io
ipv6-anycast.dns2.nextdns.io
ipv4-anycast.dns2.nextdns.io
ipv6-anycast.dns1.nextdns.io
ipv4-anycast.dns1.nextdns.io
