### ISSUE TITLE
UDM SE update to 3.2.12 rerunning 1.42.0 installer does not work.

### ISSUE THREAD

**Issue by Amazo00** [nextdns/nextdns#909]
**Context**
 - CLI Version: 1.42.0
 - Platform: UDM SE

&lt;Describe the bug>
Updated the UDM SE to OS v 3.2.12, went to rerun installer and could not install.

Debug output is this:

Device UDM-SE: Connecting
Device UDM-SE: Connected
# sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.42.0
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
DEBUG: Using deb install type

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.2.4).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Ign:1 https://archive.debian.org/debian bullseye InRelease
Hit:2 https://apt.artifacts.ui.com bullseye InRelease                          
Ign:3 https://archive.debian.org/debian bullseye-updates InRelease             
Hit:4 https://repo.nextdns.io/deb stable InRelease                             
Ign:5 https://archive.debian.org/debian bullseye-backports InRelease           
Ign:6 https://archive.debian.org//debian-security bullseye-security InRelease  
Err:7 https://archive.debian.org/debian bullseye Release            
  404  Not Found [IP: 2a04:4e42::644 443]
Hit:8 https://apt-release-candidate.artifacts.ui.com bullseye InRelease
Err:9 https://archive.debian.org/debian bullseye-updates Release
  404  Not Found [IP: 2a04:4e42::644 443]
Hit:10 https://apt-beta.artifacts.ui.com bullseye InRelease
Err:11 https://archive.debian.org/debian bullseye-backports Release
  404  Not Found [IP: 2a04:4e42::644 443]
Err:12 https://archive.debian.org//debian-security bullseye-security Release
  404  Not Found [IP: 2a04:4e42::644 443]
Reading package lists... Done
E: The repository 'https://archive.debian.org/debian bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://archive.debian.org/debian bullseye-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://archive.debian.org/debian bullseye-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://archive.debian.org//debian-security bullseye-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit

**Comment by kb9gxk** [comment]
That looks more like an issue with APT accessing archive.debian.org via IPv6 and not an issue with the NextDNS installer.  

Temporarily disable IPv6 on the WAN and try again.

**Comment by Amazo00** [comment]
Switched to IPv4 and this is the output:

Device UDM-SE: Connecting
Device UDM-SE: Connected
# 
# sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.42.0
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
DEBUG: Using deb install type
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.2.4).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Ign:1 https://archive.debian.org/debian bullseye InRelease
Ign:2 https://archive.debian.org/debian bullseye-updates InRelease             
Ign:3 https://archive.debian.org/debian bullseye-backports InRelease           
Hit:4 https://repo.nextdns.io/deb stable InRelease                             
Hit:5 https://apt.artifacts.ui.com bullseye InRelease                          
Ign:6 https://archive.debian.org//debian-security bullseye-security InRelease  
Err:7 https://archive.debian.org/debian bullseye Release                       
  404  Not Found [IP: 151.101.2.132 443]
Err:8 https://archive.debian.org/debian bullseye-updates Release               
  404  Not Found [IP: 151.101.2.132 443]
Err:9 https://archive.debian.org/debian bullseye-backports Release             
  404  Not Found [IP: 151.101.2.132 443]
Err:10 https://archive.debian.org//debian-security bullseye-security Release   
  404  Not Found [IP: 151.101.2.132 443]
Hit:11 https://apt-release-candidate.artifacts.ui.com bullseye InRelease       
Hit:12 https://apt-beta.artifacts.ui.com bullseye InRelease                    
Reading package lists... Done
E: The repository 'https://archive.debian.org/debian bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://archive.debian.org/debian bullseye-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://archive.debian.org/debian bullseye-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://archive.debian.org//debian-security bullseye-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit

**Comment by Amazo00** [comment]
This looks very similar to this closed item.

https://github.com/nextdns/nextdns/issues/830

**Comment by photomme** [comment]
Experiencing same issue:

`root@UDMSE:~# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.42.0
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.2.4).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
Hit:1 https://deb.debian.org/debian bullseye InRelease
Hit:2 https://deb.debian.org/debian bullseye-updates InRelease                                                                               
Hit:3 https://deb.debian.org/debian bullseye-backports InRelease                                                                             
Hit:4 https://security.debian.org/debian-security bullseye-security InRelease                                                                
Hit:5 https://apt.artifacts.ui.com bullseye InRelease                                                                                        
Hit:6 https://repo.nextdns.io/deb stable InRelease                                                                                           
Err:7 https://apt-release-candidate.artifacts.ui.com bullseye InRelease                                                                      
  401   [IP: 35.160.231.47 443]
Err:8 https://apt-beta.artifacts.ui.com bullseye InRelease
  401   [IP: 52.32.129.26 443]
Reading package lists... Done
E: Failed to fetch https://apt-release-candidate.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 35.160.231.47 443]
E: The repository 'https://apt-release-candidate.artifacts.ui.com bullseye InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt-beta.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 52.32.129.26 443]
E: The repository 'https://apt-beta.artifacts.ui.com bullseye InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
i) Install NextDNS
e) Exit`

**Comment by vincentbernat** [comment]
This is odd that it is trying to pull bullseye from archive.debian.org. Debian Bullseye is still a supported release and therefore is not present on archive.debian.org.

**Comment by Amazo00** [comment]
So, the UDM SE when it updated to latest OS 3.2.12 the Debian sources.list in the OS got changed somehow to the "archive" source. I edited the sources list back the correct repositories and was able to reinstall from CLI. 

Sheesh!

Not a bug for sure. But odd none the less.

**Comment by RobertCSternberg** [comment]
Unfortunately, I am experiencing this issue with a UDM Express on OS v3.2.5.   This is after the change suggested from archive.debian.org to deb.debian.org. 

Any help is GREATLY APPRECIATED

```
Hit:1 https://deb.debian.org/debian bullseye InRelease                                                                                                      
Hit:2 https://deb.debian.org/debian bullseye-updates InRelease                                                                                              
Hit:3 https://deb.debian.org/debian bullseye-backports InRelease                                                                                            
Ign:4 https://deb.debian.org//debian-security bullseye-security InRelease                                                                                   
Err:5 https://apt-beta.artifacts.ui.com bullseye InRelease                                                                                                  
  401   [IP: 52.32.129.26 443]
Err:6 https://apt-release-candidate.artifacts.ui.com bullseye InRelease                                                 
  401   [IP: 52.32.129.26 443]
Err:7 https://deb.debian.org//debian-security bullseye-security Release                                                 
  Redirection from https to 'http://cdn-fastly.deb.debian.org/debian-security/dists/bullseye-security/Release' is forbidden [IP: 151.101.182.132 443]
Hit:8 https://repo.nextdns.io/deb stable InRelease                  
Hit:9 https://apt.artifacts.ui.com bullseye InRelease
Reading package lists... Done
E: Failed to fetch https://apt-beta.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 52.32.129.26 443]
E: The repository 'https://apt-beta.artifacts.ui.com bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt-release-candidate.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 52.32.129.26 443]
E: The repository 'https://apt-release-candidate.artifacts.ui.com bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://deb.debian.org//debian-security bullseye-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by RobertCSternberg** [comment]
> Unfortunately, I am experiencing this issue with a UDM Express on OS v3.2.5. This is after the change suggested from archive.debian.org to deb.debian.org.
> 
> Any help is GREATLY APPRECIATED
> 
> ```
> Hit:1 https://deb.debian.org/debian bullseye InRelease                                                                                                      
> Hit:2 https://deb.debian.org/debian bullseye-updates InRelease                                                                                              
> Hit:3 https://deb.debian.org/debian bullseye-backports InRelease                                                                                            
> Ign:4 https://deb.debian.org//debian-security bullseye-security InRelease                                                                                   
> Err:5 https://apt-beta.artifacts.ui.com bullseye InRelease                                                                                                  
>   401   [IP: 52.32.129.26 443]
> Err:6 https://apt-release-candidate.artifacts.ui.com bullseye InRelease                                                 
>   401   [IP: 52.32.129.26 443]
> Err:7 https://deb.debian.org//debian-security bullseye-security Release                                                 
>   Redirection from https to 'http://cdn-fastly.deb.debian.org/debian-security/dists/bullseye-security/Release' is forbidden [IP: 151.101.182.132 443]
> Hit:8 https://repo.nextdns.io/deb stable InRelease                  
> Hit:9 https://apt.artifacts.ui.com bullseye InRelease
> Reading package lists... Done
> E: Failed to fetch https://apt-beta.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 52.32.129.26 443]
> E: The repository 'https://apt-beta.artifacts.ui.com bullseye InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Failed to fetch https://apt-release-candidate.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 52.32.129.26 443]
> E: The repository 'https://apt-release-candidate.artifacts.ui.com bullseye InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: The repository 'https://deb.debian.org//debian-security bullseye-security Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```

I was able to fix this by commenting the sources in the ubiquiti.list file.  Then installing NextDNS before uncommenting the sources in the ubiquiti.list file.
