### ISSUE TITLE
DNS64 support

### ISSUE THREAD

**Issue by zod076** [nextdns/nextdns#910]
Hi, any plans to add DNS64 support ?

**Comment by eboermans** [comment]
You can try this: https://developers.google.com/speed/public-dns/docs/dns64

**Comment by zod076** [comment]
I'd prefer if it's from NextDNS themselves.

**Comment by eboermans** [comment]
not sure if this helps you: 
[ipv6.dns1.nextdns.io](https://ipv6.dns1.nextdns.io/)
[ipv6.dns2.nextdns.io](https://ipv6.dns2.nextdns.io/)

**Comment by trollybusman** [comment]
DNS64 is not a feature of this cli. They have to support it on the DNS servers themselves.

**Comment by rs** [comment]
As @trollybusman said, this is not a CLI feature. Please use https://help.nextdns.io instead (it's already a feature request).
