### ISSUE TITLE
UDM (or UDR) with Firmware 3.1.16 and Network 8.0.28 cannot install

### ISSUE THREAD

**Issue by nauip** [nextdns/nextdns#911]
running the command line and nothing happens, no error, just the next command line.
 - CLI Version: whatever this would install - sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
 - Platform: UDM or UDR

Describe the bug> running the command does nothing.

**Comment by nauip** [comment]
I tried turning off IPv6 and same result.

**Comment by roggrat** [comment]
I  can confirm the same behavior with UniFi OS 3.2.12

**Comment by rs** [comment]
Do you get more output if you prefix the command with DEBUG=1 as follow:
```
DEBUG=1 sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"
```

**Comment by roggrat** [comment]
> Do you get more output if you prefix the command with DEBUG=1 as follow:
> 
> ```
> DEBUG=1 sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
> ```

I take this back, my issue was that on OS upgrade my DNS server was pointed to localhost so the unit was unable to resolve any URL's and so running  the install command the UDMP could not pull the script  or the packages to install. However the behavior stated above is what is experienced.

Solution:
- log into the console and temporally modify with VIM the /etc/resolv.dnsmasq to  add nameserver 8.8.8.8 
- Rerun the install command 

et viola !

Hopefully this may help someone in the same boat.

**Comment by nauip** [comment]
I get nothing using the Debug command. The UDR was cone stock out of the box. The UDM auto updated and was previously using NextDNS, so should have been using NextDNS servers.

**Comment by roggrat** [comment]
can you ping yahoo or google from your console ?

**Comment by nauip** [comment]
Either the issue stopped presenting today or upgrading the device to 3.2.9 resolved the problem.

**Comment by rs** [comment]
Great to hear. Ok to close the issue?

**Comment by nauip** [comment]
Yep. Hopefully it was just a temporary glitch I happen to be stumbling upon when I was upgrading from my old UDM to a new UDR. Feel free to close this out.
