### ISSUE TITLE
Add the possibility to hide the taskbar icon on Windows 1x

### ISSUE THREAD

**Issue by infocillasas** [nextdns/nextdns#914]
Hi,
For Enterprise purposes on Windows machines, 

option 1) enable the possibility to not show the NextDNS taskbar icon to avoid users disable the service (especially when internet filtering policies are required). Maybe an option to be shown during the initial install.

option2) let the icon appear in the taskbar but let only Admins to right-click on it, modify the parameter or disable the service.

**Comment by rs** [comment]
Please check UI=0 on this doc: https://help.nextdns.io/t/83hsj8t/windows-client-mass-deployment-guide

**Comment by infocillasas** [comment]
Thanks @rs
Missed that one in the documentation !

**Comment by infocillasas** [comment]
Hi,
Now that NextDNS is installed without the tray icon, how to setup profiles for each account of the computer ? (Not globally through global DNS parameters)
Thanks

**Comment by rs** [comment]
You have to use the PROFILE parameter during msi install.

**Comment by infocillasas** [comment]
If I use the PROFILE parameter, it will use one single profile for the entire machine, isn't it ? I'm looking for a solution to hide the tray icon AND assign a different NextDNS profile to each computer account. 
Is that possible ?

**Comment by rs** [comment]
No it is either one or the other.

**Comment by infocillasas** [comment]
> No it is either one or the other.

Ok thanks for your feedback.
