### ISSUE TITLE
Install without Tray Icon & still setup profiles

### ISSUE THREAD

**Issue by infocillasas** [nextdns/nextdns#916]
Hi @rs 
Now that NextDNS is installed without the tray icon, how to setup profiles for each account of the computer ? (Not globally through global DNS parameters)
Thanks

_Originally posted by @infocillasas in https://github.com/nextdns/nextdns/issues/914#issuecomment-1976564521_

**Comment by rs** [comment]
I guess you are talking about the Windows application? This github is about our CLI.

For windows, if you install it without the tray icon, you can only set a global profile on the computer.

**Comment by infocillasas** [comment]
Hi @rs 
My question was indeed about the Windows App. The Windows app is also in the releases, that's why I thought I could ask questions here.
![image](https://github.com/nextdns/nextdns/assets/150066394/e0255d2f-f2a5-496b-9cf3-078abcdb943c)
Anyway, got it that without tray icon only one profile is applicable to the computer.
Thanks

**Comment by rs** [comment]
The CLI is also compatible with Windows but it is not the same thing as the Windows app. The CLI does not have a UI and works as a local DNS proxy while the Windows app is based on a kernel driver.
