### ISSUE TITLE
Online Installer no longer working on Unifi Dream Machine

### ISSUE THREAD

**Issue by allanparsons** [nextdns/nextdns#918]
**Context**
 - CLI Version:  UNK
 - Platform: Unifi Dream Machine

NextDNS stopped working ~9p PT 2024MAR08.  Attempted to reinstall nextdns UDM client via: `sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'`.  Command appears to timeout.

Attempted to manually save the script to a `.sh` file on the UDM disk and run manually. Produces error:

```
ERROR: Cannot get latest version: 
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 
ERROR: Cannot detect running environment.
```

Full run log:
```
root@HIDDEN-UDM:~# sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'
root@HIDDEN-UDM:~# curl -k -sL https://nextdns.io/install -o /tmp/install.sh
root@HIDDEN-UDM:~# nano /tmp/install.sh
-bash: nano: command not found
root@HIDDEN-UDM:~# vi /tmp/install.sh
root@HIDDEN-UDM:~# vi /tmp/install.sh
root@HIDDEN-UDM:~# sh /tmp/install.sh 
ERROR: Cannot get latest version: 
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 
ERROR: Cannot detect running environment.
root@HIDDEN-UDM:~#  /usr/bin/nextdns
-bash: /usr/bin/nextdns: No such file or directory
root@HIDDEN-UDM:~# sh DEBUG=1 ^C
root@HIDDEN-UDM:~# DEBUG=1  sh /tmp/install.sh
ERROR: Cannot get latest version: 
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 
ERROR: Cannot detect running environment.
root@HIDDEN-UDM:~# 
```

**Comment by allanparsons** [comment]
update!  looks like something borked my install.  Wasn't able to get to github to run install script (dns not resolving).  To re-run install:

1. Edit `/etc/hosts` and add entry for api.github.com and/or
2. Update `/etc/resolv.conf` and add 1.1.1.1
3. re-run install script

devs:  install script should maybe temporarily use different dns server during install to ensure you can always run installer, even if host is borked / binary gets wiped?

**Comment by remerson** [comment]
Unfortunately your fix didn't work for me, @allanparsons but thanks for the hints. I get a slightly different issue.

The installer just hangs here:

```
root@Dream-Machine:~# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.42.0
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
```

Looking further, DNS resolves okay on the UDM but something (inside the UDM) is blocking my traffic connecting out to `wget` the repo key.

```
root@Dream-Machine:~# wget https://repo.nextdns.io/nextdns.gpg
--2024-03-24 08:49:47--  https://repo.nextdns.io/nextdns.gpg
Resolving repo.nextdns.io (repo.nextdns.io)... 2606:4700:20::681a:aba, 2606:4700:20::ac43:4459, 2606:4700:20::681a:bba, ...
Connecting to repo.nextdns.io (repo.nextdns.io)|2606:4700:20::681a:aba|:443... ^C
```

This hangs. The address is correct but no connection. The UDM doesn't have `telnet` either so I couldn't check a basic test with that. I suspect it's some internal firewall/routing issue on the UDM. Another machine on my network can `wget` the key just fine. Maybe it's an IPv6 issue (but I am reluctant to switch that off as it took me trouble to get it working on the UDM).

The NextDNS CLI install did used to work fine for me until the most recent firmware update v3.2.12

**Comment by allanparsons** [comment]
Same issue for me: installer borked after firmware update (hence my post).  Try fetching the install script from elsewhere and putting it on the UDM.  See which line breaks.  Or, run it locally with the uninstall option.

did you try editing your /etc/hosts and /etc/resolv.conf?

other UDMs I manage didn’t have this issue… just one

**Comment by remerson** [comment]
For me, it's an IPv6 issue with the UDM. The NextDNS installer hangs trying to `wget` `repo.nextdns.io` for the repo key when using IPv6, as above.

If I use your suggestion @allanparsons to add an IPv6 address into `/etc/hosts` it still fails. So I think the UDM has a routing issue for IPv6 traffic here and it's the same using `wget` on the command line directly (as above).

**However**, if I add an IPv4 resolved address for `repo.nextdns.io` into `/etc/hosts` then it does work and installs cleanly.

**Comment by xenia-09A** [comment]
Hi the install is not supported by Dream machine correct,(close eyes) lol  they told me to use native and I said I cannot bc they  don't allow a custom URL yet , hoping they get custom url added soon an seem we wont need this CLI install? correct?
 so far I was worried about installing anything on the Dream Machine as most of my clients are DoT or DoH

**Comment by rs** [comment]
> Hi the install is not supported by Dream machine correct,(close eyes) lol they told me to use native and I said I cannot bc they don't allow a custom URL yet , hoping they get custom url added soon an seem we wont need this CLI install? correct? so far I was worried about installing anything on the Dream Machine as most of my clients are DoT or DoH

If you are not interested by CLI features like per host logs or per host profile, probably. I wouldn’t hold my breath though.

**Comment by xenia-09A** [comment]
@rs thanks, so if CLI is installed on UDM it will take all the port 53 traffic coming from devices convert it to DoT and also send the hostname of that device to NEXTDNS?

thanks

**Comment by vackraord** [comment]
> @rs thanks, so if CLI is installed on UDM it will take all the port 53 traffic coming from devices convert it to DoT and also send the hostname of that device to NEXTDNS?
> 
> thanks

I can answer that one. yes, it works. Of course, you need to configure it like that on install.

**Comment by xenia-09A** [comment]
@vackraord  yes I need to stop UDP , so I gonna ignore Ubiquiti here and try this out 

thanks

**Comment by trollybusman** [comment]
There is an alternative app, that's feature complete with Nextdns and works on all Ubiqiti devices. https://github.com/Control-D-Inc/ctrld/wiki/NextDNS-Mode

Run installer: `sh -c 'sh -c "$(curl -sL https://api.controld.com/dl)"'`

Start app with your Nextdns ID: `ctrld start --nextdns abc123`

**Comment by xenia-09A** [comment]
next DNS general CLI install seem this is a bit dangerous, after trying  cli install for nextdns on UDM it seem working fine for function...  BUT 
I noticed I had block rules on some AP devices that are now able to reach the internet (I see in nextdns logs now after cli install)
maybe bc it sniffing all traffic on port 53 and messing up unfi firewalls as it not expecting  traffic to be intercepted/manipulated...

I have a ASUS router as an AP for now that I have blocked to Internet  prior.. and now it clearly reaching nextDNS even with a rule to block internet always on UDM!
for now I am gonna need to review all this and maybe try diff firewall rules, or disable this ...

@trollybusman do you notice this with git you provided  above?

**Comment by rs** [comment]
On UDM, the CLI will listen on localhost and instruct the dnsmasq of the UDM to forward DNS traffic to it. There is no port 53 sniffing nor change of the firewall rules.

**Comment by xenia-09A** [comment]
@rc okay thanks for fast response but regardless   cli install is  bypassing internet block rules  on UDM  PRO SE , and allowing device to reach egress to Internet ,where it was clearly block before cli install

**Comment by rs** [comment]
@xenia-09A I don't see how that would be possible. Do you have more insight on what change would cause that?

**Comment by xenia-09A** [comment]
@rs I have a simple FW rule "Block this device to Internet" on UDM since this is a AP I block 99% of time unless I need updated then I close it back off 

, prior to CLI install the UDM would catch this bad boy trying to reach out to Internet and it it dropped as expected, after CLI install I see the device and logs on nextDNS which clearly mean is egress out now even with my block rule still in place ,

just want ppl to be made aware of what I see

**Comment by rs** [comment]
Thanks for the additional insight. I think you might be confusing internet access with DNS access. The CLI is accessible to all your LAN hosts for DNS resolution. Even hosts that are unable to access the internet will still be able to consult the local DNS resolver for hostname resolution and, therefore, will appear in NextDNS logs. Your blocking rule will block their traffic when they actually try to reach the IPs returned by those DNS queries.

Does it make sense?

**Comment by xenia-09A** [comment]
That exactly what I was just thinking .. agree 
It just won’t show in my udm logs now as blocked at port 53 but routing should be blocked

**Comment by rs** [comment]
Closing this as the original issue was solved by its reporter.
