### ISSUE TITLE
NextDNS Install does not persist after UDM Firmware Update

### ISSUE THREAD

**Issue by ChrisColotti** [nextdns/nextdns#919]
**Context**
 - CLI Version: 1.42.0
 - Platform: UDM Pto

Install no longer persists on UDM Pro Firmware update.  Every time a new firmware update is run (not the network SW), but the full UDM update the installer is gone.  Each firmware update requires a new install of the CLI.  This used to persist just fine.

**Comment by rs** [comment]
Kind of dup of https://github.com/nextdns/nextdns/issues/918

**Comment by ChrisColotti** [comment]
> Please check #913

Oh did not see that one I will review it.  So this is a known thing at the moment.

**Comment by ChrisColotti** [comment]
Closing as it is a duplicate issue...my bad.
