### ISSUE TITLE
Fritzbox+CLI Device Names Missing

### ISSUE THREAD

**Issue by Wlad2288** [nextdns/nextdns#924]
**Context**
```
INFO: OS: synology
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/local/bin/nextdns
INFO: INSTALL_RELEASE: 1.42.0
```

Hi All,

I am running nextdns-cli on a Synology NAS and my DHCP server is a Fritzbox.
I configured the DNS settings of my Fritzbox to use the Synology NAS (IPv4 and IPv6).

Everything works fine, except that device names are not displayed in the nextdns logs.
The only device which is logged, is the Fritzbox itself. So, from the logs it looks like all requests are issued by the Fritzbox.
However, when running `nextdns discovered`, I can see all of my devices under `mdns`.
This indicates, that nextdns-cli knows the names.

Why are these names not displayed in the logs?
Is that a limitation of my Fritzbox or am I missing something?

Here is my nextdns-cli config:

```
max-inflight-requests 256
listen localhost:53
control /var/run/nextdns.sock
max-ttl 5s
report-client-info true
discovery-dns 192.168.1.1
mdns all
timeout 5s
auto-activate false
debug false
profile xxxxx
cache-max-age 0s
hardened-privacy false
use-hosts true
setup-router true
log-queries false
cache-size 10MB
detect-captive-portals false
bogus-priv true
```

Many Thanks,
Wlad

**Comment by RicoLaaa** [comment]
Same issue here with a different router.
Nextdns CLI is installed on a raspberry, everything works fine except all connections are displayed as coming from the router, no other device is identified.

`timeout 5s
max-inflight-requests 256
log-queries false
max-ttl 5s
report-client-info true
detect-captive-portals false
use-hosts true
debug false
profile 1c66d5
cache-max-age 0s
hardened-privacy false
control /var/run/nextdns.sock
mdns all
setup-router true
auto-activate true
listen localhost:53
cache-size 10MB
discovery-dns 192.168.1.1
bogus-priv true`

thanks.

**Comment by theCatWisel** [comment]
Please check your DHCP settings on your router.
Most likely the handed out DNS server is the IP pointing to your router itself.

In this case, clients in your network will query your router for DNS services and the router will query DNS requests on your NAS.

Solution would be to change the handed out DNS server in your DHCP settings.

For your Fritz.Box you can find those here:

```
Home Network -> Network -> Network Settings -> Section IP Addresses
```

Here you need to set your DNS server for **"IPv4 Addresses”** and **"IPv6 Addresses”** respectively.

Now your DHCP clients will directly query your NAS for DNS requests and as correctly configures, your NAS would query host names from your FritzBox.

For Fritz.Box it is not ideal as you can only set one DNS server for IPv4 and IPv6 - therefore a simple failover setting by using two DNS servers within your network is not that easy possible - except one for IPv4 and another one for IPv6 ;-)

**Comment by RicoLaaa** [comment]
Thanks a lot for pointing me to the right direction !

I'm not on Fritzbox (swisscom internet box) but the issue was the same.
There  are 2 places to set the DNS.
One is the main DNS address (only IPv4) and there's another setting under DHCP to set the DNS (v4 and v6) sent to the devices in the network. That was the missing part as you explained.
The devices are now seen on the logs (to many devices now actually 😅), some by their real names some by codes. That's already a huge step forward, I'll figure out the rest.

Thanks a lot!
