### ISSUE TITLE
Peaking CPU high load issue on Unify UDM Base during suricate updates

### ISSUE THREAD

**Issue by bondskin** [nextdns/nextdns#925]
**Context**
 - CLI Version:  1.42.0
 - Platform: Unifi UDM (UnifiOS)

On my UDM Base (running 3.2.12) there is a daily night job updating Suricate database for IPS/IDS.
From time to time (not daily!) the update causes the CPU load to remain unusually high at around 50%.
Only a reboot fixes this issue.

<img width="338" alt="SCR-20240407-lvmt" src="https://github.com/nextdns/nextdns/assets/55050117/b1e90c81-f9c3-4017-8eec-7eab3d934557">
<img width="384" alt="SCR-20240309-pish" src="https://github.com/nextdns/nextdns/assets/55050117/26f9e1dc-8b9e-425c-a5bb-8d89e62baefe">

Unifi recommended to not use the CLI.
Since I removed the CLI the behaviour is back to normal
<img width="355" alt="SCR-20240418-ivya" src="https://github.com/nextdns/nextdns/assets/55050117/4770af2a-206f-4b52-bbf8-ab2ec0251f96">

Any advice?

(Unifi community reference (requires access): https://community.ui.com/questions/CPU-usage-bump/3f2d776c-95ca-4e0b-8f07-8405f717445f#answer/a5795b2a-c135-4ed9-b654-9d90bc3d1a53)

**Comment by rs** [comment]
Can you please turn on query logging and tell us if this is associated with an influx of queries?
