### ISSUE TITLE
private block list

### ISSUE THREAD

**Issue by xunil89** [nextdns/nextdns#927]
as the title I wonder why you can not put a private block list, I have my own private list on github and I would like to integrate it as I do with apps like adawey... will you consider the idea? I think it can be useful to many, true also that it could compromise a little the security of the service if the password was pierced you could insert a list that carries traffic to malicious domains but in my opinion the risk is worth..

**Comment by rs** [comment]
It is explained here: https://help.nextdns.io/t/q6hmva4/custom-blocklist-support
