### ISSUE TITLE
Fails to start service on Debian (Raspberry Pi)

### ISSUE THREAD

**Issue by saneef** [nextdns/nextdns#928]
**Context**
 - CLI Version: 1.43.0
 - Platform: Debian GNU/Linux 12 (bookworm) on Raspberry Pi

I'm unable to start the service. 

```sh
# ... partial log

Selecting previously unselected package nextdns.
(Reading database ... 55511 files and directories currently installed.)
Preparing to unpack .../nextdns_1.43.0_arm64.deb ...
Unpacking nextdns (1.43.0) ...
Setting up nextdns (1.43.0) ...
NextDNS installed and started using systemd init
Error: systemctl enable nextdns.service: exit status 1: Failed to enable unit: Unit file nextdns.service does not exist.


DEBUG: Start configure
DEBUG: Get profile ID
NextDNS Profile ID:
```

Even with the below error, I can continue configuring NextDNS. But when I do `sudo nextdns start`, I get the same error.

**Comment by saneef** [comment]
The same problem with Debian Bullseye. :(

**Comment by meepmeep** [comment]
same here. 
After upgrade to 1.43,  `nextdns config ` show a complete "default" config :

> #/usr/bin/nextdns config
> cache-max-age 0s
> report-client-info false
> hardened-privacy false
> listen localhost:53
> mdns all
> use-hosts true
> timeout 5s
> discovery-dns
> cache-size 0
> max-ttl 0s
> auto-activate false
> control /var/run/nextdns.sock
> log-queries false
> detect-captive-portals false
> bogus-priv true
> max-inflight-requests 256
> setup-router false
> debug false

which, in my case doesn't work because port 53 is already used.
Conf file is /etc/nextdns.conf and is not used by 1.43.0.
Downgrade with 1.42 deb file works.

**Comment by frobbnik** [comment]
if you use `nextdns config edit`, the file is written to `/config/nextdnsnextdns.conf` - which is surely a bug, but you can copy `/etc/nextdns.conf` there as a workaround.

**Comment by rs** [comment]
Please upgrade to 1.43.1
