### ISSUE TITLE
cache-keys and cache-stats subcommands broken with release 1.43.0

### ISSUE THREAD

**Issue by radupotop** [nextdns/nextdns#929]
**Context**
 - CLI Version:  1.43.0
 - Platform: Linux x86-64

The `cache-keys` and `cache-stats` subcommands are now broken with the release of version 1.43.0

**Comment by rs** [comment]
I can't reproduce. How does it fail?

**Comment by radupotop** [comment]
It responds with `nil` for both commands.

**Comment by rs** [comment]
Do you have the cache enabled in the config?

**Comment by rs** [comment]
Please also upgrade to 1.43.1 if you are on a systemd based system.

**Comment by radupotop** [comment]
That fixed it, thanks
