### ISSUE TITLE
1.43.1 Broken on MacOS

### ISSUE THREAD

**Issue by gchallen** [nextdns/nextdns#934]
**Context**
 - CLI Version: 1.43.1
 - Platform: MacOS M1 / M2

&lt;Describe the bug>

```sh
$ sudo nextdns version
1.42.0
$ dig @127.0.0.1 www.google.com // succeeds
$ sudo nextdns upgrade
$ sudo nextdns version
1.43.1
$ dig @127.0.0.1 www.google.com // fails
```

I also don't see a way to downgrade to `1.42.0`, so at the moment the only workaround is to disable NextDNS entirely.

**Comment by rs** [comment]
Please make sure it is running with `sudo nextdns status`

**Comment by skyweir** [comment]
Experiencing the same issue on MacOS. Can confirm NextDNS status as running

**Comment by eboermans** [comment]
I've fixed my issue with this information: https://www.bleepingcomputer.com/news/security/google-chromes-new-post-quantum-cryptography-may-break-tls-connections/

**Comment by gchallen** [comment]
```sh
$ nextdns status
running
```

**Comment by ibatten** [comment]
I'm seeing the same problem too:

igb@ians-macbook-air(pro):~$ sudo sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: darwin
INFO: GOARCH: arm64
INFO: GOOS: darwin
INFO: NEXTDNS_BIN: /usr/local/bin/nextdns
INFO: INSTALL_RELEASE: 1.43.1
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): r
INFO: Uninstalling NextDNS...
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
NextDNS Profile ID (default=7485cd): 
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: 
Make NextDNS CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Enable caching? [Y|n]: 
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on your LAN hosts without having to wait for their cache to expire.
Enable instant refresh? (y/n): 
Enable instant refresh? (y/n): y
Changes DNS settings of the host automatically when NextDNS is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically setup local host DNS? [Y|n]:  
NextDNS installed and started using launchd init

Congratulations! NextDNS is now installed.

To upgrade/uninstall, run this command again and select the appropriate option.

You can use the NextDNS command to control the daemon.
Here are a few important commands to know:

# Start, stop, restart the daemon:
nextdns start
nextdns stop
nextdns restart

# Configure the local host to point to NextDNS or not:
nextdns activate
nextdns deactivate

# Explore daemon logs:
nextdns log

# For more commands, use:
nextdns help

igb@ians-macbook-air(pro):~$ sudo vi /etc/nextdns.conf 
igb@ians-macbook-air(pro):~$ dig ns .

; <<>> DiG 9.11.0 <<>> ns .
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 741
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;.				IN	NS

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Apr 29 19:36:23 BST 2024
;; MSG SIZE  rcvd: 17

igb@ians-macbook-air(pro):~$ sudo nextdns deactivate                                    
igb@ians-macbook-air(pro):~$

**Comment by ibatten** [comment]
I've replaced the binary with that from the 1.43.0 release archive, and it now works correctly:

igb@ians-macbook-air(pro):~/Downloads$ sudo nextdns restart
igb@ians-macbook-air(pro):~/Downloads$ sudo nextdns version
nextdns version 1.43.0
igb@ians-macbook-air(pro):~/Downloads$ dig ns .

; <<>> DiG 9.11.0 <<>> ns .
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56135
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 13, ADDITIONAL: 0

;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			17044	IN	NS	f.root-servers.net.
.			17044	IN	NS	h.root-servers.net.
.			17044	IN	NS	d.root-servers.net.
.			17044	IN	NS	b.root-servers.net.

**Comment by ibatten** [comment]
I've just worked back through the darwin_arm64 tar archives, installing each nextdns binary in turn.  1.43.1 and 1.43.0 return SERVFAIL to "dig @localhost ns .".  1.42.0 works correctly.

**Comment by rs** [comment]
Please upgrade to v1.43.2, should be ready in a few minutes.

**Comment by jhult** [comment]
I see there is a fix, but in case it is helpful for the future and downgrading:

For those who installed via Homebrew, I used this to temporarily downgrade to 1.42.0.

```bash
cd /tmp
curl -L -o /tmp/nextdns_1.42.0_darwin_arm64.tar.gz https://github.com/nextdns/nextdns/releases/download/v1.42.0/nextdns_1.42.0_darwin_arm64.tar.gz
tar -xvf /tmp/nextdns_1.42.0_darwin_arm64.tar.gz
mkdir -p /opt/homebrew/Cellar/nextdns/1.42.0
mv /tmp/nextdns /opt/homebrew/Cellar/nextdns/1.42.0/
rm -rf /opt/homebrew/bin/nextdns
ln -s /opt/homebrew/Cellar/nextdns/1.42.0/nextdns /opt/homebrew/bin/nextdns
sudo chown jonathan:admin /opt/homebrew/Cellar/nextdns/1.42.0/nextdns
sudo nextdns restart
```

**Comment by gchallen** [comment]
I got v1.43.3. Still no joy:

```sh
$ nextdns status
running
$ dig @127.0.0.1 www.google.com

; <<>> DiG 9.10.6 <<>> @127.0.0.1 www.google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by chrisfinazzo** [comment]
> I see there is a fix, but in case it is helpful for the future and downgrading:
> 
> For those who installed via Homebrew, I used this to temporarily downgrade to 1.42.0.
> 
> ```shell
> cd /tmp
> curl -L -o /tmp/nextdns_1.42.0_darwin_arm64.tar.gz https://github.com/nextdns/nextdns/releases/download/v1.42.0/nextdns_1.42.0_darwin_arm64.tar.gz
> tar -xvf /tmp/nextdns_1.42.0_darwin_arm64.tar.gz
> mkdir -p /opt/homebrew/Cellar/nextdns/1.42.0
> mv /tmp/nextdns /opt/homebrew/Cellar/nextdns/1.42.0/
> rm -rf /opt/homebrew/bin/nextdns
> ln -s /opt/homebrew/Cellar/nextdns/1.42.0/nextdns /opt/homebrew/bin/nextdns
> sudo chown jonathan:admin /opt/homebrew/Cellar/nextdns/1.42.0/nextdns
> sudo nextdns restart
> ```

Just came across this as I was going to try it out w/ Pi-Hole + Tailscale. I'm still on Intel, so I'm guessing that the Darwin AMD64 release is what I should be using?

**Comment by jhult** [comment]
@chrisfinazzo,

Darwin == macOS
Intel == AMD64

**Comment by chrisfinazzo** [comment]
> @chrisfinazzo,
> 
> Darwin == macOS Intel == AMD64
 
 🤦🏻‍♂️ Whoops, fixed now.

**Comment by clong** [comment]
1.43.3 not working for me either

```
$ dig @127.0.0.1 yahoo.com                                                 

; <<>> DiG 9.10.6 <<>> @127.0.0.1 yahoo.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
