### ISSUE TITLE
Invalid header field value for "X-Device-Model"

### ISSUE THREAD

**Issue by brainsik** [nextdns/nextdns#939]
**Context**
 - CLI Version: nextdns version 1.43.3
 - Platform: FreeBSD 15.0-CURRENT (pfSense 24.03)

The `nextdns` daemon will get into a state where it can no longer resolve queries on the local host, though continues to work fine with remote hosts querying it.

This problem does not happen with version 1.42.0 (the version before the device model code was added?).

Here's some examples:

```console
$ nextdns upgrade
Error: Get "https://nextdns.io/install": dial tcp: lookup nextdns.io on 127.0.0.1:53: server misbehaving
$ tail -n1 /var/log/system.log
May 10 12:51:55 ng41 nextdns[73245]: Query 127.0.0.1 UDP A nextdns.io. dfb516 (qry=39/res=28) 0ms : doh resolve: net/http: invalid header field value for "X-Device-Model" 
$ host example.com
Host example.com not found: 3(NXDOMAIN)
$ tail -n1 /var/log/system.log
May 10 12:50:03 ng41 nextdns[73245]: Query 127.0.0.1 UDP A example.com. dfb516 (qry=29/res=29) 5ms : doh resolve: net/http: invalid header field value for "X-Device-Model" 
```

Looking through some recent commits, it appears the device model is determined from this:

```console
$ sysctl -n kern.version
FreeBSD 15.0-CURRENT #0 plus-RELENG_24_03-n256311-e71f834dd81: Fri Apr 19 00:28:14 UTC 2024
    root@freebsd:/var/jenkins/workspace/pfSense-Plus-snapshots-24_03-main/obj/amd64/Y4MAEJ2R/var/jenkins/workspace/pfSense-Plus-snapshots-24_03-main/sources/FreeBSD-src-plus-RELENG_24_03/amd64.amd64/sys/pfSense
```

Strangely, this doesn't always happen. Sometimes things work fine. Sometimes restarting the nextdns daemon will fix it. It's really unclear when and how this happens.

**Comment by elarsson1** [comment]
This issue persists on 1.43.3 on pfSense+ 2024.03 (FreeBSD 15.0-CURRENT) despite fixes in header handling in https://github.com/nextdns/nextdns/commit/e2d46ab83390382ebbee82b82e4f9e3185e40392.
