### ISSUE TITLE
nextdns status returns Error: unknown status:

### ISSUE THREAD

**Issue by iptvcld** [nextdns/nextdns#940]
**Context**
INFO: OS: ubuntu
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.43.3

Hello; I have NextDNS installed on Ubuntu and when ever i run nextdns status in the CLI it first returns back **Error: unknown status:** and then if i run that same status command a couple more times then it returns **running**.

![image](https://github.com/nextdns/nextdns/assets/34818686/d6f9b082-2df8-4d18-929e-606cc772c0b5)

**Comment by RPMozley** [comment]
As per forum post, here’s the other bug report that was fixed #674 
Seems the fix put in the unknown status that you’re seeing.

**Comment by iptvcld** [comment]
> As per forum post, here’s the other bug report that was fixed #674 Seems the fix put in the unknown status that you’re seeing.

Your right, seems like that’s where the error is originated from this code. 
![image](https://github.com/nextdns/nextdns/assets/34818686/51dda673-fcae-4140-858e-f51b5f08f832)

But I am not understanding why this is being caught for me. Is Ubuntu not the preferred distro for this CLI to work?

**Comment by RPMozley** [comment]
The CLI itself is perfectly fine doing it's job, it's just that running the status script sometimes times out waiting for the systemctl status to return a result.
If you just run the `systemctl status nextdns` command yourself and wait for it to give the result, it will most likely say it's running and active.

**Comment by iptvcld** [comment]
> The CLI itself is perfectly fine doing it's job, it's just that running the status script sometimes times out waiting for the systemctl status to return a result. If you just run the `systemctl status nextdns` command yourself and wait for it to give the result, it will most likely say it's running and active.

Thanks for the explanation, maybe the cli can be updated to pause for a few seconds before out putting the result. But I am thinking to move over to freeBSD, would I have the same results there as well or because FreeBSD does not systemd, I won’t see these delays with a false positive?

**Comment by iptvcld** [comment]
Something like this command will pull the status as well
`systemctl status nextdns | grep -oP '(?<=Active: active \()[^)]+'
`

**Comment by iptvcld** [comment]
Hoping there is a fix to this, I wanted to stay with Ubuntu or Debian but seems like alpine Linux may work better?
