### ISSUE TITLE
FreeBSD 14 - Not able to resolve hostnames locally on the VM running FreeBSD

### ISSUE THREAD

**Issue by iptvcld** [nextdns/nextdns#941]
FreeBSD 14
nextdns version 1.43.3

FreeBSD 14 - Not able to resolve hostnames locally on the VM running FreeBSD - I am trying to ping google.com where i have nextdns installed (FreeBSD) and it is not able to resolve anything.

root@testdns:~ # ping google.com
ping: Unknown host

**Log:**
May 12 11:42:01 testdns nextdns[953]: NextDNS 1.43.3/freebsd stopped
May 12 11:42:01 testdns nextdns[1685]: Starting NextDNS 1.43.3/freebsd on :53
May 12 11:42:01 testdns nextdns[1685]: Listening on TCP/:53
May 12 11:42:01 testdns nextdns[1685]: Listening on UDP/:53
May 12 11:42:06 testdns nextdns[1685]: Setting up generic router
May 12 11:42:06 testdns nextdns[1685]: Activating

**Config:**
`
report-client-info true
mdns disabled
bogus-priv true
use-hosts true
setup-router true
auto-activate true
log-queries false
control /var/run/nextdns.sock
cache-size 10MB
cache-max-age 0s
timeout 5s
debug false
listen localhost:53
profile 123
max-ttl 5s
discovery-dns 10.200.1.1
detect-captive-portals false
hardened-privacy false
max-inflight-requests 256`

**resolv.conf**

```
# This file is managed by nextdns.
#
# Run "nextdns deactivate" to restore previous configuration.


search example.com
options edns0
nameserver 127.0.0.1
```

I am going with FreeBSD as there seems to be consistency issues using a distro that has systemd - perhaps FreebSD is not the way to go and someone can point out a better solution/OS?

**Comment by RainofTerra** [comment]
I am encountering a similar situation on pfsense which is based on FreeBSD 15.0-CURRENT. Other things can connect to the nextdns cli running on pfsense, but pfsense itself can't resolve (gets servfail) even though I can connect to :53 via tcp with netcat.

**Comment by RainofTerra** [comment]
confirming fixed, thanks!
```
[24.03-RELEASE][admin@rowlf]/root: nextdns deactivate
[24.03-RELEASE][admin@rowlf]/root: nextdns upgrade
INFO: OS: pfsense
INFO: GOARCH: amd64
INFO: GOOS: freebsd
INFO: NEXTDNS_BIN: /usr/local/sbin/nextdns
INFO: INSTALL_RELEASE: 1.43.4
INFO: Upgrading NextDNS...
NextDNS installed and started using bsd init
[24.03-RELEASE][admin@rowlf]/root: nextdns activate
[24.03-RELEASE][admin@rowlf]/root: nslookup google.com
Server:		::1
Address:	::1#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.189.206
Name:	google.com
Address: 2607:f8b0:4005:80d::200e

[24.03-RELEASE][admin@rowlf]/root:
```
