### ISSUE TITLE
tplinkwifi.net blocked

### ISSUE THREAD

**Issue by wandersonbrazdf** [nextdns/nextdns#942]
**Context**
 - CLI Version: 3.013
 - Platform: Windows 11 App

&lt;Describe the bug>
After starting NextDNS for Windows, I lose access to the configuration page of the TP-link Router that I use through the tplinkwifi-net address.

**Comment by rs** [comment]
Did you enable DNS rebinding protection in the security tab?

**Comment by wandersonbrazdf** [comment]
No DNS rebniding is disable

**Comment by wandersonbrazdf** [comment]
> The TP link's DNS is probably the one providing an IP for itself. You will need to use rewrites to recreate this hostname with NextDNS.

I created a DNS rewrite for the address but it still doesn't work if I remove Next, restart the PC and browser, I can access it with the Next app or with the Yoga pointed to Next, I have no access

[https://i.imgur.com/URKytYb.png](url)[https://i.imgur.com/JVP9SZf.png](url)
