### ISSUE TITLE
NextDns on udm with WireGuard vpn 

### ISSUE THREAD

**Issue by xenia-09A** [nextdns/nextdns#945]
**Context**
 - CLI Version: 
 - Platform:udm pro se

&lt;Describe the bug>
Hi I have next dns installed on iOS using DoH working great 
I have next dns cli client installed on udm pro se also working great 

But when I WireGuard vpn to my udm the next dns logs shows a  random device name not the name assigned to my profile on IOS
this is not big deal but just wondering is this expected behavior

Secondly my real issue is  I also have an Android using DoT and same udm using NextDNS cli , and I cannot get DoT DNS to work while on vpn, the android device complains and no dns until I drop vpn I had this working before Installed NextDNS cli on udm so any help to resolve would be great 

so DoH on apple no issues on vpn except  vanity device name changed 

DoT on android no dns when vpn into udm and Device  has certain local lan access I allow only( as expected) 

Thanks loving NextDNS working like a champ for months on end just need to figure out DoT on vpn .

The udm shows the android connected on von but pcap of vpn interface shows no traffic from the expect host IP I have assigned for  this user.

Thanks !

**Comment by kb9gxk** [comment]
This is a bug in the UDM. I have reported it to the Ubiquiti developers. For some reason, the config files do not include the DNS settings you set for the VPN but rather 8.8.8.8.

**Comment by xenia-09A** [comment]
Thanks so much I was unable to get this resolved via a ticket

**Comment by xenia-09A** [comment]
Also Is the device name a cli issue or also a UniFi issue thanks
