### ISSUE TITLE
Multiple upstreams

### ISSUE THREAD

**Issue by iptvcld** [nextdns/nextdns#948]
Is there an option to have multiple upstreams (google, CF) while still keeping logging in nextdns? AGH, allows this and which ever the fastest upstreams, wins. So it’s not just a backup. Thanks.

**Comment by rs** [comment]
NextDNS is an "upstream". Unlike AGH, it is not a DNS proxy. So you can't mix NextDNS with another DNS resolver. There would be no real value anyways as it would mostly add latency.
