### ISSUE TITLE
Conditional Profiles broken on UniFiOS

### ISSUE THREAD

**Issue by Forsaked** [nextdns/nextdns#949]
**Context**
 - CLI Version: 1.43.5
 - Platform: UniFiOS 4.0.3

**Bug**

Since the update to 1.43.5, the conditional profiles won't work anymore.
Every DNS requests uses the default profile instead of the conditional ones.

**Example**

profile A12345  
profile 10.0.10.0/24=B12345  
profile 10.0.20.0/24=C12345  
profile 10.0.30.0/24=D12345  
profile 10.0.40.0/24=E12345  
profile 10.0.50.0/24=F12345  
profile 10.0.60.0/24=G12345

So in this example only profile A12345 gets used.

**Comment by rs** [comment]
Please try to uninstall a d reinstall.

**Comment by Forsaked** [comment]
> Please try to uninstall a d reinstall.

Already did this, also deleted the config file and recreated it, still the same.

**Comment by rs** [comment]
Can you please do it again, something was changed in the install script.

**Comment by Forsaked** [comment]
> Can you please do it again, something was changed in the install script.

Uninstalled, deleted the nextdns.config from /data/ folder and then reinstalled.
Set conditional profiles, restartet the service, still everything get pushed into the default profile.

**Comment by rs** [comment]
Please enable query logs and post some example queries that should go to another profile. Please also provide the output of `nextdns config`

**Comment by Forsaked** [comment]
**Querys**

May 25 19:38:58 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A ping.nextdns.io. AXXXXX (qry=33/res=99) 6ms HTTP/2.0
May 25 19:39:14 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A services.gfe.nvidia.com. AXXXXX (qry=41/res=57) 5ms HTTP/2.0
May 25 19:39:15 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A events.gfe.nvidia.com. AXXXXX (qry=39/res=55) 5ms HTTP/2.0
May 25 19:39:17 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A prod.otel.kaizen.nvidia.com. AXXXXX (qry=45/res=61) 5ms HTTP/2.0
May 25 19:39:20 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A www.google.com. AXXXXX (qry=32/res=48) 5ms HTTP/2.0
May 25 19:39:28 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A login.live.com. AXXXXX (qry=32/res=302) 6ms HTTP/2.0
May 25 19:39:28 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A api.github.com. AXXXXX (qry=32/res=48) 5ms HTTP/2.0
May 25 19:39:30 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP SRV _https._tcp.enterprise.proxmox.com. AXXXXX (qry=52/res=106) 6ms HTTP/2.0
May 25 19:39:30 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP SRV _http._tcp.security.debian.org. AXXXXX (qry=48/res=92) 5ms HTTP/2.0
May 25 19:39:30 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP SRV _http._tcp.ftp.de.debian.org. AXXXXX (qry=46/res=99) 6ms HTTP/2.0
May 25 19:39:30 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A ftp.de.debian.org. AXXXXX (qry=35/res=51) 5ms HTTP/2.0
May 25 19:39:30 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A debian.map.fastlydns.net. AXXXXX (qry=42/res=58) 29ms HTTP/2.0
May 25 19:39:30 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP AAAA debian.map.fastlydns.net. AXXXXX (qry=42/res=70) 37ms HTTP/2.0
May 25 19:39:30 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP AAAA ftp.de.debian.org. AXXXXX (qry=35/res=88) 38ms HTTP/2.0
May 25 19:39:30 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP AAAA enterprise.proxmox.com. AXXXXX (qry=40/res=135) 157ms HTTP/2.0
May 25 19:39:30 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A enterprise.proxmox.com. AXXXXX (qry=40/res=122) 177ms HTTP/2.0
May 25 19:39:36 UniFi-Dream-Machine-Pro nextdns[885462]: Query 127.0.0.1 UDP A test.steampowered.com. AXXXXX (qry=39/res=55) cached HTTP/2.0
  
  
**Config**

auto-activate true
debug false
mdns all
setup-router true
max-ttl 5s
discovery-dns
detect-captive-portals false
hardened-privacy false
control /var/run/nextdns.sock
log-queries true
cache-size 10MB
cache-max-age 0s
max-inflight-requests 256
report-client-info false
bogus-priv true
timeout 5s
listen localhost:53
profile AXXXXX
profile 10.0.10.0/24=BXXXXX
profile 10.0.20.0/24=CXXXXX
profile 10.0.30.0/24=DXXXXX
profile 10.0.40.0/24=EXXXXX
profile 10.0.50.0/24=FXXXXX
profile 10.0.60.0/24=GXXXXX
use-hosts true

**Comment by rs** [comment]
What is the output of `cat /run/dnsmasq.conf.d/nextdns.conf`

**Comment by rs** [comment]
Oh yes your right, without client reporting, we disable the client IPs but then it breaks dynamic profile…

**Comment by Forsaked** [comment]
> cat /run/dnsmasq.conf.d/nextdns.conf

# Configuration generated by NextDNS
no-resolv
server=127.0.0.1#5342
max-cache-ttl=0


> Oh yes your right, without client reporting, we disable the client IPs but then it breaks dynamic profile…

**with client reporting enabled, works!**

May 25 20:42:45 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A login.live.com. BXXXXX (qry=65/res=321) 6ms HTTP/2.0
May 25 20:42:45 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A storeedgefd.dsx.mp.microsoft.com. BXXXXX (qry=83/res=289) 169ms HTTP/2.0
May 25 20:42:45 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A storeedgefd.dsx.mp.microsoft.com. BXXXXX (qry=83/res=289) 157ms HTTP/2.0
May 25 20:42:46 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A bat.bing.com. BXXXXX (qry=63/res=93) 5ms HTTP/2.0
May 25 20:42:46 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A images-eds-ssl.xboxlive.com. BXXXXX (qry=78/res=159) 33ms HTTP/2.0
May 25 20:42:46 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A images-eds-ssl.xboxlive.com. BXXXXX (qry=78/res=159) 5ms HTTP/2.0
May 25 20:42:47 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A store-images.microsoft.com. BXXXXX (qry=77/res=162) 41ms HTTP/2.0
May 25 20:42:47 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A store-images.microsoft.com. BXXXXX (qry=77/res=162) 34ms HTTP/2.0
May 25 20:42:47 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A store-images.s-microsoft.com. BXXXXX (qry=79/res=166) 6ms HTTP/2.0
May 25 20:42:49 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A musicart.xboxlive.com. BXXXXX (qry=72/res=144) 61ms HTTP/2.0
May 25 20:42:49 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A musicart.xboxlive.com. BXXXXX (qry=72/res=144) 142ms HTTP/2.0
May 25 20:42:52 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A bat.bing.com. BXXXXX (qry=63/res=93) cached HTTP/2.0
May 25 20:42:56 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A da.xboxservices.com. BXXXXX (qry=70/res=241) 38ms HTTP/2.0
May 25 20:42:56 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A da.xboxservices.com. BXXXXX (qry=70/res=241) cached HTTP/2.0
May 25 20:42:56 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A storeedgefd.dsx.mp.microsoft.com. BXXXXX (qry=83/res=289) cached HTTP/2.0
May 25 20:43:00 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A bat.bing.com. BXXXXX (qry=63/res=93) cached HTTP/2.0
May 25 20:43:06 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 127.0.0.1 UDP A ping.nextdns.io. AXXXXX (qry=56/res=110) 5ms HTTP/2.0
May 25 20:43:08 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 127.0.0.1 UDP A ping.ui.com. AXXXXX (qry=52/res=92) 6ms HTTP/2.0
May 25 20:43:08 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 127.0.0.1 UDP AAAA ping.ui.com. AXXXXX (qry=52/res=144) 6ms HTTP/2.0
May 25 20:43:08 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 127.0.0.1 UDP PTR 1.1.1.1.in-addr.arpa. AXXXXX (qry=61/res=78) 5ms HTTP/2.0
May 25 20:43:09 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 127.0.0.1 UDP PTR 1.1.1.1.in-addr.arpa. AXXXXX (qry=61/res=78) 5ms HTTP/2.0
May 25 20:43:09 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A s.to. BXXXXX (qry=55/res=49) 5ms HTTP/2.0
May 25 20:43:10 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A pool.ntp.org. BXXXXX (qry=63/res=105) 5ms HTTP/2.0
May 25 20:43:11 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A api.roonlabs.net. BXXXXX (qry=67/res=139) 6ms HTTP/2.0
May 25 20:43:12 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A bits.roonlabs.net. BXXXXX (qry=68/res=62) 5ms HTTP/2.0
May 25 20:43:16 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A services.gfe.nvidia.com. BXXXXX (qry=74/res=140) 6ms HTTP/2.0
May 25 20:43:16 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A bat.bing.com. BXXXXX (qry=63/res=93) cached HTTP/2.0
May 25 20:43:17 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A events.gfe.nvidia.com. BXXXXX (qry=72/res=111) 5ms HTTP/2.0
May 25 20:43:18 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A discovery.roonlabs.net. BXXXXX (qry=73/res=67) 5ms HTTP/2.0
May 25 20:43:21 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A push-connector-v2-0.prd-roonlabs-1.prd.roonlabs.net. BXXXXX (qry=102/res=96) 5ms HTTP/2.0
May 25 20:43:22 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A prod.otel.kaizen.nvidia.com. BXXXXX (qry=78/res=184) 5ms HTTP/2.0
May 25 20:43:45 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A ctldl.windowsupdate.com. BXXXXX (qry=74/res=378) 46ms HTTP/2.0
May 25 20:43:45 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A ctldl.windowsupdate.com. BXXXXX (qry=74/res=378) 45ms HTTP/2.0
May 25 20:43:48 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A bat.bing.com. BXXXXX (qry=63/res=93) cached HTTP/2.0
May 25 20:43:53 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.40.100 UDP AAAA api.tidal.com. DXXXXX (qry=64/res=120) 8ms HTTP/2.0
May 25 20:43:53 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.40.100 UDP A api.tidal.com. DXXXXX (qry=64/res=106) 18ms HTTP/2.0
May 25 20:43:54 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.40.100 UDP A sp-pr-fa.audio.tidal.com. DXXXXX (qry=75/res=103) 45ms HTTP/2.0
May 25 20:43:54 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.40.100 UDP AAAA sp-pr-fa.audio.tidal.com. DXXXXX (qry=75/res=145) 70ms HTTP/2.0
May 25 20:43:57 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A c.pki.goog. BXXXXX (qry=61/res=90) 45ms HTTP/2.0
May 25 20:43:57 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A c.pki.goog. BXXXXX (qry=61/res=90) 34ms HTTP/2.0
May 25 20:43:57 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A x1.c.lencr.org. BXXXXX (qry=65/res=148) 53ms HTTP/2.0
May 25 20:43:57 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A ctldl.windowsupdate.com. BXXXXX (qry=74/res=378) cached HTTP/2.0
May 25 20:43:57 UniFi-Dream-Machine-Pro nextdns[1041822]: Query 10.0.20.10 UDP A x1.c.lencr.org. BXXXXX (qry=65/res=148) 132ms HTTP/2.0
