### ISSUE TITLE
[asuswrt-merlin] No way to see the version of NextDNS running or if there are any updates available

### ISSUE THREAD

**Issue by simonbcn** [nextdns/nextdns#954]
```
INFO: OS: asuswrt-merlin
INFO: GOARCH: armv7
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /jffs/nextdns/nextdns
INFO: INSTALL_RELEASE: 1.43.5
```

On **my.nextdns.io** there is no way to see the version of nextdns running or if there are any updates available. 
Would it cost that much to add this information to the control panel?

![NextDNS-Privacy-Options-2](https://github.com/nextdns/nextdns/assets/428231/d502fd63-ede3-4c35-8255-b0e349c3a6ba)

**Comment by rs** [comment]
This is not planned.

**Comment by simonbcn** [comment]
ok, so what is your solution for users to keep applications up to date?
