### ISSUE TITLE
All clients reporting unknown on UMD Pro

### ISSUE THREAD

**Issue by kxavier23** [nextdns/nextdns#955]
**Context**
 - CLI Version: 1.43.5
 - Platform:

&lt;Describe the bug>

Here is my result from test.nextdns.io

{
	"status": "ok",
	"protocol": "TCP",
	"profile": "fp88b382eca0bf35bf",
	"client": "96.42.107.160",
	"srcIP": "96.42.107.160",
	"destIP": "45.90.28.246",
	"anycast": true,
	"server": "vultr-chi-1",
	"clientName": "unknown"
}

**Comment by rs** [comment]
Protocol being TCP means this is not using the CLI.

**Comment by kxavier23** [comment]
It is now UDP and still clientName is unknown

{
	"status": "ok",
	"protocol": "UDP",
	"profile": "fp88b382eca0bf35bf",
	"client": "96.42.107.160",
	"srcIP": "96.42.107.160",
	"destIP": "45.90.28.246",
	"anycast": true,
	"server": "vultr-chi-1",
	"clientName": "unknown"
}

**Comment by rs** [comment]
If it was the CLI it would be DOH.
