### ISSUE TITLE
When attempting to query DNS using kdig with TLS configured to NextDNS (`@127.0.0.1`), I encountered the following error:

### ISSUE THREAD

**Issue by Joshharsh** [nextdns/nextdns#959]
Steps to Reproduce:

Configure NextDNS with TLS on localhost (127.0.0.1).
Execute the command kdig +tls @127.0.0.1 example.com.
Expected Behavior:
The command should resolve the DNS query without errors.

Actual Behavior:
The command terminates abruptly with the free(): double free detected in tcache 2 error message.

Additional Information:
Operating System: debian
NextDNS Configuration: default. only change, setup-router false.
listen localhost:53
listen localhost:853
listen localhost:443

Logs:  TCP read: unexpected EOF.

kdig +tls @127.0.0.1 example.com
;; WARNING: TLS, peer took too long to respond
free(): double free detected in tcache 2
Aborted

This issue occurs consistently on my setup. if it can be fixed for dns over tls and dns over https also.

**Comment by RPMozley** [comment]
Local DNS lookups do not use TLS or HTTPS. It’s just plain old unencrypted DNS to access the CLI. The CLI then forwards the request to NextDNS using DoH (as default).

To use DoT or DoH locally you’d need to use some other software and it would probably require a SSL certificate.
