### ISSUE TITLE
Unbound - SSL handshake failed

### ISSUE THREAD

**Issue by Ph4rell** [nextdns/nextdns#96]
Hello everyone,

Just configured my unbound server to forward DNS request to nextDNS as describe in the setup.
Got those errors in the unbound logs.

`Feb 29 16:51:29 unbound[12961]: [1582995089] unbound[12961:0] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Feb 29 16:51:29 unbound[12961]: [1582995089] unbound[12961:0] notice: ssl handshake failed 45.90.30.0 port 853
Feb 29 16:51:29 unbound[12961]: [1582995089] unbound[12961:0] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Feb 29 16:51:29 unbound[12961]: [1582995089] unbound[12961:0] notice: ssl handshake failed 45.90.28.0 port 853
Feb 29 16:51:29 unbound[12961]: [1582995089] unbound[12961:0] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Feb 29 16:51:29 unbound[12961]: [1582995089] unbound[12961:0] notice: ssl handshake failed 45.90.30.0 port 853
Feb 29 16:51:29 unbound[12961]: [1582995089] unbound[12961:0] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Feb 29 16:51:29 unbound[12961]: [1582995089] unbound[12961:0] notice: ssl handshake failed 45.90.28.0 port 853
Feb 29 16:51:29 unbound[12961]: [1582995089] unbound[12961:0] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Feb 29 16:51:29 kali unbound[12961]: [1582995089] unbound[12961:0] notice: ssl handshake failed 45.90.30.0 port 853`

Any ideas ?
Regards,
Ph4rell

**Comment by rs** [comment]
You need to setup the `tls-cert-bundle`.
