### ISSUE TITLE
Does Nextdns work with Ubiquiti UDM 4.0.6 Update

### ISSUE THREAD

**Issue by tc60045** [nextdns/nextdns#960]
Ubiquiti is now rolling out 4.0.6 as RC, doing so "gradually" (here: https://community.ui.com/releases/UniFi-OS-Dream-Machines-4-0-6/bac12326-92be-490e-b5da-9ab55195a903) 

Know that you guys are all over UDM, so I'm wondering if anything with this update will break Nextdns or has it been smooth.
 
Take as a compliment that I won't upgrade my UDM until I know the answer -- you're that important to at least this customer! 

Also, filed this as a bug not because it is one, but because if you haven't tested 4.0.6 yet and they are rolling that out, I wanted to be sure you got "ahead" on resolving.  

Best,  TC

**Comment by deletedpenguin** [comment]
I upgraded inadvertently (was on my phone and approved the upgrade) and it does seem as if it has broken the NextDNS config.

**Comment by dlorddd** [comment]
I had some interesting issues today while updating to 4.0.6. My console was reportedly offline via unifi.ui.com but was reachable on local. When running the script via ssh nothing happened. Turns out I had to temporarily add cloudflare/google DNS to my unifi Internet settings so that the console itself would connect to the internet. After this I could reinstall everything as usual.

**Comment by umarbutler** [comment]
In my case, it uninstalled NextDNS but DNS continued to work (ie, I didn't need to add 8.8.8.8 in my UDM's setting). I just had to reinstall NextDNS.

I've had NextDNS uninstall with previous updates... It would be nice if we could have it persist.

**Comment by xenia-09A** [comment]
okay great I needed this as OS upgrade is pending so 
when you upgrade  unfi OS  stop or completely  uninstall next dns CLI, upgrade OS and reinstall CLI correct?

thanks

**Comment by cmatte** [comment]
I had the same experience, NextDNS was deleted when I upgraded to 4.x - but also unfortunately I'm seeing lots of transient DNS failures after re-installing the client and setting up the local IPv4/IPv6 UDM SE as a DNS across internet and network connections. Is there a better way to do this? 

Internet settings:
![image](https://github.com/user-attachments/assets/0ef6fe23-82ed-400e-8831-65b6e64b9cd7)

Network settings IPv4:
![image](https://github.com/user-attachments/assets/b6387890-ceae-4040-a3e7-7f1d498cf2e6)

Network settings IPv6:
![image](https://github.com/user-attachments/assets/a1b743ce-7e10-48c2-92c5-106a57bae165)

DNS failures seen even on the UDM SE SSH host itself:
![image](https://github.com/user-attachments/assets/96620231-0fd5-4f9e-a445-f73b1142efd4)

Reverse lookup *sometimes* working:
![image](https://github.com/user-attachments/assets/bc541c98-1b73-41fb-85e4-dd18781909e0)
