### ISSUE TITLE
[Feature Request] Add ability to point to an existing configuration file

### ISSUE THREAD

**Issue by kb9gxk** [nextdns/nextdns#961]
While I can only attest to being on the Unifi consoles here, can the installer be made so we can point it to an existing backed-up config file and have it use that instead of asking all the installation questions?

**Comment by rs** [comment]
That's already how it works.

**Comment by kb9gxk** [comment]
Im referring to the ability to reference a config file on install/reinstall for the UniFi so that it won't ask the install questions and just use the configuration file that already exists.

**Comment by rs** [comment]
Copy the configuration in `/data/nextdns.conf` prior to installation.
