### ISSUE TITLE
Error in wiki directions for manual install on Alpine

### ISSUE THREAD

**Issue by claycooper** [nextdns/nextdns#965]
The [manual install ](https://github.com/nextdns/nextdns/wiki/Alpine-Linux-Based-Distribution#manual-install) directions fail with a curl error because the apk repo list is being overwritten instead of appended to.

The line:
`echo https://repo.nextdns.io/apk | sudo tee /etc/apk/repositories >/dev/null`

should be:
`echo https://repo.nextdns.io/apk | sudo tee -a /etc/apk/repositories >/dev/null`

**Comment by RPMozley** [comment]
@rs Diff for the edits required for this issue + replacing old '-config' with newer '-profile' option.
[nextdns.wiki.diff.txt](https://github.com/user-attachments/files/17822515/nextdns.wiki.diff.txt)
(can provide whole .md file if requested)

**Comment by RPMozley** [comment]
@rs Sorry to bother you again but you forgot to add the "-a" (append) option to the "sudo tee" command. Without it the command will overwrite an existing file, losing any other set repos.

**Comment by rs** [comment]
Added, thanks for the heads up.
