### ISSUE TITLE
Support devices identification in latest Ubiquiti custom DNS implementation

### ISSUE THREAD

**Issue by sanyer** [nextdns/nextdns#966]
Latest UniFi Network Application version [8.4.59](https://community.ui.com/releases/UniFi-Network-Application-8-4-59/d3ba4443-ad36-4566-b1e6-2d21d8b4f225) supports adding custom server option.
It looks like this:
![image](https://github.com/user-attachments/assets/c33419f9-a2db-4b95-b1db-abb89ef36ee1)
 
To configure it I used DNSCrypt configuration example from my.nextdns.io page.

Can this setup support devices identification?
If you need any extra info, let me know, I will check.

**Comment by rs** [comment]
It can’t and this is out of our control. I’m closing as this is not related to the CLI.

**Comment by sanyer** [comment]
Well, okay. I guess.
