### ISSUE TITLE
Asus Merlin: DNS53 leak. Nextdns CLI should redirect udp/tcp queries to port 53 to the router itself.

### ISSUE THREAD

**Issue by catfluoride** [nextdns/nextdns#967]
While using nextdns CLI, DNS53 (plain DNS) queries done by clients don't appear in nextdns logs and thus bypass nextdns CLI.

Assuming 192.168.0.1 as the router's IP, adding these `iptables` rules manually block this behavior i.e., all queries are redirected to nextdns CLI 

```
iptables -A PREROUTING ! -s 192.168.0.1/32 -i br0 -p udp -m udp --dport 53 -j DNAT --to-destination 192.168.0.1
iptables -A PREROUTING ! -s 192.168.0.1/32 -i br0 -p tcp -m tcp --dport 53 -j DNAT --to-destination 192.168.0.1
```

I suggest an option for nextdns CLI to query the router's LAN IP and set these `iptables` rules automatically, upon activation.

Using DNS Director on AsusMerlin is not a satisfactory workaround, as it blocks DoT and devices using DoT on the LAN loose connectivity.

This has been reported by myself elsewhere: https://help.nextdns.io/t/q6ytjg4.

Thanks a lot in advance for your attention.

**Comment by rs** [comment]
Manipulating firewall rules in the CLI would be challenging as each OS/router might have their own rules managed by a different system. There is a high risk of bad interactions.

I would suggest to install those rules into your firewall either using router's firewall interface or via a custom script.

**Comment by catfluoride** [comment]
Thanks. I hoped it wasn't so challenging for an apparently simple change, but I see I haven't take in account a lot of things..

Closing this.
