### ISSUE TITLE
CLI Client randomly stopping

### ISSUE THREAD

**Issue by kxavier23** [nextdns/nextdns#968]
**Context**
 - CLI Version: 1.43.5
 - Platform: UNIFI

The CLI client is randomly stopping.  The only way I can get it going again is to reinstall the client.

INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.43.5
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.2.4).
0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.
Hit:1 https://deb.debian.org/debian bullseye InRelease
Get:2 https://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:3 https://deb.debian.org/debian bullseye-backports InRelease [49.0 kB]
Get:4 https://security.debian.org/debian-security bullseye-security InRelease [27.2 kB]
Get:5 https://repo.nextdns.io/deb stable InRelease [8490 B]
Get:6 https://apt-beta.artifacts.ui.com bullseye InRelease [9549 B]
Hit:7 https://apt.artifacts.ui.com bullseye InRelease
Hit:8 https://apt-release-candidate.artifacts.ui.com bullseye InRelease
Get:9 https://security.debian.org/debian-security bullseye-security/main arm64 Packages [282 kB]
Get:10 https://repo.nextdns.io/deb stable/main arm64 Packages [426 B]
Get:11 https://apt-beta.artifacts.ui.com bullseye/beta arm64 Packages [62.7 kB]
Fetched 484 kB in 2s (194 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 40 not upgraded.
Need to get 2967 kB of archives.
After this operation, 7143 kB of additional disk space will be used.
Get:1 https://repo.nextdns.io/deb stable/main arm64 nextdns arm64 1.43.5 [2967 kB]
Fetched 2967 kB in 1s (3838 kB/s)
Selecting previously unselected package nextdns.
(Reading database ... 121697 files and directories currently installed.)
Preparing to unpack .../nextdns_1.43.5_arm64.deb ...
Unpacking nextdns (1.43.5) ...
Setting up nextdns (1.43.5) ...
NextDNS installed and started using ubios init
NextDNS Profile ID (default=e3d7fd):
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: y
Make NextDNS CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Note that enabling this feature will disable dnsmasq for DNS to avoid double
caching.
Enable caching? [Y|n]: y
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on your LAN hosts without having to wait for their cache to expire.
Enable instant refresh? [Y|n]: y
NextDNS installed and started using ubios init

Congratulations! NextDNS is now installed.

To upgrade/uninstall, run this command again and select the appropriate option.

You can use the NextDNS command to control the daemon.
Here are a few important commands to know:

# Start, stop, restart the daemon:
nextdns start
nextdns stop
nextdns restart

# Configure the local host to point to NextDNS or not:
nextdns activate
nextdns deactivate

# Explore daemon logs:
nextdns log

# For more commands, use:
nextdns help

**Comment by Zero6Fox** [comment]
Also having the same issue

**Comment by Craigeryjohn** [comment]
Also noticed this. Version 1.43.5 on an Asus AXE11000 running Merlin. Worked fine for years, but suddenly it just stops working. Takes several re-installs to begin working again.
