### ISSUE TITLE
Listening on non-standard port not supported

### ISSUE THREAD

**Issue by jakobod** [nextdns/nextdns#97]
I'm trying to get this daemon to bind to 0.0.0.0:5353 as suggested in the sample config file from the readme.md.
When I restart the service I get this output and the dns proxy is not reachable.
```
Mar 04 00:05:23 xxx nextdns[10970]: Starting NextDNS 1.4.33/linux on :5353
Mar 04 00:05:23 xxx nextdns[10970]: Listening on TCP/:5353
Mar 04 00:05:23 xxx nextdns[10970]: Listening on UDP/:5353
Mar 04 00:05:28 xxx nextdns[10970]: Activating
Mar 04 00:05:28 xxx nextdns[10970]: Activate: activate: :5353: non 53 port not supported
```
Am I missing something here? Why is there a config option to listen on a non-standard port, but then the logs state `non 53 port not supported`?

**Comment by rs** [comment]
Activate would set 127.0.0.1 in the /etc/resolv.conf for instance. A non 53 port is not supported by /etc/resolv.conf, so nextdns can not auto activate such configuration. You'll have to set it up manually.

**Comment by jakobod** [comment]
I see, my bad! Thank you for the quick answer! :+1:

**Comment by axeloz** [comment]
> Activate would set 127.0.0.1 in the /etc/resolv.conf for instance. A non 53 port is not supported by /etc/resolv.conf, so nextdns can not auto activate such configuration. You'll have to set it up manually.

Hi @rs I don't get what you mean "set it up manually". Thanks
