### ISSUE TITLE
Unifi Express - Failed to Start Unifi after install NextDNS and Rebook

### ISSUE THREAD

**Issue by Gustavo-FS** [nextdns/nextdns#978]
Hi

I Have a bug after install nextdns on Unifi Express and Reboot the Device the Unifi Web interface not Start and i have a message on display to reboot device 

Is nextdns interfere on Unifi Express anyone have this bug?

 - CLI Version: Last Version 1.43.5
 - Unifi Express Firmware version: v4.0.9

I Dont have any issue detect on install nextdns 

Last login: Tue Oct 15 04:02:59 2024 from 192.168.1.133
root@UniFi-Express:~# sh -c 'DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.43.5
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
DEBUG: Using deb install type
Reading package lists... Done
Building dependency tree... Done
apt-transport-https is already the newest version (2.2.4).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
Hit:1 https://deb.debian.org/debian bullseye InRelease
Get:2 https://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:3 https://deb.debian.org/debian bullseye-backports InRelease [49.0 kB]
Get:4 https://security.debian.org/debian-security bullseye-security InRelease [27.2 kB]
Get:5 https://repo.nextdns.io/deb stable InRelease [8490 B]
Get:6 https://apt.artifacts.ui.com bullseye InRelease [14.9 kB]
Get:7 https://security.debian.org/debian-security bullseye-security/main arm64 Packages [298 kB]
Get:8 https://repo.nextdns.io/deb stable/main arm64 Packages [426 B]
Get:9 https://apt.artifacts.ui.com bullseye/release arm64 Packages [50.3 kB]
Fetched 492 kB in 6s (79.6 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
Need to get 2967 kB of archives.
After this operation, 7143 kB of additional disk space will be used.
Get:1 https://repo.nextdns.io/deb stable/main arm64 nextdns arm64 1.43.5 [2967 kB]
Fetched 2967 kB in 4s (726 kB/s)
Selecting previously unselected package nextdns.
(Reading database ... 45995 files and directories currently installed.)
Preparing to unpack .../nextdns_1.43.5_arm64.deb ...
Unpacking nextdns (1.43.5) ...
Setting up nextdns (1.43.5) ...
NextDNS installed and started using ubios init
DEBUG: Start configure
DEBUG: Get profile ID
NextDNS Profile ID: db6c34]
ERROR: Invalid profile ID.

ID format is 6 alphanumerical lowercase characters (example: 123abc).
Your ID can be found on the Setup tab of https://my.nextdns.io.

NextDNS Profile ID: XXXXXX
DEBUG: Add arg -profile=XXXXXX
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: y
DEBUG: Add arg -report-client-info=true
DEBUG: Add arg -setup-router=true
Make NextDNS CLI cache responses. This improves latency and reduces the amount
of queries sent to NextDNS.
Note that enabling this feature will disable dnsmasq for DNS to avoid double
caching.
Enable caching? (y/n): y
DEBUG: Add arg -cache-size=10MB
Instant refresh will force low TTL on responses sent to clients so they rely
on CLI DNS cache. This will allow changes on your NextDNS config to be applied
on your LAN hosts without having to wait for their cache to expire.
Enable instant refresh? (y/n): y
DEBUG: Add arg -max-ttl=5s
NextDNS installed and started using ubios init

Congratulations! NextDNS is now installed.

I have this error on NextDNS after boot and the interface web not start

Oct 15 04:37:03 UniFi-Express systemd[1]: nss-lookup.target: Found dependency on unifi-core.service/start
Oct 15 04:37:03 UniFi-Express systemd[1]: nss-lookup.target: Found dependency on nginx.service/start
Oct 15 04:37:03 UniFi-Express systemd[1]: nss-lookup.target: Found dependency on nss-lookup.target/start
Oct 15 04:37:03 UniFi-Express systemd[1]: nss-lookup.target: Job nss-lookup.target/start deleted to break ordering cycle starting with nss-lookup.target/start
Oct 15 04:37:03 UniFi-Express systemd[1]: nextdns.service: Found ordering cycle on unifi.service/start
Oct 15 04:37:03 UniFi-Express systemd[1]: nextdns.service: Found dependency on unifi-core.service/start
Oct 15 04:37:03 UniFi-Express systemd[1]: nextdns.service: Found dependency on nginx.service/start
Oct 15 04:37:03 UniFi-Express systemd[1]: nextdns.service: Found dependency on nss-lookup.target/start
Oct 15 04:37:03 UniFi-Express systemd[1]: nextdns.service: Found dependency on nextdns.service/start
Oct 15 04:37:03 UniFi-Express systemd[1]: nextdns.service: Unable to break cycle starting with nextdns.service/start

**Comment by jeffgogel** [comment]
My Unifi Express was doing the same so I downgraded from v4.0.9 to v4.0.4.  Now I have to restart the unifi service via SSH after reboots to make the Unifi web portal available... 

service unifi stop
service unifi start

But NextDNS is still not working on the Express.  I use the exact same config (with different NextDNS profile id's) on my UDM Pro  without any problems.  That one has a different WAN IP so I can't use the same profile id's.

**Comment by Material-Design** [comment]
Having the same issue on my UDM pro unfiOS 4.1.5. 

Crashed the OS completely- no internet. Web interface down. Reboots didn't bring any interface or network up. 

It resolved itself overnight after 7 hours of downtime- my SSH was disabled so couldn't comment on any logs produced.

On being back online, NextDNS was in an unknown status and had to be started manually.

**Comment by afonsosantos** [comment]
Hi there,

Just adding to the issue - same happened here today using my Unifi Express, on the latest NextDNS and Unifi OS version.
I had to SSH into the gateway and run `nextdns uninstall` to be able to access the UI.

Thanks.

**Comment by RobertCSternberg** [comment]
Reporting another issue with the unifi Express. Unresolved.

**Comment by svengjohnson** [comment]
@Gustavo-FS @afonsosantos @RobertCSternberg NextDNS is natively supported on UniFi via DnsCrypt. 

Check this out to see if it helps - https://github.com/nextdns/nextdns/issues/985

**Comment by RobertCSternberg** [comment]
I also manage a dream machine router and this issue occurs there too. Any update on a resolution?

**Comment by rs** [comment]
Please try again with 1.44.3.
