### ISSUE TITLE
luci-app-nextdns broken on latest SNAPSHOT OpenWRT

### ISSUE THREAD

**Issue by Mile-Lile** [nextdns/nextdns#981]
**Context**
 - CLI Version: 1.43.5
 - Platform: OpenWrt SNAPSHOT / LuCI Master 24.297.79487~591911d/mediatek/filogic/Xiaomi Mi Router AX3000T (OpenWrt U-Boot layout)

after resseting my OpenWRT router to defaults and installing luci-app-nextdns with opkg update && install luci-app-nextds I get error:

`Fri Oct 25 18:35:26 2024 daemon.err nextdns[1765]: Setting up openwrt router: open /tmp/dnsmasq.d/nextdns.conf: no such file or directory`

It started lastnight when I upgraded latest snapshot, but then today I did firstboot and all the same. I didn't deleted this directory myself

![image](https://github.com/user-attachments/assets/c12a8863-86f4-4510-883c-69cb81f24a95)

**Comment by Mile-Lile** [comment]
it is related to https://github.com/openwrt/openwrt/issues/10625

**Comment by Mile-Lile** [comment]
`root@AX3000T:~# cat /var/etc/dnsmasq.conf.*
# auto-generated config file from /etc/config/dhcp
conf-file=/etc/dnsmasq.conf
dhcp-authoritative
domain-needed
localise-queries
read-ethers
enable-ubus=dnsmasq
expand-hosts
bind-dynamic
local-service
cache-size=1000
edns-packet-max=1232
domain=lan
local=/lan/
addn-hosts=/tmp/hosts
dhcp-leasefile=/tmp/dhcp.leases
resolv-file=/tmp/resolv.conf.d/resolv.conf.auto
stop-dns-rebind
rebind-localhost-ok
dhcp-broadcast=tag:needs-broadcast
conf-dir=/tmp/dnsmasq.cfg01411c.d
user=dnsmasq
group=dnsmasq


dhcp-ignore-names=tag:dhcp_bogus_hostname
conf-file=/usr/share/dnsmasq/dhcpbogushostname.conf


bogus-priv
conf-file=/usr/share/dnsmasq/rfc6761.conf
dhcp-range=set:lan,192.168.1.100,192.168.1.249,255.255.255.0,12h
no-dhcp-interface=wan

`

**Comment by Mile-Lile** [comment]
@rs did I missconfigured it?

**Comment by xize** [comment]
hmm this is strange, I got the opposite effect.

with my own compiled snapshot from openwrt/openwrt@a2aabc9a7a4ec8a66477fbdde84a73b5942b460e i do see it being copied over to ``/tmp/dnsmasq.d`` but this still breaks.

when I use ``ls /tmp``

I see this:
```
dnsmasq.cfg01411c.d
dnsmasq.d
```

if i copy the  contents of ``/tmp/dnsmasq.d`` to ``/tmp/dnsmasq.cfg01411c.d`` it works again, my suspicioun is that it became uci'd when they added support for multiple dnsmasq instances.

**Comment by IamRPDev** [comment]
This isn't a luci-app-nextdns error,  its just a nextdns service issue because they user /tmp/dnsmasq.d/ to place their alt config. Unfortionatly it looks like openwrt changed their implementation of dnsmasq. Please refer to 
`https://github.com/openwrt/openwrt/pull/14975/files` 
The change was committed on October 20th. This change implements different sub directories for each DNS/DHCP instance.

**Comment by rs** [comment]
Any recommendation how to automate custom dnsmasq configuration with this new implementation?

**Comment by IamRPDev** [comment]
My workaround:

Edit /etc/rc.local to include a command to make /tmp/dnsmasq.d persistent on reboot

`mkdir /tmp/dnsmasq.d/`

Then I edit the variable EXTRACONFFILE  /etc/init.d/dnsmasq to point to /tmp/dnsmasq.d/nextdns.conf

`EXTRACONFFILE="/tmp/dnsmasq.d/nextdns.conf"`

Reboot or issue the mkdir command and restart nextdns.

They do expect the developers to adapt to the new convention and the EXTRACONFFILE variable is temporary and only available to one program. They left a comment in the code I previously referenced.

# EXTRACONFFILE allows new dnsmasq parameters before they are natively handled in this init file

**Comment by rs** [comment]
How do you learn (as a service), the path of the new config directory?

**Comment by IamRPDev** [comment]
Quick update. Might want to hold off on anything, this is waiting for approval as a fix. 

https://github.com/openwrt/openwrt/pull/16806

**Comment by rs** [comment]
Thanks for the heads up

**Comment by IamRPDev** [comment]
@rs Following up on this issue, it looks like they plan on moving forward without a fix as of now. This change has also been merged into the new 24.10-rc, per issue #16806 above.

I will be flashing 24.10-rc2 tonight. I will investigate further, if I see differently I'll let you know.

**Comment by IamRPDev** [comment]
So looks like you can use "uci get dhcp.@host[0].instance" to get the instance name to fill in for the temp directory /tmp/dnsmasq.INST.conf. Run the instance number through a loop til it outputs not found and hit every instance?

The extraconf variable still exists in the /etc/init.d/dnsmasq file, it sets for all dhcp instances. But other projects might step on each others feet using it. But as an end user its the easiest fix to implement as an end user.

**Comment by rs** [comment]
Is there a thread where this is discussed?

**Comment by xize** [comment]
> Is there a thread where this is discussed?

I think best is here this issue https://github.com/openwrt/openwrt/pull/16806 there is also a new PR by systemcrash, https://github.com/openwrt/openwrt/pull/16890 regarding dnsmasq.d.

**Comment by IamRPDev** [comment]
I don't completely understand the benefit. Do they run as separate processes as well? I would assume this would give you isolated DNS caching and configuration segmentation per network. I wrote a one line command fix for anyone that may find this. The `dhcp.@dnsmasq[0]` is a pointer to the name such as `dhcp.cfg01411c.confdir`. You should be able to apply this to any instance if you want them to have the same configurations, such as `dhcp.@dnsmasq[1].confdir` and so on.

**Here is a one liner to set the default dhcp instance back to `/tmp/dnsmasq.d` and restart the services to get the job done.**

`uci set dhcp.@dnsmasq[0].confdir='/tmp/dnsmasq.d' ; uci commit dhcp ; service dnsmasq reload ; service nextdns restart`

Thanks for taking the time to look at it! Things may change, your mileage may vary, I am not a lawyer in real life I just play one on TV. I just hate the lack of care shown to the change that's caused a loss of synergy between two products I love.

**Comment by Mile-Lile** [comment]
I solved it easily. Stopped/unsubscribed from NextDNS (which I loved very much), installed luci-app-adblock and luci-app-https-dns-proxy and luci-app-wifischedule... with uncensored Quad 9 (free of pay) on cheap Xiaomi ax3000t (40 euro) router... I have everything I had with NextDNS and I`m very satisfied because it is cheaper :)
