### ISSUE TITLE
NextDNS app installs and runs, but doesn't work (Windows 10)

### ISSUE THREAD

**Issue by ezxpro** [nextdns/nextdns#982]
**Context**
 - CLI Version:  3.0.13 (latest stable as of now)
 - Platform: Windows 10 22H2 x64

&lt;Describe the bug>
Installs runs and configures normally, but it simply doesn't work:

![image](https://github.com/user-attachments/assets/535b1e8a-01ec-493b-aa49-ef24b2bd6748)
![image](https://github.com/user-attachments/assets/bff302f2-994a-4364-8e9a-4917ae3f1789)

Same goes for Yoga DNS

**Comment by rs** [comment]
Please report this on https://help.nextdns.io
