### ISSUE TITLE
OpenWRT 24rc2 

### ISSUE THREAD

**Issue by skyweir** [nextdns/nextdns#984]
**Context**
 - CLI Version: latest
 - Platform: OpenWRT

&lt;Describe the bug> Status running but the router is not utilizing NextDNS.

system log file error: Setting up openwrt router: open /tmp/dnsmasq.d/nextdns.conf: no such file or directory

**Comment by rs** [comment]
Likely a dup of https://github.com/nextdns/nextdns/issues/981

**Comment by skyweir** [comment]
Agree. I'll pull this duplicate
