### ISSUE TITLE
Rqeuest for the Wiki page update - UniFi supports NextDNS natively since Network Application 8.4.62 via DnsCrypt.

### ISSUE THREAD

**Issue by svengjohnson** [nextdns/nextdns#985]
Hi there,

I know this is not a bug report or in any way related to the NextDNS Client, but it's not possible to submit a PR requesting changes to the wiki.

There are some bug reports like this however - https://github.com/nextdns/nextdns/issues/978

Installing custom applications on UniFi OS is officially unsupported. It works, and that's great, but there's a better way.

Since Unifi Network 8.4.62 (although not explicitly mentioned in the Release Notes), it's possible to configure custom DnsCrypt servers.
https://community.ui.com/releases/UniFi-Network-Application-8-4-62/40240312-bb43-4648-adab-5b05f3d4354e

This uses DnsCrypt under the hood.

So all you actually need to do on UniFi, is follow the Linux -> DnsCrypt instructions.

![image](https://github.com/user-attachments/assets/9141760c-4f95-4dc0-ac97-96129a7cd56c)

Then you navigate to Security -> Protection (on 9.0.101, might be different on earlier versions), select "Encrypted DNS", click "Custom", and just copy the Server Name and SDNS Stamp.

![image](https://github.com/user-attachments/assets/5ff2b593-ee5b-4597-8694-3643aff11cfd)
![image](https://github.com/user-attachments/assets/9d8d03fe-5a90-4a93-a453-0a9dfd33f899)

And that's it!

I think it would be beneficial to update the Wiki page with this information, as there is an officially supported flow for using NextDNS on UniFi. While it doesn't use the NextDNS client, DnsCrypt is officially supported by NextDNS.

While Device identification & conditional profiles obviously won't work with this approach, DNS itself will.

Thanks!

EDIT: forgot to link the wiki page--it's this one: https://github.com/nextdns/nextdns/wiki/UnifiOS

**Comment by svengjohnson** [comment]
cc: @rs, as you seem to be the owner of the Wiki page.

**Comment by rs** [comment]
This wiki is about how to install the CLI on various devices. It could be confusing to add other types of instructions here.

**Comment by aad4321** [comment]
Thanks for this but once configured does next dns logs show the actual device? I am only getting my WAN IP for everything.

**Comment by rs** [comment]
Not without installing the CLI.
