### ISSUE TITLE
DNS-over-TLS/QUIC Support for CLI

### ISSUE THREAD

**Issue by jhysler** [nextdns/nextdns#988]
Hello NextDNS team,

I do not believe that there is a way to use DoT/QUIC using the CLI. Is this feature currently planned? Would love to see it given the performance improvements over standard DoH.

**Comment by rs** [comment]
It is not planned and there is no performance improvement to expect in this context. We will add HTTP/3 support when Go adds official support for it.

Most client implementation based on QUIC that we tested so far show degraded DNS performance due to their implementation being too young.

**Comment by jhysler** [comment]
Thank you for the quick response. That is very encouraging to hear that HTTP/3 support is planned!
