### ISSUE TITLE
Wiki page broken link for android 

### ISSUE THREAD

**Issue by salah-ismail93** [nextdns/nextdns#989]
**Wiki page broken link for android **
 - CLI Version: 
 - Platform: Android

&lt;Wiki page has a broken link for android > 

there is no info about install next dns on android since the URL on play store is broken

**Comment by eboermans** [comment]
You can find solution on https://my.nextdns.io/
Private DNS
Android 9 or higher
1. Go to Settings → Network & internet → Advanced → Private DNS.
2. Select the Private DNS provider hostname option.
3. Enter USERID.dns.nextdns.io and hit Save.

**Comment by rs** [comment]
I removed android and ios, they shouldn't be on this wiki. Thanks for the heads up.
