### ISSUE TITLE
OpenWRT Issue reboot issue

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/nextdns#99]
Device ->
AR750S Glinet
Mudy Glinet

The client cli loses its configuration once the router has restarted, go back to the initial settings

**Comment by rs** [comment]
can you execute "nextdns config" before and after the restart?

**Comment by scafroglia93** [comment]
Device -> Mudy

Access, currently the dns as described are those of the 4G operator

nextdns config ->
log-queries false
report-client-info false
bogus-priv true
auto-activate true
timeout 5s
setup-router true
listen localhost:53
config 6ad58f
detect-captive-portals false
hardened-privacy true
use-hosts true

**Comment by scafroglia93** [comment]
There are some news about this bug ?
