### ISSUE TITLE
Can't install NextDNS CLI on Alpine or Ubuntu

### ISSUE THREAD

**Issue by scottmckenzie** [nextdns/nextdns#990]
**Context**
 - 1.44.0
 - Alpine + Ubuntu

I have tried a manual install on both Alpine and Ubuntu. Neither work due to an issue with the repo. Both URLs are returning an HTTP 404. This is also affecting the installation script (https://nextdns.io/install) which fails to install for the same reason.
```shell
> curl https://repo.nextdns.io/apk
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>apk</Key><RequestId>GG6D0BZMY72RP2WR</RequestId><HostId>eKdLz94PdUAnUJRmrv4MYFDngycQaHkSi5tUn1nCXvFDGOIy3KrSBB2wwCVA+iRGpVWyUzK8IW8=</HostId></Error>
``` 

```shell
> curl https://repo.nextdns.io/deb
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>deb</Key><RequestId>W6Q0Z3ND9NRPBWRY</RequestId><HostId>/nRy3JbHYXCyfCgNz9roDNkc9KQAT2E2bSCddcJNnxqtewOz7qXKFKNKKK1Feoj3L+L1GglDyZ0GGOGP2Fi6MYSAt67LerS2yWLsA4oQRC8=</HostId></Error>
```

**Comment by marcoamtz** [comment]
Not sure why, but at least for alpine by looking at this commit, looks intentional: https://github.com/nextdns/nextdns/commit/a64ae4d31299b2ddcd86abf7464552bb820d09ca

**Comment by vincentbernat** [comment]
The repository is backed by S3, there is no listing of packages available, hence the 404. For Ubuntu, the repository seems OK. For Alpine, the fix is in progress.
