### ISSUE TITLE
Doesn't work with OpenWrt 24.10.0-rc2

### ISSUE THREAD

**Issue by AppleFanBoi** [nextdns/nextdns#992]
**Context**
 - CLI Version: Latest
 - Platform: Openwrt

When I install it using : 

opkg update && opkg install curl

sh -c "$(curl -sL https://nextdns.io/install)"

It does not install the latest version 

I can't upgrade it via the cli as well 

Please fix

**Comment by AppleFanBoi** [comment]
root@OpenWrt:~# sh -c "$(curl -sL https://nextdns.io/install)"
INFO: OS: openwrt
INFO: GOARCH: mipsle_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/sbin/nextdns
INFO: INSTALL_RELEASE: 1.44.0
u) Upgrade NextDNS from 1.43.5 to 1.44.0
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): r
INFO: Uninstalling NextDNS...
Removing package nextdns from root...
Error: remove /etc/init.d/nextdns: no such file or directory
You can force removal of packages with failed prerm scripts with the option:
        --force-remove
No packages removed.
Collected errors:
 * pkg_run_script: package "nextdns" prerm script returned status 1.
 * opkg_remove_pkg: not removing package "nextdns", prerm script failed
ERROR: uninstall: exit 0
u) Upgrade NextDNS from 1.43.5 to 1.44.0
c) Configure NextDNS
r) Remove NextDNS
e) Exit

Can't even uninstall it

**Comment by AppleFanBoi** [comment]
u) Upgrade NextDNS from 1.43.5 to 1.44.0
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/ramips/mt7621/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/ramips/mt7621/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/ramips/mt7621/kmods/6.6.63-1-fc5e5f442ac8adc9e18e3d9c5d0803a5/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_kmods
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/ramips/mt7621/kmods/6.6.63-1-fc5e5f442ac8adc9e18e3d9c5d0803a5/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/telephony/Packages.sig
Signature check passed.
u) Upgrade NextDNS from 1.43.5 to 1.44.0
c) Configure NextDNS

Can't upgrade it either

**Comment by AppleFanBoi** [comment]
INFO: Uninstalling NextDNS...
Removing package nextdns from root...
Not deleting modified conffile /etc/config/nextdns.
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/ramips/mt7621/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/ramips/mt7621/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/ramips/mt7621/kmods/6.6.63-1-fc5e5f442ac8adc9e18e3d9c5d0803a5/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_kmods
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/ramips/mt7621/kmods/6.6.63-1-fc5e5f442ac8adc9e18e3d9c5d0803a5/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/telephony/Packages.sig
Signature check passed.
Installing nextdns (1.43.5-r1) to root...
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mipsel_24kc/packages/nextdns_1.43.5-r1_mipsel_24kc.ipk
Configuring nextdns.
NextDNS installed and started using procd init
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/nextdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/nextdns-opkg.
Install the GUI? [Y|n]:

After many uninstall attempt, it uninstalled but check out how it installs 1.43.5-r1 instead of the latest version.

**Comment by IamRPDev** [comment]
I just checked the commit for the new package, it is still waiting to be approved.

**Comment by rs** [comment]
Will be fixed on next revision

**Comment by AppleFanBoi** [comment]
> Will be fixed on next revision

https://forum.openwrt.org/t/nextdns-package-needs-update/219179/3
